### ISSUE TITLE
Where in the world is the def file

### ISSUE THREAD

**Issue by ianclarke1422** [MicrosoftDocs/cpp-docs#1000]
As always, just a little information, but not the full answer.
Where does one find the .def file? How is it created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142bb8a9-d18a-1e94-653d-c5d4c8a64ecc
* Version Independent ID: 40d6607d-8df0-1185-dc0a-fac2c3d4fab5
* Content: [Linker Tools Warning LNK4070](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4070?view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4070.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4070.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ianclarke1422 
If the linker created a .DEF file or a .EXP file, I expect it should be in the output directory with the object files. That directory depends on your build configuration.
