### ISSUE TITLE
Insufficient info

### ISSUE THREAD

**Issue by ianclarke1422** [MicrosoftDocs/cpp-docs#1001]
What is .EXP and where does one find it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142bb8a9-d18a-1e94-653d-c5d4c8a64ecc
* Version Independent ID: 40d6607d-8df0-1185-dc0a-fac2c3d4fab5
* Content: [Linker Tools Warning LNK4070](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4070?view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4070.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4070.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ianclarke1422 
For information, see [Building an import library and export file](https://docs.microsoft.com/en-us/cpp/build/reference/building-an-import-library-and-export-file?view=vs-2019). We assume people who run into this particular error are familiar with this material, and aren't looking for a tutorial here.

**Comment by ianclarke1422** [comment]
Thank you for the quick reply, and the link below, but I was able to figure it out on my own, by referencing other internet posts.

I find it surprising that you think that people who run into errors are not looking for a tutorial on how to fix them? If I know how the system works and how to fix it, why would I ever reference the documentation?  Having a page that more or less reiterates the output from the linker is really pretty useless.

But really, thanks for the quick reply.  I was surprised to receive it!
