### ISSUE TITLE
ZI will change the type of __LINE__ based on context

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#1002]
In the [ZI documentation](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019#feedback) there is a warning about using \_\_LINE__ in a context that requires a constant:

> The /ZI option is also incompatible with use of the \_\_LINE__ predefined macro; code compiled with /ZI cannot use \_\_LINE__ as a non-type template argument, although \_\_LINE__ can be used in macro expansions.

I think that it should also be mentioned that the type of \_\_LINE__ will change depending on context. It seems to be an int or a long depending on where it is used. Ex:

https://godbolt.org/z/DlOqtV
cl -c -ZI x.cpp
```
#include <type_traits>

static_assert(std::is_same_v<decltype(__LINE__), int>, "__LINE__ is not int");

void f()
{
    static_assert(std::is_same_v<decltype(__LINE__), long>, "__LINE__ is not long");
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 429cc6e8-2120-8a0f-eadb-0bc926d5bb5c
* Version Independent ID: d5a3132e-9f84-0cb3-446a-9703f65ba782
* Content: [/Z7, /Zi, /ZI (Debug Information Format)](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019#feedback)
* Content Source: [docs/build/reference/z7-zi-zi-debug-information-format.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/z7-zi-zi-debug-information-format.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
