### ISSUE TITLE
Mention cpp targets default as well

### ISSUE THREAD

**Issue by NN---** [MicrosoftDocs/cpp-docs#1004]
Compiler (cl.exe) defaults and msbuild targets defaults are slightly different.
For instance, this settings is enabled by default through msbuild targets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df24f63-6fc8-25e3-91df-5e9f576ec2d8
* Version Independent ID: 3e4af063-b629-363f-30c2-0f30e030cf66
* Content: [/Zc:inline (Remove unreferenced COMDAT)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-inline-remove-unreferenced-comdat?view=vs-2019#feedback)
* Content Source: [docs/build/reference/zc-inline-remove-unreferenced-comdat.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zc-inline-remove-unreferenced-comdat.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by asklar** [comment]
This is set by MSBuild through the RemoveUnreferencedCodeData metadata

**Comment by mikeblome** [comment]
Thanks @NN and @asklar this topic has been updated and will publish by Sept 7.
