### ISSUE TITLE
Incorrect complex types names

### ISSUE THREAD

**Issue by mshabunin** [MicrosoftDocs/cpp-docs#1006]
Complex types are incorrectly named `_FComplex, _DComplex, _LComplex` ([here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=vs-2019#types-used-in-complex-math)), while other pages (e.g. related function [references](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/creal-crealf-creall?view=vs-2019)) use correct types: `_Fcomplex, _Dcomplex, _Lcomplex`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 837f9388-5530-798a-5b6d-aaa1a5c0e285
* Version Independent ID: fc31aaec-0539-bfc5-7d24-de55eb1d4a4c
* Content: [C complex math support](https://docs.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=vs-2019)
* Content Source: [docs/c-runtime-library/complex-math-support.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/complex-math-support.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mshabunin 
Yes, those are typos, thanks for spotting them. A fix is in the works.

In the future, [you are welcome to make trivial fixes like this one yourself](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents). To make it a little easier to follow, we also made a [video demo of fixing a typo and submitting a pull request](https://www.youtube.com/watch?v=V3h3X08A0DY). We review all PRs and usually get them approved within a day or two, with occasional exceptions.

**Comment by corob-msft** [comment]
Finally getting around to closing this, as the fixes are live.
