### ISSUE TITLE
CMakeSettings_schema.json camelcase typo (remotePreBuildCommand vs remotePrebuildCommand) 

### ISSUE THREAD

**Issue by bs444** [MicrosoftDocs/cpp-docs#1009]
The article mentions:
You can use these optional settings for more control:

```json
{
      "remotePreBuildCommand": "",
      "remotePreGenerateCommand": "",
      "remotePostBuildCommand": "",
}
```

But the schema uses:

```json
          "remotePreGenerateCommand": {
            "type": "string",
            "description": "The command to run before running CMake to parse the CMakeLists.txt."
          },
          "remotePrebuildCommand": {
            "type": "string",
            "description": "Command to run on remote machine before building."
          },
          "remotePostbuildCommand": {
            "type": "string",
            "description": "Command to run on remote machine after building."
          },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4cb5d3-4f66-32e8-8b74-522738eb5215
* Version Independent ID: ae7afcc9-5c5e-6dc5-cd6a-9b1aa25ac149
* Content: [CMake predefined configuration reference](https://docs.microsoft.com/en-us/cpp/build/cmake-predefined-configuration-reference?view=vs-2019#feedback)
* Content Source: [docs/build/cmake-predefined-configuration-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-predefined-configuration-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@bs444 fixed and thank you. I wish the schema were consistent but in this case I think it's better to just change the doc. Fix should appear tomorrow morning.
