### ISSUE TITLE
Incorrect xref for linker option DRIVER

### ISSUE THREAD

**Issue by ellerkelso** [MicrosoftDocs/cpp-docs#101]
In the [linker option DRIVER](https://docs.microsoft.com/en-us/cpp/build/reference/driver-windows-nt-kernel-mode-driver) material, the section "To set this linker option programmatically" has an incorrect xref:

```
1.  See `P:Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.driver`.  
```

**Comment by ellerkelso** [comment]
Would open a pull request for this, but I can't seem to get the docfx to resolve an xref correctly. Perhaps someone familiar with the feature can make the change. Or provide a pointer as to what else is required and I can implement.

For example [linker option DELAYLOAD](https://docs.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import) has an xref that resolves correctly:
`-   See <xref:Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.DelayLoadDLLs%2A>.  `

Following that pattern in DRIVER unfortunately doesn't resolve to a link in a local build. Instead it seems to have no resolution applied and ends up as raw text in the produced docs:
`-   See <xref:Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.driver%2A>.  `

Trying it without the encoded asterisk at the end has the same result (not sure what that character is about):
`-   See <xref:Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.driver>.  `

For reference, there is in fact a `VCLinkerTool.driver` property in the API docs:
https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vcprojectengine.vclinkertool.driver.aspx

**Comment by corob-msft** [comment]
Unfortunately, the xref system probably requires the customized build tool used internally by our publishing system to generate working links for preview. I don't think it's part of the stock DocFX capability. It uses custom YML files found in .zip form in the docs directory, for example. vs.140.zip, to associate the xref link with a URL. If the .NET API definition exists in the YML files, then it's safe to use in an xref link even if the preview doesn't show it working.

**Comment by ellerkelso** [comment]
OK understood. I'll follow that pattern for future changes. Thanks for your pull request.

I see there are `VCLinkerTool.yml` files in 2 of the zip files:
* `vs.110.zip` - `Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.yml`
* `vs.140.zip` - `Microsoft.VisualStudio.VCProjectEngine.VCLinkerTool.yml`

I'm not seeing a `driver` property in either of them. They do both have the `DelayLoadDLLs` property from the working example. Is it possible the driver link is missing?

**Comment by corob-msft** [comment]
It may well be that [VCLinkerTool.driver](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.vclinkertool.driver?view=visualstudiosdk-2017) is not there in the YML. My search didn't find it, either, which means my fix will probably not fix much - yet. We've been finding a fair number of missing entries, particularly for enumeration types, and I'm told someone is looking into it. We'll probably get a new set of zip files and commit them "soon", then a new build of the whole project will pick them up and the xref links will appear as intended.
