### ISSUE TITLE
std::clamp(value, min, max) function not listed, but is implemented

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/cpp-docs#1010]
Since C++17, the C++ standard has had the function template [`T& std::clamp<T>(T& value, T& min, T& max)`](https://en.cppreference.com/w/cpp/algorithm/clamp) in `#include <algorithm>`. std::clamp() returns _value_ if it's between _min_ and _max_, _min_ if _value_ is less than _min_, or _max_ if _value_ is greater than _max_.

Microsoft's C++ library has supported std::clamp() since Visual Studio 2015.3 (VS 14.3) according to the [Visual C++ Language Conformance](https://docs.microsoft.com/cpp/overview/visual-cpp-language-conformance?view=vs-2019) page, but it's not listed on the [&lt;algorithm&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/algorithm-functions?view=vs-2019) page. Please add it there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2345d5-8891-8d5d-5a8c-b7b4382d4541
* Version Independent ID: 03684e91-dbcd-5acc-b86d-7099dac5b473
* Content: [&lt;algorithm&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/algorithm-functions?view=vs-2019)
* Content Source: [docs/standard-library/algorithm-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/algorithm-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @metathinker. This is on our backlog to do soon along with several other new types and functions. I'll leave this open until its complete.

**Comment by mikeblome** [comment]
This is documented now. thanks @metathinker

**Comment by thatfox** [comment]
I thought I was the only one experiencing these issues. 
I have both tested this with: `/C++17` and  `/C++ Latest`, yet I'm still having issues reading back the implementation. 

I saw a post [here ](https://stackoverflow.com/questions/41972588/namespace-std-has-no-member-clamp)and assumed it was just a common compiler issue, but apparently not... 

Still wondering: Anyone found a solution?

**Comment by metathinker** [comment]
> I thought I was the only one experiencing these issues.
> I have both tested this with: `/C++17` and `/C++ Latest`, yet I'm still having issues reading back the implementation.
> 
> I saw a post [here ](https://stackoverflow.com/questions/41972588/namespace-std-has-no-member-clamp)and assumed it was just a common compiler issue, but apparently not...
> 
> Still wondering: Anyone found a solution?

So, this issue is "`clamp` is there but the docs don't mention it". Based on what you wrote and the link you gave, your issue seems to be nearly the opposite: "`clamp` is supposed to be there but I can't use it."

Since `clamp` is working for others, this could be an issue specific to your configuration. I'd suggest you ask on https://developercommunity.visualstudio.com and the folks there can help you debug.
