### ISSUE TITLE
Contradiction regarding which Universal CRT libraries to specify

### ISSUE THREAD

**Issue by Mike4Online** [MicrosoftDocs/cpp-docs#1012]
For a VC++ executable, sometimes you have to manually specify the CRT libraries to link to, but Microsoft's advice on which libraries to specify is contradictory.

In the [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019#feedback) document, three sets of libraries -- **UCRT**, **vcruntime** and **cmt/msvcrt** -- are all presented as valid and current.  For example, the following is a quote from this article:

> If you link your program from the command line without a compiler option that specifies a C run-time library, the linker will use the statically linked CRT libraries: **libcmt.lib**, **libvcruntime.lib**, and **libucrt.lib**.

However, the document [Overview of potential upgrade issues (Visual C++)](https://docs.microsoft.com/en-us/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019) contradicts this by saying:

> If you were using...........You need to **_replace it_** with:
> libcmt.lib.............................libucrt.lib, libvcruntime.lib
> libcmtd.lib..........................libucrtd.lib, libvcruntimed.lib
> msvcrt.lib...........................ucrt.lib, vcruntime.lib
> msvcrtd.lib........................ucrtd.lib, vcruntimed.lib

So should the **cmt** or **msvcrt** libs be retained when manually specifying the runtime libraries to link to, as the [first article](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019#feedback), implies, or should they be dropped in favor of only specifying **UCRT** and **vcruntime**, as the [second article](https://docs.microsoft.com/en-us/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019) explicitly advises?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Mike4Online 
Good catch, there. If you tried both scenarios, using the libraries suggested by the [CRT library features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019) article would work, and the instructions in [Overview of potential upgrade issues (Visual C++)](https://docs.microsoft.com/en-us/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019) would lead to a bunch of unresolved external symbol errors. Instead of "You need to replace it with" it should say *You also need to link to*, or something similar.

**Comment by corob-msft** [comment]
The updated text is live, so I'm closing this issue.

**Comment by Mike4Online** [comment]
Colin, thanks for verifying this and revising the text so quickly.
