### ISSUE TITLE
and what is the order when there is more than one project?

### ISSUE THREAD

**Issue by pablocar80** [MicrosoftDocs/cpp-docs#1014]
From this explanation, it's not clear to me if the order is per solution or per project. So I don't know whether (A) all pre-build in a solution execute before compiling any project and all post-build after compiling all projects, or (B) each project is compiled following the sequence above, so a pre-build of one project comes after the post-build of its dependencies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e0035ba-394d-8b59-05c8-442beeb0da88
* Version Independent ID: fbcf56d2-541b-97bc-69f9-88962e08c6fe
* Content: [Understanding Custom Build Steps and Build Events](https://docs.microsoft.com/en-us/cpp/build/understanding-custom-build-steps-and-build-events?view=vs-2019)
* Content Source: [docs/build/understanding-custom-build-steps-and-build-events.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/understanding-custom-build-steps-and-build-events.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@pablocar80 thanks for the feedback. Pre-build and post-build events occur at the beginning and end of each project compilation. So the answer is (B). I have clarified the documentation.
