### ISSUE TITLE
ทำใหมาเลย

### ISSUE THREAD

**Issue by yang980** [MicrosoftDocs/cpp-docs#1015]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: f4ffbe91-9a1a-bed3-e219-a07dfe238435
* Version Independent ID: f952e396-33ca-34d4-b355-96cdb64b23c5
* Content: [CDynamicAccessor Class](https://docs.microsoft.com/th-th/cpp/data/oledb/cdynamicaccessor-class?view=vs-2019)
* Content Source: [docs/data/oledb/cdynamicaccessor-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/data/oledb/cdynamicaccessor-class.md)
* Product: **visual-cpp**
* Technology: **cpp-data**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Closed. This issue does not appear to contain any feedback.
