### ISSUE TITLE
Maximum (2048) of open files at stdio level appears wrong on W10 x64

### ISSUE THREAD

**Issue by janhec** [MicrosoftDocs/cpp-docs#1020]
I can increase the stdio open file limit to 8192 without receiving an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac712ff-ab50-25f4-ae4f-04d1b89d48ff
* Version Independent ID: 047f00f3-0eec-1177-9759-96584493cbe3
* Content: [_setmaxstdio](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/setmaxstdio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/setmaxstdio.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@janhec 
True enough. Technically, the upper limit is defined by the preprocessor macro `_NHANDLE_` defined in corecrt_internal_lowio.h in the Windows SDK sources for the UCRT. IntelliSense tells me its definition is (128 * (1 << 6)), or 8192. I have no idea how old this article is, but the limit hasn't changed since Visual Studio 2015 shipped, so it's been out of date for some time.

**Comment by janhec** [comment]
Hey Colin,
Thanks for the elaboration!
_NHANDLE_  appears to be used only in validation, but the important
bits, IOINFO_ARRAYS and IOINFO_L2E cannot be modified without recompiling
the ucrt libs, I guess.
Not that I really need to, but I would be tempted to increase IOINFO_L2E.
Long history of upgrading (I remember my second MB of ram which cost me an
arm and a leg and I had to solder if I remember correctly) tells me that
this limit has become a bit restrictive in comparison with other limits
such as the total number of handles for a proces.
But, no lives at stake here 😉
Sincerely,
Jan

**Comment by corob-msft** [comment]
The content is updated, so I'm closing this issue.

Yes, I recall soldering a 512K (K! Not even a megabyte!) memory upgrade directly onto the motherboard of my original Macintosh back in the day. I also remember when I'd build my own modified copy of the CRT from sources, to make a stripped-down version without some of the startup overhead. I suppose that's technically still possible, if you don't need the transcendentals, which don't have source for licensing reasons. There's probably a relevant OS limit on handles that would come into play. 
Best,
// Colin
