### ISSUE TITLE
mistake in code example

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1023]
Example is a constructor of CMainFrame. It has problem with the middle part between function head and function body, and it doesn't seem to make sense, because I searched the source code and didn't find those. these seem to be member variables in terms of how they are named. Even so, there is problem with the code format.
![Capture213](https://user-images.githubusercontent.com/32254161/58143390-43195280-7c7d-11e9-97a5-542580196dfc.JPG)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83228d11-7bdb-155a-d6a6-1d37532f9540
* Version Independent ID: a68da254-3bde-f474-5f1e-8e12a7bc023d
* Content: [CFrameWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cframewnd-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cframewnd-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cframewnd-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@songxia233 apologies for delated response. CMainFrame is an application-defined variable of type CFrameWnd. You could call such a variable anything you like. I added a code comment to clarify that.
