### ISSUE TITLE
code indentation issue

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1025]
There is a problem with code indentation in this document.
![tempsnipd](https://user-images.githubusercontent.com/32254161/58158176-7d4e1880-7cac-11e9-8df8-8c663dc308aa.png)
The if statement in the red circle corresponds to the next else statement, and the indentation distance should be the same.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c11b2e5-1be9-8d75-a063-8e5c769ec7b0
* Version Independent ID: 533b7b93-3e56-787e-6c39-f346e2104ab0
* Content: [CAsyncSocket Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/casyncsocket-class?view=vs-2019)
* Content Source: [docs/mfc/reference/casyncsocket-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/casyncsocket-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@songxia233 thanks this is fixed now.
