### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by nurbles** [MicrosoftDocs/cpp-docs#1026]
Where do we find information about the different "Item Type" settings available on the custom build "General" panel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cedaa87-4db9-94e0-8f69-29ef5528349a
* Version Independent ID: 688890b6-ab41-f363-ae2c-7914c5473d9b
* Content: [Specifying Custom Build Tools](https://docs.microsoft.com/en-us/cpp/build/specifying-custom-build-tools?view=vs-2019)
* Content Source: [docs/build/specifying-custom-build-tools.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/specifying-custom-build-tools.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@nurbles thanks for the suggestion. Topic has been updated for Sept 1 publishing.
