### ISSUE TITLE
This page appears to be very much out of date

### ISSUE THREAD

**Issue by ajbrehm** [MicrosoftDocs/cpp-docs#1027]
The POSIX subsystem has been replaced by WSL, might have to be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6cac15-3494-2247-f162-06669c09ab5e
* Version Independent ID: eb8794ff-d93d-76fe-36d2-3a65f51132bf
* Content: [Porting from UNIX to Win32](https://docs.microsoft.com/en-us/cpp/porting/porting-from-unix-to-win32?view=vs-2019#feedback)
* Content Source: [docs/porting/porting-from-unix-to-win32.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/porting-from-unix-to-win32.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@ajbrehm thanks yes this page was ancient. we have updated it and the fix should be visible by July 31.
