### ISSUE TITLE
Code indentation issue

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1028]
There is a problem with code indentation in this document.
![Capturesadas](https://user-images.githubusercontent.com/32254161/58227842-281f0f00-7d5f-11e9-97c5-3248308f906f.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2018405-12f5-966a-939d-eafa5dfc0792
* Version Independent ID: 38564b8f-4181-c416-cf46-7903e6cd8726
* Content: [CD2DPointU Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cd2dpointu-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cd2dpointu-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cd2dpointu-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed for Aug 29 publish thanks!
