### ISSUE TITLE
What is the format of the private key file?

### ISSUE THREAD

**Issue by Tragetaschen** [MicrosoftDocs/cpp-docs#1029]
I've tried to connect to my Linux box which requires private key authentication. I have the private key in a format suitable for Putty (`PuTTY-User-Key-File-2: ssh-ed25519`) and for OpenSSH (`-----BEGIN OPENSSH PRIVATE KEY-----`).

Using the former results in an a unrecognized file format error within the dialog, using the latter results in a log file containing an exception "Key 'OPENSSH' is not supported".

So what's the required format of the private key file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Connect to your remote Linux computer in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2019)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by sfreed141** [comment]
How are you creating the keys? The key I created begins with `-----BEGIN RSA PRIVATE KEY-----`.

Here is what worked for me (Windows client connecting to an ssh server on a remote Linux machine):
1. Create the ssh key pair with `ssh-keygen -t rsa` (on Windows machine)
2. Copy the public key to the server:  `scp -p C:\Users\<USERNAME>\.ssh\id_rsa.pub user@hostname:`
3. Add the key to the list of authorized keys on the server (and ensure the file has the correct permissions): `cat ~/id_rsa.pub >> ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys`

4. Add the connection (in Connection Manager). The default private key name is `C:\Users\<USERNAME>\.ssh\id_rsa`.

**Comment by Tragetaschen** [comment]
I had created the keys on Ubuntu 16.04. Note that I'm not using RSA, but ed25519. Maybe that's the issue?

**Comment by sfreed141** [comment]
Looking it some more it appears SSH.NET only support RSA and DSA keys (see [this issue on SSH.NET](https://github.com/sshnet/SSH.NET/issues/485)). Are you able to use one of the other key types until SSH.NET adds support for other key types?

**Comment by Tragetaschen** [comment]
Sure, I've both ends easily under my control. 

Thanks so much for the help!
