### ISSUE TITLE
Incomplete sentence in Events (C++/CX)

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/cpp-docs#1030]
Some words are missing between "that is" and "For more information":

"The method can do whatever you want it to do; the only requirement is that its signature must match the signature of the delegate that is For more information about how to create an delegate event handler and subscribe to an event, see Delegates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa0c454-4197-8ee4-e54b-772772da7b6a
* Version Independent ID: f2e3fc35-8517-186a-9c6e-18b14de7ff1e
* Content: [Events (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/events-c-cx?view=vs-2019)
* Content Source: [docs/cppcx/events-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/events-c-cx.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@KalleOlaviNiemitalo fixed thanks! Should appear by July 15.
