### ISSUE TITLE
Has no effect on LoadLibrary call

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/cpp-docs#1044]
There description can also be read as having an effect on explicit LoadLibrary calls.
But in fact there is no effect. LoadLibrary uses standard search orders even if set a valid value for this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d177f004-5584-1008-dc8f-2c4507d7b88e
* Version Independent ID: af547dc7-3e7a-a15c-c70d-ba0b707c7d0e
* Content: [/DEPENDENTLOADFLAG (Set default dependent load flags)](https://docs.microsoft.com/en-us/cpp/build/reference/dependentloadflag?view=vs-2019)
* Content Source: [docs/build/reference/dependentloadflag.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dependentloadflag.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@0xbadfca11 
I would also expect this to affect explicit `LoadLibrary` calls, though I admit, I could be wrong. If you have a repro case where it doesn't work, I'd recommend you submit it to Developer Community as a product bug. The details on bug submission can be found in [How to report a problem with the Visual C++ toolset or documentation](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019). I'm interested in the result.

**Comment by 0xbadfca11** [comment]
Implicit DLL loading is working as expected, and the specified ``loadflags`` value is correctly stored in ``IMAGE_LOAD_CONFIG_DIRECTORY::DependentLoadFlags``.
So I think there is no problem with the VC ++ toolset.

**Comment by 0xbadfca11** [comment]
Perhaps, the "LoadLibrary call" means after the DLL has been loaded? Not the search path when looking for the DLL passed to LoadLibrary's argument?
