### ISSUE TITLE
C++ AMP source code does not compile without a modification to amp.h

### ISSUE THREAD

**Issue by sharpe5** [MicrosoftDocs/cpp-docs#1049]
The first example on this page for the function `
void CppAmpMethod() {` simply did not compile under Visual Studio 2017.

After making a change suggested here, it compiled and worked for me:
https://developercommunity.visualstudio.com/content/problem/200035/c-amp-does-not-compile-with-permissive.html

The change I made was an edit to the file `amp.h` which is in the folder `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include`. Instructions from said website:

```
I had a similar issue.

Appears to be related to array_view::get_ref and array_view::operator().

The code in the 'amp.h' file has a line like this:

void *_Ptr = _Access(_Index);

I changed it to :

void *_Ptr = this->_Access(_Index);

The 'this->' helped to resolve the method correctly.

So, for me, it now compiles and is working.
```

Unfortuantely, this file "amp.h" is protected, so I could only edit it with SubLime started in administrator mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58e07cc-2b1b-668a-5d9d-73afd80ce1c6
* Version Independent ID: 2b3cbb85-9f6c-2ef2-285a-5af0dc64e31d
* Content: [C++ AMP Overview](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-overview?view=vs-2017)
* Content Source: [docs/parallel/amp/cpp-amp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/cpp-amp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating.

**Comment by sharpe5** [comment]
To be honest, this is not really an issue with the docs. It might require an update to `amp.h` in Visual Studio 2017? Not sure what the best solution is here.

**Comment by mikeblome** [comment]
yes it is a product issue, not a doc issue. Possibly you are hitting this issue, for which a fix is in the pipeline: “AMP does not compile with /permissive-“ ? https://developercommunity.visualstudio.com/content/problem/200035/c-amp-does-not-compile-with-permissive.html

Until 16.3 arrives, you can try removing the /permissive- flag.

**Comment by mikeblome** [comment]
closing as not a documentation issue.
