### ISSUE TITLE
Return value -2, same reason as _fileno?

### ISSUE THREAD

**Issue by squelart** [MicrosoftDocs/cpp-docs#1050]
I'm getting -2 in my code, with fd==1 or fd==2.
Is it for the same reason as noted in https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=vs-2019 ? "If stdout or stderr is not associated with an output stream (for example, in a Windows application without a console window), the file descriptor returned is -2. In previous versions, the file descriptor returned was -1. This change allows applications to distinguish this condition from an error."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e81c11-d21e-f12a-c5aa-bc05f2d3cb8f
* Version Independent ID: e043fc06-5fb5-5792-c770-64508541a113
* Content: [_get_osfhandle](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/get-osfhandle.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/get-osfhandle.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Yes. The standard low-level I/O file descriptors are initialized with the special value -2 by the CRT when there's no console, so any function that checks the value will see it if no other error occurs.

**Comment by corob-msft** [comment]
This seems like an unexpected use case for `_open_osfhandle`, so I don't think there's a need to document this info here.

**Comment by squelart** [comment]
That's disappointing.
- I would have expected all possible return values to be documented.
- "Unexpected" as it may be, it does happen; And when that happened to me I wouldn't have wasted time chasing what else I did wrong (until a colleague noticed the better-documented _fileno).
- The behavior being documented in _fileno already, I think it should be documented elsewhere, otherwise it's confusing and even misleading ("it's documented in _fileno, so if it happened with _get_osfhandle surely it would be documented as well, but it's not so it must be something else...")

I hope you will reconsider.
It should "just" be a copy of that note from _fileno to _get_osfhandle -- but of course it may be trickier than that on your side, I don't know.

Thank you for your answer anyway. At least now I'll know not to trust MS docs.

**Comment by corob-msft** [comment]
It's no problem to copy, it's just that I'm not sure how you use `_open_osfhandle` and get out the stdin, stdout, and stderr file descriptors. Are you iterating through the file descriptor table? How do you get those values into it? Basically, convince me you're not doing something way out of the ordinary.

**Comment by squelart** [comment]
Not sure why you keep coming back to `_open_osfhandle` when I'm talking about `_get_osfhandle`?

In my case, I didn't write the original code, but it does something like: [`RegisterFD(1); RegisterFD(2);`](https://searchfox.org/mozilla-central/rev/f8b11433159cbc9cc80500b3e579d767473fa539/xpcom/build/PoisonIOInterposerWin.cpp#341-342), each calls [`_get_osfhandle`](https://searchfox.org/mozilla-central/rev/f8b11433159cbc9cc80500b3e579d767473fa539/xpcom/build/PoisonIOInterposerBase.cpp#24) and [stores the handle in a list](https://searchfox.org/mozilla-central/rev/f8b11433159cbc9cc80500b3e579d767473fa539/xpcom/build/PoisonIOInterposerBase.cpp#207), so that later [these handles](https://searchfox.org/mozilla-central/source/xpcom/build/PoisonIOInterposerBase.cpp#193-197) will [*not* be spied upon](https://searchfox.org/mozilla-central/rev/f8b11433159cbc9cc80500b3e579d767473fa539/xpcom/build/PoisonIOInterposerWin.cpp#120).

Don't know if it's ordinary or not. I still think it shouldn't matter, especially since you documented _fileno.

**Comment by squelart** [comment]
Also, you already document INVALID_HANDLE_VALUE (-1), so why not talk about -2 as well?

**Comment by corob-msft** [comment]
That's because I thought you were talking about [_open_osfhandle](https://docs.microsoft.com/cpp/c-runtime-library/reference/open-osfhandle?view=vs-2019), and I could not for the life of me figure out how you were turning an OS handle into one of the standard file descriptors using it. So, I was completely wrong about that, and I'm not sure how I got confused. Apologies.

**Comment by squelart** [comment]
No worries, I should have asked about the discrepancy after your first reply.

So... What do you think now, regarding the documentation for `_get_osfhandle`? 😉

**Comment by corob-msft** [comment]
I'm fiddling with it. There may be a case for talking about this value in other places as well.

**Comment by corob-msft** [comment]
After some investigation, it appears that this is the only other function that exposes the -2 value. And the only reason it does is the same reason `_fileno` does, to indicate that there is no stream associated with the file descriptor. And if you don't indulge in the questionable practice of using literal 0, 1, or 2 for `stdin`, `stdout`, and `stderr` file descriptors, but instead get the file descriptor value returned by `_fileno` for those streams and pass it to `_get_osfhandle`, you get the entirely sane result of `INVALID_HANDLE_VALUE` out instead, with `errno` set to `EBADF`. Curiously, you can create a copy or move one of these file descriptors by using `_dup` or `_dup2` from one of the standard streams in this state, and then use `_get_osfhandle` on the new file descriptor to get what looks like a real handle value; but no, if you try to use it, it fails.

**Comment by squelart** [comment]
Thank you for the changes, much appreciated. (I'll let you close this issue, in case you want to do more...)
