### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by platinumsamples** [MicrosoftDocs/cpp-docs#1051]
"The following sample generates C2326:"

should read:

The following sample generates C2362:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d02359-cabf-49da-a6fd-5188aa482125
* Version Independent ID: 4707df0b-dd98-e09f-6141-5133d00b7714
* Content: [Compiler Error C2362](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2362?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2362.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2362.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@platinumsamples 
Thanks, good catch. This fix should show up tomorrow sometime.
