### ISSUE TITLE
Confusion with dllexport and dllimport

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#1054]
The description of the warning talks about dllimport, but the examples all show dllexport. The reason for the warning is still not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9e8ae17-52f0-72f3-10ed-79b10c0f3fc3
* Version Independent ID: e34b2a4f-9e8e-a1ef-52e7-87edab85ffdd
* Content: [Linker Tools Warning LNK4217](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4217?view=vs-2019)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4217.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4217.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
topic has been updated. thanks @ScotBren !
