### ISSUE TITLE
Optional Components pane?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#1057]
For VS2017, where is the *Optional Components* pane?  I have _Visual Studio Installer_ open, and I see a *Individual components* tab.  When I click on that, I don't see anything that states *MFC and ATL support*.  Do have under the _SDKs, libraries, and frameworks_ heading *Visual C++ ATL for x86 and x64* and *Visual C++ MFC for x86 and x64* selected.  Is that was is meant?  Is there something else I'm missing, because it isn't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d751aad8-2e30-e629-1bc4-fd5c6bd3bd5c
* Version Independent ID: ed23ae52-fd39-b83c-104b-0bad48ce63e9
* Content: [MFC MBCS DLL Add-on](https://docs.microsoft.com/en-us/cpp/mfc/mfc-mbcs-dll-add-on?view=vs-2019)
* Content Source: [docs/mfc/mfc-mbcs-dll-add-on.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/mfc-mbcs-dll-add-on.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Ma-XX-oN 
When you open the Visual Studio Installer and choose **Modify**, it opens to the **Workloads** tab. If **Desktop development with C++** is selected, then there is an entry for it in the **Installation details** pane to the right. When it's expanded, there are two headings: **Included** and **Optional**. The **Optional** section is what's meant by **Optional Components** in the document. You can choose **Visual C++ ATL for x86 and x64** or **Visual C++ MFC for x86 and x64** support there. I believe choosing MFC also automatically chooses ATL.

It's also fine to choose things from the **Individual components** tab instead, which gives you more options. In particular, you can choose the more secure versions of the ATL and MFC libraries with Spectre mitigations, and you can choose platform support for ARM and ARM64 development.

Odds are this description was written when the installer was still in prototype, and some wording may have changed. We'll look into clarifying it.

**Comment by gdsotirov** [comment]
Exactly what I needed for an old project. Thanks!

**Comment by mikeblome** [comment]
I have updated the topic with a link for more information about the Installer. Thanks all for the feedback!
