### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by nfalliere** [MicrosoftDocs/cpp-docs#1060]
- it is written that "#pragma pack(pop, identifier, n) is undefined." =&gt; the Examples section shows one such example along with the expected result, which kind of makes it look like the behavior is defined
- it is written that "If the compiler option is not set, the default value is 8." =&gt; that is incorrect on x64 targets, the alignment is 16-byte by default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdeaa85c-b414-742d-156e-1b9d031c5913
* Version Independent ID: 252a08e0-cf80-6788-7d8a-f15ef7a77e17
* Content: [pack](https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/pack.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/pack.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@nfalliere thanks for the feedback. Topic is updated and fix should be visible in 1-2 days.
