### ISSUE TITLE
Missing newline in syntax?

### ISSUE THREAD

**Issue by masamaru-san** [MicrosoftDocs/cpp-docs#1061]
The syntax written here "SET CL=[ [option] ... [file] ...] [/link link-opt ...] SET _CL_=[ [option] ... [file] ...] [/link link-opt ...]", but this place missing a BR tag, isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4afc238-4349-65b7-8e67-ad24e1129018
* Version Independent ID: d4cab2f6-222c-ec99-cf7d-cf178af099a8
* Content: [CL Environment Variables](https://docs.microsoft.com/en-us/cpp/build/reference/cl-environment-variables?view=vs-2019)
* Content Source: [docs/build/reference/cl-environment-variables.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/cl-environment-variables.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@masamaru-san 
Yes, that's missing a break tag, and so are some of the commands later in the article. I've put a fix in that should show up on Monday. Thanks for pointing it out.

**Comment by masamaru-san** [comment]
@corob-msft 
Thank you for your quick action. Because the incorrect note misleads the novice like me to do the right thing.
