### ISSUE TITLE
Remark

### ISSUE THREAD

**Issue by naraindraa** [MicrosoftDocs/cpp-docs#1062]
Good info. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fcd45cd-eb1d-c4c1-d5cd-f8c5b94cd07a
* Version Independent ID: f731e6e5-7d8e-e97c-b71f-0188dc474758
* Content: [VC++ Directories Property Page](https://docs.microsoft.com/en-us/cpp/build/reference/vcpp-directories-property-page?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Projects.VCDirectories)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/build/reference/vcpp-directories-property-page.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/vcpp-directories-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@naraindraa cc: @mikeblome 
We're always pleased to hear that.
