### ISSUE TITLE
Regarding doc section Calling virtual functions in constructors

### ISSUE THREAD

**Issue by bigegg46** [MicrosoftDocs/cpp-docs#1063]
In the example, virtual print_it() is called in ctors of both base class and leaf class, for demonstrating calling virtual function in ctors. However doesn't matter if the function is virtual or not, it will show the same result. What's the purpose of this section and this example?

I tried the code in VS 2019 and confirmed the same result for virtual and non-virtual print_it().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a6e442-8368-26f5-0699-97f8af21bb85
* Version Independent ID: d8075582-1104-18d8-fabb-66666c85eb6b
* Content: [Constructors (C++)](https://docs.microsoft.com/en-us/cpp/cpp/constructors-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/constructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/constructors-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@bigegg46 thanks for the feedback. I have deleted this section because it does seem confused.
