### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by Sachelis** [MicrosoftDocs/cpp-docs#1064]
The title of this page is "Life Cycle of a Dialog Box," but there is almost no information about this topic. What messages are called before, during, and after creation? After destruction? I end up on this page a few times each year and find it frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c397155-4f5a-d280-b64f-c31121d19f18
* Version Independent ID: 2c2a8a79-6e9b-6847-9649-cc802be433f1
* Content: [Life Cycle of a Dialog Box](https://docs.microsoft.com/en-us/cpp/mfc/life-cycle-of-a-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/mfc/life-cycle-of-a-dialog-box.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/life-cycle-of-a-dialog-box.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Sachelis thanks for the feedback. I have changed the title to be more reflective of the actual content. You can infer the life cycle from the sub-topics below this one. Or better yet, find a good book on MFC, of which there are several.
