### ISSUE TITLE
Mention ON_UPDATE_COMMAND_UI

### ISSUE THREAD

**Issue by Sachelis** [MicrosoftDocs/cpp-docs#1068]
This page says, "Use the Properties window to connect a user-interface object to a command-update handler in a command-target object." However, it isn't clear (and I still don't know) which Properties window this is referring to. The only Properties window I know of (relating to controls) is in the Resource Editor, and it don't have a way to connect to a command-update handler. I think the Class Wizard probably does, but I can't find it.

I suggest you: 
1. Explain which properties window you are referring to (and explain how to add the handler from the Class Wizard).
2. Explain how to manually connect the control to handle this message using the ON_UPDATE_COMMAND_UI. Not mentioning this macro seems very strange to me.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0091aaab-01e2-559c-9a3a-62d5cbf7389d
* Version Independent ID: 3d0197ba-64be-e940-a489-8bc97c81024b
* Content: [ON_UPDATE_COMMAND_UI Macro](https://docs.microsoft.com/en-us/cpp/mfc/on-update-command-ui-macro?view=vs-2019)
* Content Source: [docs/mfc/on-update-command-ui-macro.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/on-update-command-ui-macro.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Sachelis thanks for the feedback. I have updated the page and it should be published by Sept 10. Short answer: right-click on the class in Class View and choose Class Wizard. Or, select the class and then choose Properties for similar functionality in Properties window.
