### ISSUE TITLE
The "Clauses" link points to the "Directives"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#1069]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/cpp-docs.zh-cn/issues/88
@UnitDan reports both links lead to the same page and the error replicates in the localized documents.
Kind regards,
Microsoft DOCS International Team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef561fb5-bc2c-d281-9f5b-9d52fa612f12
* Version Independent ID: ed0f2280-f9f8-5ba7-c8d6-dcdd81918485
* Content: [OpenMP Library Reference](https://docs.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-library-reference?view=vs-2019&tdsourcetag=s_pcqq_aiomsg#feedback)
* Content Source: [docs/parallel/openmp/reference/openmp-library-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/openmp/reference/openmp-library-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@CeciAn fixed for 07-31 thanks!
