### ISSUE TITLE
Page content does not change when switching between VS2015/VS2017/VS2019 on menu (upper left corner)

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#1073]
When I use the menu on the upper left corner of the page to switch between various Visual Studio versions, the list of linker options on this page does not change. This makes it hard to compare the linker options for different VS versions.

Same problem happens with the compiler options shown at https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0255b2-cf9d-3325-ccd7-e34aed553311
* Version Independent ID: d1664a56-cee1-bdd9-bb77-3acb62670a41
* Content: [MSVC Linker Options](https://docs.microsoft.com/en-us/cpp/build/reference/linker-options?view=vs-2019)
* Content Source: [docs/build/reference/linker-options.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/linker-options.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fpl9000 

Since the content here is similar to the content referenced in issue #1072, I'm closing it for the same reason.
