### ISSUE TITLE
VS2019 option /Qspectre missing

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#1077]
If I run this command in a VS2019 Developer Command Prompt console:

"C:\franl&gt;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64\cl.exe" /?

the output includes this option, which is not documented on this page:

/Qspectre[-] enable mitigations for CVE 2017-5753

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2353367-e490-5dc3-fc39-3bcba30bf365
* Version Independent ID: 4300089e-7ea0-68bf-eb1f-c9c31cdb8d41
* Content: [Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2019)
* Content Source: [docs/build/reference/compiler-options-listed-alphabetically.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/compiler-options-listed-alphabetically.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
fixed! Thanks @fpl9000. Should be published by Aug 5
