### ISSUE TITLE
VS2019 option /arch:AVX512 not documented

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#1078]
If I run this command in a VS2019 Developer Command Prompt console:

"C:\franl&gt;"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64\cl.exe" /?

the output includes this option, which is not documented on this page:

/arch:AVX512 - enable use of instructions available with AVX-512-enabled CPUs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732983a0-a628-77d4-a224-0db096ade499
* Version Independent ID: e7aae128-bb82-c6b5-3389-2f4470d66d11
* Content: [/arch (x64)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2019)
* Content Source: [docs/build/reference/arch-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/arch-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed in September, but I forgot to close the bug.
