### ISSUE TITLE
Missing VS2019 linker options

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#1080]
When I execute this command in a VS2019 Developer Command Prompt console:

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64\link.exe" /?

The following options are shown, but they are missing from this page:

/LINKREPRO:dir
/LINKREPROTARGET:filename

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0255b2-cf9d-3325-ccd7-e34aed553311
* Version Independent ID: d1664a56-cee1-bdd9-bb77-3acb62670a41
* Content: [MSVC Linker Options](https://docs.microsoft.com/en-us/cpp/build/reference/linker-options?view=vs-2019)
* Content Source: [docs/build/reference/linker-options.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/linker-options.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by 9527KGG** [comment]
Thanks for the report. Fixed in the latest VS2019.

Kevin, VC++ team

**Comment by corob-msft** [comment]
@fpl9000 
These should be visible sometime on Monday. Thanks for your patience.
