### ISSUE TITLE
Missing link target

### ISSUE THREAD

**Issue by McTrk** [MicrosoftDocs/cpp-docs#1086]
Clicking the section link "C++/CLI Migration Primer" takes me to this same page of table of contents. Intended? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e59840-a55c-3282-0b9c-346c0687d48f
* Version Independent ID: 9bb354b6-d77a-1e8d-4cfe-94f77b9890e3
* Content: [.NET Programming with C++/CLI (Visual C++)](https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=vs-2019#feedback)
* Content Source: [docs/dotnet/dotnet-programming-with-cpp-cli-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/dotnet-programming-with-cpp-cli-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed for 08-01. thanks @McTrk !
