### ISSUE TITLE
${vsInstallDir} or ${env.vsInstallDir}?

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1088]
section "Build-in macros" lists 3 built-in macros for use in CppProperties.json, after test i find use ${vsInstallDir} in known keys such as includePath in CppProperties.json results in a warning text printed in vs' output window:
failed to evaluate environment variable "${vsInstallDir}"
if i use ${env.vsInstallDir} it works.
"includePath": [ "${env.vsInstallDir}" ]

so is it ${vsInstallDir} or ${env.vsInstallDir}?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed0104b-8ba3-0b4d-5765-29f20e842b5c
* Version Independent ID: 7d5cc7af-86de-89cd-c86f-61f050ce7d1b
* Content: [CppProperties.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=vs-2019#feedback)
* Content Source: [docs/build/cppproperties-schema-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cppproperties-schema-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by wangzimei** [comment]
after some consideration i believe despite the above fact that ${env.vsInstallDir} seems defined, it really should be ${vsInstallDir}, not ${env.vsInstallDir}, that is, defined in current ide rather than in system env. because under side by side installation, the environment variable vsInstallDir, even if set as array, is almost useless and in fact is not set. since there's no vsInstallDir env var, the item shouldn't be accessed through ${env.xxx}.

ps. the warning message given by output window is
`failed to evaluate environment variable "${vsInstallDir}"`
does this suggesting that it only evaluates ${env.xxx}?

**Comment by mikeblome** [comment]
@wangzimei in cppproperties.json the correct value is ${env.vsInstallDir}. Thanks for the feedback and the doc will be fixed soon.

**Comment by wangzimei** [comment]
thanks. i prefer ${vsInstallDir} though. unless some bin files already rely on the environment variable vsInstallDir, it's no point to add it to some exe's environment (when called by vs), being a macro in vs is sufficient.
