### ISSUE TITLE
"disableDeploy" not available in launch_schema.json

### ISSUE THREAD

**Issue by infinite-persistence** [MicrosoftDocs/cpp-docs#1090]
I'm using 2019-16.1.3, but the last piece of code-block in this page doesn't seem to have IntelliSense to describe it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001834ce-31d2-e768-1df1-4a776aa9ef65
* Version Independent ID: 45f15fc0-e5c7-34a1-2469-f38d304ef5bd
* Content: [Deploy, run, and debug your C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/deploy-run-and-debug-your-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/deploy-run-and-debug-your-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by infinite-persistence** [comment]
Is there a complete example in Github? 

"disableDeploy": false,
"deployDirectory": "~\foo",
"deploy" : [
   {
      "sourceMachine": "127.0.0.1 (username=example1, port=22, authentication=Password)",
      "targetMachine": "192.0.0.1 (username=example2, port=22, authentication=Password)",
      "sourcePath": "~/example.cpp",
      "targetPath": "~/example.cpp",
      "executable": "false"
   }
]

The above doesn't work.  It is complaining that  `disableDeploy` wants to be a string.

**Comment by mikeblome** [comment]
@infinite-persistence If you put false in quotes, does it work as expected? Is that the only problem you are having?

**Comment by infinite-persistence** [comment]
I couldn't get the entire "deploy to another target" to work.  Most likely I misunderstood the partial instructions, hence the request for a full example.
I ended up installing nfs on the target and making manual copies, since I couldn't get VS2019 to deploy it from the Linux build machine to the Linux target.

**Comment by mikeblome** [comment]
@infinite-persistence We have a work item on our internal backlog to provide a better tutorial for this scenario. I'm going to close this issue since you solved your immediate problem.
