### ISSUE TITLE
How to choose different IntelliSense path?

### ISSUE THREAD

**Issue by infinite-persistence** [MicrosoftDocs/cpp-docs#1095]
Hi.  When connecting to the Remote Build Machine, I do not wish to use the default gcc for IntelliSense.  I am using a different ARM toolchain/path when building.  Is it possible to override where VS2019 searches for IntelliSense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@infinite-persistence sorry for delay. Right now, these settings are defined on a per-connection basis by manually editing the “settings.xml” file in the header cache. Expect that sooner or later it will be possible to set this on a per-project basis via property pages.
