### ISSUE TITLE
Deletion of pointer after usage

### ISSUE THREAD

**Issue by amalshaji** [MicrosoftDocs/cpp-docs#1099]
Please delete the issued pointers after usage (use delete). Non-removal of pointers leads to slow execution of programs (high memory consumption).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e828bb-986a-eba0-c0d4-104dae013b50
* Version Independent ID: 2a1920a7-d6f5-142d-c596-e661ee65962d
* Content: [Virtual Functions](https://docs.microsoft.com/en-us/cpp/cpp/virtual-functions?view=vs-2019#feedback)
* Content Source: [docs/cpp/virtual-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/virtual-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@amalshaji thanks for the feedback and apologies for delayed response. In this code example there is no call to "new" and therefore no need to "delete". The original object and all pointers to it are declared on the stack and go out of scope when main returns.
