### ISSUE TITLE
reuse is misspelled

### ISSUE THREAD

**Issue by P301319** [MicrosoftDocs/cpp-docs#1105]
Use this dialog to view the current directories. However, if you want to change or add a directory, it is better to use Property Manager to create a property sheet or modify the default user property sheet. For more information, see Share or "resuse" Visual Studio C++ project settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fcd45cd-eb1d-c4c1-d5cd-f8c5b94cd07a
* Version Independent ID: f731e6e5-7d8e-e97c-b71f-0188dc474758
* Content: [VC++ Directories Property Page](https://docs.microsoft.com/en-us/cpp/build/reference/vcpp-directories-property-page?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Projects.VCDirectories)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/build/reference/vcpp-directories-property-page.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/vcpp-directories-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@P301319 fixed thanks! Should be visible by July 15.
