### ISSUE TITLE
What is the problem with c++ keywords color in https://docs.microsoft.com/....

### ISSUE THREAD

**Issue by EnchevEG** [MicrosoftDocs/cpp-docs#1107]
![image](https://user-images.githubusercontent.com/50485223/59746372-7a305300-927f-11e9-81b6-b1852b2fa8b2.png)

In the Github's page there is no such color's mismatch of keywords but only in Microsoft's Docs page.

**Comment by corob-msft** [comment]
@EnchevEG 

The last time I looked into this, the colorization was supplied by a third-party add-in that runs client-side on elements of type `<code>`. I think it was written in jQuery, but I don't remember for sure. It's part of the script stuff loaded along with our pages. It's supplied by the production team that builds the website. We don't have any control over that within our repo. I'm not sure there's a feedback mechanism for this kind of thing. You could try the [Docs team blog](https://docs.microsoft.com/en-us/teamblog/).
