### ISSUE TITLE
and?

### ISSUE THREAD

**Issue by dotfield** [MicrosoftDocs/cpp-docs#1108]
Where does that [Reflection::DefaultMember] above the property come from? I have loads of examples in code I'm working on. When I right-click "Go To Definition" it keeps telling me the definitiion is not found. It appears in our own namespace, I see it used everywhere but defined nowhere. It appears to have come by magic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45fe3dc6-7a36-54e9-9c57-2854b246e71d
* Version Independent ID: e14c986b-2286-074b-87ee-ebd19d7ae3d9
* Content: [How to: Use Properties in C++/CLI](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-use-properties-in-cpp-cli?view=vs-2019)
* Content Source: [docs/dotnet/how-to-use-properties-in-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-use-properties-in-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by MSDN-WhiteKnight** [comment]
The `Reflection::DefaultMemberAttribute` type is defined in .NET Framework mscorlib.dll assembly, namespace `System::Reflection`. The C++/CLI support in Visual Studio is lacking and "Go To Definition/Declaration" functionality doesn't work for managed types (unlike for unmanaged types, C++ declarations for managed types had to be decompiled from binary assembly metadata, it can't just show a line in the header file, and nobody implemented this). But you may view this declaration on corresponding .NET API documentation page: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.defaultmemberattribute?view=netframework-4.7.2

**Comment by corob-msft** [comment]
Just to elaborate on @MSDN-WhiteKnight 's comment: One thing that's confusing about .NET attributes is that they're abbreviated from their names in the documentation, [leaving off the "Attribute" part at the end](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/attributes/index) as a bit of syntactic sugar. And it doesn't help that IntelliSense doesn't know how to find the declarations. It's possible that F1 might take you to the right documentation, but I wouldn't be surprised if it doesn't. Basically, you just have to know that if you see an attribute named something like `System::Serializable`, then you need to look up [SerializableAttribute](https://docs.microsoft.com/dotnet/api/system.serializableattribute) in the docs.

I'm closing this as the question is only incidental to the article.
