### ISSUE TITLE
C# - No article on labeled statements

### ISSUE THREAD

**Issue by EugeneKramer** [MicrosoftDocs/cpp-docs#1110]
There appears to be no equivalent C# article covering labeled statements? There is an article for [C](https://docs.microsoft.com/en-us/cpp/c-language/goto-and-labeled-statements-c?view=vs-2019), [C++](https://docs.microsoft.com/en-us/cpp/cpp/labeled-statements?view=vs-2019
), and [VB](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/how-to-label-statements).

There is a brief mention at [Statements (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/statements).

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf407fc-4210-de79-9afb-f06452244844
* Version Independent ID: 72412cad-7448-a3da-15e9-313504553c08
* Content: [Labeled Statements](https://docs.microsoft.com/en-us/cpp/cpp/labeled-statements?view=vs-2019)
* Content Source: [docs/cpp/labeled-statements.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/labeled-statements.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@EugeneKramer can you please file this issue in the https://github.com/microsoft/dotnet repo?
