### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by eventura1** [MicrosoftDocs/cpp-docs#1111]
The following link :  see Console Applications (https://docs.microsoft.com/en-us/cpp/windows/console-applications-in-visual-cpp?view=vs-2019) redirects back to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c828ff7-367e-cdb9-7573-69e3f87f27a2
* Version Independent ID: 39f4562b-606c-4a6a-150a-eade928a85da
* Content: [Overview of Windows Programming in C++](https://docs.microsoft.com/en-us/cpp/windows/overview-of-windows-programming-in-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/overview-of-windows-programming-in-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/overview-of-windows-programming-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
thanks @eventura1 ! Link has been fixed to go to a better topic. Should be visible by Sept 19
