### ISSUE TITLE
tasks.vs.json is useful, please provide the schema and examples

### ISSUE THREAD

**Issue by solvingj** [MicrosoftDocs/cpp-docs#1112]
There are lots of use cases for tasks.vs.json which are not good fits for CMakeLists.txt, just like there are use cases for CppProperties.json.  Please provide official schema definition, and some examples.  I've posted the latest schema definition here as a reference until the official one gets posted here: https://gist.github.com/solvingj/8e9aa575aa0c6dd3db655f680e49f44a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743bb803-b9a9-0b2f-341f-69f1823e5dba
* Version Independent ID: 853beb3f-f378-3da1-1eed-f5189363173c
* Content: [Tasks.vs.json schema reference (C++)](https://docs.microsoft.com/en-us/cpp/build/tasks-vs-json-schema-reference-cpp?view=vs-2019)
* Content Source: [docs/build/tasks-vs-json-schema-reference-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/tasks-vs-json-schema-reference-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
topic has been updated. thanks @solvingj !
