### ISSUE TITLE
Remarks missing entry (keyword argument not valid in 64-bit MASM)

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1119]
**ASSUMES** and **CPU** keyword arguments are not valid in 64-bit MASM (ml64.exe).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58dcede-cec1-c577-7f34-556e6dbc3d61
* Version Independent ID: dc77540e-ff6f-8ef8-73b7-08f26383b213
* Content: [PUSHCONTEXT](https://docs.microsoft.com/en-gb/cpp/assembler/masm/pushcontext?view=vs-2019)
* Content Source: [docs/assembler/masm/pushcontext.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/pushcontext.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @Player1UK! Fix should appear in a day or so.
