### ISSUE TITLE
Remarks missing entry (keyword argument not valid in 64-bit MASM)

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1120]
**ASSUMES** and **CPU** keyword arguments are not valid in 64-bit MASM (ml64.exe).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff0e952a-d01a-73bf-1d25-db4fd6f5cff1
* Version Independent ID: 9606b784-56ea-beda-140a-efa4c475ae50
* Content: [POPCONTEXT](https://docs.microsoft.com/en-gb/cpp/assembler/masm/popcontext?view=vs-2019)
* Content Source: [docs/assembler/masm/popcontext.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/popcontext.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @Player1UK! Fix should appear in a day or so.
