### ISSUE TITLE
Remarks missing entry

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1121]
Each instance of *name* in this definition mirrors the other.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b596c9e7-026b-94f5-c50d-e2d381a58f60
* Version Independent ID: a556fc54-b0e9-833f-b90d-4caf865b4cfa
* Content: [STRUCT (MASM)](https://docs.microsoft.com/en-gb/cpp/assembler/masm/struct-masm?view=vs-2019)
* Content Source: [docs/assembler/masm/struct-masm.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/struct-masm.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @Player1UK! Fix should appear in a day or so.
