### ISSUE TITLE
Missing Article: Microsoft Macro Assembler (MASM for x64) Reference

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1122]
ml64.exe requires its own article because the directives, symbols, and operators are more refined and the directive definitions are different.  Having to constantly point out the differences in the 32-bit (MASM for x86) reference is vexatious.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15c4f44-4788-a43e-b4ef-cee0600a0553
* Version Independent ID: 89ba85d9-7a78-5a89-f18d-011a76d513e2
* Content: [Compiler Intrinsics and Assembly Language](https://docs.microsoft.com/en-gb/cpp/intrinsics/compiler-intrinsics-and-assembly-language?view=vs-2019)
* Content Source: [docs/intrinsics/compiler-intrinsics-and-assembly-language.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/compiler-intrinsics-and-assembly-language.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Player1UK thanks for the suggestion. It's a reasonable request. I have created an internal work item for tracking and prioritizing against other work. As vexatiousness is not a bug, strictly speaking, I'm going to close this issue.
