### ISSUE TITLE
Unnecessary definition.

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1146]
Already covered by [**TEXTEQU, CATSTR**](./textequ "TEXTEQU, CATSTR Directives")

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200d95e3-0601-9a28-05db-e726d2907982
* Version Independent ID: be911eda-2f1c-0906-3014-d778cee64e89
* Content: [CATSTR](https://docs.microsoft.com/en-gb/cpp/assembler/masm/catstr?view=vs-2019)
* Content Source: [docs/assembler/masm/catstr.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/catstr.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Player1UK I added a link to TEXTEQU but will leave this page as-is otherwise.
