### ISSUE TITLE
Remarks missing entry (non-Terminal not valid in 64-bit MASM)

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1150]
Non-Terminal argument _definition_ entry _langtype_ not valid in 64-bit MASM (ml64.exe).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 594bbfb8-e9ff-0a62-2c21-be49f0d84c0d
* Version Independent ID: 6b4071f6-c1f7-72c9-a4db-0de29ef2d96d
* Content: [COMM](https://docs.microsoft.com/en-gb/cpp/assembler/masm/comm?view=vs-2019)
* Content Source: [docs/assembler/masm/comm.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/comm.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @Player1UK! Fix should appear in a day or so.
