### ISSUE TITLE
Missing key when connecting to linux target

### ISSUE THREAD

**Issue by infinite-persistence** [MicrosoftDocs/cpp-docs#1154]
My Linux target doesn't have the compiler or GDB, so when I add a connection in the Cross Platform settings page, there will be an error saying that it could not find items for IntelliSense.  According to comment from Marc Goodner in a blog post, this is fine since we are not building on this machine. However, in 16.1.3, when I try to update a CMake Linux project's launch.vs.json ${remoteMachineName} to this target, there will be an exception saying that a "key does not exist".  I think that's the general dictionary exception message, and is probably not working due to the IntelliSense error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Connect to your target Linux system in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2019)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@infinite-persistence this sounds like a product issue for 16.1. Are you willing to raise the issue on [developer community](https://developercommunity.visualstudio.com/spaces/62/index.html), so that it can be triaged and addressed by the product team?
