### ISSUE TITLE
Typo in cpp-docs/docs/cpp/func.md

### ISSUE THREAD

**Issue by LogicalKnight** [MicrosoftDocs/cpp-docs#118]
The text in the "Return Value" section has a typographical error (emphasized for clarity):

> Returns a null-terminated const char array of characters that **constains** the function name.

The word "constains" should be "contains", I presume.

**Comment by corob-msft** [comment]
Thanks, well spotted. We've got a branch with that fix added to it that should be merged in a day or two.

**Comment by corob-msft** [comment]
Fixed this back in October, but forgot to close this issue.
