### ISSUE TITLE
CAsyncSocket Create's bind implementation has a bug in it

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#1190]
See Stackoverflow for description of the problem: https://stackoverflow.com/questions/10968182/windows-socket-error-10013 and https://stackoverflow.com/questions/17123380/c-windows-socket-error-10013.
The MFC Create function makes sure is set up properly by creating its own Socket, memset'ing it and calling 'bind'. The failure occurs on the OPs PCs and mine when something in the environment changes which makes the socket code useless in a production environment. When the failure occurs, it is consistent and always occurs in the bind whose source code is unavailable.

My workaround was to discard the 'addrResult' obtained from ::getaddrinfo and find another addrResult that does work. This is not a solution, but that is better than letting such an obscure bug stop the development of critical code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c11b2e5-1be9-8d75-a063-8e5c769ec7b0
* Version Independent ID: 533b7b93-3e56-787e-6c39-f346e2104ab0
* Content: [CAsyncSocket Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/casyncsocket-class?view=vs-2019#create)
* Content Source: [docs/mfc/reference/casyncsocket-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/casyncsocket-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@rtischer8277 thanks for reporting this. Are you willing to post it on [developer community](https://developercommunity.visualstudio.com/spaces/62/index.html) so that the product team can see it and triage it?

**Comment by rtischer8277** [comment]
Fine with me. Is that something I do? Or do you transfer #1190?

**Comment by rtischer8277** [comment]
Okay, I did post the problem on the Developer Community site.

**Comment by rtischer8277** [comment]
Because the problem dll is presumably in __imp_bind, which is in the Windows dll and not MFC, this issue has been referred to them by the Developer Community's Billy Robert O'Neal III (C+E Security) [MSFT]. Remaining, however, is the issue that the CAsyncSocket::Create Return Values documentation doesn't account for the WSAEACCES error. This is a situational bug and hard to replicate, but I have set aside a test rig where the bug appears, until it can get resolved and the documentation corrected.

**Comment by rtischer8277** [comment]
Problem resolved. See my Answer in Stackoverflow `how to determine socket interface type`.

**Comment by mikeblome** [comment]
@rtischer8277 Glad you were able to figure this out. I added a link to the Windows topic that lists all the  possible socket errors. Should appear in the next day or so.
