### ISSUE TITLE
Unnecessary entry

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1191]
Already covered by [**IF2**](./if2 "IF2 Directive") and [**ELSEIF**](./elseif-masm "ELSEIF Directive").

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5e3b9f-3cba-57b0-5106-ff0584847015
* Version Independent ID: 79701bc0-3419-08a4-8a24-347747b60af8
* Content: [ELSEIF2](https://docs.microsoft.com/en-gb/cpp/assembler/masm/elseif2?view=vs-2019)
* Content Source: [docs/assembler/masm/elseif2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/elseif2.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Player1UK thanks for your feedback! Product team prefers not to merge these topics.

**Comment by mikeblome** [comment]
@Player1UK thanks for the feedback! We prefer to keep these pages, but have added links to related pages for more info.
