### ISSUE TITLE
Is it a bad link in MFC Hierarchy Chart?

### ISSUE THREAD

**Issue by kynowoo** [MicrosoftDocs/cpp-docs#12]
route: cpp-docs/docs/mfc/hierarchy-chart.md

>   You can download the complete chart from the following location: http://go.microsoft.com/fwlink/LinkId=112301.

I got an error message numbered 404 when accessing the page.

**Comment by ghogen** [comment]
I have submitted a fix for this which should appear shortly.

**Comment by corob-msft** [comment]
Cleaning up old issues. This appears to be fixed now.
