### ISSUE TITLE
_beginthread says "The locale of the new thread is inherited from its parent thread" - not correct.

### ISSUE THREAD

**Issue by will-bartlett** [MicrosoftDocs/cpp-docs#121]
The documentation for _beginthread (https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/beginthread-beginthreadex) says:
`The locale of the new thread is inherited from its parent thread. If per-thread locale is enabled by a call to _configthreadlocale (either globally or for new threads only), the thread can change its locale independently from its parent by calling setlocale or _wsetlocale. For more information, see Locale.`
This is mostly wrong. The locale of the new thread is the same as the locale of the parent thread when per-thread locale is disabled (aka when per-process locale is being used). However, this isn't "inheritance" - both threads are just checking the same global variable. When per-thread locale is enable, the locale of the new thread is the default locale, not the locale of the parent thread (which "inheritance" implies would be the case).

**Comment by corob-msft** [comment]
Yep, you've identified some content that's misleading, and the parent thread inheritance part is just plain wrong. 

When new threads are created, they are initialized with the per-process global current locale info. That's potentially different from the default locale info that was loaded at process start-up, if changes have already been made via `setlocale`. Threads that have the per-thread locale flag set can change their thread-local copy of the locale info without affecting other threads. Threads that don't have the flag set can affect the locale info in all other threads that also don't have the per-thread locale flag set, as well as all newly-created threads. 

You're welcome to propose a change and make a pull request. If you'd rather have the docs team deal with it, we'll get around to it eventually, and we'll note it here when it's fixed.

**Comment by corob-msft** [comment]
This bubbled up in the backlog and the updated language is now live: [_beginthread, _beginthreadex](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/beginthread-beginthreadex). Closing as fixed.
