### ISSUE TITLE
"An example of the comments" is not consistent with individual topics

### ISSUE THREAD

**Issue by definedrisk** [MicrosoftDocs/cpp-docs#1241]
Individual topics refer to a sample listing from CStdioFile class but the actual example shown is a part of CChildFrame class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3672a55f-5a4f-0b81-ec8f-afe7f02a6a64
* Version Independent ID: a482ae2c-c685-00be-4bdb-85baef045fe8
* Content: [Using the MFC Source Files](https://docs.microsoft.com/en-us/cpp/mfc/using-the-mfc-source-files?view=vs-2019)
* Content Source: [docs/mfc/using-the-mfc-source-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/using-the-mfc-source-files.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@definedrisk I can't repro this. Looking at afx.h at (in my installation location) C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.23.28019\atlmfc\include\afx.h, the example does in fact show CStdioFile. Feel free to reopen if I'm missing something.
