### ISSUE TITLE
Incorrect and incomplete Syntax definition

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1249]
Grants assembly of _directive_\[s\] following statement if **IF** statement is true \(nonzero\), or false \(0\) and optional **ELSEIF** statement is true, or if optional **ELSE** statement is present\.
> \{\{**IF**\[\[**E**\]\] _constantExpression_ \| **IF**\[\[**N**\]\]**B** _macroTextItem_ \| **IF**\[\[**N**\]\]**DEF** _id_ \| **IF**\[\[**DIF** \| **IDN**\]\]\[\[**I**\]\] _macroTextItem_**,**_macroTextItem_ \| **IF**\[\[**1** \| **2**\]\]\}\}_;;_
_directive_\.\.\.
\[\[\{\{**ELSEIF**\[\[**E**\]\] _constantExpression_ \| **ELSEIF**\[\[**N**\]\]**B** _macroTextItem_ \| **ELSEIF**\[\[**N**\]\]**DEF** _id_ \| **ELSEIF**\[\[**DIF** \| **IDN**\]\]\[\[**I**\]\] _macroTextItem_**,**_macroTextItem_ \| **ELSEIF**\[\[**1** \| **2**\]\]\}\}_;;_
_directive_\.\.\.\]\]\.\.\.
\[\[**ELSE**_;;_
_directive_\.\.\.\]\]
**ENDIF**_;;_

non-Terminal|Definition
---|---
_;;_|\(\[\\x9\\x20\]\*;\[\\x0\-\\x9\\xB\-\\xFF\]\*\)?\\xA
_id_|\[A\-Za\-z$?@\_\]\[A\-Za\-z0\-9$?@\_\]\{0,246\}
_number_|\[0\-9\]\[A\-Fa\-f0\-9\]\*\[HOQTYhoqty\]?
_character_|\[\\x0\-\\x9\\xB\-\\xFF\]
_text_|_character_\.\.\.
_literal_|**&lt;**\[\[_text_\]\]**&gt;**
_chainString_|\(“\[\\x0\-\\x9\\xB\-\\x21\\x23\-\\xFF\]\*“\)\+\|\(’\[\\x0\-\\x9\\xB\-\\x26\\x28\-\\xFF\]\*’\)\+
_constant_|\{\{**\(**_constantExpression_**\)**\}\}\.\.\. \| _terminalExpression_ \| _type_
_type_|_dataType_ \| \{\{**NEAR** \| **FAR**\}\} \| **PROC** \| _structnameId_ \| _recordnameId_ \| _typeId_
_dataType_<br/><br/>|**BYTE** \| **SBYTE** \| **WORD** \| **SWORD** \| **DWORD** \| **SDWORD** \| **FWORD** \| **QWORD** \| **SQWORD** \| **TBYTE** \| **OWORD** \| **REAL4** \| **REAL8** \| **REAL10** \| **MMWORD** \| **XMMWORD** \| **YMMWORD**
_directive_|_generalDirective_ \| _segmentDirective_ \| _structDirective_
_generalDirective_<br/><br/><br/><br/><br/><br/><br/>|_nameDirective_ \| _includeDirective_ \| _includeLibDirective_ \| _commentDirective_ \| _recordDirective_ \| _typedefDirective_ \| _externDirective_ \| _externdefDirective_ \| _publicDirective_ \| _commDirective_ \| _protoDirective_ \| _contextDirective_ \| _optionDirective_ \| _radixDirective_ \| _titleDirective_ \| _pageDirective_ \| _listDirective_ \| _crefDirective_ \| _echoDirective_ \| _ifDirective_ \| _errorDirective_ \| _macroDirective_ \| _macroCallDirective_ \| _macroForDirective_ \| _macroForcDirective_ \| _macroPurgeDirective_ \| _macroRepeatDirective_ \| _macroTextDirective_ \| _macroTextEquDirective_ \| _macroText=Directive_ \| _macroWhileDirective_ \| _aliasDirective_
_constantExpression_|_operatorExpression_ \| _constant_
_operatorExpression_|\[\[_unaryOperator_\]\] _constant_ _binaryOperator_ _constantExpression_ \| _unaryOperator_ _constant_
_recordExpression_<br/><br/>|_recordnameId_ \{\{**\{**\[\[_constantExpression_\]\]\[\[**,**\[\[_constantExpression_\]\]\]\]\.\.\.**\}** \| **<**\[\[_constantExpression_\]\]\[\[**,**\[\[_constantExpression_\]\]\]\]\.\.\.**>**\}\}
_terminalExpression_|_lengthOperator_ \| _recordOperator_ \| _sizeTypeOperator_ \| _recordExpression_ \| _number_ \| _chainString_
_binaryOperator_|_arithmeticOperator_ \| _booleanOperator_ \| _conditionalOperator_
_arithmeticOperator_|**\+** \| **\-** \| **\*** \| **/** \| **MOD** \| **SHR** \| **SHL**
_booleanOperator_|**AND** \| **OR** \| **XOR**
_conditionalOperator_|**EQ** \| **NE** \| **LT** \| **LE** \| **GT** \| **GE**
_lengthOperator_|\{\{**LENGTH** \| **LENGTHOF**\}\} _dataLabel_
_dataLabel_|\{\{_variablenameId_ \| _structnameId_\}\}\[\[_memberOperator_\]\]\.\.\.
_memberOperator_|**\.**_structmemberId_
_recordOperator_|\{\{**WIDTH** \| **MASK**\}\} \{\{_recordnameId_ \| _recordfieldnameId_\}\}
_sizeTypeOperator_|\{\{**SIZE** \| **SIZEOF** \| **TYPE**\}\} \{\{_dataLabel_ \| _type_\}\}
_unaryOperator_|**\+** \| **\-** \| **NOT** \| _highlowOperator_
_highlowOperator_|**HIGH** \| **LOW** \| **HIGHWORD** \| **LOWWORD** \| **HIGH32** \| **LOW32**
_macroTextItem_|_literal_ \| _**%**_constantExpression_ \| _macroTextId_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|

Optionally, assembles **ELSE** _directive_\[s\] if the previous statement is false\.  Note that the statements are evaluated at assembly time\.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6355b0-caa2-4fe1-ef4e-80879149c621
* Version Independent ID: 38195d45-ca8e-b970-3761-fb2aa63680cf
* Content: [IF (MASM)](https://docs.microsoft.com/en-gb/cpp/assembler/masm/if-masm?view=vs-2019)
* Content Source: [docs/assembler/masm/if-masm.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/if-masm.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Player1UK thanks! See comment for #1123.
