### ISSUE TITLE
Incorrect additional argument

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/cpp-docs#1250]
There is no _expression_ to evaluate in an **IF2** statement, just an end-of-line non-Terminal.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9bf854-46ea-9d89-e77e-53323accb9f6
* Version Independent ID: b9a04083-6042-a638-1b72-1602a1373051
* Content: [IF2](https://docs.microsoft.com/en-gb/cpp/assembler/masm/if2?view=vs-2019)
* Content Source: [docs/assembler/masm/if2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/if2.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Player1UK** [comment]
Incorporated into Incomplete Syntax definition issue.

**Comment by mikeblome** [comment]
@Player1UK thanks for your feedback! Fix should appear in a day or so.
