### ISSUE TITLE
Missed semi-colon

### ISSUE THREAD

**Issue by imanirajian** [MicrosoftDocs/cpp-docs#1267]
In first cell of this document, on the line contains (`t.f = 7.25 // t now holds a float`), semi-colon of the statement is missed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a72b499a-3b65-4005-32dd-a6be9100a975
* Version Independent ID: aaa2c0c5-677c-4fb6-cca8-9d4a7aa9122f
* Content: [Unions](https://docs.microsoft.com/en-us/cpp/cpp/unions?view=vs-2019#declaring-a-union)
* Content Source: [docs/cpp/unions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unions.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@imanirajian thanks! The fix should be visible by Sept 17.
