### ISSUE TITLE
/p:platform=myplatform causes error

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1289]
i changed
```
<ProjectConfiguration Include="Release|Win32">
    <Configuration>Release</Configuration>
    <Platform>Win32</Platform>
</ProjectConfiguration>
```
to
```
<ProjectConfiguration Include="Release|myplatform">
    <Configuration>Release</Configuration>
    <Platform>myplatform</Platform>
</ProjectConfiguration>
```
then run `msbuild myproject.vcxproj /p:configuration=release /p:platform=myplatform`, got following error
```
“C:\code\abc\build\msbuild\c++\myproject.vcxproj”(默认目标) (1) ->
(_CheckForInvalidConfigurationAndPlatform 目标) ->
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'my
project.vcxproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='release' Platform='myplatform'. You
may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
[C:\code\abc\build\msbuild\c++\myproject.vcxproj]
```

besides, section "Using MSBuild with Build Properties" states "the release or debug build configuration is specified by the Configuration property" but i see the `<Configuration>` node is under `<ProjectConfiguration>` node, is it indeed considered as property (accessed via $(Configuration))?

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: be969ff1-c6bf-a58a-4f1e-cc6c037ab8f5
Version Independent ID: 17272cba-73e8-d640-104a-989345208ca8
Content: [Walkthrough: Using MSBuild to Create a Visual C++ Project](https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=vs-2019#feedback)
Content Source: [docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md)
Product: visual-cpp
Technology: cpp-tools
GitHub Login: @corob-msft
Microsoft Alias: corob

**Comment by mikeblome** [comment]
@wangzimei sorry for delayed response. The error here is probably because you use `release` but it should be `Release`. MSBuild is case-sensitive.
