### ISSUE TITLE
regarding error c3867

### ISSUE THREAD

**Issue by SapphireSpire** [MicrosoftDocs/cpp-docs#129]
The lack of 'void' in the parameter list of a class member function that doesn't take an argument will trigger a c3867 error. There's no mention of this in VS or the MS Docs page it links to.

**Comment by corob-msft** [comment]
Can you give an example? I tried to see if I could get a warning without an explicit `void` in the parameter list using this code:

```c++
class X {
public:
    void mf() {}
};

int main() {
    X x;
    void (X::*pmf)() = &X::mf;
    (x.*pmf)();
}
```
This compiled with no warnings at /W4.

**Comment by SapphireSpire** [comment]
These are the files I created in Microsoft Visual Studio Community 2017, version 15.4.3.:
`//test_code.h
#pragma once

class Stuff {
	int a;
	int b;
public:
	void seta(int x) { a = x; }
	void setb(int x) { b = x; }
	int geta(void) { return a; }
	int getb(void) { return b; }
	int sum(void) { return a + b; }
};`
`//test_code.cpp
#include<iostream>
#include "test_code.h"
using namespace std;

int main() {
	Stuff things;

	things.seta(3);
	cout << "a is " << things.geta() << endl;

	things.setb(5);
	cout << "b is " << things.getb() << endl;

	cout << "a + b is " << things.sum() << endl;

	return 0;
}`

Strange thing is, if I move the class from the .h file to the .cpp file and remove the #include, it generates the error. It only compiles as long as the class is in the .h file.
