### ISSUE TITLE
<Inputs>$(TargetFileName)</Inputs> should be <...>$(ProjectDir)main.cpp</...>

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1291]
in section "To define what is executed by the custom build step"

because the command is `makecab.exe $(ProjectDir)main.cpp $(TargetName).cab`
$(TargetFileName) and $(ProjectDir)main.cpp are hardly the same thing, when i execute it as is, it always call makecab.exe

and
```
<CustomBuildStep Inputs="main.cpp" Outputs="$(Configuration)\$(TargetName).cab">
    <Command>makecab.exe main.cpp $(Configuration)\$(TargetName).cab</Command>
</CustomBuildStep>
```
is verbose, error prone, i'd like
```
<CustomBuildStep Inputs="main.cpp" Outputs="$(Configuration)\$(TargetName).cab">
    <Command>makecab.exe $(parent.inputs) $(parent.outputs)</Command>
</CustomBuildStep>
```

and when post this on docs.microsoft.com it screwed up my texts by replacing some characters into html entities, please see edit histroy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aea71b3-c087-e1b5-c8a3-9e70deb7330f
* Version Independent ID: 09ebda7f-2f42-2eac-8968-a33e4dfe546d
* Content: [How to: Add a Custom Build Step to MSBuild Projects](https://docs.microsoft.com/en-us/cpp/build/how-to-add-a-custom-build-step-to-msbuild-projects?view=vs-2019)
* Content Source: [docs/build/how-to-add-a-custom-build-step-to-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-add-a-custom-build-step-to-msbuild-projects.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@wangzimei thanks for the feedback. Topic has been updated and should be visible by Oct 16.
