### ISSUE TITLE
CustomBuild always before ClCompile regardless of <CustomBuildAfterTargets>

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1292]
my project file custom-build-tool.xml
```
<Project>
    <Import Project="main.xml" />

    <PropertyGroup>
        <CustomBuildBeforeTargets>Link</CustomBuildBeforeTargets>
        <CustomBuildAfterTargets>ClCompile</CustomBuildAfterTargets>
    </PropertyGroup>

    <ItemGroup>
        <CustomBuild Include="faq.txt">
            <Message>Copying readme...</Message>
            <Command>copy %(Identity) "$(OutDir)%(Identity)"</Command>
            <Outputs>$(OutDir)%(Identity)</Outputs>
        </CustomBuild>
    </ItemGroup>
</Project>
```
main.xml and the whole project is copied from [Walkthrough: Using MSBuild to Create a Visual C++ Project](https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=vs-2019)
command `msbuild custom-build-tool.xml`
msbuild version `16.1.76+g14b0a930a7`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b905566-4db7-32f1-38d6-f2f6d1e00234
* Version Independent ID: 7ef6e764-9e17-2a3b-9258-c10d098ddcbc
* Content: [How to: Add Custom Build Tools to MSBuild Projects](https://docs.microsoft.com/en-us/cpp/build/how-to-add-custom-build-tools-to-msbuild-projects?view=vs-2019)
* Content Source: [docs/build/how-to-add-custom-build-tools-to-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-add-custom-build-tools-to-msbuild-projects.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@wangzimei did you have a question or problem with this topic?

**Comment by wangzimei** [comment]
@mikeblome i had a problem in that i thought i found a bug that is
> CustomBuild always before ClCompile regardless of \<CustomBuildAfterTargets>

but after some more tests, i found the \<CustomBuildAfterTargets> PropertyGroup must be placed before

`<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Targets" />`

in order to take effect

**so no a bug in doc, but a bug in my code, problem solved**

(another problem) if place them before some imports is the requirement, should it be added to msdn doc?

**Comment by mikeblome** [comment]
@wangzimei thanks for the feedback. I'm closing this, but FYI you can always run msbuild /pp to see the order of the properties.
