### ISSUE TITLE
How to create a dll that use my tensorflow model?

### ISSUE THREAD

**Issue by wangxuesong29** [MicrosoftDocs/cpp-docs#1298]
I am using tensorflow to train a model. In the end, I would like to provide a dll for other softwares to use. Is this possible? Or should I use caffe？

**Comment by mikeblome** [comment]
@wangxuesong29 [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) is a much better place for this kind of question. Good luck!
