### ISSUE TITLE
Conflicting settings

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/cpp-docs#1300]
This page conflicts with the settings specified here: https://docs.microsoft.com/en-us/previous-versions/ms810829(v=msdn.10)#configuring-resource-pooling-from-the-registry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db22b48-345c-e8b5-1738-4be4854090c8
* Version Independent ID: 27a16b2a-ad5d-88f6-fe5e-2884b3066b3e
* Content: [Enabling and Disabling Services for a Provider](https://docs.microsoft.com/en-us/cpp/data/oledb/enabling-and-disabling-services-for-a-provider?view=vs-2019)
* Content Source: [docs/data/oledb/enabling-and-disabling-services-for-a-provider.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/data/oledb/enabling-and-disabling-services-for-a-provider.md)
* Product: **visual-cpp**
* Technology: **cpp-data**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@mdell-seradex thanks! This topic was incorrect and is fixed for 07-31.
