### ISSUE TITLE
psize clarification

### ISSUE THREAD

**Issue by plangevin** [MicrosoftDocs/cpp-docs#1301]
It is not clear if the psize argument will corresponds to the reserved size for both pipe direction or only one direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b68d264-1456-94ff-2898-557567cde992
* Version Independent ID: 4778fdc8-20b7-4f84-52ff-27201c4deb0c
* Content: [_pipe](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/pipe?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(%22CORECRT_IO%2F_pipe%22)%3Bk(_pipe)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019&WT.mc_id=email#feedback)
* Content Source: [docs/c-runtime-library/reference/pipe.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/pipe.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@plangevin 

Thanks for asking. The *psize* parameter is passed directly to the operating system, as a suggested buffer size for the pipe. There's only one memory buffer for a pipe, whether you're reading from it or writing to it. It wouldn't make sense to have more space to write to than you can read from, or vice-versa. I hope that clarifies things for you.
