### ISSUE TITLE
Example is wrong in section "Create your own command prompt shortcut"

### ISSUE THREAD

**Issue by jmairboeck** [MicrosoftDocs/cpp-docs#1304]
The example given in that section doesn't work and gives an error about not finding "C:\Program". The quotes are misplaced. The correct working  syntax would be:
    %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm uwp -vcvars_ver=14.16

The arguments must be put outside of the quoted path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019#create-your-own-command-prompt-shortcut)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jmairboeck 

Sometimes it takes a while, but thanks for pointing out the issue. The fix should appear tomorrow.
