### ISSUE TITLE
"Adding ATL Support to Your MFC Project" page is no longer applicable in VS2019

### ISSUE THREAD

**Issue by pizza2code** [MicrosoftDocs/cpp-docs#1307]
https://docs.microsoft.com/en-us/cpp/mfc/reference/adding-atl-support-to-your-mfc-project?view=vs-2019

This documentation is no longer applicable in Visual Studio 2019.  The wizard it refers to is no longer present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9a277c7-9a63-bb8d-6b8d-85b7a2178c48
* Version Independent ID: 9f81c54d-8f11-6179-890a-af3afedebc7d
* Content: [Adding ATL Support to Your MFC Project](https://docs.microsoft.com/en-us/cpp/mfc/reference/adding-atl-support-to-your-mfc-project?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/adding-atl-support-to-your-mfc-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/adding-atl-support-to-your-mfc-project.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@pizza2code thanks! The topic has been updated, along with several others. Be sure to set the version selector before viewing content to see correct content for VS2015 vs 2017 vs 2019.
