### ISSUE TITLE
Functions relocated to legacy_stdio_definitions.lib

### ISSUE THREAD

**Issue by spun69** [MicrosoftDocs/cpp-docs#1315]
There is no mention that these functions have been relocated to "legacy_stdio_definitions.lib".  Found this tidbit while tracking down unresolved symbol link errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb364ee-46da-e132-0020-ce4e4e6c352a
* Version Independent ID: 59c4fd5a-bb2e-3f78-0bff-ba2ab94f5943
* Content: [vsnprintf_s, _vsnprintf_s, _vsnprintf_s_l, _vsnwprintf_s, _vsnwprintf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@spun69 thanks for the feedback. I have updated the page to mention the new library and headers and also link to where this change is documented more thoroughly. (It's buried in the breaking changes history.) This fix should be public in 1-2 days.
