### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by karim** [MicrosoftDocs/cpp-docs#1317]
`echo %PATH%` does not print anything because `%` is a special char in Makefile and needs to be escaped. It should be `echo %%PATH%%`, or `echo "%PATH%"`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af30a352-8e46-7ffd-0917-e9ba72887c20
* Version Independent ID: f513616e-6aac-d560-76ce-b78e2933b761
* Content: [Environment-Variable Macros](https://docs.microsoft.com/en-us/cpp/build/reference/environment-variable-macros?view=vs-2019#feedback)
* Content Source: [docs/build/reference/environment-variable-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/environment-variable-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@karim thanks! Fix should appear by 07/10.
