### ISSUE TITLE
_MSC_VER needs to be updated for VS 16.1

### ISSUE THREAD

**Issue by erwanh1112** [MicrosoftDocs/cpp-docs#1320]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined Macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@erwanh1112 thanks! Fix should appear by 07/10
