### ISSUE TITLE
Missing pause

### ISSUE THREAD

**Issue by Sirmyself** [MicrosoftDocs/cpp-docs#1322]
`system("pause")` is missing in the code example of the test client _.cpp_ file. The code compiles, does what it has to, but then the console shuts down right away before I can read anything.

(on the DLL tutorial : https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019)

**Comment by corob-msft** [comment]
@Sirmyself When the sample is built and run as described in Visual Studio 2019 and Visual Studio 2017 version 15.9, the console window launched by VS automatically inserts a pause to allow you to look at the output. Adding a separate pause is an option, but it would be redundant.

**Comment by Sirmyself** [comment]
I see. I ran the code on VS community, don't know if my option is disabled or just unavailable.

**Comment by corob-msft** [comment]
@Sirmyself It should work exactly the same on VS Community. Which version are you using?

**Comment by Sirmyself** [comment]
VS Community 2017 version 15.7.1
