### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ewqzxc789123** [MicrosoftDocs/cpp-docs#1327]
very good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38efb50a-8551-fce2-79db-c778e90f3ca3
* Version Independent ID: 97b37bd0-68e1-b047-1afc-5ba6d8976f39
* Content: [memcpy, wmemcpy](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/memcpy-wmemcpy?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/memcpy-wmemcpy.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/memcpy-wmemcpy.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks.
