### ISSUE TITLE
Errors with the final working code.

### ISSUE THREAD

**Issue by Kafonin** [MicrosoftDocs/cpp-docs#1331]
Copy pasted the working version of the code (at the bottom) and got an error.

`Severity	Code	Description	Project	File	Line	Suppression State Error LNK2019	unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	windowsDesktopProject C:\Users\kafon\source\repos\windowsDesktopProject\MSVCRTD.lib(exe_main.obj)	1`

`Severity	Code	Description	Project	File	Line	Suppression State Error LNK1120	1 unresolved externals	windowsDesktopProject C:\Users\kafon\source\repos\windowsDesktopProject\Debug\windowsDesktopProject.exe	1`

**Comment by corob-msft** [comment]
@Kafonin 
I'm sorry you had trouble. I'm closing this, as there's no way for me to tell which document has the issue. If there's a specific article you were using, go back and use the feedback control there, to let us know there's a problem with that specific document. Thanks!
