### ISSUE TITLE
There is no such thing as a "Property Manager" item in the View menu.

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/cpp-docs#1333]
There is no such thing as a "Property Manager" item in the View menu in Visual Studio 2019.  Further, there is no way to edit a directory macro.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d320011e-7558-c4fc-04d8-31cbc2fda834
* Version Independent ID: 7b598fab-e8c1-d3a0-0fbf-730a7b2511a5
* Content: [Set C++ compiler and build properties in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=vs-2019#feedback)
* Content Source: [docs/build/working-with-project-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/working-with-project-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CLIRResearch 
Windows that are used less often are grouped in a **View** sub-menu. Use **View** > **Other Windows** > **Property Manager** to bring up the window, which is usually loaded as a tabbed window in the Solution Explorer space.

What kind of directory macro editing did you have in mind? Most of the existing directory macros are loaded from the environment, such as the SDK directories or VC include directories, or they're created from combinations of other properties, such as the root of the solution and various configuration-specific subdirectories for source files or build output. Generally speaking, you'd break the build if you tried to edit them. It's pretty easy to add source or include directories or to change output directories in the project's Properties pages, which will change what the macros evaluate to, without fiddling with them directly.

**Comment by corob-msft** [comment]
Closing. It appears that some updates a couple of weeks ago addressed the initial complaint.
