### ISSUE TITLE
There is no such thing as "User Macros" on the left-hand side of "Property Pages".

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/cpp-docs#1334]
In Visual Studio 2019, there is no entry called "User Macros" in the list on the left-hand side of "Property Pages".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d320011e-7558-c4fc-04d8-31cbc2fda834
* Version Independent ID: 7b598fab-e8c1-d3a0-0fbf-730a7b2511a5
* Content: [Set C++ compiler and build properties in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=vs-2019#feedback)
* Content Source: [docs/build/working-with-project-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/working-with-project-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CLIRResearch 
There is an entry for User Macros only if the property pages you're looking at are for a *.user* properties file, not a project or source file.

**Comment by CLIRResearch** [comment]
This is an older solution that was automatically updated from VS2015 to VS2019.

 

The updated solution contains a trailing backslash for  $(SolutionDir). Some of the evaluated include paths are showing up with a double backslash before “include”.

 

The macros are an issue as we need to move this solution to source control.  We would like the solution the build identically on any development box.  

 

I have not been able to find anything for the solution in the <userprofile>\AppData\Local\Microsoft\MSBuild\v4.0\ folder for this solution.  If I take the solution offline, the paths with the double backslashed in front of “include” in the VC++ Directories show up in the XML of the solution.

 

The best solution may be to scrap the existing solution (automatically updated from VS2015) and build a new solution in VS2019.
