### ISSUE TITLE
How to turn off optimize in my cmake project with visual studio

### ISSUE THREAD

**Issue by Laioyu** [MicrosoftDocs/cpp-docs#1335]
[Enter feedback here]
I was developing c++ with Visual Studio 2019 + Cmake + Clang , but there are some optimize behavior that I don't wan't when I debugging my program. I have no way to search the optimize option. Who can tell me how to close the optimize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by merlynoppenheim** [comment]
Optimization is off by default for Debug configurations.   To see or modify flags passed to clang-cl, in Open CmakeSettings editor (for example, double click CmakeSettings.json from your project).   Check 'Show advanced variables'.  Type 'flags' in the filter.  (Note that MSVC-style cl.exe flags are used on Windows and gcc-style flags are used for Linux).

**Comment by Laioyu** [comment]
Thank for your help.
I can't find any item about optimization. In fact, I am not sure it is optimization cause the result of the program is not what I imagined. But the Locals window shows some message of below when I was debugging.

![image](https://user-images.githubusercontent.com/33061113/61310139-47e62700-a826-11e9-97c8-d9ab6b778c3c.png)

There are my  CmakeSettings.json
```json
{
    "configurations": [
        {
            "name": "x64-Debug",
            "generator": "Ninja",
            "configurationType": "Debug",
            "inheritEnvironments": [ "msvc_x64_x64" ],
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "-v",
            "ctestCommandArgs": "",
            "variables": []
        },
        {
            "name": "x64-Clang-Debug",
            "generator": "Ninja",
            "configurationType": "Debug",
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "-v",
            "ctestCommandArgs": "",
            "inheritEnvironments": [ "clang_cl_x64" ],
            "variables": [
                {
                    "name": "CMAKE_CXX_COMPILER",
                    "value": "C:/Program Files/LLVM/bin/clang-cl.exe",
                    "type": "FILEPATH"
                },
                {
                    "name": "CMAKE_C_COMPILER",
                    "value": "C:/Program Files/LLVM/bin/clang-cl.exe",
                    "type": "FILEPATH"
                },
                {
                    "name": "CMAKE_MAKE_PROGRAM",
                    "value": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\\ninja.exe",
                    "type": "FILEPATH"
                }
            ]
        }
    ]
}
```
and there are my code 
```cpp
        fd_set fs_read;
	fd_set fs_write;
	fd_set fs_exp;


	while (true)
	{
		//5 accept client socket connect;
		
		FD_ZERO(&fs_read);
		FD_ZERO(&fs_write);
		FD_ZERO(&fs_exp);

		FD_SET(sock_server, &fs_read);
		FD_SET(sock_server, &fs_write);
		FD_SET(sock_server, &fs_exp);

		int ret_select = select(
			sock_server + 1,
			&fs_read,
			&fs_write,
			&fs_exp,
			NULL);

		if (ret_select < 0)
		{
			printf("select 任务结束");
			break;
		}

		for (size_t i = 0;i < socks_clients.size();++i)
		{
			FD_SET(socks_clients[i], &fs_read);
		}

		if (FD_ISSET(sock_server, &fs_read))
		{
			FD_CLR(sock_server, &fs_read);

			sockaddr_in sin_client = {};
			int size_sin_client = sizeof(sockaddr_in);
			SOCKET sock_client = INVALID_SOCKET;
			sock_client = accept(sock_server, (sockaddr*)& sin_client, &size_sin_client);
			if (INVALID_SOCKET == sock_client)
			{
				printf("error:cannot accept a invalid socket connect\n");
			}
			printf("a client of IP:%s connected!\n", inet_ntoa(sin_client.sin_addr));

			socks_clients.push_back(sock_client);
		}

		//6.handle cmd 
		for (size_t i = 0;i < fs_read.fd_count;++i)
		{
			printf("%d", (int)i);
			int ret_handle = handle(fs_read.fd_array[i]);
			if (-1 == ret_handle)
			{
				auto iter = find(
					socks_clients.begin(),
					socks_clients.end(),
					fs_read.fd_array[i]);
				if (iter != socks_clients.end())
				{
					socks_clients.erase(iter);
				}
			}
		}
	}

	//close client sockets
	for (size_t i = 0; i < socks_clients.size();++i)
	{
		closesocket(socks_clients[i]);
	}
```

**Comment by Laioyu** [comment]
I am developing WinSock programs by using Clang+Cmake+VS2019 in windows platform, may be it is a horrible idea.

**Comment by mikeblome** [comment]
@Laioyu Maybe you can ask on [developer community](https://developercommunity.visualstudio.com/topics/C%2B%2B.html) whether anyone has tried this before.

**Comment by Laioyu** [comment]
Sure enough, the abnormality of program caused by the unknown conflict between the Clang compiler and the Winsock library, The windows program is still suitable for vc++ development. 

![image](https://user-images.githubusercontent.com/33061113/61338442-0e380f00-a86c-11e9-85b3-e3ece49ad428.png)
