### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by chenderen** [MicrosoftDocs/cpp-docs#1342]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e946d01e-fd47-5f2f-fb02-193b1e2c0aba
* Version Independent ID: d8aebea2-132d-f77f-1584-73b39745e96e
* Content: [Linker Tools Error LNK1000](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1000?view=vs-2019)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1000.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1000.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing for a lack of actionable feedback.
