### ISSUE TITLE
Problem linking glfw

### ISSUE THREAD

**Issue by Lkledu** [MicrosoftDocs/cpp-docs#1343]
hi i'm trying to create a .bat in vscode to build a c++ project that uses glfw. I'm using the example code in documentation to test the build with msvc, but te link.exe returns me LNK2019 (i constantly think that error is like the actual year can't be a coincidence). I'm using the .dll, .lib and .dll.lib who I downloaded froom the binary files in the glfw site. I try the x86 an 64, both with the same error.
I open a post in khronos forum of opengl too.
https://community.khronos.org/t/vscode-problem-lnk-msvc/104321

**Comment by corob-msft** [comment]
@Lkledu 
While I'm sorry you're having trouble building something, this issues area is for reporting problems with the MSVC documentation, not for support. If the many, *many* ways to [cause and fix a LNK2019 error described in the error article](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-error-lnk2019) don't help, then I suggest you follow up in the other forums suited to questions like yours.
