### ISSUE TITLE
formatting isssue

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1356]
There are two formatting issues in this page
![tempsnip](https://user-images.githubusercontent.com/32254161/61516832-5e63cc80-aa38-11e9-909b-6f5d5a04808a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49925079-0727-b01d-3b83-2492d42c82ff
* Version Independent ID: 5a653ade-25fb-2982-ff52-ed1e32f517cb
* Content: [CMDIChildWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmdichildwnd-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmdichildwnd-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmdichildwnd-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@songxia233 
That does look strange, but unfortunately, the code colorization is not under our control. That's done by some third-party extension that the website production team has added. Sometimes it does unexpected things. We can't do much about it.
