### ISSUE TITLE
Missing expression syntax. Examples allow #if to use expressions: DLEVEL == 0, or DLEVEL > 0, but DLEVEL != 0 does not work. 

### ISSUE THREAD

**Issue by markyoung143** [MicrosoftDocs/cpp-docs#1359]
What are the operators allowed in #if expression ? They are ==, &gt;, &lt;, and what else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7bf772-9265-68cd-a8d7-68c938987e2a
* Version Independent ID: f70281a8-b576-3f1f-ea2b-fb4abe39c206
* Content: [#if, #elif, #else, and #endif Directives (C/C++)](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp?view=vs-2019)
* Content Source: [docs/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@markyoung143 
Whether you can use `DLEVEL != 0` depends entirely on what `DLEVEL` expands to. For example, if it expands to nothing, then the compiler will complain. There's otherwise no restriction keeping you from using the `!=` operator as part of an integer-valued [constant expression](https://docs.microsoft.com/cpp/cpp/cpp-constant-expressions) in a `#if` or `#elif` directive. You can in fact use any operator that can be evaluated at compile time as part of an integer-valued constant expression, with a few explicitly listed exceptions, such as `sizeof`, assignment, or the comma operator. You can do integer math, for example, in addition to using the relational operators. 

Closing, as this seems like a support issue, not a documentation issue.

**Comment by markyoung143** [comment]
I think you missed my point. DLEVEL is what the doc used as an example. It does not matter at all. I was stating the documentation does not tell you what syntax is allowed (except for the examples given using == and >). In fact != does not work and I'd like to know what can be used to indicate "not equal", as well as know the complete list of operators support for this syntax

**Comment by corob-msft** [comment]
I can assure you that `!=` works just fine, and that it would be grossly redundant to list every possible operator that can be used in every article (there are about ninety of them) that mentions constant expressions. Just about any arithmetic, logical, bitwise, or relational operator can work, if the preprocessor macros in use have the right values when expanded.

Here's an example with `!=` I made up using part of the sample code in the article:

```cpp
// ifnotequal.cpp
// test a preprocessor directive
#include <iostream>

//#define DLEVEL
// uncomment the above line to see what the compiler
// does if a macro value is defined as nothing.
// Expect error C1017 on line 10 in this case.

#if DLEVEL != 5
    #define SIGNAL  1
    #if STACKUSE == 1
        #define STACK   100
    #else
        #define STACK   200
    #endif
#else
    #define SIGNAL  2
    #if STACKUSE == 1
        #define STACK   300
    #else
        #define STACK   400
    #endif
#endif

int main()
{
    std::cout << "SIGNAL + STACK = " << SIGNAL + STACK << "\n";
}
```

And here are a few different invocations, given different values for preprocessor macros on the command line:

```cmd
C:\Users\corob\Documents\Projects\curiosity\ifnotequal>cl /EHsc /W4 /nologo ifnotequal.cpp
ifnotequal.cpp

C:\Users\corob\Documents\Projects\curiosity\ifnotequal>ifnotequal
SIGNAL + STACK = 201

C:\Users\corob\Documents\Projects\curiosity\ifnotequal>cl /EHsc /W4 /nologo /DSTACKUSE ifnotequal.cpp
ifnotequal.cpp

C:\Users\corob\Documents\Projects\curiosity\ifnotequal>ifnotequal
SIGNAL + STACK = 101

C:\Users\corob\Documents\Projects\curiosity\ifnotequal>cl /EHsc /W4 /nologo /DDLEVEL#5 ifnotequal.cpp
ifnotequal.cpp

C:\Users\corob\Documents\Projects\curiosity\ifnotequal>ifnotequal
SIGNAL + STACK = 402
```

**Comment by markyoung143** [comment]
I see your point. I could not get the code below to work until you told me != was indeed supported and I then realized I needed to cast 18 to an enum storage type. In my defense, both the Intellisense and compiler error were not helpful: cdisk.cpp(2315): fatal error C1189: #error:  "Need to add new bus type to pBusTypes[]", gave me no clue. If the operators supported are numerous and you don't want to list them in 90 places, that is fine, but in this case I could not find *any* reference to the operators allowed for constant expressions. You can consider this closed, and I will consider myself sowewhat too dependent on Intellisense :) 
  #if BusTypeMax != (STORAGE_BUS_TYPE)18
  #error "Need to add new bus type to pBusTypes[]"
  #endif

typedef enum _STORAGE_BUS_TYPE {
    BusTypeUnknown = 0x00,
    BusTypeScsi,
    BusTypeAtapi,
...
    BusTypeNvme,
    BusTypeMax,
    BusTypeMaxReserved = 0x7F
} STORAGE_BUS_TYPE, *PSTORAGE_BUS_TYPE;
