### ISSUE TITLE
Extremely unhelpful. 

### ISSUE THREAD

**Issue by alexjheck** [MicrosoftDocs/cpp-docs#1360]
This page is ab-so-lutely unhelpful. It only gave me information that I already read in my debugging error list. 

Why not suggest some common causes or ways to fix the issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6967b409-0e48-d72e-8ed6-1c429ecead02
* Version Independent ID: 0b6ebb5b-d15c-5e37-4a9d-0d81aba9f2cc
* Content: [Linker Tools Error LNK1120](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1120?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1120)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1120.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1120.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@alexjheck 
Sorry you didn't find this helpful. There's only one way to fix error LNK1120, which is by fixing all the preceding [LNK2001](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-error-lnk2001) and [LNK2019](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-error-lnk2019) errors. Information on how to identify and fix these errors is found in the linked topics. LNK1120 can't appear as the only linker error, and it can't be resolved independently. 
Is there some other information you were hoping to see here?

**Comment by alexjheck** [comment]
Colin,

Thank you for getting back to me. I figured out the problem with my code,
thank you. At the time there was only the one error message and it was
confusing.

As a student, I visit the Microsoft Docs help page frequently and have felt
on multiple occasions that the site needs to provide more information about
error messages and how to fix them. Many times I have come across a page
that tells me no more than what my error message says. In that case, I
would find that page unhelpful and a waste of time.

Thanks again for the response and for considering my request for the
elaboration of errors on your help page.

-Alex

**Comment by corob-msft** [comment]
Resolving, as a request for general improvements is pretty much what we're doing all the time. 🍰

**Comment by silence48** [comment]
we can tell... (sarcasm)
