### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Const-me** [MicrosoftDocs/cpp-docs#1362]
I’ve followed installation carefully, bootstrap-vcpkg.bat printed many pages of text but at the end it printed “Building vcpkg.exe... done.”
When I type `vcpkg search` at the command prompt, I’m, getting error:
'vcpkg' is not recognized as an internal or external command, operable program or batch file.

Do you have an MSI? Or at least the complete installation guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg-- A C++ package manager for Windows, Linux and MacOS](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019)
* Content Source: [docs/build/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by NenadNRakas** [comment]
Try add the path to the .\vcpkg.exe or navigate to the folder...

**Comment by cirobruno** [comment]
Awful.
I've been spending too much time trying to set thing to work in Visual Studio Code. But so far, dozens of tips and tricks. I wouldn't myself be able to tell someone how to get were I am now.
Is Visual Studio Code really meant to be a professional, portable and productive platform for fast development?
I guess it's better go to Microchip IDE or Atmel Studio or even Arduino IDE. They've got all resources built in and work fine!!!

**Comment by Const-me** [comment]
@cirobruno Apparently, they had a weird idea that just because users are C++ programmers, they would enjoy building a package manager with the same compiler.

**Comment by cirobruno** [comment]
Must be...
Otherwise, just insanity!

**Comment by cirobruno** [comment]
Have you been able to perform any of these charades?

**Comment by Const-me** [comment]
@cirobruno Yes, I actually got it working.
They don’t have any installer, nor dependencies database. Apparently, the workflow they support — you `git clone` the vcpkg into some persistent location, build vcpkg.exe, leave it there, and use command-line shell to do stuff. The workflow is complicated and not particularly user friendly.

If you need custom config (I did, wanted to build a few packages into static libraries, with DLL link to C runtime), create custom triplet in `triplets` subfolder. In their terminology, a triplet = project configuration, platform, plus a few other settings. If you don't need custom ones, use a built-in like `x64-windows`

Patch packages in ports subfolder fixing broken ones (the whole thing is unreliable, some packages are broken and don't compile).

Run `vcpkg install somePackage:triplet` to compile `somePackage` using the `triplet` config.

Run `vcpkg export somePackage:triplet otherPackage:triplet --nuget --nuget-id=something --nuget-version=1.0.42` to pack previously compiled packages into nuget.

Finally, you can forget about vcpkg, and instead consume the nuget package you’ve built. Unlike vcpkg, nuget is integrated into visual studio and just works. Also it's compatible with teams, only one person need to jump through these hoops and waste electricity compiling sources, other developers can consume nuget packages. Only sometimes you need to patch the consuming .vcproj files, adding `<VcpkgTriplet ...>` elements there.

**Comment by cirobruno** [comment]
Thank you for your description.
Even though, that's too much!  Moreover, I'm using Mac OS, so I guess I'll have to find it out by myself.
My job is just to program microcontrollers such as Atmel, Arduino, Espressif, etc. I intended to make something as portable as possible. That's why I came to VS Code. 
But I'm absolutely disappointed. Too big learning process to learn and it won't worth it.
Nevertheless, thank you.
Keep in touch.
Regards,
Ciro (cirobruno@yahoo.com)

**Comment by Const-me** [comment]
@cirobruno You’re welcome.

As you see, the usability is not great even on Windows. But technically, the workflow probably works for other targets, too.

You definitely need to create a custom triplets for your target platforms. Can’t help you with that, I only program for Windows and Linux, and only for PC and ARM.

And you need different `vcpkg export` command. With different arguments, it can package results into ZIP files, you’ll get a ZIP file with all headers + compiled libraries, dynamic or static ones depending on the triplet.

I don’t have much experience with vcpkg. But based on what I know, I think it only pays off for large libraries with tons of dependencies. If you only need a few simple ones, and if you don’t need nuget packages (on Windows they are nice, contain everything you need to consume a library, and include relevant parts of project setup to do so), not sure vcpkg is good enough.

**Comment by cirobruno** [comment]
Thank you.
I'm afraid I'm taking too much of your time. I'll try to make it short and don't worry when you can't help.
The idea of gathering all used resources and packaging them into a single file sounds very interesting.
What's a triplet in this context?
Thank you.
Regards

**Comment by Const-me** [comment]
@cirobruno A triplet is a combination of target platform, OS, and a few other settings. You specify name of the triplet when you build libraries with vcpkg. Then, if you’re lucky and they build without errors, you also specify triplets when you export the built libraries.

Vcpkg ships [with a few built-in ones](https://github.com/microsoft/vcpkg/tree/master/triplets ) but as you see there’s nothing for AVR, and ARM ones are only for Windows. You can create custom ones, by adding text files into that subfolder of vcpkg.

**Comment by mikeblome** [comment]
@cirobruno Sorry to hear you are having trouble. Here is the [documentation for vcpkg](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019). Currently it only explicitly covers Visual Studio, and Windows but it should help you get up and running on MacOS. Feel free to reopen this issue if you have further questions.
