### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by caowenyuan888** [MicrosoftDocs/cpp-docs#1366]
the example of Width specification is error
printf("%0*f", 5, 3); /* 00003 is output */

I think it should be printf("%0*d", 5, 3);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bd3fde-7eae-a126-f330-563d912a1fab
* Version Independent ID: b6f2df29-3154-05ec-4c9b-9dbd8c316dd3
* Content: [Format Specification Syntax: printf and wprintf Functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@caowenyuan888 You're right. A fix is in progress.

**Comment by TylerMSFT** [comment]
Closing per fix submitted by corob-msft.
