### ISSUE TITLE
Snippet missing in cpp-docs/docs/cppcx/wrl-integration-c-cx.md

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/cpp-docs#137]
1. Visit https://docs.microsoft.com/en-us/cpp/cppcx/wrl-integration-c-cx
2. Notice snippet just says "master"

**Comment by corob-msft** [comment]
Thanks for pointing out the issue. The snippet was there at the bottom all along; there was just some stray merge marker stuff that hadn't been deleted. A fixed version is now live.
