### ISSUE TITLE
AgileEventSource is undocumented

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/cpp-docs#139]
I don't see any documentation for `AgileEventSource`. It's in WRL in `event.h`. I learned of it from the [in-process WRL WinRT Component sample](https://github.com/Microsoft/Windows-universal-samples/blob/ad44f9b846b7064a0dd6eca8b0b7a453902e4a22/Samples/WRLInProcessWinRTComponent/cpp/Server/OvenServer.cpp#L67).

Adam Comella
Microsoft Corp.

**Comment by mikeblome** [comment]
Thanks Adam! I've added this to our backlog.

**Comment by mikeblome** [comment]
content added: https://docs.microsoft.com/en-us/cpp/windows/agileeventsource-class

**Comment by rigdern** [comment]
@mikeblome Thanks! I looked at the doc that was just added and saw the phrase "agile event" but I couldn't find a description of what this phrase means conceptually. I filed #197.

**Comment by mikeblome** [comment]
I'll add a link to this page, which AFAIK is the best explanation of the subject. It applies to WRL as well as C++/CX: https://docs.microsoft.com/en-us/cpp/cppcx/threading-and-marshaling-c-cx

**Comment by rigdern** [comment]
That page talks about "agile classes" but doesn't mention "events" anywhere. Are there any additional semantics for "agile events"?

**Comment by mikeblome** [comment]
Not as far as I know. Agile events are fired by agile classes/components and are the most common case by far; they should just work. It's events fired by non-Agile components that might need extra care wrt which thread you handle them on. If you run into issues or have a more specific question I can try to get an answer from the dev team.
