### ISSUE TITLE
Example Working Code

### ISSUE THREAD

**Issue by greggwon** [MicrosoftDocs/cpp-docs#1406]
There needs to be real working examples here.  If tooltips don't appear, devs need to be able to look here and see a definitive list of reason why tips would not appear.  This includes any kind of "repainting" or other events which might reset timers or otherwise cause problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cc82441-df8e-5fa6-47b1-8d9b8c09df8b
* Version Independent ID: d2bb0732-b44c-91dd-ad6e-1f7c479b4b21
* Content: [Using CToolTipCtrl to Create and Manipulate a CToolTipCtrl Object](https://docs.microsoft.com/en-us/cpp/mfc/using-ctooltipctrl-to-create-and-manipulate-a-ctooltipctrl-object?view=vs-2019#feedback)
* Content Source: [docs/mfc/using-ctooltipctrl-to-create-and-manipulate-a-ctooltipctrl-object.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/using-ctooltipctrl-to-create-and-manipulate-a-ctooltipctrl-object.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by TylerMSFT** [comment]
Unfortunately, I am unable to invest in new MFC documentation.

**Comment by greggwon** [comment]
What an awesome response to a two year old ticket.  Makes everyone feel like Microsoft has interest in help developers be productive.   How awesome for you to create a toolkit that's deficient yet part of decade old software systems that work and have to be maintained.  You can't invest one time in documentation but instead inspect your customers to spend 1000x the cost to rewrite their applications.  How novel!
