### ISSUE TITLE
Word spelled incorrectly

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/cpp-docs#1410]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1728) by @Taylor-Hasterd**

Link to article:
https://docs.microsoft.com/en-us/cpp/cpp/stdcall?view=vs-2019

Problem:
In the article, the word "caller" is spelled as "callee" in the first sentence of the article.
The sentence is:

The __stdcall calling convention is used to call Win32 API functions. The callee cleans the stack, so the compiler makes vararg functions __cdecl. Functions that use this calling convention require a function prototype.

**Comment by corob-msft** [comment]
@ryanmajidi 
The documentation is correct. In the `__stdcall` convention, the called function (the "callee") is responsible for cleaning up the stack when it returns. This differs from the default convention, `__cdecl`, where the calling function (the "caller") is responsible for cleaning up the stack after the called function returns.
