### ISSUE TITLE
what's the purpose of struct deleter in some examples? 

### ISSUE THREAD

**Issue by hongsoog** [MicrosoftDocs/cpp-docs#1450]
what's the purpose of ```struct deleter``` in some examples of ```weak_ptr```? 
It might be redundant code made by accident and should be removed for clear understanding of examples.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d643a044-5146-a180-46f7-395a639c9dd7
* Version Independent ID: 73905ddf-928d-c1f5-3d02-624d81114c9f
* Content: [weak_ptr Class](https://docs.microsoft.com/en-us/cpp/standard-library/weak-ptr-class?view=vs-2019#feedback)
* Content Source: [docs/standard-library/weak-ptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/weak-ptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hongsoog 
I think you're right. It's a functor that deletes its argument, and it might be intended as an extra parameter to one of the shared_ptr constructor calls, but it's not actually used or needed.
