### ISSUE TITLE
Steps shown are misleading and incorrect

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#1455]
In VC++ 2019, it's apparently no longer possible to create a console app with MFC support.  I don't know why we got rid of that.  But the steps shown here say to follow the instructions to create C++ console app project, and then give instructions to select an MFC Application template wizard. Creating a console app without MFC, and then creating an MFC application (which doesn't offer console as an application type) does not yield a console app that supports MFC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0128902a-afb9-2399-a378-3d5d6ca046b4
* Version Independent ID: 484ada2f-c1ed-1a3d-9d19-5bbfcb1cc705
* Content: [Creating an MFC Application](https://docs.microsoft.com/en-us/cpp/mfc/reference/creating-an-mfc-application?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/creating-an-mfc-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/creating-an-mfc-application.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@ScotBren 
It's still possible to create MFC Console apps, but it's not obvious how:

1. Choose **File** > **New** > **Project** from the menubar.
2. In the **Create a new project** dialog, select the **Windows Desktop Wizard** template, then choose **Next**.
3. Fill in the project configuration settings, and then choose **Create**.
4. In the **Windows Desktop Project** dialog box, select **Console Application** in the **Application type** dropdown, then under **Additional Options** select the **MFC Headers** checkbox. Choose **OK** to create your MFC console app.

The documentation is also completely wrong about how to create any other sort of MFC project. For other kinds of MFC projects, you can choose **MFC Dynamic-Link Library**, **MFC ActiveX control**, or **MFC App** project templates. The last one has the wizard that lets you choose your app's SDI/MDI settings, toolbars, document templates, resources, and so on. The directions about creating a regular console app first are bogus in VS2019, and we'll fix it.

**Comment by mikeblome** [comment]
Thanks @ScotBren topic has been updated.
