### ISSUE TITLE
should be utf-32?

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1457]
please search "with the U prefix is a UTF-32 character" in this page, in the section there is a word "utf-8", i believe it should be utf-32?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ebb90bf-a25a-cb4c-56d0-d46cc341d14b
* Version Independent ID: e709e8b2-2a41-f66b-26cd-762a631817cc
* Content: [String and Character Literals  (C++)](https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/string-and-character-literals-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/string-and-character-literals-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@wangzimei Fixed, thanks for pointing that out.
