### ISSUE TITLE
Curious about the macro, "WIN32", and others defined in minwindef.h

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/cpp-docs#1459]
I see that the macro `WIN32` is always defined if the user `#includes <minwindef.h>` or `#includes <Windows.h>` in a C++ project, so I'm wondering if the macro `WIN32` is still used commonly?

If yes, should the macros in the header file `minwindef.h` be included on this page, or it will be in a separate Windows specific article about Windows macros?

Are we discouraged from using `minwindef.h` and should follow the conventions of using only the macros with the leading underscores listed in this page?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined Macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@tommai78101 

Good question. The important distinction here is *predefined*. This page lists the macros the compiler may define *before* any macros defined by source code (or in the project files, or on the command line) are created. Anything defined in the headers for Windows or MFC or WinRT is not part of the predefined macros, so it won't be mentioned here.
