### ISSUE TITLE
How to implement a preprocessor statement

### ISSUE THREAD

**Issue by tlwu** [MicrosoftDocs/cpp-docs#1460]
I'm trying to write a project-scope preprocessor statement for the following code:
"#define LOG(level) \
if (level &gt; logger.getReportLevel()) ; else logger.log(level)"
However, I cannot figure out where to edit this in VC++. I was thinking to put "LOG(level)" and "if (level &gt; logger.getReportLevel()) ; else logger.log(level)" into somewhere. I tried
Configuration Properties -&gt; C/C++ -&gt; Preprocessor -&gt; Preprocessor Definitions -&gt; &lt;Edit...&gt;
But the "Evaluated value" field cannot be edited. Thanks for any advice! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8649ec5-09cf-8157-8bbb-f71dc329b669
* Version Independent ID: d991cbe7-79f0-a43d-5331-f16e9632deab
* Content: [Preprocessor Directives](https://docs.microsoft.com/en-us/cpp/preprocessor/preprocessor-directives?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/preprocessor-directives.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/preprocessor-directives.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@tlwu 
Sorry you're having trouble. The top edit box is where you add definitions; the **Evaluated value** field shows the result of any inherited definitions along with the definitions you add. Each preprocessor definition is passed to the compiler command line as the argument to a [/D](https://docs.microsoft.com/en-us/cpp/build/reference/d-preprocessor-definitions?view=vs-2019) option. It's better to define complex function-like macros in your source code, say, in a common header file, and use simple preprocessor definitions at project level (think `/DLOGLEVEL=0`) to turn them on and off. 

Closing, as this is a support question, and only peripherally related to the document.
