### ISSUE TITLE
Invalid links to the  SCROLLINFO structure

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/cpp-docs#1461]
The link provided results in 404 page:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagscrollinfo

The invalid link can be found [here](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CUNLIMITEDLISTBOX%2FCUnlimitedListBox%3A%3AGetScrollInfo)%3Bk(CUnlimitedListBox%3A%3AGetScrollInfo)%3Bk(AFXWIN%2FCListBox%3A%3AGetScrollInfo)%3Bk(AFXWIN%2FCWnd%3A%3AGetScrollInfo)%3Bk(CListBox%3A%3AGetScrollInfo)%3Bk(CWnd%3A%3AGetScrollInfo)%3Bk(GetScrollInfo)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019#getscrollinfo).

_You do know that the real usable documentation on the MSDN pages had been working just fine for decades before you started to delete and make a mess of it all.
No one thought it might be a good idea to leave the old documentation just as it was until you got the new one ready and working?_

I managed to find what might be the real msdn documentation page in web.archive.org: [SCROLLINFO structure](https://web.archive.org/web/20190730085257/https://msdn.microsoft.com/en-us/data/bb787537(v=vs.80))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f567a739-943e-c85d-07a1-d43229fa6d4e
* Version Independent ID: c41ddd0d-df30-7ac0-407b-d7a9c9a18478
* Content: [CWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CUNLIMITEDLISTBOX%2FCUnlimitedListBox%3A%3AGetScrollInfo)%3Bk(CUnlimitedListBox%3A%3AGetScrollInfo)%3Bk(AFXWIN%2FCListBox%3A%3AGetScrollInfo)%3Bk(AFXWIN%2FCWnd%3A%3AGetScrollInfo)%3Bk(CListBox%3A%3AGetScrollInfo)%3Bk(CWnd%3A%3AGetScrollInfo)%3Bk(GetScrollInfo)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019#getscrollinfo)
* Content Source: [docs/mfc/reference/cwnd-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cwnd-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Bartolomeus-649 
Thanks for spotting this issue. I've updated the links to point to [SCROLLINFO](https://docs.microsoft.com/windows/win32/api/winuser/ns-winuser-scrollinfo) in all the C++ articles it appears in. These updates should be live by tomorrow mid-day.
