### ISSUE TITLE
How to set program parameters

### ISSUE THREAD

**Issue by bcsanches** [MicrosoftDocs/cpp-docs#1464]
Folks,

how do I set arguments for lauching my executable, for example:
myexecutable -parameter something

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001834ce-31d2-e768-1df1-4a776aa9ef65
* Version Independent ID: 45f15fc0-e5c7-34a1-2469-f38d304ef5bd
* Content: [Deploy, run, and debug your C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019)
* Content Source: [docs/linux/deploy-run-and-debug-your-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/deploy-run-and-debug-your-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@bcsanches 
It's shown, but not called out, right on this page in the [Debug your Linux project](https://docs.microsoft.com/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#debug-your-linux-project) section. Check out the **Program Arguments** property on the [Debugger Properties](https://docs.microsoft.com/cpp/linux/prop-pages/debugging-linux?view=vs-2019) page of the **Property Pages** dialog, about five up from the highlighted **Debugging Mode** property in the picture.

@mikeblome Should this get a special mention here? Seems like a common question.

**Comment by bcsanches** [comment]
Sorry, for the lack of the information, I am using a cmake project. 

I switch Solution Explorer to targets view and selected debug settings.

I got a json file with the settings, but cannot figure out which setting should I use to enter program arguments: https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=vs-2019 

This is the launch.vs.json that I got:

`{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "default",
      "project": "CMakeLists.txt",
      "projectTarget": "Launcher.exe (bin\\Launcher.exe)",
      "name": "Launcher.exe (bin\\Launcher.exe)"
    }
  ]
}`

thank you

**Comment by corob-msft** [comment]
Ah, you want to [specify arguments for debugging](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#specify-arguments-for-debugging). Those are in the launch.vs.json file.

**Comment by corob-msft** [comment]
As in the example, you might want to change the "name" value to reflect the arguments you use, since apparently you can set up different ones and switch configurations.

**Comment by bcsanches** [comment]
great! Almost there, but having some trouble here. I am not sure if this channel is for documentation only or for runtime, so please let me know.

- I switched solution explorer to "Targets View", then right clicked on my target project and selected "Debug and launch settings"

- this got me to "launch_schema.json"

`{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "Launcher (bin\\Launcher)",
      "project": "CMakeLists.txt",
      "projectTarget": "Launcher (bin\\Launcher)",
      "cwd": "${debugInfo.defaultWorkingDirectory}",
      "program": "${debugInfo.fullTargetPath}",
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "${debugInfo.remoteMachineName}",
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}",
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}",
          "/p",
          "${debugInfo.parentProcessId}",
          "/c",
          "${debuggerCommand}",
          "--tty=${debugInfo.tty}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
  ]
}`

havent touched the file, but now when I press F5 or try to start debug, it fails:

![image](https://user-images.githubusercontent.com/1449621/62239899-23ed1e80-b3ac-11e9-9efe-8932e91fbc37.png)

After pressing OK:

![image](https://user-images.githubusercontent.com/1449621/62239926-3404fe00-b3ac-11e9-9a06-af40e3438de7.png)

And no debug anymore... if I delete the entire folder, clone again from git, it works , but if I repeat this process, it breaks.

My project on github: 
https://github.com/bcsanches/DCCLite

Thank you

**Comment by paulmaybee** [comment]
What configuration have you selected (for example WSL_Debug, or Linux-DEBUG)?

**Comment by bcsanches** [comment]
WSL - debug

**Comment by paulmaybee** [comment]
For WSL you need a different pipe configuration. Try replacing the entire pipeTransport element in launch.json with
```
      "pipeTransport": {
        "pipeProgram": "${debugInfo.windowsSubsystemPath}",
        "pipeArgs": [
          "${debuggerCommand}",
          "--tty=${debugInfo.tty}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
```

**Comment by bcsanches** [comment]
That worked perfectly! I even was able to add the "args" element and worked perfectly!

I hope you guys fix this, because being able to debug and compile linux software directly on Visual Studio is really nice.

Thank you for your help and support!

**Comment by bcsanches** [comment]
A second thing, perhaps you already have seem: 

- Every time I right click on a cmake target (on solution explorer) and select "Debug and Launch settings", it opens the launch_schema.json, but it adds a entire new configuration, instead of simple letting me edit the existing one. The old one is kept, but the file keeps growing.

thank you

**Comment by corob-msft** [comment]
@bcsanches 
Yes, that's [an issue that's already been reported](https://developercommunity.visualstudio.com/content/problem/526370/cmake-cmakeliststxt-debug-and-launch-settings-ther.html) on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). You can add a vote to give the problem a higher priority. When you find an issue that hasn't been reported yet, follow the instructions in [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset) to make a bug report. Both Microsoft and your fellow developers will thank you!

**Comment by bcsanches** [comment]
Thank you! 

About the wrong launch_schema being generated, is this reported? 

Anyway, thanks you all for this awesome feedback here. I really was not expecting this thread to get any answers at all.
