### ISSUE TITLE
setlocale and UTF-8 codepage

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/cpp-docs#1469]
From [setlocale remarks](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=vs-2019#remarks):

>The set of available locale names, languages, country/region codes, and code pages includes all those supported by the Windows NLS API except code pages that require more than two bytes per character, such as UTF-7 and UTF-8. If you provide a code page value of UTF-7 or UTF-8, setlocale will fail, returning NULL.   

This information appears outdated now. In Visual Studio 2017, when passing ".UTF8" or ".65001" to setlocale it doesn't return NULL. Moreover, it actually works: UTF-8 characters in the current language can be correctly displayed in console after it. Full example:

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>

int main(int argc, char **argv)
{
	char* res = setlocale(LC_ALL, ".UTF8");
	if (res == nullptr) puts("setlocale failed");	
	else printf("Current locale: %s\n",res);
	puts(u8"Русский текст");

	getchar();
	return 0;
}
/* Output on my machine:
Current locale: Russian_Russia.utf8
Русский текст
*/
```
Supposedly, UTF8 locale support was introduced at the same time as UTF8 string literals, in VS2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MSDN-WhiteKnight 
Good to know, thanks. I'll add an update to the planning.

**Comment by TylerMSFT** [comment]
looks like the doc was updated
