### ISSUE TITLE
make_unique<[]>: definition shows the array elements being default-initialised, but the Remarks section says they're not

### ISSUE THREAD

**Issue by acs-godonnell** [MicrosoftDocs/cpp-docs#1470]
https://docs.microsoft.com/en-us/cpp/standard-library/memory-functions?view=vs-2019#make_unique shows the definition for arrays as:
```
// make_unique<T[]>
template <class T>
make_unique(size_t size)
    {
        return (unique_ptr<T>(new elements[size]()));
    }
``` 
which would mean each element of the array is default-initialised.
The Remarks section claims they're not.
Please clarify.

> When you use make_unique to create a unique_ptr to an array, you have to initialize the array elements separately

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec5d7ac7-0acc-63e3-9f87-cdfc4997c29b
* Version Independent ID: 03f518f7-2f57-7a0d-235e-136aa11a1364
* Content: [&lt;memory&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/memory-functions?view=vs-2019#make_unique)
* Content Source: [docs/standard-library/memory-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/memory-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@acs-godonnell 
Well spotted. I'm not sure how an implementation detail got in there, especially an incorrect one. I've updated the article to just show the prototypes. It should be visible by tomorrow sometime.

**Comment by corob-msft** [comment]
Fix is merged, closing.

**Comment by acs-godonnell** [comment]
My concern is that the implementation detail is actually correct - it describes what the implementation in VS2017 (and probably VS2019) actually does.  
The description in the Remarks doesn't.  
If a developer heeds the warning in the Remarks to separately initialise each array element, the end result is they get initialised twice, which is unnecessary and incurs a cost.
