### ISSUE TITLE
CPU scheduling impact on this instruction

### ISSUE THREAD

**Issue by SJKU** [MicrosoftDocs/cpp-docs#1471]
Hi, somewhere I read this instruction might take more clock cycle. If CPU is preempted  when calculating this counter, what will happen. Can you provide some hint on how CPU scheduling affects this instruction  in the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d231564-4e9f-16f3-f346-997198dd4cbd
* Version Independent ID: 2dde080f-c1fb-7da4-01b4-740512e2760e
* Content: [__rdtsc](https://docs.microsoft.com/en-us/cpp/intrinsics/rdtsc?view=vs-2019#feedback)
* Content Source: [docs/intrinsics/rdtsc.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/rdtsc.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SJKU 
When you use the `__rdtsc` intrinsic, the compiler just generates the opcode, and any timing issues internal to the processor are hardware-specific. We don't document those; we defer to the manufacturers for that kind of information. You'll have to do some digging for the sort of detail you're after. These are the top-level links we provide:

- [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide). Use the search box to find specific intrinsics.

- [Intel 64 and IA-32 Architectures Software Developer Manuals](https://software.intel.com/articles/intel-sdm)

- [Intel Architecture Instruction Set Extensions Programming Reference](https://software.intel.com/isa-extensions)

- [Introduction to Intel Advanced Vector Extensions](https://software.intel.com/articles/introduction-to-intel-advanced-vector-extensions)

- [AMD Developer Guides, Manuals & ISA Documents](https://developer.amd.com/resources/developer-guides-manuals/)
