### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by SirWhiteHat** [MicrosoftDocs/cpp-docs#1472]
Missing "const" at end of L39.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09262045-27b3-a35c-f382-6ab08604eed5
* Version Independent ID: 95bf2505-64a6-026c-f33c-3f1931d6985e
* Content: [constexpr (C++)](https://docs.microsoft.com/en-us/cpp/cpp/constexpr-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/constexpr-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/constexpr-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@SirWhiteHat 
Good catch, a fix is in progress and should be available tomorrow.

**Comment by corob-msft** [comment]
Fix is merged, closing.
