### ISSUE TITLE
Is the text for C4996 'issue': description, may just template text and needs to be filled in with values. 

### ISSUE THREAD

**Issue by DOMARS** [MicrosoftDocs/cpp-docs#1481]
I think you could use the text from the 4996 topic =&gt; The compiler encountered a deprecated declaration. 
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672bc066-51a0-9778-4c50-98922ebb4b4c
* Version Independent ID: 6263d065-c81a-54f7-a99d-fef41134c872
* Content: [Compiler Warnings by compiler version](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DOMARS 
I see what you're saying; it would be useful to have some indication here of what that message is about. We usually attempt to put the literal text of the message along with descriptive metadata variable names in the descriptions, to make it easy to match in a search engine, but in this case, the message is usually whatever the person who wrote the deprecation directive put there. If there isn't a deprecation message, the default is "was declared deprecated." I've put something like that in the descriptions: 

C4996 | '*deprecated-declaration*': *deprecation-message* (or "was declared deprecated")

This update should appear tomorrow.

**Comment by DOMARS** [comment]
@corob-msft - Thanks for making this update. The only other thing I found in these docs as I work on my docs for binskim, is that I'm not finding any text for C4748. I will send an out of band follow up email on that.
