### ISSUE TITLE
Unsafe use of weak_ptr<T>

### ISSUE THREAD

**Issue by s3rv4nt** [MicrosoftDocs/cpp-docs#1486]
Consider the following snippet from `CheckStatuses()`:

```cpp
try
{
    auto p = wp.lock();
    wcout << L"Status of " << p->Num << " = " << p->Status << endl;
}

catch (bad_weak_ptr b)
{
    wcout << L"Null object" << endl;
}  
```

Instead of throwing an exception, `std::weak_ptr<T>::lock()` will simply return an empty `shared_ptr` if the managed object has expired. Moreover, since `std::weak_ptr<T>::lock()` and `std::shared_ptr<T>::operator->` are both declared as `noexcept`, they are unable to throw any kind of exception. 

The only constructor capable of throwing a `bad_weak_ptr` exception is `template< class Y > explicit shared_ptr( const std::weak_ptr<Y>& r )`. This constructor is not implicitly called during `auto p = wp.lock();` since `wp.lock()` returns a `shared_ptr`, let alone the fact that the constructor is designated `explicit`.

This means that the `catch` block will never be executed if the managed object has expired. As a result, the `try` block can end up dereferencing a null stored pointer via `p->Num` and `p->Status`.

Replacing `auto p = wp.lock();` with `shared_ptr<Controller> p(wp);` should cause the `catch` block to be executed in the case of an expired, managed object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c879eb4-3a94-9968-63b1-1f4519ce11f8
* Version Independent ID: ae94388e-d305-321f-763d-f864aa7ecc32
* Content: [How to: Create and Use weak_ptr Instances](https://docs.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-weak-ptr-instances?view=vs-2019#feedback)
* Content Source: [docs/cpp/how-to-create-and-use-weak-ptr-instances.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/how-to-create-and-use-weak-ptr-instances.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@s3rv4nt thanks for the feedback! Looking at the example, I think the call to lock() is correct, but the following lines should check the returned shared_ptr like this:

            auto p = wp.lock();
            if (p)
            {
               wcout << L"Status of " << p->Num << " = " << p->Status << endl;
            }
            else
            {
               wcout << L"Null object" << endl;
            }
The STL designers obviously intended us to use lock(), and they provided a mechanism to use it without resorting to exception handling, which wouldn't work anyway, as you correctly pointed out.

**Comment by s3rv4nt** [comment]
@mikeblome I agree. I believe exception handling would work with the fix I suggested, but I agree that using `lock()` and checking for an empty `shared_ptr` would be a cleaner solution. Thanks for your response!

**Comment by mikeblome** [comment]
topic is updated and should be published by Sept 17. Thanks again for reporting this error!
