### ISSUE TITLE
Ob3 switch

### ISSUE THREAD

**Issue by Kojoley** [MicrosoftDocs/cpp-docs#1488]
The article https://devblogs.microsoft.com/cppblog/msvc-backend-updates-in-visual-studio-2019-preview-2/ states that there were (or there is) `/Ob3` switch, but it not mentioned in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8753fc2-5ab9-47ad-f52b-ae878986bc0f
* Version Independent ID: 47c6098b-17b4-a22d-b21a-8d8032b0df78
* Content: [/Ob (Inline Function Expansion)](https://docs.microsoft.com/en-us/cpp/build/reference/ob-inline-function-expansion?view=vs-2019#)
* Content Source: [docs/build/reference/ob-inline-function-expansion.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/ob-inline-function-expansion.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Kojoley 
It's not unusual for the docs to lag the product, unfortunately. I've updated the content and the engineering team is reviewing it. It should be visible by tomorrow sometime.

**Comment by corob-msft** [comment]
It's live now.
