### ISSUE TITLE
Is %zu supported for size_t values in Visual Studio 2015?  Old documentation disagrees with the current documentation.

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/cpp-docs#1490]
[The current "Format specification syntax: printf and wprintf functions" documentation for Visual Studio 2015](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2015) lists `z` as a valid size specification for `size_t` in [the "Argument size specification" section](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2015#argument-size-specification).

[An older version of the "Size Specification" documentation for Visual Studio 2015](https://web.archive.org/web/20170311084643/https://msdn.microsoft.com/en-us/library/tcxf1dw6.aspx), saved in the Wayback Machine, lists `I` as the size specification for `size_t`, and doesn't mention `z`.

Is the old documentation incorrect, with the VS 2015 runtime supporting `z`, or is the new documentation incorrect, with `I` being required?

**Comment by corob-msft** [comment]
@guyharris 
It took a while for the documentation to catch up with the implementation. Unless you're working with versions older than Visual Studio 2015, the documentation on Docs always supersedes anything found in the Internet Archive. VS 2015 included an overhaul of the CRT to bring it much closer to conformance with the C99 standard. While the `I` width specifier is still supported as a Microsoft extension, the `z` width specifier is standard, portable, and supported in VS 2015 and its current redistributables.

**Comment by guyharris** [comment]
Thank you.  You've just made my day (because that means I don't need to worry about `%I` vs. `%u` in libpcap and tcpdump - we require VS 2015 for Windows builds and "supports C99" for UN\*X builds).

(I bookmarked some Internet Archives links when, at least for Wireshark, I wanted to be able to research what pre-VS 2015 compilers and run-times did.  The Wireshark Developer's Guide still appears to speak of VS 2013, but I think that's out of date - I'll check into that.)
