### ISSUE TITLE
the link pointing to this page failed

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1491]
the link pointing to this page failed
![wdqwq](https://user-images.githubusercontent.com/32254161/62763013-1414bf00-babd-11e9-89cf-91a1e0954d64.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc086fe-c52c-d474-0657-f8281185966a
* Version Independent ID: 43c8e36d-70ba-4c15-29c0-8a90a79646ac
* Content: [CMFCToolBarsCustomizeDialog Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfctoolbarscustomizedialog-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmfctoolbarscustomizedialog-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmfctoolbarscustomizedialog-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@songxia233 thanks for the feedback. That last "link" is not really a link because the CMFCToolBarsCustomizeDialog type is here on the current page.
