### ISSUE TITLE
P0409R2 Listed Twice

### ISSUE THREAD

**Issue by Jessper** [MicrosoftDocs/cpp-docs#1494]
P0409R2 is listed as both unsupported and supported (VS 2019 16.1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C++ Language Conformance Table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019#feedback)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by k15tfu** [comment]
+2:
  P0515R3 Three-way (spaceship) comparison operator <=>
  P1008R1 Prohibiting aggregates with user-declared constructors

**Comment by corob-msft** [comment]
@Jessper @k15tfu 
Thanks for spotting these issues. An update should appear by tomorrow.
