### ISSUE TITLE
A link failed

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1496]
There is a link pointing to this apge failed
![121211111](https://user-images.githubusercontent.com/32254161/62844152-de0c5080-bcf1-11e9-8389-bdd693baa489.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 509335de-3776-7c83-8693-946f32451c53
* Version Independent ID: d3a3d52f-a559-2888-958f-5224bd508814
* Content: [CMFCToolBarEditBoxButton Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfctoolbareditboxbutton-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmfctoolbareditboxbutton-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmfctoolbareditboxbutton-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@songxia233 that hierarchy chart ends with the type documented on the current page, so no need to link. These are all by design. Thanks!
