### ISSUE TITLE
Lack of information.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#1499]
**TRANSLATED**
@NotACoder11 commented on [Sun Aug 11 2019](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/64)
For me, personally, this error appeared due to the lack of an entry point (main function). Add the same to the article) It will probably be useful to someone

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ab7d8d70-709a-67c8-799f-399ba8a6c38c
* Version Independent ID: ba5ba087-422c-4974-db42-4ae343defb3f
* Content: [Ошибка средств компоновщика LNK2019](https://docs.microsoft.com/ru-ru/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DRU-RU%26k%3Dk(LNK2019)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2019.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/error-messages/tool-errors/linker-tools-error-lnk2019.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Sun Aug 11 2019](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/64#issuecomment-520254276)

Hello, @NotACoder11
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
This issue was machine translated from ru-RU

**Comment by corob-msft** [comment]
Thanks to @MSDN-WhiteKnight for contributing this addition.
