### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Nijegorodov** [MicrosoftDocs/cpp-docs#1502]
The link to VARIANT data type point to nowhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0ef9c3-f7af-2dd7-2c7a-bc39394f3edc
* Version Independent ID: d0bcfae9-e185-44ae-f981-b2a7973fbe80
* Content: [COleVariant Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/colevariant-class?view=vs-2019)
* Content Source: [docs/mfc/reference/colevariant-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/colevariant-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Nijegorodov 
Thanks for the report. This link is now fixed, along with lots of other links into the Windows SDK documentation.
