### ISSUE TITLE
Improper use of FromHandle in sample code

### ISSUE THREAD

**Issue by RobertDunlop** [MicrosoftDocs/cpp-docs#1505]
The following sample code provided with the CBrush::CBrush documentation is incorrect:

CBrush OrigBrush;
...
// Save original brush.
OrigBrush.FromHandle((HBRUSH)pTempBrush);
...
// Reselect original brush into device context.
pDC-&gt;SelectObject(&OrigBrush);

CBrush::FromHandle is a static function that returns a pointer to a CBrush object.  In the sample code calling FromHandle on the OrigBrush instance has no effect on that instance, and the returned pointer is not being captured.  Later use of SelectObject(&OrigBrush) will be passing an uninitialized CBrush instance to SelectObject.

The correct use would be:

CBrush *pBrush = CBrush::FromHandle((HBRUSH)pTempBrush);
pDC-&gt;SelectObject(pBrush);

It is unclear why this is being used here though... why not just:

pDC-&gt;SelectObject(pTempBrush);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d898f04-8a4a-8c6f-a24a-e3c3789a8237
* Version Independent ID: 7f7fe6d9-b2b3-ab99-7cde-aad249195574
* Content: [CBrush Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cbrush-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cbrush-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cbrush-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@RobertDunlop thanks for the feedback! Yes this code was very confused. Corrected version should be visible by Oct 16.
