### ISSUE TITLE
This page's example contents don't match with the following links's contents.

### ISSUE THREAD

**Issue by drvoss** [MicrosoftDocs/cpp-docs#1511]
This page's example contents don't match with the following links's contents.

https://docs.microsoft.com/en-us/cpp/mfc/decrement-implementation-comment?view=vs-2019
https://docs.microsoft.com/en-us/cpp/mfc/decrement-constructors-comment?view=vs-2019
https://docs.microsoft.com/en-us/cpp/mfc/decrement-attributes-comment?view=vs-2019
https://docs.microsoft.com/en-us/cpp/mfc/decrement-operations-comment?view=vs-2019
https://docs.microsoft.com/en-us/cpp/mfc/decrement-overridables-comment?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e05986d-e4f1-8add-bb47-c6a373a9c8a9
* Version Independent ID: 737fa1b9-7d75-7183-55c7-f01fbcb77c20
* Content: [An Example of the Comments](https://docs.microsoft.com/en-us/cpp/mfc/an-example-of-the-comments?view=vs-2019#feedback)
* Content Source: [docs/mfc/an-example-of-the-comments.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/an-example-of-the-comments.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@drvoss 
It's true, the sample code must have been changed at some point. I have a fix in the works that should address this. It makes PRs #1508, #1509, and #1510 unnecessary.
