### ISSUE TITLE
This walkthrough is incorrect for VS2019 Community edition

### ISSUE THREAD

**Issue by MartyMacGyver** [MicrosoftDocs/cpp-docs#1513]
The first problem is `stdafx.h` doesn't even exist.... then the second step fails if you don't have `#include <memory>` in ChildView.h. Working my way through from there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3722ed-f2a1-cd80-5e25-453b349505d4
* Version Independent ID: 917820fe-456e-3bb9-98ed-188ced32eafb
* Content: [Walkthrough: Removing Work from a User-Interface Thread](https://docs.microsoft.com/en-us/cpp/parallel/concrt/walkthrough-removing-work-from-a-user-interface-thread?view=vs-2019#feedback)
* Content Source: [docs/parallel/concrt/walkthrough-removing-work-from-a-user-interface-thread.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/walkthrough-removing-work-from-a-user-interface-thread.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@MartyMacGyver thanks for the feedback. The new default name for the precompiled header file is "pch.h".  I noticed we still use "stdafx.h" in several other places in the documentation so I'll fix those as well. The updated topic should be visible by Aug 20. Feel free to reopen if you find other issues in this topic.
