### ISSUE TITLE
I can't see the Linux Console option in Visual studio 2019 16.2.2 option

### ISSUE THREAD

**Issue by priyankasabharwal81** [MicrosoftDocs/cpp-docs#1516]
I am working by opening the solution as folder and adding the configurations in launch.vs.json. I can debug all ok but can not see the debug console. I do not see the option under 
debug -> Linux Console

**Comment by mikeblome** [comment]
@priyankasabharwal81 aologies for delayed response. when you are debugging, do you see the Linux Console as a tab in the Output Window?
