### ISSUE TITLE
Use range-based for loop in examples

### ISSUE THREAD

**Issue by mywtfmp3** [MicrosoftDocs/cpp-docs#152]
Lots of example code use this,

```C++
   cout << "L = ( " ;  
   for ( Iter = L.begin( ) ; Iter != L.end( ) ; Iter++ )  
      cout << *Iter << " ";  
   cout << ")" << endl;  
```

It's a perfect case to use range-based for loop here.

```C++
   cout << "L = ( " ;  
   for ( const auto& item : L )  
      cout << item << " ";  
   cout << ")" << endl;  
```

Is it a good idea to change it?

**Comment by corob-msft** [comment]
If it's appropriate, there's no objection from us if you want to edit some examples to adopt this style. We don't usually revisit working examples for stylistic changes to syntactic sugar, for reasons of time and priority. Do you have some specific examples in mind?

**Comment by mywtfmp3** [comment]
@corob-msft It's everywhere in the std algorithm documentation. Example code for  [std::rotate](../blob/master/docs/standard-library/algorithm-functions.md#rotate) use several raw loops. 

```C++
for ( v1Iter1 = v1.begin( ) ; v1Iter1 != v1.end( ) ;v1Iter1 ++ )  
   cout << *v1Iter1  << " ";  

for ( d1Iter1 = d1.begin( ) ; d1Iter1 != d1.end( ) ;d1Iter1 ++ )  
   cout << *d1Iter1  << " ";  
```
Something else can be improved too. Here it declares variable `i` outside of for loop, but it's not used anywhere after the for loop. Isn't it better to put `i` inside for loop?

```C++
int i;  
for ( i = -3 ; i <= 5 ; i++ )  
{  
   v1.push_back( i );  
}  
```

Cpp core guidelines recommend using range-based for loop whenever appropriate. If you don't object, I will send a PR later.

**Comment by corob-msft** [comment]
Closing without prejudice as won't fix, though new code examples will certainly use modern style. PRs to address this complaint can still be made.
