### ISSUE TITLE
HString::IsValid() docs ambiguous about what it's really checking

### ISSUE THREAD

**Issue by paulcam206** [MicrosoftDocs/cpp-docs#1523]
Does `HString::IsValid()` check to see if the underlying `HSTRING` is `nullptr`? How about `""`? Also, it's marked `throw()`. When would it throw?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dac57d-a52b-8a76-76dd-726d5579a984
* Version Independent ID: 6a4ef894-94a6-0888-af31-a4d7f3d7e680
* Content: [HString Class](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/hstring-class?view=vs-2019#isvalid)
* Content Source: [docs/cppcx/wrl/hstring-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/hstring-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by paulcam206** [comment]
I should probably note that the actual answer is found in the header. It's strictly a `nullptr` check, so the below phrasing is imprecise:

> Indicates whether the current `HString` object is empty or not.

**Comment by mikeblome** [comment]
@paulcam206  yep good point. Thanks! Fix should be visible in a day or so.
