### ISSUE TITLE
a couple of questions

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/cpp-docs#1525]
suppose folder structure below

```
out/
f1.asm
f2.asm
f3.asm
```

doc
> ML and ML64 can accept several /c options

if so, what would be the difference between 1 -c and several -c? in my test
`ml -Foout\ f1.asm -Foout\ f2.asm -Foout\ f3.asm -Feout\`
no matter where i put the -c, 3 obj files appears, no link takes place

since i couldn't image what the difference will be (maybe "do not link object files decorated by -c"? i failed to produce that) , i suspect there's no difference between 1 -c and several -c hence a doc bug

doc
> /omf implies /c

if i execute this command
`ml -Foout\ f1.asm -Foout\ f2.asm -Foout\ f3.asm -Feout\ -omf`
it assembles then links. change -omf to -c, no link occurs

by moving -omf around i find it will prevent link when qualifying at least 1 file, for example
`ml -Foout\ f1.asm -Foout\ f2.asm -Foout\ -omf f3.asm -Feout\`

so can i say -omf is similar to -c in that if it takes effect, link will not called; but /omf does not imply /c?

doc
> The options listed in the following table
> /AT

masm 14.22.27905.0
`ml -AT -Foout/ f1.asm -Feout/`
MASM : warning A4018:invalid command-line option : -AT

-AT is a switch of masm 6.11. not an error of doc but the doc should make this clear

doc
> The options listed in the following table
> /omf

masm 6.11
`ml -Foout\ f1.asm -Feout\ -omf`
warning A4017: invalid command-line option : -omf

-omf is a switch of masm 14. not an error of doc but the doc should make this clear

doc
> Some command-line options to ML and ML64 are placement-sensitive

"need more info"

during test i find 4 kind of switches
1\. applies to 1 file after it
2\. applies to all files after it
3\. applies to all files
4\. -link

```
1. applies to 1 file after it
-unrecognized switch     ml 6, 14; ml64 14
    action: ignore 1 token after it
-Fo     ml 6, 14; ml64 14
    ml -Foout\ f1.asm -Foout\ f2.asm -Foout\ f3.asm -Feout\

2. applies to all files after it
-coff   ml 6, 14. default
-omf    ml 14 - implies -c?
-Zs     ml 6, 14; ml64 14. absorbs -c

3. applies to all files
-AT     ml 6
-c      ml 6, 14; ml64 14
-Fe     ml 6, 14; ml64 14
```

my personal opinion is informations like above is helpful. if possible, i'd like to see
those informations which based on actual implementation, not on observation. but i'm not
suggesting anything here, feel free to ignore this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4eaa981-a205-47f7-12f9-09f8b3c95919
* Version Independent ID: 43ba0448-bad1-4298-cedb-e8580051ebea
* Content: [ML and ML64 Command-Line Reference](https://docs.microsoft.com/en-us/cpp/assembler/masm/ml-and-ml64-command-line-reference?view=vs-2019#feedback)
* Content Source: [docs/assembler/masm/ml-and-ml64-command-line-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/ml-and-ml64-command-line-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
