### ISSUE TITLE
Nmake 'Dependents' link points to a wrong description

### ISSUE THREAD

**Issue by mitsukuri** [MicrosoftDocs/cpp-docs#1530]
It should point to relevant description of nmake dependents, but points to dumpbin /dependents option instead.

* ID: 994aee97-7c77-b074-c966-0d6a4b47d093
* Version Independent ID: 52253d9f-148c-7586-7d44-25b2ba13b6c1
* Content: [Description Blocks](https://docs.microsoft.com/en-us/cpp/build/reference/description-blocks?view=vs-2019)
* Content Source: [docs/build/reference/description-blocks.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/description-blocks.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
The documentation has been updated in the repo we publish from, but changes to the website may not happen until next Monday, due to an embargo for the Ignite conference.
