### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by dmcminn** [MicrosoftDocs/cpp-docs#1532]
The example is incorrect. It looks like someone has simply replaced _control87 by_control87_2  without considering the different behaviour of the two functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66680427-0e66-2b6e-f49b-6458e720c671
* Version Independent ID: e6c16b21-19a5-2c39-98a6-8ab1660684d3
* Content: [_control87, _controlfp, __control87_2](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/control87-controlfp-control87-2?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/control87-controlfp-control87-2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/control87-controlfp-control87-2.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dmcminn 
You're right, there's something suspect about the assignment of the return values from `__control87_2`. A fix is in the works, and should appear in the next day or two.

**Comment by corob-msft** [comment]
The content is merged and should appear online by next Tuesday.
