### ISSUE TITLE
Missing explanation

### ISSUE THREAD

**Issue by GG36** [MicrosoftDocs/cpp-docs#1533]
bar[3] is not explained clearly.
What is bar[3]???
Also:
 char _pad1[1];    // padding to make sizeof(x_) multiple of 4
Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7ada89-39df-87fc-1b38-ee2f68529796
* Version Independent ID: 40bd6b1a-43b4-e8b4-9040-6333e6c49b6f
* Content: [Alignment (C++ Declarations)](https://docs.microsoft.com/en-us/cpp/cpp/alignment-cpp-declarations?view=vs-2019#feedback)
* Content Source: [docs/cpp/alignment-cpp-declarations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/alignment-cpp-declarations.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@GG36 

You're right, that's very confusing. Thanks for pointing it out, and sorry it's taken a while to get to this. I've added some apparently missing context to the struct definitions, and clarified the text. Basically, they should both have a declaration of `struct x_ bar[3];` afterward. I cleaned up the padding descriptions as well, and both fixes should be visible by tomorrow.
