### ISSUE TITLE
generate_canonical() has been fixed

### ISSUE THREAD

**Issue by yousuketakada** [MicrosoftDocs/cpp-docs#1534]
It seems generate_canonical() has been fixed already in 2015 (although I am not sure it is fully compliant to the standard): 
https://devblogs.microsoft.com/cppblog/stl-fixes-in-vs-2015-part-2/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15314802-757e-6973-f63f-4147f6df9467
* Version Independent ID: efc7aea2-7d37-0245-340a-3edb35b1cdf1
* Content: [&lt;random&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/random-functions?view=vs-2019)
* Content Source: [docs/standard-library/random-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/random-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yousuketakada 
Thanks, it looks like you are correct. The function is now supposed to be conforming, so I've updated the documentation to match. The updated documentation should appear in a day or two.
