### ISSUE TITLE
ERROR OUTPUT

### ISSUE THREAD

**Issue by Changes1988** [MicrosoftDocs/cpp-docs#1537]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8478a5ea-acf4-0519-15f7-a24fd19fefef
* Version Independent ID: deec191e-e5f8-e122-0873-b9d445963aef
* Content: [ML Fatal Error A1000](https://docs.microsoft.com/en-us/cpp/assembler/masm/ml-fatal-error-a1000?view=vs-2019)
* Content Source: [docs/assembler/masm/ml-fatal-error-a1000.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/ml-fatal-error-a1000.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I'm closing the issue, as this feedback doesn't give us any information about a problem in the documentation.
