### ISSUE TITLE
_BitScanForward64 is listed as supported on ARM

### ISSUE THREAD

**Issue by kusma** [MicrosoftDocs/cpp-docs#1538]
The definition of _BitScanForward64 doesn't exist for ARM builds, even though the docs claims so. My guess would be that it exists for ARM64, but not for ARM...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9a85d1-fd99-7639-14ca-78f241efb69d
* Version Independent ID: 6f8cda00-2028-7de7-0afe-a7b8835b4e1c
* Content: [_BitScanForward, _BitScanForward64](https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64?view=vs-2019#feedback)
* Content Source: [docs/intrinsics/bitscanforward-bitscanforward64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/bitscanforward-bitscanforward64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by kusma** [comment]
This article doesn't list _BitScanForward64 as supported on ARM:
https://docs.microsoft.com/en-us/cpp/intrinsics/arm-intrinsics?view=vs-2019

**Comment by kusma** [comment]
Checking further, according to intrin0.h, this is only defined for X64 and ARM64. So it seems the docs are indeed wrong here.

**Comment by corob-msft** [comment]
@kusma
Thanks for looking into that. It turns out that there are many other intrinsics that are incorrect in similar ways. I've made an update that should address those, and it will appear in a couple of days.
