### ISSUE TITLE
Still get C1010 "unexpected EOF looking for precompiled header", even with it turned off.

### ISSUE THREAD

**Issue by TacticalBFG** [MicrosoftDocs/cpp-docs#1540]
It's like all VS wants me to do is suffer
I've turned it off on the entire project by right clicking on it in the solution explorer.
I've manually disabled precompiled headers for every single file
I've even tried a blank solution, which won't give an error, but refuses to compile into a DLL, even after I change both the output type and the output extension, yet it throws out an EXE.

I literally have no idea what happened, it was working fine a few months ago, now on my new project it just decides to quit on everything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7710ea05-1307-eaaf-3ba0-86175eeaf184
* Version Independent ID: 30568a08-383b-1676-dfb3-e1dc6f28f38c
* Content: [Fatal Error C1010](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1010?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1010.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1010.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TacticalBFG 
Sorry you're having issues. Turning off precompiled headers in an existing project can be complex. I've updated the procedure for that in the article, which should appear in a day or two. Here's the new procedure: 

To turn off precompiled header use in a project, follow these steps:

1. In the **Solution Explorer** window, right-click the project name, and then choose **Properties** to open the project **Property Pages** dialog.

1. In the **Configuration** drop-down, select **All Configurations**.

1. Select the **Configuration properties** > **C/C++** > **Precompiled Headers** property page.

1. In the property list, select the drop-down for the **Precompiled Header** property, and then choose **Not Using Precompiled Headers**. Choose **OK** to save your changes.

1. In the **Solution Explorer** window, right-click the *pch.cpp* source file in your project. (In older projects, the file may be named *stdafx.cpp*.) Choose **Exclude from Project** to remove it from the build.

1. Use the **Build** > **Clean solution** menu command for each configuration you build, to delete any *project_name.pch* files in your intermediate build directories.

I think the part about making changes for all configurations could be one of the problems you ran into. Hopefully this procedure will address your issue.
