### ISSUE TITLE
Example function does not compile.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#1541]
@DotBlack commented on [Sun Sep 01 2019](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/28)

Hello.
void test( char * format, ... ) needs to be 
void test( const char * format, ... ) because "%d %c %d"
is a const char array and can't implicitly convert to a char*.
Can you maybe update the test function?
Thank you! 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: df8d5020-450c-0b03-8588-a2dcf3e0a84d
* Version Independent ID: fc463135-65e1-dba0-2f9a-b1ef329818f8
* Content: [vsprintf, _vsprintf_l, vswprintf, _vswprintf_l, __vswprintf_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Mon Sep 02 2019](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/28#issuecomment-526902074)

Hello, @DotBlack,

Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user is reporting errors in the code

**Comment by corob-msft** [comment]
@DotBlack 
It took some experimenting to find the cause of the error. The code fails to compile only when compiled as C++ (using **/TP**, or giving the code a .cpp extension), and when using **/permissive-**. These are the defaults you'd get if you created a console application in the latest version of Visual Studio, and then pasted in the code. However, even in C, your suggestion is a good one from a code style standpoint. The `test` function doesn't modify the `format` parameter, so it should advertise that by using `const`. 
I've updated the code to fix such issues. It should be visible in a day or two. Thanks for the input!
