### ISSUE TITLE
Compiler Error C2864 fix code has something wrong

### ISSUE THREAD

**Issue by handanzhang** [MicrosoftDocs/cpp-docs#1547]
[Enter feedback here]
### fix code has something wrong !!!

> // C2864b.cpp
// compile with: /c
class C  {
private:
   int a = 3;
   static int b; // = 3; C2864
   volatile static int c; // = 3; C2864
   volatile static const int d; // = 3; C2864
   static const long long e = 3;
   static const double f; // = 3.33; C2864
};

`static const long long e = 3;`
This is error, do not match be before
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be67df94-1d31-681d-914e-a729b4e53396
* Version Independent ID: 6a2f7167-3a37-1156-9fd3-6018c4e35ddc
* Content: [Compiler Error C2864](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2864?view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2864.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c2864.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@handanzhang 

I'm sorry, I can't find an error in the example. Can you explain what is wrong, and which compiler version you used?

**Comment by corob-msft** [comment]
Absent further comment, I've done an update pass on the content, and I'm closing the issue.
