### ISSUE TITLE
aligned_alloc is listed but not existed

### ISSUE THREAD

**Issue by objectx** [MicrosoftDocs/cpp-docs#1548]
`aligned_alloc` is listed in this page, but current VC++ does not have it (cf. https://developercommunity.visualstudio.com/solutions/473365/view.html )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb9fdb9-8fdb-7595-3139-e4d5266d2b15
* Version Independent ID: 30dc7138-42be-eb4a-e6e6-4e4ce938ff68
* Content: [&lt;cstdlib&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/cstdlib?view=vs-2019#feedback)
* Content Source: [docs/standard-library/cstdlib.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/cstdlib.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@objectx 

You're right. I've added a note about that function, which is an unimplemented part of the C11 standard. It should be visible later today.
