### ISSUE TITLE
Takes 1 min to read

### ISSUE THREAD

**Issue by Aaryan-M** [MicrosoftDocs/cpp-docs#1549]
The page says it takes 2 minutes to read about the abort function, but it only takes like 30 seconds. Not like it's that big of a deal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6798cd12-7ad1-7b19-fb3b-746731fe7341
* Version Independent ID: eab88d85-827c-a15f-b5fa-f4f175cce00c
* Content: [abort Function](https://docs.microsoft.com/en-us/cpp/cpp/abort-function?view=vs-2019#feedback)
* Content Source: [docs/cpp/abort-function.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/abort-function.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Aaryan-M

Thanks, you speed reader, you, that's the funniest thing I've seen today. :)

Those numbers are generated automatically somewhere deep in the publishing process, which is mostly opaque to us mere writers. I'm sure the publishing team just wired up some library that judges the time based on text complexity and length for some theoretical reader at a particular grade level. Its inner workings may be just as opaque to them.

As it's not really a problem with the content, I'm closing the issue, but I'll pass your note along.

**Comment by corob-msft** [comment]
Just a follow-up on the formula, after hearing back. Apparently, it's a lot simpler than I imagined. It's basically word count / 200, with a floor of 2.

**Comment by Aaryan-M** [comment]
Thanks for the info 🤙🤙
