### ISSUE TITLE
_getdrive returns 0 if current directory is UNC path

### ISSUE THREAD

**Issue by skissane** [MicrosoftDocs/cpp-docs#1552]
If current directory is a UNC path, _getdrive() returns 0.

But the documentation never mentions this. For completeness, the documentation should mention this fact.

I have confirmed this for myself using the following test program:

    #include <direct.h>
    #include <stdio.h>

    int main(int argc,char**argv) {
	printf("DRIVE=%d\n",_getdrive());
	printf("press ENTER to continue...");
	getchar();
	return 0;
    }

If you run the above from a UNC path (easy way is to put the .EXE on a network share, use Windows Explorer to navigate to the share's UNC path and run the .EXE from there), then it will be started with the UNC path as the current working directory, and in that scenario it prints DRIVE=0. (The "press ENTER to continue..." and getchar() is simply to stop the console window from closing before you can see the output.) By contrast, if you run it from e.g. drive C, it will print DRIVE=3.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f827185-f3ff-9a42-8b8b-262eb750f10d
* Version Independent ID: a36ff9eb-d7bc-3754-d79c-eff34aedfbbb
* Content: [_getdrive](https://docs.microsoft.com/en-au/cpp/c-runtime-library/reference/getdrive?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/getdrive.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/getdrive.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@skissane 

The function isn't really that smart. You'll get a 0 returned for any path that doesn't start with a letter followed by a colon, or for a zero-length path. That can happen in several situations, including when the current directory is a UNC path. You can also get a 0 returned in the unlikely event the path is longer than MAX_PATH and a temporary buffer allocation fails, in which case errno is set to ENOMEM.

I've updated the Return value section to clarify this, and it should be visible tomorrow. Thanks for bringing it up.
