### ISSUE TITLE
Initialization of Mixed Assemblies Would be better if project/Solution provided

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/cpp-docs#1555]
I was trying to use this in as a base for a dll project for a mixed dll, and have yet to get it all to work without adding any code of my own. I t would be better if supplied as a project/solution for the ide.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1028b55d-1e68-f38b-478b-5e66d6c6a486
* Version Independent ID: 1dd441b1-ebb9-195a-9c5c-25125cf36db2
* Content: [Initialization of Mixed Assemblies](https://docs.microsoft.com/en-us/cpp/dotnet/initialization-of-mixed-assemblies?view=vs-2017#example)
* Content Source: [docs/dotnet/initialization-of-mixed-assemblies.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/initialization-of-mixed-assemblies.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
