### ISSUE TITLE
Information is wrong.

### ISSUE THREAD

**Issue by JN-LT** [MicrosoftDocs/cpp-docs#1561]
"You have used an attribute that is not supported in this version of Visual C++."
... and yet other projects using the same attributes compile just fine with this version of C++!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545cead3-2a93-4888-0e69-7e542ebea155
* Version Independent ID: c2b4f61a-b363-3f8d-96ed-3bacd9649b1c
* Content: [Compiler Error C2337](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2337?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2337.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2337.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JN-LT 

The description could use an update. Here's the new description:

"Your code uses an attribute that isn't supported in this context. Or, the attribute isn't available in this version of the compiler. To resolve this issue, remove the unsupported attribute."

This fix should be visible by tomorrow.

**Comment by JN-LT** [comment]
You have no idea just how gratifying it is to see an issue addressed! Thank you!!

At my place of work, tickets are opened, and then closed a few days later, but no action is taken, and nothing is ever fixed/resolved.

Jeff Nygren
Software Engineer II | ext. 65440
