### ISSUE TITLE
I cannot use /openmp:experimental option due to cl Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by chengdi123000** [MicrosoftDocs/cpp-docs#1572]
[Enter feedback here]
I am using Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64 in win 10.

I want to use some feature of openm4.0 such as `#pragma omp simd`. But I cannot activate it. I will produce warning and generate a `penmp[:experimental].exe` file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c23f71d-4fe6-e91a-2331-900bc86f78b1
* Version Independent ID: 37bcd3b7-8072-c6b7-4da1-97258dc85883
* Content: [/openmp (Enable OpenMP Support)](https://docs.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=vs-2019#feedback)
* Content Source: [docs/build/reference/openmp-enable-openmp-2-0-support.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/openmp-enable-openmp-2-0-support.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chengdi123000 

I'm sorry you're having trouble. It looks like you have put square brackets in the command-line option. These are not part of the option. In the **Syntax** section, they indicate that the enclosed text is optional. Try using **/openmp:experimental** instead.
