### ISSUE TITLE
Reference to __catch

### ISSUE THREAD

**Issue by sctam** [MicrosoftDocs/cpp-docs#1574]
Should __catch be __except?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c50154d-3283-0e7b-2436-376531c344d2
* Version Independent ID: f321866b-867d-edb8-6c50-19d1249b5950
* Content: [Handle structured exceptions in C++](https://docs.microsoft.com/en-us/cpp/cpp/exception-handling-differences?view=vs-2019#feedback)
* Content Source: [docs/cpp/exception-handling-differences.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/exception-handling-differences.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@sctam 

Yes, it should be `__except` there. Good catch, thanks! I've made an update that should be visible tomorrow.
