### ISSUE TITLE
Behavior of this intrinsic when run the code on i386/i486 and bellow processors  

### ISSUE THREAD

**Issue by shamalwinchurkar** [MicrosoftDocs/cpp-docs#1575]
When we use __asm(cpuid) instruction in our code, we fist check EFLAGS register whether this instruction is supported or not. How this intrinsic reports that cpuid instruction is not supported on given platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b56aae-e5af-6403-9ed2-a04a76d1fb91
* Version Independent ID: 8ff51c36-f23a-3a3a-3e91-092c2e4340d1
* Content: [__cpuid, __cpuidex](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=vs-2019#feedback)
* Content Source: [docs/intrinsics/cpuid-cpuidex.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/cpuid-cpuidex.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shamalwinchurkar 

Intel reports that the way to tell if the `cpuid` instruction is supported is by checking whether bit 21 can be modified in the EFLAGS register. They have sample code that looks something like this:
```asm
    pushfd                ;copy EFLAGS to stack
    pop     eax           ;copy EFLAGS to eax
    mov     ecx, eax      ;copy EFLAGS to ecx
    xor     eax, 200000h  ;toggle bit 21 in eax 
    push    eax           ;push eax onto stack
    popfd                 ;pop stack into EFLAGS
    pushfd                ;copy EFLAGS to stack
    pop     eax           ;copy EFLAGS to eax
    xor     eax, ecx      ;compare with original  
    je      no_cpuid      ;cpuid not supported 
```
For more details, see Example 10-1 in [Intel Processor Identification and the CPUID Instruction](https://www.scss.tcd.ie/Jeremy.Jones/CS4021/processor-identification-cpuid-instruction-note.pdf).
