### ISSUE TITLE
Target Platform and Target Platform Version not documented

### ISSUE THREAD

**Issue by mehagar** [MicrosoftDocs/cpp-docs#1576]
In Visual Studio Enterprise 2019, Version 16.2.5, I see the properties "Target Platform" and "Target Platform Version" instead of "Windows SDK Version".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a66e1d7-8954-b4d2-2e13-37fcb207725b
* Version Independent ID: c47d8881-fa05-db11-a6a6-ceb8a8d42c0b
* Content: [General Property Page (Project)](https://docs.microsoft.com/en-us/cpp/build/reference/general-property-page-project?view=vs-2019)
* Content Source: [docs/build/reference/general-property-page-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/general-property-page-project.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@mehagar hmmm that page looks correct for my more recent version of VS 2019. Can you still repro your issue on 16.3?

**Comment by mehagar** [comment]
Oh, sorry, I think it's because the version of the project is VS 2015, even though I am using VS 2019.
