### ISSUE TITLE
Remote pre and post run events

### ISSUE THREAD

**Issue by gzorlee** [MicrosoftDocs/cpp-docs#1577]
Hello,

first of all great article and great feature! Hats off. One little question though. Is it possible to run a program/script before and after the execution of the debugger. For instance we use a sh script to setup the environment consisting of file copies/set of environment variables... For large scale CMake Linux preexisting projects it would help the transition to Visual Studio if we could focus first on having the binaries properly debugged from VS and then migrate all the boilerplate everyone usually does to have those binaries running.

In a nutshell we want to run a beforeStart.sh before gdb kicks in and a afterStop.sh after gdb session is over.

Thank in advance for the help.

GT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001834ce-31d2-e768-1df1-4a776aa9ef65
* Version Independent ID: 45f15fc0-e5c7-34a1-2469-f38d304ef5bd
* Content: [Deploy, run, and debug your C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/deploy-run-and-debug-your-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/deploy-run-and-debug-your-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gzorlee** [comment]
We have tried to play with the launch.vs.json without luck. Tried to create a preLaunch task a bit like what we can find in the VSCode documentation. No luck. Tried to inject some commands in gdb desperately. No luck.

FYI we have a RedHat on Linux side with the usual gcc/gdb couple. On windows side we have VS2019 16.2.5. Our project uses CMake to build and deploy all the binaries.

**Comment by gzorlee** [comment]
It would be the equivalent of the Pre-Launch command for a VS Linux project. Anybody here?

**Comment by mikeblome** [comment]
Hi @gzorlee I have forwarded your question to the product team.

**Comment by gzorlee** [comment]
Thank you!

**Comment by mikeblome** [comment]
@gzorlee in your CMakeSettings.json file, in the configuration for your build, you can add a "remotePostBuildCommand" property where you can specify a script to run after the build, and before launching the debugger. VS doesn't currently provide an automated way to run a script after the debugger exits. Also you'll want to make sure any environment variables that are set in the script are persisting when VS invokes gdb.

**Comment by mikeblome** [comment]
Closing this issue but feel free to reopen if you are still having difficulties.
