### ISSUE TITLE
Code bug in _getcwd sample

### ISSUE THREAD

**Issue by BCG-Jackson** [MicrosoftDocs/cpp-docs#1579]
This line

printf("%s \nLength: %d\n", dir, strnlen(dir));

has 2 errors:

error C2660: 'strnlen': function does not take 1 arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26a72576-a0f9-aabb-840f-a521b92d7ec9
* Version Independent ID: e892325a-273a-86dd-b01d-13cb4675cd25
* Content: [_getcwd, _wgetcwd](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getcwd-wgetcwd?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/getcwd-wgetcwd.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/getcwd-wgetcwd.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@BCG-Jackson 

Yes, that's an issue; well spotted, thanks. I've updated the sample a bit to compile cleanly in the latest C and C++ environments. It should be visible in tomorrow's published updates.
