### ISSUE TITLE
/Zc:ternary

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#158]
Would it be possible to add a section on /Zc:ternary to the conformance page?
docs/build/reference/zc-conformance.md

**Comment by corob-msft** [comment]
Yes, it is possible. Look for it in a few days. In the meantime, this switch is discussed in [Diagnostic Improvements in Visual Studio 2017 15.3.0](https://blogs.msdn.microsoft.com/vcblog/2017/07/21/diagnostic-improvements-in-vs2017-15-3-0/) on the [Visual C++ Team Blog](https://blogs.msdn.microsoft.com/vcblog/).

**Comment by corob-msft** [comment]
See updated docs in https://docs.microsoft.com/en-us/cpp/build/reference/zc-ternary linked from the conformance page.

**Comment by tiagomacarios** [comment]
@corob-msft Thanks!
