### ISSUE TITLE
Incorrect remark for ArrayReference::operator() Operator

### ISSUE THREAD

**Issue by SergeyADoroshenko** [MicrosoftDocs/cpp-docs#1580]
The page says "Platform::ArrayReference and Platform::Array are standard C++ class templates, not ref classes." Platform::Array is actually a ref class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938f9317-eac1-10ee-e8a5-52428da6dbfe
* Version Independent ID: e342f8eb-0ef5-968e-241f-eaf3c5e37655
* Content: [Platform::ArrayReference Class](https://docs.microsoft.com/en-us/cpp/cppcx/platform-arrayreference-class?view=vs-2019#feedback)
* Content Source: [docs/cppcx/platform-arrayreference-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/platform-arrayreference-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@SergeyADoroshenko you are correct, thanks! Fix should appear in a day or so.
