### ISSUE TITLE
missing switch and range expressions

### ISSUE THREAD

**Issue by cyungmann** [MicrosoftDocs/cpp-docs#1585]
Missing switch and range expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc4f59b-159f-5038-fc24-4e78c7dff783
* Version Independent ID: f0015080-14af-58f1-15bb-c2691ea4186f
* Content: [Precedence and order of evaluation](https://docs.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation?view=vs-2019#feedback)
* Content Source: [docs/c-language/precedence-and-order-of-evaluation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/precedence-and-order-of-evaluation.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@cyungmann can you pls clarify? This topic is about operator precedence, and the info applies to any kind of expression. Unless I'm not understanding the question...

**Comment by cyungmann** [comment]
@mikeblome context here: https://stackoverflow.com/q/58088073/9287029

The precedence of switch and range expressions seems to be undocumented, and this seems like the most appropriate place to include that information.

**Comment by cyungmann** [comment]
@mikeblome, whoops it looks like I commented on the wrong page! Should be here instead: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence

**Comment by cyungmann** [comment]
@mikeblome already appears here, so I guess this can be closed/deleted: https://github.com/dotnet/docs/issues/14698

**Comment by mikeblome** [comment]
@cyungmann  no worries! Thanks for clarifying!
