### ISSUE TITLE
Changing the message 

### ISSUE THREAD

**Issue by tmalik345** [MicrosoftDocs/cpp-docs#1587]
Hi 
I’m trying to change the message “Hello, Windows desktop!" to something else but when I do and run the code an error message appears but only the original message is displayed. Is this message able to be modified?

Thank you.

TMalik.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@tmalik345 

There should be no problems with changing the code and rebuilding the solution. You may need to stop the debugger and close the console window the program is running in first. What is the error message you're seeing?
