### ISSUE TITLE
What happens if size is zero ?

### ISSUE THREAD

**Issue by arnaudrichard** [MicrosoftDocs/cpp-docs#1590]
Is the behavior defined in case size is zero ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 949915d3-2a42-24a5-4d43-e9a3e34addac
* Version Independent ID: 0ea2da0a-b9f1-1a9b-b368-922fa03d311b
* Content: [calloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/calloc?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/calloc.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/calloc.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@arnaudrichard 

The standard calls behavior when *size* is zero implementation-specific. The Microsoft implementation allocates a block of non-zero size and returns a pointer to it. It should be freed like any other allocated memory. However, the result of *writing* or *reading* through the returned pointer is undefined behavior.

I've updated the docs; the change should be visible by sometime Monday.

**Comment by arnaudrichard** [comment]
Impressive reactivity ! Thx.
FYI, I face a case where the stack is corrupted immediately after a call to calloc with size=0. Before any read or write to the returned pointer. So it is a good news it is supposed to follow POSIX standard which allows at least the call to calloc+free, but I guess there's a caveat in the implementation. Sorry I won't take time to craft a testcase because anyway I should handle the size==0 case in my code. However it's worth a code review/full testing on your side. Greetings!
