### ISSUE TITLE
Add documentation for /Zc:externC-

### ISSUE THREAD

**Issue by pgroke-dt** [MicrosoftDocs/cpp-docs#1594]
In compiler version 19.23 there's a new `/Zc` switch `/Zc:externC-` that isn't yet documented on https://docs.microsoft.com/en-us/cpp/build/reference/zc-conformance?view=vs-2019

I suggest to document it because it's a valuable tool for projects using libraries like Boost.Interprocess. See https://developercommunity.visualstudio.com/content/problem/756694/including-windowsh-and-boostinterprocess-headers-l.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127ca431-7115-bc22-25f2-f67339efc59a
* Version Independent ID: 45759414-19a0-326b-bbac-08b59e23a661
* Content: [/Zc (Conformance)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-conformance?view=vs-2019)
* Content Source: [docs/build/reference/zc-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zc-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
User story [1608902](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_workitems/edit/1608902).

**Comment by corob-msft** [comment]
Content should be published later today.
