### ISSUE TITLE
C5038 and C4495

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#160]
Hi can you add C5038 and C4495?

**Comment by corob-msft** [comment]
Sorry it's taken so long to get to this issue. Documentation for warning C5038 is coming soon, probably next week, after it gets reviewed. Right now the best explanation is found in the [Visual Studio 2017 conformance improvement](https://docs.microsoft.com/en-us/cpp/cpp-conformance-improvements-2017#c5038-order-of-initialization-in-initializer-lists) docs.

Warning C4495 is considered self-explanatory, so there's no individual topic for it, though it will soon show up in the list of compiler warning messages in [Compiler Warnings C4400 through C4599](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4400-through-c4599), which will come up if you hit F1 on the warning. The absence there was an oversight.

**Comment by corob-msft** [comment]
Updates are live; see https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5038 for an example.
