### ISSUE TITLE
References to LocalEspC should be replaced with ConcurrencyCheck

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/cpp-docs#1603]
LocalEspC has been replaced with ConcurrencyCheck. Please note that LocalEspC is a PREfast plug-in, but ConcurrencyCheck is an EspXEngine extension, enabled differently from the old LocalEspC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09296a0d-dea6-bcf6-7370-5ec2cf061835
* Version Independent ID: b6de3061-2d20-4508-6a76-663a2d61d098
* Content: [/analyze (Code Analysis)](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019#feedback)
* Content Source: [docs/build/reference/analyze-code-analysis.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/analyze-code-analysis.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updates should be visible tomorrow.
