### ISSUE TITLE
using legacy_stdio_definitions.lib outside from Visual Studio

### ISSUE THREAD

**Issue by carlkl** [MicrosoftDocs/cpp-docs#1620]
quotation: `To provide partial link compatibility with object files (and libraries) compiled with older versions of the Microsoft C Runtime headers, we provide a library, legacy_stdio_definitions.lib, with Visual Studio 2015 and later. This library provides compatibility symbols for most of the functions and data exports that were removed from the Universal CRT.`

The library `legacy_stdio_definitions.lib` ist provided with the installation of VS, but is not part of the Microsoft Visual C++ Redistributable. 

Request: 

Please clarify under which circumstances the license agreement allows to redistribute this library as part of another software package, for example an non-MS compiler.

**Comment by mikeblome** [comment]
@carlkl 
We do not allow redistributing any of our static (or import) libraries. However, you can link against the library and redistribute the resulting binary. 

A full list of what can be distributed is under Visual C++ Runtime section at: [Distributable Code for Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/releases/2019/redistribution).   
All files under the redist folder mentioned in the article are either DLLs, MSMs or vc_redist installer executables.

**Comment by corob-msft** [comment]
As @mikeblome said, only files on the [redist list](https://docs.microsoft.com/visualstudio/releases/2019/redistribution#visual-c-runtime-files) can be redistributed. Beyond that, we can't interpret or qualify our [license agreements](https://visualstudio.microsoft.com/license-terms/) or provide any kind of legal advice.
