### ISSUE TITLE
_abormal_termination is internal, yes, but only barely

### ISSUE THREAD

**Issue by jaykrell** [MicrosoftDocs/cpp-docs#1622]
AbnormalTermination is the public name for *exactly* this functionality.
excpt.h: #define AbnormalTermination         _abnormal_termination

This is how you can tell in a `__finally` if you left the __try via:
 - `return` -- TRUE
 - an exception -- TRUE
 - falling off the bottom -- FALSE
 - __leave -- FALSE (equivalent to jump to end of __try, and then falling out)

https://docs.microsoft.com/en-us/cpp/cpp/try-finally-statement?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685be682-38f1-f150-d488-c79b9265f3b6
* Version Independent ID: 44ddc760-1d40-5f84-8c2d-fbafde60b158
* Content: [_abnormal_termination](https://docs.microsoft.com/en-us/cpp/c-runtime-library/abnormal-termination?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/abnormal-termination.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/abnormal-termination.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jaykrell 

You're right, but even though `_abnormal_termination` is the implementation behind the [AbnormalTermination](https://docs.microsoft.com/windows/win32/Debug/abnormaltermination) macro, I'd never tell someone to call it in preference to using the macro. I don't think a change is warranted.
