### ISSUE TITLE
More Detail

### ISSUE THREAD

**Issue by traptw1thin** [MicrosoftDocs/cpp-docs#1623]
More detail on the Sources to Copy portion would be helpful. Currently, there is a macro set named DataFilesToCopyRemotely that I did not create but that I need to change, but when I click Edit&gt;View Macros it does not appear in the list, so I cannot change it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8e98d3-1826-922e-b4fd-18bdaa5d44a8
* Version Independent ID: 387b1b26-43a3-1069-9d80-1ce39c58ecb7
* Content: [Copy Sources Project Properties (Linux C++)](https://docs.microsoft.com/en-us/cpp/linux/prop-pages/copy-sources-project?view=vs-2019#feedback)
* Content Source: [docs/linux/prop-pages/copy-sources-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/prop-pages/copy-sources-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating
