### ISSUE TITLE
Official epilog shown in MASM does not work

### ISSUE THREAD

**Issue by paul-davies-autodesk** [MicrosoftDocs/cpp-docs#1627]
The epilog shown in MASM leaves the stack pointer 40h too low. Either the LEA instruction should be adding 20h or there is a missing add ESP instruction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2019#feedback)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@paul-davies-autodesk 
Thanks for pointing that out. The updated content should go live tomorrow as part of our daily publishing.
