### ISSUE TITLE
Could not able to generate the DLL to call from Labview

### ISSUE THREAD

**Issue by BaskaranRajamanickam** [MicrosoftDocs/cpp-docs#1630]
I am a newbie to C++, I told to convert the code from C++ to Labview. I am practising the problem of fibbanacci series provided on the microsoft page in the name "Walkthrough: Create and use your own Dynamic Link Library (C++)". When i try to built the program as mentioned in the instruction, it shows error named "unable to start program-MathLibrary.dll is not a valid win32 application." Please explain me what would be the reason. It would be really helpful.

Thanks
Baskaran

**Comment by corob-msft** [comment]
@BaskaranRajamanickam 

Sorry to hear you're having trouble. A DLL is a kind of library of code that gets used by another program. It's not a program that can run on its own. The example creates a separate program called MathClient to run the code in the DLL.

Assuming you created and built the MathClient app, my guess is that now you need to set the startup project in the Solution Explorer window to be the MathClient project. Right-click on the MathClient project in Solution Explorer, and choose **Set as Startup Project**. You've probably already built everything, so you should be able to just start it by using the green arrow in the toolbar, or by choosing the **Debug** > **Start Without Debugging** menu item. Give it a try.

**Comment by BaskaranRajamanickam** [comment]
Thank you for your kind reply :) Its really helpful :)
I actually wanted to call the DLL generated from MathLibrary.cpp in/from **Labview**.
I have not yet created the MathClient project. I wanted to call the MathLbrary.dll in/from labview, which would be generated using MathLibrary.cpp. But, when i run MathLibrary.cpp, it could not able to built and producing error named "unable to start program-MathLibrary.dll is not a valid win32 application." Please find the file attached.

![Screenshot (2)](https://user-images.githubusercontent.com/56631477/66908518-83ea7d00-f00b-11e9-80e1-1d4ddb88821e.png). 

Thanks
Baskaran

**Comment by corob-msft** [comment]
MathLibrary is not a program, and it can't be run by itself. You need to have another program call it. That's why you see the error message. It doesn't mean there's anything wrong with the code, it means you're trying to do something that doesn't make sense.

You should be able to call MathLibrary.dll from any program, not just the MathClient app as shown in the example. However, you probably should work through the whole example first, before trying to figure out how to call the library from a different program.

**Comment by BaskaranRajamanickam** [comment]
Thanks a lot! It makes sense now :)

Thank you for your help !

Yep, will try to understand and then try to call from Labview!

Thanks
Baskaran Rajamanickam
