### ISSUE TITLE
How to create a .dll file for already existing C++ file ??

### ISSUE THREAD

**Issue by BaskaranRajamanickam** [MicrosoftDocs/cpp-docs#1631]
Hello , I am newbie to C++ programming. I told to convert from C++ to Labview using .dll function. I already have the program written in C++ which calls the list of images in the main function. I wanted to call the list of images in Labview using C++ DLL, 
1. Please sameone explain how to generate the .dll file for already existing C++ file.
2. Please someone explain how to call the list of images in labview using .dll c++ file.

Thanks
Baskaran

**Comment by corob-msft** [comment]
@BaskaranRajamanickam 

This GitHub issues board is meant for raising issues about the documentation for the Microsoft C++ compiler and tools. Unfortunately, that means it isn't really the right forum to ask questions like yours. I expect questions about coding for LabVIEW would get more attention in [their forums](https://forums.ni.com/t5/Code-and-Documents/ct-p/code-documents?profile.language=en), instead.

**Comment by BaskaranRajamanickam** [comment]
Sorry and Thanks :)
