### ISSUE TITLE
What about 64 bit integers?

### ISSUE THREAD

**Issue by thomasjammet** [MicrosoftDocs/cpp-docs#1633]
I guess this page could be updated with 64 bits integer types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3172ab8c-37b9-1ce6-eeac-339ffed758b1
* Version Independent ID: b262c777-3978-8cd2-0173-b7f95b77ca1e
* Content: [C++ Integer Limits](https://docs.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=vs-2019#feedback)
* Content Source: [docs/c-language/cpp-integer-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/cpp-integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Page has been updated for the 21st century. Thanks @thomasjammet !
