### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by natanfudge** [MicrosoftDocs/cpp-docs#1636]
I copied the full example, but I get this error when building:
Error	LNK2019	unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	HdrTest	C:\Users\natan\Desktop\HdrTest\MSVCRTD.lib(exe_main.obj)	1	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by natanfudge** [comment]
I have tried changing the subsystem to Windows 
![image](https://user-images.githubusercontent.com/25990014/67089648-d913c380-f1b0-11e9-8b4f-ac638df6803e.png)
As outlined here https://stackoverflow.com/questions/33400777/error-lnk2019-unresolved-external-symbol-main-referenced-in-function-int-cde
But that did not solve the problem.

**Comment by natanfudge** [comment]
Going back and choosing under Application type, `Desktop application` solved the problem. Note that there is no "Windows Application" anymore as the docs suggest.

**Comment by corob-msft** [comment]
@natanfudge 

Thanks for reporting the issue. I've updated the wording to mention the Desktop application choice, and fixed an analysis issue in the code. The changes should be live tomorrow.
