### ISSUE TITLE
CppProperties.json does not work in root folder for c++ projects

### ISSUE THREAD

**Issue by amoldeshpande** [MicrosoftDocs/cpp-docs#1640]
> If, for example, you choose x64-Debug, Visual Studio creates a file called CppProperties.json in your root project folder and populates it like so:

VS may do exactly what this says, but the configurations in that file will not get picked up unless the file is inside the ".vs" directory,  *not* the root folder of the source.

I tore the one remaining hair on my head out trying to figure this out.

**Comment by sfreed141** [comment]
Which version of VS are you using? I wasn't able to repro on 16.3.5 or 16.4.0 preview 2.

Can you provide any repro steps or the project you are using?

**Comment by amoldeshpande** [comment]
I'm using the latest release of VS2019. I suppose that's 16.3.5 ?

As far as repro, you can try this repo https://github.com/amoldeshpande/haproxy and do an "open folder", and create the CppProperties via the "Manager Configurations" menu. They should be inoperative until you place it inside .vs

Below is the CppProperties I was trying to use.

```
{
  "projectName": "HAProxy",
  "environments": [
    {
      "PATH": "${env.vsInstallDir}\\VC\\ClangC2\\bin\\am64;${env.LOCALAPPDATA}\\Atlassian\\SourceTree\\git_local\\usr\\bin;${env.PATH}"
    }
  ],
  "configurations": [
    {
      "name": "Clang-x64-Release",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "includePath ,": [
        "${env.INCLUDE}"
      ],
      "defines": ["NDEBUG"],
      "intelliSenseMode": "windows-clang-x64",
      "environments": [
        {
          "PATH": "${env.vsInstallDir}\\VC\\ClangC2\\bin\\am64;${env.LOCALAPPDATA}\\Atlassian\\SourceTree\\git_local\\usr\\bin;${env.PATH}",
          "environment": "msvc_x64"
        }
      ]
    },
    {
      "name": "Clang-x64-Debug",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "includePath ,": [
        "${env.INCLUDE}"
      ],
      "defines": [ "DEBUG" ],
      "intelliSenseMode": "windows-clang-x64",
      "environments": [
        {
          "PATH": "${env.vsInstallDir}\\VC\\ClangC2\\bin\\am64;${env.LOCALAPPDATA}\\Atlassian\\SourceTree\\git_local\\usr\\bin;${env.PATH}",
          "BUILD_DEBUG": 1,
          "environment": "msvc_x64"
        }
      ]
    }
  ]
}
```

**Comment by sfreed141** [comment]
Found the issue: in Open Folder mode VS will ignore the stuff specified in .gitignore, which, in your case, ignored everything by default. Adding an exception to your .gitignore (!/CppProperties.json) will fix the issue.

**Comment by amoldeshpande** [comment]
Awesome, thank you!  Curious why it works from with .vs then ? Is that just a fallback location ?

**Comment by sfreed141** [comment]
Correct, the .vs folder is special :)

**Comment by mikeblome** [comment]
I added a note about .gitignore to the topic. Should go public in 1-2 days. Thanks for the feedback @amoldeshpande !
