### ISSUE TITLE
Length/count documentation is unnecessarily verbose/confusing

### ISSUE THREAD

**Issue by vlovich** [MicrosoftDocs/cpp-docs#1641]
&gt; Both len and count are in bytes for snprintf and _snprintf, wide characters for _snwprintf.

Length and count are actually always in # of characters. For snprintf/_snprintf the size of a charcter is 1 byte while for _snwprintf it's 2 bytes (size of a wide character). It's slightly misleading to say that length & count are in # of bytes for snprintf/_snprintf solely because the sizeof(char) == 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dc580a-fc4a-6a2a-bdfc-d52fc7b24f00
* Version Independent ID: 6047a186-0908-915a-0f35-c4b3e3f1b199
* Content: [snprintf, _snprintf, _snprintf_l, _snwprintf, _snwprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
@vlovich, thank you for bringing this to our attention. I've updated the page and it should be live by end of day 8/28
