### ISSUE TITLE
Where's the schema?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#1645]
The title purports to give me a schema reference (e.g. all data types used for all fields and all acceptable values for all fields), but it only gives a summary description and not a schema reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed0104b-8ba3-0b4d-5765-29f20e842b5c
* Version Independent ID: 7d5cc7af-86de-89cd-c86f-61f050ce7d1b
* Content: [CppProperties.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=vs-2019)
* Content Source: [docs/build/cppproperties-schema-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cppproperties-schema-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@LegalizeAdulthood thanks for the feedback. Topic has been updated to reflect that this is not a full schema reference, and to point to location of actual schema. Fix should appear in 2-3 days.
