### ISSUE TITLE
Reference to non-existing Q058860 Knowledge Base article

### ISSUE THREAD

**Issue by dragmz** [MicrosoftDocs/cpp-docs#165]
The following files reference non-existing Q058860 Knowledge Base article:

https://github.com/MicrosoftDocs/cpp-docs/blob/8fa8fdf0fbb4f57950f1e8f4f9b81b4d39ec7d7a/docs/data/oledb/cdynamicparameteraccessor-class.md

https://github.com/MicrosoftDocs/cpp-docs/blob/8fa8fdf0fbb4f57950f1e8f4f9b81b4d39ec7d7a/docs/data/oledb/using-dynamic-accessors.md

**Comment by corob-msft** [comment]
It's conceivable that the KB article number was a typo, but I could find no reference to it by title anywhere, either. However, it looks like the target may have been intended to be a description of one of the OLEDB samples that shipped in Visual Studio long ago. These are now on a GitHub repo, so I pointed the sample links there, instead. PR #170 should fix things when it goes live. Hope this helps.
