### ISSUE TITLE
test for metadata set globally

### ISSUE THREAD

**Issue by meganbradley** [MicrosoftDocs/cpp-docs#1655]
Hello!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d310125d-c556-88aa-05ad-bc695360b89d
* Version Independent ID: e4a9c9d6-8f16-8540-6a4c-55f37c593b9d
* Content: [ARM Assembler Command-Line Reference](https://docs.microsoft.com/en-us/cpp/assembler/arm/arm-assembler-command-line-reference?view=vs-2019)
* Content Source: [docs/assembler/arm/arm-assembler-command-line-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/arm/arm-assembler-command-line-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@meganbradley 
Hello! Just testing?

**Comment by meganbradley** [comment]
Yes - I'll close it. :)
