### ISSUE TITLE
Documentation of CRecordset::Open needs hyperlink

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#1656]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/cpp-docs.fr-fr/issues/15 
since it applies to original documentation.

@feraudyh commented 5 hours ago — with docs.microsoft.com
The following text

For more information about this string, see the table and the discussion of ClassWizard's role under Remarks.

left me confused. Maybe a hyperlink would help to know where to look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71164027-2c34-9866-08c8-8ceef252b0a8
* Version Independent ID: 9a2b95ed-065d-cb52-29e5-669d232230c0
* Content: [CRecordset Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/crecordset-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/crecordset-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/crecordset-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks for the feedback. Topic has been updated with a link. Should be visible in 1-2 days.
