### ISSUE TITLE
great, but...

### ISSUE THREAD

**Issue by prof-muller** [MicrosoftDocs/cpp-docs#1664]
how to used mixed C++ and asm in a project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98bfc236-120c-71db-ec5b-62ba2f843e45
* Version Independent ID: ff3fbc33-9193-3ece-1b4e-d134deb73b3c
* Content: [Writing Functions with Inline Assembly](https://docs.microsoft.com/en-us/cpp/assembler/inline/writing-functions-with-inline-assembly?view=vs-2019)
* Content Source: [docs/assembler/inline/writing-functions-with-inline-assembly.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/inline/writing-functions-with-inline-assembly.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@prof-muller 

I'm not sure what you're asking for. If you're trying to add `.asm` files to a C++ project, we've buried those instructions pretty well. You'll find them in [MASM for x64 (ml64.exe)](https://docs.microsoft.com/en-us/cpp/assembler/masm/masm-for-x64-ml64-exe?view=vs-2019) in the [Add an assembler-language file to a Visual Studio C++ project](https://docs.microsoft.com/en-us/cpp/assembler/masm/masm-for-x64-ml64-exe?view=vs-2019#add-an-assembler-language-file-to-a-visual-studio-c-project) section. I have to look this up again every time I want to do it. I don't know why MASM isn't associated with `.asm` files by default in the default toolset rules installed by the C++ workload.

If that's not what you're asking about, you'll need to reopen this issue and clarify.
