### ISSUE TITLE
missing label

### ISSUE THREAD

**Issue by prof-muller** [MicrosoftDocs/cpp-docs#1665]
it does not appear that you can jump from C++ code into a ASM block, but: C++ can jump (goto) over an ASM block; ams can jump (jmp) inside an asm block---but cannot jump from c++ into an ASM block... at least it seems that way with me.  This compiles: 
void func(void)
{
	goto C_Dest;  /* Legal: correct case   */
	

//	 cannot jump into asm block
//	 goto A_Dest;  
	
	__asm
	{
		jmp C_Dest; okay, jump out
		jmp A_Dest; okay, stay  in block

		A_Dest : 
	}
	
C_Dest:  
	return;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72c0bf3-40fe-7a05-6289-c30fad27b4b7
* Version Independent ID: 5edd2717-16eb-8093-b93a-725049f7b217
* Content: [Jumping to Labels in Inline Assembly](https://docs.microsoft.com/en-us/cpp/assembler/inline/jumping-to-labels-in-inline-assembly?view=vs-2019)
* Content Source: [docs/assembler/inline/jumping-to-labels-in-inline-assembly.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/inline/jumping-to-labels-in-inline-assembly.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@prof-muller 

Jumping into an asm block from C++ code works fine in my tests. You can try [Compiler Explorer](https://godbolt.org/z/dFctYy) to see what the generated assembly listing looks like. Locally, try the **/FAs** flag for a listing.

Closing, as this doesn't look like a documentation issue.
