### ISSUE TITLE
Walkthrough: Create a traditional Windows Desktop application (C++) VS 2017 Errors

### ISSUE THREAD

**Issue by MaxFun** [MicrosoftDocs/cpp-docs#1666]
https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017#create-a-windows-desktop-project

Copied the build code and passed it into HelloWindowsDesktop.cpp.

When I build it, I got the following errors;

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error (active)	E1097	unknown attribute "no_init_all"	DesktopApp	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h	7597	

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?	DesktopApp	c:\users\myself\source\repos\desktopapp\desktopapp	c:\users\myself\source\repos\desktopapp\desktopapp\hellowindowsdesktop.cpp	145	

Tried adding #include <stdafx.h>, but got even more errors

stdafx.h is in the Header Files folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017#create-a-windows-desktop-project)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@MaxFun 

The result may depend on which version of the compiler you're using. The latest version of Visual Studio 2017 (15.9.something) has a **Windows Desktop Wizard** template that doesn't check the **Precompiled Header** box in the wizard dialog if you select **Empty Project**. Earlier versions did check this box, and it's shown as checked in the screenshot. However, the code listing assumes the box wasn't checked. I'll see about cleaning up this inconsistency in the docs. For now, make sure the precompiled header option is turned off when you create the project.

**Comment by MaxFun** [comment]
Thanks, followed your instructions and the code build/ran with no errors.
When I initially checked the Empty Project box, it caused the Precompiled Header box to uncheck. Thinking  Precompiled Header checked box was need, I assumed I could delete any code generated to make a empty project.

**Comment by MaxFun** [comment]
Now that the code runs, I wanted to add a button on the window but the toolbox is all grayed out.
How do I add things to the window?

**Comment by corob-msft** [comment]
For that kind of info, I recommend the Windows documentation on [Using buttons](https://docs.microsoft.com/en-us/windows/win32/controls/using-buttons), or maybe just go through an [online tutorial series](https://docs.microsoft.com/en-us/windows/win32/learnwin32/learn-to-program-for-windows). It's twenty years old, but Charles Petzold's book, [Programming Windows (Fifth edition)](http://charlespetzold.com/pw5/), might still be the best intro to this style of coding. I think it's out of print, but used copies can be had pretty cheaply. And there's YouTube tutorials for everything.

**Comment by MaxFun** [comment]
After following links and searching on line, I could not find any solution to the grayed out toolbox items. Did find a lot on non-functioning toolbox questions for VS 2017 & 2019 with no solutions. Please verify that toolbox is not usable any more.

**Comment by mikeblome** [comment]
The tool box works only for things with design surfaces, i.e. Resources. If you right-click on "Resources" in Solution Explorer and choose for example Add New Resource > Dialog > FormView, then open the dialog, you can drag buttons etc onto that. However, I see no option to create a main window as a resource. That's definitely a gap in our documentation and possibly a limitation of the tools.  This is a question for the [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html).

**Comment by MaxFun** [comment]
When I right-click on "Resources" in Solution Explorer, there is no Add New Resource. If I select Add, there is a Resource, but it causes an error "fatal error RC1015: cannot open include file 'winres.h'"
Not sure where to go from here. I have updated VS 2017 and not seeing what you are seeing.
