### ISSUE TITLE
gets_s does more than the documentations describes

### ISSUE THREAD

**Issue by SteveWTF** [MicrosoftDocs/cpp-docs#1668]
Switching from gets to gets_s caused my program to crash. I did not know the length of the buffer so I entered a really big number. The gets_s does what the documentation describes but it also continues to put stuff into memory after the terminating null character. It pads 0xFE to every byte after the terminating null character up to the length of the buffer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fe6061f-bc40-b147-36f2-c68a0e6a29da
* Version Independent ID: 579dea39-e1c4-d118-51b2-27161cd389ef
* Content: [gets_s, _getws_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/gets-s-getws-s?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/gets-s-getws-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/gets-s-getws-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SteveWTF 

> **I did not know the length of the buffer so I entered a really big number.**

This is why your code fails. The point of the secure CRT functions is to require you to be explicit about the actual sizes of the buffers you're using. The functions make sure they don't go past the end of the buffer that you tell them is there. If you lie to a function, and it crashes immediately, consider yourself lucky. Your program could instead keep limping along in a damaged state and only keel over later, when it's hard to debug what went wrong. Who knows what evil it might do along the way.

The software engineering rule is, *know your bounds*. If you don't know what the size of the buffer is, you *can't use it safely*. If another part of your program knows what the size is, then pass that information along to all the users of the buffer.

**Comment by SteveWTF** [comment]
If the documentation was complete I would not have had an issue. Please change the documentation to fully describe what the function does so others can use it safely.

**Comment by corob-msft** [comment]
@SteveWTF 

I'm sorry you're having trouble with the documentation and the linked [Security features in the CRT](https://docs.microsoft.com/en-us/cpp/c-runtime-library/security-features-in-the-crt?view=vs-2019) provided. What information do you consider missing from these two documents? 

The normal behavior of secure CRT functions is to zero-fill buffers. I don't know what is causing the behavior you are seeing, but it is not part of the `gets_s` function, so far as I know.

**Comment by SteveWTF** [comment]
The gets_s function places the entered text into the buffer with a terminating null character as described in the documentation. What the documentation fails to mention is that it does more than that. It continues to write 0xFE characters to the end of the buffer.

I made this test code to show this. There is a char buffer with 4096 bytes allocated. The test code sets the first 20 bytes to ‘x’ and writes the first 20 characters to the console, then does a gets_s telling it the buffer size is 15. I typed in “Hello” which is 5 bytes. Then it prints out the first 20 characters of the buffer again. As you can see the first 6 bytes have been modified according to the gets_s documentation. The first 5 bytes contain “Hello” and the 6th byte is null terminated. Notice that the 7th through the 15th bytes have been changed to 0xfe. This behavior is not mentioned in the documentation. 

If we’re concerned with safety I think the gets_s should be changed to do only what the documentation says it does. Writing a bunch of characters that will never be seen has its own hazards. Short of that the documentation should be changed to describe what happens to your buffer beyond the terminating null character.

Here is the test code:

int _tmain(int argc, _TCHAR *argv[])
{
    char buf[4096];

    int i;

    for(i = 0; i < 20; i++)
    {
        buf[i] = 'x';
        printf("buf[%i] = %0x\n", i, (unsigned char)buf[i]);
    }
    gets_s(buf, 15);
    for(i = 0; i < 20; i++)
    {
        printf("buf[%i] = %0x\n", i, (unsigned char)buf[i]);
    }

    
    gets_s(buf,999); // this holds the window open until you press Enter
    return 0;
}

Here is the console output:

buf[0] = 78
buf[1] = 78
buf[2] = 78
buf[3] = 78
buf[4] = 78
buf[5] = 78
buf[6] = 78
buf[7] = 78
buf[8] = 78
buf[9] = 78
buf[10] = 78
buf[11] = 78
buf[12] = 78
buf[13] = 78
buf[14] = 78
buf[15] = 78
buf[16] = 78
buf[17] = 78
buf[18] = 78
buf[19] = 78
Hello
buf[0] = 48
buf[1] = 65
buf[2] = 6c
buf[3] = 6c
buf[4] = 6f
buf[5] = 0
buf[6] = fe
buf[7] = fe
buf[8] = fe
buf[9] = fe
buf[10] = fe
buf[11] = fe
buf[12] = fe
buf[13] = fe
buf[14] = fe
buf[15] = 78
buf[16] = 78
buf[17] = 78
buf[18] = 78
buf[19] = 78

**Comment by corob-msft** [comment]
@SteveWTF 

Your comment triggered a memory. The debug versions of some secure CRT functions do indeed fill buffers with the 0xFE magic value by default. You can read about it in [_CrtSetDebugFillThreshold](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetdebugfillthreshold?view=vs-2019) (which also mentions how to turn the feature off). I didn't think `gets_s` was one of the affected functions, but I eyeballed the source code in the Windows SDK, and it is in fact doing just that. You can see it yourself in %WindowsSdkDir%Source\%WindowsSDKLibVersion%ucrt\stdio\gets.cpp around line 107 in the latest version. 

I'll check for other functions that might have missed documenting this feature, and add a note.

**Comment by SteveWTF** [comment]
I just tried my test code in release and sure enough, it doesn’t do it. Thanks for looking into this.

I think I originally ran into this with fgets_s.
