### ISSUE TITLE
Compiler warning help link not redirected

### ISSUE THREAD

**Issue by NextTurn** [MicrosoftDocs/cpp-docs#1669]
Some compiler warning help links (in Visual Studio Error List window) are not redirected to the correct article, for example, https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(C5045)&rd=true should be redirected to https://docs.microsoft.com/cpp/error-messages/compiler-warnings/c5045.

**Comment by corob-msft** [comment]
@mikeblome Is this a product issue or a site redirection issue? There was no C5045 on the MSDN site; it's only ever existed on docs.microsoft.com, so that and any other new error message might run into this problem.

**Comment by mikeblome** [comment]
investigating

**Comment by rloutlaw** [comment]
@mikeblome @corob-msft  The content for the C5045 warning message doesn't contain F1 keyword metadata-once added and republished the content should work fine.

**Comment by corob-msft** [comment]
@NextTurn 

Thanks for the report. I found another 13 diagnostics articles that were missing F1 metadata. All of them should be fixed and published by sometime in the next day or two.
