### ISSUE TITLE
Community Support ?

### ISSUE THREAD

**Issue by johne53** [MicrosoftDocs/cpp-docs#1686]
As a long time VC++ user I'm interested in the cross-platform aspect of trying Visual Studio with Clang/LLVM. Are there any user forums or mailing lists where I can chat to other programmers who've already gone down this route?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fff2d2-a800-945f-1545-6f0a8896ce68
* Version Independent ID: 4caa187d-dc33-1b1c-f9fa-c3ffe1078054
* Content: [Clang/LLVM support in Visual Studio CMake projects](https://docs.microsoft.com/en-us/cpp/build/clang-support-cmake?view=vs-2019)
* Content Source: [docs/build/clang-support-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/clang-support-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@johne53 
That's an interesting question, but not one we'd normally address in this article. I'd say that an internet search is your best option.
