### ISSUE TITLE
Wrong link in cchecklistbox-class.md

### ISSUE THREAD

**Issue by Blonder** [MicrosoftDocs/cpp-docs#1687]
The Link https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/codesnippet/cpp/cchecklistbox-class_1.cpp
is wrong must be
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/codesnippet/CPP/cchecklistbox-class_1.cpp

**Comment by corob-msft** [comment]
@Blonder 
Our publishing build system uses a copy of the repo on a Windows filesystem that's largely insensitive to case, except when comparing files for changes. Basically, a change to either the folder name or the relative path in the article could cause build problems. So, we try not to touch them. The articles build correctly. Links work when navigating the article source on Windows. We don't think fixing it's worth the risk.

**Comment by Blonder** [comment]
I am getting a 404 on Windows with Chrome when clicking on the link, also with Firefox and Opera.and Brave.

**Comment by corob-msft** [comment]
@Blonder 
Where do you see the link? I scanned the C++ documentation, and a reference to this file only appears in one place, as a relative link that resolves into a bit of example source code displayed on the [CCheckBoxList Class](https://docs.microsoft.com/cpp/mfc/reference/cchecklistbox-class) page.

**Comment by Blonder** [comment]
@corob-msft 
Here: https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/reference/cchecklistbox-class.md
Scroll down to
`Example
[!code-cppNVC_MFCControlLadenDialog#60]`
Here also the link text looks damaged.
The link goes into this github page: https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/codesnippet
Here the name is CPP not cpp.
You get a 404 if you click it.

**Comment by Blonder** [comment]
It seems that all example links are wrong: e.g. https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/reference/ccombobox-class.md 
`Example
[!code-cppNVC_MFC_CComboBox#3]`

**Comment by corob-msft** [comment]
Ah, now I understand what you're looking at. My recommendation is, stop looking at the [preview page](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/reference/cchecklistbox-class.md), and look at the [finished one instead](https://docs.microsoft.com/cpp/mfc/reference/cchecklistbox-class). That one looks the way we intend it to look, and all the links work, too. The repo is for meant for authoring, not for reading the documentation.

Here's the problem. The GitHub preview engine doesn't understand the dialect of markdown we use to create [Microsoft Docs](https://docs.microsoft.com). Our content uses markdown extensions for code snippets, graphics, video, notes, and version-specific content. The GitHub markdown renderer doesn't support these extensions. They look like links in the preview, but really, they're instructions for the HTML rendering engine. The fact that most of the links usually work in the previewer is something of a happy accident.

We think of the preview on GitHub as a slightly broken, low-fidelity version of our content. It's only good for a quick sanity check when using the web editor. We have no plans to try to make it work like our website. Broken links here are not something we care about, if the content works correctly on the official website. Especially when fixing them for the preview might break them on the official website.

**Comment by Blonder** [comment]
Ah o.k. I understand.
