### ISSUE TITLE
This page should be renamed

### ISSUE THREAD

**Issue by davidhesselbom** [MicrosoftDocs/cpp-docs#1690]
This page doesn't describe how to "use MSBuild to create a Visual C++ project", it describes how to
1. create a Visual C++ project using a *text editor* and 
2. use MSBuild to *build* the project.

I was looking for a way to use MSBuild to create a project (like dotnet.exe can with .NET Core projects) when I found this, only to realize it wasn't what I was looking for at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be969ff1-c6bf-a58a-4f1e-cc6c037ab8f5
* Version Independent ID: 17272cba-73e8-d640-104a-989345208ca8
* Content: [Walkthrough: Using MSBuild to Create a Visual C++ Project](https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by davidhesselbom** [comment]
Happily, I later found this, which is a lot closer to what I was really looking for! https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-api?view=vs-2019

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
