### ISSUE TITLE
False positive C4251

### ISSUE THREAD

**Issue by JackHeeley** [MicrosoftDocs/cpp-docs#1693]
Microsoft Visual Studio Enterprise 2019 Version 16.3.8 VisualStudio.16.Release/16.3.8+29503.13

C4251 warning is about passing CRT objects across DLL boundaries. 

Its wrong to raise this warning on private data members. The case of pimpl its especially obvious that the object is going nowhere. Here's my code snippet where this occurs...

private:
   ///&lt;summary&gt; forward reference to private implementation.&lt;/summary&gt;
   class impl;

   ///&lt;summary&gt; smart unique pointer to private implementation.&lt;/summary&gt;
   ///&lt;remarks&gt; with default copy, move and compare support.&lt;/remarks&gt;
#pragma warning (disable:4251)
   spimpl::impl_ptr&lt;impl&gt; pimpl;
#pragma warning (default:4251)

See also: 		https://github.com/oliora/samples/blob/master/spimpl.h

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b571095e-4252-7238-10a9-3db7b5305031
* Version Independent ID: a71ff684-6456-f516-c2e8-c6626c5b7eb0
* Content: [Potential Errors Passing CRT Objects Across DLL Boundaries](https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JackHeeley 
Your complaint is acknowledged, but unfortunately, you're making it in the wrong place. The documentation reflects what the compiler does. If you think compiler diagnostic behavior should change, then the best place to make the suggestion is on our [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. It gives others a place to chime in with support, which may increase its chances of being taken up by the development team. I'm closing this, as it's not (yet) a documentation issue.

**Comment by JackHeeley** [comment]
Thanks, I realised that was probably the case just after I posted.
