### ISSUE TITLE
Exponent of hexadecimal float should be decimal, not hexadecimal

### ISSUE THREAD

**Issue by skoehler** [MicrosoftDocs/cpp-docs#1696]
Many other sources explicitly state, that the "p" character in a hexadecimal float is followed by a decimal number. In other words: 1p10 is one times two to the power of 10, not 16. I believe this page is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0656f7f5-94a4-e2cd-c0ff-7949a271dd45
* Version Independent ID: 7f8311a0-098a-d03e-d215-61c00c88966e
* Content: [strtod, _strtod_l, wcstod, _wcstod_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mr-intj** [comment]
Nice catch.

**Comment by TylerMSFT** [comment]
@skoehler, thank you for bringing this to our attention. I've updated the page and it should be live by end of day 8/28
