### ISSUE TITLE
The format in this simple example can be confusing for people who are new to programming

### ISSUE THREAD

**Issue by vladik-hbinov** [MicrosoftDocs/cpp-docs#1697]
This can be the first coding example a new programmer sees.
The instruction says "Format: a+b | a-b | a*b | a/b" but the example has spaces before and after the operation.
Maybe they will not notice but you should be strict and stick to the format without the spaces in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019#feedback)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Mstava** [comment]
Hi @corob-msft I just fixes this issue and make a pull request at #1991

**Comment by TylerMSFT** [comment]
Spaces or not are a stylistic thing. The code works either way and programmers use both styles. Given the backlog of other work, I don't see being able to prioritize this one. Closing.
