### ISSUE TITLE
CString::Replace escape chars?

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#1703]
Are there any? When the Replace fails, how do I know which characters it can fail on without a list of characters that need escaping.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a9ec5a-f8e2-f739-1b39-74b4a775ee98
* Version Independent ID: c1eaf2d0-1cd3-25a1-c44d-3aae49be555b
* Content: [CStringT Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cstringt-class?view=vs-2019&source=docs#replace)
* Content Source: [docs/atl-mfc-shared/reference/cstringt-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cstringt-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
