### ISSUE TITLE
Cross Compile in WSL - Deploy and Debug on Arm Device

### ISSUE THREAD

**Issue by martinbu** [MicrosoftDocs/cpp-docs#1704]
"Specify different machines for building and debugging" needs two remote machines as described above. One Linux x64 Build host and the target arm device.
Is it possible to provide an example how to use WSL for cross compiling for a linux arm device? Then deploy and debug the build on the target linux arm device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001834ce-31d2-e768-1df1-4a776aa9ef65
* Version Independent ID: 45f15fc0-e5c7-34a1-2469-f38d304ef5bd
* Content: [Deploy, run, and debug your C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/deploy-run-and-debug-your-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/deploy-run-and-debug-your-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by martinbu** [comment]
Hi,

I was able to cross compile my program now in wsl with the following configuration. But I cannot debug the application on the remote machine. Nothing is copied to the remote machine... 

One more issue that I have now is, that the intellisense does not work correctly anymore. Visual Studio does not detect the header files of the additional include files...

**CMakeSettings.json**
```
{
    "name": "WSL-Debug-Cross",
    "generator": "Unix Makefiles",
    "configurationType": "Debug",
    "buildRoot": "${projectDir}\\out\\build\\${name}",
    "installRoot": "${projectDir}\\out\\install\\${name}",
    "cmakeExecutable": "/usr/bin/cmake",
    "cmakeCommandArgs": "",
    "buildCommandArgs": "-j 6",
    "ctestCommandArgs": "",
    "inheritEnvironments": [ "linux_arm" ],
    "wslPath": "${defaultWSLPath}",
    "addressSanitizerRuntimeFlags": "detect_leaks=0",
    "cmakeToolchain": "wsl_linux_arm_toolchain.cmake",
    "variables": [
      {
        "name": "CONFIGURATION_NAME",
        "value": "${name}",
        "type": "STRING"
      },
      {
        "name": "ADDITIONAL_INCLUDES",
        "value": "/opt/sysroot/usr/include",
        "type": "STRING"
      },
      {
        "name": "ADDITIONAL_LINK_DIRS",
        "value": "/opt/sysroot/usr/lib",
        "type": "STRING"
      }
    ],
    "addressSanitizerEnabled": false,
    "remoteMachineName": "${defaultRemoteMachineName}",
    "remoteCMakeListsRoot": "~/vs/src/test/Debug",
    "remoteBuildRoot": "~/vs/build/test/build/Debug",
    "remoteInstallRoot": "~/vs/build/test/install/Debug",
    "remoteCopySources": true,
    "remoteCopySourcesOutputVerbosity": "Normal",
    "remoteCopySourcesConcurrentCopies": "10",
    "remoteCopySourcesMethod": "rsync",
    "remoteCopySourcesExclusionList": [ ".vs", ".git" ],
    "rsyncCommandArgs": "-t --delete --delete-excluded",
    "remoteCopyBuildOutput": true
}
```

**wsl_linux_arm_toolchain.cmake**
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(tools /opt/toolchains/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf)

set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER, ${tools}/bin/arm-linux-gnueabihf-c++)
```

**Comment by martinbu** [comment]
I have a valid configuration now for building and deployment. But with this configuration the debugInfo variables in lauch.vs.json are all undefined... Therefore debugging is still not possible.

**CMakeSettings.json**
```
{
      "name": "WSL-Debug-Cross",
      "generator": "Unix Makefiles",
      "configurationType": "Debug",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeExecutable": "/usr/bin/cmake",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-j 6",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "linux_arm" ],
      "wslPath": "${defaultWSLPath}",
      "addressSanitizerRuntimeFlags": "detect_leaks=0",
      "variables": [],
      "addressSanitizerEnabled": false,
      "cmakeToolchain": "wsl_linux_arm_toolchain.cmake",
      "remotePostbuildCommand": "rsync -r -t --delete --delete-excluded ./ <Username>@<IP_ADDRESS>:/home/root/build" // deploy manually
    },
```

**wsl_linux_arm_toolchain.cmake**
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_SYSROOT /opt/sysroot)

set(tools /opt/toolchains/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf)

set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER, ${tools}/bin/arm-linux-gnueabihf-c++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
**launch.vs.json**
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "my-program Cross Compiled (my-program)",
      "project": "CMakeLists.txt",
      "projectTarget": "my-program (my-program)",
      "cwd": "/home/root/build",
      "program": "/home/root/build/my-program",
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "<IP_ADDRESS>",
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}", // invalid variable
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}", // invalid variable
          "/p",
          "${debugInfo.parentProcessId}", // invalid variable
          "/c",
          "${debuggerCommand}",
          "--tty=${debugInfo.tty}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
  ]
}
```

**Comment by mikeblome** [comment]
@martinbu thanks for the feedback. We are working on getting better docs for this scenario!

**Comment by sfreed141** [comment]
The issue you're seeing with the additional includes not being picked up for intellisense is a [bug ](https://developercommunity.visualstudio.com/content/problem/752964/intellisense-does-not-see-vcpkg-include-directorie.html) that was fixed in 16.4 (or 16.5 preview 1).

There isn't support for build/deploy separation using native WSL yet (it's on our backlog) but it should work fine if you connect over SSH. By providing remoteMachineName in your configuration it should be treated as a "remote over SSH" configuration (which you've done), but you should also remove wslPath as that might be what's causing the ${debugInfo.*} variables to not be set. Hope that helps!

**Comment by martinbu** [comment]
hi, thank you for your response.
Yes, if I treat the wsl as a remote machine the cross compilation, deployment and remote debugging works. But therefor I have to configure a ssh server inside wsl.
But since there is already a working wsl integration, there shouldn't be much missing for the scenario I described. Great to hear that it is on the backlog. This feature would a be a greate enhancement for me. I leave this issue open until the feature exists and works.
Thanks for now.

**Comment by mfide** [comment]
Is this supported with VS2022 now? I want to compile a CMake project for a Raspberry Pi on WLS2 (because the compilation is faster than on a Pi) but deploy and debug on the real platform which is an Raspberry Pi.

**Comment by elizabethmorrow** [comment]
VS2022 does have support for compiling on WSL2 and deploying/debugging on a remote system. To accomplish this you'll use the deploy{} block in launch.vs.json:

"disableDeploy": false,
"deployDirectory": "~\foo",
"deploy" : [
   {
      "sourceMachine": "127.0.0.1 (username=example1, port=22, authentication=Password)",
      "targetMachine": "192.0.0.1 (username=example2, port=22, authentication=Password)",
      "sourcePath": "~/example.cpp",
      "targetPath": "~/example.cpp",
      "executable": "false"
   }
]

More documentation found here: https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio-2019-wsl-asan-for-linux-separation-of-build-and-debug/

**Comment by TylerMSFT** [comment]
Closing because tracking feature requests/availability as a doc issue isn't what doc issues are designed for.
