### ISSUE TITLE
Winrt version

### ISSUE THREAD

**Issue by ergan89** [MicrosoftDocs/cpp-docs#1714]
Hi, is there a winrt version for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6f884e-c216-4396-6ba1-c49863cb9141
* Version Independent ID: 98d65d43-b51b-8d3b-1ed7-66856f91f98a
* Content: [to_vector Function](https://docs.microsoft.com/en-us/cpp/cppcx/to-vector-function?view=vs-2019#feedback)
* Content Source: [docs/cppcx/to-vector-function.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/to-vector-function.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Not as such, though you can go the other direction easily. The content in [Standard C++ data types and C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/std-cpp-data-types) is suggestive of how to move data types back and forth.
