### ISSUE TITLE
Development of 64-bit C and C++ applications

### ISSUE THREAD

**Issue by AndreyKarpov** [MicrosoftDocs/cpp-docs#1717]
Yes, this page lists common issues that can be encountered, porting an application to a 64-bit system. However, in practice, you can face other problems. If you want to get acquainted with this topic in more detail, then I suggest you get acquainted with this big article: Development of 64-bit C and C++ applications - https://www.viva64.com/en/l/full/
This link can be added to "See also".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b74bd46-c934-2385-fb14-37158e70f975
* Version Independent ID: 6f74f919-9e3f-9c5f-681a-83a14b661464
* Content: [Common Visual C++ 64-bit Migration Issues](https://docs.microsoft.com/en-us/cpp/build/common-visual-cpp-64-bit-migration-issues?view=vs-2019#feedback)
* Content Source: [docs/build/common-visual-cpp-64-bit-migration-issues.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/common-visual-cpp-64-bit-migration-issues.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closed as a promotion.
