### ISSUE TITLE
Vector::InsertAt inserts AT index, not after element at index

### ISSUE THREAD

**Issue by samyun** [MicrosoftDocs/cpp-docs#1719]
"Inserts the specified item into the current Vector after the element identified by the specified index."

In my code, I see that the item is inserted at the index, not after the element at the index.

Compare to UWP Windows::Foundation::Collections::IVector https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivector-1.insertat "Inserts an item at a specified index in the vector."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49ce316-6234-040c-f446-f23efee9f308
* Version Independent ID: 3ed6b779-6ac8-c9f5-0012-6effd4e8debc
* Content: [Platform::Collections::Vector Class](https://docs.microsoft.com/en-us/cpp/cppcx/platform-collections-vector-class?view=vs-2019#feedback)
* Content Source: [docs/cppcx/platform-collections-vector-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/platform-collections-vector-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@samyun thanks! Fix should appear in a day or so.
