### ISSUE TITLE
Regarding the 2 occurrences of "Microsoft Specific" in https://docs.microsoft.com/en-us/cpp/c-language/escape-sequences?redirectedfrom=MSDN&view=vs-2019

### ISSUE THREAD

**Issue by abergquist** [MicrosoftDocs/cpp-docs#1721]
Hi, both occurrences of "Microsoft Specific" need to be replaced with either "Microsoft-Specific" or "Microsoft-specific" (1) to be consistent with "device-specific" in the same page which comports with (2) https://en.wikipedia.org/wiki/Compound_modifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a038b8f0-2f78-6a3d-a881-744a21ef9d0a
* Version Independent ID: 8f22036a-4d4e-6e76-7f8f-e3de94ff3186
* Content: [Escape Sequences](https://docs.microsoft.com/en-us/cpp/c-language/escape-sequences?redirectedfrom=MSDN&view=vs-2019)
* Content Source: [docs/c-language/escape-sequences.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/escape-sequences.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@abergquist 

Grammatically, you're absolutely right. The **Microsoft Specific** - **END Microsoft Specific** pair of bold tags appear in over 350 of our articles. As far as I can tell, they've been used this way for a very long time. I'm disinclined to change only this one set.

**Comment by corob-msft** [comment]
Closing as we've adopted some similar style changes that will be gradually applied as we touch documents.
