### ISSUE TITLE
"END Microsoft Specific"

### ISSUE THREAD

**Issue by abergquist** [MicrosoftDocs/cpp-docs#1722]
Also, in lieu of having "END Microsoft Specific", I recommend including "Microsoft-specific" in a box along with the Microsoft-specific text.  That eliminates the extra text of "END Microsoft Specific" and also eliminates some potential confusion (the "END Microsoft Specific" looks like the header for the text that follows it).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a038b8f0-2f78-6a3d-a881-744a21ef9d0a
* Version Independent ID: 8f22036a-4d4e-6e76-7f8f-e3de94ff3186
* Content: [Escape Sequences](https://docs.microsoft.com/en-us/cpp/c-language/escape-sequences?view=vs-2019)
* Content Source: [docs/c-language/escape-sequences.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/escape-sequences.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Thanks. It's an interesting suggestion, but we're not adopting it because it doesn't fit with our other editorial standards.
