### ISSUE TITLE
Forward binary comaptibility guarantees?

### ISSUE THREAD

**Issue by Resurr3ction** [MicrosoftDocs/cpp-docs#1728]
In this topic: https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/porting/binary-compat-2015-2017.md there used to be explicit guarantee for backwards binary compatibility (still there) and explicit denial of forward binary compatibility:

> When consuming libraries built with a toolset whose version is greater than the toolset used to compile and link the application. For example, a program that is compiled and linked with compiler version 19.12 can consume libraries that are compiled with 19.0 up through 19.12. Also, binary compatibility only exists between Visual Studio 2015 and Visual Studio 2017; linking 19.x programs with libraries produced by Visual Studio 2013 or earlier is not supported.

The latter is no longer there. Along with wording such as

> The runtime libraries and apps compiled by any of these versions of the compiler are binary-compatible.

it might lead to incorrect assumptions that forward binary compatibility is indeed supported. I do not thing it is the case and removal of the first quoted paragraph was wrong and decreased clarity of the topic. If the forward binary compatiblity is indeed NOT guaranteed (as I suspect and as it used to be for a long time) then the topic should definitely say so explicitly.

**Comment by corob-msft** [comment]
@Resurr3ction 
By coincidence, I made a change in this article yesterday, which may address your issue. Please take a look at the current content, and see if it answers your question about forward compatibility. There's a new distinction made between the toolset version used for compiling, and the one used for linking, for forward binary compatibility that wasn't in the article previously. Basically, an old app can consume a newer static library without being recompiled, as long as it's relinked using the newer linker. This isn't a new feature, but it wasn't described correctly in the paragraph you quote, either.

**Comment by Resurr3ction** [comment]
@corob-msft It actually does! At our organization what we are doing is delivering newer binaries to older releases. When they came from the same compiler/linker it was not a problem. Now when we upgrade to a newer compiler we would like to know whether this is still a safe practice. I assumed not based on the original quote. But now it is quite clear I believe. Recompilation would not be needed but relinking would. Thank you.

**Comment by corob-msft** [comment]
@Resurr3ction 
I'm glad that worked out. I thought it was funny how your comment came in not long after I'd made the change, but before it was visible. Prescient!
