### ISSUE TITLE
Bad design

### ISSUE THREAD

**Issue by satya-das** [MicrosoftDocs/cpp-docs#1732]
Why `src` is not `const char*`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d63df7c-131f-66a2-cfba-78c584b4865a
* Version Independent ID: 973598db-2ae7-fd75-e417-016052df59f4
* Content: [_swab](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/swab?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/swab.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/swab.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@satya-das 
That's a philosophical question for the creator of the function. My guess is, it was created long before using const was a common software engineering paradigm for read-only data. The documentation accurately represents the declaration of the function, so I'm closing this issue.
