### ISSUE TITLE
Confusion regarding 64-bit support

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/cpp-docs#1734]
Under the *Remarks* section, there is a note that says the following:
> Structured exception handling works with Win32 for both C and C++ source files.

Does this mean that SEH only works for 32-bit programs, and not 64-bit? And does SEH only work for 32-bit regardless of if you are implementing it using `__try`-`__except` or the `/EHa` compiler option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5dfade-e224-32b4-919a-1e4f0c7b87ac
* Version Independent ID: 00702e1e-21c9-3520-ebec-53ff75dbb8f5
* Content: [try-except Statement](https://docs.microsoft.com/en-us/cpp/cpp/try-except-statement?view=vs-2019#feedback)
* Content Source: [docs/cpp/try-except-statement.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/try-except-statement.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@FrankAtHexagon 

SEH works on all Windows platforms, whether Intel, AMD, or ARM, 32-bit or 64-bit. 

I understand the source of your confusion. Win32 is the name of the [native Windows OS API](https://docs.microsoft.com/en-us/windows/win32/api/). It got the name thirty years ago in the transition from 16-bit to 32-bit Windows, but it hasn't been limited to 32-bit processors for the last twenty years. There was never much traction for calling it Win64, although there is an obsolete compiler switch with that name. I don't want to insert a history lesson everywhere we use Win32 to mean the native OS API, as opposed to WinRT or the .NET platform, so I'll leave this alone.

**Comment by FrankAtHexagon** [comment]
Thank you for your help! This was exactly what my team was looking for.
