### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/cpp-docs#1737]
There is no mention or example where you scan more than one thing at a time in the buffer string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb0a71a-b940-e7e9-d6b2-a4d1ce0260b6
* Version Independent ID: 610f338f-1d30-7899-2df9-c0a1600ca7de
* Content: [sscanf_s, _sscanf_s_l, swscanf_s, _swscanf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/sscanf-s-sscanf-s-l-swscanf-s-swscanf-s-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@markyoung143 
That's true. It should be pretty simple to add an example that reads, say, two or three items in a single `sscanf_s` call to the example code, if anyone should feel sufficiently ambitious.

**Comment by KishkinJ10** [comment]
sir can i work on this ? i am a beginner can you guide me from where to start?

**Comment by TylerMSFT** [comment]
@KishkinJ10 , that would be fanstastic!
Sorry for the delay. We've been getting ready for a doc release.

Here's our [contributor guide](https://docs.microsoft.com/en-us/contribute) which has steps for making a change to our docs.
You might start with [this approach](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) which shows you how to make an edit to an existing document.

Thanks again, @KishkinJ10.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
