### ISSUE TITLE
wcstok has wrong prototype

### ISSUE THREAD

**Issue by bhaible** [MicrosoftDocs/cpp-docs#1738]
The documentation at `c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md` lists `wcstok` having a 2-argument prototype. However, ISO C and MSVC 14 (= Visual Studio 2015) has changed it to have a 3-argument prototype, unless the user has defined the macro `_CRT_NON_CONFORMING_WCSTOK`. See wchar.h around lines 218..265.

The documentation needs to be updated to
  - mention the 3-argument prototype,
  - optionally mention the `_CRT_NON_CONFORMING_WCSTOK` macro.

**Comment by TylerMSFT** [comment]
@bhaible, good catch. I have added the signature for the three parameter version of wcstok(), explained that the two parameter version is not standard and that you need to define _CRT_NON_CONFORMING_WCSTOK to use the older, non-standard two-argument version. Thanks for helping us improve the docs.

**Comment by TylerMSFT** [comment]
Oh, these updates should be live tomorrow (6/25)

**Comment by bhaible** [comment]
I don't see it fixed so far,
- neither in https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md
- nor in https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l?view=vs-2019 .

**Comment by TylerMSFT** [comment]
I see it. It's live, here: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l?view=vs-2019
Search for "context"

**Comment by bhaible** [comment]
I see. Thanks!
Sorry for the false alarm.

**Comment by TylerMSFT** [comment]
@bhaiable, no worries! It's fantastic that you were willing to take the time to help us improve the docs. Thank you very much.
-Tyler

**Comment by interrupt-routine** [comment]
Furthermore, it seems like in Windows CRT, `wcstok_s()` is merely an alias for the standard `wcstok()`, even though it is claimed to have security improvements.
