### ISSUE TITLE
Sourced from wutime.com

### ISSUE THREAD

**Issue by Wutime** [MicrosoftDocs/cpp-docs#1743]
I submitted wide-character construct - if you have a poignant question let me know through https://www.wutime.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9565cf21-a9b5-39a3-34df-1db5242f1863
* Version Independent ID: ff3a236b-abbe-c74a-ca48-49081ababe36
* Content: [_utime, _utime32, _utime64, _wutime, _wutime32, _wutime64](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/utime-utime32-utime64-wutime-wutime32-wutime64?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/utime-utime32-utime64-wutime-wutime32-wutime64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/utime-utime32-utime64-wutime-wutime32-wutime64.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Wutime This issue doesn't appear to identify a problem in the documentation. Could you clarify what's wrong? I'll reopen it if something needs to be fixed.
