### ISSUE TITLE
typo in example

### ISSUE THREAD

**Issue by datgame** [MicrosoftDocs/cpp-docs#1750]
the example lacks a / (or -) prefixing the middle "NODEFAULTLIB:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126acce3-7235-e676-89fa-77f16e2e6dc0
* Version Independent ID: 4a45039e-0d7c-9ec6-31b9-00b75209c332
* Content: [Linker Tools Warning LNK4098](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4098?view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4098.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4098.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@datgame Thanks for the report. It's fixed now.

**Comment by MOHAMED-Button-Games** [comment]
Thank you so much.
