### ISSUE TITLE
stricmp and wcsicmp are not POSIX functions

### ISSUE THREAD

**Issue by mna41** [MicrosoftDocs/cpp-docs#1753]
The page claims that stricmp and wcsicmp are POSIX functions. No, they are not, and they have never been.
Also there are no any references to the functions (_stricmp, _wcsicmp, _mbsicmp, _stricmp_l, wcsicmp_l, _mbsicmp_l) in the C++ Standard ISO/IEC 14882:2017(E).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86885c18-4102-9692-2ae6-974705307695
* Version Independent ID: b23411af-053c-c471-9f0b-e119f0e96f09
* Content: [stricmp, wcsicmp](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stricmp-wcsicmp?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/stricmp-wcsicmp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/stricmp-wcsicmp.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mna41 

You're right, those are not POSIX functions, though you wouldn't know it from the C4996 deprecation message you get if you use them. And the statement about conformance is far from clear. It means those functions have *names* that conform to the Standards' rules for implementation-specific global names. (The rules are currently in C++17 section 5.10, and C18 section 7.1.3.) It's not meant to imply that the functions themselves are part of any standard. In fact, the leading underscore is supposed to be a signal that they are specifically *not* in the Standard C library.

**Comment by mna41** [comment]
Additionally, there are many other pages in the C Run-time library (CRT) reference claiming the functions they describe are POSIX functions, while they are not. Those pages include:

cgets
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cgets?view=vs-2019

chsize
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-chsize?view=vs-2019

cprintf
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cprintf?view=vs-2019

cputs
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cputs?view=vs-2019

cscanf
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cscanf?view=vs-2019

cwait
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-cwait?view=vs-2019

filelength
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/filelength?view=vs-2019

getche
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getche?view=vs-2019

getw
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-getw?view=vs-2019

kbhit
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-kbhit?view=vs-2019

memicmp
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/memicmp?view=vs-2019

putch
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putch?view=vs-2019

putw
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-putw?view=vs-2019

setmode
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-setmode?view=vs-2019

sopen
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sopen?view=vs-2019

strcmpi
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcmpi?view=vs-2019

strlwr, wcslwr
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strlwr-wcslwr?view=vs-2019

strnicmp, wcsnicmp
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strnicmp-wcsnicmp?view=vs-2019

strnset, wcsnset
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strnset-wcsnset?view=vs-2019

strrev, wcsrev
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strrev-wcsrev?view=vs-2019

strupr, wcsupr
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strupr-wcsupr?view=vs-2019

There may be others too.

**Comment by corob-msft** [comment]
I've updated the boilerplate text for the deprecated CRT functions, with a more accurate explanation of what's deprecated and why (and which are POSIX and which aren't). Thanks for commenting.
