### ISSUE TITLE
Int vs long

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#1756]
Hi team,
I moved this from here: https://github.com/MicrosoftDocs/cpp-docs.cs-cz/issues/6

@KevinTwist commented 2 days ago — with docs.microsoft.com
Hi,
I was reading https://docs.microsoft.com/cs-cz/cpp/cpp/integer-limits?view=vs-2019 and int as well as long appear to have same min and max values.
Is that an error or am I just not getting something?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262486b8-5d80-2c0b-f2eb-40c86aaf6a61
* Version Independent ID: 26b45954-2bcc-263f-7522-0c72941141bb
* Content: [Integer Limits](https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=vs-2019)
* Content Source: [docs/cpp/integer-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@KevinTwist on Windows, unlike UNIX, int and long are synonyms. Use long long for a 64-bit int. This confuses everyone. I have updated the topic to clarify. Thanks for the feedback!
