### ISSUE TITLE
mkgmtime remarks confusion

### ISSUE THREAD

**Issue by ts2do** [MicrosoftDocs/cpp-docs#1762]
The paragraphs about tm_isdst appear to be lifted directly from mktime. I believe everything between 'When specifying a **tm** structure time' and 'the return value from **mktime** is unpredictable.' should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddd4a4d5-21ca-b885-5c3d-990e4e1b13fe
* Version Independent ID: 7bf9dd4e-a4f8-160e-9c92-740ff05ffaee
* Content: [_mkgmtime, _mkgmtime32, _mkgmtime64](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ts2do 
You're right, the `tm_isdst` field is irrelevant here. An update is in the queue and should be published tomorrow sometime.
