### ISSUE TITLE
More explanation need 

### ISSUE THREAD

**Issue by NerkarVijay** [MicrosoftDocs/cpp-docs#1764]
Hi, 
  In the following example, there is no any relation between class A and class D.
  Then why    A* pa2 = dynamic_cast<A*>(pb); is unambiguous?

// dynamic_cast_4.cpp
// compile with: /c /GR
class A {virtual void f();};
class B {virtual void f();};
class D : public B {virtual void f();};

void f() {
   D* pd = new D;
   B* pb = dynamic_cast<B*>(pd);   // first cast to B
   A* pa2 = dynamic_cast<A*>(pb);   // ok: unambiguous
}

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d85be2-8651-4283-1781-2fb38dcf6024
* Version Independent ID: 9108c324-b273-959b-12b3-b0995c44d59a
* Content: [dynamic_cast Operator](https://docs.microsoft.com/en-us/cpp/cpp/dynamic-cast-operator?view=vs-2019&source=docs#feedback)
* Content Source: [docs/cpp/dynamic-cast-operator.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/dynamic-cast-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@NerkarVijay 
You are correct, this example was not showing what it claimed. It may have been corrupted when we moved to markdown. I've updated the code, and it should get published later today. Thanks for pointing the issue out.
