### ISSUE TITLE
In code that's compiled by using /clr, this header is blocked.

### ISSUE THREAD

**Issue by 4elovek37** [MicrosoftDocs/cpp-docs#1768]
Actually, it is blocked only for /clr:pure since at least VS2017 (there is an ifdef for _M_CEE_PURE).
Please, fix this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af384261-ac31-1ca0-7165-2526f29622f5
* Version Independent ID: 405d8787-c438-caae-f54f-2ae3224f18c5
* Content: [&lt;atomic&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/atomic?view=vs-2019#feedback)
* Content Source: [docs/standard-library/atomic.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/atomic.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@4elovek37 
You're correct. This fix is in the publishing pipeline and ought to appear by tomorrow sometime.
