### ISSUE TITLE
Tried walkthrough but failed to run application

### ISSUE THREAD

**Issue by davef16** [MicrosoftDocs/cpp-docs#1771]
I walked through every detail as presented and both client and dll compiled successfully with one minor exception; I needed to uncomment the pch.h line of the MathClient to #include "pch.h" even though it said to  //Uncomment for Visual Studio 2017 and earlier .  In the end of the walkthrough the files compiled but failed when I tried to run the application.  The error stated that the mathlibrary.dll is not a valid win32 application.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by davef16** [comment]
Forgot to mention that I am running most current version of Visual Studio 2019 Version 16.4.0

**Comment by davef16** [comment]
As expected, the error was mine.  I re-created the client from scratch and everything worked fine.  At some point in the process I had the client as a dll and not an executable and naturally, windows cannot execute a dll as an application.  This thread can be closed.  The walkthrough worked fine.

**Comment by corob-msft** [comment]
@davef16 Glad you figured the issue out.
