### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/cpp-docs#1774]
Despite of https://github.com/MicrosoftDocs/cpp-docs/issues/576 
the discussed section in the article does not appear to be updated yet. It appears that the issue might have been closed by mistake before any changes were made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa0c454-4197-8ee4-e54b-772772da7b6a
* Version Independent ID: f2e3fc35-8517-186a-9c6e-18b14de7ff1e
* Content: [Events (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/events-c-cx?view=vs-2019)
* Content Source: [docs/cppcx/events-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/events-c-cx.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
My colleague didn't think further changes were needed, but I added a couple of sentences that should appear later today.
