### ISSUE TITLE
which header?

### ISSUE THREAD

**Issue by sztomi** [MicrosoftDocs/cpp-docs#1783]
I came to this page to figure out which header these types (like DWORD) are defined in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c1bff4-be17-2bcc-8017-d4f2d044088c
* Version Independent ID: 2acc8cc4-9a40-ef0a-fd44-4e76d50d4d93
* Content: [DWORD](https://docs.microsoft.com/en-us/cpp/assembler/masm/dword?view=vs-2019#feedback)
* Content Source: [docs/assembler/masm/dword.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/dword.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sztomi 

DWORD is a native type in the assembler. If you're looking for a header file, I'll assume you're actually trying to code in C or C++ for Windows, not MASM. In that case, DWORD is a typedef in \<minwindef.h>, which is included by \<windows.h>.

I'm closing this issue on the assumption that you're not actually looking for info on the MASM keyword DWORD. Let me know if my assumption is incorrect.
