### ISSUE TITLE
Why claim that returning numberOfElements by strnlen indicates error?

### ISSUE THREAD

**Issue by rafaello7** [MicrosoftDocs/cpp-docs#1785]
Suppose we want to know whether some string is at least e.g. 10 characters long. The most obvious solution is to use strlen and then compare the length with 10, but what if the input string is e.g. 10 kB long or even longer? Such way of checking would be very inefficient. Use of strnlen is much better: give 10 as numberOfElements and if the return value is 10, we know that string is at least 10 characters long.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfddf388-8e35-aa6e-f2dd-749a53f79ec5
* Version Independent ID: c97e89ab-e1db-0263-dbc0-3d8231769522
* Content: [strnlen, strnlen_s, wcsnlen, wcsnlen_s, _mbsnlen, _mbsnlen_l, _mbstrnlen, _mbstrnlen_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strnlen-strnlen-s?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CORECRT_WSTRING%2Fwcsnlen)%3Bk(wcsnlen)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strnlen-strnlen-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strnlen-strnlen-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rafaello7 
You've identified another valid use-case for `strnlen`, but I don't think that warrants a change in the documentation for the return value, which states its assumptions up front. If you use it in a different way, then you presumably know that getting the buffer length you supplied back is not an error.

**Comment by rafaello7** [comment]
Does it mean that use of strnlen is discouraged for purposes of such kind, when passing a string longer than numberOfElements not an error, or even can be expected to happen most often?

**Comment by corob-msft** [comment]
I see no reason this would discourage other valid ways to use `strnlen`. It just returns the *numberOfElements* parameter value when it doesn't find a null in the string parameter before then. If you're looking for a valid, null-terminated string that fits in a buffer that size, then the input string has failed the test. If you are looking for something else, then how to interpret the result is up to you.

**Comment by corob-msft** [comment]
Perhaps the distinction between an error condition and an error is too subtle.

**Comment by rafaello7** [comment]
OK, thanks :)
