### ISSUE TITLE
Missing SSE2 explicit value for the default

### ISSUE THREAD

**Issue by mikekaganski** [MicrosoftDocs/cpp-docs#1787]
For x86 ( https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86 ), there is a value for the default case: /arch:SSE2. But there's no such value here for x64, which requires to have this switch handled explicitly differently for x86 and x64 builds, even when they both are SSE2 (and it needs to be set for other reasons, instead of omitting: like further analyzing the command line to detect arch). Such a value wouldn't hurt, so reasons for its omission are not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732983a0-a628-77d4-a224-0db096ade499
* Version Independent ID: e7aae128-bb82-c6b5-3389-2f4470d66d11
* Content: [/arch (x64)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2019&source=docs)
* Content Source: [docs/build/reference/arch-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/arch-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mikekaganski 

Good question. I don't know why there isn't an explicit /arch:SSE2 option available in the x64 compiler. That's a question you'll have to pose to the development team. The best way to do that is by going to the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site and asking there.

I'm closing this, as there isn't (yet) a change required in the documentation.
