### ISSUE TITLE
<cmath> does not contain M_PI anymore

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#179]
@BugsDigger commented on [Mon Feb 05 2018](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/2)

This part does not work (at least in VC2017):
-------------------------------------------------
#define _USE_MATH_DEFINES // for C++
#include <cmath>
-------------------------------------------------

The only option now is
-------------------------------------------------
#define _USE_MATH_DEFINES
#include <math.h>
-------------------------------------------------

**Comment by corob-msft** [comment]
In reference to MicrosoftDocs/cpp-docs.ru-ru#2 by @BugsDigger this issue appears to be not-repro.

Here's an example I tried in VS 2017 version 15.5.7:

```cpp
#define _USE_MATH_DEFINES
#include <cmath>
int main(){
    static_assert(M_PI > M_PI_2, "_USE_MATH_DEFINES does not define math constants in cmath!");
}
```

This compiles without errors. Is there a different issue that I'm not seeing?

**Comment by corob-msft** [comment]
Absent further comment, I'm closing this issue as not repro.
