### ISSUE TITLE
Suggestion to mention that include paths can be different for different build configurations (Release/Debug)

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/cpp-docs#1791]
Guys, somewhere in part "To add the DLL header to your include path" of this really great guide we should mention to:

Double check the configuration that you update in `Property Pages` so that you do not get caught in updating `Release` and building as `Debug` (with no such file errors). Or choose "All configurations" as in the image. I believe this can save someone time when trying to figure out why the include do not work..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019#create-a-client-app-that-uses-the-dll)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ortymd 

You aren't the only one. Because applying changes only to the current configuration has been such a common problem, your suggestion is already explicitly called out as step 2 in the procedure. I don't want to beat people over the head with it, so I don't think it needs to be called out in other steps as well.
