### ISSUE TITLE
Failed attempt to run code in command window

### ISSUE THREAD

**Issue by JohnPhilpott** [MicrosoftDocs/cpp-docs#1794]
I ran through "Build and run your code in Visual Studio" with apparent success. But when I tried the next step, "Run your code in a command window" there was no .exe file to be found. The debug folder contains:
a folder: HelloWorld.tlog
and the files:
HelloWorld.Build.CppClean - a text document
Hello World - a text document
HelloWorld - a 3D Object
HelloWorld.vcxproj.FileListAbnsulute
vc142.idb
vc142.pdb
and nothing else! So - what to do next?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d597b582-59ec-2014-699b-6aac8db69cf6
* Version Independent ID: 81941537-4446-9c5a-6af3-25318396420d
* Content: [Build and run a C++ console app project](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=vs-2019#feedback)
* Content Source: [docs/build/vscpp-step-2-build.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-2-build.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by paroche** [comment]
Same here, more or less, but I just have:
```
HelloWorld.tlog (directory)
HelloWorld.log
HelloWorld.obj
vc142.idb
vc142.pdb
```

no `HelloWorld.exe` file.

**Comment by corob-msft** [comment]
A fix should appear later today that clarifies that it's the Debug directory in the HelloWorld solution folder, not the Debug directory in the HelloWorld project folder, that has the executable. Yes, it's confusing.
