### ISSUE TITLE
The diagrams in code blocks seems mess up

### ISSUE THREAD

**Issue by ghsgz** [MicrosoftDocs/cpp-docs#1798]
The position of those characters that act as connecting lines should be shifted to the right, e.g. the content in the first code block  of this page:
```
RESOURCE.H     AFXRES.H
\       /
\     /
    MYAPP.RC
|
|
    RES\MYAPP.RC2
    AFXRES.RC
    AFXPRINT.RC
```

I think it should be something like this:
```
RESOURCE.H     AFXRES.H
                 \       /
                  \     /
             MYAPP.RC
                     |
                     |
    RES\MYAPP.RC2
    AFXRES.RC
    AFXPRINT.RC
```

The doc in MSDN is really great, maybe we can make it better!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d9cd09b-cf63-7a61-39f5-93b31dfc9ff5
* Version Independent ID: 36cec252-9602-e5d9-2375-17b5ec9d79e2
* Content: [TN035: Using Multiple Resource Files and Header Files with Visual C++](https://docs.microsoft.com/en-us/cpp/mfc/tn035-using-multiple-resource-files-and-header-files-with-visual-cpp?view=vs-2019#feedback)
* Content Source: [docs/mfc/tn035-using-multiple-resource-files-and-header-files-with-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/tn035-using-multiple-resource-files-and-header-files-with-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by ghsgz** [comment]
It seems that the characters' position of the edit box is inconsistent with the rendered code block in MSDN doc site.

**Comment by corob-msft** [comment]
@ghsgz 
This content is really old, and is mostly supplied as-is. After several platform moves, it looks like some formatting was lost, so I fixed what I could. Updates should be visible later today.
