### ISSUE TITLE
Heading shouldn't have second anchor and articles shouldn't have second TOC

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/cpp-docs#18]
Many articles in this repo seem to have a structure like this (from [Storage classes](https://docs.microsoft.com/en-us/cpp/cpp/storage-classes-cpp)):

```md
…

-   [static](#static)  
  
-   [extern](#extern)  
  
-   [thread_local](#thread_local)  

## <a name="static"></a>  static  
…
  
##  <a name="extern"></a>  extern  
…
  
##  <a name="thread_local"></a>  thread_local (C++11)  
…
  
##  <a name="register"></a>  register  
…

## Example: automatic vs. static initialization  
…
  
## See Also  
…
```

Notice that the article has an explicit Table Of Contents, which is not correct (it does not include "register") and duplicates the auto-generated TOC, which is shown on the right of the article. Also notice that the headings have `<a name>` tag, which results in the heading having two anchor targets: one coming from the `<a name>`, used in the manual TOC (e.g. `static`) and second autogenerated, used in the autogenerated TOC (e.g. `a-namestatica--static`).

I this this manually written TOC and the manually added `<a name>` tags serve no purpose and only make the docs worse, so they should be removed.

**Comment by mikeblome** [comment]
Thanks for the feedback. Very observant! Yes, currently the "name" anchors are redundant with the auto-generated TOC, which creates "id" attributes. Oops :-\ We are aware of the issue and it is in our backlog to resolve. The "name" attribute does serve a purpose, which is to provide a target for the member table links at the top of the topic, and for F1 help lookups.  One proposed solution is to have the auto-generated TOC use the existing name attribute for the H2 heading if one exists.

**Comment by corob-msft** [comment]
I'm closing this issue not because we're not working on it, but because it's difficult to say when we're done. For information architecture reasons, these sections will stay in library class aggregate topics. In other topics, individual issues may be opened, which we will address. Thanks for your suggestions.
