### ISSUE TITLE
This page contains misleading information - that causes developers to think they are subverting DLL preloading attacks. But in reality it isn't.

### ISSUE THREAD

**Issue by VimalShekar** [MicrosoftDocs/cpp-docs#1802]
This article is misleading developers. This doc needs to be modified to include an additional section that clearly describes the load order when multiple LOAD_LIBRARY_SEARCH flags are ORed. See the LoadLibraryEx document :
https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw

"If more than one LOAD_LIBRARY_SEARCH flag is specified, the directories are searched in the following order:

The directory that contains the DLL (LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR). This directory is searched only for dependencies of the DLL to be loaded.
The application directory (LOAD_LIBRARY_SEARCH_APPLICATION_DIR).
Paths explicitly added to the application search path with the AddDllDirectory function (LOAD_LIBRARY_SEARCH_USER_DIRS) or the SetDllDirectory function. If more than one path has been added, the order in which the paths are searched is unspecified.
The System32 directory (LOAD_LIBRARY_SEARCH_SYSTEM32). 
"

We had developers reach out claiming they were setting /DEPENDENTLOADFLAG:0xA00. They thought that should protect them from DLL preloading from their application directory, but it didn't and their app was misused in an attack... 

The current version of the page says:
"If you specify the link option /DEPENDENTLOADFLAG:0xA00 (the value of the combined flags LOAD_LIBRARY_SEARCH_APPLICATION_DIR | LOAD_LIBRARY_SEARCH_SYSTEM32), then even if safe DLL search mode is disabled on the user's computer, the DLL search path is limited to protected directories that are more difficult for an attacker to change. "

This misleads developers into believing that it protects them from DLL preloading attacks. 

But in reality - Application directory gets searched before the system32 directory. If the attacker controls the application directory - then the application is still susceptible to preloading attacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d177f004-5584-1008-dc8f-2c4507d7b88e
* Version Independent ID: af547dc7-3e7a-a15c-c70d-ba0b707c7d0e
* Content: [/DEPENDENTLOADFLAG (Set default dependent load flags)](https://docs.microsoft.com/en-us/cpp/build/reference/dependentloadflag?view=vs-2019#feedback)
* Content Source: [docs/build/reference/dependentloadflag.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dependentloadflag.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@VimalShekar 

I've added more qualifications to the language on DLL search order, and more explicit discussion of the search order used by the example (i.e. app directory first, then system32), as well as pointers to the search order documentation. I'm resistant to making one more place that lists the search order details, since redundancy leads to sync issues. Updates should appear later today, or possibly Thursday, depending on when the production editing team gets to it.
