### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Mike-j-t** [MicrosoftDocs/cpp-docs#1805]
If you enter a non numeric e.g. r then you get into an infinite loop, due to cin retaining the input.

Although perhaps confusing/complex adding something like the following appears to handle the situation :- 

```
        cin.clear();
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        cin >> x >> oper >> y; //<<<<<<<<< Existing Code
```

**Comment by TylerMSFT** [comment]
This issue doesn't have necessary context, such as what document it is referring to. Feel free to reopen if this is still an issue and you are able to identify what documentation needs to be updated.
