### ISSUE TITLE
Would you upload samples both vb.net(or csharp) and c++amp dll example in 64bit?

### ISSUE THREAD

**Issue by SKSON** [MicrosoftDocs/cpp-docs#1806]
I tested the "How to use C++ AMP from C#" and found the samples settings are 32bit. default.
So, I tried to change both helloWorldCsharp, and helloworldlib.dll 32bit -&gt; 64bit but I couldn't.
Using Vb.net module. c++ amp works, but also in 32bit default. not in 64bit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58e07cc-2b1b-668a-5d9d-73afd80ce1c6
* Version Independent ID: 2b3cbb85-9f6c-2ef2-285a-5af0dc64e31d
* Content: [C++ AMP Overview](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-overview?view=vs-2019#feedback)
* Content Source: [docs/parallel/amp/cpp-amp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/cpp-amp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by TylerMSFT** [comment]
AMP is deprecated for C++, which is the area we work in. We won't have bandwidth to work on code samples for other languages for it, unfortunately.
