### ISSUE TITLE
Unclosed quote in Lambda expressions section

### ISSUE THREAD

**Issue by agashlin** [MicrosoftDocs/cpp-docs#1809]
The "can be read as" gloss in the Lambda expressions section is missing a closing `"`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [Welcome back to C++ (Modern C++)](https://docs.microsoft.com/en-us/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@agashlin Thanks, an update should be visible now.
