### ISSUE TITLE
Unclear if VS2019 can compile for WinXP

### ISSUE THREAD

**Issue by pegleGrot** [MicrosoftDocs/cpp-docs#1810]
The docs read:

> Visual Studio 2019 and later does not include support for creating code for Windows XP by using the v142 toolset. Support for Windows XP development by using the v141 toolset that shipped in Visual Studio 2017 is available as an optional component in the Visual Studio Installer.

If I understand correctly (**didn't check**), and the above means: (1) the v141 toolset _is_ available in the VS2019 installer and can be used, (2) v141 is exactly the same as what originally shipped in VS2017, so no new C++/other features.

If that's correct, I suggest this wording:

> Visual Studio 2019 only supports creating code for Windows XP using the legacy v141 toolset, which is an optional component in the Visual Studio Installer. The toolset is unchanged from what shipped in Visual Studio 2017. It does not support new features introduced in v142 and later toolsets, such as (...).

In the next paragraph, it says:
> To get the platform toolset and components to target Windows XP and Windows Server 2003 in **Visual Studio 2017** ...

If supported, it should say VS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651c91cd-a0c3-f631-7bab-707ea4f1827b
* Version Independent ID: bfd995d2-6875-2301-ef78-4446ed268845
* Content: [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2019)
* Content Source: [docs/build/configuring-programs-for-windows-xp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configuring-programs-for-windows-xp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Dennis-Petrov** [comment]
Faced with the same issue.
There's no any v14*_xp toolsets in VS 2019 installer:
https://stackoverflow.com/a/60691678/580053

**Comment by pegleGrot** [comment]
@Dennis-Petrov 
Maybe a "bug" to report to the team responsible for the installer?

As usual, best keep offline installers. Though Microsoft makes that hard and tedious to do.

**Comment by mirh** [comment]
It was there on a clean install at least this september I installed VS2019.

**Comment by corob-msft** [comment]
The install option is still there in VS 2019, but it moved. Updated instructions for installing the v141_xp toolset in VS 2019 and VS 2017 are now accessed by the documentation version selector.

**Comment by Dennis-Petrov** [comment]
@corob-msft ,

The docs:
![image](https://user-images.githubusercontent.com/5005677/76824514-6c1c5c80-6828-11ea-9d67-0572587bcd2c.png)

Istaller:
![image](https://user-images.githubusercontent.com/5005677/76824547-7f2f2c80-6828-11ea-82b0-877876dbd3a7.png)

Maybe, I'm missing it, but where is "C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]" here?

**Comment by Dennis-Petrov** [comment]
OMG.
There are "Individual Components" **tab** and "Individual Components" **check list**. 
WinXP support must be checked in tab, and then it appears in check list.

MS, it's a kind of  mockery.

**Comment by alysdexia** [comment]
no any -> no
TNG

Isn't "Individual components" also redundant?
