### ISSUE TITLE
Are there plans for C# support

### ISSUE THREAD

**Issue by DamianSuess** [MicrosoftDocs/cpp-docs#1812]
Are there any plans to support C#? I gave it a quick shot hoping it would work, but there is not option to deploy/debug.

Overall, I'd like to perform remote debugging with our prototypes on the Raspberry Pi. There are a couple of 3rd-party solutions with limited support, however, I would prefer a baked-in Visual Studio solution. Previously, I'd use MonoDevelop (Xamarin Studio), but we all know VS is a must stronger IDE.

Also, read over [remote debugging c#](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2019), however, this doesn't cover Linux (_RaspberryPi_).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Connect to your target Linux system in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2019)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@DamianSuess 

I'm pretty sure that's doable, but there might not be specific documentation for it yet. Scott Hanselmann wrote about [remote debugging a C# .NET Core app on the WSL from Visual Studio](https://www.hanselman.com/blog/RemoteDebuggingANETCoreLinuxAppInWSL2FromVisualStudioOnWindows.aspx). It should be possible to remote into a Raspberry Pi using a very similar procedure. I've seen another blogger or two report on such stuff.

It doesn't seem like there's a change to be made to the C++ documentation here, so I'm closing this issue.

**Comment by corob-msft** [comment]
@mairaw Do you know of any docs about remote debugging .NET Core on Linux? I didn't see anything when looking around under the [.NET Core guide](https://docs.microsoft.com/en-us/dotnet/core/).

**Comment by corob-msft** [comment]
I should probably ask @Mikejo5000 about this as well.

**Comment by andysterland** [comment]
It’s sure possible. If the Linux box supports SSH you can just use that as the transport type in the attach to process dialog and off you go. Blog with details on that at: https://devblogs.microsoft.com/devops/debugging-net-core-on-unix-over-ssh/. If that doesn’t work there is more detailed instructions over on the MIEngine github repo:
https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio

**Comment by DamianSuess** [comment]
@corob-msft and @andysterland, thank you for the feedback. I'll give Scotts thing a try.

I wish I had a link on-hand to the 3rd-party VS extension as a reference. It was able to deploy via SSH but it was unable to debug (_using Mono_). It just ended up locking up.  I'll give @andysterland  thing a try too. The manual process may work for initial prototyping for now.  Thank you all!

**Comment by DamianSuess** [comment]
@corob-msft, in regards to closing the issue ticket, are there plans on updating or creating formal documentation for this functionality?

**Comment by mairaw** [comment]
@corob-msft i missed the ping earlier. I don’t believe we do. Also, would this be a .NET Core article or VS? /cc @gewarren

**Comment by corob-msft** [comment]
@DamianSuess This particular issue is closed, because it's unrelated to the C++ documentation. However, we recognize that using Visual Studio for remote debugging of C# on Linux (including on Raspberry Pi) is worth documenting. The debate is about whether this belongs in the [.NET](https://github.com/dotnet/docs) or the [Visual Studio](https://github.com/MicrosoftDocs/visualstudio-docs) docs, which determines where to create a new issue. Most debugger docs live in the Visual Studio repo, so that's the direction I'd lean. But, maybe .NET debugging belongs with other .NET topics, if that's where developers expect it.

**Comment by DamianSuess** [comment]
@corob-msft, Colin, thank you very much for the professional followup and closing remarks. Really do appreciate your time and finding a suitable home on this matter.
