### ISSUE TITLE
 CRenderTarget::GetTransform has wrong documentation

### ISSUE THREAD

**Issue by code-creator** [MicrosoftDocs/cpp-docs#1813]
Doc seems copied from SetTransform:

 CRenderTarget::GetTransform

Applies the specified transform to the render target, replacing the existing transformation. All subsequent drawing operations occur in the transformed space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3024b0f-49a5-b06e-1fa9-5cd87b59fa01
* Version Independent ID: ee0e2b3b-6edd-ff0e-ff0e-990fdb2f8524
* Content: [CRenderTarget Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/crendertarget-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/crendertarget-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/crendertarget-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
A fix should appear later today.
