### ISSUE TITLE
Assumption that na update is required

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/cpp-docs#1814]
Having followed the tutorial I see that vs 2019 actually creates 2 projects (for default configuration). THese 2 projects are: atl1 and atl1ps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b6f074-8d33-8f93-6555-f7d559936fee
* Version Independent ID: 1edf1754-026c-dade-898b-76a42d6363c7
* Content: [Creating the Project (ATL Tutorial, Part 1)](https://docs.microsoft.com/en-us/cpp/atl/creating-the-project-atl-tutorial-part-1?view=vs-2019)
* Content Source: [docs/atl/creating-the-project-atl-tutorial-part-1.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/creating-the-project-atl-tutorial-part-1.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by TylerMSFT** [comment]
Due to other priorities, I won't be updating this tutorial.
