### ISSUE TITLE
Please consider addling links about ActiveX in popular browsers

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/cpp-docs#1815]
I see that ActiveX is mostly a windows technoology that is not avalibale on other platforms. I believe it is worth mentioning this is the tutorial to save people time. 
Here is a link for firefox for example: 
https://support.mozilla.org/en-US/kb/ActiveX

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d8323-d824-40eb-4954-2620d86a44b6
* Version Independent ID: a090fbda-31ee-a2d1-6f9c-9e495b4b4e08
* Content: [Adding a Control (ATL Tutorial, Part 2)](https://docs.microsoft.com/en-us/cpp/atl/adding-a-control-atl-tutorial-part-2?view=vs-2019&viewFallbackFrom=vs-2020)
* Content Source: [docs/atl/adding-a-control-atl-tutorial-part-2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/adding-a-control-atl-tutorial-part-2.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@ortymd 

As far as I know, there are no current browsers that enable ActiveX controls. You can use them in the still available, but deprecated, Internet Explorer 11 browser if you [explicitly enable them](https://support.microsoft.com/en-us/help/17469/windows-internet-explorer-use-activex-controls). I've heard there will be a way to enable an IE compatibility mode in Edge Chromium that may support ActiveX controls, but it sounds like a lot of bother.

This tutorial doesn't seem very useful anymore, does it. ATL is a fine way to create COM components, but ActiveX controls are a bit out of style. Given this reality, these documents only get touched to fix serious bugs. This suggestion doesn't meet that bar, so I'm closing the issue. Sorry.
