### ISSUE TITLE
Making filenames bold

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/cpp-docs#1816]
I think it would be great if the filenames in tutorial were updated to bold.
Such an update would allow much better "tutorial navigation". :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29408b51-59df-3afb-b521-7fcdb259803f
* Version Independent ID: e32689f9-74c1-3055-79fd-c32728dbf665
* Content: [Adding a Property to the Control (ATL Tutorial, Part 3)](https://docs.microsoft.com/en-us/cpp/atl/adding-a-property-to-the-control-atl-tutorial-part-3?view=vs-2019)
* Content Source: [docs/atl/adding-a-property-to-the-control-atl-tutorial-part-3.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/adding-a-property-to-the-control-atl-tutorial-part-3.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@ortymd 
Our current style guide uses *italics* to distinguish file names. In old content such as this, you might see various other styles used, but we don't bother updating styles alone unless there's another issue to address. However, if you feel ambitious, you're welcome to submit a pull request with italicized file names. We're always happy to see contributions from our users.
