### ISSUE TITLE
Path difference

### ISSUE THREAD

**Issue by gertkommer** [MicrosoftDocs/cpp-docs#1817]
`sudo ./cmake-3.16.3311152-MSVC_2-Linux-x64.sh --skip-license --prefix=/usr/local` points to /usr/local where vs 2019 will look by default for cmake, but on "connect to the remote machine" it will look in /usr/bin for cmake. Is this an documentation error?

For your information, I just downloaded the .sh file and not the src tar.gz. is this required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4535255d-395b-6b11-daf3-b03e0c3ad87d
* Version Independent ID: 1aad5206-ea1e-630c-800a-bb79bbd942b4
* Content: [Create C++ cross-platform projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2019#feedback)
* Content Source: [docs/build/get-started-linux-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/get-started-linux-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @mikeblome
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gertkommer 
The path changed after the documentation was originally written. I've just made an update with the current paths, which should appear sometime tomorrow.
