### ISSUE TITLE
Will also happen with private const variable

### ISSUE THREAD

**Issue by SilvijnRuben** [MicrosoftDocs/cpp-docs#1819]
private:
Const &lt;T&gt; m_name;

this will also trigger this warning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68e21e25-cb3c-3ea2-c4e5-74eeb76246b1
* Version Independent ID: 5342318d-4239-8fe8-cad2-3fa7dd7c314b
* Content: [Compiler Warning (level 4) C4626](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4626?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4626)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4626.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4626.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
