### ISSUE TITLE
CMake install prefix is wrong

### ISSUE THREAD

**Issue by mboyar** [MicrosoftDocs/cpp-docs#1824]
In the Prerequisites section, CMake installation directory prefix should be '/usr' instead of '/usr/local' for VS2019. If VS cannot find cmake in WSL, it offers to install to remote itself. Except for this, the document is so useful, thx a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4535255d-395b-6b11-daf3-b03e0c3ad87d
* Version Independent ID: 1aad5206-ea1e-630c-800a-bb79bbd942b4
* Content: [Create C++ cross-platform projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2019#prerequisites)
* Content Source: [docs/build/get-started-linux-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/get-started-linux-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @mikeblome
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mboyar 
Thanks for the report. A fix for the issue should be published later today.
