### ISSUE TITLE
_mbclen may returns 3, not only 1 and 2

### ISSUE THREAD

**Issue by heroboy** [MicrosoftDocs/cpp-docs#1826]
```c++
int main(int argc, char ** argv)
{
	setlocale(LC_CTYPE, ".65001");//utf8
	const char * s = u8"啊啊啊啊";//啊 is 3 bytes in utf8
	int k = mblen(s,10);
	return 0;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3bd74c-fb18-4faa-5458-20db0072f323
* Version Independent ID: fd3c0344-baae-072d-719f-40679b40c6a5
* Content: [_mbclen, mblen, _mblen_l, _mbclen_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mbclen-mblen-mblen-l?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/mbclen-mblen-mblen-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/mbclen-mblen-mblen-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by heroboy** [comment]
Why close this? As the document , it says mbclen only return 1,2,-1, but the example shows it will return 3.

**Comment by corob-msft** [comment]
@heroboy  Sorry, I made a typo in another update, and as a result this issue got closed by mistake.

**Comment by corob-msft** [comment]
@heroboy Updated content should appear later today.
