### ISSUE TITLE
Thread-Safety

### ISSUE THREAD

**Issue by Cygon** [MicrosoftDocs/cpp-docs#1827]
This page should state whether Microsoft's implementation or strerror() uses thread-local storage (or returns pointers to fixed string buffers) or whether it should be avoided in multi-threaded scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26a123e8-15f1-7c93-b9f8-a040e1ea10ee
* Version Independent ID: 08c24b75-603f-b40e-08c8-8bc04648ecb1
* Content: [strerror, _strerror, _wcserror, __wcserror](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-strerror-wcserror-wcserror?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strerror-strerror-wcserror-wcserror.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strerror-strerror-wcserror-wcserror.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Cygon 
The buffer is allocated in thread-local storage on an as-needed basis (not more than once) and pointed at by an entry in the runtime's internal per-thread data structure. There are separate buffers for narrow and wide strings, on the off chance you use both.

**Comment by corob-msft** [comment]
Updates should appear later today.
