### ISSUE TITLE
CFileTimeSpan documentation is wrong

### ISSUE THREAD

**Issue by deniskovalchuk** [MicrosoftDocs/cpp-docs#1828]
The documentation says that `CFileTimeSpan` represents a period of time in milliseconds, but actually in the number of 100-nanosecond intervals (similar to [`CFileTime`](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cfiletime-class.md)).

For example:
```
CFileTime time1(1 * CFileTime::Millisecond); // 1 millisecond
CFileTime time2(2 * CFileTime::Millisecond); // 2 milliseconds
CFileTimeSpan span = time2 - time1;

span.GetTimeSpan(); // returns 10000, not 1
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fba63d1-f0cf-ccd1-f737-2bef056b2e88
* Version Independent ID: d9597683-f31a-e9a9-877b-5fbc716a6212
* Content: [CFileTimeSpan Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cfiletimespan-class?view=vs-2019#operator_add)
* Content Source: [docs/atl-mfc-shared/reference/cfiletimespan-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cfiletimespan-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@deniskovalchuk 
Thanks for pointing this issue out. I've updated the document, and it should be published some time tomorrow.

**Comment by deniskovalchuk** [comment]
@corob-msft, If I'm not mistaken, now the documentation is not consistent. Milliseconds are still mentioned in `CFileTimeSpan::CFileTimeSpan` and `CFileTimeSpan::GetTimeSpan` functions. Could you check it?

**Comment by corob-msft** [comment]
@deniskovalchuk Yes, thanks, I missed those. Fixes should be published on Monday.
