### ISSUE TITLE
Examples would be helpful

### ISSUE THREAD

**Issue by jimmonte** [MicrosoftDocs/cpp-docs#1830]
Examples would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1757c6ba-3fba-3827-f76f-88b13e7729d4
* Version Independent ID: f5e6efed-f9ae-a310-645c-961ee2d5bb80
* Content: [Executing a Program in Preprocessing](https://docs.microsoft.com/en-us/cpp/build/reference/executing-a-program-in-preprocessing?view=vs-2019#feedback)
* Content Source: [docs/build/reference/executing-a-program-in-preprocessing.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/executing-a-program-in-preprocessing.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
