### ISSUE TITLE
Document the -Brepro flag

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#1837]
The -Brepro flag is used a lot in environments where one needs reproducible builds. It would be great if it was documented.

**Comment by corob-msft** [comment]
@tiagomacarios 
Generally speaking, the docs team doesn't decide which flags to document. This is an ask for the product team. If you want to enlist public support, a suggestion on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) is the way to go.

**Comment by tiagomacarios** [comment]
https://developercommunity.visualstudio.com/idea/731265/document-brepro-flag.html
