### ISSUE TITLE
Poor machine translation

### ISSUE THREAD

**Issue by fwidmann** [MicrosoftDocs/cpp-docs#1843]
The machine translation of the reference documentation of library functions provides funny but useless descriptions. E.g.: the description of the function strtol() in German (https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/strtol-wcstol-strtol-l-wcstol-l):

> " **dartol** " gibt den in der Zeichenfolge " _darsource_" dargestellten Wert zurück, es sei denn, die Darstellung würde einen Überlauf verursachen. in diesem Fall wird **LONG_MAX** oder **LONG_MIN**zurückgegeben. " **Strauch** " gibt "0" zurück, wenn keine Konvertierung ausgeführt werden kann. **wcstol** gibt Werte analog zu " **Strauch**" zurück. Bei beiden Funktionen wird **errno** auf **ERANGE** festgelegt, wenn ein Überlauf oder ein Unterlauf auftritt.

In the past there was a checkbox on these pages to switch off the automatic translation. Where has this checkbox gone?

Friedbert

**Comment by corob-msft** [comment]
@fwidmann 

I'm sorry about the poor experience. There's a defect in the website code for the language switch. The automatic translation checkbox was removed temporarily, while it gets fixed. 

@JasonCard for awareness and clarification, if needed. Is this an instance where setting no-loc strings would help?

**Comment by JasonCard** [comment]
@fwidmann We're sorry the poor experience with machine translation and inconvenience for the disabled feature. I believe you're referring to the "Read in English" toggle option which allowed you to switch to the English version and back without having to change the language settings. This feature is temporarily disabled as we are working to make improvements to it. In the meantime, you can use the language selection settings at the bottom left to change to English version:
![language_selection](https://user-images.githubusercontent.com/18313964/72377293-3b9f3180-36c4-11ea-8bea-58f6eacab7ee.png)

@corob-msft Yes, adding the no-loc metadata would help in this case as you did for [Command macros and options macros](https://docs.microsoft.com/de-de/cpp/build/reference/command-macros-and-options-macros?view=vs-2019).

**Comment by corob-msft** [comment]
Closing this issue that was addressed back in January.
