### ISSUE TITLE
Text Formating Improvement

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/cpp-docs#1848]
The items under the list element "An object of class path stores the pathname in native form, but supports easy conversion between this stored form and several external forms:" should be indented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c07ee4-ff79-f9ac-c7c9-758d212381a8
* Version Independent ID: 9e079442-f226-6fac-032e-aae30eb8c0d4
* Content: [&lt;filesystem&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem?view=vs-2019#feedback)
* Content Source: [docs/standard-library/filesystem.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/filesystem.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JustaSimpleUser 
Thanks for the report. These and other related formatting issues were addressed sometime last week and should be visible now.
