### ISSUE TITLE
Duplicate Enumerations

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/cpp-docs#1849]
There are two entries for copy_options under the Enumerations header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c07ee4-ff79-f9ac-c7c9-758d212381a8
* Version Independent ID: 9e079442-f226-6fac-032e-aae30eb8c0d4
* Content: [&lt;filesystem&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem?view=vs-2019#feedback)
* Content Source: [docs/standard-library/filesystem.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/filesystem.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JustaSimpleUser 
Thanks for the report. This was fixed sometime last week, but I forgot to update the issue.
