### ISSUE TITLE
Missing step for Visual Studio 2019

### ISSUE THREAD

**Issue by akabeera** [MicrosoftDocs/cpp-docs#1857]
If you following the directions for VS 2019, you will still get the following compile errors:

**unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source?**	

To build successfully, I had to go into project properties and set the following option.

Project Properties --> C/C++ --> Precompile Headers --> Precompile Header: "Not Using Precompile Headers"

This step was included in the VS2017 directions, I think this is required for the VS2019 documentation too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@akabeera 
Thanks for pointing the issue out. I addressed this in the recent update to this topic.
