### ISSUE TITLE
In the VS2019 directions, there is a missing step before #3. Add reference 

### ISSUE THREAD

**Issue by akabeera** [MicrosoftDocs/cpp-docs#1858]
With the current directions, when you get to the following step, you will not see anything in the Add Reference dialog:

3. The Add Reference dialog box lists the libraries that you can reference. The Projects tab lists the projects in the current solution and any libraries they reference. On the Projects tab, select the MathFuncsLib check box, and then choose the OK button.  

I think you first need to do the following:
1. In the **MyExecRefsLib** project go to File menu --> Add --> Existing Project
2. In the file dialog navigate to **/path/to/MathFuncsLib/MathFuncsLib.vcxproj**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@akabeera 
Thanks for writing in. When I gave the article an update recently, I didn't run into the issue you describe. As far as I can tell, the only way you'd see what you're describing is if you haven't followed the directions to create the client project in the same solution as the library project. That's a legitimate thing to do, and would necessitate the step you mention, but it shouldn't be required if you follow the steps listed here. I'm going to close this issue as outside the current scope of the document. Another article on using third-party libraries is planned - eventually - and should cover this requirement.
