### ISSUE TITLE
How to target Windows 10 (1507) and later using Windows 10 SDK

### ISSUE THREAD

**Issue by daveorourke** [MicrosoftDocs/cpp-docs#1862]
I'm updating our Windows desktop application (not UWP) and wish to target Windows 10 (1507) and later.  How do I determine which version of the Windows 10 SDK to use?

Previously, we were targeting Windows SDK 8.1 for compatibility with Windows 7 and later and the instructions [here](https://docs.microsoft.com/en-us/cpp/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application?view=vs-2019) clearly states
> Note that 8.1 in this context refers to the Windows SDK version, which is also backwardly compatible with Windows 8, Windows Server 2012, Windows 7, Windows Server 2008, and Windows Vista.

That's great.  But how do I target a specific version of Windows 10 (and later) ?  It seems that the older method of using the _WIN32_WINNT and related macros to select the target API is no longer supported.  Ideally, we would have some way to target, say Windows 10 (1507) and later, but this is not clear from the docs.

Can you please clarify how this should be done?  Thanks in advance!

**Comment by corob-msft** [comment]
@daveorourke 

If the question is just which version of the SDK to use, that's easy - use the latest one. It includes the bits you need for every version of Windows still in support. The only reason to pick up an older SDK is if it had tools or API support that's been dropped in later versions, which might apply to, say, the Windows 7.1A SDK, or the Windows Phone SDK. The docs describe which project properties to update when you switch SDK versions.

I'm not sure where you get the idea that the version macros are no longer supported. You can still use macros to target specific API levels. That works fine, and it's used all over the SDK headers. If you need to get finer-grained about Windows 10 versions, there are specific NTDDI_WIN10_* macros defined in *sdkddkver.h* you can use in conditional compilation. Either NTDDI_WINTHRESHOLD or NTDDI_WIN10 is the minimum for any version of Windows 10. Use NTDDI_WIN10_19H1 to only support the very latest bits.

I'm not seeing a specific doc issue to address here. What am I missing?

**Comment by corob-msft** [comment]
Just to make life easier, I updated [How to: Use the Windows 10 SDK in a Windows Desktop Application](https://docs.microsoft.com/en-us/cpp/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application?view=vs-2019) and [Update WINVER and _WIN32_WINNT](https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=vs-2019) with the latest info, and tried to make them less confusing. The updates should appear sometime tomorrow.

**Comment by daveorourke** [comment]
@corob-msft 

> If the question is just which version of the SDK to use, that's easy - use the latest one. It includes the bits you need for every version of Windows still in support. The only reason to pick up an older SDK is if it had tools or API support that's been dropped in later versions, which might apply to, say, the Windows 7.1A SDK, or the Windows Phone SDK. The docs describe which project properties to update when you switch SDK versions.

Got it.  This clears it up.  It was unclear (to me) from the docs whether the version of the Windows SDK was somehow tied to the version of Windows we were trying to target.

> I'm not sure where you get the idea that the version macros are no longer supported. You can still use macros to target specific API levels. That works fine, and it's used all over the SDK headers. If you need to get finer-grained about Windows 10 versions, there are specific NTDDI_WIN10_* macros defined in sdkddkver.h you can use in conditional compilation. Either NTDDI_WINTHRESHOLD or NTDDI_WIN10 is the minimum for any version of Windows 10. Use NTDDI_WIN10_19H1 to only support the very latest bits.

I had not found `NTDDI_WIN10_19H1` or any of the other `NTDDI_WIN10*` macros.  Previously, the last macros were `_WIN32_WINNT_WINTHRESHOLD` and `NTDDI_WINTHRESHOLD`, which made it look like this was the end of the road for the use of these macros to target a version of the API.  Your reply makes it clear that I was mistaken about this.

Clearly, things changed at the Windows 10 boundary.  We're just trying to make sense of what that means for how we target the Windows API for desktop applications.  Your updates are much appreciated, and do help to clear things up, at least for me.  Thank you.
