### ISSUE TITLE
The doc is wrong: older (not vcxproj) c++ projects upgrade is available in all VS versions

### ISSUE THREAD

**Issue by olgaark** [MicrosoftDocs/cpp-docs#1864]
You don't need to install Visual Studio 2010 to be able to upgrade .vcproj and .dsw/.dsp (vc6 format). All VS versions including VS2019 support the upgrade of old projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349f9d38-ee28-e99a-6527-241d9a4bf8f3
* Version Independent ID: d2b2131f-38a8-2bbf-3403-1064a2b75a7c
* Content: [Upgrade C++ projects from earlier versions of Visual Studio](https://docs.microsoft.com/en-us/cpp/porting/upgrading-projects-from-earlier-versions-of-visual-cpp?view=vs-2019#feedback)
* Content Source: [docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
A fixed version is scheduled for publication tomorrow.
