### ISSUE TITLE
CListBoxItem::ItemFromPoint bOutside

### ISSUE THREAD

**Issue by dbrookes96** [MicrosoftDocs/cpp-docs#1866]
It seems like bOutside is TRUE if the point is outside the area of the entire list box, not outside the area of the nearest list box item as suggested here.
LB_ITEMFROMPOINT indicates this also https://docs.microsoft.com/en-us/windows/win32/controls/lb-itemfrompoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30ff1bd4-58a7-7e02-cc44-63006b3e98bd
* Version Independent ID: 9f415ea7-35cb-bc52-1549-c0d2c48145af
* Content: [CListBox Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/clistbox-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/clistbox-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/clistbox-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dbrookes96 
Your assessment appears to be correct. A fix should appear later today.

**Comment by dbrookes96** [comment]
A year later and I realised that I was possible wrong about this. I think it behaves differently for different list box styles.

If the list box has LBS_EXTENDEDSEL style ItemFromPoint bOutside is TRUE for a point inside the client area that doesn't hit an item. That matches what the documentation previously said.

This may need to be checked...

**Comment by TylerMSFT** [comment]
Unfortunately, due to doc resourcing and current priorities, closing.
