### ISSUE TITLE
The term 'dumpbin' is not recognized in Windows PowerShell

### ISSUE THREAD

**Issue by MaxFun** [MicrosoftDocs/cpp-docs#1871]
What is the replacement for dumpbin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e19d7aee-ba2c-51ae-bd66-2745e808db02
* Version Independent ID: 8bbee0cd-8c48-0957-f6be-29b1d62c9e39
* Content: [DUMPBIN Command Line](https://docs.microsoft.com/en-us/cpp/build/reference/dumpbin-command-line?view=vs-2019)
* Content Source: [docs/build/reference/dumpbin-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dumpbin-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MaxFun 
PowerShell can invoke the regular DUMPBIN command, as long as your environment knows where it is. There's no PowerShell-native equivalent built-in script or command that I'm aware of.
Since the C++ docs don't address PowerShell-specific issues, I'm closing this.
