### ISSUE TITLE
[Concurrency Runtime] Misleading documentation

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/cpp-docs#1874]
This is what the documentation claims:

>The final continuation task, which updates the UI, specifies no continuation context, and therefore follows the apartment threading rules.

and

>   // We don't specify a continuation context here because we want the continuation to run on the STA thread.

This does not seem to be true for any arbitrary task. For example, for the following code, this is what happens:
```c++
MainPage::MainPage()
{
   InitializeComponent();
   //We're in the STA apartment
   create_task([]
   {
	//We're now in an MTA
   }).then([this, i]
      {
         //Still in an MTA (may or may not be the same thread as the antecedent task)
      });
}
```

Here, the continuation clearly does **not** return to the STA.  We should perhaps make this more explicit by noting that the claimed behavior only is guaranteed if the antecedent task is an `IAsyncOperation<T>` (perhaps `IAsyncInfo` in general?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2f7ded-3fcf-4ff2-0e43-0637d7d9332f
* Version Independent ID: 9d02885b-488b-2c41-22fa-d90f0fbe7d1e
* Content: [Creating Asynchronous Operations in C++ for UWP Apps](https://docs.microsoft.com/en-us/cpp/parallel/concrt/creating-asynchronous-operations-in-cpp-for-windows-store-apps?view=vs-2019#feedback)
* Content Source: [docs/parallel/concrt/creating-asynchronous-operations-in-cpp-for-windows-store-apps.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/creating-asynchronous-operations-in-cpp-for-windows-store-apps.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@keparanj 

I understand your confusion. The behavior you describe is true for the PPL in general. However, a `task` behaves differently in the Windows Runtime. The behavior is made clear in the last bullet point under [Key points](https://docs.microsoft.com/en-us/cpp/parallel/concrt/creating-asynchronous-operations-in-cpp-for-windows-store-apps?view=vs-2019#key-points) near the top of the article.
Given the context (sorry about the unintentional pun, there) this doesn't seem like a doc issue, so I'm closing it.
