### ISSUE TITLE
MinGW vs CppProperties

### ISSUE THREAD

**Issue by ZwergNaseXXL** [MicrosoftDocs/cpp-docs#1875]
I added the default configuration for MinGW64 and it looks exactly like in the example, except that the environment block is missing. In the output window I get the following message:

CppProperties.json: Warning: environment variable '${env.INCLUDE}' failed to evaluate.

Am I supposed to copy the environments block from the example? Or should it be created  automatically? Is there any way to autofill it according to my MinGW installation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder support for C++ build systems in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/open-folder-projects-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/open-folder-projects-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/open-folder-projects-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by amirea** [comment]
MSVS 2019 has built-in environments, one of which is mingw for arm processors. You have to create an environment for mingw x86/x64. And the environment variable ${env.INCLUDE} is probably defined in the environment block.
My CppProperties.json:
```
{
  "configurations": [
    {
      "environments": [
        {
          "MINGW_PREFIX": "C:/msys64/mingw64",
          "MINGW_CHOST": "x86_64-w64-mingw32",
          "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
          "MSYSTEM": "MINGW64",
          "MSYSTEM_CARCH": "x64_64",
          "MSYSTEM_PREFIX": "${env.MINGW_PREFIX}",
          "SHELL": "${env.MINGW_PREFIX}/../usr/bin/bash",
          "TEMP": "${env.MINGW_PREFIX}/../tmp",
          "TMP": "${env.TEMP}",
          "PATH": "${env.MINGW_PREFIX}/bin;${env.MINGW_PREFIX}/../usr/local/bin;${env.MINGW_PREFIX}/../usr/bin;${env.PATH}",
          "INCLUDE": "project/lib/include;${env.MINGW_PREFIX}/include;${env.MINGW_PREFIX}/${MINGW_CHOST}/include"
        }
		    ],
        
          "inheritEnvironments": [
            "mingw_64"
          ],
          "name": "Mingw64",
          "includePath": [
            "${env.INCLUDE}", 
            "${workspaceRoot}\\**"
          ],
          "intelliSenseMode": "windows-clang-x64"
    }
  ]
}
```
In my case `Warning: environment variable '${env.INCLUDE}' failed to evaluate.` is apparently not justified.

**Comment by amirea** [comment]
I'm sure the environments block contains the definition for `${env.INCLUDE}` in the form of `"INCLUDE": "<whatever/path;other/path>"`

**Comment by TylerMSFT** [comment]
Closing. Appears to be a support question that was answered.
