### ISSUE TITLE
Detect if env var is set OR use env var from Makefile

### ISSUE THREAD

**Issue by ZwergNaseXXL** [MicrosoftDocs/cpp-docs#1876]
The makefile sets a certain variable to a certain directory, but only when it is not already defined. So I need to either duplicate this behavior in CppProperties.json (detect if set, if not then use default value) or - better - just use the variable from the makefile. Is there any way to achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed0104b-8ba3-0b4d-5765-29f20e842b5c
* Version Independent ID: 7d5cc7af-86de-89cd-c86f-61f050ce7d1b
* Content: [CppProperties.json reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=vs-2019)
* Content Source: [docs/build/cppproperties-schema-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cppproperties-schema-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Closing. Over 1.5 years old and a product question rather than a specific scenario we are able to address at this time.
