### ISSUE TITLE
"includePath" vs #include <>

### ISSUE THREAD

**Issue by ZwergNaseXXL** [MicrosoftDocs/cpp-docs#1877]
So I defined my includePath to include some folders two up from ${workspaceRoot}. Go to definition works fine. However, when I rightclick on #include &lt;header.h&gt;, VS says it can't find it, even though it looks in the right directories. When I change that to #include "header.h", VS finds it without problems. I think that both the angular and the quoted #include should work, since the include path is set correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed0104b-8ba3-0b4d-5765-29f20e842b5c
* Version Independent ID: 7d5cc7af-86de-89cd-c86f-61f050ce7d1b
* Content: [CppProperties.json reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=vs-2019)
* Content Source: [docs/build/cppproperties-schema-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cppproperties-schema-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by ZwergNaseXXL** [comment]
I just noticed that opening angular #includes works fine when I'm already in one of those upper include folders. It just doesn't work from the workspace two levels down from there.

**Comment by TylerMSFT** [comment]
Closing. Not a specific doc ask and is over 1.5 years old.
