### ISSUE TITLE
Correction for example code in _popen

### ISSUE THREAD

**Issue by YellowAfterlife** [MicrosoftDocs/cpp-docs#1880]
It might be worthwhile to change
```cpp
printf(psBuffer);
```
to either
```cpp
printf("%s", psBuffer);
```
or
```cpp
puts(psBuffer);
```
as this currently will interpret %&lt;char&gt; in output as format specifiers, and thus likely crash the program if they appear in obtained string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b85181a9-588c-8ec0-a1b6-ffc18fc8856b
* Version Independent ID: 55212126-bfa9-d3ed-202b-1c27e2ad3689
* Content: [_popen, _wpopen](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/popen-wpopen.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/popen-wpopen.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@YellowAfterlife 
Thanks for the suggestion. The possibility seems remote in the file system context, but you never know. I've updated the article, and it should be published and visible tomorrow sometime.
