### ISSUE TITLE
Wrong/misleading link for extern templates?

### ISSUE THREAD

**Issue by jefgen** [MicrosoftDocs/cpp-docs#1883]
Near the top of the page, in item/bullet 4 it says:
  "For more information about this use of extern, see Templates."
However, the page that it links to has no mention or info about the "extern" keyword at all.
Could the link perhaps have been copy/pasted wrong perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5507963a-8f67-1de6-d164-28469e956006
* Version Independent ID: d4155e73-d05d-997b-8454-09564ea117d8
* Content: [extern (C++)](https://docs.microsoft.com/en-us/cpp/cpp/extern-cpp?view=vs-2019&source=docs)
* Content Source: [docs/cpp/extern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/extern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jefgen 

You're right, there's nothing in the Templates topic about that use of **extern**. Thanks for pointing that out. I've updated this article to link to [Explicit instantiation](https://docs.microsoft.com/en-us/cpp/cpp/explicit-instantiation?view=vs-2019) instead. It should get published sometime tomorrow.

**Comment by jefgen** [comment]
Thanks! :)
