### ISSUE TITLE
FE_ALL_EXCEPT is miss-spelled as FE_ALLEXCEPT

### ISSUE THREAD

**Issue by Lectem** [MicrosoftDocs/cpp-docs#1888]
The C and C++ standard (as well as MSVC fenv.h) define FE_ALL_EXCEPT  not FE_ALLEXCEPT http://eel.is/c++draft/cfenv.syn#:%3cfenv.h%3e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48c319db-8d0d-3385-ae33-5fdf336e17a2
* Version Independent ID: 22fa61cf-a379-be44-dd17-a907f7f9fc03
* Content: [fetestexcept](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fetestexcept1?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/fetestexcept1.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fetestexcept1.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Lectem 
Thanks for the report. It looks like the same typo was also in fegetexceptflag, feraiseexcept, and fesetexceptflag. I've corrected them all, and the update should be published on Monday.
