### ISSUE TITLE
C4616 incorrectly flagged for static analysis warnings if they are not the first item

### ISSUE THREAD

**Issue by chipplyman** [MicrosoftDocs/cpp-docs#1892]
#pragma warning ( disable : 6237 )  // OK
#pragma warning ( disable : 6239 ) // OK
#pragma warning ( disable : 6237; 6239 ) // C4616 false positive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cd410c-26bb-4e9b-5699-7a473ec73eb6
* Version Independent ID: f28aed65-d9a6-94fc-9ac0-95c4ffb3ad87
* Content: [Compiler Warning (level 1) C4616](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4616?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4616.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4616.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chipplyman 

Thanks for the submission. Based on my understanding of the syntax of the first two lines, it looks like you don't want a semicolon in the third line. Currently it's explicitly enabling 6239 as a warning. To disable two warnings in the same directive, you can concatenate them like this:
`#pragma warning ( disable : 6237 6239 )`

In any event, if the product behavior is incorrect, which may well be the case here, I recommend you raise a product issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). That's where the development team looks for product issue reports. The docs repo issues board is for documentation issues, and this doesn't look like one to me.
