### ISSUE TITLE
directory_iterator now throws exceptions, unlike the <experimental/...> one

### ISSUE THREAD

**Issue by malkia** [MicrosoftDocs/cpp-docs#1897]
Just hit that one, while porting code to work on vs2019 (from vs2017). We've used <experimental/filesystem> and the directory_iterator was not throwing under what we were feeding it, now it throws. 

This would require a bit more change than expected. I think developers should've been notified of this breaking change (I understand it was "experimental", but still...)

**Comment by corob-msft** [comment]
@malkia 
It appears the dev team thought that having the release notes link to the [Microsoft C++ language conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019) page that [has a footnote saying](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019#note_E) "This is a completely new implementation, incompatible with the previous `std::experimental` version" was sufficient indication that both the exceptions you've seen and a whole lot else besides are breaking changes. A similar note was added to the [\<filesystem>](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem) documentation to advertise the change a little more.

**Comment by malkia** [comment]
Ah, yes - saw that yesterday, after posting this! And also found out that most of my problems can be solved by using the constructors taking in std::error_code. Thank you for looking into it @corob-msft!
