### ISSUE TITLE
Powershell?

### ISSUE THREAD

**Issue by hjmallon** [MicrosoftDocs/cpp-docs#1898]
What is the recommended way to use the developer tools in an existing powershell window? I used to use vcvarsall.bat on CMD to choose 2015 or 2017 compiler (both installed with BuildTools 2017).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hjmallon 
Check out this Visual Studio team blog post: [The PowerShell you know and love now with a side of Visual Studio](https://devblogs.microsoft.com/visualstudio/the-powershell-you-know-and-love-now-with-a-side-of-visual-studio/). Given the feature backlog in Docs, that's likely to be your best and only documentation for some time.

**Comment by TylerMSFT** [comment]
Closing as it's been a year-and-a-half and the backlog is still large.
