### ISSUE TITLE
Variable name definitions wrong on data's example

### ISSUE THREAD

**Issue by TomsProject** [MicrosoftDocs/cpp-docs#1900]
Hello, I was learning the STL vector on this page, and I think your example code is wrong, you should turn the variable name "c1 ptr" to "c1_ptr" on line 10.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cd55b4-5345-3493-9d05-12868315571d
* Version Independent ID: 8e501921-6f1d-7705-231b-7ed0eded02ae
* Content: [vector class](https://docs.microsoft.com/en-us/cpp/standard-library/vector-class?view=vs-2019#data)
* Content Source: [docs/standard-library/vector-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/vector-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TomsProject 
That's a bizarre typo. Thanks for pointing it out. An updated document should be published sometime on Monday.
