### ISSUE TITLE
CMakeSettings.json supports setting the toolset using the VCToolsVersion property

### ISSUE THREAD

**Issue by lightwolf** [MicrosoftDocs/cpp-docs#1901]
This property can be defined in either the global or local environment block. For example, to use the v141 toolset with Ninja you can add this global environment block above the "configurations" block.

"environments": [

{

"VCToolsVersion": "14.16"

}

],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4417dbbb-58ad-4417-3a96-c1cb40516ca2
* Version Independent ID: cb5427c7-ee24-c972-bc44-ff890621cbf9
* Content: [CMakeSettings.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2019#feedback)
* Content Source: [docs/build/cmakesettings-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmakesettings-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
