### ISSUE TITLE
When count is zero

### ISSUE THREAD

**Issue by Snuff-Daddy** [MicrosoftDocs/cpp-docs#1907]
The bit about "When count is zero" is incomplete.  It will only work as described if also 'buffer' is NULL, at least as far as _vsnwprintf() is concerned on VS 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb683ba2-c8e8-9f2d-e265-f08b10495462
* Version Independent ID: 8b57f003-a4d3-48f1-e514-8a35b53d0bc7
* Content: [vsnprintf, _vsnprintf, _vsnprintf_l, _vsnwprintf, _vsnwprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l?view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
@Snuff-Daddy , quite right. Thank you for catching that. Should be live by tomorrow (6/25)

I have updated the doc to reflect:
- If *count* is zero and *buffer* is **NULL**, the value returned is the number of characters the functions would write, not including any terminating null. You can use this result to allocate sufficient buffer space for the string and its terminating null, and then call the function again to fill the buffer.
- If *count* is zero but *buffer* is not **NULL**, nothing is written and the function returns `-1`.
