### ISSUE TITLE
Missing Move ctor and move assignment operator

### ISSUE THREAD

**Issue by CrankFlash** [MicrosoftDocs/cpp-docs#1909]
This class (and all the other concurrent buffers) only declare private copy ctor and copy assignment operator. Which means we can't move them at all. Would it be possible to update them to a more modern C++ standard ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d612923-a959-f9df-816b-b729169d0e02
* Version Independent ID: 616a7bf5-2bb2-60c3-7b52-7f6a6c539e00
* Content: [single_assignment Class](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/single-assignment-class?view=vs-2019&source=docs#feedback)
* Content Source: [docs/parallel/concrt/reference/single-assignment-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/single-assignment-class.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@CrankFlash 
That's a good question, but not one we can address here in the C++ documentation. You're really making a product feature request. To get the attention of the product team, you'll want to ask in Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) instead. The issues and suggestions raised there go right to the people who can do something about them. If enough other people show interest in your suggestion, it'll become a higher priority. Bring it up there, and your idea has a shot at being implemented. Good luck!
