### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by hpesoj** [MicrosoftDocs/cpp-docs#1912]
&gt;As of Visual Studio 2019 version 16.2, modules are _*not*_ fully implemented in the Microsoft C++ compiler.
This seems like odd wording, given that you do not elaborate on what exactly is not yet implemented. Is this a typo? Did you mean to write "now"? When I initially read this I was deterred from trying to use modules with VC++. You might want to fix this, or explain what is yet to be implemented if it isn't a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hpesoj 
It's not a typo. The C++ standards committee adopted modules at a meeting last year, but the specification added to the draft standard didn't exactly match the experimental implementation in MSVC. Something to do with module partitions, if I recall correctly. So, to be appropriately circumspect, we say we don't fully implement the draft standard. We do, however, have a largely conforming implementation, and it's getting closer all the time. For more information, check out [C++ Modules conformance improvements with MSVC in Visual Studio 2019 16.5](https://devblogs.microsoft.com/cppblog/c-modules-conformance-improvements-with-msvc-in-visual-studio-2019-16-5/#module-partitions) in the C++ developer team blog. The documentation often lags the product by a little bit, but we'll be updating it as progress is made.

**Comment by hpesoj** [comment]
Thanks for clarifying.
