### ISSUE TITLE
C++20 print UTF-8 to console

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#1915]
Using C++2a. Please see the questions in the main.
```cpp
// https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=vs-2019
#include <cstdio>
#include <typeinfo>
#include <string>
#ifdef __GNUC__
#include <cstdlib>
#include <cxxabi.h>
#endif
#include <cuchar>
// -----------------------------------------------
using namespace std;
#define HIRAGANA "平仮名"
/// -----------------------------------------------
template<typename T>
static const char * nametype (T && t) {
    #ifdef __GNUC__
int     status{};
char   *realname{};
realname = abi::__cxa_demangle(
    typeid(T).name(), 0, 0, &status
);
    static string retval;
    retval = realname ;
    free(realname);
    return retval.c_str();
    #else
    return typeid(T).name();
    #endif
}
/// -----------------------------------------------
int main () {

  // how to print (u8"" HIRAGANA) to console?
   printf("\n%s", nametype((u8"" HIRAGANA)) );
  // how to print (u8"" HIRAGANA)[0] to console?
   printf( "\n%s", nametype((u8"" HIRAGANA)[0]) );
}
```
[Godbolt](https://godbolt.org/z/5MbnsX)

Please advise...

**Comment by corob-msft** [comment]
@DBJDBJ 

I built your code using this command line in a VS2019 Developer Command Prompt window:
`cl /nologo /EHsc /W4 /analyze /permissive- /std:c++latest u8_literals.cpp`

The output when I ran the compiled code:

```

char8_t const [19]
char8_t
```

By inspection, that appears to be correct, as far as I can tell. Were you expecting something different? If so, is there a particular page in the documentation that said you'd see something else?

**Comment by corob-msft** [comment]
Ah, I failed to run the Godbolt first. Yes, I see the size difference. This isn't a documentation issue, or at least, it isn't one yet. It's a product issue. I recommend you bring this up on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html), which can connect you to the people who can deal with it appropriately. Best of luck.

**Comment by DBJDBJ** [comment]
@corob-msft  many tanks for your reply, what  meant is hits does not compile (the things commented out above):
```cpp
  // how to print (u8"" HIRAGANA) to console?
         ... solution here ... (u8"" HIRAGANA) 
  // how to print (u8"" HIRAGANA)[0] to console?
        ... solition here ... (u8"" HIRAGANA)[0]) );
```
I know how to print the type names, I am asking how to print the values :)

**Comment by corob-msft** [comment]
Ah, I see. The short answer is, by default, you can't print UTF-8 directly to the Windows console, because the console is usually set to a code page that doesn't support it, and its font may only support a limited set of character glyphs.

If you use a narrow output function (`std::cout`, `printf`), and the content happens to all be single-byte utf-8 characters, it will probably work in a default code page console window, but if it's multibyte, you'll get gobbledygook, such as `σ╣│Σ╗«σÉì` or `å¹³ä»®å`. 

It's possible to change the console code page to utf-8 in Windows 10 (use the console command `chcp 16001`, or programmatically, call `::SetConsoleOutputCP(CP_UTF8)`). If you also set the console font to something that supports a broad character set, then your chances of getting useful output increase. Try Lucida Console, MS Gothic, or NSimSun. If the font doesn't support a particular code point, you'll get a rectangle glyph instead.

It probably doesn't need to be elaborated on, but there's absolutely nothing portable about code that outputs utf-8 to the console. C++20 makes it even more annoying by changing the default type of u8 string literals to char8_t, something that most C runtime functions can't digest.

**Comment by corob-msft** [comment]
Here's one way to do it, relying on the bitwise identical nature of `char` and `char8_t`. First, set your console font to MS Gothic,
```C++
// Projectutf8.cpp
// compile with: cl /nologo /EHsc /W4 /analyze /permissive- /std:c++latest
#include <iostream>
#include <Windows.h>

class ConsoleUTF8
{
public:
    ConsoleUTF8() 
        : original_cp(::GetConsoleOutputCP())
    {
        ::SetConsoleOutputCP(CP_UTF8);
    }
    ~ConsoleUTF8() 
    {
        ::SetConsoleOutputCP(original_cp);
    }
private:
    UINT original_cp;
};

int main()
{
    ConsoleUTF8 set_console_to_utf8;

#if 201703L < _MSVC_LANG
// #ifdef _­_­cpp_­char8_­t
    // The change to char8_t in C++20 is a breaking change to the std:
    const char8_t* hiragana = u8"平仮名";
    std::cout << reinterpret_cast<const char*>(hiragana) << std::endl;
#else
    const char* hiragana = "平仮名";
    std::cout << hiragana << std::endl;
#endif
}
```

**Comment by DBJDBJ** [comment]
@corob-msft you are very helphull thanks :) 

what I am aiming at , regardless of OS, there is no natural way to output u8

```cpp
    printf("%"  WG21DECISION_HERE ", u8"ひらがな"); // char8_t * 

    printf("%"  WG21DECISION_HERE ", u8'ひ'); // char8_t
```

And WG21 is "blaming" WG14 ... thus few more short years and world will have formating char for UTF8 , from C/C++ that is. 

### But wait, there is more! 
why not just `#include <cuchar>` [as documented](https://en.cppreference.com/w/cpp/header/cuchar) and use it before it is the very same implemented by compiler vendors when and if they go ahead and decide for themselves on utf8 formating char? 

dang .. it is not implemented by the spec ... yet.

**Comment by corob-msft** [comment]
Ours not to reason why. It seems very unlike the committee to make this sort of breaking change without fully specifying the replacement at the same time.

I also admit to being amused by ひらがな written as 平仮名. It just seems *wrong* somehow.

**Comment by DBJDBJ** [comment]
```cpp
   constexpr char const * speciment_one = "平仮名";
   constexpr char const * speciment_two = "ひらがな";
```
Works. VS2019, Wandbox, Godbolt. No `char8_t` in sight.  There must be some subliminal message somewhere ..

**Comment by DBJDBJ** [comment]
Yes, I just realized this too:

![image](https://user-images.githubusercontent.com/145155/75119036-aa868780-567f-11ea-9c0b-59713b41fcdb.png)
