### ISSUE TITLE
"Enforce type conversion rules" instead of "Additional Options"

### ISSUE THREAD

**Issue by aeewlwong** [MicrosoftDocs/cpp-docs#1918]
For VS2015: Common Properties &gt; C/C++ &gt; Language &gt; Enforce type conversion rules &gt; Yes (/Zc:rvalueCast)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e48392e-93be-f57c-4aa8-069c395b270a
* Version Independent ID: 237483df-5d18-4dad-a31a-423392083113
* Content: [/Zc:rvalueCast (Enforce type conversion rules)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-rvaluecast-enforce-type-conversion-rules?view=vs-2015#feedback)
* Content Source: [docs/build/reference/zc-rvaluecast-enforce-type-conversion-rules.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zc-rvaluecast-enforce-type-conversion-rules.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aeewlwong 
Thanks for pointing that out. Sometimes the compiler options get written about before there's an option in the IDE. In this case, it never got updated after the IDE changed. The fix should appear within a day or so.
