### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by irmackenzie** [MicrosoftDocs/cpp-docs#1919]
The item "C++ Clang tools for Windows" mentioned in the instructions doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f9a6a82-c89c-673f-0db3-9d4e2689c956
* Version Independent ID: 93c77d1a-b248-a12e-b13f-9ab299e88066
* Content: [Using Clang-Tidy in Visual Studio](https://docs.microsoft.com/en-us/cpp/code-quality/clang-tidy?view=vs-2019)
* Content Source: [docs/code-quality/clang-tidy.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/clang-tidy.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @frozenpandaman
* Microsoft Alias: **efessler**

**Comment by frozenpandaman** [comment]
Conversing with @corob-msft about this via email. :)

**Comment by corob-msft** [comment]
@irmackenzie 
Thanks for the reminder. Those instructions were temporary during the preview, and weren't needed for the released version, but the docs didn't get updated. The fix is live now.
