### ISSUE TITLE
Default property file for C/C++ projects

### ISSUE THREAD

**Issue by EvgeniyKishov** [MicrosoftDocs/cpp-docs#1924]
I can't find default property file for C/C++ projects in Visual Studio 2019 Community Edition. My directory "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC" doesn't contain a folder "VCTargets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b365b5b-ac15-1c0c-63c3-68fc9cbb48b0
* Version Independent ID: dcbeb798-114f-2abc-975d-176d1d3952d4
* Content: [Property inheritance in Visual Studio projects - C++](https://docs.microsoft.com/en-us/cpp/build/project-property-inheritance?view=vs-2019#feedback)
* Content Source: [docs/build/project-property-inheritance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/project-property-inheritance.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
A fix has been merged and should get published by sometime Monday.

**Comment by corob-msft** [comment]
@EvgeniyKishov 

And I forgot to mention, here's what I added:
"In Visual Studio 2019, these files are located in *`\Program Files (x86)\Microsoft Visual Studio\2019\<edition>\MSBuild\Microsoft\VC\v160`*."
