### ISSUE TITLE
Initialization in code snippets are irrelevant

### ISSUE THREAD

**Issue by jabelloc** [MicrosoftDocs/cpp-docs#1926]
Within the "**string literal is a constant array**" bullet point, in [Conformance improvements in Visual Studio](https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=vs-2019#VS_RTM) there are two code snippets containing the initialization `void *p = &"";` which are irrelevant in the examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311ab4e2-ad88-95df-4a9d-31266cfe8ee4
* Version Independent ID: 74e811f2-f772-3183-c700-66f4d8a763ac
* Content: [Visual C++ change history 2003 - 2015](https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=vs-2019)
* Content Source: [docs/porting/visual-cpp-change-history-2003-2015.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/visual-cpp-change-history-2003-2015.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jabelloc 
That's true, but it does no harm. I'm willing to leave it. On the other hand, if someone feels sufficiently motivated to provide a PR, I'd likely approve it.
