### ISSUE TITLE
This page deserves links pointing to the pages for GetExceptionCode, GetExceptionInformation, EXCEPTION_POINTERS, etc...

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#1933]
Cross-linking all information in documentation like this is generally a good idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5dfade-e224-32b4-919a-1e4f0c7b87ac
* Version Independent ID: 00702e1e-21c9-3520-ebec-53ff75dbb8f5
* Content: [try-except Statement](https://docs.microsoft.com/en-us/cpp/cpp/try-except-statement?view=vs-2019)
* Content Source: [docs/cpp/try-except-statement.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/try-except-statement.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed.
