### ISSUE TITLE
Incorrect parameters for SaveDivide function

### ISSUE THREAD

**Issue by MarcelInTO** [MicrosoftDocs/cpp-docs#1934]
The documentation has the divisor and dividend reversed. Both running tests and inspecting the code have confirmed this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33328acb-2809-04c8-1475-6e1a1d186934
* Version Independent ID: 7e44b7e5-86cd-08bd-b3f4-9be906bf982e
* Content: [SafeInt Functions](https://docs.microsoft.com/en-us/cpp/safeint/safeint-functions?view=vs-2019#feedback)
* Content Source: [docs/safeint/safeint-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/safeint/safeint-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for catching that, @MarcelInTO.
Fixed. Should go live by tomorrow afternoon (6/24)
