### ISSUE TITLE
b ooo

### ISSUE THREAD

**Issue by ztarby** [MicrosoftDocs/cpp-docs#1935]
jjaaj no sierto esq esta en ingles

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 97fd6e1e-08ca-04a7-fa81-3b9d55005d34
* Version Independent ID: 40ff5926-9706-4a15-3e4d-3d6ea965b9a7
* Content: [#define directive (C/C++)](https://docs.microsoft.com/es-es/cpp/preprocessor/hash-define-directive-c-cpp?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/hash-define-directive-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/hash-define-directive-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
It's English of a technical kind. Closing as not actionable.
