### ISSUE TITLE
Number of Elements

### ISSUE THREAD

**Issue by MikeMayUK** [MicrosoftDocs/cpp-docs#1936]
It would have saved me a couple of days poking around in the debug CRT code if this page had made it clear that the dest_size parameter includes the terminating NULL (and that therefore, the dest buffer needs to be one (ANSI or wide) character larger that what we conventionally regard as the string size i.e. the number of characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50b132-e9c1-1242-946e-7d04b68bc83b
* Version Independent ID: baf557db-7d11-c7cb-d696-e9e55f991fcf
* Content: [strcpy_s, wcscpy_s, _mbscpy_s, _mbscpy_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CORECRT_WSTRING%2Fwcscpy_s);k(wcscpy_s);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@MikeMayUK - Thank you for helping out other developers. I've added this tip. Should be live by tomorrow (5/29)
