### ISSUE TITLE
what will the getch return if there is no content avaliable on

### ISSUE THREAD

**Issue by jingkaimori** [MicrosoftDocs/cpp-docs#1939]
[Enter feedback here]
what will the <code>getch</code> return if there is no content avaliable on the stream  <code>stdin</code> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c56cd0-6b04-3472-ce56-fe749a238b70
* Version Independent ID: 5e6e3834-0c3c-0677-9dc2-9e7a96d31f0c
* Content: [_getch, _getwch](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/getch-getwch.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/getch-getwch.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@jingkaimori 
**`_getch`** waits for input, and doesn't return until input is available. It also locks the calling thread, Nothing else can happen on the calling thread until a key is pressed and **`_getch`** returns. That's why it's sometimes called a "blocking" function. Does this need clarification in the article?

**Comment by jingkaimori** [comment]
Yes.This feature needs to be clarified in the article, because the feature is a hot topic on the Internet.

**Comment by TylerMSFT** [comment]
I've added some text to the Return section indicating that it doesn't return until input is available.
The fix should be live by EOD tomorrow (6/24)
