### ISSUE TITLE
Numbered list doesn't restart, misleads the interpretation of a complex structure

### ISSUE THREAD

**Issue by EssentialNPC** [MicrosoftDocs/cpp-docs#194]
There should be two numbered lists on this page (https://docs.microsoft.com/en-us/cpp/c-language/interpreting-more-complex-declarators): one starting with "Start with the identifier", the other starting with "The identifier `var` is declared as".  It is important that the steps restart from 1 at the start of the second list, because that list's numbers must match those in the chart above it.  Github renders this correctly (https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/c-language/interpreting-more-complex-declarators.md)..

**Comment by corob-msft** [comment]
It's possible that a change to the markdown interpreter that's planned for a couple of months from now would fix the issue, but it was easier to just remove a stray space that appears to have been the cause of the problem. Thanks for pointing it out.
