### ISSUE TITLE
_mm_empty doesn't seem to be documented anywhere in this documentation.

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#1944]
We shouldn't mention undocumented functions. If the user is required to use _mm_empty, then we should document it and link to it from here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511e71d7-31f7-614e-e442-10a72012e09b
* Version Independent ID: 1bcd9f58-ba4b-70cc-f4b3-8dc0f8c2ea5a
* Content: [Compiler Warning (level 1) C4799](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4799?view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4799.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4799.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheJCAB 

`_mm_empty` is actually a preprocessor macro, defined in \<mmintrin.h> as [_m_empty](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_m_empty&expand=2231), which we [document](https://docs.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=vs-2019) as we do most intrinsics, by linking to the Intel Intrinsics Guide. I couldn't say why the macro is used here. Perhaps it's a preferred spelling.

**Comment by corob-msft** [comment]
@TheJCAB This and related macros have been added to the intrinsics list. However, it's not linked from here, because we don't usually link incidental function names to their definitions, unless they've got something useful to add. In this case, the `_mm_empty` documentation just says the same thing the warning docs say.
