### ISSUE TITLE
CComSingleThreadModel::Increment description incorrect

### ISSUE THREAD

**Issue by jcopenha** [MicrosoftDocs/cpp-docs#1947]
The description for CComSingleThreadModel::Increment says "This static function decrements the value of the variable pointed to by p" I believe it should say "This static function increments ...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbc1c0a-94bc-3afc-e201-f8490d6f946e
* Version Independent ID: 5d4dc392-525c-dafc-a5a5-326868f1a063
* Content: [CComSingleThreadModel Class](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomsinglethreadmodel-class?view=vs-2019#feedback)
* Content Source: [docs/atl/reference/ccomsinglethreadmodel-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/ccomsinglethreadmodel-class.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for catching that. I have fixed it and it should be live Monday (3/2) afternoon.
#please-close
