### ISSUE TITLE
Comparison operators for input iterators are wrong!

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/cpp-docs#1952]
You can compare input iterators by using the ++ and != operators.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: cbb2e33d-becb-5535-e621-670d76949e51
* Version Independent ID: 7d907ac2-287f-8466-f35a-cade3f86e08a
* Content: [Iterators](https://docs.microsoft.com/pl-pl/cpp/standard-library/iterators?view=vs-2019)
* Content Source: [docs/standard-library/iterators.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/iterators.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for catching that. Fixed. Should be live by tomorrow (6/24)
