### ISSUE TITLE
This page should provide packing rules of bit-fields IMO

### ISSUE THREAD

**Issue by frederick-vs-ja** [MicrosoftDocs/cpp-docs#1957]
In tests I have found that:

Only contiguous bit-fields whose types are of the same width may be packed into an allocation unit (e.g. two bit-fields of type int and unsigned long respectively may be packed together). The allocation unit is of the size and alignment as types of such bit-fields. Packing is greedy and from left to right. The total bit width of packed bit-fields is as large as possible, but must not greater than the bit width of the allocation unit.

These details are implementation-defined in C/C++ standard, but not documented here  (and on https://docs.microsoft.com/en-us/cpp/c-language/c-bit-fields?view=vs-2019) currently.

I don't know whether the conclusion I got is right. The packing rules should be documented IMO, since some codes may depend on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78c89c2-7d34-fac8-9043-4099bc8637dd
* Version Independent ID: e265dccc-e3f6-7464-a6cf-e0e19aea772f
* Content: [C++ Bit Fields](https://docs.microsoft.com/en-us/cpp/cpp/cpp-bit-fields?view=vs-2019#feedback)
* Content Source: [docs/cpp/cpp-bit-fields.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-bit-fields.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
