### ISSUE TITLE
"Learn Visual C++" link at the bottom of the page is misleading

### ISSUE THREAD

**Issue by Phidler** [MicrosoftDocs/cpp-docs#196]
The "Learn Visual C++" link at the end of the page under "More resources" is misleading and sends you to https://msdn.microsoft.com/en-us/library/aa187916.aspx which looks like old documentation on tools?

Anyways, it's definitely not a link that teaches you Visual C++.

Would be nice to have some official documentation and tutorials directly from Microsoft on how to use C++ and C with the Visual Studio compiler specifically. I've been begging for this for years.

Thanks!

Phidler

**Comment by Phidler** [comment]
Oh in case this wasn't clear I was referring to this page: https://docs.microsoft.com/en-us/cpp/visual-cpp-in-visual-studio

Thanks

**Comment by Phidler** [comment]
No not necessarily it's just convenient to have everything in one place and I like how everything is explained on Microsoft docs, the examples, and its open source nature and how quickly you guys respond, wow!

I find it very cool and useful. I'm just a student and the docs have been crucial to my learning.

If I were to suggest something it would be to add some nice tutorials for C and C++. Learning through those is a lot of fun and essential ice breakers for learning different languages, etc.

But I understand that it's against your policy.

Thank you so much for you quick response!

Phidler

**Comment by Phidler** [comment]
I just had an Idea. If you really don't want to write your own tutorials or instructions then maybe we could get some links to some books and/or online tutorials officially recognized by Microsoft as good learning material.

Phidler

**Comment by mikeblome** [comment]
@Phidler The specific link you mentioned now goes to the right starting point for Visual C++. Thanks for noticing that and letting us know! Your suggestion for other links to C++ educational content is interesting and we'll be adding additional links here in the next few months as we do some general site improvements.
