### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by munsingh** [MicrosoftDocs/cpp-docs#1960]
It would be good to mention the header file, which defines the CComPtr SmartPointer class.

**Comment by corob-msft** [comment]
@munsingh 
Any required headers are listed in a **Requirements** section [on the relevant page](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptr-class?view=vs-2019#requirements). In this case it requires *atlbase.h*, but `CComPtr` is actually declared in *atlcomcli.h*, which is included in *atlbase.h*, in case you were looking for the class sources.
