### ISSUE TITLE
error in example code

### ISSUE THREAD

**Issue by blurredart** [MicrosoftDocs/cpp-docs#1963]
For Distance class, operator+ should accept Distance instead of Distance&. Otherwise we get error: cannot bind non-const lvalue reference of type 'Distance&' to an rvalue of type 'Distance'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba17b29c-7421-ef5a-5817-dc1d7cde6e64
* Version Independent ID: a5405b59-608f-eaa8-c5c2-e38b6c89248a
* Content: [User-defined literals (C++)](https://docs.microsoft.com/en-us/cpp/cpp/user-defined-literals-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/user-defined-literals-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/user-defined-literals-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@blurredart 
You're right, that code has a problem. I've submitted a fix, and it should be visible sometime in the next day or so. Thanks!
