### ISSUE TITLE
/analyze option form has changed for different VS versions

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#1965]
Selecting the VS version drop-down in the documentation doesn't seem to do anything anymore.

The form of the /analyze option has changed significantly between VS 2015, 2017 and 2019, but those changes are not shown in the documentation.

**Comment by corob-msft** [comment]
@LegalizeAdulthood 

Before version-specific tagging became available in Docs about a year ago, we tried to write content in a way applicable to all the versions supported, usually by calling out version-specific content explicitly.  There is some version-specific content in the [/analyze:plugin](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019#arguments) option, for example, that switches based on the version selected.

Is there specific content you're looking for? If so, which page are you looking for it on?

**Comment by LegalizeAdulthood** [comment]
Not all the options listed are available in VS 2017 or VS 2015.  The documentation shows the correct options for VS 2019 AFAICT.

**Comment by TylerMSFT** [comment]
It looks like this was addressed by the doc update mentioned above. Please reopen if it doesn't address your concern.
