### ISSUE TITLE
"delete pObject"

### ISSUE THREAD

**Issue by aeewlwong** [MicrosoftDocs/cpp-docs#1967]
It seems to me that there are changes of auto-delete behavior under MFC framework across versions (e.g. VS2002/VS2010/VS2013, VS2015) of visual studio.

In some old versions, I need to explicitly "delete pObject" otherwise memory leak is reported.
I upgrade my MFC projects from VS2013 to VS2015 now. I encounter a "double delete" problem with some dynamic created objects I explicitly "delete pObject". It could be better if your documentation could describe "how to delete these dynamic created objects".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5866f41e-0388-9014-4ad6-6e1c5c330cd2
* Version Independent ID: ed345ab9-b26f-06d1-7fb3-d7a6d9ea9081
* Content: [Dynamic Object Creation](https://docs.microsoft.com/en-us/cpp/mfc/dynamic-object-creation?view=vs-2019)
* Content Source: [docs/mfc/dynamic-object-creation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/dynamic-object-creation.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by aeewlwong** [comment]
Please forget the "double free" issue I mentioned above.

Anyway, it could be useful if you add a link to the technical article "TN017: Destroying Window Objects".

**Comment by TylerMSFT** [comment]
I've added the requested link. Thanks for raising the issue.
