### ISSUE TITLE
What's the difference between an agile event and a non-agile event?

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/cpp-docs#197]
These are doc pages for non-agile and agile events:
  - [EventSource](https://docs.microsoft.com/en-us/cpp/windows/eventsource-class) (non-agile)
  - [AgileEventSource](https://docs.microsoft.com/en-us/cpp/windows/agileeventsource-class)

These docs mention the phrases "agile event" and "non-agile event" but don't elaborate on what these phrases mean conceptually.

Adam Comella
Microsoft Corp.

**Comment by corob-msft** [comment]
Closing the issue on the assumption that the related PR fixes it.
