### ISSUE TITLE
What environment variables are defined in those predefined toolsets?

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/cpp-docs#1972]
There is no document on what kind of environment vars are defined in those toolsets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292b6ea2-afb0-8a77-7748-6d39286890ce
* Version Independent ID: 55816d6b-9600-c31c-01df-b53c2f185319
* Content: [Customize CMake build settings in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=vs-2019#feedback)
* Content Source: [docs/build/customize-cmake-settings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/customize-cmake-settings.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@esweet431 for info.

**Comment by congkun-ck** [comment]
Ping.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
