### ISSUE TITLE
How to configure deploy for WSL based build/debug separated cmake project?

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/cpp-docs#1974]
Build happens on WSL. In this case how should I configure sourceMachine??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7a4e8b-d422-93b1-e042-55c2acbf8ef3
* Version Independent ID: 0d55f5d8-846e-3282-b580-9b7770053958
* Content: [Configure CMake debugging sessions in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=vs-2019#customize-debugger-settings)
* Content Source: [docs/build/configure-cmake-debugging-sessions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configure-cmake-debugging-sessions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@congkun-ck 
Check out the instructions in [Choose a Linux target](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019#choose-a-linux-target). Depending on how you access the WSL file system, you might not need to do any source-target file copying.

@esweet431 Is this something we can add clarification to?

**Comment by esweet431** [comment]
Unless you want fine-grained control over the files and directories that are copied over to the deploy system, you shouldn't need to fill out the "deploy"object (including "sourceMachine") - remoteMachineName just needs to be the remote system you are deploying to.

I'm assuming you are building natively on WSL (not over SSH)? I'll get back to you on how to configure sourceMachine in this case.

**Comment by congkun-ck** [comment]
I am doing WSL based ARM build and debug on a separate machine. Documents on this configuration is pretty incomplete. Now I have to manually deploy bits to the debug machine. There is no clear document on how to configure deploy for WSL for this separate machines scenario.

**Comment by esweet431** [comment]
Circling back hear: when natively building on WSL you don't need to specify sourceMachine. You can still specify sourceDirectory with a path that exists on WSL to configure additional files and directories for deployment. The 'sourceMachine' used for build is determined by the WSL instance specified in CMakeSettings.json.

**Comment by congkun-ck** [comment]
The document says:
"disableDeploy: Indicates whether build/debug separation is disabled. When enabled, this feature allows build and debug to occur on two separate machines"

It sounds to me if I wants to separate build and debug on two machines, this has to be turned on to true? So auto deployment will not happen for separate machines scenario?

However the example in the [linked document ](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#cmake-projects) shows an example of "disableDeploy:false"??? I tried to set this to true but always got a connection timed out error.

**Comment by esweet431** [comment]
Sorry for the confusion, disableDeploy should be set to "false" to enable the separation of build and debug. I have a PR out to make this more clear.

**Comment by congkun-ck** [comment]
okay thanks. apparently it doesn't work for me if I set disableDeploy to false. It fails with error. I am opening a ticket to the prod team.
