### ISSUE TITLE
Evaluation of postfix-expression is not precise enough

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/cpp-docs#1975]
The postfix-expression must unambiguously evaluate to a function address (for example, by matching a function identifier applicable to the parameters of the given function-call or by evaluating a function pointer).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c626924e-d490-c748-5c75-b69d54357eb8
* Version Independent ID: 06cb2f2f-a402-0626-2afe-3601cef43f0c
* Content: [Function Call Operator: ()](https://docs.microsoft.com/en-us/cpp/cpp/function-call-operator-parens?view=vs-2019)
* Content Source: [docs/cpp/function-call-operator-parens.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/function-call-operator-parens.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yecril71pl 
Thanks for the report, and the PR. In review, I'm having trouble reconciling the content (not just your additions) with what I read in the Standard. Can you point at something there that supports the distinctions you've suggested?

**Comment by yecril71pl** [comment]
I am sorry, I do not have the standard.  However, I believe it is common knowledge that matching a function address to a function identifier depends on a wider context than mere identifier and suggesting otherwise is deeply misleading to the reader.  I do not insist that my request is necessarily correct but I believe it would make an improvement.

**Comment by corob-msft** [comment]
I suspect the discussion about addresses is something of a red herring. Functions don't need to resolve to unambiguous addresses in practice, at least in terms of being the only function identifier that has a given address, unless something in the code actually compares the addresses. That's how the COMDAT folding optimization works. The *postfix-expression* does need to resolve unambiguously to a callable thing, which might be a function, function pointer, function reference, member function, function object, or lambda. It looks like the article has just picked an arbitrary subset of possible function-call types to document. What also gets left out in the article is discussion of how these callable types interact with overload resolution and argument-dependent lookup to affect the *postfix-expression* interpretation by the compiler. It was confusing before your change, and, no disparagement intended, your change hasn't fixed what's confusing me.

**Comment by yecril71pl** [comment]
I do not take it as a disparagement; I just tried to change as little as possible.  I agree that the concept needs more work and, short of writing a book, whatever we do is going to be unsatisfactory.  But it is an intro, so an approximation is necessary, with links to further information.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
