### ISSUE TITLE
Old-Style Cast Warning

### ISSUE THREAD

**Issue by LCS-Inrotech** [MicrosoftDocs/cpp-docs#1977]
Hi,
I wanted to know if you have a compiler warning for casts of the old style?
Eg. using (MyType*)somePtrToCastinstead instead of dynamic_cast&lt;MyType*&gt;(somePtrToCast).

I have not been able to find some in your documentation.

br
Lukas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4febd6ec-05d8-97cf-fb9f-fc41e4ee2142
* Version Independent ID: afe287bd-011f-90f2-eef4-2559e405d277
* Content: [Type conversions and type safety](https://docs.microsoft.com/en-us/cpp/cpp/type-conversions-and-type-safety-modern-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/type-conversions-and-type-safety-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/type-conversions-and-type-safety-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LCS-Inrotech 
There used to be a warning C4303 "C-style cast from '*type1*' to '*type2*' is deprecated, use static\_cast, \_\_try\_cast or dynamic\_cast", but I'm not convinced the compiler generates this warning anymore. At least, I couldn't get it to appear, even with /Wall, on some examples I tried.

If you enable code analysis, and turn on all the [C++ Core Guidelines checks](https://docs.microsoft.com/en-us/cpp/code-quality/code-analysis-for-cpp-corecheck?view=vs-2019), there's also [C26493 NO_CSTYLE_CAST](https://docs.microsoft.com/en-us/cpp/code-quality/c26493?view=vs-2019), but I couldn't get that to fire, either. Maybe there's a bug here.

**Comment by LCS-Inrotech** [comment]
Thanks for the quick reply!
I've had as much luck with the two methods as you did, but thanks for the information!
Would be nice to get C4303 back thought.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
