### ISSUE TITLE
Broken link to Containers in the section See also

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/cpp-docs#1978]
The link [Containers](https://docs.microsoft.com/en-us/cpp/cpp/containers-modern-cpp?view=vs-2019) takes me to the page "welcome-back-to-cpp-modern-cpp".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71492b71-7570-f06d-c905-e78b359b0b8b
* Version Independent ID: 6cc78e56-7034-c776-f532-68b8ccf75572
* Content: [C++ Standard Library Containers](https://docs.microsoft.com/en-us/cpp/standard-library/stl-containers?view=vs-2019)
* Content Source: [docs/standard-library/stl-containers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/stl-containers.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Fixed. Now links to the parallel containers topic.
Will be live by Monday afternoon (3/30)
