### ISSUE TITLE
Using algorithms with custom containers

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/cpp-docs#1979]
The wording *the same algorithm can be used by most if not all of the C++ Standard Library containers* hides the information that algorithms should be useful with iterators to custom containers as well, provided that a custom (e.g. stream-based) container fulfils the same requirements as imposed on standard library containers (in particular, that the value type can be freely copied).  For some algorithms, e.g. sort, these requirements turn out to be indispensable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a35679-b92d-3ffb-6413-8210323c686a
* Version Independent ID: 84327371-0da6-14fe-f84b-092fc6b634ad
* Content: [Algorithms](https://docs.microsoft.com/en-us/cpp/standard-library/algorithms?view=vs-2019)
* Content Source: [docs/standard-library/algorithms.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/algorithms.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by yecril71pl** [comment]
If this issue is approved as valid, resolving it will require creating a concept page about custom containers, currently missing.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
