### ISSUE TITLE
unable to compile constexpr in condition without a warning

### ISSUE THREAD

**Issue by gaebor** [MicrosoftDocs/cpp-docs#1981]
```cpp
#include<cstdio>

template<int i>
void f()
{
    if (i == 0)
        std::puts("f zero");
    else
        std::puts("f positive");
}

int main()
{
    f<0>();
    f<1>();
	return 0;
}
```
 - As stated in the documentation of C4127 this triggers a warning with `/std:c++17`, which is fine.
 - Also if I put the `constexpr` as advised, it won't compile with `/std:c++14` (or `c++11`), which is also not a surprise.

What baffle me is that it shows a warning in `/std:c++14` without the `constexpr`:

    > cl -nologo /W4 /std:c++14 src\ifconstexpr.cpp
    ifconstexpr.cpp
    src\ifconstexpr.cpp(6): warning C4127: conditional expression is constant
    src\ifconstexpr.cpp(6): note: consider using 'if constexpr' statement instead
    src\ifconstexpr.cpp(14): note: see reference to function template instantiation 'void f<0>(void)' being compiled

But if I put the `constexpr` in it, then it won't compile:

    > cl -nologo /W4 /std:c++14 src\ifconstexpr.cpp
    ifconstexpr.cpp
    src\ifconstexpr.cpp(6): error C4984: 'if constexpr' is a C++17 language extension
    src\ifconstexpr.cpp(14): note: see reference to function template instantiation 'void f<0>(void)' being compiled

It's kind-of contradictory that the compiler suggests to use something which is not supported.

If this is intended, then my question is:
 - Is it a pre-`c++17` compliant way of doing this?

Version info:
 - Microsoft Visual Studio Community 2017 
 - Version 15.7.3
 - VisualStudio.15.Release/15.7.3+27703.2026

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88a50e7-ed43-5fe5-e3f7-7e243af2e290
* Version Independent ID: 7ed7dfe9-7959-4e04-30d0-1c39e33af8e8
* Content: [Compiler Warning (level 4) C4127](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4127?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gaebor 
I'm sorry the message is giving you grief. Odds are good that this is a minor product bug, where a diagnostic note is triggered when it shouldn't be. In this case, the C4127 warning about the conditional expression is expected, but the appended notes don't apply and are actively misleading. I'd recommend raising this issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html), where the product team will see it and perhaps do something about it. If the documentation needs an update, they'll let us know. Thanks for taking the time to report.
