### ISSUE TITLE
Inputting anything other than a number causes the calculator to break a little...

### ISSUE THREAD

**Issue by coranax** [MicrosoftDocs/cpp-docs#2003]
I tried finding a work around myself but as I am new to this I've been unsuccessful. I think including this in the tutorial would be beneficial as most users will try to see what happens when using an unexpected input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019&redirectedfrom=MSDN#feedback)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Hi @cornax, I agree that this would be helpful, but we just don't have the bandwidth for this update given other document issues that need to be addressed. Sorry about that.
