### ISSUE TITLE
Where is the Attach function?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#2012]
I was going to link to a colleague to this function, only to find that it is missing.  Please add.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 812eb693-bf13-8af9-95b9-5826cf1dfa62
* Version Independent ID: e78b430e-e120-f625-87c8-088fa266481e
* Content: [CBitmap Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cbitmap-class?view=vs-2019#fromhandle)
* Content Source: [docs/mfc/reference/cbitmap-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cbitmap-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
