### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by LaurenENye** [MicrosoftDocs/cpp-docs#2015]
The header says C2372.
Just before the example code it says "this will generate C2326."
Then in the code it goes back to C2372.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52cebe4-7649-c7d6-6deb-935ccff75b5f
* Version Independent ID: 2dca4016-c72f-1283-f8c4-a1a0cc64c226
* Content: [Compiler Error C2372](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2372?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2372.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2372.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LaurenENye Fixed, thanks for the report.
