### ISSUE TITLE
The secure versions of swprintf and _swprintf_l do not take a count parameter.

### ISSUE THREAD

**Issue by fanck13** [MicrosoftDocs/cpp-docs#2017]
Is this right? I think it should be "The secure versions of swprintf and _swprintf_l take a count parameter."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a209539e-aeec-2bb4-5887-c4cf90467204
* Version Independent ID: ed0abe24-9562-5db6-29dc-c7ad7588081a
* Content: [sprintf, _sprintf_l, swprintf, _swprintf_l, __swprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
The description is incorrect. It should say that they take the size of the buffer.
Fixed. Should be live by tomorrow (6/24/)
