### ISSUE TITLE
Error in table

### ISSUE THREAD

**Issue by cpuwzd** [MicrosoftDocs/cpp-docs#2018]
The table has two rows for LPCSTR. The first of these rows should be for LPSTR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7907e0-45f6-2333-d4b0-09c2206f2917
* Version Independent ID: ba9200fd-d49e-8d88-0d21-faa82db22c36
* Content: [Calling Native Functions from Managed Code](https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2019)
* Content Source: [docs/dotnet/calling-native-functions-from-managed-code.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/calling-native-functions-from-managed-code.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you. Fixed.
The fix should be live by Monday 3/30
