### ISSUE TITLE
Trigger warning C6011 only if there are no checks on the pointer before the offending call.

### ISSUE THREAD

**Issue by razor85** [MicrosoftDocs/cpp-docs#2020]
This warning should be triggered only if there are no validations on the pointer before the offending call. If there are asserts verifying for ptr != nullptr, the warning should not appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f06b2b0-b8c7-8d02-1c6c-71bf6f2abe07
* Version Independent ID: d85395d3-d1ec-7863-5263-a142a424cbb1
* Content: [C6011](https://docs.microsoft.com/en-us/cpp/code-quality/c6011?view=vs-2019)
* Content Source: [docs/code-quality/c6011.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6011.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@razor85 Thanks for the report. The fix should appear within a day.

**Comment by razor85** [comment]
Thanks :D
