### ISSUE TITLE
documentation completely missing for all the important functionality

### ISSUE THREAD

**Issue by tanjb-msft** [MicrosoftDocs/cpp-docs#2027]
Where are ALL THE IMPORTANT FUNCTIONS?  Find(), at(), operator[], count(), emplace(), insert(), erase(), clear()

I'm mystified.  What happened here, do you have a broken automatic documentation generator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd46da79-7f00-5e35-d2cc-105c115c1ef9
* Version Independent ID: 9038804b-4ff8-db02-35fa-da0aea8e46e0
* Content: [&lt;map&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/map-functions?view=vs-2019)
* Content Source: [docs/standard-library/map-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/map-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, they are there. They are documented on the class. See https://docs.microsoft.com/en-us/cpp/standard-library/map-class?view=vs-2019

The way the STL docs work is they list the non-member functions and operators separately from the member functions/operators.
