### ISSUE TITLE
VisualStudio CMake support auto re-generate always deletes cache

### ISSUE THREAD

**Issue by b8adamson** [MicrosoftDocs/cpp-docs#2034]
My team and I are really enjoying CMake support in Visual Studio.
However, the features seem to be evolving pretty rapidly.
Recently we seem to have encountered new issues with VisualStudio's CMake support each time we update to newer release/version of Visual Studio.  Typically these are things that were previously working, that seem to have stopped working, or work differently in undesirable ways after updating.  

For example, after a recent update to Visual Studio 16.5 the CMake "auto-regenerate" feature, which re-runs the CMake generate step after editing a CMakeLists.txt file seems to have gotten much more aggressive and **always deletes the entire cache** before re-generating.

Beginning of the output from CMake window after adding a meaningless space to a CMakelists.txt file:

> 1> The set of enabled languages has changed. 
> 
> Deleting cache and regenerating.
> ...

This is really undesirable for the workflow we've built around how this worked in earlier versions of Visual Studio.

We're wondering where we should direct feedback/questions regarding whether changes like this are intentional or if we're using the product wrong, etc...

If this is the correct place for questions/feedback like this, please let me know and I'll provide more details.

Thanks!  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019#see-also)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@b8adamson 

We try to keep the documentation in sync with the product, but sometimes there's a lag. This is a good place to report a discrepancy. However, if you're having an issue with product behavior, then you should bring that to the attention of the development team instead. You can do that from within Visual Studio by using the **Help** > **Send Feedback** > **Suggest a feature** menu item, or by entering an issue directly on the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website. That's the fastest and easiest way to get your issue in front of dev team eyeballs. Even if it's working as designed, that doesn't mean it can't be improved. And if the product changes and the docs need an update, the dev team will let us know.

@esweet431 FYI.

**Comment by b8adamson** [comment]
Thanks! I filed an issue here:
https://developercommunity.visualstudio.com/content/problem/971061/cmake-auto-configure-always-deletes-cache-after-ed.html
