### ISSUE TITLE
Configure to make x64 the default project

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/cpp-docs#2035]
Is there a way to make the default x64 instead of x86 for all newly opened projects? If not, there should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56287d26-a426-a30f-bdb4-432125710e49
* Version Independent ID: 6af8f7c6-9657-739c-0e06-3b1f43fae7e4
* Content: [How to: Configure Visual Studio C++ projects to Target 64-Bit, x64 Platforms](https://docs.microsoft.com/en-us/cpp/build/how-to-configure-visual-cpp-projects-to-target-64-bit-platforms?view=vs-2019)
* Content Source: [docs/build/how-to-configure-visual-cpp-projects-to-target-64-bit-platforms.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-configure-visual-cpp-projects-to-target-64-bit-platforms.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@troglobytor 

That's a worthy idea, and I'm sure you're not the only one who'd appreciate that ability. At present, there's no simple way to switch the default configuration for new projects. If you'd like to see one added to the product, you can make a suggestion from within Visual Studio by using the **Help** > **Send Feedback** > **Suggest a Feature** menu item, or by entering an issue directly on the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. That's the easiest way to bring ideas to the attention of the development team. If enough other people upvote your idea, odds are good it will be implemented. Give it a shot, and good luck.
