### ISSUE TITLE
Additional explanation on non covariant return type

### ISSUE THREAD

**Issue by zosrothko** [MicrosoftDocs/cpp-docs#2036]
Could you add a chapter explaining why the C2555 error pops up on line 13
#include &lt;iostream&gt;

class Token {
public:
	virtual ~Token() {}
	virtual Token*& next() = 0;
	virtual const Token* next() const = 0;
};
class MyToken : public Token {
public:
	MyToken() {}
	virtual ~MyToken() {}
	virtual MyToken*& next() { return _next; }                            // line 13
  	virtual const MyToken* next() const { return _next; }
private:
	MyToken* _next = nullptr;
};
class HisToken : public Token {
public:
	HisToken() {}
	virtual ~HisToken() {}
	virtual Token*& next() { return _next; }
	virtual const Token* next() const { return _next; }
private:
	Token* _next = nullptr;
};
int main()
{
	std::cout &lt;&lt; "Hello World!\n";
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d191cbda-da8a-c83f-282f-f893f33ae070
* Version Independent ID: a8c83adc-b727-050c-467d-9471dccb6be1
* Content: [Compiler Error C2555](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2555?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2555.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c2555.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@zosrothko Thanks for the suggestion. An updated document is live.
