### ISSUE TITLE
Unable to grasp from the document how actual compilation is being achieved

### ISSUE THREAD

**Issue by aileronajay** [MicrosoftDocs/cpp-docs#204]
The ClCompile, is an item as it is nested under the ItemGroup tag, it also seems that the files to be compiled are referred to in the ClCompile tag. On the documentation page for Items, https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items, it states that Items are inputs into the build system. I dont see a task above which takes these ClCompile items and compiles them, how is compilation being achieved with the above setup

**Comment by mikeblome** [comment]
@aileronjay I'm not an MSBuild expert, but have you looked at this page? It talks about how tasks are not explitly declared in the XML file: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-tasks.  If this doesn't answer the question let me know and I'll forward to the experts.

**Comment by aileronajay** [comment]
posting link to the stackoverflow post, https://stackoverflow.com/questions/49591809/is-the-clcompile-item-a-task-as-well

**Comment by mikeblome** [comment]
@aileronajay I have updated this page: https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project .
