### ISSUE TITLE
Convert ATL MFC Shared TOC from MD to Yaml

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/cpp-docs#2040]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/atl-mfc-shared/reference/TOC.md
Pretty minor thing, but I thought I'd suggest it if you have an automated way to do it, since it has a bunch of unescaped elements that trigger Markdownlint

**Comment by corob-msft** [comment]
@nschonni 
Thanks, that's a work item I already have in progress, along with all the rest of our TOC and index pages. We're working to adopt the new common Docs style. Other issues like this one should get fixed as a side-effect.
