### ISSUE TITLE
No definition of each variable type?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2041]
@HSeo commented on [Sun Mar 29 2020](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/227)

Is it possible to omit the definition of each variable type in bit_fields2.cpp, such as
unsigned nWeekDay  : 3;    // 0..7   (3 bits)
instead of 
unsigned int nWeekDay  : 3;    // 0..7   (3 bits)
?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a78c89c2-7d34-fac8-9043-4099bc8637dd
* Version Independent ID: e265dccc-e3f6-7464-a6cf-e0e19aea772f
* Content: [C++ ビット フィールド](https://docs.microsoft.com/ja-jp/cpp/cpp/cpp-bit-fields?view=vs-2019#feedback)
* Content Source: [docs/cpp/cpp-bit-fields.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/cpp-bit-fields.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Sun Mar 29 2020](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/227#issuecomment-605652535)

Hello, @HSeo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@HSeo

Bit fields must always be declared using an integral type. The `unsigned` and `unsigned int` types are synonyms. That is, `unsigned` means `unsigned int`, unless another integral type name follows it. These declarations are identical:

```
// bit_fields123.cpp
struct Date1 {
   unsigned int nWeekDay  : 3;    // 0..7   (3 bits)
   unsigned int nMonthDay : 6;    // 0..31  (6 bits)
   unsigned int           : 0;    // Force alignment to next boundary.
   unsigned int nMonth    : 5;    // 0..12  (5 bits)
   unsigned int nYear     : 8;    // 0..100 (8 bits)
};

struct Date2 {
   unsigned nWeekDay      : 3;    // 0..7   (3 bits)
   unsigned nMonthDay     : 6;    // 0..31  (6 bits)
   unsigned               : 0;    // Force alignment to next boundary.
   unsigned nMonth        : 5;    // 0..12  (5 bits)
   unsigned nYear         : 8;    // 0..100 (8 bits)
};
```
