### ISSUE TITLE
Newer libraries with older Apps

### ISSUE THREAD

**Issue by Ryan3D** [MicrosoftDocs/cpp-docs#2051]
This page has this example: "Here's an example: you can link an app compiled using the 2017 toolset to a static library compiled using 2019, if they're linked using the 2019 toolset." 

However, I do not see how it is possible to use different toolsets for building and linking an application. Is there a way to specify a different toolset for the compiler and link stages in Visual Studio 2019? It seems like this is controlled by the &lt;PlatformToolset&gt; property, and that applies to both the compile and link stages. If my understanding is correct, the example above is impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcccbfe4-34d9-67cb-efbb-6c15ff35b38e
* Version Independent ID: cc082cbf-a967-6709-f3ef-190e78cf84e9
* Content: [C++ binary compatibility 2015-2019](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019#feedback)
* Content Source: [docs/porting/binary-compat-2015-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/binary-compat-2015-2017.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ryan3D 

The article isn't describing a single project that compiles different files using different toolsets then links them together. So far as I know, your surmise that that's impossible is correct. Separate projects, on the other hand, can specify their own toolsets. One project can produce object files with an older toolset, while another project consumes those object files and links them to libraries of more recent vintage by using a later toolset. The most realistic scenarios involve consuming third-party libraries built with different versions of the toolset than are used by your app. This used to be a source of much consternation, when you had to rely on a vendor to supply you with a binary library built using the specific toolset version your app used.
