### ISSUE TITLE
"Sample header file" sample should start with comment stating the name of the file

### ISSUE THREAD

**Issue by AndrewR66** [MicrosoftDocs/cpp-docs#2052]
The last sample should start with a comment stating the name of the file to show that it is a .h file, something like this:
`// sample.h`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99df644-075c-fe3f-3e5a-94cb7f7edde8
* Version Independent ID: 0d48190e-803b-316b-5b79-82245d103c46
* Content: [Header files (C++)](https://docs.microsoft.com/en-us/cpp/cpp/header-files-cpp?view=vs-2019)
* Content Source: [docs/cpp/header-files-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/header-files-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AndrewR66 
Sure, that's an easy fix. I'll give it an \[up for grabs] tag.

**Comment by corob-msft** [comment]
Closed by #2092 - Thanks, @AndrewR66 !
