### ISSUE TITLE
Error in void* pointer example

### ISSUE THREAD

**Issue by tratitude** [MicrosoftDocs/cpp-docs#2053]
This is the example in void* pointers section.
The condition of this for loop causes error.

`for(char* c = static_cast<char*>(pvoid); pvoid < &pvoid + 1000; ++c)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2284bc5b-569d-81ee-0b8d-38c711c92656
* Version Independent ID: d448ee76-816d-67a9-6c1d-19da30933822
* Content: [Raw pointers (C++)](https://docs.microsoft.com/en-us/cpp/cpp/raw-pointers?view=vs-2019#void-pointers)
* Content Source: [docs/cpp/raw-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/raw-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tratitude True enough, that could well cause a run-time error. A fix should appear today.
