### ISSUE TITLE
Can -Wx be overridden by a file-specific "#pragma warning"?

### ISSUE THREAD

**Issue by SRM256** [MicrosoftDocs/cpp-docs#2063]
The pragma warning is supposed to be able to raise or lower warning/error level for specific codes.
https://docs.microsoft.com/en-us/cpp/preprocessor/warning?view=vs-2019
If I use -Wx to elevate all warnings to errors generally, can a specific warning be knocked back down to a warning in a single file using a "#pragma warning" command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abd121e9-da7d-891c-c881-773cb9756aec
* Version Independent ID: cc4a6be7-8eaa-6f09-c32a-631ae4f551bf
* Content: [/WX (Treat Linker Warnings as Errors)](https://docs.microsoft.com/en-us/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=vs-2019)
* Content Source: [docs/build/reference/wx-treat-linker-warnings-as-errors.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/wx-treat-linker-warnings-as-errors.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SRM256 
We try not to repeat ourselves too often, so the answer to your question is found in another article: [Pragmas and compiler options](https://docs.microsoft.com/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=vs-2019#pragmas-and-compiler-options). The short answer is that the most local directive takes precedence.
