### ISSUE TITLE
The directions assume precompiled headers are off, but VS2019 has PCH enabled by derault

### ISSUE THREAD

**Issue by NeilChatterjee** [MicrosoftDocs/cpp-docs#2069]
I think that these institutions are out of date, as they have no reference to the PCH stuff which is created by default when creating a static lib project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@NeilChatterjee 
You're right. The precompiled header defaults for the supported versions of Visual Studio are all over the map. In an effort to simplify the presentation, I've changed the way the templates are used to create the library and the client, so no precompiled headers are used. Updated example code and procedures should appear tomorrow.
