### ISSUE TITLE
A2008 syntax error mov in assembly language

### ISSUE THREAD

**Issue by Usman404912** [MicrosoftDocs/cpp-docs#2070]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd41d08f-f4ef-fbf4-4298-6cc656df14ae
* Version Independent ID: a1217f80-0162-016d-dbd6-668b2af30277
* Content: [ML Nonfatal Error A2008](https://docs.microsoft.com/en-us/cpp/assembler/masm/ml-nonfatal-error-a2008?view=vs-2019)
* Content Source: [docs/assembler/masm/ml-nonfatal-error-a2008.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/ml-nonfatal-error-a2008.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Usman404912 
This sounds like a support issue, not a documentation issue. Have you identified a problem in the A2008 documentation?

**Comment by corob-msft** [comment]
Closing, as there's not enough info to be actionable.
