### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Samboy1990** [MicrosoftDocs/cpp-docs#2074]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559d48f6-eb99-a0b5-b7fc-9051b23dafd9
* Version Independent ID: db20780c-a332-ef6b-1b77-9d3a6fd83342
* Content: [Install cross-platform mobile development with C++](https://docs.microsoft.com/en-us/cpp/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Samboy1990** [comment]
C++

**Comment by corob-msft** [comment]
This feedback doesn't seem actionable. If there's something in the documentation that needs attention, feel free to respond with more details on what you think is missing or incorrect, and I'll reopen the issue.
