### ISSUE TITLE
Support for autotools/automake projects

### ISSUE THREAD

**Issue by l33ds** [MicrosoftDocs/cpp-docs#2075]
Is there support for working with automake projects, meaning that don't have a CMakeLists.txt file but rather configure.ac and Makefile.am.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4535255d-395b-6b11-daf3-b03e0c3ad87d
* Version Independent ID: 1aad5206-ea1e-630c-800a-bb79bbd942b4
* Content: [Create C++ cross-platform projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2019#feedback)
* Content Source: [docs/build/get-started-linux-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/get-started-linux-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@l33ds 
I don't know, but this is a good question to ask on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) boards. If the documentation needs an update, the dev team will let us know.
