### ISSUE TITLE
please fix "BCG" in docs

### ISSUE THREAD

**Issue by pavelc7** [MicrosoftDocs/cpp-docs#2076]
"Add CBCGPWorkspace::ReloadWindowPlacement (pMainFrame)"
"CBCG" should be fixed

hm. But according to https://www.bcgsoft.com/doc/BCGControlBarPro_MFC_Class_Relation.htm
There is no CBCGPWorkspace analog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b54896e-732a-6832-ba4b-99236452b2cf
* Version Independent ID: 446ba2dd-8fe2-cad8-dc7f-b65f37e0352c
* Content: [CMDIFrameWndEx Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmdiframewndex-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cmdiframewndex-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmdiframewndex-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@pavelc7, thank you for catching this. I have updated the documentation and it will be live by tomorrow (6/25)
