### ISSUE TITLE
conformance changes in earlier versions

### ISSUE THREAD

**Issue by TSlivede** [MicrosoftDocs/cpp-docs#2077]
The introduction text links to a few pages with information regarding "conformance changes in earlier versions". However, none of the links point to a table similar to the table on this page but for earlier versions. Is it possible to add a link to the page "[Support For C++11/14/17 Features (Modern C++)](https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140))" in the sentence starting with "For conformance changes in earlier versions, see" and in the "See also" section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C++ language conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TSlivede 
We generally prefer not to link to pages we can't update. The page you're referring to was split into the two current pages, [C++ conformance improvements in Visual Studio](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019) and [Microsoft C++ language conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019). The current table does have all the info for what's supported by version, it's just not in an easy tabular format.

**Comment by TSlivede** [comment]
I can fully understand, that you don't want to link to pages, that are no longer updated. However, the information on that page can currently not found on any of the following pages:

https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance
https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements
https://docs.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio
https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015
https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015

---

For example: In what version of Visual Studio was the Exception specification `noexcept` added? The table on https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140) clearly shows, that it was added in Visual Studio 2015, but I can't find any information about that in the above mentioned pages.

Another example: In what version of Visual Studio was Extended sizeof added? The "old" table shows, that it was added in Visual Studio 2015, but again I can't find any information about that in the above "up to date" pages.

---

Suggestion:    

Could the table from https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140) be added to https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015?

Alternatively: Could a new page (for example) https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-language-conformance-2010-through-2015 be created with the contents of https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)? The reasoning

<a href="https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015" ><blockquote>This information is provided as a convenience in case it might be useful when upgrading from earlier versions of Visual Studio.</blockquote></a>

could apply to that page as well.

**Comment by TSlivede** [comment]
@corob-msft Or should I open a new Issue with that suggestion?
