### ISSUE TITLE
No mention of winmain

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/cpp-docs#2078]
winmain is one of the most well known variations to the standard and should be called out in some form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bcbd9c-deb2-5a1a-d78b-ed4fc551bcc5
* Version Independent ID: 8c3ae6e2-9bd6-bbf4-d80b-a69576a84f8e
* Content: [Arguments to main](https://docs.microsoft.com/en-us/cpp/c-language/arguments-to-main?view=vs-2019)
* Content Source: [docs/c-language/arguments-to-main.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/arguments-to-main.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@henke37 

Interesting idea, but this isn't the right place for a discussion of winmain, as this topic is about the standard language.
