### ISSUE TITLE
Casting pointers to and from integers

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/cpp-docs#2079]
I expect this page to document how pointers and integers interact when typecasted between each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10440523-52d4-720a-82f1-3a24c126497e
* Version Independent ID: b87d2bd4-f0e5-938b-f05d-64c4bf509f4c
* Content: [Arrays and Pointers](https://docs.microsoft.com/en-us/cpp/c-language/arrays-and-pointers?view=vs-2019)
* Content Source: [docs/c-language/arrays-and-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/arrays-and-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@henke37 
This section is based on a (very old) standard language reference, and doesn't speak to that particular issue.
