### ISSUE TITLE
Value of MB_CUR_MAX

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/cpp-docs#2080]
It would be helpful to indicate the value of `MB_CUR_MAX` like other such constants in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a3ad17-c938-ef81-0025-b174447464ae
* Version Independent ID: 7c3109f3-71f1-2e82-b9ca-aeaf685dde11
* Content: [Wide Characters](https://docs.microsoft.com/en-us/cpp/c-language/wide-characters?view=vs-2019)
* Content Source: [docs/c-language/wide-characters.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/wide-characters.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@henke37 
`MB_CUR_MAX` is a macro that's loaded from a CRT internal function, and it doesn't have a fixed value, though the value shouldn't change as long as the effective locale is constant. Depending on various settings, it may have a value between 2 and 5.
