### ISSUE TITLE
Contradictory claims about long double

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/cpp-docs#2082]
The section about long double gives a representation different from unqualified double. Yet the same paragraph says that they have identical representations. This is a clear contradiction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db786e53-8487-b219-e026-85ee869027be
* Version Independent ID: cee6b57e-6832-22fb-2a6f-252b77924916
* Content: [Values](https://docs.microsoft.com/en-us/cpp/c-language/values?view=vs-2019)
* Content Source: [docs/c-language/values.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/values.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by henke37** [comment]
Did I miss the fix for this? The live page still has the issue?

**Comment by corob-msft** [comment]
The publishing queue runs once a day around 11AM Redmond time, so any minute now...
