### ISSUE TITLE
Failure to state rounding direction

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/cpp-docs#2083]
This point is supposed to document the rounding direction. But the rule for which direction that is is at best unclear. "nearest suitable value" depend on the definition of "suitable value", which is not explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bca6a0-f299-5b36-7a68-6cf3b553a660
* Version Independent ID: 4c43c4cd-cd5f-1c52-148b-4fc8c65fd07b
* Content: [Casting Integers to Floating-Point Values](https://docs.microsoft.com/en-us/cpp/c-language/casting-integers-to-floating-point-values?view=vs-2019)
* Content Source: [docs/c-language/casting-integers-to-floating-point-values.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/casting-integers-to-floating-point-values.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@henke37 
The rounding direction is unspecified because it depends on the nearest representable value, which may be larger or smaller than the original value. "Suitable" is another way of saying "representable," as unrepresentable values are unsuitable.
