### ISSUE TITLE
The page for strerror_s isn't clear on what the "numberOfElements" argument is

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/cpp-docs#2086]
The page at https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=vs-2019 lists the second argument to various routines as a `size_t` with the name `numberOfElements`; it's documented as "Size of buffer".

It appears to be the number of elements in the buffer, treated as an array, rather than as the size of the buffer in bytes.  That should be clarified - the two are the same for `strerror_s()` and `_strerror_s()`, as the elements are one-byte `char`s, but are *not* the same for `_wcserror_s()` and `__wcserror_s()`, as the elements are two-byte `wchar_t`s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba2ec2-b636-574d-f749-c3a6060a73dc
* Version Independent ID: ba19e8ab-6b4f-295d-e4e7-ee6a6cb0d302
* Content: [strerror_s, _strerror_s, _wcserror_s, __wcserror_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @guyharris  
I've tried to clarify this by updating the doc to use the actual parameter names, e.g. sizeInBytes, sizeInWords. The functions know the type they take (char vs. wchar) and are doing buffer math according to the size of the elements. So it was technically correct, before, but hopefully matching the parameter names makes it a little clearer.
The update should be live by tomorrow (6/10)
