### ISSUE TITLE
Missing import menu in Visual Studio Mac

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/cpp-docs#2087]
How to import xcode project into Visual Studio on Mac ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64efba6d-c5c4-0417-af9b-38b3873d0c09
* Version Independent ID: c899bef4-849f-803e-a11d-9cabb497a4ec
* Content: [Import an Xcode project](https://docs.microsoft.com/en-us/cpp/cross-platform/import-an-xcode-project?view=vs-2019&source=docs)
* Content Source: [docs/cross-platform/import-an-xcode-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/import-an-xcode-project.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jimicze 
Sorry, there's no way to import an Xcode project into Visual Studio for the Mac. The instructions on this page are for Visual Studio for Windows to build remotely on a Mac running Xcode.
