### ISSUE TITLE
f(S) where S is a typename ?

### ISSUE THREAD

**Issue by Algo-ryth-mix** [MicrosoftDocs/cpp-docs#2088]
```
// Example 2
struct S {
    friend void f(S *);
};
void g() {
    // Using nullptr instead of S prevents argument dependent lookup in S
    f(nullptr); // error C3861: 'f': identifier not found

    S *p = nullptr;
    f(S); // Hidden friend now found via argument-dependent lookup.
}
```

I would assume it should be f(p) instead of f(S) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5dd0404-7b28-63e4-5807-e30610040df1
* Version Independent ID: f96947d7-45bd-e89d-e25e-9fac7c1cc412
* Content: [/permissive- (Standards conformance)](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019#feedback)
* Content Source: [docs/build/reference/permissive-standards-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/permissive-standards-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
A fix should be live sometime today.
