### ISSUE TITLE
I'm not able to find the Assembler ,CC, and link.exe in visual studio 2015

### ISSUE THREAD

**Issue by Mehul-Dhameliya** [MicrosoftDocs/cpp-docs#2090]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139d8805-bfe6-1aa7-c24f-f31afab77b43
* Version Independent ID: ff72cf3f-2332-aa0b-1fad-0ce6bfaf30d3
* Content: [C Language Reference](https://docs.microsoft.com/en-us/cpp/c-language/c-language-reference?view=vs-2015)
* Content Source: [docs/c-language/c-language-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/c-language-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Mehul-Dhameliya** [comment]
I'm not able to find the Assembler ,CC, and link.exe in visual studio 2015 

What is the name in 2010 version and in 2015

for Example In 2010 assembler file :ml.exe 
What will be name for 2015 version  is this the same ?

**Comment by corob-msft** [comment]
@Mehul-Dhameliya 
The names are the same in all versions of Visual Studio for at least the last decade. The x86 assembler is ml.exe, and the x64 assembler is ml64.exe. The ARM assemblers are armasm.exe. The linker is still link.exe, and all versions of the compiler are cl.exe.

The location of these binaries is different depending on the version of Visual Studio. I'd recommend using the `where` command to find them, inside a Developer Command Prompt:

```cmd
>cd %VCINSTALLDIR%
>where /r . cl.exe
```

This should list all the paths to the various versions of the compiler.
