### ISSUE TITLE
inconsistency description on _getpid

### ISSUE THREAD

**Issue by bbap-7fat** [MicrosoftDocs/cpp-docs#2091]
Hi team,

in https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getpid?view=vs-2019, it says : This API cannot be used in applications that execute in the Windows Runtime. For more information, see CRT functions not supported in Universal Windows Platform apps.

But in this page you suggested _getpid as well, so I am confused if _getpid is a good method or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0086976-3992-75a0-5cdc-0202b006a73a
* Version Independent ID: 26a32c12-0c9e-10a9-373c-85bae76e8555
* Content: [CRT functions not supported in Universal Windows Platform apps](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps?view=vs-2019)
* Content Source: [docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bbap-7fat 
The recommendation to use `_getpid` is in error. I'll close this after I fix that shortly.
