### ISSUE TITLE
Need the f**k download url ANYWHERE!!!

### ISSUE THREAD

**Issue by ahdung** [MicrosoftDocs/cpp-docs#2093]
no download, no value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380e8af0-aa0f-d882-d764-ddc02991d537
* Version Independent ID: ac27a8d9-280d-89b6-ed33-8c8fbb80c146
* Content: [Additional MSVC Build Tools](https://docs.microsoft.com/en-us/cpp/build/reference/c-cpp-build-tools?view=vs-2019#feedback)
* Content Source: [docs/build/reference/c-cpp-build-tools.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/c-cpp-build-tools.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ahdung 
The documentation you're looking for is probably in [Download and install the tools](https://docs.microsoft.com/cpp/build/building-on-the-command-line?view=vs-2019#download-and-install-the-tools). All the command-line tools are included in Visual Studio when you install any C++ workload. If you *only* want the command-line tools and libraries, you can install them using [this download](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16). It runs a special version of the Visual Studio Installer that lets you pick the tools and libraries you need.
