### ISSUE TITLE
The documentation for the methods has not been provided

### ISSUE THREAD

**Issue by Nijegorodov** [MicrosoftDocs/cpp-docs#2099]
There are also the following public methods (declared in afxwin.h):
	virtual void LoadTemplate();
	virtual void AddDocument(CDocument* pDoc);
	virtual void RemoveDocument(CDocument* pDoc);
	virtual POSITION GetFirstDocPosition() const;
	virtual CDocument* GetNextDoc(POSITION& rPos) const;
	virtual CDocument* OpenDocumentFile(LPCTSTR lpszPathName, BOOL bMakeVisible = TRUE);
	virtual CDocument* OpenDocumentFile(LPCTSTR lpszPathName, BOOL bAddToMRU, BOOL bMakeVisible);
	virtual void SetDefaultTitle(CDocument* pDocument);

So why don't you include the documentation for these methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998728f8-54a6-0709-9af5-2db2e2535009
* Version Independent ID: 7b791876-df12-150d-fe31-203ceb1a106e
* Content: [CMultiDocTemplate Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmultidoctemplate-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmultidoctemplate-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmultidoctemplate-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @Nijegorodov, 
Regarding CMultiDocTemplate, all of its methods are virtual. The parent class ([CDocTemplate](https://docs.microsoft.com/en-us/cpp/mfc/reference/cdoctemplate-class?view=vs-2019)) documentation should be used.

**Comment by TylerMSFT** [comment]
@Hijegorodov, to make this clearer, I've added a note and link in the member section to take readers to the docs for the inherited functions. That will go live tomorrow (6/25)

**Comment by Nijegorodov** [comment]
And it is a very good idea! Thank you! :)
