### ISSUE TITLE
Support for RFC3339-compatible time zone specifiers (%:z, %::z, %:::z) in strftime?

### ISSUE THREAD

**Issue by mbronk** [MicrosoftDocs/cpp-docs#2100]
Are there any plans to extend the conversion specifiers `strftime()` accepts _(following glibc's implementation)_, to allow representing **time zone** in a `±hh:mm` format, compatible with [RFC-3339](https://tools.ietf.org/html/rfc3339) ?

**Supported today (ISO C):** <-- RFC-3339-incompatible
```
%z     The offset from UTC in the ISO 8601 format "±hhmm" (e.g., -0400)
```

**Proposed extension ([GNU](https://github.com/coreutils/gnulib/commit/c0e63657aced0f505bab0d91a2d5db472d7d1013 ))**
```
%:z    The offset from UTC in the ISO 8601 format "±hh:mm" (e.g., -04:00)
%::z   The offset from UTC in the ISO 8601 format "±hh:mm:ss" (e.g., -04:00:00)
%:::z  The offset from UTC in the ISO 8601 format, with : up to the necessary precision (e.g., -04, +05:30) 
```
---------
**Details:**

The ISO C99-specified **%z** conversion specifier outputs a time zone in a `±hhmm` format, which, while permitted by ISO-8601, does not allow to format a time zone into `±hh:mm`, making it incompatible with widely adopted RFC-3339.
A practical consequence is the inability use standard libraries' formatting implementation in scenarios when RFC-formatting is required (notably: as an [XML date time](https://www.w3schools.com/xml/schema_dtypes_date.asp) - `xs:dateTime`)

**Examples:**
```
|   Format specifier   |        Example            |
|----------------------|---------------------------|
|   %FT%T%z            | 2020-04-15T11:34:22+0200  |   <- ISO C99, incompatible w/ RFC-3339
|   %FT%T%:z           | 2020-04-15T11:34:22+02:00 |   <- GNU extension (unsupported today)
```
  _Note that while both are ISO-8601 compatible, only the 2nd also complies with RFC-3339._

**Resources:**

* While most high-level programming languages do work around this on an above-stdlib layer and support RFC-3339 formats, it should be noted that, the GNU implementation of C stdlib, introduced an extension adding new format specifiers (in 2005): https://github.com/coreutils/gnulib/commit/c0e63657aced0f505bab0d91a2d5db472d7d1013 

* The GNU **date** tool supports the new format since circa 2015. Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799479 for more context and discussion on the change

* [strfrime in Rust::chrono](https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html) - allows for: `%:z`
* [Some discussion on comp.lang.c - dated 2000](https://groups.google.com/d/msg/comp.std.c/TwSByJpG85Q/xgho3kXkoG4J) regarding possible inclusion of `%:z`-like specifier into the standard _(seems not to have been added up to and including C18)_

[Edit] Added new reference (above)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192d5630-230a-efb2-1d88-f21a53c8a55f
* Version Independent ID: 1b52b050-4081-04cf-525f-7dafa4882e51
* Content: [strftime, wcsftime, _strftime_l, _wcsftime_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by mbronk** [comment]
On a separate note, the [current documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2019) is ambiguous in the description of `%z`: 
> |**%z**|The offset from UTC in ISO 8601 format; no characters if time zone is unknown|

"**ISO 8601 format**" is, unfortunately, vague and matches both `+mmhh` and `+mm:hh` (plus a few others). Please add a concrete format definition.

**Comment by TylerMSFT** [comment]
Thanks @mbronk . I'll look into this and get back to you.

**Comment by TylerMSFT** [comment]
Hi @mbronk, 
There are no plans to support this. It needs to be voted in before our library team says they will look at it.

**Comment by mbronk** [comment]
Hi @TylerMSFT ,
What about my 2nd comment (re: doc ambiguity). Any chances for getting the description clarified?
