### ISSUE TITLE
incomplete and hard to understand

### ISSUE THREAD

**Issue by wonkoRT** [MicrosoftDocs/cpp-docs#2101]
I struggle to understand what the above sentence "When a postfix operator is applied to a function argument, the value of the argument is not guaranteed to be incremented or decremented before it is passed to the function. See section 1.9.17 in the C++ standard for more information." exactly tries to say and to which version of the standard it refers to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0fb45d8-cdb3-f736-ad53-56791efbc5f9
* Version Independent ID: 7e885863-dbf7-2c68-7197-616277d03b12
* Content: [Postfix Increment and Decrement Operators: ++ and --](https://docs.microsoft.com/en-us/cpp/cpp/postfix-increment-and-decrement-operators-increment-and-decrement?view=vs-2019#feedback)
* Content Source: [docs/cpp/postfix-increment-and-decrement-operators-increment-and-decrement.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/postfix-increment-and-decrement-operators-increment-and-decrement.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wonkoRT 
I agree, that's a clunky sentence. Basically, what it's saying is, don't expect portable, consistent behavior when you apply postfix ++ or -- to a function argument.

The Standard referred to is C++98, and the paragraph in question is about the sequence of operations when a function is called. That standard doesn't specify everything about when argument post-evaluation side-effects occur. Later standards (for example, C++11 in section 1.9.15) clarify that post-evaluation side effects and value computations do occur before the function is called - but the argument expressions are unsequenced and the order of argument evaluation is unspecified. That means it's really easy to create undefined behavior when you call a function:

```cpp
#include <iostream>
void fn(const int arg1, const int arg2)
{
    std::cout << "arg1 " << arg1 << ", arg2 " << arg2 << std::endl;
}
int main()
{
    int a = 0;
    fn(a++, a++); // What will arg1 and arg2 be? It's undefined. Don't do this!
}
```

That doesn't mean it will crash, it just means that if arg1 and arg 2 are both 0, both 1, both 2, or they're a mixture of any of those values, don't act surprised. Microsoft C++ appears to set arg1 to 0 and arg2 to 1 when I try the sample for x86, but that might depend on the calling convention or the processor.

**Comment by wonkoRT** [comment]
Thanks for the clarification, the example and for specifying the standard! Now i see from where (or what time) this is coming from.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
