### ISSUE TITLE
Limitations of /Fo

### ISSUE THREAD

**Issue by billyquith** [MicrosoftDocs/cpp-docs#2102]
If you specify multiple files for compilation, I believe you cannot use /Fo. This is not mentioned in the documentation. 

Can I, alternatively, specifiy a directory, into which I want my intermediates to go? This isn't mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca1e187-dfc2-3988-c184-845a66930ce1
* Version Independent ID: a4cdc0a2-9b78-9457-62ab-67ef1f135ab5
* Content: [/Fo (Object File Name)](https://docs.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=vs-2019#feedback)
* Content Source: [docs/build/reference/fo-object-file-name.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fo-object-file-name.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@billyquith 
The quick answer is, yes, you can specify a directory. All the object files will have the usual names, but go in the specified directory. That's how Visual Studio projects put the object files into an intermediate build directory.

**Comment by billyquith** [comment]
Thanks for the reply. It would be nice to have this information in the docs.

I can't remember what I tried now. I ended up invoking the compiler from the intermediate directory and everything with absolute paths. These seemed to work.

**Comment by corob-msft** [comment]
An updated topic should appear tomorrow.
