### ISSUE TITLE
What are the exact definitions of these predefined environments?

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/cpp-docs#2108]
What exact env variables are defined in these predefined environments??

linux_arm: Target ARM Linux remotely.
linux_x64: Target x64 Linux remotely.
linux_x86: Target x86 Linux remotely.
msvc_arm: Target ARM Windows with the MSVC compiler.
msvc_arm_x64: Target ARM Windows with the 64-bit MSVC compiler.
msvc_arm64: Target ARM64 Windows with the MSVC compiler.
msvc_arm64_x64: Target ARM64 Windows with the 64-bit MSVC compiler.
msvc_x64: Target x64 Windows with the MSVC compiler.
msvc_x64_x64: Target x64 Windows with the 64-bit MSVC compiler.
msvc_x86: Target x86 Windows with the MSVC compiler.
msvc_x86_x64: Target x86 Windows with the 64-bit MSVC compiler.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4417dbbb-58ad-4417-3a96-c1cb40516ca2
* Version Independent ID: cb5427c7-ee24-c972-bc44-ff890621cbf9
* Content: [CMakeSettings.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2019#environments)
* Content Source: [docs/build/cmakesettings-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmakesettings-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@congkun-ck 
This is not the sort of thing we'd document. Have you tried using the `SET` command?

**Comment by congkun-ck** [comment]
These are Linux remote envs, they are not the same as traditional local envs, and there is no correspondent "Developer Command Prompt" for them. The doc is absolutely confusing.
linux_arm: Target ARM Linux remotely.
linux_x64: Target x64 Linux remotely.
linux_x86: Target x86 Linux remotely.

Anyway I figured it out myself: they defined nothing.
