### ISSUE TITLE
[Technical issue] About C++ decoration name of __cdecl call type

### ISSUE THREAD

**Issue by dragon-archer** [MicrosoftDocs/cpp-docs#2114]
In this document, it says `__cdecl` means to `@@ZA`,
but in [this doc](https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=vs-2019), it says `__cdecl` means to `@@YA`,
and, I test this in Visual Studio 2019 (with VC version 14.25.18610, cl version 19.25.28612), it reports `__cdecl` means to `@@YA`,
I also test this in `undname` , it accept both of `@@YA` and `@@ZA`,
so, which is correct, or which is preferred. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09cc2c09-c8d6-7fa6-69b6-653ef7870810
* Version Independent ID: 60830da6-27dc-63e9-b1b9-478f96d184ff
* Content: [Name Decoration](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/name-decoration?view=vs-2019)
* Content Source: [docs/error-messages/tool-errors/name-decoration.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/name-decoration.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dragon-archer 
That's a good question. The answer is, we don't document the name decoration scheme beyond what you've observed. That's not to say there isn't a specification, just that it hasn't been given to the docs team to share. So, if both results are possible, and `undname` accepts both, then both appear to be correct. I don't have enough info to say one form is preferable, or what circumstances might cause one or the other to be generated. It's possible that asking this question on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) might result in a more satisfactory answer.
