### ISSUE TITLE
Mistake in shutdown

### ISSUE THREAD

**Issue by kevinkuan0** [MicrosoftDocs/cpp-docs#2117]
I believe the code in Shutdown(void) is wrong.
ReleaseMutex(hRunMutex); was called multiple times when once is enough to signal all others threads to exit.
Instead, the KbdFunc thread should call WaitForMultipleObjects on all thread handles, before clearing the screen and closing all mutexs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0606b080-f262-a922-2888-aa47a1ec75bd
* Version Independent ID: 8cebbc8f-5c27-7151-6681-581534874f4a
* Content: [Sample Multithread C Program](https://docs.microsoft.com/en-us/cpp/parallel/sample-multithread-c-program?view=vs-2019#feedback)
* Content Source: [docs/parallel/sample-multithread-c-program.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/sample-multithread-c-program.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
Dup of #2116
