### ISSUE TITLE
The source code is wrong.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2119]
@jinwho commented on [Tue Apr 21 2020](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/issues/987)

https://docs.microsoft.com/ko-kr/cpp/cpp/raw-pointers?view=vs-2019#initialization-and-member-access
If you look here, func_A (mc); When calling like this, mc is MyClass type and sends MyClass * as an argument of a function.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2284bc5b-569d-81ee-0b8d-38c711c92656
* Version Independent ID: d448ee76-816d-67a9-6c1d-19da30933822
* Content: [원시 포인터(C++)](https://docs.microsoft.com/ko-kr/cpp/cpp/raw-pointers?view=vs-2019#initialization-and-member-access)
* Content Source: [docs/cpp/raw-pointers.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/raw-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Tue Apr 21 2020](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/issues/987#issuecomment-617233168)

Hello, @jinwho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@CeciAc  Fix in source document should be published tomorrow.
