### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/cpp-docs#2120]
The following bullet point links leads to 404s:

>[`Windows::Foundation::Collections::IObservableVector`](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.IObservableVector_T_) and [`Windows::Foundation::Collections::IObservableMap`](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.IObservableMap_K_V_) define events that are fired...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd8121b-7e03-669e-fa70-3c003c442436
* Version Independent ID: 2c19ee26-24c7-1cf7-42f7-91ae3b30f56e
* Content: [Collections (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/collections-c-cx?view=vs-2019#feedback)
* Content Source: [docs/cppcx/collections-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/collections-c-cx.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@keparanj 
Good catch, the fix should appear tomorrow sometime.
