### ISSUE TITLE
Function CASyncSocket::CreateEx() is not documented

### ISSUE THREAD

**Issue by erwanh1112** [MicrosoftDocs/cpp-docs#2121]
THis function is necessary to create sockets for IPv6. See an example on https://stackoverflow.com/questions/51503540/socket-programming-with-mfc. It would be helpful to document IPv6 sockets creation here, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c11b2e5-1be9-8d75-a063-8e5c769ec7b0
* Version Independent ID: 533b7b93-3e56-787e-6c39-f346e2104ab0
* Content: [CAsyncSocket Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/casyncsocket-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/casyncsocket-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/casyncsocket-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @erwanh1112, 
The reason that this isn't documented is that it doesn't exist in the MFC source code. Our MFC engineer took a look and the method isn't there.

**Comment by erwanh1112** [comment]
Here is the implementation of  CAsyncSocket::CreateEx() in afxsock.h line 341:

inline BOOL CAsyncSocket::CreateEx(ADDRINFOT* pAI, long lEvent) {
	if (pAI == NULL) 	{
		WSASetLastError(WSAEINVAL);
		return FALSE;
	}
	return Socket(pAI->ai_socktype, lEvent, pAI->ai_protocol, pAI->ai_family);
}

Here is a program that uses this function: [Socket_v6.zip](https://github.com/MicrosoftDocs/cpp-docs/files/4830193/Socket_v6.zip)

But this function is not documented

**Comment by TylerMSFT** [comment]
@erwanh1112, I have a message out to our MFC engineer to see what the situation is.

**Comment by TylerMSFT** [comment]
@erwanh1112, thanks for hanging in there on this one. I have added the function to the docs. Should be live by Monday (6/29)
