### ISSUE TITLE
Please clarify

### ISSUE THREAD

**Issue by mgcst99** [MicrosoftDocs/cpp-docs#2123]
"you can link an app compiled using the 2017 toolset to a static library compiled using 2019, if they're linked using the 2019 toolset" does not make sense, and the response by corob-msft to the previous comment didn't clear it up for me. Please rewrite the sentence to indicate what "they" is referring too, and include examples of what will and won't work. Can a 2017 built app link in a 2019 built static library? Can a 2017 built app link to a 2019 built third party DLL installed on the target machine? If not, can a 2017 built app link not link to a 2019 built third party app, but can dynamic link to the 2019 built CRT ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcccbfe4-34d9-67cb-efbb-6c15ff35b38e
* Version Independent ID: cc082cbf-a967-6709-f3ef-190e78cf84e9
* Content: [C++ binary compatibility 2015-2019](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019#feedback)
* Content Source: [docs/porting/binary-compat-2015-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/binary-compat-2015-2017.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mgcst99 

In this case, "they" refers to "an app compiled using the 2017 toolset" and "a static library compiled using 2019". To address your last three questions, the answers in order are yes, it depends, and I can't tell what you're asking, but yes to the last part.

> Can a 2017 built app link in a 2019 built static library?

If your apps and libraries (both static libraries and import libraries for implicitly linked DLLs) were built using any of VS 2015, 2017, or 2019, you can link them together. You must link them together using a toolset version *greater than or equal to* the latest toolset used to build any of the component parts. Let's say you have three binaries to link together. They were built using toolsets from VS 2015 version 14.3, VS 2017 version 15.1, and VS 2017 version 15.6, respectively. You can link them using any toolset version greater than or equal to 15.6.

> Can a 2017 built app link to a 2019 built third party DLL installed on the target machine?

I'm assuming you're talking about [implicit linking](https://docs.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=vs-2019#implicit-linking), the sort where you have an import library for the DLL you want to link to at load time, and not [explicit linking](https://docs.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=vs-2019#explicit-linking) where you load a DLL during runtime using `LoadLibraryEx` or similar. The *linking* part gets an unqualified Yes answer. The *loading* part might be what you really want to know.

If you link an app to an import library for a DLL, following the toolset version rules above, the DLL on the client machine that gets loaded when your app starts must be *ABI compatible* with the import library. (ABI compatibility does *not* depend on the toolset version used to compile your app, or the toolset version used for linking the app and the import library.) Normally, ABI-compatible means either the DLL on the client has a version that's equal to the import library version, or if it's an earlier or later version of the DLL, the ABI contract hasn't changed. It doesn't matter if it's your DLL, a Microsoft DLL, or a third-party DLL. All that matters is the ABI contract. The answer depends on the DLL. Your app's installer should include the third-party DLL you need, and implement logic to install it depending on whether there's already a compatible DLL installed.

> If not, can a 2017 built app link not link to a 2019 built third party app,

This part of your question confused me.

> but can dynamic link to the 2019 built CRT ?

You can safely update the Redistributables on a client machine to any version that's at least as recent as your apps and libraries. The ABI contract for the UCRT and other runtime libraries that ship in Visual Studio 2015 through 2019 is guaranteed to be backward compatible. That means later UCRT versions may implement new functions, but all existing functions will continue to work for all your binaries built by any toolset from VS 2015 on.

**Comment by mgcst99** [comment]
Thanks so much for your response. Replies inline.

**Comment by AA11BB22** [comment]
Following up on,

> Can a 2017 built app link to a 2019 built third party DLL installed on the target machine?

It seems it's fine as long as they're ABI compatible?
However, this contradicts [this statement](https://github.com/MicrosoftDocs/cpp-docs/issues/374#issuecomment-424146636).

Here are some of my examples, maybe this will help? Which of these are good/bad.
The functions are exported by a .dll compiled with 2019 toolset to be consumed by a .exe compiled with 2017 toolset.

1. C mangling, (assume does not throw any exception)
`extern "C" __delspec(dllexport) void f1(int32_t x);`

2. C++ mangling, (assume does not throw any exception)
`__declspec(dllexport) void f2(int32_t x);`

3. C++ mangling with exception, throws an object with stable ABI like `int`.
`__declspec(dllexport) void f3(int32_t x);  // Throws int`

4. C++ mangling with exception, throws a hopefully compatible `std::exception`, cause ... that's the recommendation way. Ignore the case where `std::exception` is incompatible, this is an obvious ABI break.
`__declspec(dllexport) void f4(int32_t x);  // Throws std::exception or a derivative`

Is the said statement incorrect? Or what are the corner cases where *it is not guaranteed to be compatible*.

**Comment by corob-msft** [comment]
@AA11BB22 
It's rare that you'd keep object files from an older build around and link them by using a later toolset to a newer DLL's import library - but it should work if you do. More commonly, you'd rebuild your executable from sources with the newer toolset, and then link the new object files to the new DLL. 

If the question is, can an existing, unchanged 2017 executable use a 2019 DLL without being linked again, then the answer is maybe, but it's not guaranteed. There can't have been any ABI-breaking changes in the DLL or the way it gets built. If there aren't any, then it should work. For guaranteed compatibility, rebuild.

There haven't been any changes to name mangling for existing types. There have been new types added to C++ binaries that you can export, with new mangling. Older binaries will not recognize these types, but they weren't built to call them, so it doesn't matter. Newer binaries can of course link to any older binaries.

It's not a good idea to throw an exception from a DLL to be caught by a client in any case, even if the build toolsets are identical. Exceptions should not leave a DLL. See Sutter and Alexandrescu's [C++ Coding Standards](http://www.gotw.ca/publications/c++cs.htm) item 62.

**Comment by AA11BB22** [comment]
I was mainly referring to
> If the question is, can an existing, unchanged 2017 executable use a 2019 DLL without being linked again, then the answer is maybe, but it's not guaranteed.

As for exceptions, I'm aware it's not recommended to propagate through dll/module boundaries, but error codes, expected<T> or result<T> are too much of a hassle. Having to write a inline C++ thin wrapper for EVERY function just to rethrow the error doesn't bode well with me, especially since the dll internally will use exceptions (a lot), catching them just to return an error, just to be rethrown again seems really redundant. Maybe I could just cheese it when the build environment is exactly the same.

Nevertheless, appreciate the clarification.

**Comment by AA11BB22** [comment]
@corob-msft oh, i forgot one last thing, how does msvc toolset integrate with the llvm/clang (downloaded or built from src)?

Does the same rules apply?, an .exe compiled with 2017 using a .dll compiled with clang, i.e., not guaranteed to work?

Also, whatabout the clang version that can be installed through visual studio installer?

**Comment by corob-msft** [comment]
@AA11BB22 
I know you can build with clang/llvm in VS by using the CMake build system. I don't know if its objects are linkable with MSVC objects by default. Maybe there are some compatibility switches that can make it work? DLLs, on the other hand, can make ABI contracts that are independent of the implementation language or toolset version, so you can call DLLs written in Python or Pascal from C++ executables and vice-versa. That level of interface will work just fine. The usual caveats apply: don't pass internal state, don't hand off ownership, don't rely on structure layout, use `extern "C"` for data and function declarations, and so on.

**Comment by AA11BB22** [comment]
I see, those were my initial thoughts before reading this doc, wasn't expecting toolset played any role in dynamic libraries.

Definitely need clarification on which/what components (language, linkage, etc) are actually dependent on the toolset in the doc.
