### ISSUE TITLE
Wrong example of ASan options

### ISSUE THREAD

**Issue by ssenchenko** [MicrosoftDocs/cpp-docs#2127]
The example of Asan options doesn't work.
The options string should have no semicolons because arguments are parsed based on spaces and a semicolon is attached to the previous value. Should be like this:
detect_leaks=0 leak_check_at_exit=true detect_deadlocks=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96add46-2399-7254-c20e-fb1c987bbec9
* Version Independent ID: 04d6223f-fd3c-8ef7-2d1c-6a3eba619cbc
* Content: [Configure Linux projects to use Address Sanitizer](https://docs.microsoft.com/en-us/cpp/linux/linux-asan-configuration?view=vs-2019#feedback)
* Content Source: [docs/linux/linux-asan-configuration.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/linux-asan-configuration.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @ssenchenko,
I've updated the topic. The fix will go live by Monday evening (9/28)
