### ISSUE TITLE
I believe that the default case is described the wrong way round

### ISSUE THREAD

**Issue by Dirksche** [MicrosoftDocs/cpp-docs#2128]
This page states "The default causes the constructor to call AddRef on a non-null IErrorInfo interface.".
I believe this is the wrong way round and should actually be "The default causes the constructor to not call AddRef on a non-null IErrorInfo interface.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe35be2-3626-287a-b1f3-d9263d0ced08
* Version Independent ID: b9e0169f-9a9a-93af-f54f-44fd7e2ac0b5
* Content: [_com_error::_com_error](https://docs.microsoft.com/en-us/cpp/cpp/com-error-com-error?view=vs-2017#feedback)
* Content Source: [docs/cpp/com-error-com-error.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/com-error-com-error.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
A fix is in the works for publishing tomorrow.
