### ISSUE TITLE
"ARM64 Exception Handling" is missing

### ISSUE THREAD

**Issue by hyln9** [MicrosoftDocs/cpp-docs#213]
It will be great to see how asynchronous exceptions are handled by Windows on ARM64.

**Comment by corob-msft** [comment]
I haven't heard about anything ARM64-specific from the dev team. I'll look into this. It might take a while.

**Comment by corob-msft** [comment]
I forgot to come back to this issue after updating the docs a couple of weeks ago. Check out [ARM64 exception handling](https://docs.microsoft.com/en-us/cpp/build/arm64-exception-handling) and related topics in the links for details.

**Comment by hyln9** [comment]
Thanks!
