### ISSUE TITLE
C++ Standard Library header files list includes non-standard header files

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/cpp-docs#2130]
See #2096 for details and suggestions.

(If that issue could also be re-opened, that would be great - the removed header isn't particularly clear in the current state).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3f34a7-062a-f199-f31e-d35e0444d9be
* Version Independent ID: 5fba6de8-b958-f9e7-b0b6-059ec6ac8cf6
* Content: [C++ standard library header files](https://docs.microsoft.com/en-us/cpp/standard-library/cpp-standard-library-header-files?view=vs-2019#feedback)
* Content Source: [docs/standard-library/cpp-standard-library-header-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/cpp-standard-library-header-files.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I reopened 2096. Closing this as it was a request to reopen 2096, which is done.
