### ISSUE TITLE
C6385

### ISSUE THREAD

**Issue by bghaemi1379** [MicrosoftDocs/cpp-docs#2131]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1d6c74-a51c-b51b-17a8-23ec1c2f68e1
* Version Independent ID: d7a63ea5-0aa0-bd24-1e04-7f5a0b51037c
* Content: [C6385](https://docs.microsoft.com/en-us/cpp/code-quality/c6385?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C6385)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/code-quality/c6385.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6385.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closed because the report doesn't appear to contain anything actionable.
