### ISSUE TITLE
More info in table for `_MSC_VER`

### ISSUE THREAD

**Issue by TSlivede** [MicrosoftDocs/cpp-docs#2132]
Visual studio version numbers are really confusing.

Currently, the description table for `_MSC_VER` lists the "friendly name" and the version number of visual studio. Could the table also list the corresponding "toolset version"?

I'd suggest to add a column to the table that contains text similar to the VS installer, for example `MSVC v142 - build tools v14.21`
[(The installer shows "`MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)`")](https://devblogs.microsoft.com/cppblog/wp-content/uploads/sites/9/2019/08/Install-SxS-Toolsets-Annotated.png)

The "term" `v142` is important because it is sometimes needed as an argument for commandline build systems (e.g. cmake) and the "term" `v14.21` is necessary to show the *full* version number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TSlivede** [comment]
Alternatively, without adding a new column, the content of the left column could be changed from something like `Visual Studio 2019 version 16.1` to    
`MSVC v142 - Visual Studio 2019 version 16.1 C++ build tools (v14.21)`

**Comment by TylerMSFT** [comment]
I recently updated this table. It may address your concerns.
