### ISSUE TITLE
message() method - only "happy path" is documented

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/cpp-docs#2134]
&gt; **Returns**
&gt;
&gt; Returns a descriptive name of the error code val for the category.

...and what does it return in the case of an unrecognized error value? Should I rely on this to give me a human-readable string that I can display to a user, or do I need to check for empty string (or similar), and construct my own fallback message (e.g. "error code = 0x08X")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a611dcda-62fe-fd47-73fb-7a5aa9747b2e
* Version Independent ID: a6480951-1c45-c782-4de3-5de0b6cd5559
* Content: [error_category Class](https://docs.microsoft.com/en-us/cpp/standard-library/error-category-class?view=vs-2017#message)
* Content Source: [docs/standard-library/error-category-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/error-category-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @mr-intj, it returns "unknown error" in that case. I've updated the doc and the update will be live by tomorrow (6/25).

**Comment by mr-intj** [comment]
Thank you sir!  :-)
