### ISSUE TITLE
cppgdb not available in 16.6 4

### ISSUE THREAD

**Issue by Stricklyspeaking** [MicrosoftDocs/cpp-docs#2135]
I am looking for cppgdb described here in this webpage. I am running VS 16.6 Version 4. I have looked a Configuration Options and then added a new configuration When I select Configuration Type I see debug, release, RelwithDebinfo, MinSizeRel.

I want to add a command line argument to the be included when debug starts my application on a remote Linux machine. This Web page looks like exactly what I need but I can not see how to implement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7a4e8b-d422-93b1-e042-55c2acbf8ef3
* Version Independent ID: 0d55f5d8-846e-3282-b580-9b7770053958
* Content: [Configure CMake debugging sessions in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=vs-2019#feedback)
* Content Source: [docs/build/configure-cmake-debugging-sessions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configure-cmake-debugging-sessions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Stricklyspeaking 
There isn't a 16.6 version 4 yet. The current release, 16.5.4, and 16.6 Preview 3 are available. [A bug in the cppgdb configuration is fixed in 16.6 Preview 3](https://developercommunity.visualstudio.com/content/problem/967036/template-type-cppdbg-added-instead-of-cppgdb.html). Is this the issue you're seeing?

**Comment by esweet431** [comment]
@Stricklyspeaking
It sounds like you're looking at CMakeSettings.json, which is a separate json file where you configure CMake invocation and build. This page describes the options available in launch.vs.json, which is where you configure debug sessions. To create a launch.vs.json file you can right-click on the root CMakeLists.txt in the Solution Explorer and select "Add new debug configuration." The other entry points to this file are described at the top of this page.

**Comment by TylerMSFT** [comment]
Closing. Don't see further action to take.
