### ISSUE TITLE
Does strtod or wcstod invoke invalid parameter handler when overflow or underflow occurs?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2136]
@miimou commented on [Fri Apr 24 2020](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/229)

In the section "Return Value", this document says that wcstod and strtod set errno to ERANGE if overflow or underflow occurs *and* the invalid parameter handler is invoked.
&gt; *wcstod* returns values analogously to *strtod*. For both functions, *errno* is set to *ERANGE* if overflow or underflow occurs and the invalid parameter handler is invoked, as described in Parameter Validation.
It implies overflow or underflow may invoke invalid parameter handler, and errno is set only when invalid parameter handler invoked.

But,
* strtod does not invoke invalid parameter handler for overflow or underflow (for cases I tested).
* when overflow or underflow occurs, errno is set to ERANGE whether the invalid parameter handler called or not.

And,
* strtod does call invalid parameter handler when pointer passed as strSource is NULL.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0656f7f5-94a4-e2cd-c0ff-7949a271dd45
* Version Independent ID: 7f8311a0-098a-d03e-d215-61c00c88966e
* Content: [strtod、_strtod_l、wcstod、_wcstod_l](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

---

@srvbpigh commented on [Sat Apr 25 2020](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/229#issuecomment-619333488)

Hello, @miimou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by TylerMSFT** [comment]
@CeciAc, you are correct. I have updated the document to untangle invalid parameters from overflow/underflow.
The change should be live by tomorrow (6/25)
