### ISSUE TITLE
#89

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2138]
@OldFaggotGeek commented on [Sat Apr 25 2020](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/91)

https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/89 - closed by writing a template "unsubscribe", but the description of the first example is still nonsense!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a000dbf7-4ebd-8227-41c8-343c8f8a3af5
* Version Independent ID: 38e5a6ab-69ef-8f16-a828-c0f01e297393
* Content: [Оператор switch (C)](https://docs.microsoft.com/ru-ru/cpp/c-language/switch-statement-c?view=vs-2019#feedback)
* Content Source: [docs/c-language/switch-statement-c.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-language/switch-statement-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Sat Apr 25 2020](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/91#issuecomment-619354456)

Hello, @OldFaggotGeek
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@CeciAc 
I made an update to the article, which should be translated now. I know some words and formatting are fixed. Unfortunately, I don't know more than three or four phrases in Russian, so I can't tell if the article makes sense. Can you get a confirmation before I close this issue?

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, how old it is, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
