### ISSUE TITLE
Another cause

### ISSUE THREAD

**Issue by sdgMihai** [MicrosoftDocs/cpp-docs#2144]
Hello!
There is also the probability that the dependencies are causing the error. Consider the case of a dynamic library based on a c code file.c and an file.h, where file.c has missing
definitions of functions declared in file.h. That fires U1073 in connection with /implib:file.lib. After the implementation of all functions declared in file.h are finished within file.c, the error disappears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 420c997a-993d-3da9-c23c-28c532adcba9
* Version Independent ID: 5d0ad491-576b-3e78-6541-535d09bf6dec
* Content: [NMAKE Fatal Error U1073](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/nmake-fatal-error-u1073?view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/nmake-fatal-error-u1073.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/nmake-fatal-error-u1073.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
