### ISSUE TITLE
Can the same marshal_context object be used to marshal multiple strings?

### ISSUE THREAD

**Issue by cschreib-ibex** [MicrosoftDocs/cpp-docs#2151]
See title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91624358-e8b2-ab8a-3060-03838bfe66ca
* Version Independent ID: 8f091c62-0cb1-1880-5e21-7d361e05cb55
* Content: [marshal_context Class](https://docs.microsoft.com/en-us/cpp/dotnet/marshal-context-class?view=vs-2019#feedback)
* Content Source: [docs/dotnet/marshal-context-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/marshal-context-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@cschreib-ibex 
According to the second paragraph of the **Remarks** section, the same `marshal_context` object can be reused to marshal any number of objects, which presumably includes strings.
