### ISSUE TITLE
No macro for number of threads?

### ISSUE THREAD

**Issue by Michaelangel007** [MicrosoftDocs/cpp-docs#2160]
I see $(NUMBER_OF_PROCESSORS) but where is the macro for Tools &gt; Tools Options &gt; Projects and Solutions&gt; Build And Run &gt; maximum number of parallel project builds??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46cf831-faea-6357-0e06-3284f114c879
* Version Independent ID: 0345affe-ce33-c438-d3e4-d134f905d084
* Content: [Common macros for MSBuild commands and properties](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2019#feedback)
* Content Source: [docs/build/reference/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Michaelangel007 
As far as I've been able to find out, the maximum number of parallel project builds isn't directly exposed as a macro. There are related-looking values such as $(MultiProcMaxCount) and $(ToolTaskCount), but these don't reflect the value in the Tool Options dialog. Sorry. You might have better luck asking on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html).
