### ISSUE TITLE
C3905 when using __n128

### ISSUE THREAD

**Issue by mtl1979** [MicrosoftDocs/cpp-docs#2161]
Unaligned accesses using NEON vector types used to work with Visual C++ 2015 but don't work with Visual C++ 2017.9 or 2019 even though ARM has separate instructions for unaligned reads and writes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89813d74-d85f-94f7-aab5-df89245715e9
* Version Independent ID: 6e6bf3e2-589e-8c07-50b1-63358462628f
* Content: [Compiler errors C3500 through C3999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-errors-c3500-through-c3999?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-errors-c3500-through-c3999.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-errors-c3500-through-c3999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mtl1979 
If the product behavior has changed, then this sounds like a product issue, not a documentation issue. You can use the feedback control at the bottom of the page to send product feedback, or go to the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site for questions and solutions. If the error needs to be elaborated on in docs, the engineering team will let the docs team know.
