### ISSUE TITLE
GetFileURL() returns only path

### ISSUE THREAD

**Issue by Chrisbpy** [MicrosoftDocs/cpp-docs#2166]
The Remarks are misleading as they indicate that it should return the entire file path similar to CFileFind::GetFilePath().  It does not, it only returns the path component.  In the above example it only returns "ftp://moose/dir"

Tested on VS2013 & VS2019 host OS Windows 10 1909

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8ea15-d03a-683c-7f59-8554c88d259d
* Version Independent ID: 6dd4cd6c-6679-803e-e20e-4d8025d9416e
* Content: [CFtpFileFind Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cftpfilefind-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cftpfilefind-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cftpfilefind-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @Chrisbpy.  Fixed. Should be live by tomorrow (5/29)
