### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/cpp-docs#2169]
There is a typo where it says "Build Systems and Projects". I think it should say 

You make settings in a build configuration file(s), and the build system accepts that file as input before it invokes the compiler.

You guys put "invoke". lol. oops?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8973bd-ab25-4497-e05b-e690fe6060d5
* Version Independent ID: ebc36c82-e305-d5e1-ac17-3c55e2944d56
* Content: [C/C++ projects and build systems in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/projects-and-build-systems-cpp?view=vs-2019)
* Content Source: [docs/build/projects-and-build-systems-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/projects-and-build-systems-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by KishkinJ10** [comment]
sir I am a beginner can I work on this ? can you guide me what should I do??

**Comment by corob-msft** [comment]
@KishkinJ10 
Yes, you're welcome to submit a PR to fix this issue. There's an introduction in our [Microsoft Docs contributor guide overview](https://docs.microsoft.com/contribute/) that explains the steps to follow for quick edits to existing documents. Mention #2169 in your comments, so the PR gets linked to this issue. Thanks for asking, and for contributing!

**Comment by KishkinJ10** [comment]
Sir kindly check the PR and Guide me if I am wrong.

**Comment by corob-msft** [comment]
Thanks to @KishkinJ10 for submitting a fix. This content should appear tomorrow after going through our publishing process.
