### ISSUE TITLE
Hi again

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/cpp-docs#2170]
here's another typo at Code style enforcement with ClangFormat and EditorConfig:

"ClangFormat, however, has a more style options than EditorConfig,"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68da5bbf-1ea4-65a2-1032-672bd632bac8
* Version Independent ID: ccf8eb50-c15a-8be3-63e7-d712e0f25f27
* Content: [Edit and refactor C++ code in Visual Studio](https://docs.microsoft.com/en-us/cpp/ide/writing-and-refactoring-code-cpp?view=vs-2019#feedback)
* Content Source: [docs/ide/writing-and-refactoring-code-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/writing-and-refactoring-code-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Fixed. Thanks, @Rixius44. Should be live by tomorrow (5/29)
