### ISSUE TITLE
CComboBox::GetLBText(int nIndex, CString& rString) throws exception when index is invalid

### ISSUE THREAD

**Issue by tobias-loew** [MicrosoftDocs/cpp-docs#2171]
It should be mentioned (or better changed in the MFC code) that CComboBox::GetLBText(int nIndex, CString& rString) runs into AtlThrow(E_INVALIDARG) when called with an invalid index.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4112e9-2fed-302f-0983-0320431b87e4
* Version Independent ID: 8d840945-9dc1-6cb7-76ab-03d6b2f50cc2
* Content: [CComboBox Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/ccombobox-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/ccombobox-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/ccombobox-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@tobias-loew, thank you for bringing this to our attention. I've updated the page to indicate that it throws and it should be live by end of day 8/28
