### ISSUE TITLE
Conflicting error handling instructions

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/cpp-docs#2172]
SendRequest and other functions describe error reporting by returning 0 and by throwing a CInternetException object. These two approaches can't both be true. If a CInternetException is thrown, there will be no return value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab214754-643b-097b-820a-fb77b7e2c441
* Version Independent ID: 54b4a4ad-614f-26ac-53da-eea07d7d750c
* Content: [CHttpFile Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/chttpfile-class?view=vs-2019#sendrequest)
* Content Source: [docs/mfc/reference/chttpfile-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/chttpfile-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
