### ISSUE TITLE
mfc validations of edit box

### ISSUE THREAD

**Issue by rishika-sys** [MicrosoftDocs/cpp-docs#2177]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7db9e30-9c36-5110-7e84-13bd0e769c4a
* Version Independent ID: bc2b7716-4b28-4d96-1275-7fb49604d470
* Content: [Dialog Data Validation](https://docs.microsoft.com/en-us/cpp/mfc/dialog-data-validation?view=vs-2019)
* Content Source: [docs/mfc/dialog-data-validation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/dialog-data-validation.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@rishika-sys 
I'm sorry, I can't tell what's wrong from the title alone. Can you explain the issue?

**Comment by corob-msft** [comment]
Closing for lack of actionable info.
