### ISSUE TITLE
Document Broken

### ISSUE THREAD

**Issue by sayurin** [MicrosoftDocs/cpp-docs#2182]
Previous page is [here](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/87zae4a3(v=vs.120)).
What is `DEVMODE` and `TEXTMETRIC`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11fc03b-ef6d-be4d-d17a-de38040445bf
* Version Independent ID: 55df0691-25fe-a060-b394-40b8ef0b0dda
* Content: [String Conversion Macros](https://docs.microsoft.com/en-us/cpp/atl/reference/string-conversion-macros?view=vs-2015)
* Content Source: [docs/atl/reference/string-conversion-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/string-conversion-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
Several years ago, there was an effort to consolidate ATL content, and some may have been lost in the process. This topic corresponds to [String Conversion Macros](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/w055htd5\(v=vs.120\)), which had the content from [ATL and MFC String Conversion Macros](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/87zae4a3\(v=vs.120\)) and [DEVMODE and TEXTMETRIC String Conversion Macros](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/y7328zzh\(v=vs.120\)) merged into it. It looks like the first document was truncated early. For now, I recommend using the archived documentation. `DEVMODE` and `TEXTMETRIC` structures are used for printers, display devices, and font metric calculations.

**Comment by TylerMSFT** [comment]
losing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
