### ISSUE TITLE
New Unwind Operator Codes for AVX-512

### ISSUE THREAD

**Issue by jan-auer** [MicrosoftDocs/cpp-docs#2187]
Could there be a new unwind operation with operation code `11` (`0xB`), and potentially more after that? I have reason to believe that this is being emitted for some of the Intel AVX-512 extension instructions.

For example, one of the unwind infos contains unwind code: `AD 1B 05 01`, which is generated by `kmovw word ptr [rsp+828h],k1`. Based on this, it seems that:

- Offset in prolog `0xAD`.
- Code `0xB`/11.
- Info `1`, seems to refer to mask register `k1`.
- Operator `0x0105` seems to refer to the scaled-by-8 stack offset of the allocation.

WinDbg 1909 was not able to decode this and instead prints "Unknown unwind opcode: b". Unfortunately, I do not know if this part of the executable was compiled with the Intel ICC compiler or with MSVC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?redirectedfrom=MSDN&view=vs-2019)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jan-auer 
Thanks for the report. I've put the question to our compiler back-end developers, and they doubt the unwind code in question is coming from our compiler. We have business partners from the major processor manufacturers who consult with us, and one of the Intel people said he'd ask their compiler team about it. I'll report back if I hear more. Given the nature of the issue, though, it sounds like our documentation covers what our compiler does. As such, I'm closing this issue, but always open to reconsideration if things change.

**Comment by jan-auer** [comment]
Thank you for the swift response!
