### ISSUE TITLE
Typo...

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/cpp-docs#2188]
over where it says  
Unlike the C++/CX implementation. C++/WinRT doesn't use non-standard syntax or Microsoft language extensions, and it takes full advantage of the C++ compiler to create highly-optimized output. For more information, see Introduction to C++/WinRT.

there should be a comma at "Unlike the C++/CX implementation." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a2d3f-950b-77a4-07d9-f57c4368c0eb
* Version Independent ID: 6e985011-f7b0-98d2-b363-d5608d707a13
* Content: [Universal Windows Apps (C++)](https://docs.microsoft.com/en-us/cpp/cppcx/universal-windows-apps-cpp?view=vs-2019)
* Content Source: [docs/cppcx/universal-windows-apps-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/universal-windows-apps-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by KishkinJ10** [comment]
sir I am a beginner can I work on this ?? can you guide me??

**Comment by corob-msft** [comment]
@KishkinJ10 
Yes, you're also welcome to submit a PR to fix this issue. There's an introduction in our [Microsoft Docs contributor guide overview](https://docs.microsoft.com/contribute/) that explains the steps to follow for quick edits to existing documents. Mention #2188 in your comments, so the PR gets linked to this issue. Thanks for asking, and for contributing!

**Comment by corob-msft** [comment]
I should have looked at this more closely to find out if it had already been fixed. Someone took care of this without linking to it in PR #2991. Sorry about the wasted effort.
