### ISSUE TITLE
another typo...

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/cpp-docs#2190]
In the section "To add functionality to the WndProc function", the end of step 1 says "The functions help make the graphics subsystem is available for use by other applications." It should be "The functions [used to]..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you. Fixed. I reworked the paragraph as it was somewhat misleading. 
Changes should be live by 5/29
#please-close
