### ISSUE TITLE
Integrate with Visual Studio Code (Linux/MacOS)

### ISSUE THREAD

**Issue by mohamedsayed18** [MicrosoftDocs/cpp-docs#2191]
when I try to run this command ```./vcpkg integrate install```
output:
```
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=/media/mohamed/C03CCDB43CCDA62E/tutorials/Innopolis/2nd/BCR/vcpkg/scripts/buildsystems/vcpkg.cmake"
```
then I used these commands:
```
cd toolsrc/
cmake . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
```
output:
```
.cmake
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_TOOLCHAIN_FILE
-- Build files have been written to: /media/mohamed/C03CCDB43CCDA62E/tutorials/Innopolis/2nd/BCR/vcpkg/toolsrc
```
when I run this command again ```./vcpkg integrate install``` I got the same error as above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg: a C++ package manager for Windows, Linux, and MacOS](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019#feedback)
* Content Source: [docs/build/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mohamedsayed18 
I'm sorry you're having trouble. What you're describing sounds more like a product issue than a documentation issue. For help with a product issue, I recommend either the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site, or the [Issues section of the vcpkg repo](https://github.com/microsoft/vcpkg/issues). The developers will let us know if the documentation needs to be updated.

**Comment by quangthanh010290** [comment]
I'm cross-build for arm target and include path is local. So, how to use with vcpkg
