### ISSUE TITLE
MFC setup information would be helpful

### ISSUE THREAD

**Issue by dexmagic** [MicrosoftDocs/cpp-docs#2204]
I have an existing project that won't build because MFC libraries aren't installed. It would be helpful to know how I can look at an existing project and know what MFC libraries the project relies on so I know what libraries to install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97fca0e3-6a3f-a9d1-23fd-866492ebba42
* Version Independent ID: 84706940-ed7d-10b9-b61d-312c2e490654
* Content: [MFC and ATL](https://docs.microsoft.com/en-us/cpp/mfc/mfc-and-atl?view=vs-2019#feedback)
* Content Source: [docs/mfc/mfc-and-atl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/mfc-and-atl.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@dexmagic, I'm sorry, but we aren't able to invest in new MFC documentation. Closing.
