### ISSUE TITLE
Addition to "See also" section

### ISSUE THREAD

**Issue by Melirius** [MicrosoftDocs/cpp-docs#2206]
I think the page about format specification syntax will be a nice addition to "See also" section here.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a1655b-7dbc-9a8a-e8c5-5232f86c5827
* Version Independent ID: daa02428-6f8c-597e-fb24-632148f988e0
* Content: [printf, _printf_l, wprintf, _wprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Good call, @Melirius.
I have added that to the page. It should be live tomorrow.
