### ISSUE TITLE
Start Page and New Project Dialog

### ISSUE THREAD

**Issue by heatherlock** [MicrosoftDocs/cpp-docs#2208]
I am new to VS code and I looked at this page for starting a new app, however, it shows a start page that never shows for me and there is no new project option, nor is there a new project dialog window. Why does this page have this information if it does not actually exist??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019#feedback)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@heatherlock 

I understand your confusion. Despite the similarity in names, Visual Studio and Visual Studio Code are different programs, with very different interfaces. It doesn't help that there's also a Visual Studio for Mac, yet another program that's got a different interface of its own. You've landed on a page in the Visual Studio documentation, which not unexpectedly describes how to use Visual Studio.

Assuming you don't want to [download and install the Visual Studio IDE](https://visualstudio.microsoft.com/vs/community/), you should instead look for the documentation for [VS Code](https://code.visualstudio.com/) and its guide on how to [configure VS Code for Microsoft C++](https://code.visualstudio.com/docs/cpp/config-msvc) and use the VS Code [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) with the MSVC [Build tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019). The configuration guide shows you how to get "Hello, world" running, and how to debug it, too. It's pretty nifty.
