### ISSUE TITLE
PDF bookmarks don't link to the right pages

### ISSUE THREAD

**Issue by stevehartdata** [MicrosoftDocs/cpp-docs#2212]
PDF bookmarks don't always link to the right pages. For example, if you download the PDF [here](https://docs.microsoft.com/en-us/cpp/opbuildpdf/8d846aa6/cpp/toc.pdf?branch=live&view=vs-2019) and click the "Namespaces" bookmark, page 347 ("Transfers of Control") is displayed. Many other bookmarks are also wrong (some are more than one page off). To be clear, the bookmarks I'm referring to are the PDF bookmarks, not the links in the table of contents section of the document. The same problem appears when reading the PDF in Google Chrome and in Adobe Acrobat, so I think the problem is with the PDF, not with the reader.

![image](https://user-images.githubusercontent.com/868153/82568261-8c300b00-9b4c-11ea-8773-67887bcc8fd0.png)

![image](https://user-images.githubusercontent.com/868153/82568349-ab2e9d00-9b4c-11ea-97b4-8db18503d10d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b79794-72e8-5fc5-1788-e6bee86d040d
* Version Independent ID: 3e6dc433-4bab-13cd-50ff-4212e79e3056
* Content: [C++ Language Reference](https://docs.microsoft.com/en-us/cpp/cpp/cpp-language-reference?view=vs-2019)
* Content Source: [docs/cpp/cpp-language-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-language-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, how old it is, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
