### ISSUE TITLE
Explain please

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/cpp-docs#2214]
@baltaevamin commented 9 hours ago — with docs.microsoft.com

In the first example, at the beginning of the topic.
b = 6
a = 3
b% = a; // b is 6; in the example right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb7e11f-cd0d-5e4d-fcf2-6b1060b7586c
* Version Independent ID: 90046753-8233-1a30-09d8-126f8350b3fc
* Content: [Assignment Operators](https://docs.microsoft.com/en-us/cpp/cpp/assignment-operators?view=vs-2019#feedback)
* Content Source: [docs/cpp/assignment-operators.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/assignment-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@baltaevamin

Yes, `b == 6` after these operations:

```cpp
    int a = 3, b = 6;
    a += b;      // a = a + b ⇒ a = 3 + 6 ⇒ a == 9 
    b %= a;      // b = b % a ⇒ b = 6 % 9 ⇒ b == 6
```
