### ISSUE TITLE
Improve documentation for upgrades and features

### ISSUE THREAD

**Issue by Erroneous1** [MicrosoftDocs/cpp-docs#2215]
It'd be nice if the documentation for update/upgrade mentioned you need to `git pull origin master` and that you may need to rerun the bootstrap-vcpkg script.

Additionally, some packages offer different features that can be chosen. It'd be good to document A) how to find those features or at least show an example of one that has more than just `[core]` and B) how to install specific features. A common one might be curl:

```
vcpkg search curl
...
curl                 7.68.0-3         A library for transferring data with URLs
curl[tool]                            Builds curl executable
curl[non-http]                        Enables protocols beyond HTTP/HTTPS/HTTP2
curl[http2]                           HTTP2 support
curl[ssl]                             Default SSL backend
curl[ssh]                             SSH support via libssh2
curl[openssl]                         SSL support (OpenSSL)
curl[winssl]                          SSL support (Secure Channel / "WinSSL")
curl[mbedtls]                         SSL support (mbedTLS)
curl[sectransp]                       SSL support (sectransp)
curl[c-ares]                          c-ares support
curl[sspi]                            SSPI support
curl[brotli]                          brotli support (brotli)
...
vcpkg install curl[tool]:x64-windows
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg: a C++ package manager for Windows, Linux, and MacOS](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019#feedback)
* Content Source: [docs/build/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Issue addressed in an update available on 2020.07.07.
