### ISSUE TITLE
CMake Linux Configurations renamed

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/cpp-docs#2224]
Seems that on Visual Studio 2019 (16.6.0 Community) You need to add the Configurations they no longer show on the dropdown it just shows `x64-Debug` the options name have now changed and instead of being called `Linux-Debug` or `Linux-Release` they are now `Linux-Clang-Release` `Linux-Clang-Debug` `Linux-GCC-Debug` `Linux-GCC_Release` 

Can documentation be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create and configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019#configure_cmake_linux)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @annerajb 
I've updated the topic. It'll go live by Monday evening (9/28)
#please-close
