### ISSUE TITLE
Missing detail about switching from DLL import of VC runtime to statically linking VC runtime

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/cpp-docs#2225]
Missing detail about switching from DLL import of VC runtime to statically linking VC runtime.
On this page: https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019
And on this page: https://docs.microsoft.com/en-us/cpp/parallel/concrt/overview-of-the-concurrency-runtime?view=vs-2019
It is NOT mentioned that when switching to statically linking VC runtime, you need to link with "concrt.lib" to resolve unresolved externals related to using the Concurrency Runtime.  This took me over an hour to figure out.  Both pages should be updated.   Both mention concrt140.dll, but not the lib needed for linking/building.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@ChuckM2, sorry you are having trouble here. I’m pretty certain this should not be the case – concrt depends on vcruntime140, not the other way around. Additionally, “concrt.lib” is the dynamic-link version of concrt. If you switched to static link, you should be linking with libconcrt.lib. I think there may be an issue with how your project is configured.
