### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by Bob64375** [MicrosoftDocs/cpp-docs#2228]
Needs link to the definitions of values for execute before and execute after, e.g. where is BuildGenerateSources defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34e186-20d4-e937-8b4a-036b4708aad8
* Version Independent ID: 0d911d7c-1338-c554-bb55-7de0c33e846a
* Content: [Custom Build Step Property Page: General](https://docs.microsoft.com/en-us/cpp/build/reference/custom-build-step-property-page-general?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCCustomBuildStep.Command)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/build/reference/custom-build-step-property-page-general.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/custom-build-step-property-page-general.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Bob64375 
See [MSBuild targets](https://docs.microsoft.com/visualstudio/msbuild/msbuild-targets?view=vs-2019) in the Visual Studio docs for more information about those targets for now.
