### ISSUE TITLE
Broken links in styleguide/template.md

### ISSUE THREAD

**Issue by ratijas** [MicrosoftDocs/cpp-docs#2229]
Several links point to 404 pages at the bottom of the [`styleguide/template.md`](https://github.com/MicrosoftDocs/cpp-docs/blob/master/styleguide/template.md) document.

For example:

 - Alert styles https://github.com/MicrosoftDocs/cpp-docs/raw/master/images/alerts.png
 - Button links https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/core/index.md
 - Intune docs https://docs.microsoft.com/intune/get-started/choose-how-to-enroll-devices

... and probably much more. Those are just three ones in a row.

**Comment by corob-msft** [comment]
@ratijas 
Thanks for the info. I'm not sure we need our own style guide, given the [common one for Docs](https://docs.microsoft.com/en-us/contribute/markdown-reference) covers most of what we do. I'll look into it.

**Comment by ratijas** [comment]
That's some high-quality guide! I never knew it existed.

**Comment by corob-msft** [comment]
I know, right? I think the only thing we need that's specific to cpp-docs is a table for how we format **`keywords`**, `functions`, *parameters*, *`EBNF-non-terminals`*, and maybe a few others.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
