### ISSUE TITLE
For CMake based project, "Debug your Linux project" section isn't useful

### ISSUE THREAD

**Issue by DovahYol** [MicrosoftDocs/cpp-docs#2231]
I can't follow the instructions in this section, because there is no place called "Debugging property page" for CMake based project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001834ce-31d2-e768-1df1-4a776aa9ef65
* Version Independent ID: 45f15fc0-e5c7-34a1-2469-f38d304ef5bd
* Content: [Deploy, run, and debug your C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019#configure-other-debugging-options-cmake-projects)
* Content Source: [docs/linux/deploy-run-and-debug-your-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/deploy-run-and-debug-your-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@DovahYol 

I understand your confusion. This page is not meant for Linux CMake projects. It's part of a series of three pages for MSBuild-based (.vcxproj) Linux projects:

- [Create a new Linux project](https://docs.microsoft.com/cpp/linux/create-a-new-linux-project?view=vs-2019)
- [Configure a Linux project](https://docs.microsoft.com/cpp/linux/configure-a-linux-project?view=vs-2019)
- [Deploy, run, and debug your Linux project](https://docs.microsoft.com/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2019)

For CMake Linux projects, all three steps are all covered in:

- [Create and configure a Linux CMake project](https://docs.microsoft.com/cpp/linux/cmake-linux-project?view=vs-2019)

I don't think our TOC is helping here. I'll take a look at rearranging it.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
