### ISSUE TITLE
The doc doesn't mention that I need to be a su to allow vs to install latest CMake

### ISSUE THREAD

**Issue by DovahYol** [MicrosoftDocs/cpp-docs#2237]
> Visual Studio 2019 detects whether a recent version of CMake is installed on the Linux system. If none is found, Visual Studio shows an info-bar at the top of the editor pane. It offers to install CMake for you from https://github.com/Microsoft/CMake/releases.

I'm not a su, so it seems that vs can't install CMake in `/usr/bin/` for me, which isn't mentioned in the doc. Additionally, should I ask a su to install the latest CMake in `/usr/bin/` for me and let vs use it? Otherwise I see no way to meet vs prerequisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create and configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@esweet431 for awareness.

**Comment by esweet431** [comment]
Hi @DovahYol, Visual Studio doesn't need su permissions for CMake binary deployment to work. We just drop the binaries into your home directory (~.vs/cmake/bin). 

If you acquire CMake another way (like through your system package manager), then you likely will need su permissions. 

CMake doesn't need to be installed in /usr/bin, that's just the default location that VS will search. You can change the path to the CMake.exe that Visual Studio will use in the CMake Settings Editor ("Show advanced settings" link at the bottom of the editor > CMake executable)

**Comment by TylerMSFT** [comment]
#please-close
