### ISSUE TITLE
Updating __vectorcall Documenations.

### ISSUE THREAD

**Issue by hberghoff** [MicrosoftDocs/cpp-docs#2238]
My change will target __vectorcall documentation found in directory docs/cpp/ found at https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cpp/vectorcall.md

My changes would be to simplify register and stack allocation allocation explanations and expand the examples section. Also to change wordage to improve clarity such as "shadow stack"

**Comment by corob-msft** [comment]
@wberghoff 
Please use the cpp-docs-pr repo for your updates. Instructions are in the devdiv wiki under Content Development > Docs > Edit. Feel free to message me for more info.

**Comment by wberghoff** [comment]
@corob-msft 
I just looked through the wiki and it looks like the Edit subsection is gone. Also, I have searched for the cpp-docs-pr repo and I can't find it. Have things changed since June 1?

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
