### ISSUE TITLE
WRL ComPtr::Reset incorrect documentation

### ISSUE THREAD

**Issue by samyun** [MicrosoftDocs/cpp-docs#2239]
https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=vs-2019#reset

"Releases all references for the pointer to the interface that is associated with this ComPtr."

"Return Value: The number of references released, if any."

This seems incorrect. Implementation seems to call IUnknown->Release, which decrements the refcount and returns the new refcount. It doesn't release all references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c769cdb9-ab7c-77bd-16b7-8bb686169eff
* Version Independent ID: ff913b70-328c-9d9e-c7ec-ba942db726b1
* Content: [ComPtr Class](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=vs-2019#reset)
* Content Source: [docs/cppcx/wrl/comptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/comptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@samyun 

I think you're right. Thanks for reporting this.

**Comment by corob-msft** [comment]
Fixed.
