### ISSUE TITLE
Two m_cause values seem to be wrong.

### ISSUE THREAD

**Issue by markh524** [MicrosoftDocs/cpp-docs#2243]
Documentation says:
CFileException::diskFull 14: The disk is full.
CFileException::endOfFile 15: The end of file was reached.

Looking in code the values are 13 and 14, respectively.
	enum {
		none,
		genericException,
		fileNotFound,
		badPath,
		tooManyOpenFiles,
		accessDenied,
		invalidFile,
		removeCurrentDir,
		directoryFull,
		badSeek,
		hardIO,
		sharingViolation,
		lockViolation,
		diskFull,
		endOfFile
	};

FYI - I'm using VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31dfb732-be4e-944b-7aac-16669e70a640
* Version Independent ID: 4fb457d9-e2e8-7cb8-6764-035cc47b4eba
* Content: [CFileException Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cfileexception-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cfileexception-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cfileexception-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @markh524. I've fixed this and it should be live tomorrow.
