### ISSUE TITLE
atomic_wait() and atomic_notify_one() are missing

### ISSUE THREAD

**Issue by Varonec** [MicrosoftDocs/cpp-docs#2245]
Per the standard for c++ there are functions atomic_wait() and atomic_notify_one() thedse are just flat out missing from MSVC.  is there a reason for this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beec3676-ba42-faca-7d01-41bf5f8c7484
* Version Independent ID: 16b5df04-ed0e-def2-513c-0eb25e975e5a
* Content: [&lt;atomic&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/atomic-functions?view=vs-2019)
* Content Source: [docs/standard-library/atomic-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/atomic-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Varonec 

The atomic class member functions `atomic_wait` and `atomic_notify_one` are recent additions to the [C++20 working draft](https://wg21.link/n4861), and aren't implemented yet. You can follow the progress of the Microsoft STL implementation in its GitHub repo at [https://github.com/microsoft/STL](https://github.com/microsoft/STL). The wiki includes a [Changelog](https://github.com/microsoft/STL/wiki/Changelog) to show which updates appear in each Visual Studio release. The documentation follows along behind the implementation, but we're working on catching up.

**Comment by Varonec** [comment]
Thank you so much for the response!
