### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DABH** [MicrosoftDocs/cpp-docs#2247]
There is one instance on this page where a flag is written as `/std:latest` (which is invalid) rather than `/std:c++latest`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6183aaac-1eb4-f704-4bf5-1c3fe67ae2fe
* Version Independent ID: d3f24754-fcba-3eee-e34d-445962c5485c
* Content: [/std (Specify Language Standard Version)](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019)
* Content Source: [docs/build/reference/std-specify-language-standard-version.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/std-specify-language-standard-version.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
A fix for this and the other two places with the same mistake should appear later today.
