### ISSUE TITLE
Redistributing Visual C++ Files wrong for VS 

### ISSUE THREAD

**Issue by CADbloke** [MicrosoftDocs/cpp-docs#2248]
https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=vs-2019 is all about VS 2017, not 2019. The MSM merge modules do not exist for VS 2017 nor 2019. VC14 is the latest version to have merge modules. Oh wait, VC14 is for VS/VC16. **that's not confusing at all**, particularly for .NET developers who happen to stumble into to C++ rabbit hole.

https://docs.microsoft.com/en-us/cpp/windows/redistributing-components-by-using-merge-modules?view=vs-2019 is also wrong: `\Program Files\Common Files\Merge Modules\` does not exist on a Windows 10 x64 system with both VS 2019 & 2017 installed. The correct folder is `C:\Program Files (x86)\Merge Modules` but there is no VC15 or VC16 msm modules so that web page is totally wrong for VS 2019. The most recent VC merge modules are from 2016 so, nah.

Visual Studio 2017 has `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Redist\MSVC\14.16.27012\MergeModules` but no such equivalent exists for Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdd5052-e8a5-633e-3c31-74e5ac664917
* Version Independent ID: 1f1321f2-8de8-80a9-fa29-06c71c71d573
* Content: [Redistributing Visual C++ Files](https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=vs-2019)
* Content Source: [docs/windows/redistributing-visual-cpp-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/redistributing-visual-cpp-files.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CADbloke** [comment]
I found an option in the Visual Studio 2019 installer. Under "Compilers, built tools, and runtimes" the 3rd checkbox is "C++ 2019 Redistributable MSMs", Well, there ya go.

**Comment by corob-msft** [comment]
This was fixed on July 16th, but I forgot to follow up and close this issue.
