### ISSUE TITLE
Please document [[msvc::forceinline_calls]] etc. attributes

### ISSUE THREAD

**Issue by zx64** [MicrosoftDocs/cpp-docs#2249]
Currently only `gsl::suppress` is documented on the attributes.md MSDN page.

I recently learned about the existence of complier specific attributes for controlling inlining from [this reddit comment](https://old.reddit.com/r/programming/comments/g9inos/smarter_cc_inlining_with_attribute_flatten/foyoq62/) and can't find any documentation about it, e.g. supported versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2eb231e-d120-ad82-539c-f30baa904815
* Version Independent ID: ea724ca8-bc1c-f154-c122-0217f6280590
* Content: [Attributes in C++](https://docs.microsoft.com/en-us/cpp/cpp/attributes?view=vs-2019)
* Content Source: [docs/cpp/attributes.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/attributes.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@zx64 
It's possible these attributes are available in 16.7 previews, but they're not in a released version of Visual Studio yet. 
@terrymah Can you comment on availability?

**Comment by TylerMSFT** [comment]
This has been documented.
