### ISSUE TITLE
cURL fails in CMake projects when using its own version of libcurl

### ISSUE THREAD

**Issue by Petezah** [MicrosoftDocs/cpp-docs#225]
I needed to do:
```
cmake ../ -DCMAKE_USE_SYSTEM_CURL=YES
```
Otherwise, the project I was trying to build would fail to download dependencies with the error: "Protocol https unsupported or disabled in libcurl".

**Comment by mikeblome** [comment]
Thanks for the feedback @Petezah. Since Visual Studio doesn't really get involved in the CMake build pipeline, I'm not sure there's anything we can do here. Perhaps you could give feedback on the CURL site: https://curl.haxx.se/docs/help-us.html.
