### ISSUE TITLE
Warning is triggered for functions that might throw

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2251]
Moved from: https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/46

@FrankHeimes commented 14 hours ago
Functions that do properly acquire and release locks may still trigger this warning if they might throw. The following code triggers C26110 for `~scoped_lock` if and only if `GetMutex()` is _not_ declared `noexcept`.

```
std::mutex& GetMutex() /*noexcept*/
{
  static std::mutex m;
  return m;
}

std::scoped_lock lock(GetMutex());   // warning C26110
```

IMHO, the documentation should clarify that "... other lock-related annotations on at least one path of execution - including exceptions." in the first paragraph and maybe add the above as a second example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8f0de0-364e-09d2-e133-db938f09ce44
* Version Independent ID: fc7a9431-5799-032d-fc93-b468e6c606b5
* Content: [C26110](https://docs.microsoft.com/en-us/cpp/code-quality/c26110?view=vs-2019)
* Content Source: [docs/code-quality/c26110.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26110.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
