### ISSUE TITLE
Slightly incorrect example output

### ISSUE THREAD

**Issue by Rawk-Star** [MicrosoftDocs/cpp-docs#2254]
For the second example, it says the output will be this.

In each case:
0123

But it should say this.

In each case:
0
1
2
3

or remove the \n from the example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c8aeb7-013d-9049-a57e-409df38ca17e
* Version Independent ID: 09540f27-6045-3a69-327c-9ab810b8733a
* Content: [break Statement (C++)](https://docs.microsoft.com/en-us/cpp/cpp/break-statement-cpp?view=vs-2019)
* Content Source: [docs/cpp/break-statement-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/break-statement-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by piyush9311** [comment]
I would like to work on this issue

**Comment by corob-msft** [comment]
@piyush9311 We welcome PRs to fix issues like this one. It's essentially fixing a typo, and a good introduction to contributing to our repo.
