### ISSUE TITLE
Incorrect onfo

### ISSUE THREAD

**Issue by sluge** [MicrosoftDocs/cpp-docs#2258]
It is defined that /GL is disabled by default. It disabled by default only for debug but enabled for release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8523cfca-780b-de2e-4fc0-59a708589fc8
* Version Independent ID: d3740de2-4523-5fee-642b-1b459cc9cfee
* Content: [/GL (Whole Program Optimization)](https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=vs-2019)
* Content Source: [docs/build/reference/gl-whole-program-optimization.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/gl-whole-program-optimization.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sluge 

As far as I can tell, the only way to get **`/GL`** behavior from the compiler is to set the option explicitly. **`/GL`** is not implied by any other compiler switch, except the linker's **`/LTCG`** switch.
