### ISSUE TITLE
_com_ptr_t is implicitly convertible to just about anything

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#2260]
@FrankHeimes commented on [Thu Jun 11 2020](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/48)

Those who consider using `_com_ptr_t` should be aware that this type converts to just about anything. The following code compiles fine without any warnings or errors:
```
using IStreamPtr = _com_ptr_t<_com_IIID<IStream, &__uuidof(IStream)>>;
IStreamPtr p;
const bool b = p;
const int i = p;
const long l = p;
```
This is caused by the `operator bool() const noexcept` member of `_com_ptr_t`, which is implicitly converted to `int`, `long` or any other POD type. So `b == true` and `i == l == 1` if the interface pointer is not `NULL`.

If `IStreamPtr` was an alias for `void*`, then that code would trigger
_warning C4800: Implicit conversion from 'IStreamPtr' to bool. Possible information loss
error C2440: 'initializing': cannot convert from 'IStreamPtr' to 'int'_

Granted - the `bool()` cast operator has been implemented to support statements like `if (p) {...}` and warning C4800 can be enabled by including `comip.h` with warning level 4 enabled. But this still does not catch the situation where an interface is inadvertently passed as an `int` or `long` parameter.

It is highly unlikely that Microsoft will modify `_com_ptr_t` as this could break a large existing code base.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6cdedf5f-d1b3-3a53-352b-23dfeccf775b
* Version Independent ID: 401c4a01-5117-250d-8b5f-78410c0db84b
* Content: [Vorgehensweise: Erstellen und Verwenden von CComPtr-und CComQIPtr-Instanzen](https://docs.microsoft.com/de-de/cpp/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances?view=vs-2019)
* Content Source: [docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

---

@srvbpigh commented on [Thu Jun 11 2020](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/48#issuecomment-642465448)

Hello, @FrankHeimes
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by FrankHeimes** [comment]
I'd like to publish a code snippet that allowed me to sort of "patch" the original `_com_ptr_t` to follow the safe bool idiom, i. e. define `explicit operator bool()`.

This causes warning C4800 and error C2440 to be triggered when attempting to cast incorrectly but conditions using `_com_ptr_t` keep working.

Save the following code as `comip.h` somewhere in your project specific include path and define the preprocessor symbol VCTOOLSVERSION to be your current toolset version (e.g. 14.25.28610):
```
#pragma once

// class _com_ptr_t uses an unsafe bool() cast operator, which allows interfaces to be passed as integral parameters.
// Since C++11 supports explicit cast operators, it is possible to enforce the safe-bool idiom.
// See https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Safe_bool

// To achieve this, <comip.h> must be included as early as possible,
// so that it can be patched by this header and have its bool() cast operator replaced with an explicit one.

#include <boost\preprocessor\cat.hpp>
#include <boost\preprocessor\stringize.hpp>

__if_exists(_com_ptr_t)
{
  static_assert(false, "_com_ptr_t is already defined. Move compip.h up in the include sequence.");
}

// Hide original definition of _com_ptr_t and break its 'private' encapsulation open
#define _com_ptr_t _com_ptr_tORIGINAL
#define _ALLOW_KEYWORD_MACROS
#define private public
// Including the original header via relative path prevents recursive inclusion.
// C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\comip.h
#include BOOST_PP_STRINGIZE(BOOST_PP_CAT(BOOST_PP_CAT(..\..\,VCTOOLSVERSION),\include\comip.h))
#undef private
#undef _ALLOW_KEYWORD_MACROS
#undef _com_ptr_t

__if_not_exists(_com_ptr_tORIGINAL)
{
  static_assert(false, "_com_ptr_tORIGINAL is not defined even after including comip.h. Check INCLUDE path.");
}

// Alternative definition that just replaces the bool cast operator
template<typename _IIID>
class _com_ptr_t : public _com_ptr_tORIGINAL<_IIID>
{
public:
  using BaseClass = _com_ptr_tORIGINAL<_IIID>;
  using BaseClass::BaseClass;

  #pragma warning(suppress: 26434) // Function '_com_ptr_t<_com_IIID<xxx>>::operator bool' hides a non-virtual function '_com_ptr_tORIGINAL<_com_IIID<xxx>>::operator bool' (c.128).
  explicit operator bool() const noexcept
  {
    return _com_ptr_tORIGINAL<_IIID>::m_pInterface != nullptr;
  }
};

#include <comdef.h>
```

**Comment by corob-msft** [comment]
@FrankHeimes 

I'm familiar with the safe `bool` idiom. Making unanticipated `bool` (and other POD type) casts fail is a nice improvement to the `_com_ptr_t` class. However, there are a couple of things that make me concerned about adding your example to the documentation. We'd rather not include dependencies on third party libraries such as Boost in our primary docs. And the `private` -> `public` macro hack raised the hairs on my head. I'd never give that a pass in a code review.

Frankly, the easiest solution is to just make a private copy of the header files, and edit comip.h to add an `explicit` to the `operator bool()` definition. Presumably you're willing to deal with the consequences and add explicit `bool` casts in your own source code, where needed.

It's appropriate to include some warnings about the possibilities for unexpected conversions in the docs, and even to mention that you could reimplement a safer `_com_ptr_t` at the possible expense of backward compatibility. That's as far as I'd go.

**Comment by corob-msft** [comment]
I've added a cautionary note to the [_com_ptr_t Extractors](https://docs.microsoft.com/cpp/cpp/com-ptr-t-extractors) article, which should be visible tomorrow.
