### ISSUE TITLE
Incomplete Documentation values must be enclosed in single quotes.

### ISSUE THREAD

**Issue by lusandov** [MicrosoftDocs/cpp-docs#2262]
Values for _level_ and _uiAccess_ must be enclosed in single quotes:

/MANIFESTUAC:level='asInvoker'
/MANIFESTUAC:"level='asInvoker'"
/MANIFESTUAC:"level='asInvoker' uiAccess='false'"

When we have a single key=value, it may or may not be enclosed in double quotes (see first and second examples above) but value must be enclosed in single quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508783bb-9844-158e-226a-2fa9af55d557
* Version Independent ID: 941a6bee-5703-7bbc-caf0-5989f518e2ca
* Content: [/MANIFESTUAC (Embeds UAC information in manifest)](https://docs.microsoft.com/en-us/cpp/build/reference/manifestuac-embeds-uac-information-in-manifest?view=vs-2019)
* Content Source: [docs/build/reference/manifestuac-embeds-uac-information-in-manifest.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/manifestuac-embeds-uac-information-in-manifest.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@lusandov Thanks for the report. An updated version should be available by this afternoon.
