### ISSUE TITLE
Priciple of ON_UPDATE_COMMAND_UI 

### ISSUE THREAD

**Issue by luweiqianyi** [MicrosoftDocs/cpp-docs#2264]
[Enter feedback here]
Could you tell me the principle of ON_UPDATE_COMMAND_UI ，when I define an afx method,and add it to ON_UPDATE_COMMAND_UI  Macro，why my method is always called. This Page just tells me how to use it,but doesn't tell me how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0091aaab-01e2-559c-9a3a-62d5cbf7389d
* Version Independent ID: 3d0197ba-64be-e940-a489-8bc97c81024b
* Content: [ON_UPDATE_COMMAND_UI Macro](https://docs.microsoft.com/en-us/cpp/mfc/on-update-command-ui-macro?view=vs-2019)
* Content Source: [docs/mfc/on-update-command-ui-macro.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/on-update-command-ui-macro.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
You may also try [Microsoft Q&A for c++](https://learn.microsoft.com/en-us/answers/tags/314/cpp) regarding your question.
