### ISSUE TITLE
Page about WINVER etc. has references to erroneous OS versions and could benefit from review.

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/cpp-docs#2266]
Ref: Page:
https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?redirectedfrom=MSDN&view=vs-2019
1) The page makes reference to non existent builds of Windows:
"Older toolsets include support for Windows XP SP4, Windows Server 2003 SP4, Vista, and Windows Server 2008." 
There was no XP SP4 and 2003 SP4?
2) Later on there are references to: 
/* ABRACADABRA_THRESHOLD */
Whats the reason for the ABRACADABRA phrase?
3) Last but not least - in the WTL 10 source code, there are references to a WINVER value >= 0x605.
I can see no documentation for a WINVER == 0x604 or 0x605? What does WINVER == 0x605 correspond to, in terms of a product/Windows version? It's not documented.

Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31716afc-7fa8-9829-43e4-fff0ff73f912
* Version Independent ID: ef4343c0-3f57-5b38-08e0-623a79e8d508
* Content: [Update WINVER and _WIN32_WINNT](https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?redirectedfrom=MSDN&view=vs-2019)
* Content Source: [docs/porting/modifying-winver-and-win32-winnt.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/modifying-winver-and-win32-winnt.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MikeDiack 
To answer your questions in order, 
1. You're right, Windows XP SP2 and its 2003 Server equivalent are the last updates to that operating system, and the only versions supported by older VS toolsets. (They're not supported by the v142 toolset). I've got a fix for that in progress that should appear Monday.
2. I have no idea what ABRACADABRA means in this context. The header source is quoted verbatim.
3. WTL is not a Microsoft product, and while it may have similarly-named objects and macros, they're not necessarily the same as the ones we document. It sounds like an iffy way to check for Windows 10.
