### ISSUE TITLE
Missing Example Syntax

### ISSUE THREAD

**Issue by AtanasRusevPros** [MicrosoftDocs/cpp-docs#2267]
Your page is good, but it lacks Example. I tried few times and I always fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7207017a-c1a1-8a8c-7875-e0ba5a8f623e
* Version Independent ID: 67d07924-d569-5565-9c00-cea0a3e83ca5
* Content: [/HEAP (Set Heap Size)](https://docs.microsoft.com/en-us/cpp/build/reference/heap-set-heap-size?view=vs-2019)
* Content Source: [docs/build/reference/heap-set-heap-size.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/heap-set-heap-size.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
An update should appear tomorrow with an example. When people get a D8021 error with this, it's usually because they're trying to pass the option to the compiler instead of the linker or editbin command.
