### ISSUE TITLE
langtype

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/cpp-docs#227]
It'd be helpful if this document had more information, for example what are values for langtype (e.g., stdcall)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a4a85cb-0d4d-5d48-0ed8-c2089e5de15c
* Version Independent ID: 35a70002-a86f-80f4-5150-c333b616ddcf
* Content: [PROTO](https://docs.microsoft.com/en-us/cpp/assembler/masm/proto)
* Content Source: [docs/assembler/masm/proto.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/proto.md)
* Service: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
That looks like a reasonable idea; thanks for the suggestion. This is on our backlog, but if anyone feels strongly enough to jump in with an edit PR, that is also welcome.

**Comment by corob-msft** [comment]
@clandrew This was updated courtesy of a PR by @nsurampu.
