### ISSUE TITLE
Missin section

### ISSUE THREAD

**Issue by JanuszCz** [MicrosoftDocs/cpp-docs#2270]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc540c3-34c2-18ae-e08e-5769e34cdc2e
* Version Independent ID: 44591909-d820-1d9a-96a7-41f377b01056
* Content: [CMemFile Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmemfile-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmemfile-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmemfile-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by JanuszCz** [comment]
There is missing documentation about "GetBufferPtr" member of the CMemFile.
Janusz.

**Comment by TylerMSFT** [comment]
@JanuszCz, thank you for bringing this to our attention. I have documented the GetBufferPtr() and it should be live by tomorrow afternoon (7/24/2020)
