### ISSUE TITLE
bad example code

### ISSUE THREAD

**Issue by cjwijtmans** [MicrosoftDocs/cpp-docs#2271]
The example is terrible and doesnt demonstrate proper usage of smart pointers. The smart point should manage a real object that is used outside of its declared scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4941a280-af7a-9fec-7dc0-cc5001735666
* Version Independent ID: 951f54c6-6ba0-6025-d34c-84a1024bd6bb
* Content: [Object lifetime and resource management (RAII)](https://docs.microsoft.com/en-us/cpp/cpp/object-lifetime-and-resource-management-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/object-lifetime-and-resource-management-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/object-lifetime-and-resource-management-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cjwijtmans 

Thanks for reporting your concerns. The documentation doesn't expand on what its example code does with the smart pointer, which is used to keep any functions called between when the object is created and when it's destroyed from stealing the managed resource or deleting it out of turn. It's true that there are lots of other things that can be done with smart pointers, but it doesn't seem like the point of this short article to cover them. Perhaps the author had something else in mind, and never got around to it. In any case, this doesn't look wrong, it just doesn't satisfy some arbitrary standard of expansiveness. I'm inclined to leave it.
