### ISSUE TITLE
#line directive

### ISSUE THREAD

**Issue by solodon4** [MicrosoftDocs/cpp-docs#2272]
Talking about internal counter is useless when talking about #line directive. The most common question people get is whether the directive indicates the position of the line in which directive itself is or whether it indicates the next line's position.

Think about it this way: when line directive is used to return counter back to the current source file (the generated one), should the directive be on the same line as the number in it or should it be on the previous line indicating the number for the current line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0081cce-780f-0af2-482f-16fc1d43fd45
* Version Independent ID: 666c597d-3da6-2a13-ced7-d2ba73f44473
* Content: [#line directive (C/C++)](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-line-directive-c-cpp?view=vs-2019)
* Content Source: [docs/preprocessor/hash-line-directive-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/hash-line-directive-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@solodon4 

Thanks for the report. Empirically, the `#line` directive sets the `__LINE__` value reported on the *next* line after the directive. I've added a short bit of sample code to demonstrate. An update should be visible sometime tomorrow.
