### ISSUE TITLE
Is strerror_s() thread-safe?

### ISSUE THREAD

**Issue by matheustavares** [MicrosoftDocs/cpp-docs#2281]
`strerror_s()` is very similar to the POSIX `strerror_r()` variant, which is thread-safe. But there is no mention about `_s()` being thread-safe and the `_r()` variant is not implemented for Windows. I was wondering, is the `_s()` thread-safe? Also, would it be possible to add this information to the docs page?

Thanks,
Matheus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba2ec2-b636-574d-f749-c3a6060a73dc
* Version Independent ID: ba19e8ab-6b4f-295d-e4e7-ee6a6cb0d302
* Content: [strerror_s, _strerror_s, _wcserror_s, __wcserror_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @matheustavares,
Yes, strerror_s() is thread safe. I've added a note to the docs to the effect, which will go live by Monday or so.
Thank you for helping make the docs better.
