### ISSUE TITLE
Missing documentation for ATL CComPtr<IDispatch> specialization

### ISSUE THREAD

**Issue by EricAllen-tr** [MicrosoftDocs/cpp-docs#2282]
I was trying to determine what was going on with some existing source code I've come across. It uses the InvokeN method present on ATL's CComPtr<IDispatch> Specialization.

The specialization of CComPtr<IDispatch> and the additional methods Invoke0, Invoke1, Invoke2, InvokeN are missing from the current documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a04e4fcc-fc70-6fb3-4562-a15659d7837b
* Version Independent ID: 2e2dc015-06b3-515f-f3bf-e19c4edbb4b4
* Content: [CComPtr Class](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptr-class?view=vs-2019)
* Content Source: [docs/atl/reference/ccomptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/ccomptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
