### ISSUE TITLE
Remaining parameters after first four, L to R, or R to L?

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#2286]
The article states that the first four parameters are passed left-to-right in registers. But after that, it doesn't specify what order the remaining parameters are pushed onto the stack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87b11e0-0214-175b-0926-0f8a4653e444
* Version Independent ID: 43e8bf4a-9a0d-ea28-d432-ead828604d5e
* Content: [x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019)
* Content Source: [docs/build/x64-calling-convention.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/x64-calling-convention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ScotBren 
Eyeballing the disassembled register-passing code of some representative functions, it might be more accurate to say all arguments are pushed on the stack from right to left, except for the leftmost four, which are passed in registers. The __vectorcall convention is the same, but adds a couple of registers.

Parameters from right to left:
| type | > 4 from left | 4th from left | 3rd from left | 2nd from left | leftmost |
|-|-|-|-|-|-|
| floating-point | stack | XMM3 | XMM2 | XMM1 | XMM0 |
| integer | stack | R9 | R8 | RDX | RCX |

**Comment by ScotBren** [comment]
Note that the article specifically says  "Integer values are passed in left-to-right order in RCX, RDX, R8, and R9, respectively." But then it goes on ta say. "Arguments five and higher are passed on the stack". One might assume that it is continuing left to right, based on the previous sentence.

**Comment by corob-msft** [comment]
@ScotBren 

Thanks for the report. An update should work its way through publishing by sometime tomorrow.
