### ISSUE TITLE
/Z7 documentation is confusing

### ISSUE THREAD

**Issue by paddymcd-MSFT** [MicrosoftDocs/cpp-docs#2289]
[Enter feedback here]

/Z7 is a cl.exe switch and as such it is targeting compiler part of the process.  These (the front-end:c1.dll  and the back-end:c2.dll) translate the source into object file (.obj), which normally only exist in the intermediate output directory.

So in this context the “no pdb will be produced” is technically correct as all the debug information is contained in the .obj files.

.obj files can then be bundled into a static lib using lib.exe or link.exe /lib

BUT this is not the final form….

For this we now need to invoke the linker.  This consumes .obj files and static .lib files 

The linker will take the executable code and data from the objs and combine them into a single executable.  It will not place any of the debug information into the final executable.  If the correct linker switches are invoked (/debug) the linker will take the debug information in the obj files and emit them to a pdb.

So really it should read: “These object files and lib files can be substantially larger”.

And “No separate PDB file is produced by the compiler, but may later be produced by the linker.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 429cc6e8-2120-8a0f-eadb-0bc926d5bb5c
* Version Independent ID: d5a3132e-9f84-0cb3-446a-9703f65ba782
* Content: [/Z7, /Zi, /ZI (Debug Information Format)](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019#remarks)
* Content Source: [docs/build/reference/z7-zi-zi-debug-information-format.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/z7-zi-zi-debug-information-format.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@paddymcd-MSFT 

Thanks for the report. A fix is in the works, and should be visible by sometime tomorrow.
