### ISSUE TITLE
Please check types for second parameters in declarations

### ISSUE THREAD

**Issue by versat** [MicrosoftDocs/cpp-docs#229]
"const time32_t *sourceTime" should be "const __time32_t *sourceTime"
and
"const _time64_t *sourceTime" should be "const __time64_t *sourceTime"
i guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684adba0-62cb-59d7-d58c-69c7181b9903
* Version Independent ID: ef0c00f2-d75b-42f2-7918-208dd9c96560
* Content: [localtime_s, _localtime32_s, _localtime64_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s)
* Content Source: [docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md)
* Service: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks, it's always good to keep the syntax prototypes in line with the headers.

Fixed with the 5/15 AM merge from private repo to live.
