### ISSUE TITLE
button

### ISSUE THREAD

**Issue by JunkmanDong** [MicrosoftDocs/cpp-docs#2290]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JunkmanDong 

I'm sorry, this problem description doesn't have enough information for us to know what's wrong. If there's a problem on this page, tell us about it, and I'll reopen this issue.

If you're looking for [how to create a button](https://docs.microsoft.com/windows/win32/controls/create-a-button) or other Windows controls in a traditional Win32 app, that's described in the [Windows docs](https://docs.microsoft.com/windows/win32/). That documentation covers everything about windows, controls, and messages in Windows that we can't cover in a one-page intro.
