### ISSUE TITLE
COleDateTime::GetDayOfWeek

### ISSUE THREAD

**Issue by tibx** [MicrosoftDocs/cpp-docs#2292]
COleDateTime::GetDayOfWeek function description:
Gets the day of the month ---> Gets the day of the week

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c31362-cb6f-cd6a-f0cb-b03a6f23cda0
* Version Independent ID: 64066ad0-5778-4f58-9d0e-7ef1978f9f86
* Content: [COleDateTime Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/coledatetime-class?view=vs-2019)
* Content Source: [docs/atl-mfc-shared/reference/coledatetime-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/coledatetime-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@tibx, thank you for bringing this to our attention. I've updated the page and it should be live by end of day 8/28
