### ISSUE TITLE
Wrong parameter assignment in the file read example

### ISSUE THREAD

**Issue by hexonianlabs** [MicrosoftDocs/cpp-docs#2294]
[Enter feedback here]
Could you please review the example?
According to the function definition, I feel the 3rd and 4th parameter values should be swapped in the `numread = fread_s( list, BUFFERSIZE, ELEMENTSIZE, ELEMENTCOUNT, stream );` line. Am I right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c554578-ed4f-89ba-f803-5f3ca9202782
* Version Independent ID: c83faea7-2805-52e8-fffa-e8deb7d955ed
* Content: [fread_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fread-s?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/fread-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fread-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @hexonianlabs,
It looks correct to me. The order is: buffer, buffersize, elementsize, count, stream.
Which is what the code sample and header show as well. I think we are good here.
@please-close
