### ISSUE TITLE
Confused how to run .bat file 

### ISSUE THREAD

**Issue by Daniw2009872** [MicrosoftDocs/cpp-docs#2295]
[Can someone please explain how to "Run the bootstrapper in the root folder"?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg: a C++ package manager for Windows, Linux, and MacOS](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019)
* Content Source: [docs/build/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Daniw2009872 
Run the batch/shell bootstrapper file from the same folder that contains the file. This is the vcpkg root folder. Don't run it from the root of your drive, or from `/` on Linux.

**Comment by corob-msft** [comment]
Issue addressed in an update available on 2020.07.06.

**Comment by corob-msft** [comment]
Oops, I meant on 2020.07.07.
