### ISSUE TITLE
Uninitialized Pointers not null by default?

### ISSUE THREAD

**Issue by DavidBChristensen** [MicrosoftDocs/cpp-docs#2296]
The document says that uninitialized pointers are set to a random value, but when I test it out, they are assigned null when not explicitly initialized.

Perhaps the document is describing the standard and not the practice of the Microsoft compilers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2284bc5b-569d-81ee-0b8d-38c711c92656
* Version Independent ID: d448ee76-816d-67a9-6c1d-19da30933822
* Content: [Raw pointers (C++)](https://docs.microsoft.com/en-us/cpp/cpp/raw-pointers?view=vs-2019)
* Content Source: [docs/cpp/raw-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/raw-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DavidBChristensen 

The docs are describing the C++ standard behavior. What you actually get, depends. The compiler, at least in release builds, doesn't do any initialization of raw pointers unless you specify it. The value you're likely to see when you examine the contents of an uninitialized variable depends on several things. In debug builds, memory blocks are often initialized with sentinel values upon allocation. You can read about those in [CRT Debug Heap Details](https://docs.microsoft.com/en-us/visualstudio/debugger/crt-debug-heap-details). There are also flags that will cause the heap blocks handed out by Windows to get initialized. If you create a pointer on the stack somewhere and the stack hasn't advanced that far before, you *might* get zero-initialized memory. If the stack recedes and then advances again, you'll likely get whatever value was there before. 

The lesson remains, always initialize before you access something.
