### ISSUE TITLE
Correcting the logical sequence of items listed 

### ISSUE THREAD

**Issue by Prabhukp** [MicrosoftDocs/cpp-docs#2298]
[Enter feedback here]
As you read this page it becomes quite clear that the classes associations are shown correctly in the image below , 
but if you notice the  sequence under "The key objects in a running application are:" section it is incorrect

The correct logical sequence for any new person reading the article should be as below.
1.  Thread objects						        CWinThread
2.  The application object					CWinApp
3.  The document template or templates		CDocTemplate, CSingleDocTemplate, CMultiDocTemplate 
4.  The frame windows 					        CFrameWnd, CMDIFrameWnd,  CMDIChildWnd
5.  The document or documents.  			        CDocument
6.  Views   								CView

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bae1e0-7ecb-2f0c-b35c-7863ecce0334
* Version Independent ID: d2d904a8-9b4e-8a0e-334c-f9edf5d99ed6
* Content: [Documents, Views, and the Framework](https://docs.microsoft.com/en-us/cpp/mfc/documents-views-and-the-framework?view=vs-2019)
* Content Source: [docs/mfc/documents-views-and-the-framework.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/documents-views-and-the-framework.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @Prabhukp,
I've updated the topic. The fix will go live by Monday evening (9/28)
