### ISSUE TITLE
The unstable result issue with the qsort

### ISSUE THREAD

**Issue by lifenjoiner** [MicrosoftDocs/cpp-docs#2303]
`Quicksort` IS unstable! The document hasn't mention this now.

Example:
```c
/* test-qsort.c
To produce the unstable result bug on comparing result is 0.

Known:
    msvcrt: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort
    Reason: qsort bubbles the biggest to the last, but initial is the first!
*/

#include <stdlib.h>
#include <stdio.h>

typedef struct _X_OBJ {
    char    *name;
    int     v1;
    int     v2;
} X_OBJ;

int cmp(const void *p1, const void *p2) {
    X_OBJ *X1 = (X_OBJ *)p1;
    X_OBJ *X2 = (X_OBJ *)p2;
    int v1 = X1->v1 - X2->v1;
    int v2 = X1->v2 - X2->v2;
    return v1 ? v1 : v2;
}

int main(int argc, char **argv) {
    int i, n;
    X_OBJ XA[3] = {"a", 1, 2, "b", 1, 2, "c", 1, 2};

    n = sizeof(XA) / sizeof(X_OBJ);

    qsort(XA, n, sizeof(X_OBJ), cmp);

    for (i = 0; i < n; i++) {
        printf("%s ", XA[i].name);
    }
    // gives: b c a
    printf("\n");

    qsort(XA, n, sizeof(X_OBJ), cmp);

    for (i = 0; i < n; i++) {
        printf("%s ", XA[i].name);
    }
    // gives: c a b
    printf("\n");

    return 0;
}
```
There is some improvement can be done. For example: bubble the biggest to the end with the last as initial, or bubble the smallest to the first with the first as initial. And, seems that doesn't cost much. It will keep the `all elements 'equal' array` unchanged, which is rational.
I really want to log an issue to some place/contact to improve it, but can't find out anyone.
Make it better gives developers more convenience.

MS experts should have noticed this, but leave it as it is.
So, as `Quicksort` IS unstable, remind people with it really helps who 'forget' this, especially `all elements 'equal' array` will be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135f5795-2d27-fded-f416-2f5723b85b14
* Version Independent ID: 245a2a7a-b1b4-dcc3-9581-9d6101ed0292
* Content: [qsort](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/qsort.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/qsort.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@lifenjoiner 
Thanks for the report. If you think the CRT implementation should change, then the place to report that is on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). This is where the engineering team looks for bug reports and product suggestions. You can get there from the button labeled "This product" in the feedback section at the bottom of a Docs article.

Mention of qsort instability could be documented in Remarks. Assigning to @TylerMSFT to look into that possibility.

**Comment by lifenjoiner** [comment]
Thanks!
I have logged a feedback: https://developercommunity.visualstudio.com/content/problem/1110489/the-unstable-result-issue-with-the-qsort.html

**Comment by TylerMSFT** [comment]
Hi @lifenjoiner ,
I've updated the doc to indicate that if there are elements that are the same, that the order in the sorted array is unspecified.
Thank you for helping us improve the docs.  This change will be live by Monday evening (10/26)
