### ISSUE TITLE
Example and text inconsistent

### ISSUE THREAD

**Issue by stewart-patch** [MicrosoftDocs/cpp-docs#2305]
The text of the example does not match either the figure or the other text on the page. It suggests that the parent class of MyView is CFormView rather than CView as stated in the text and in the figure.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd1ce9c2-a24e-e56a-a284-4274efcea3c5
* Version Independent ID: 424d3dea-cbf7-ae8b-0e5c-5859753c9c68
* Content: [Derived Message Maps](https://docs.microsoft.com/en-us/cpp/mfc/derived-message-maps?view=vs-2019)
* Content Source: [docs/mfc/derived-message-maps.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/derived-message-maps.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @stewart-patch, 
I've updated the topic. The fix will go live by Monday evening (9/28)
