### ISSUE TITLE
Fixes create another warning

### ISSUE THREAD

**Issue by gerikintercede** [MicrosoftDocs/cpp-docs#2309]
The fixes will generate C26493 Don't use C-style casts (type.4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bb5405-5b75-6e6f-dcad-bda6a41665b8
* Version Independent ID: b806753e-dbf6-4ba5-ec3c-bd0ae9f10e10
* Content: [C26451](https://docs.microsoft.com/en-us/cpp/code-quality/c26451?view=vs-2019)
* Content Source: [docs/code-quality/c26451.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26451.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gerikintercede 
True enough. Thanks for reporting the issue, A fix in this and related topics should be visible now.
