### ISSUE TITLE
Error in function description

### ISSUE THREAD

**Issue by SzalonyOgrodnik** [MicrosoftDocs/cpp-docs#2312]
[Enter feedback here]
The return value  of funtion bool locale::operator() is described as -1, 0, 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d59f7-3875-d49b-0344-c96fa364727d
* Version Independent ID: 43ea89e9-bd06-6454-fe44-4cc14c29ccf6
* Content: [locale Class](https://docs.microsoft.com/en-us/cpp/standard-library/locale-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(XLOCALE%2Fstd%3A%3Alocale);k(std%3A%3Alocale);k(locale);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/standard-library/locale-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/locale-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@SzalonyOgrodnik, thank you for letting us know about this problem.
I have fixed it to indicate that it returns true if left is lexicographically less than right, otherwise false.  I also fixed the code sample for this function so that it will compile.
The fix should be live by tomorrow (7/21)
