### ISSUE TITLE
VC++ Compiler warning C5208 (introduced in VS 2019 Update 6 and later) is not documented.

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/cpp-docs#2313]
Compiling some legacy code with VS 2019 Update 7 Pre 4, I hit the following warning (very annoying with Warnings as Errors!). The warning is not documented please document it. Rumours suggest it was introduced in VS 2019 Update 6.

warning C5208: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes

See also:
https://github.com/microsoft/bond/issues/1027
https://developercommunity.visualstudio.com/content/problem/1034754/warning-c5208-a-c20-feature-occurs-when-compiling-1.html
https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019

Note: Reading the following, Microsoft have closed this as not a bug, but it plainly is. Please reopen. A C++ 20 check should not be made if compiling code with C++ 17 standards.

https://developercommunity.visualstudio.com/content/problem/1034754/warning-c5208-a-c20-feature-occurs-when-compiling-1.html

**Comment by corob-msft** [comment]
@MikeDiack 

I'm sorry you've run into difficulty. Documentation for C5208 should appear by next Monday sometime. The change in compiler behavior is not C++20-specific. The C++ standard committee apparently accepted the proposal as a defect report against existing standards, so implementers may apply it to code targeting older versions of the standard.
