### ISSUE TITLE
Add link to documentation about nmake special macros on page NMAKE Fatal Error U1100

### ISSUE THREAD

**Issue by buzz3791** [MicrosoftDocs/cpp-docs#2314]
I appreciate that the page is explaining that only $< is allowed in a batch-mod rule.  But what does $< even mean?  Ideally, this page would link to documentation on nmake macros.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3155a3ba-8215-15f1-f8c0-7a919eacebfa
* Version Independent ID: c0242806-93b8-7415-e333-d7677cc34f1a
* Content: [NMAKE Fatal Error U1100](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/nmake-fatal-error-u1100?view=vs-2019)
* Content Source: [docs/error-messages/tool-errors/nmake-fatal-error-u1100.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/nmake-fatal-error-u1100.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@buzz3791 
Thanks for the report. A fix is in the works to be published Monday.

**Comment by buzz3791** [comment]
@corob-msft Thanks, Colins.  Fix looks great!
