### ISSUE TITLE
Help should provide format of entries of each field

### ISSUE THREAD

**Issue by mdeisher** [MicrosoftDocs/cpp-docs#2315]
The help page says what each field is for but does not specify the format of the entries in each field.  This is pretty useless. The developer can already tell by the name what the field is for.  The developer needs to know the syntax of these entries to make use of the fields.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab1483eb-1b5b-ce7d-0cb2-eda20ee93753
* Version Independent ID: 0d95fbc5-fffd-4091-8928-e225a818c85b
* Content: [C++ Debugging Property Pages](https://docs.microsoft.com/en-us/cpp/build/reference/debugging-prop-pages?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.IVCLocalDebugPageObject.Environment)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/build/reference/debugging-prop-pages.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/debugging-prop-pages.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mdeisher 
While I agree that could be a useful addition, the priority of adding that content compared to the time it would take is hard for us to justify. A motivated contributor is welcome to take this task on.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
