### ISSUE TITLE
strerror language labeling

### ISSUE THREAD

**Issue by squm** [MicrosoftDocs/cpp-docs#2317]
Syntax and Remark sections have listings labeled as "C" language, however it is not C. Overloads are not supported by C

[https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=vs-2019](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=vs-2019)

**Comment by TylerMSFT** [comment]
Thank you, @squm,
I've updated the topic. The fix will go live by Monday evening (9/28)
#please-close
