### ISSUE TITLE
Multiple issues with CLinkCtrl::GetItemUrl

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/cpp-docs#2323]
I am reporting four inter-related issues with `CLinkCtrl::GetItemUrl` (the non-`CString` overload). The documentation states:

> "This function also returns FALSE if the buffer of `szUrl `or `strUrl `is smaller than MAX_LINKID_TEXT."

**My first two issues concern that sentence in a solely documentational sense:**

1. The cited minimum buffer size is wrong by a very large margin. MAX_LINKID_TEXT is defined to be 48, but the actual minimum buffer size deemed acceptable for `GetItemUrl `is 2083 characters (the value of L_MAX_URL_LENGTH).
2. (_DEBUG BUILDS ONLY_) If the supplied buffer is smaller than 2083 characters the function does not return FALSE because it **ASSERT**s first, thereby crashing the application.

**These two issues concern the function's implementation:**

3. The function should not **ASSERT** just because the supplied URL buffer is not huge.

4. The actual minimum buffer size of 4,166 bytes is excessively large. This threshold should either be significantly reduced or removed altogether (my preference). This function should only fail if the buffer is too small for the actual URL - not if it is too small for the largest possible URL that a `CLinkCtrl `can ever contain. The seemingly reasonable value of MAX_LINKID_TEXT is also inappropriate because it is entirely unrelated to the URL length.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8e9b21-3f70-2610-ab3a-b49a668d32bd
* Version Independent ID: e5ad1204-54a7-d7a2-8600-83384cb38578
* Content: [CLinkCtrl Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/clinkctrl-class?view=vs-2019)
* Content Source: [docs/mfc/reference/clinkctrl-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/clinkctrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
