### ISSUE TITLE
COleCmdUI Class Documented header file does not exist 

### ISSUE THREAD

**Issue by mnatsuhara** [MicrosoftDocs/cpp-docs#2326]
On the page documenting the [COleCmdUI class](https://docs.microsoft.com/en-us/cpp/mfc/reference/colecmdui-class?view=vs-2019#requirements), the listed header file does not exist.  Perhaps it should be **afxdocob.h** instead of **afxdocobj.h**?

**Comment by corob-msft** [comment]
@mnatsuhara 
Thanks for the report. A fix should appear Monday.
