### ISSUE TITLE
No rule to make target 'libpthread.so', needed by '../VisualGDB/Debug/ControlTest'.  Stop.

### ISSUE THREAD

**Issue by liebingbubing** [MicrosoftDocs/cpp-docs#2329]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=vs-2019)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@liebingbubing, sorry for the delay on this. We can't quite make out how you ran into this. If this is still a problem, could you provide more repro details?

**Comment by TylerMSFT** [comment]
@liebingbubing , please reopen if you have more information to share about the repro.
