### ISSUE TITLE
Missing linker error information

### ISSUE THREAD

**Issue by cowlinator** [MicrosoftDocs/cpp-docs#233]
The page https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-errors-and-warnings is missing any information about linker error LNK1318, which I received when building a vc++ project with msbuild.  ( "LINK : fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006E7)'")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f351badb-0958-c6a9-9830-134f9247017f
* Version Independent ID: 3e4eb760-6c7d-279a-9833-36e6f1ad1221
* Content: [Linker Tools Errors and Warnings](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-errors-and-warnings#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md)
* Service: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
To follow up, here's what's likely to be the generic LNK1318 advice: perform a clean of your build directories, and then do a full build of your solution. Reboot your computer, or check for stray or hung mspdbsrv.exe processes and kill them in TaskMan. Turn off AV checks in your project directories. Use the /Zf flag if using /MD with MSBuild or another parallel build process. Try building by using the 64-bit hosted toolset. Serialize linking to mitigate parallel link issues if needed.

**Comment by corob-msft** [comment]
Content is live at [Linker Tools Error LNK1318](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1318).

**Comment by cowlinator** [comment]
This is actually very satisfying.  Maybe I'm jaded or something, but I honestly wasn't expecting much.  I was able to resolve my issue with /Zf, and I'm very glad to see that this and LNK4020 have been added to the documentation.  Thank you, corob.
