### ISSUE TITLE
Incorrect xor operator description

### ISSUE THREAD

**Issue by honglh** [MicrosoftDocs/cpp-docs#2336]
[Enter feedback here]

```
If the bit in the first operand is 0 and the other bit is 1, the corresponding result bit is set to 1. Otherwise, the corresponding result bit is set to 0.
```

Since the order of operands does not matter, the statement is not accurate saying `0^1` is `1` and  "Otherwise"  result is `0` (implying `1^0` is `0`)

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5ca370-f857-8c5e-746f-059c1badaa50
* Version Independent ID: 2b6f89b5-6a24-47d7-56cf-f9fd89813df2
* Content: [Bitwise exclusive OR operator: ^](https://docs.microsoft.com/en-us/cpp/cpp/bitwise-exclusive-or-operator-hat?view=vs-2019)
* Content Source: [docs/cpp/bitwise-exclusive-or-operator-hat.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/bitwise-exclusive-or-operator-hat.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@honglh Thanks for the report. Article uipdated with accurate description.
