### ISSUE TITLE
int vs long confusion

### ISSUE THREAD

**Issue by vukovinski** [MicrosoftDocs/cpp-docs#2337]
As a long-time C# programmer and a first-time C++ learner, the difference between int and long was not apparent to me until I googled with bing for the answer on some other site. To make myself more clear:

by the C++ standard, and having in mind all the different platforms C++ programs could run on,

int is guaranteed to be at least 16 bits long,
whereas long is guaranteed to be 32 bits long,

however,

on most common 32-bit and 64-bit platforms,

int is implemented as having 32 bits of integer representation.

I would only like for this page of cpp-docs to **stress** this fact.

P.S. By the way, thank you for doing great work with Microsoft Docs. It does make an impact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a22c8bac-8d8a-a9c8-4167-26f21f7e4a78
* Version Independent ID: cf220c62-e61f-c64e-8e68-075d9273e305
* Content: [C++ type system](https://docs.microsoft.com/en-us/cpp/cpp/cpp-type-system-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/cpp-type-system-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-type-system-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Implementation-specific versus standard-mandated sizes clarified; added link to relevant topic.
