### ISSUE TITLE
What about a string?

### ISSUE THREAD

**Issue by CaleMcCollough** [MicrosoftDocs/cpp-docs#234]
None of the official literature covers the question of if a string is a POD type. This document seams to point that a string is not a POD type because the typical implementation is NOT contiguous, but could just consider the start of the string as a struct with an arbitrary number of char members large enough to guarantee a nil-term char; yes we could THEORIZE a string that fits the POD definition, but does this fulfill the definition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249da7e2-4135-6468-221b-d62df3af0f22
* Version Independent ID: 2e68cba5-e743-2d88-7b4c-7bb6f79c54cd
* Content: [Trivial, standard-layout, POD, and literal types](https://docs.microsoft.com/en-us/cpp/cpp/trivial-standard-layout-and-pod-types)
* Content Source: [docs/cpp/trivial-standard-layout-and-pod-types.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/trivial-standard-layout-and-pod-types.md)
* Service: **visual-cpp**
* GitHub Login: @Saisang

**Comment by corob-msft** [comment]
I suppose it's possible to imagine a `std::string` implementation that could be POD, if there weren't a whole bunch of other constraints on its behavior. It's pretty easy to use the `is_trivial<string>()` and `is_standard_layout<string>()` template functions to see that  `std::string` is neither, and hence not POD.

I'm not going to make a change here. If we had to explicitly call out every class in the standard library that's not a POD, or detail exactly why, it would be a really long list, and that's not what this topic is about. If you're curious, you can use these functions to find that out yourself, and the functions here make that discovery trivial (pun intended).

**Comment by CaleMcCollough** [comment]
Sorry I did not mean std::string, I meant abstract string including a char*. You cannot extend a char*, thus char* is a POD type, but the pointer to string is not contiguous under most circumstances. One could consider the packed data in memory a POD type that contains an abstract string, but that would require a user-defined constructor to ensure the nil-term char is there else the string is no longer an abstract string and thus has undefined behavior.

I spoke with a doctor of CS/AI today at my engineering school and a string is not a POD type because a UTF-8 string is a polymorphic subclass of class Unicode, which also has a subclassses UTF-16 and UTF-32. There is no vtable but it is possible to use the alignment of the first byte of the pointer to the string to store if the string is ASCII, UTF-8, UTF-16, or UTF-32 by using modulo 4 of the pointer being 0,1, 2, or 4 respectively.

**Comment by mikeblome** [comment]
The C++ specification is very specific about what qualifies as POD, and doesn't permit much debate about it, which is probably a good thing. This would be a good homework assignment: create a MyString class for which is_trivial<MyString>() and is_standard_layout<MyString>() both return true :-)
