### ISSUE TITLE
Need to add documentation for new properties in Advanced page

### ISSUE THREAD

**Issue by olgaark** [MicrosoftDocs/cpp-docs#2342]
Please add documentation for recently added 'Copy ...' properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b82557-4a26-70f9-c7ae-ca21c91318ec
* Version Independent ID: d93c9b26-7bde-7186-0d27-b37ade129b3c
* Content: [Advanced Property Page (Project)](https://docs.microsoft.com/en-us/cpp/build/reference/advanced-property-page?view=vs-2019)
* Content Source: [docs/build/reference/advanced-property-page.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/advanced-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Completed a year ago, but not closed at the time.
