### ISSUE TITLE
Maybe some more detail required

### ISSUE THREAD

**Issue by heuanhomos** [MicrosoftDocs/cpp-docs#2346]
Using an exe built with vs2008 - i needed to copy the debug dlls and manifests from the non redist folder (i guess that matches method 2), but got a sxs error.

I ran sxstrace - the version number in the manifest didn't match what the exe wanted. Putting in the older version of the dlls had an incorrect entry point. I had to edit the manifest file to change the version (also removed the sha details) whilst using the new dlls. No idea where these version numbers reside in the vcproj!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3ac071-f6e9-da5a-6fa5-577da31bd308
* Version Independent ID: 92854ad2-954f-e12f-7f7f-f9cec8924548
* Content: [Preparing a Test Machine To Run a Debug Executable](https://docs.microsoft.com/en-us/cpp/windows/preparing-a-test-machine-to-run-a-debug-executable?view=vs-2019)
* Content Source: [docs/windows/preparing-a-test-machine-to-run-a-debug-executable.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/preparing-a-test-machine-to-run-a-debug-executable.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@heuanhomos 
My understanding is that debug DLL version matching information doesn't come from the project file. It's either recorded in the PDB file, or for SxS assemblies, in the manifest. The linker records this version info when it generates the PDBs and manifests. If you're doing new builds with the 2008 toolset, it should pick up whatever libraries you use for your build. If it's an old binary, locating the PDB and debug DLLs you need is up to you; it's a good idea to archive these whenever you create a binary for precisely this purpose. Doing as you've done, trying to make a slightly different version of some library work instead, is sometimes possible, but it's not recommended. I don't expect we'll explain how to do something we don't recommend. 

I'm currently closing the issue as out of scope, but it's entirely possible that I've misunderstood what detail you're asking for, and something should be clarified in the docs. If you can explain what you're looking for in this article, and it's in scope for the article, I'm happy to reconsider, and reopen the issue.
