### ISSUE TITLE
Link to "Distributable Code for Microsoft Visual Studio 2015 and Microsoft Visual Studio 2015 SDK" does not work

### ISSUE THREAD

**Issue by aasmundbo** [MicrosoftDocs/cpp-docs#235]
I get 404 when clicking that link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637a643b-3eb6-8a64-4979-ccfc07822681
* Version Independent ID: 86434874-40d2-d1d0-5551-a60620fad426
* Content: [Redistributing Visual C++ Files](https://docs.microsoft.com/en-us/cpp/ide/redistributing-visual-cpp-files)
* Content Source: [docs/ide/redistributing-visual-cpp-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/redistributing-visual-cpp-files.md)
* Service: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for spotting that issue. It looks like the link should go to 
https://docs.microsoft.com/visualstudio/productinfo/2015-redistribution-vs instead. I've updated the fwlink target, and this should work now.
