### ISSUE TITLE
VERSION <major>[.<minor>[.<patch>[.<tweak>]]]]         [DESCRIPTION <project-description-string>]         [HOMEPAGE_URL <url-string>]         [LANGUAGES <language-name>...])

### ISSUE THREAD

**Issue by cabra27l** [MicrosoftDocs/cpp-docs#2350]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53a6ab65-63a0-360a-da0e-a33c09028036
* Version Independent ID: cd1038f8-3b50-8c29-847f-7749d2ba78cf
* Content: [Program Structure](https://docs.microsoft.com/en-us/cpp/c-language/program-structure?view=vs-2019)
* Content Source: [docs/c-language/program-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/program-structure.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cabra27l 
I'm sorry, this doesn't look like actionable feedback, so I'm closing it. Have you found an issue on the Program Structure page? I can reopen the issue if you can clarify what's wrong.
