### ISSUE TITLE
VS docs for ios_base::openmode are incorrect

### ISSUE THREAD

**Issue by Mark44-AVX** [MicrosoftDocs/cpp-docs#2353]
The flags for ios_base::openmode aren't shown. Instead, what are shown are the flags for ios_base::iostate. See https://docs.microsoft.com/en-us/cpp/standard-library/ios-base-class?view=vs-2019#ios_base, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b5cdbd-d3da-90b3-897d-614c0e9a9dd5
* Version Independent ID: 471a8fc6-47c1-d3be-0178-53e7d83c1d83
* Content: [ios_base Class](https://docs.microsoft.com/en-us/cpp/standard-library/ios-base-class?view=vs-2019#openmode)
* Content Source: [docs/standard-library/ios-base-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/ios-base-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Mark44-AVX , thank you for bringing that to our attention. Fixed. You should see the updated content by the end of tomorrow (10/27).
