### ISSUE TITLE
Documentation for EnablePaneMenu is non-existent

### ISSUE THREAD

**Issue by jd-young** [MicrosoftDocs/cpp-docs#2354]
Hi,

The name of the method is EnablePaneMenu, and the complete documentation to explain what this method does is this:

Enables or disables the automatic handling of the pane menu.

This barely expands what the name of the function says.  It does not give _any_ additional information as to what this method does.  This documentation page adds no value.

Adding value?  For example...

- What is a pane menu? If there is a better explanation, then add a link.
- Why should I call this method?  What does it do?
- What does it add to my application?  Should I call this method?  What are the benefits, and what are the drawbacks?

This is typical of Microsoft documentation and it rips ma knittin'.

Cheers,

-John
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15ed57b-7487-081b-5d89-55b5ba673448
* Version Independent ID: 42302a29-b8a7-32f6-6f0e-af93ce903d20
* Content: [CFrameWndEx Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cframewndex-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cframewndex-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cframewndex-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
