### ISSUE TITLE
where's std::format (P0645)

### ISSUE THREAD

**Issue by tvaneerd** [MicrosoftDocs/cpp-docs#2357]
std::format (P0645) isn't mentioned in conformance - not even a "No".
Maybe it should be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C++ language conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tvaneerd 
Thanks for the report. The docs have been updated with the latest set of library feature additions for C++20. The `<format>` header and functions aren't implemented yet. For progress, you can track the Microsoft/STL [C++20 Features](https://github.com/microsoft/STL/projects/3) project on GitHub.
