### ISSUE TITLE
C26443 NO_EXPLICIT_DTOR_OVERRIDE, Core Guidelines changed

### ISSUE THREAD

**Issue by othrayte** [MicrosoftDocs/cpp-docs#2359]
The "current consensus on the Core Guidelines" has changed and this page is now out of date.

If states
> The current consensus on the Core Guidelines is to exclude destructors from the 'override explicitly' recommendation.

The Core Guidelines was changed in https://github.com/isocpp/CppCoreGuidelines/pull/1448 to
> [affirm] that all virtual functions, including destructors, should be declared exactly one of virtual, override, or final.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e21fe6-6192-128e-b60a-9ecd81dc95a2
* Version Independent ID: c23a36d9-fa3c-c7ae-9fd2-0159537927f5
* Content: [C26443](https://docs.microsoft.com/en-us/cpp/code-quality/C26443?view=vs-2019)
* Content Source: [docs/code-quality/c26443.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26443.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@othrayte 
Thanks for the report. I'm not so concerned about the page being out of date if the warning has been removed. If it still happens, then it's a product issue that should be reported on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html).

@sunnychatterjee FYI. Does code analysis still emit this warning?

**Comment by sunnychatterjee** [comment]
Yes, the code analysis still emits this warning. @othrayte could you please file an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) to fix this on the checker side?

**Comment by othrayte** [comment]
Ok, raised on Developer Community. https://developercommunity.visualstudio.com/content/problem/1215752/cpp-core-guidelines-c128-require-virtualoverridefi.html

**Comment by othrayte** [comment]
Closing as this was fixed in 7957d0f following removal of the warning from CppCoreCheck.
