### ISSUE TITLE
Un

### ISSUE THREAD

**Issue by wkeilholz** [MicrosoftDocs/cpp-docs#2363]
I'm trying to add a WinForm control to an MFC Dialog following this tutorial, but I am unable to add the reference to the .NET control to the MFC application : when I select WindowsFormsControlLibrary1 after chosing Add...Reference on MFC01 (step 4), I get 'A reference to WinFormControlLibrary1 cannot be added because it is  incompatible with this project'.

I'm using VS 2019. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6b9db41-a73f-73a3-fd0e-f4b756f38eb2
* Version Independent ID: 0970feb1-0b72-48c3-f5a0-fd568df9e36a
* Content: [How to: Create the User Control and Host in a Dialog Box](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box?view=vs-2019)
* Content Source: [docs/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by Digilee** [comment]
I'm having the exact same issue, but with VS2017

**Comment by corob-msft** [comment]
This tutorial needs a rewrite to bring UI elements and project properties up-to-date. Now that you can target both the classic .NET Framework and .NET Core, you need to create the hosted controls project as a **Windows Forms Control Library (.NET Framework)** project. In the MFC project's Property Pages dialog, you need to change the Platform value at the top to All platforms before making the property changes. In VS 2019, the Common Language Runtime support section has moved to the Advanced node. It might help to set a value in the .NET Target Framework Version to match the value in your WinForms project. I set the WinForms project to target .NET Framework 4.8, and in the MFC01 project, I set NET Target Framework Version to 4.8. These changes were sufficient to add the project reference without the incompatible project type error.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
