### ISSUE TITLE
_cwait example needs updates

### ISSUE THREAD

**Issue by bhaible** [MicrosoftDocs/cpp-docs#2367]
In the example, the type of the <code>nPid</code> member in <code>struct PROCESS</code> ought to be changed from <code>int</code> to <code>intptr_t</code>. This is needed because

* The return type of <code>_spawnl</code> was changed from <code>int</code> to <code>intptr_t</code>,
* The type of the second argument of <code>_cwait</code> was changed from <code>int</code> to <code>intptr_t</code> as well.

Also, the name <code>nPid</code> is a misnomer, as the value represents a process handle and not a process id. Recall that in Windows, a process handle and a process id are different concepts, see https://docs.microsoft.com/en-us/windows/win32/procthread/process-handles-and-identifiers . I would suggest to rename this member to -- using Hungarian notation -- <code>hProcess</code>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c70d863-eac1-30e5-0650-00fdaf076ae9
* Version Independent ID: af33ee42-e7d0-517d-f6d8-03abc88056b2
* Content: [_cwait](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cwait?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/cwait.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/cwait.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@bhaible, thanks for catching this. I've updated the sample and it should be live Monday, 10/26.
Appreciate you helping us keep the docs current!
