### ISSUE TITLE
Title/headers should use "Segoe UI Light" 

### ISSUE THREAD

**Issue by ianpan870102** [MicrosoftDocs/cpp-docs#2369]
[Enter feedback here]
The titles/headers would look significantly better if they used "Segoe UI Light" instead of "Segoe UI", as specified by Microsoft's design language.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2170bcdc-1b81-38fb-c4fa-013d945774e1
* Version Independent ID: 474faf3b-3c28-18ae-4a8b-d8028315aceb
* Content: [What's new for C++ in Visual Studio](https://docs.microsoft.com/en-gb/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=vs-2019)
* Content Source: [docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/what-s-new-for-visual-cpp-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ianpan870102 
I'm afraid I can't do much about this issue. The C++ Docs team has no say over the Microsoft Docs sitewide style and design choices. If you'd like, you can take this issue up with the design team. One way to do that is to send feedback to the [Docs Team Blog](https://docs.microsoft.com/en-us/teamblog/updating-navigation) and add `FYI @dend` to get the attention of the blog author, who probably has good connections to the design team. Best of luck.

**Comment by ianpan870102** [comment]
@corob-msft I appreciate the reply Colin! I'll try your suggestion.
