### ISSUE TITLE
Give full documentation for the different versions of bitmap headers

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/cpp-docs#237]
As a bitmap management library developer, it would be extremely useful to have access to clear documentation describing the BITMAPV2INFOHEADER and BITMAPV3INFOHEADER. The current documentation seems to skip it for no obvious reason: https://msdn.microsoft.com/en-us/library/dd183376(VS.85).aspx

This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/60

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b26334-088f-b7d7-b8d0-3f8c5cd733a4
* Version Independent ID: b5cf26e4-5d88-1675-3757-e0928febb95f
* Content: [BITMAPINFO Structure](https://docs.microsoft.com/en-us/cpp/mfc/reference/bitmapinfo-structure)
* Content Source: [docs/mfc/reference/bitmapinfo-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/bitmapinfo-structure.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Powerhelmsman This is not a C++ documentation issue, it's a Windows Dev Center documentation issue. There's an MFC BITMAPINFO wrapper, but it refers to [the Windows BITMAPINFOHEADER documentation](https://msdn.microsoft.com/en-us/library/dd183376(v=vs.85).aspx) for details. This issue, [MicrosoftDocs/feedback#60](https://github.com/MicrosoftDocs/feedback/issues/60) should be reopened and reassigned to the Windows dev docs team.
