### ISSUE TITLE
ARM64 ABI: Inconsistent handling of aggregate structs

### ISSUE THREAD

**Issue by richard-townsend-arm** [MicrosoftDocs/cpp-docs#2371]
Hi folks: I've got an interesting edge-case in the ABI where Clang and MSVC behave differently (this shows up in a Chromium test suite called `dawn_end2end_tests`). What the tests do is they create an empty D3D12_RESOURCE_DESC and return it on the stack (see a cut-down demonstrator at https://godbolt.org/z/jE8538).

Here, D3D_RESOURCE_DESC is 56 bytes, it's an aggregate type, no user-provided constructors, no private or protected non-static data members, no base classes, and no virtual functions, trivial copy-assignment operator, and it has a trivial destructor, so it should fall into this case:

* For types greater than 16 bytes, the caller shall reserve a block of memory of sufficient size and alignment to hold the result. The address of the memory block shall be passed as an additional argument to the function in x8. The callee may modify the result memory block at any point during the execution of the subroutine. The callee isn't required to preserve the value stored in x8.

However, that's not actually what happens, if I disassemble the `main()` function linked in the demonstrator, space gets allocated and passed in x1.
```
|main|  PROC
|$LN8|
        str         lr,[sp,#-0x10]!
        sub         sp,sp,#0x40               ; Allocate space to hold the D3D12_RESOURCE_DESC plus a 8-byte class
        add         x1,sp,#8                    ; Increment to get original sp - 56 bytes to hold the D3D_RESOURCE_DESC in X1
        mov         x0,sp                        ; $this pointer is at the base of stack, passed in X0
        bl          |virtual D3D12_RESOURCE_DESC B::GetResource(void) __ptr64|
        ldr         w0,[sp,#8]
        add         sp,sp,#0x40
        ldr         lr,[sp],#0x10
        ret

        ENDP  ; |main|
```

Clang (the official compiler for Chromium/Edge) follows the current wording of the spec and allocates room in X8 (https://godbolt.org/z/rs7G7a). Are there additional cases covered by MSVC which have not been accounted for in the specification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee4db12-6226-a1e6-6c8c-d2d5d77ae92e
* Version Independent ID: 180f6f4e-d5a9-88cd-c297-6cba5b16289e
* Content: [Overview of ARM64 ABI conventions](https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=vs-2019#feedback)
* Content Source: [docs/build/arm64-windows-abi-conventions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/arm64-windows-abi-conventions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@richard-townsend-arm 
I can't fault your analysis, but it's not reaching the right audience. This sounds more like an issue for the product engineers than for the docs team, at least to start with. This a question for the Visual Studio [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site, which the dev team looks at directly. If it's an ABI violation, they can fix it. If it's a gray area, they can tell us what to add or clarify in the docs. If you'd be kind enough to report it there, and come back here and link your issue, I'd appreciate it.

**Comment by richard-townsend-arm** [comment]
OK, apologies about that: I've raised it here. Will re-open this issue if I hear back.

**Comment by corob-msft** [comment]
Thanks!

**Comment by corob-msft** [comment]
@richard-townsend-arm 
A docs fix is in the works, and should appear tomorrow.
