### ISSUE TITLE
Missing linker warning LNK4020

### ISSUE THREAD

**Issue by cowlinator** [MicrosoftDocs/cpp-docs#238]
This article contains no information about Linker Tools Warning LNK4020 (e.g. "warning LNK4020: a type record in 'c:\proj\x64\Release\vc141.pdb' is corrupted; some symbols and types may not be accessible from the debugger")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f351badb-0958-c6a9-9830-134f9247017f
* Version Independent ID: 3e4eb760-6c7d-279a-9833-36e6f1ad1221
* Content: [Linker Tools Errors and Warnings](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-errors-and-warnings)
* Content Source: [docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-errors-and-warnings.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I'll add a document for this message, but it's unlikely to tell you anything you don't already know. This error occurs when the linker detects an issue in a PDB file with a corrupt type record. Your best bet is to clean and rebuild. If the problem persists, try cleaning and rebuilding individual projects without parallel builds enabled. A common suspect in corrupt type records in PDB files is the mspdbsrv.exe file, which ironically is supposed to help with multiple clients accessing a single PDB file, but is as often as not implicated when it fails to work. It's unlikely to cause a problem if only one link process is running at a time.

**Comment by corob-msft** [comment]
Content is live at [Linker Tools Warning LNK4020](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4020).
