### ISSUE TITLE
Documentation for parameter "bEndSession" in member "CloseAllDocuments(BOOL bEndSession)" needs better explanation.

### ISSUE THREAD

**Issue by Hrnkas** [MicrosoftDocs/cpp-docs#239]
"Specifies whether or not the session is being ended. It is TRUE if the session is being ended; otherwise FALSE." - this is no more Information than revealed through the name of the variable itself. What kind of Session? What is a session (maybe add a link to the explanation about sessions)?
What does it mean? Can I open another document after calling this function with TRUE in parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b7930d-1635-786d-422e-391d04a6c61f
* Version Independent ID: ebfd875e-d39f-cea2-3116-66a01feee08f
* Content: [CDocTemplate Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cdoctemplate-class#feedback)
* Content Source: [docs/mfc/reference/cdoctemplate-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cdoctemplate-class.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Hrnkas It looks like the bEndSession parameter isn't actually used in the method implementation. You can see the source code on your machine. The exact path depends on which version of VS you have installed. Mine is at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\atlmfc\src\mfc. Thanks for your feedback. I will update the documentation to note this fact.
