### ISSUE TITLE
wrong syntax

### ISSUE THREAD

**Issue by markyin** [MicrosoftDocs/cpp-docs#2390]
wrong with ")"
cout << Values.dValue) << endl;

The correct one:
cout << Values.dValue << endl;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a72b499a-3b65-4005-32dd-a6be9100a975
* Version Independent ID: aaa2c0c5-677c-4fb6-cca8-9d4a7aa9122f
* Content: [Unions](https://docs.microsoft.com/en-us/cpp/cpp/unions?view=vs-2019)
* Content Source: [docs/cpp/unions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unions.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@markyin 
Thanks for the report. An updated version is now live.
