### ISSUE TITLE
In the Debugger Type list, select GPU Only is incorrect for Windows 10

### ISSUE THREAD

**Issue by rchiodo** [MicrosoftDocs/cpp-docs#240]
Step 4 for debugging the GPU is incorrect on Windows 10. Leave the debugger type as Auto.
Additionally AMP debugging is broken on RS3 (build 1703). The bug was fixed in a patch (build 17134). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec054a56-bc4a-198e-6fc1-8a9fbb78c2c2
* Version Independent ID: 0bb33ae4-3fb1-8683-b3c2-6773e3b20cfb
* Content: [Walkthrough: Debugging a C++ AMP Application](https://docs.microsoft.com/en-us/cpp/parallel/amp/walkthrough-debugging-a-cpp-amp-application)
* Content Source: [docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by Mikejo5000** [comment]
Yes, I'll take a look at it.
