### ISSUE TITLE
Rounding comparison

### ISSUE THREAD

**Issue by cadop** [MicrosoftDocs/cpp-docs#2401]
It is a bit confusing to show the output of the different rounding methods on different numbers. It would be nice (maybe in a separate section) to see examples of behavior when the values are the same. 

```
#include <math.h>
#include <stdio.h>

int main( void )
{
   double x      = 2.4999999;
   long double y = 2.4999999;

   printf("round(%f) is %.0f\n", x, round(x));
   printf("round(%f) is %.0f\n", -x, round(-x));
   printf("roundf(%f) is %.0f\n", x, roundf(x));
   printf("roundf(%f) is %.0f\n", -x, roundf(-x));
   printf("roundl(%Lf) is %.0Lf\n", y, roundl(y));
   printf("roundl(%Lf) is %.0Lf\n", -y, roundl(-y));
}
```

Outputs:
```
round(2.500000) is 2
round(-2.500000) is -2
roundf(2.500000) is 3
roundf(-2.500000) is -3
roundl(2.500000) is 2
roundl(-2.500000) is -2
```
 
Likewise;

```
#include <math.h>
#include <stdio.h>

int main( void )
{
   double x      = 2.4999998;
   long double y = 2.4999998;

   printf("round(%f) is %.0f\n", x, round(x));
   printf("round(%f) is %.0f\n", -x, round(-x));
   printf("roundf(%f) is %.0f\n", x, roundf(x));
   printf("roundf(%f) is %.0f\n", -x, roundf(-x));
   printf("roundl(%Lf) is %.0Lf\n", y, roundl(y));
   printf("roundl(%Lf) is %.0Lf\n", -y, roundl(-y));
}
```

Outputs

```
round(2.500000) is 2
round(-2.500000) is -2
roundf(2.500000) is 2
roundf(-2.500000) is -2
roundl(2.500000) is 2
roundl(-2.500000) is -2
```
 
* I used cpp.sh to generate examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ea9619-77fc-a1b9-5833-773ee494e864
* Version Independent ID: 90c0529e-995b-eb09-da2a-03232f1a61be
* Content: [round, roundf, roundl](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/round-roundf-roundl?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/round-roundf-roundl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/round-roundf-roundl.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@cadop, I think you make a good point. I will add this to my backlog.

**Comment by TylerMSFT** [comment]
Thank you, @cadop,
I've updated the topic. The fix will go live by Monday evening (9/28)
