### ISSUE TITLE
C runtime _DLL symbol abused,

### ISSUE THREAD

**Issue by jaykrell** [MicrosoftDocs/cpp-docs#2411]
This article abuses the symbol `_DLL` which is reserved for the C runtime,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd9724a-4824-5784-83a7-acaf9099610a
* Version Independent ID: a93349dd-05fe-f661-e084-b8313a8214f2
* Content: [How to: Use Existing C++ Code in a Universal Windows Platform App](https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019&source=docs#feedback)
* Content Source: [docs/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jaykrell 

I'm not sure where my comment went. When I added the 'needs more info` tag, I meant to include a comment to the effect that `_DLL` is the MSVC implementation-specific (and hence of form underscore-capital letter) macro used during compilation to indicate that the **`/MD`** or **`/MDd`** compiler option was set. It's described in our article on [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros). I don't see what's wrong with the usage in this example. What am I missing?

**Comment by corob-msft** [comment]
A fix should appear in the published content tomorrow.
