### ISSUE TITLE
_leave(__leave) ';' statement is missing in jump statement section.

### ISSUE THREAD

**Issue by mtehk** [MicrosoftDocs/cpp-docs#2413]
Hello,

The _leave/__leave  keyword is listed in the C Language Keyword Summary. It is not listed as a jump statement in either the Phrase summary or in Jump Statements.

Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21945129-819f-b824-1448-7dcf82489dbb
* Version Independent ID: 4208a09f-059d-e29c-da34-6f37f12f2ca6
* Content: [Statements (C)](https://docs.microsoft.com/en-us/cpp/c-language/statements-c?view=vs-2019)
* Content Source: [docs/c-language/statements-c.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/statements-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mtehk 
That's true. The grammar summary is incomplete. I've added the **`__leave`** keyword with a footnote that it's context-specific.
