### ISSUE TITLE
Conditions allowing C4275 warning to be ignored are not completely clear

### ISSUE THREAD

**Issue by DanBlanchard** [MicrosoftDocs/cpp-docs#2422]
The documentation lists several conditions where C4275 may be ignored as "if you are deriving from a type in the C++ Standard Library, compiling a debug release (/MTd) and where the compiler error message refers to _Container_base".

It's not clear to me if ALL these conditions need to apply, or if ANY of these conditions need to apply before the warning can be ignored.

It might be useful if the documentation also mentioned whether or not using different versions of the compiler to build a DLL that exports a C++ class and the application that imports the C++ class is guaranteed to work - and if not, which compiler versions are compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2df25-8de5-6ba4-c4dc-b77327e10bcb
* Version Independent ID: a9213cb7-68c1-e276-8e8d-aa6e84888047
* Content: [Compiler Warning (level 2) C4275](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4275?view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-2-c4275.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-2-c4275.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DanBlanchard 

The specific combination of *all* those conditions represents a case where the warning is spurious. That combination might not even cause a warning in the current library anymore. Basically, we documented an implementation bug at some point, and we were never told if it was fixed. I'll follow up to see if that special case still needs to be documented.

If you see the C4275 warning, you shouldn't ignore it. The compiler has detected a problem with your DLL interface. Usually, something required to instantiate an exported class is missing from your exports. We've got other documentation that goes into more details: [Using dllimport and dllexport in C++ Classes](https://docs.microsoft.com/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=vs-2019) and [General Rules and Limitations](https://docs.microsoft.com/cpp/cpp/general-rules-and-limitations?view=vs-2019). The C4275 article should probably include these links, too.

How to fix the issue depends on what you're doing. If you can move more of your library into headers, that can eliminate some causes of C4275. Virtual classes with factory functions that keep creation and destruction internals inside the DLL can work well. And don't do things like throw exceptions from your DLL and expect your client to catch them. Compiler versions can matter, but class layout and calling convention compatibility matter more. Compile both DLL and client with the same compiler switches.
