### ISSUE TITLE
Incorrect capitalization of types

### ISSUE THREAD

**Issue by dajoke** [MicrosoftDocs/cpp-docs#2424]
Documentation cites "long"s throughout, when it is really "LONG". The first is signed, the second is unsigned. As a result the documentation is misleading, and code produces many errors... Applies to InterlockedIncrement as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5995a9c2-6454-1b80-d086-7b53f8638995
* Version Independent ID: d24d17dc-e5f6-ab1d-48dc-dccea29ae92c
* Content: [_InterlockedDecrement intrinsic functions](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockeddecrement-intrinsic-functions?view=vs-2019)
* Content Source: [docs/intrinsics/interlockeddecrement-intrinsic-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/interlockeddecrement-intrinsic-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dajoke 

Thanks for the report. It doesn't match my experience. `LONG` has been a typedef for a (signed) `long` in the Windows headers for, literally, decades. And, when I use IntelliSense in the IDE and hover over an `_InterlockedDecrement` call, it shows the return type as `long`. (It also reports the argument is a `volatile` pointer, which isn't reflected in the docs.) Where do you see a definition that uses LONG as an unsigned type for the return value?

**Comment by corob-msft** [comment]
Closing. We'll reopen on contrary evidence.
