### ISSUE TITLE
Required VS components

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/cpp-docs#243]
To compile projects with `/Qspectre` switch, these VS 2017 components must be installed:

* VC++ 2017 version 15.7 v14.14 Libs for Spectre (x86 and x64)
* Visual C++ ATL (x86/x64) with Spectre Mitigations
* Visual C++ MFC for x86/x64 with Spectre Mitigations

If the **VC++ 2017 version 15.7 v14.14 Libs for Spectre (x86 and x64)** is not installed, compiler will report this error: **warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.**

If you don't install ATL and/or MFC libraries, the compiler will not report the error above, but the linker will fail with error like **fatal error LNK1104: cannot open file 'oldnames.lib'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad87698-8cd7-aaf9-87b1-eaf8c290017f
* Version Independent ID: be796703-261a-ec99-11e6-d023aa7ee849
* Content: [/Qspectre](https://docs.microsoft.com/en-us/cpp/build/reference/qspectre)
* Content Source: [docs/build/reference/qspectre.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/qspectre.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @jozefizso we're investigating.
