### ISSUE TITLE
c++ amp on arm64

### ISSUE THREAD

**Issue by fobrs** [MicrosoftDocs/cpp-docs#2430]
It seems C++ AMP on ARM64 is supported in Visual Studio 2019 16.8.0 preview 2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58e07cc-2b1b-668a-5d9d-73afd80ce1c6
* Version Independent ID: 2b3cbb85-9f6c-2ef2-285a-5af0dc64e31d
* Content: [C++ AMP Overview](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-overview?view=vs-2019)
* Content Source: [docs/parallel/amp/cpp-amp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/cpp-amp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @fobrs. Unfortunately, C++ AMP isn't and won't be supported on ARM64.
