### ISSUE TITLE
C++ operators

### ISSUE THREAD

**Issue by pmnadkarni** [MicrosoftDocs/cpp-docs#2435]
When I looked for the ^ operator, the documentation only talks about XOR. It fails to mention that, as a suffix to a class name, it lets you declare (and optionally initialize, using gcnew) a managed pointer to an instance of a .NET framework object. 
Against the arrow operator (->) the documentation should also tell you the members of variables that have been declared with the ^suffix must be accessed using the -> (arrow) operator.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b130b32-a542-990a-9202-dfeeccbd2a6e
* Version Independent ID: b3a17ea8-b2fa-9134-faa0-1c6dea905d05
* Content: [C++ built-in operators, precedence, and associativity](https://docs.microsoft.com/en-us/cpp/cpp/cpp-built-in-operators-precedence-and-associativity?view=vs-2019)
* Content Source: [docs/cpp/cpp-built-in-operators-precedence-and-associativity.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-built-in-operators-precedence-and-associativity.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pmnadkarni 

The *handle to object* operator ^ (often called *hat*) used as you describe is not part of the C++ language, so it's not included in the standard C++ documentation. It's used in the Microsoft-specific C++/CLI and C++/CX dialects supported by the compiler for .NET and Windows Runtime coding, respectively,  You'll find it described in the Component Extensions section of the documentation. Here are a couple of instances:

[Handle to Object Operator (^)  (C++/CLI and C++/CX)](https://docs.microsoft.com/en-us/cpp/extensions/handle-to-object-operator-hat-cpp-component-extensions?view=vs-2019)

[Quick Reference (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/quick-reference-c-cx?view=vs-2019)

Hopefully, those articles should address your questions.

**Comment by pmnadkarni** [comment]
Hello Colin,


Thank you for taking the trouble to reply, and supply the appropriate links.


I know that the ^ operator is not standard C++, which I'm familiar with from working on other platforms, and that is why I wasted so much energy tracking its specific .NET usage down. I entered  the search term "^ operator C++ Microsoft " into Google,  I was taken to the C++ operators page. The "Handle to Object" page is #10 on the list. However, since the first 9 pages, all from docs.microsoft.com, are unhelpful, you can't blame the searcher for trying an alternative source.


Adding the search term ".NET" to the above query moves the correct page to #2; the C++ operators page is still the top hit.


A user entering the search term "hat" or "handle to object" would know enough about the issue not to seek online help at all. (The situation is like Niklaus Wirth's 1970 "Pascal User Manual and Report", which was described as "the only introduction to Pascal understandable only by advanced Pascal programmers", The MANUAL assumed a solid knowledge of Algol, Pascal's parent, and this assumption was unstated.)


Might I suggest adding a "See Also" link somewhere on the C++ operators page to the "Handle to Object Operator" page, maybe with a short phrase/sentence providing context (e.g., "Extra Operators for .NET"? This would solve the problem with minimal effort expenditure.


Best regards,

Prakash


________________________________
