### ISSUE TITLE
C4018, C4388, C4389 should link to each other, describe when each applies

### ISSUE THREAD

**Issue by mathcounts4** [MicrosoftDocs/cpp-docs#2444]
The pages for 4389 and 4018 should mention that they only apply to same-size types, and point to 4388 (or just name it, since there's no page yet) to perform the same check when the operands have different sizes.

The pages for 4389 and 4018 should describe which operators they apply to, and should point to each other for the other operators.

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=vs-2019
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4389?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183bfd0e-88c4-41dc-0dd0-ec46de6055be
* Version Independent ID: f92b76cd-a7a5-8543-cf5d-bc568c51e2fa
* Content: [Compiler Warning (level 3) C4018](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-3-c4018.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-3-c4018.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mathcounts4 

As far as I can tell, C4389 applies to `==` and `!=` operators, and C4018 applies to all other comparisons. C4388 is off by default, and it applies when the unsigned type is larger than the signed type in the comparison.

**Comment by mathcounts4** [comment]
> @mathcounts4
> 
> As far as I can tell, C4389 applies to `==` and `!=` operators, and C4018 applies to all other comparisons. C4388 is off by default, and it applies when the unsigned type is larger than the signed type in the comparison.

Yes, I should have included this link in the problem, where Xiang Fan describes the 3:
[https://developercommunity.visualstudio.com/content/problem/1171950/warning-c4018-fails-to-be-reported-on-intstdsize-t.html](https://developercommunity.visualstudio.com/content/problem/1171950/warning-c4018-fails-to-be-reported-on-intstdsize-t.html)

**Comment by corob-msft** [comment]
Closing, addressed by cpp-docs-pr#3217
