### ISSUE TITLE
File extension of a property sheet is .props, not .user

### ISSUE THREAD

**Issue by FlyingDutchman1965** [MicrosoftDocs/cpp-docs#2446]
In the section on "User-defined macros" the page states in brackets "its name ends in .user". This is now incorrect as the property sheet extension is .props. as viewed in Windows File Explorer.

Also, the file extension is not shown in the Property Manager, anyway!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d320011e-7558-c4fc-04d8-31cbc2fda834
* Version Independent ID: 7b598fab-e8c1-d3a0-0fbf-730a7b2511a5
* Content: [Set C++ compiler and build properties in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=vs-2019)
* Content Source: [docs/build/working-with-project-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/working-with-project-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@FlyingDutchman1965 
I appreciate the report, and on review in context, I don't see an issue here. The file extension has always been *`.props`*. The part about the property sheet name ending in *.user* is meant to describe the name you actually see in the **Property Manager** window, which will be something like *Microsoft.Cpp.x64.user*, depending on which configuration you're looking at. On disk, it would have the name *`Microsoft.Cpp.x64.user.props`*, but you don't usually open it for editing from File Explorer.
I'm closing this as not an issue, though feel free to make a case for different wording if you feel there's a way to specify the property sheets that end in *.user* in the **Property Manager** window more clearly.
