### ISSUE TITLE
Wording is misleading and gives the wrong impression

### ISSUE THREAD

**Issue by mwasplund** [MicrosoftDocs/cpp-docs#2448]
I was on a Reddit thread and there was a discussion where someone thought this page was telling them to use modules in their code NOW.

> We recommend that new projects use modules rather than header files as much as possible.

While I agree that when the implementation is read all new projects should favor modules over headers, this wording is dangerous and could give people the impression that Microsoft is saying that the experimental implementation of C++20 Modules is ready for production usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=vs-2019)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mwasplund 
I suppose it can be read that way, though the fact that modules are a C++20 feature and the compiler doesn't have a **`/std:c++20`** option yet should be a clue about being production-ready. This article is due for an update that should show up later this month for the 16.8 preview/release. We'll address the recommendation as part of that.

@cdacamar @gdr-at-ms  Would you care to comment on what this should recommend now?

**Comment by TylerMSFT** [comment]
It's ok to use modules now.
