### ISSUE TITLE
homework problem

### ISSUE THREAD

**Issue by nazary11** [MicrosoftDocs/cpp-docs#2449]
[Enter feedback here]

#include <iostream>
using namespace std;
int main()
{
	double n;
	cout << "Please enter your age: ";
	cin >> n;
	if (n < 21)
	{
		cout << "You are not qualify for loan." << endl;
	}
	double x;
	cout << "Please enter your credit score: ";
	cin >> x;
	if (x >= 680)
	{
		cout << "You are not quality for loan." << endl;
		if (x == 'n')
		{
		}
	return 0;
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c20cf-53ed-f41c-f21d-a9cb7695f3b5
* Version Independent ID: f02d4617-2d5f-a0b5-f6e5-d9a9712284ca
* Content: [Fatal Error C1075](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1075?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1075)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1075.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1075.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as a dup of #2450.
