### ISSUE TITLE
Logic mistake in code example

### ISSUE THREAD

**Issue by Yairsno1** [MicrosoftDocs/cpp-docs#245]
# Logic mistake in the code example

Within the code example there is this line:
`if(c < numeric_limits<char>::max())`  
 `    throw invalid_argument("MyFunc argument too large.");`

To my opinion the correct condition that indicates char value "range overflow" should be **>** (greater than), like this
`if(c > numeric_limits<char>::max())`  
 `   throw invalid_argument("MyFunc argument too large.");`

Best regards,
Yair Shohat

---
#### פרטי מסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [Errors and Exception Handling (Modern C++)](https://docs.microsoft.com/he-il/cpp/cpp/errors-and-exception-handling-modern-cpp)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @Yairsno1 ! Fix should be visible in a day or so.
