### ISSUE TITLE
ambiguity and unclear text in the section "send and asend"

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/cpp-docs#2460]
Much ambiguity and unclear text in the section "send and asend". For example, in 2nd paragraph is a confusing mix of accept, decline, delivered, otherwise, and receive. 5 words which should only be 2 consistent words.

Same problems with 3rd paragraph and it should also relate and use similar words as 2nd paragraph. And in addition what is the distinction between "accept" and "take"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea128e03-8a12-e7c6-8a27-d1d3a524b1cb
* Version Independent ID: 5e9ab48a-6b4b-81f6-3e0d-41339e6c5c35
* Content: [Message Passing Functions](https://docs.microsoft.com/en-us/cpp/parallel/concrt/message-passing-functions?view=vs-2019)
* Content Source: [docs/parallel/concrt/message-passing-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/message-passing-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
