### ISSUE TITLE
missing or unclear text in Asynchronous Message Blocks overview

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/cpp-docs#2466]
While learning and reading, I found the following gaps/errors in the documentation for Asynchronous Message Blocks

1. Section "Message Propagation", 3rd paragraph. It starts well by writing, "by using the send function, the runtime blocks the current context until the target block either accepts or rejects the message". However, the next sentences about `asend` are mired in not-useful internal Microsoft implementation details about how Microsoft implements `asend`. The reader doesn't care about such internals in an intro paragraph. This paragraph needs to tell the reader what is the behavior of the calling context when `asend` is called just as was done a few lines before when discussing `send`. Is the context blocked? At what stages is it blocked? Does the blocking differ based on accepting or rejecting? The reader needs the high-level distinction of context blocking behavior when `send` or `asend` is called.
2. Layout errors in `Output` of most examples. The usual problem is the lack of carriage returns. This is most dramatically seen in the `Output` of the `transformer` Class example which writes `10.8914.5218.15` and should instead be three separate numbers on three separate lines.
3. Section "Choice class". The sentence "After you link all sources, the choice object preserves the order in which each source receives a message." is unclear or errant. I can find nothing that supports that sentence. I recommend more clear text like, "After a message is chosen, the choice class will propagate the index of the source that produced the message."
4. Section "Greedy Versus Non-Greedy Joins". 2nd sentence is unclear. Perhaps clearer is, "A greedy join accepts one message from each of its sources as messages become available until it has accepted one message from all sources." Same lack of clarity is also in sentence 5.
6. Section "Greedy Versus Non-Greedy Joins". 1st sentence having the text "...perform better..." provides no information. Instead, what is "better"? Does it use less CPU resources, lower latency, or perhaps it performs better on stage 💃😉.
7. Section "Message Reservation". 2nd paragraph. 4th sentence is so unclear it is almost false. "...a non-greedy join object waits for each of its sources to receive a message." I recommend you use the same wording used in the section "Greedy Versus Non-Greedy Joins" of "...a non-greedy join waits until it is offered a message from each of its sources."

Cheers🤓

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f10e0e0-43af-3337-f48f-f17f5f8af1d5
* Version Independent ID: 47f57152-cf3f-4465-a190-bff45123b856
* Content: [Asynchronous Message Blocks](https://docs.microsoft.com/en-us/cpp/parallel/concrt/asynchronous-message-blocks?view=vs-2019)
* Content Source: [docs/parallel/concrt/asynchronous-message-blocks.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/asynchronous-message-blocks.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by diablodale** [comment]
yikes. Well, its an unused dead product feature. Best of luck in your future endevours.
