### ISSUE TITLE
Missing auto-vectorization reason code

### ISSUE THREAD

**Issue by ivanka2012** [MicrosoftDocs/cpp-docs#2467]
The reason explanation for the code `1204` is missing from the `Vectorizer and parallelizer messages` page. In case if it's relevant, my version is Visual Studio 16.7.3.

**Comment by corob-msft** [comment]
@ivanka2012 
Thanks for the report. Investigation shows this occurs when a compiler limit is hit because loops are nested too deeply. One suggestion is to move the innermost loop or loops into a separate function. An update to the relevant docs should be visible sometime tomorrow.
