### ISSUE TITLE
Add notes on WSL shell configuration requirements

### ISSUE THREAD

**Issue by ntw-au** [MicrosoftDocs/cpp-docs#2474]
In my experience debugging CMake+GCC projects running in WSL (tested under Ubuntu 20.04) only works reliably when:
* The login shell is Bash, otherwise WSL fails to start with `Could not open windows subsystem shell`
* There is no extraneous console output when a shell is started. In particular, adding `fortune` to `.profile` often confuses the communication between Visual Studio and GDB, depending on the fortune displayed

There is no documentation to indicate these requirements and I have discovered them by trial and error. I suggest adding new text under the `Before you begin` section of this page describing these points and how the WSL environment needs to be configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create a CMake Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing until the dev team provides a matrix of supported scenarios.
