### ISSUE TITLE
Version-specific info regarding precompiled headers

### ISSUE THREAD

**Issue by Ponser** [MicrosoftDocs/cpp-docs#2475]
The existing document contains the phrase, `Warning C4627 is generated in Visual Studio 2015 and earlier'. The article does not address how later versions react to this situation. Granted, the page is about the message, not the situation, so perhaps a link like "also see" would be appropriate as opposed to having text on the page about later versions. In any case, I think the article would be more useful if there were some mention of how VS2017 and later handle this situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1618db17-1471-2891-a876-c3d8aaee28cb
* Version Independent ID: 740dc7c7-1dca-aa7f-c292-d48c87929193
* Content: [Compiler Warning (level 1) C4627](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4627?view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4627.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4627.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ponser 

In Visual Studio 2015 version 14.1 and later, this situation is covered by C4654, an off-by-default level 4 warning. If the C4654 warning isn't explicitly enabled (or you've turned on **`/Wall`**), then you'll only see warnings and errors from side-effects of the ignored #include or other directives. Usually, that means you'll see errors about undeclared identifiers from an ignored header. You won't get any diagnostic indication that says the header was ignored, or why. No, that doesn't seem useful to me, either.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
