### ISSUE TITLE
USELESS!

### ISSUE THREAD

**Issue by CoreyCoop** [MicrosoftDocs/cpp-docs#2476]
I'm not sure I remember what '^' does as a Boolean operator, and I get a generic description that it's punctuation?  With no way to link to it's possible usage in different contexts?  Look at your old documentation for C++, or any other company's docs.  This is laughable, and written by someone who either has no idea what a programmer does, or is so set in the way that they think that they assume everybody does it the same way.  Maybe I have to search for "Boolean Operators", maybe I have to search for "invert".
Maybe I should just go to an older Visual Studio, or a generic C/C++ reference that had reasonable documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3d70a67-d531-4c81-5a26-2999c5f18008
* Version Independent ID: e3585e35-7e9f-f8a7-1b15-9667ad155310
* Content: [Punctuators (C++)](https://docs.microsoft.com/en-us/cpp/cpp/punctuators-cpp?redirectedfrom=MSDN&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(%5E);k(DevLang-C%252B%252B)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/cpp/punctuators-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/punctuators-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CoreyCoop 

I was rather surprised to find the F1 result on a `^` character in the IDE landed on this page. It should have taken you to something more along the lines of [Bitwise exclusive OR operator: ^](https://docs.microsoft.com/cpp/cpp/bitwise-exclusive-or-operator-hat). I've put together a fix that ought to take effect within a couple of days. Thanks for the report.

**Comment by corob-msft** [comment]
Fix is live, closing.
