### ISSUE TITLE
IN: mbsnbcat-s-mbsnbcat-s-l.md, use "_tcsncat_s" instead of "_tcsncat"

### ISSUE THREAD

**Issue by RickDaniels314** [MicrosoftDocs/cpp-docs#2479]
In: cpp-docs/docs/c-runtime-library/reference/mbsnbcat-s-mbsnbcat-s-l.md

Should line 97 use "_tcsncat_s" instead of "_tcsncat"?

Per line 1287 in tchar.h header which says: "#define _tcsncat_s      _mbsnbcat_s"?

**Comment by TylerMSFT** [comment]
Thank you for catching that. Fixed. This fix should show up by 12/3
