### ISSUE TITLE
Compile error C3493 on cts

### ISSUE THREAD

**Issue by DevMatSolutions** [MicrosoftDocs/cpp-docs#2480]
get compile error as below:

error C3493: 'cts' cannot be implicitly captured because no default capture mode has been specified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559780c1-2a75-83c4-e58e-1c5062e5f054
* Version Independent ID: 6ec47c2d-c3f4-c0a9-3e9e-4cca161ede74
* Content: [How to: Create a Task that Completes After a Delay](https://docs.microsoft.com/en-us/cpp/parallel/concrt/how-to-create-a-task-that-completes-after-a-delay?view=vs-2019)
* Content Source: [docs/parallel/concrt/how-to-create-a-task-that-completes-after-a-delay.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/how-to-create-a-task-that-completes-after-a-delay.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
Updated, compiling sample code should be visible when our next publish cycle completes tomorrow.
