### ISSUE TITLE
Well-done

### ISSUE THREAD

**Issue by Magdy-Hemeda** [MicrosoftDocs/cpp-docs#2482]
Excellent detailed illustration to sum up the essential requisite to understand  C++ project' files structure and what it should include, simple Object declaration, creation and instantiation, inception, and debugging. Just needed a brief introduction on Variables and Constants scope (Local or Global) not too much at this stage on Private, Public, Friend or Protected. 

I love you guys, you are doing a great job.........., 

Magdy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a console calculator in C++](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Magdy-Hemeda 
Thanks!
