### ISSUE TITLE
Documenting UWOP_EPILOG

### ISSUE THREAD

**Issue by j04n** [MicrosoftDocs/cpp-docs#2483]
Hello,

Could it be possible to document unwind operation code UWOP_EPILOG (opcode 6) in https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/build/exception-handling-x64.md#unwind-operation-code ?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2019#struct-unwind_code)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
