### ISSUE TITLE
Code of "Walkthrough: Create a traditional Windows Desktop application (C++)" causes build errors

### ISSUE THREAD

**Issue by realicraft** [MicrosoftDocs/cpp-docs#2487]
When I copy the code from the "Build the Code" section into Visual Studio 2019 and build it, I get two build errors. I've pasted the console log below:

`1>------ Build started: Project: Application Test, Configuration: Debug x64 ------`
`1>MainScript.cpp`
`1>D:\Personal\Visual Studio\ApplicationTest\Application Test\MainScript.cpp(129,40): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`
`1>LINK : D:\Personal\Visual Studio\ApplicationTest\Application Test\x64\Debug\Application Test.exe not found or not built by the last incremental link; performing full link`
`1>MainScript.obj : error LNK2005: "__int64 __cdecl WndProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?WndProc@@YA_JPEAUHWND__@@I_K_J@Z) already defined in Application Test.obj`
`1>MainScript.obj : error LNK2005: "struct HINSTANCE__ * hInst" (?hInst@@3PEAUHINSTANCE__@@EA) already defined in Application Test.obj`
`1>LINK : warning LNK4067: ambiguous entry point; selected 'WinMainCRTStartup'`
`1>D:\Personal\Visual Studio\ApplicationTest\Application Test\x64\Debug\Application Test.exe : fatal error LNK1169: one or more multiply defined symbols found`
`1>Done building project "Application Test.vcxproj" -- FAILED.`
`========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@realicraft 
Sorry you're having difficulty. My guess is, you didn't follow the project template creation directions, and created a project using a template that already defined a WinMain function for you in "Application Test.cpp", then added the sample code in a new MainScript.cpp file, which caused duplicate symbols to be found by the linker. We're not equipped to offer support for anything but the documentation here, so I'm closing this issue. You may find the [Microsoft Docs Q&A C++ forum](https://docs.microsoft.com/en-us/answers/topics/c++.html) can assist you in finding and fixing build issues. Good luck!
