### ISSUE TITLE
Comparing CString for equality is inefficient

### ISSUE THREAD

**Issue by tobias-loew** [MicrosoftDocs/cpp-docs#2488]
Equality comparison for CString is solely based on calls to the strcmp family and thus inefficient: it lacks the size-comparison test. 

IMHO, "CString::operator ==" should be extended with a size-test, and there should be an additional function "bool EqualNoCase" which compares case-insensitive with an additional size-test.

Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6700c70-5679-b2fe-260e-bdb973af3130
* Version Independent ID: 0b25ccfa-13fa-dbbc-4677-dad029a80bbe
* Content: [Basic CString Operations](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/basic-cstring-operations?view=vs-2019)
* Content Source: [docs/atl-mfc-shared/basic-cstring-operations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/basic-cstring-operations.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@tobias-loew 
Thanks for writing in. While you're not necessarily wrong, you're addressing the wrong people. We only handle the documentation. To make a suggestion for the product implementation, you can use the Visual Studio IDE's **Help** > **Send Feedback** > **Suggest a Feature** menu command. It lets you make such suggestions directly to the product team, on the [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=62) website. If enough other people vote your idea up, odds are good that it will be implemented. Good luck!
