### ISSUE TITLE
explain "output tag"

### ISSUE THREAD

**Issue by rakslice** [MicrosoftDocs/cpp-docs#2490]
What is an "output tag"? This is the only occurrence of the term on the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743bb803-b9a9-0b2f-341f-69f1823e5dba
* Version Independent ID: 853beb3f-f378-3da1-1eed-f5189363173c
* Content: [tasks.vs.json schema reference (C++)](https://docs.microsoft.com/en-us/cpp/build/tasks-vs-json-schema-reference-cpp?view=vs-2019)
* Content Source: [docs/build/tasks-vs-json-schema-reference-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/tasks-vs-json-schema-reference-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@esweet431 @jureid Is this something either of you can answer?

**Comment by corob-msft** [comment]
@RaulPerez1 Is this something you're familiar with?

**Comment by corob-msft** [comment]
@WillBuik I'm told this is an anycode thing and that you might know more.

**Comment by corob-msft** [comment]
@rakslice 
I'm sorry, I don't know and neither does anyone who has responded to my emails. You might have better luck asking on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site, which is used for issues by the development team. They can probably route the question appropriately.
