### ISSUE TITLE
HTA to the rescue

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2491]
FFWD to 2020 ... There is no way to execute this step with today's modern browsers. Edge included.

Probably the easy way out is to rename the HTML file to hta. `mshta.exe` is still in Windows 10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e6484f-2b16-e4fa-5db9-4d0413c425ec
* Version Independent ID: 2b28dc02-b54d-0c2d-452c-3c5f1e2835be
* Content: [Putting the Control on a Web Page (ATL Tutorial, Part 7)](https://docs.microsoft.com/en-us/cpp/atl/putting-the-control-on-a-web-page-atl-tutorial-part-7?view=vs-2019)
* Content Source: [docs/atl/putting-the-control-on-a-web-page-atl-tutorial-part-7.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/putting-the-control-on-a-web-page-atl-tutorial-part-7.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
