### ISSUE TITLE
Typo in _configthreadlocale

### ISSUE THREAD

**Issue by j-oel** [MicrosoftDocs/cpp-docs#2492]
In the Remarks section there are two mentions of "_configurethreadlocale " - I reckon that it should be "_configthreadlocale", which is the name of the function and the title of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c4b7a8-a12d-8082-18bc-4a63d58d233d
* Version Independent ID: c86c99df-d0c2-3263-6c59-e2814b319428
* Content: [_configthreadlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/configthreadlocale?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/configthreadlocale.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/configthreadlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @j-oel 
I fixed this and it'll be live by tomorrow afternoon (10/30)

You may have noticed the tag: good-first-PR-issue. That's just an indication that if you want to, this is a good opportunity for you to contribute to the docs by making the fix yourself. [Here's how](https://review.docs.microsoft.com/en-us/windows-authoring-guide/quickstart?branch=master).  We are in the cpp-docs repo.
