### ISSUE TITLE
Compiler Error C3381

### ISSUE THREAD

**Issue by Rob190** [MicrosoftDocs/cpp-docs#2493]
The explanation really isn't very helpful. MSVC often gives these errors if there is a syntax error of some sort e.g. missing the ':' after a 'public' statement in a class declaration. Your example looks to be perfectly valid C++ so presumably you meant to say the error was caused by it not being in a class declaration.

In any case, is this really valid assembly? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e09f9b-33a8-1968-3d29-3c281d4e422c
* Version Independent ID: 69e3d2ea-989f-b94d-e247-30b886d76134
* Content: [Compiler Error C3381](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3381?view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c3381.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c3381.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Rob190 Thanks for the report. An update is live.
