### ISSUE TITLE
/kernel with the hypen

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2496]
If I do use /kernel- I get
```
command line warning D9002: ignoring unknown option '/kernel-'
```
this page says
```
/kernel-
The code in the current project is compiled and linked without using the C++ language rules that are specific to code that will run in kernel mode.
```
Wink wink, I wonder what prompted this sudden change :) So what are the " C++ language rules that are specific to code that will run in kernel mode", is that documented somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab4cd21-5a26-620f-9bd4-403a02b2b915
* Version Independent ID: 41e125c3-a7bc-69cb-7142-43974c5fe519
* Content: [/kernel (Create Kernel Mode Binary)](https://docs.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary?view=vs-2019)
* Content Source: [docs/build/reference/kernel-create-kernel-mode-binary.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/kernel-create-kernel-mode-binary.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ Thanks for the report. There are signs there may have been a **`/kernel-`** option in the past, but if so, it predates the current version control history, so I can't say for sure. I've updated the article.

**Comment by DBJDBJ** [comment]
@corob-msft  MSVC (aka CL) C++ behaviour with /kernel builds is a winner. It is a real point to be rectified. As people at large have no clue this switch exists and MSVC C++ just works with no C++ exceptions.

https://github.com/MicrosoftDocs/cpp-docs/issues/2494#issuecomment-701003578

**Comment by corob-msft** [comment]
@DBJDBJ 
It's trivially easy to leave out the standard-conforming C++ exception handling machinery from Microsoft C++, and you don't need **`/kernel`** to do it. Just don't include an **`/EH`** option in your command line or project properties. That is exactly what **`/kernel`** does to achieve this effect - no more, no less.  **`/kernel`** implicitly adds **`/GR-`** to remove RTTI, which you can also do independently. If all you care about is turning off EH, you only need **`/kernel`** if you also want to enable the kernel-mode compiler diagnostics.

**Comment by DBJDBJ** [comment]
@corob-msft  ... What am I trying to do is convince you and your coleagues to write one page on MS Docs entitled (something like): "Howe to use C++ in /kernel builds". I will finalize my involvement with https://github.com/MicrosoftDocs/cpp-docs/issues/2496#issuecomment-701166781

Many thanks ...
