### ISSUE TITLE
Lacks real content

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/cpp-docs#250]
The best resource (and its not great) I found at https://docs.microsoft.com/en-us/cpp/windows/runtimeclass-class - suggest linking to that from here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae1bbae-95c2-b27d-61f3-6001c35e2390
* Version Independent ID: 3609b951-e1e8-7427-879a-00cf56f70bc5
* Content: [FtmBase Class](https://docs.microsoft.com/en-us/cpp/windows/ftmbase-class)
* Content Source: [docs/windows/ftmbase-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/ftmbase-class.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
linked to the suggested topic. Thanks @amp64 !
