### ISSUE TITLE
MFC MenuButton Control.

### ISSUE THREAD

**Issue by Ol85** [MicrosoftDocs/cpp-docs#2502]
In general the good documentation on any GUI controls must have a mandatory example of use AND PICTURES how it will look like. It will save the developers time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aaeebc8-4feb-6add-c508-569f8ec7f149
* Version Independent ID: 1e215009-3826-71fe-737c-18988f2165da
* Content: [CMFCMenuButton Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfcmenubutton-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmfcmenubutton-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmfcmenubutton-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @O185,

Thanks for the feedback. I am focused on other areas and regret that I won't be able to invest time adding graphics to these docs. Best regards to you.

#please-close
