### ISSUE TITLE
Add // code...

### ISSUE THREAD

**Issue by AlkindiX** [MicrosoftDocs/cpp-docs#2504]
[Enter feedback here]
Add // code... before free(x) in the corrected issue one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb235fe8-558a-17cb-5454-0fab568da6a1
* Version Independent ID: b13b8fb5-8715-ff82-6546-cafcd7426d4a
* Content: [C6308](https://docs.microsoft.com/en-us/cpp/code-quality/c6308?view=vs-2019)
* Content Source: [docs/code-quality/c6308.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6308.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This issue should be addressed when a publishing update occurs later today.
