### ISSUE TITLE
If needed, could you update this for 15.7.2?

### ISSUE THREAD

**Issue by GatoRat** [MicrosoftDocs/cpp-docs#251]
If needed, could you update this for 15.7.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4353ff7-e91a-0887-c667-1211331167ac
* Version Independent ID: 1aa674cb-9646-8b22-7f37-1eb41d25db67
* Content: [Compiler Warnings That Are Off by Default](https://docs.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default#feedback)
* Content Source: [docs/preprocessor/compiler-warnings-that-are-off-by-default.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/compiler-warnings-that-are-off-by-default.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I think this lists the off-by-default warnings as of VS2017 RTM, but there have been some changes in 15.1 and 15.3 that are not reflected here. I've added a task to my list to update these.

**Comment by corob-msft** [comment]
Up-to-date content is live.
