### ISSUE TITLE
Warning appears and I'm using _unlink!

### ISSUE THREAD

**Issue by cniggeler** [MicrosoftDocs/cpp-docs#2511]
Hi, I get this multiple times:
`_unlink(tmpfile);
`
`warning C4996: '_unlink': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _unlink.
`
In other words, I get a warning message to use _unlink because I'm using... _unlink!  What up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b972b4d3-9362-3e94-6bff-859bc257a622
* Version Independent ID: e40451a2-e38c-aa9b-df86-d4c6e4cd93ad
* Content: [unlink](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/unlink?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/unlink.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/unlink.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@cniggeler I'd check for macros that redefine `unlink` somewhere in your code or the code you include. If `unlink` is redefined as `_unlink` before the standard headers are included, you could see the issue you describe. 
This sounds like a support issue rather than a docs issue, so I'm closing it.
