### ISSUE TITLE
There is no difference between the corrected function and the original function

### ISSUE THREAD

**Issue by junqu14** [MicrosoftDocs/cpp-docs#2516]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe05e67-1616-750b-c490-4c35540c1524
* Version Independent ID: 3a6250ac-9f56-29d0-ce25-cc157aceff67
* Content: [C28230](https://docs.microsoft.com/en-us/cpp/code-quality/c28230?view=vs-2019)
* Content Source: [docs/code-quality/c28230.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c28230.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@junqu14 
Thanks for the report. A fix is scheduled for publication later today.
