### ISSUE TITLE
Wrong rules  location for vs2019

### ISSUE THREAD

**Issue by olgaark** [MicrosoftDocs/cpp-docs#2519]
This is VS2017 location
%ProgramFiles%\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCTargets\1033

Please change the doc to use instead

`[VSInstallDir]\Msbuild\Microsoft\VC\[version]\[LCID]`
For instance, for English VS2019 Enterprise installation:
%ProgramFiles%\Microsoft Visual Studio\2019\Enterprise\Msbuild\VC\v160\1033

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2a638e-e8fb-b704-a7fb-e7b60a2fed7b
* Version Independent ID: 0691c76c-0241-fbbb-b2e0-09c5e2ccdf67
* Content: [Property Page XML rule files](https://docs.microsoft.com/en-us/cpp/build/reference/property-page-xml-files?view=vs-2019)
* Content Source: [docs/build/reference/property-page-xml-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/property-page-xml-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@olgaark 
 I forgot to mark this fixed when the change was merged over a week ago. The directories are updated in several related files as well.
