### ISSUE TITLE
Additional Cause when Windows Subsystem for Linux is installed

### ISSUE THREAD

**Issue by pmachapman** [MicrosoftDocs/cpp-docs#252]
An additional cause of this error is case-sensitivity in the file system, either for the file name or path, if per directory case sensitivity is enabled, and the directories were created by the Windows Subsystem for Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d846b08f-ccc3-d619-d710-3a526e00d5bc
* Version Independent ID: 11f14d2a-affb-9e33-6e76-4983389e52b1
* Content: [Fatal Error C1083](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1083?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C1083)%26rd%3Dtrue)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1083.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1083.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for pointing out this possibility. I'll update the error topic with an extra cause down in the "Additional causes" section for this case. It should go live in a day or so.

**Comment by corob-msft** [comment]
Content is live.

**Comment by tarapoto2006** [comment]
This was the exact cause of my problem. I had used Ubuntu running under WSL and rsync to download my Dev folder from my PC to my new laptop, and I could not build any project with Visual Studio 2017 under any folder inside my Dev folder.  To fix this, I had to run Windows Powershell as administrator and run the command:
fsutil.exe file setCaseSensitiveInfo d:\Dev disable

This fixed the C1083 error for me.

**Comment by mikeblome** [comment]
@tarapoto2006 thanks for reporting this. I'd like to improve documentation for this issue, but can you clarify whether the Dev folder was on WSL or on Windows?

**Comment by tarapoto2006** [comment]
@mikeblome The folder was created originally when I used rsync to download my Dev folder from another Windows computer which was running an SSH server on WSL Ubuntu. So the folder was on my my d drive, but it was created as /mnt/d/Dev by rsync, I didn't use Windows to create the folder.

**Comment by mikeblome** [comment]
@tarapoto2006 looking at this again I think the issue is sufficiently covered by the new text in C1083. Feel free to reopen if you disagree.
