### ISSUE TITLE
Inconsistent return value description

### ISSUE THREAD

**Issue by tholp** [MicrosoftDocs/cpp-docs#2521]
Two contradicting descriptions of the return value:
- On success, fegetround returns **the rounding mode** as one of the floating point rounding macro values. ...
- On success, fesetround returns **0**. Otherwise, a non-zero value is returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b5bba8-6129-56e0-bd04-22c1e558306e
* Version Independent ID: 2948d9e2-4712-8796-aa85-cb263a938380
* Content: [fegetround, fesetround](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fegetround-fesetround2?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/fegetround-fesetround2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fegetround-fesetround2.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@tholp 
The C Standard defines these two functions' behavior, and the documentation accurately reflects that behavior. If they're inconsistent, it wouldn't be the first inconsistency in the C standard.

**Comment by tholp** [comment]
Does this mean that you don't intent to do anything about the problem?  It seems to be waste of my time to ask for feedback, if you are just going to state a dumb excuse instead of correcting the problem.

**Comment by tholp** [comment]
Sorry my mistake.
