### ISSUE TITLE
Error when stepping into code

### ISSUE THREAD

**Issue by rdholland** [MicrosoftDocs/cpp-docs#2524]
I had to turn this off. If I get to a line of code that calls a function in my DLL and I attempt to "step into", I get an error. Then the "no source available" window shows up because there is no source for My.Dll_CheckForDebuggerJustMyCode(). I have to keep hitting F11 until I finally get into my code. So, I immediately disabled this feature. So thanks for this page detailing what this setting is and how to turn it off.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a18808-d7a4-58d9-02ec-801e5a37f714
* Version Independent ID: bbd8c856-7fa8-efce-3d1b-cc6c9d8169e7
* Content: [/JMC (Just My Code debugging)](https://docs.microsoft.com/en-us/cpp/build/reference/jmc?view=vs-2019)
* Content Source: [docs/build/reference/jmc.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/jmc.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rdholland Glad you found it useful.
