### ISSUE TITLE
Array Bounds specified incorrectly

### ISSUE THREAD

**Issue by steve-madden** [MicrosoftDocs/cpp-docs#253]
When specifying the dimensions of the multi-dimensional array in the Example, the first CComSafeArrayBound element should call SetCount(2) instead of SetCount(3).  The code in the article creates a 3x3 array.

CComSafeArrayBound bound[2];
bound[0].SetCount(3);  // <-- Should be 2
bound[0].SetLowerBound(0);
bound[1].SetCount(3);
bound[1].SetLowerBound(0); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8642fbbb-4313-9a09-e16e-ea3edb7d35c5
* Version Independent ID: af389449-79df-e313-24bc-4a2db9da39fd
* Content: [CComSafeArray Class](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomsafearray-class#example)
* Content Source: [docs/atl/reference/ccomsafearray-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/ccomsafearray-class.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed. Thanks!
