### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by Dave-51** [MicrosoftDocs/cpp-docs#254]
There is a "see also" link here which links to this same page. Remove it.  This article claims that "C" and "C++" are used with strings and then goes on to give examples with chars and ints. Last I heard, a char was not a string and certainly an int is not. There is no explanation, nor reference to what exactly C (string?) linking and C++ (string?) linking means. Null terminated vs a (structured, with internal components (fields, functions)) data object? The potential implications of linkages between files are deeper than simply null terminated or structured stings, are they not? Aren't there also implications for data/program security and compatibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 933730ba-c23b-b25a-657e-c9dc5d85bcf2
* Version Independent ID: 89890352-1314-9d68-e25f-64c33522ee5d
* Content: [Using extern to Specify Linkage](https://docs.microsoft.com/en-us/cpp/cpp/using-extern-to-specify-linkage)
* Content Source: [docs/cpp/using-extern-to-specify-linkage.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/using-extern-to-specify-linkage.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Dave-51 Thanks for the feedback. In addition to the issues you found, this section of the documentation in general is very out-of-date. We plan to make some major improvements in the near future. I'll keep this issue open until the new topics are published.

**Comment by mikeblome** [comment]
@Dave-51 Page has been rewritten and hopefully improved.
