### ISSUE TITLE
properly enumerated and cast but getting C2665 in VS 2017 ?

### ISSUE THREAD

**Issue by LewisHoff** [MicrosoftDocs/cpp-docs#2543]
using vs 2017 with c++/CLI console project template 👍 
code 👍 
// Ex2_13b.cpp : main project file. 
// Defining and using a C++/CLI enumeration.

#include "stdafx.h" 

using namespace System; 

 
enum class Suit{Clubs, Diamonds, Hearts, Spades};

int main(array<System::String ^> ^args)
{
	Suit suit = Suit::Clubs; 
	int value = safe_cast<int>(suit); 
	Console::WriteLine(L"Suit is {0} and the value is {1} ", value, suit);  
	suit = Suit::Diamonds;
	value = safe_cast<int>(suit);
	Console::WriteLine(L"Suit is {0} and the value is {1} ", value, suit);
	return 0;
}

I get   
Error	C2665	'System::Console::WriteLine': none of the 19 overloads could convert all the argument types	Ex2_13b	
Thank You for any guidance,  Lewis 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c477e357-0738-21c8-a309-ddbf3c35d328
* Version Independent ID: e49ca50c-acf7-e722-a0c4-1fcb335eaa80
* Content: [Compiler Error C2665](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2665?view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2665.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c2665.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by LewisHoff** [comment]
I did , actually, have value and suit switched improperly in the above console output code, but I switched them back to suit, value and I still get the c2665.

Thank You, Lewis

**Comment by corob-msft** [comment]
@LewisHoff 
I'm sorry, we don't have the bandwidth for support requests here, so I'm closing your issue. The best place to ask a question like yours is on the [Microsoft Docs Q&A forum for C++](https://docs.microsoft.com/en-us/answers/topics/c++.html). Off the top of my head, it looks like you have two issues. The first is, you're not using a template parameter with your `safe_cast`, which ought to be `value = safe_cast<int>(suit);` instead. The other problem that's causing Error C2665 is, you're passing a value `suit` of type `Suit` to `Console.WriteLine` without creating a way to convert its values into something printable. `Console.WriteLine` won't implicitly convert a `Suit` for you. Best of luck!

**Comment by LewisHoff** [comment]
Thank You very much.  This is very helpful.  Lewis
