### ISSUE TITLE
The final screenshot shown on this page is not the same as the one shown at the beginning of the next page. Selecing 

### ISSUE THREAD

**Issue by if4ww** [MicrosoftDocs/cpp-docs#2544]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 417f5323-ac82-40f1-59c2-181ae9f2426a
* Version Independent ID: 153a0220-8514-3257-69fd-e190cbb3ab0a
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-1-create?view=vs-2019#create-your-app-project)
* Content Source: [docs/build/vscpp-step-1-create.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-1-create.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by if4ww** [comment]
Selecting 'Start Without Debugging' brings up a debug popup window, not the popup window shown in the next step of the tutorial. Note that the code is different in the screenshot at the head of the next tutorial page, as well as the Properties window.

**Comment by corob-msft** [comment]
@if4ww 
It probably doesn't help that all the screen shots are from VS 2015, which will pop-up a dialog telling you your sources are out of date if you've edited the code but haven't built it before invoking **Debug > Start without debugging**. VS 2019 assumes you want to build your code, and only puts up a pop-up if there was a build error. I'll look into the issue with the screen shots.

**Comment by if4ww** [comment]
Thanks. I was able to work around the gap, though I don’t remember exactly how, now. I may have just manually edited the code in the final screenshot of step one so that it looked like the code in the first screenshot of step 2.  Cheers.  Ian From: Colin RobertsonSent: Tuesday, October 20, 2020 5:27 PMTo: MicrosoftDocs/cpp-docsCc: if4ww; MentionSubject: Re: [MicrosoftDocs/cpp-docs] The final screenshot shown on this page is not the same as the one shown at the beginning of the next page. Selecing (#2544) @if4wwIt probably doesn't help that all the screen shots are from VS 2015, which will pop-up a dialog telling you your sources are out of date if you've edited the code but haven't built it before invoking Debug > Start without debugging. VS 2019 assumes you want to build your code, and only puts up a pop-up if there was a build error. I'll look into the issue with the screen shots.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
