### ISSUE TITLE
What OS installations include the CRT DLLs by default?

### ISSUE THREAD

**Issue by frinkfree** [MicrosoftDocs/cpp-docs#2546]
A callout is made that the latest CRT DLLs are part of Windows 10 installation. What about Windows Server installations such as Windows Server 2016, etc.?
Thanks,
Parx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d45abb-3fbc-b262-29ca-8f5c4e7b49b2
* Version Independent ID: 3c087dd0-b858-f9fe-b9e6-81d1d336de68
* Content: [Universal CRT deployment](https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=vs-2019)
* Content Source: [docs/windows/universal-crt-deployment.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/universal-crt-deployment.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@frinkfree 
To quickly answer your question, the UCRT is a native operating system component for all versions of Windows based on the NT 10.0 core, including Windows Server 2016 and Windows Server 2019 products. It's an installable component on older versions of Windows Server that are still in extended support.

**Comment by corob-msft** [comment]
A fix should be published later today.

**Comment by frinkfree** [comment]
That is great information! and a fast response. Much appreciated.
