### ISSUE TITLE
ARM64 ABI: Clarify HFA handling

### ISSUE THREAD

**Issue by richard-townsend-arm** [MicrosoftDocs/cpp-docs#2548]
Hi folks, I had a question about how MSVC handles deciding whether or not a function should use a HFA type (answered here: https://developercommunity.visualstudio.com/content/problem/1179157/arm64-abi-inconsistent-handling-of-hfas.html). There's an important difference to the way MSVC does it that's different from all other compilers.

In standard ARM64 ABIs, a type is considered HFA if it's a homogenous aggregate with a floating-point type that contains at most 4 members. In Microsoft's ABI, it's additionally required that a type's base classes and members all share the same HFA type. For example:

```
struct Pod {
  double b[2];
};
struct NotAggregate {
  NotAggregate();
  double b[2];
};
struct NotPod {
  NotAggregate x;
};
Pod copy(Pod *x) { return *x; }  // MSVC: ldp d0,d1,[x0], Clang: ldp d0,d1,[x0]
NotAggregate copy(NotAggregate *x) { return *x; } // MSVC: stp x8,x9,[x0], Clang: str q0,[x0]
NotPod copy(NotPod *x) { return *x; } // MSVC: ldp x0,x1,[x8], Clang: d0,d1,[x0]
```

`Pod`/`NotPod` would all be HFA under the standard ARM64 ABI, but MSVC doesn't consider `NotPod` to be HFA because `NotAggregate` is not considered to be a HFA. Could the ARM64 ABI documentation be updated to note this additional requirement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee4db12-6226-a1e6-6c8c-d2d5d77ae92e
* Version Independent ID: 180f6f4e-d5a9-88cd-c297-6cba5b16289e
* Content: [Overview of ARM64 ABI conventions](https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=vs-2019)
* Content Source: [docs/build/arm64-windows-abi-conventions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/arm64-windows-abi-conventions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
