### ISSUE TITLE
0x800401F9 error - CalculatorComponent.def needs to be specified in linker settings

### ISSUE THREAD

**Issue by adamtki** [MicrosoftDocs/cpp-docs#2549]
[Enter feedback here]
Step 8 forgot to set CalculatorComponent.def file as the Module Definition File linker setting for the CalculatorComponent.  Without that step, you get a 0x800401F9 error when trying to create the component.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff38587-44d4-291e-92f2-1835bae646b2
* Version Independent ID: d03537dc-cad6-9888-dcc7-6881c00a479c
* Content: [How to: Create a Classic COM Component Using WRL](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl?view=vs-2019)
* Content Source: [docs/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@adamtki 
Thanks for the report. A fix should be published later today.
