### ISSUE TITLE
Static?

### ISSUE THREAD

**Issue by Dave-51** [MicrosoftDocs/cpp-docs#255]
What does all of the prose discussing "static" have to do with "extern" as a storage class specifier. I understand that "static" is also a storage class specifier, but so what? It is, in general, a really bad idea to name functions and variables use pedagogically with common words: does "other variable" mean "another variable" or does it mean "a variable belonging to other()"?? This page should, imho, be linked to the subjects of 1) storage class (is there such an article?) and 2) linking of files (and compilation units). Finally, is it true that C++ and C are still similar enough so that the same content is optimum for both? That is: does extern behave identically in C as in C++ (and in Visual C and Visual C++)? (If that were the case then extern "C" {blah; blah} wouldn't be a thing, would it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3cfde1-0cf0-dd81-5820-86affa13e152
* Version Independent ID: a86d0b25-78ad-5617-ed75-6c260536289d
* Content: [extern Storage-Class Specifier](https://docs.microsoft.com/en-us/cpp/c-language/extern-storage-class-specifier)
* Content Source: [docs/c-language/extern-storage-class-specifier.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/extern-storage-class-specifier.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Dave-51 Agreed. See my other comment about improvements to this whole section of the docs. Thanks!

**Comment by mikeblome** [comment]
@Dave-51  Page has been updated and hopefully improved per your suggestions. Should be live by 07/11.
