### ISSUE TITLE
Example 3 text should be part of a separate Example 3, not part of the Example 2 code.

### ISSUE THREAD

**Issue by donmac703** [MicrosoftDocs/cpp-docs#2550]
Example 3 code should be part of a separate Example 3, not part of the Example 2 code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef4bc6b-b29f-2390-8757-45fef6db57d6
* Version Independent ID: d7239941-1853-9d8b-d907-7b4debd8997d
* Content: [C26400](https://docs.microsoft.com/en-us/cpp/code-quality/c26400?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26400);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/code-quality/c26400.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26400.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@donmac703 
Thanks for the report. A fix should be published later today.
