### ISSUE TITLE
WSL X11 to Windows

### ISSUE THREAD

**Issue by Coarist** [MicrosoftDocs/cpp-docs#2553]
Hello, thank you for this great tutorial. Many useful ideas are highlighted and it is very informative. 

On my computer I connect to WSL Windows Subsystem for Linux. Launching a GUI application, in my case, would not work. The reasons could be SSH which X11 server on Windows 10 (XLaunch) is already taken up by Visual Studio debugging. Is there a workaround that enable debugging GUI programs from Visual Studio in WSL using Windows 10 as X11 display server? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4535255d-395b-6b11-daf3-b03e0c3ad87d
* Version Independent ID: 1aad5206-ea1e-630c-800a-bb79bbd942b4
* Content: [Create C++ cross-platform projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2019)
* Content Source: [docs/build/get-started-linux-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/get-started-linux-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Coarist 
That's an interesting question, but you're probably asking in the wrong place. For product questions like this, I'd recommend the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. That's where the developers who can tell if it's a bug with a workaround, an unimplemented feature, or just an oversight in the docs can respond. If the documentation needs to be updated to address the issue, they'll let us know. Closing for now, but if you respond with a link to the issue on Developer Community, and a doc change is needed, that will help us link it up. Thanks, and good luck.
