### ISSUE TITLE
Selecting /clr in dev environment isn't described in referenced page

### ISSUE THREAD

**Issue by wilFab** [MicrosoftDocs/cpp-docs#2554]
The section titled "**Change Project Setting**" says:

 "**/clr** can be selected in the development environment by following the instructions in [/clr (Common Language Runtime Compilation)](https://docs.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=vs-2019)."

The referenced page does not currently include instructions on how to select **/clr** in the development environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202280ec-5cf8-31d5-2d38-1a60a9035ff5
* Version Independent ID: 733c8347-4f2d-1d20-5968-48541aeecb7f
* Content: [How to: Migrate to -clr](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-migrate-to-clr?view=vs-2019)
* Content Source: [docs/dotnet/how-to-migrate-to-clr.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-migrate-to-clr.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@wilFab 
A fix should be published later today.

**Comment by wilFab** [comment]
I do see a section on the referenced page [/clr (Common Language Runtime Compilation)](https://docs.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=vs-2019) titled "**To set this compiler option in the Visual Studio development environment**," but step 3 points to an incorrect location in the project configuration properties for the **/clr** property.  Should it instead be:

    3. Select the **Configuration Properties** > **C/C++** > **General** page.

**Comment by corob-msft** [comment]
@wilFab
 
You are correct, if the only thing you want to change is the compiler switch, that's the way to do it. And since the doc is about the compiler switch, and the automation link shown only sets the compiler switch, the instructions should be about the compiler switch. I'll address that. I was trying to head off the support calls by people who change it and break their projects, but maybe that was not the right way forward.

**Comment by corob-msft** [comment]
New fix is live.
