### ISSUE TITLE
Where is the #include "stdafx.h" file in Visual Studio 2019? 

### ISSUE THREAD

**Issue by yeokaiwei** [MicrosoftDocs/cpp-docs#2557]
[Where is the #include "stdafx.h" file in Visual Studio 2019? According to https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2019

"When you create a new project in Visual Studio, a precompiled header file named pch.h is added to the project. (In Visual Studio 2017 and earlier, the file was called stdafx.h.) The purpose of the file is to speed up the build process. Any stable header files, for example Standard Library headers such as <vector>, should be included here. The precompiled header is compiled only when it, or any files it includes, are modified. If you only make changes in your project source code, the build will skip compilation for the precompiled header."

Is there a way to see where it is?

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cadd6022-4e0d-d292-de08-4b73b681f6e8
* Version Independent ID: ce99a474-56fd-f48f-137e-ba6570fa3f4e
* Content: [Precompiled Header Files](https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2019)
* Content Source: [docs/build/creating-precompiled-header-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/creating-precompiled-header-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yeokaiwei 

The location of the *pch.h* file or *stdafx.h* file depends on the project template. All the templates I checked put the file in a virtual folder named **Header Files** in the Solution Explorer window. On disk, it's in the project folder with your other source files. The generated PCH file is in the project build output folder, usually *Debug* or *Release*.
This question doesn't seem like something that needs to be noted in the document, so I'm closing this issue.
