### ISSUE TITLE
Glitchy title

### ISSUE THREAD

**Issue by drpritch** [MicrosoftDocs/cpp-docs#2558]
There shouldn't be a "UIElement List" title on this page. Looks like a markup editing glitch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34e186-20d4-e937-8b4a-036b4708aad8
* Version Independent ID: 0d911d7c-1338-c554-bb55-7de0c33e846a
* Content: [Custom Build Step Property Page: General](https://docs.microsoft.com/en-us/cpp/build/reference/custom-build-step-property-page-general?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCCustomBuildStep.Command)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/build/reference/custom-build-step-property-page-general.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/custom-build-step-property-page-general.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@drpritch 
Thanks for the report. A fix should be published tomorrow.
