### ISSUE TITLE
"Deprecated; migrated" common practice for deprecation all around the Net is ...

### ISSUE THREAD

**Issue by leo-zspace** [MicrosoftDocs/cpp-docs#256]
$(InputName)	(Deprecated; migrated.)
common practice for deprecation all around the Net is to tell developers what to use instead or where to look for replacement. But because Microsoft is so arogant and beleives that "Visual Studio is so _beloved_" - it's up to developers to google (pardon bing) the deprecated migrated property till s/he is blue in the face and ready to give Microsoft feedback that is likely to be ignored for years. I don't even know why I rant about it anymore... :( Back to googling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba7e6dc-88bf-47ff-7bcf-467140bc92f1
* Version Independent ID: 5dfa8c91-eb92-8905-741e-15cd10d54baa
* Content: [Common Macros for Build Commands and Properties](https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties)
* Content Source: [docs/ide/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/common-macros-for-build-commands-and-properties.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updated content is live. Note that some obsoleted .vcproj macros do not have equivalents in .vcxproj files, and some have more than one, depending on the item type. For the specific question asked, the $(InputName) can be translated to $(SolutionName) for solutions, $(ProjectName) for projects, and %(Filename) for source files, and there may be other translations for other item types that I didn't see. The documentation mentions the most common two you're likely to see if updating a project by hand.

**Comment by leo-zspace** [comment]
Yes - I see much cleaner version on:
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/ide/common-macros-for-build-commands-and-properties.md
Thanks a lot.
But I don't see updated: https://msdn.microsoft.com/en-us/library/c02as0cs.aspx
May be it just takes time. Thanks for quick response.

**Comment by corob-msft** [comment]
The current documentation for [Common macros for build commands and properties](https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties) lives in docs.microsoft.com. None of the MSDN content is being updated, and it will all be archived or migrated and redirected into docs.microsoft.com sometime this year.
