### ISSUE TITLE
No longer valid.

### ISSUE THREAD

**Issue by codetronik** [MicrosoftDocs/cpp-docs#2564]
This guide is not an appropriate guide.

The build fails in /w4 even with the /Ze option.

https://docs.microsoft.com/ko-kr/cpp/build/reference/za-ze-disable-language-extensions?view=msvc-160
It also says "deprecated" on this page.

I had to use /w3 for the build.

build Environment : windows 10 x64/ visual studio 2019  lastest version / wdk lastest version

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 86c497af-4325-33ae-5d64-3126a498d336
* Version Independent ID: 9395c06b-2050-aa09-c1e4-e98dae74594f
* Content: [Compiler Warning (level 4) C4214](https://docs.microsoft.com/ko-kr/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4214?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4214.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4214.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@codetronik 

You are right. **`/Ze`** is the same as the default, and gives the same warning (plus another warning saying that **`/Ze`** is deprecated).

The warning tells you that C89 doesn't support bit-field types other than **`int`**, **`signed int`**, or **`unsigned int`**. The warning means the code isn't portable to other C89 compilers. In the C99 standard and later, a compiler may support other integral types for bit-fields. It's usually okay to ignore this warning.

To ignore the warning, try using **`/Za`** instead. Or, explicitly ignore the warning, by using either `#pragma warning( disable: 4214 )` or **`/wd4215`** on the command line. In the IDE, open your project's Property Pages dialog. Select the **Configuration Properties > C/C++ > Advanced** property page. Select the **Disable Specific Warnings** property dropdown control and then choose Edit. In the edit box in the Disable Specific Warnings dialog, enter the warning number, 4214. Save your changes in the Disable Specific Changes dialog, and choose **OK** in the Property Pages dialog.
