### ISSUE TITLE
how can I download this page?

### ISSUE THREAD

**Issue by qiemanqieman** [MicrosoftDocs/cpp-docs#2565]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-160)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@qiemanqieman 

Good question. I can think of three ways to download the page off the top of my head. In most browsers, you can use **ctrl+S** to save the current page as HTML. Or you can choose **ctrl+P** to print the page, then choose "Microsoft Print to PDF" as the printer, which will save the output as a PDF file. If you'd rather have a full content set, down in the lower left of the page a bit below the table of contents, you should see a **Download PDF** control. You can search for the article title in the PDF to get there directly. I hope one of these methods works for you. I'm closing the issue, as this isn't an issue with this particular article.
