### ISSUE TITLE
Here we go again ...

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2567]
_"...we recommend that you use ISO-standard C++ exception handling..."_

- AFAIK, Windows OS is written in C and core SDK is C API
- Core of Windows is using SEH and raises SE
- MS STL can be legally compiled into C++ projects not using C++ Exceptions
      - In such a scenario 
            - MS STL raises Structured Exceptions
            - C++ keywords throw/try/catch  do not compile

This page might be highly confusing? People and projects working for mission-critical systems can not follow this advice? Any project using ISO C, can not follow this advice. Latest CL (16.8) update will be also (almost 100%) standard C11 and C17 compiler, it appears ISO C is not "abandoned" after all.

Kind regards ...

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6820eb86-7922-fc81-a6cd-80fbf6143726
* Version Independent ID: 3e2936b4-498d-0656-17d3-d4fa6566630c
* Content: [Structured Exception Handling (C/C++)](https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-160)
* Content Source: [docs/cpp/structured-exception-handling-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/structured-exception-handling-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ 

Thanks for the feedback. As I read the article, I don't see anything particularly confusing about it. The simplest reading of the opening paragraph is, don't use SEH in C++ code unless you need to. SEH doesn't have the facility or portability of C++ standard exception handling, so we don't recommend it as a substitute. If this advice doesn't apply to you, we expect you'll know. 

When you claim "MS STL raises Structured Exceptions" absent standard (**`/EHsc`**) exception handling, it appears to reflect a misunderstanding of what's going on and what it costs. Use of SEH incurs costs just like regular C++ exception handling does. C++ exception handling is in fact built on top of SEH by MSVC's implementation. C++ EH does extra work for type matching and local object unwinding (work you would have to manually replicate in your finalizers anyway for leak-free code), but the non-trivial cost of raising and catching an exception is still there in the base SEH mechanism. If you're trying to avoid the costs of exception handling by substituting SEH, you're bound to be disappointed. The only way to avoid the costs of exception handling is, don't use exception handling. It may be slightly cheaper, but there are no free lunches to be had by using SEH.

**Comment by DBJDBJ** [comment]
Hi Rob :)

My text is **not**  about the "costs" but the service MS STL also provides. Page text as it is misleading as it advises the unknown audience to use c++ exceptions. Confusing the decision-makers in turn. Many of whom simply can not use C++ exceptions, RTTI or even heap allocation. 

I have measured MS STL in an SEH mode and it is (much) faster than C++ exceptions mode. Almost as fast as EASTL.  Do I need to understand more?

I just have this feeling MS STL SEH mode is somewhat "hidden" from the world? Is there any authoritative post on MS STL SEH? The reasons and history behind? I myself discovered MS STL SEH almost by accident.

Also, there are seasoned C/C++ developers who simply do not like the idea of exceptions. Me including. Windows is C. Win32 is C. And SEH is in the foundations of Windows. Thus each and every mildly serious WIN service, or some such component, is C + SEH.  One can not ignore that.  I just do not see that history and fact permeating MS DOCS enough :)

If and when Windows would be written in C++, throwing C++ exceptions, then I would follow that philosophy.

**Comment by corob-msft** [comment]
I think I mentioned before that your "discovery" about SEH in the STL is an emergent property fluke, and is not recommended, completely unsupported, and likely to get you weird bugs that are hard to diagnose. And I can't repeat often enough that we *do indeed* recommend C++ standard exceptions for your C++ exception handling needs. If the runtime cost is prohibitive, SEH is a really poor substitute. And it's one that's being misused if you're doing anything like regular C++ exception handling with it. SEH has its place, and it's widely used in code built with the Hardware SDK. Lots of that code is actually C++, by the way, as is much of the core Windows OS, except for the shell bits and UWP components written in C#. Often it's just C-with-classes style C++, but that's what the file extensions say for the parts I've seen.

**Comment by DBJDBJ** [comment]
I hear you loud and clear :) 

Are you implying the MS STL SEH might be soon deprecated?  I went ["deep" inside MS STL](https://github.com/dbj-data/kernel_ms_stl) and I can not see any "adventure park" in there. That part is clean and well designed and allows for easy switch indeed to/from SEH. I am using it and I can report it makes for very fast MS STL.

![image](https://user-images.githubusercontent.com/145155/97887140-c7ed1480-1d29-11eb-9428-63978eae6447.png)

ps: the debate we had before was about `comdef.h` which seemingly is using SEH but "accidentally".

Many thanks  for your time
