### ISSUE TITLE
Why have Links to out of date tutorials 

### ISSUE THREAD

**Issue by melvyn-n** [MicrosoftDocs/cpp-docs#2568]
[Enter feedback here]
Where is the updated version for WSL ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4535255d-395b-6b11-daf3-b03e0c3ad87d
* Version Independent ID: 1aad5206-ea1e-630c-800a-bb79bbd942b4
* Content: [Create C++ cross-platform projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/get-started-linux-cmake.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/get-started-linux-cmake.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@melvyn-n I'm not sure I understand what you're asking. Is this page the tutorial you think is out of date? Or, did you follow a link on this page to something else that's out of date, and if so, which link?

@esweet431 FYI - do we have a gap here? WSL may still be primarily command-line oriented, but it can do graphics now.

**Comment by esweet431** [comment]
@corob-msft You still can't run a GUI application on WSL without setting up an XServer. @melvyn-n, is that what you are referring to? Or is there something else you think is missing?

**Comment by melvyn-n** [comment]
VS2019 “welcome/start here page” mentions Cmake development on Linux and WSL2 but has links to tutorial pages from pre WSL2 days.
Sent from my Windows 10 device

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
