### ISSUE TITLE
Possibly Misleading: "This linker option is not available from the Visual Studio development environment"

### ISSUE THREAD

**Issue by FBoyne** [MicrosoftDocs/cpp-docs#257]
While it is true that there is no specific property within a project's property pages that allows one to set a /DEFAULTLIB value, it seems misleading to say that the option is not available from the Visual Studio development environment.  The Linker | Command Line property page may be used within Visual Studio to specify /DEFAULTLIB.  A casual reader might take that sentence to mean more than it is really trying to say?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147c472f-8e2f-f936-349b-5fd526143b53
* Version Independent ID: 35c431c6-2d5d-c8f1-e678-0bae77aaa71d
* Content: [-DEFAULTLIB (Specify Default Library)](https://docs.microsoft.com/en-us/cpp/build/reference/defaultlib-specify-default-library)
* Content Source: [docs/build/reference/defaultlib-specify-default-library.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/defaultlib-specify-default-library.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
True enough. I've updated the text to include the usual instructions for adding something via the Additional Options property, and made a few other minor editorial changes. This fix is in progress and should appear in a day or two.

**Comment by corob-msft** [comment]
Content is live.
