### ISSUE TITLE
CommandLineToArgvA.

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2573]
[https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargva](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea?source=docs)

it is mentioned above

![image](https://user-images.githubusercontent.com/145155/98115539-47542280-1ea7-11eb-88f9-e4233ce7d30d.png)

But that link leads to 404?

[https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargva](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargva)

Kind regards ...

**Comment by corob-msft** [comment]
@Karl-Bridge-Microsoft Is this your topic?

**Comment by corob-msft** [comment]
@DBJDBJ   The Win32 docs team has made a fix and queued it for publication. It turns out there is no ANSI flavor, there's only [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw).

**Comment by DBJDBJ** [comment]
@corob-msft yes, I have noticed that.  Perhaps a little side info (on this page) about when was the `CommandLineToArgvA` removed will help so that in the future you will not have this issue repeatedly taking your bandwidth or of the Win32 docs team.
