### ISSUE TITLE
Compiler Warning (level 4) C4706 and "<="

### ISSUE THREAD

**Issue by yeokaiwei** [MicrosoftDocs/cpp-docs#2577]
For a newbie, if you forget the "<", you will get Compiler Warning (level 4) C4706

for (i = 2; i = n / 2; ++i)
for (i = 2; i <= n / 2; ++i)

It's not immediately noticeable as the compiler can still run the project.

If this a good example, could you kindly add it as an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf067a7-3f30-3d37-dbee-856d00a42f82
* Version Independent ID: 0d46c95c-a0d1-fcc3-d6f6-5484d0142721
* Content: [Compiler Warning (level 4) C4706](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4706?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4706.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4706.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
