### ISSUE TITLE
where are those examples???

### ISSUE THREAD

**Issue by vraivon** [MicrosoftDocs/cpp-docs#2578]
where are those examples???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18740be5-c9f7-69aa-a5cb-505f562298b9
* Version Independent ID: 32400d1a-db89-c42e-d9a1-b02a33392e31
* Content: [Cross-platform mobile development examples](https://docs.microsoft.com/en-us/cpp/cross-platform/cross-platform-mobile-development-examples?view=msvc-160)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-examples.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/cross-platform-mobile-development-examples.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
This is a duplicate. I'm tracking this problem in an internal tracking system.
