### ISSUE TITLE
Error in this document page 

### ISSUE THREAD

**Issue by ActiveVariable** [MicrosoftDocs/cpp-docs#2584]
[Enter feedback here]

void process(double p*, const size_t len)
{
    std::cout << "process:\n";
    for (size_t i = 0; i < len; ++i)
    {
        // do something with p[i]
    }
}

void process(const double p*, const size_t len);

Error type : double p*,const double p*
A small mistake , hope to fix it
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cc4d71-6795-72d2-5c91-c5268972a233
* Version Independent ID: 2f09013f-cee2-c094-096c-7595d72cc96c
* Content: [Arrays (C++)](https://docs.microsoft.com/en-us/cpp/cpp/arrays-cpp?view=msvc-160)
* Content Source: [docs/cpp/arrays-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/arrays-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by ActiveVariable** [comment]
a small mistake

**Comment by corob-msft** [comment]
@ActiveVariable 
Thanks for the report. A fix should appear with our next daily publishing update.
