### ISSUE TITLE
Descriptions of crend, end and rend in the table of functions is incorrect

### ISSUE THREAD

**Issue by FlyingDutchman1965** [MicrosoftDocs/cpp-docs#2589]
crend description is "Returns a const iterator to the end of a reversed vector." It should be like the descritpion for cend eg
"Returns a const iterator that points just beyond the end of of a reversed vector."

end description is "Returns a random-access iterator that points to the end of the vector." Should be "Returns a random-access iterator that points just beyond the end of the vector."

rend description is "Returns an iterator to the end of a reversed vector."  Should be "Returns an iterator to just beyond the end of a reversed vector."
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cd55b4-5345-3493-9d05-12868315571d
* Version Independent ID: 8e501921-6f1d-7705-231b-7ed0eded02ae
* Content: [vector class](https://docs.microsoft.com/en-us/cpp/standard-library/vector-class?view=msvc-160#rend)
* Content Source: [docs/standard-library/vector-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/vector-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@FlyingDutchman1965, thank you for pointing that out. I've fixed it and the changes should be live in a couple days.
Thank you for helping us improve the docs.

**Comment by TylerMSFT** [comment]
@FlyingDutchman1965 , just FYI that we are having some issues with our publishing pipeline. I hope that the fix will be out sometime next week.
