### ISSUE TITLE
_open_osfhandle does not work with HANDLE arguments

### ISSUE THREAD

**Issue by PerMildner** [MicrosoftDocs/cpp-docs#259]
The docs should emphasize that _open_osfhandle does not take a HANDLE (!) so when calling _open_osfhandle the first argument must be cast from HANDLE to intptr_t (to prevent "warning C4047: 'function': 'intptr_t' differs in levels of indirection from 'HANDLE'" and "warning C4024: '_open_osfhandle': different types for formal and actual parameter 1").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25d8611-6401-b7b6-7df9-00fc9ee3987a
* Version Independent ID: 0a3f89eb-3b0c-7a1e-16c0-f394915c3837
* Content: [_open_osfhandle](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle)
* Content Source: [docs/c-runtime-library/reference/open-osfhandle.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/open-osfhandle.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I have no idea why there's an impedance mismatch here. I've added a comment to _open_osfhandle and _get_osfhandle to address it. It should show up in a day or two.
