### ISSUE TITLE
This is now a clearer and better text, as far as I can see...

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2594]
Although for C++ teams it might be important to inform `_HAS_EXCEPTIONS` value depends on `_KERNEL_MODE` and is best left to compile-time machinery to decide on its value when using the `/kernel` mode:

```cpp
// <vcruntime.h> near to #100

#ifndef _HAS_EXCEPTIONS // Predefine as 0 to disable exceptions
    #ifdef _KERNEL_MODE
        #define _HAS_EXCEPTIONS 0
    #else
        #define _HAS_EXCEPTIONS 1
    #endif // _KERNEL_MODE
#endif // _HAS_EXCEPTIONS
```
HTH

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab4cd21-5a26-620f-9bd4-403a02b2b915
* Version Independent ID: 41e125c3-a7bc-69cb-7142-43974c5fe519
* Content: [/kernel (Create kernel mode binary)](https://docs.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/reference/kernel-create-kernel-mode-binary.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/kernel-create-kernel-mode-binary.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
