### ISSUE TITLE
Global Exception Handler help is missing information about SetUnhandledExceptionFilter()

### ISSUE THREAD

**Issue by JSpencerSeagull** [MicrosoftDocs/cpp-docs#2598]
Our C++/CLI code currently already uses SetUnhandledExceptionFilter() to catch all unhandled exceptions for our application. It then creates a crash dump and allows the OS / Dr. Watson to process the unhandled exception normally.

It's unclear to us if this mechanism should work for managed (c sharp) code as well. It would be very helpfull if the relationship between the global exception handler and SetUnhandledExceptionFilter() was explained. 

So I recommend either adding this information to this page or creating a link to a page that describes it. 

Thanks, Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1987113-3ef0-fd6f-afa9-7a18203839ad
* Version Independent ID: a231cd80-22b9-0b72-bf2b-26b0b2138c1a
* Content: [How to: Define and Install a Global Exception Handler](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-define-and-install-a-global-exception-handler?view=msvc-160)
* Content Source: [docs/dotnet/how-to-define-and-install-a-global-exception-handler.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-define-and-install-a-global-exception-handler.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
