### ISSUE TITLE
This object must be at global scope

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/cpp-docs#260]
Its destructor calls ::Windows::Foundation::Uninitialize and cause havoc if you make the mistake of using this at inner scope somewhere. Make sure it is global or top-level scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c883ad85-5926-09a1-19c7-b63a284bdba6
* Version Independent ID: bc9a3b9b-6eab-6923-9694-511ee0cc9700
* Content: [RoInitializeWrapper Class](https://docs.microsoft.com/en-us/cpp/windows/roinitializewrapper-class)
* Content Source: [docs/windows/roinitializewrapper-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/roinitializewrapper-class.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed!
