### ISSUE TITLE
_ReadWriteBarrier used after a big fat red warning not to use it?

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2601]
Ok, we have the big fat red warning about using `_ReadWriteBarrier`, but then within `<atomic>` there is this macro:

```cpp
#define _Compiler_barrier() _STL_DISABLE_DEPRECATED_WARNING _ReadWriteBarrier() _STL_RESTORE_DEPRECATED_WARNING
```

And that is used a lot inside `<atomic>` various inline implementations. 

Please advise?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d13f81a-9967-3546-04b4-e4dc92b772ba
* Version Independent ID: 13a10179-337b-088c-0012-d60ded244820
* Content: [_ReadWriteBarrier](https://docs.microsoft.com/en-us/cpp/intrinsics/readwritebarrier?view=msvc-160)
* Content Source: [docs/intrinsics/readwritebarrier.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/readwritebarrier.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ 

Good question. I recall being told to add the caution several years ago by members of the compiler team. The reason being, these intrinsics represent compiler barriers, not hardware barriers. The distinction is apparently lost on our readers, which led to much bug reporting. The deprecated intrinsics' action isn't a lot different from turning optimizations off locally to prevent instruction reordering. The \<atomic> implementation adds processor-specific hardware barrier instructions where they're needed, and will use the compiler-barrier intrinsics by themselves where the underlying hardware does the expected thing without additional barrier instructions.

There are more finely-grained memory barrier intrinsics available for specific processors, and those are not deprecated. There are also the `_Interlocked` primitives if you aren't trying to be compatible across compilers and want to implement your own atomic controls. The reason to use \<atomic> is the same as it ever was; it's standard, cross-platform, and both safer and easier to use compared to rolling your own, something notoriously difficult to get right.

It's possible I'm wrong in some way about the deprecation reasons. If you'd like to get the perspective of the Standard Library team, you can [raise a question on their GitHub repo](https://github.com/microsoft/STL/discussions). They generally know what they're doing, and may have a better explanation than I've provided.

**Comment by DBJDBJ** [comment]
@corob-msft  many thanks ... what I am looking for inside MSFT is a "standard C team" and "the CL team". We are also having projects in "standard cross-platform ISO C" without any C++.

Now that `/std:c11` and `/std:c17` are here we are "almost there"
