### ISSUE TITLE
Example code attribute errors

### ISSUE THREAD

**Issue by LordDanielW** [MicrosoftDocs/cpp-docs#2609]
This code does not compile.  

The  errors are:
![image](https://user-images.githubusercontent.com/19895389/99818964-dbb3bb80-2b1c-11eb-9330-9814aee34736.png)
'event_receiver': attribute not found
'event_source': attribute not found
'native': undeclared identifier
'native': undeclared identifier

Visual studio 2019 community edition, default c++ compiler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f09726-cc61-858c-3a0d-4fc80a0288b0
* Version Independent ID: d0ef017b-b938-4401-6c9a-1405bd60e096
* Content: [Event Handling in Native C++](https://docs.microsoft.com/en-us/cpp/cpp/event-handling-in-native-cpp?view=msvc-160)
* Content Source: [docs/cpp/event-handling-in-native-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/event-handling-in-native-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LordDanielW 

I'm sorry it's giving you trouble. The code compiles and runs for me at the command line, although it does give a warning about being deprecated. If you're trying to run this example in the IDE, I suggest starting with the **Empty Project** template, and turn off the **`/permissive-`** option, which is now set by default. That's found in the **Project Property Pages** dialog, under **Configuration Properties > C/C++ > Language**, in the **Conformance mode** property. Set it to **No**. The Microsoft extension that supports event attributes is incompatible with strict conformance mode.

I'll make a note of that in the document. Thanks for the report.

**Comment by corob-msft** [comment]
A fix should be visible by sometime the next business day.
