### ISSUE TITLE
libcurl dependencies

### ISSUE THREAD

**Issue by tester0077** [MicrosoftDocs/cpp-docs#2611]
I have libcurl installed in/via vcpkg and am trying to use the library, but I get unresolved linker errors, such as:
4>libcurl-d.lib(multi.c.obj) : error LNK2019: unresolved external symbol __imp__WSACloseEvent@4 referenced in function _curl_multi_cleanup
...
4>libcurl-d.lib(ftp.c.obj) : error LNK2001: unresolved external symbol __imp__inet_pton@12
...
4>libcurl-d.lib(schannel.c.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _schannel_connect_step1
...
4>libcurl-d.lib(schannel_verify.c.obj) : error LNK2019: unresolved external symbol __imp__CryptDecodeObjectEx@32 referenced in function _cert_get_name_string

My assumption was that vcpkg would install all dependencies, but I see nothing installed which would help me sort this out.
As well, I am trying to use a static linked version of libcurl and yet the __imp__ strings seem to imply DLLs are needed.

**Comment by corob-msft** [comment]
Hi, @tester0077 -

I'm sorry you're having trouble, and I'm also sorry that I have to close this issue and redirect you elsewhere for support. The cpp-docs issues board is for filing bugs or making suggestions for the documentation. For product behavior questions that are best addressed by the product development team, the place to raise issues is in the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. For more general programming questions, I recommend the [C++ board](https://docs.microsoft.com/en-us/answers/topics/c++.html) on Microsoft Docs Q&A. And for issues with vcpkg as a program, and the library build recipes supplied, you can [raise issues on the vcpkg GitHub repo](https://github.com/microsoft/vcpkg/issues). That last link might be where I'd start. It's worth spending some time to search for similar issues before you add your own.

It does look like the libcurl build might be missing import libraries for (I'm guessing just based on the import names) crypt32.lib and ws2_32.lib. It seems odd that they'd be missing if needed, but maybe your particular combination of features specified for the libcurl build was missing something that would pull them in? I don't know. Good luck to you.

**Comment by tester0077** [comment]
Thank you for even looking at this.
Eventually I satisfied all of the missing symbols messages by manually including the appropriate M$ libraries.
