### ISSUE TITLE
There is no cl.exe installed alongside the Visual Studio Build Tools

### ISSUE THREAD

**Issue by Foadsf** [MicrosoftDocs/cpp-docs#2614]
Following the instructions on [this page](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-160), I installed the Visual Studio Build Tools 2019. According to the mentioned documentation:

> The Build Tools for Visual Studio version of Visual Studio installs only the command-line toolset, the compilers, tools, and libraries you need to build C and C++ programs.

However, when running the `Developer Command Prompt for VS 2019` there is no `cl.exe`

> 'cl' is not recognized as an internal or external command, operable program or batch file.

**P.S.** BTW I was one of the people who actually requested this feature [here](https://developercommunity.visualstudio.com/idea/954596/installing-the-command-line-only-compilers-without.html).

**Comment by corob-msft** [comment]
@Foadsf 
I'm sorry you're having difficulty. This isn't a support channel *per se*, but I can think of a couple of reasons the effect you're seeing could happen.

The first could happen if you've only installed the Visual Studio Build Tools. You have to specifically select the C++ build tools for installation when you run the Visual Studio Installer. The build tools create their own developer command prompt (DCP) entries in the Start menu. If you choose the .NET build tools, but not the C++ build tools, you can run the cs compiler in the DCP, but not the cl compiler. To fix it, run the Visual Studio Installer again, and choose the Modify button by the Visual Studio Build Tools. On the next page, select the Visual C++ build tools, and press the Modify button. Once it runs, the DCP should include cl.exe on the path. 

The second way might happen if you've installed the Visual Studio IDE without the C++ build tools, and then installed the Visual Studio Build Tools separately *with* the C++ build tools. You'll see two entries in the Visual Studio Installer, one for the build tools, and one for the IDE. They'll both insert DCP shortcuts in the Start Menu. The binaries get installed in separate folders; you can run both VS and the build tools side by side. In this case, you have to choose the right developer command prompt shortcut from the Start menu. Yes, it's confusing. If you have double entries for developer command prompt shortcuts in the Start menu's Visual Studio 2019 folder, that's what's going on. Whichever one got installed second will have shortcuts that end in `(2)`, probably.

My reading of the article shows it covers the first case. I don't think the second case is common enough to merit a documentation change; describing it would just clutter the article up for the great majority of readers. Therefore, I'm closing the issue. If you feel there's something useful to be changed here, you're welcome to argue your case, and I'll consider it.

**Comment by Foadsf** [comment]
Dear @corob-msft ,

Thanks a lot for the reply. I have followed the [documentation](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-160) exactly as is instructed. And then installed the [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) following the default settings. I think it would be a good idea to update the documentation and mention the required step if does not include the `cl.exe` by default.

Moreover, If I modify the installation and manually add the C++ build tools

![Capture2](https://user-images.githubusercontent.com/12762442/100007857-f7dd8400-2dcc-11eb-983b-c4f89b7f655b.PNG)


Then it becomes 6.2GB of installation, which I suppose includes the Visual Studio GUI/IDE and contradicts the feature request I have asked for [here](https://developercommunity.visualstudio.com/idea/954596/installing-the-command-line-only-compilers-without.html). And if it doesn't include the GUI/IDE Visual Studio then the question is why is a compiler 6.2GB?! 🤔
