### ISSUE TITLE
ambiguity in discussing calls to GetExceptionCode

### ISSUE THREAD

**Issue by bknittel** [MicrosoftDocs/cpp-docs#2620]
[Enter feedback here]

When discussing both the __except() statement expression (the "filter expression") and the use of a filter <i>function</i>, the word "filter" by itself is ambiguous.  The except() statement expression should be called the "filter expression" or, more verbosely but somewhat clearer, "the __except statement's filter expression",

So, in the paragraphs under the C++ sample code, the sentence

    You must call this function inside the filter itself. 

might be more clearly stated as

    You must call this function in the __except () statement's filter expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f78358-2080-9921-3252-adf8db58acd3
* Version Independent ID: e069ddc2-bb6b-8a46-2024-21c7e5bd7cbc
* Content: [Writing an exception filter](https://docs.microsoft.com/en-us/cpp/cpp/writing-an-exception-filter?view=msvc-160)
* Content Source: [docs/cpp/writing-an-exception-filter.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/writing-an-exception-filter.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bknittel 
Thanks for the report. I've attempted to clarify the language a little here in an update that's available now.
