### ISSUE TITLE
Should fully specify the effect of using this intrinsic

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#2622]
We should fully specify in documentation the effects of the intrinsics.

In particular (relevant to me as I write this), for __noop(), its arguments are considered "referenced" by the compiler, so it can be used to silence warning C4100 "unreferenced formal parameter" and similar, wherever appropriate.

Example:

```
// Use __noop so assertions on variables that are not otherwise referenced won't cause "unreferenced" warnings.
#define MyAssert(c) do { assert(c); __noop(c); } while (false)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf760e5-e83c-219d-1ced-250f9e0760f2
* Version Independent ID: a27b6550-93b1-8e60-7269-4079219c2ae7
* Content: [__noop](https://docs.microsoft.com/en-us/cpp/intrinsics/noop?view=msvc-160)
* Content Source: [docs/intrinsics/noop.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/noop.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheJCAB 
Your initial request is a bit too broad to address all at once. However, it's easy enough to mention the fact that the compiler considers `__noop` arguments referenced, so I added that and updated the sample.

**Comment by TheJCAB** [comment]
Thank you!
