### ISSUE TITLE
There is no "installed templates" when you click on new project.

### ISSUE THREAD

**Issue by marcel-landman** [MicrosoftDocs/cpp-docs#2634]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2381f0f1-6b3e-694d-3902-c5cd8397f806
* Version Independent ID: 0f1a499c-62ab-0a3a-703d-2d3c635bc751
* Content: [How to: Create CLR Console Applications (C++/CLI)](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-create-clr-console-applications-cpp-cli?view=msvc-160)
* Content Source: [docs/dotnet/how-to-create-clr-console-applications-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-create-clr-console-applications-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@marcel-landman 

Thanks for pointing that out. The instructions haven't been updated for VS 2017 and 2019, which have a different new project dialog. We'll give the instructions an update. 

For now, here's how to create a new CLR console project: On the menu bar, choose **File > New > Project** to open the **Create a new project** dialog. Enter *clr console* in the search box. Select **CLR Console App (.NET Framework)** from the list of templates, and then choose **Next**. On the **Configure your new project** page, enter a project name, then choose **Create**. You should be good to go.

**Comment by marcel-landman** [comment]
Thanks Colin.

I do not get any template matches for  “clr console”. In fact, there are no template matches to “clr” at all. The search is a nice feature, but the old hierarchical would have been a nice fall back. The hierarchical view takes more effort to find a template, but it doesn’t leave me with the feeling “am I typing the write keywords”.

My work around was to create a c++ console app and change the “configuration type” in “General”. It seems to work somewhat but I am having difficulties with intellisense. I am #using <some_csharp_project.dll>, which intellisense highlights as “unknown directive” eventhough it compiles fine. I tried deleting the .vs directory and restart VS. Intellisense does detect when I misspell a property in one of the classes from that dll, but suggestions don’t work so I end up doing a lot of jumping back and forwards. So perhaps other properties were needed which I probably would have gotten if I had found the right template.

Regards,
Marcel

**Comment by corob-msft** [comment]
@marcel-landman 

If the CLR template didn't appear, then if may be you haven't installed support for C++/CLI in Visual Studio. If you launch the VS installer and choose the **Modify** button, there's an **Individual components** tab next to **Workloads** at the top of the next page. Choose it, then scroll to the **Compilers, build tools, and runtimes** section, where you should see several options for C++/CLI. Select the latest one, then choose the **Modify** button. I think this is all you need, as long as you've also already installed the .NET desktop development workload. The compiler already knows how to compile for /clr, but the component adds other support you need to the IDE.

**Comment by corob-msft** [comment]
Content updated a week ago, but I forgot to close the issue.
