### ISSUE TITLE
Enterprise only?

### ISSUE THREAD

**Issue by adamsd5** [MicrosoftDocs/cpp-docs#2635]
I don't see the options for VS2019 community.  Should I?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0acbb6-5b9f-b28d-a7c8-196049ee561f
* Version Independent ID: c77469e1-7c9f-3dcd-c2e5-63c75f160e1a
* Content: [Install the C++ Linux workload in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=msvc-160)
* Content Source: [docs/linux/download-install-and-setup-the-linux-development-workload.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/download-install-and-setup-the-linux-development-workload.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@adamsd5 
I'm unsure which options you're talking about. Do you mean you don't see the **Linux development with C++** workload in the installer? It should be present in all editions of Visual Studio 2019 on Windows, with the possible exception of the Build Tools edition, which doesn't include the IDE.

**Comment by corob-msft** [comment]
Closing due to no obvious doc issue to address.
