### ISSUE TITLE
Modify example to function as intended

### ISSUE THREAD

**Issue by BlenderChrisDW** [MicrosoftDocs/cpp-docs#2636]
It appears that in the first example "Example arguments to main" there will be no output unless the "/n" argument is used. I would suggest that the last line be split as such:

```
for (int i = 0; envp[i] != NULL; ++i) {
        if (iNumberLines)
            cout << i << ": ";   // prepend number only for iNumberLines = 1
        cout << envp[i] << "\n"; // default with no line numbers
 }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c5ec8f-dc90-d0bd-5aa5-1340ccc877c3
* Version Independent ID: 19646aca-3da3-14e8-ea9a-fcb3020cf51c
* Content: [`main` function and command-line arguments (C++)](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-160)
* Content Source: [docs/cpp/main-function-command-line-args.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/main-function-command-line-args.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@BlenderChrisDW 
Thanks for the report. While there might have been some logic to the sample behavior, it wasn't very good logic, so I've updated it per your suggestion.
