### ISSUE TITLE
Last example missing constructor parameters

### ISSUE THREAD

**Issue by BlenderChrisDW** [MicrosoftDocs/cpp-docs#2637]
sd1 missing parameters

```
int main() {
   // ShowData sd1, sd2( "hello.dat" );
   ShowData sd1("CON"), sd2( "hello.dat" );

   sd1.Disp( "hello to default device\n" );
   sd2.Disp( "hello to file hello.dat\n" );
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c79542-ceaa-f395-69bf-07ba08051fe7
* Version Independent ID: 1bd9739b-d3b4-9dd1-3d61-e07c924d8856
* Content: [C++ program termination](https://docs.microsoft.com/en-us/cpp/cpp/program-termination?view=msvc-160)
* Content Source: [docs/cpp/program-termination.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/program-termination.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@BlenderChrisDW 
Thanks for the report. An update that fixes the missing initialization should be visible by the end of tomorrow.
