### ISSUE TITLE
information about the content of debugInfo is missing

### ISSUE THREAD

**Issue by slymz** [MicrosoftDocs/cpp-docs#2638]
Various documentation, most notably launch.vs.json and CMake Debugging settings, reference ${debugInfo.}  collection of variables.  However, the extensive list of fields available in debugInfo is no where to be found. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43899bd1-664f-ee64-b56d-fc2b60464aed
* Version Independent ID: 7703eb41-41a8-6c69-5584-5df0f8962abf
* Content: [launch.vs.json schema reference (C++)](https://docs.microsoft.com/en-us/cpp/build/launch-vs-schema-reference-cpp?view=msvc-160)
* Content Source: [docs/build/launch-vs-schema-reference-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/launch-vs-schema-reference-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CraigHutchinson** [comment]
I am very interested in this one. I have issue that I am having to hard code the path to the built binary into the `setupCommands` and `${debugInfo.fullTargetPath}` has the filename and I just need the Path to the target which maybe already exists but I cannot manage to 'guess' this yet!

**Comment by TylerMSFT** [comment]
I am pulling together some information about those properties from the team and will add it in a few days.

**Comment by TylerMSFT** [comment]
@CraigHutchinson , @slymz , I have added the DebugInfo macros to this article: https://docs.microsoft.com/cpp/build/launch-vs-schema-reference-cpp?view=msvc-160
