### ISSUE TITLE
bug on the jami app

### ISSUE THREAD

**Issue by 78uh78uj** [MicrosoftDocs/cpp-docs#2642]
[Enter feedback here]
 I got  bugs on the jami, is stoping sharing location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b965be6-8dfd-db91-84e3-345e70d7c302
* Version Independent ID: 291bf1e4-c8f7-12e9-3f38-f54bbd822bc7
* Content: [Create an Android Native Activity App](https://docs.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@78uh78uj 
I'm sorry you're having difficulty. The problems you describe don't seem related to this particular article, so I'm closing the issue. For development questions, you can check our [Docs Q&A forum](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). For product issues, support is available on the Visual Studio [C++ Developer Community](https://aka.ms/vsfeedback/browsecpp) site. Documentation on troubleshooting issues with the Android NDK and the Google emulators is also available on the [Android Developer](https://developer.android.com/studio/run/emulator-troubleshooting) site. Best of luck.
