### ISSUE TITLE
Abbreviation

### ISSUE THREAD

**Issue by bugaevski** [MicrosoftDocs/cpp-docs#2644]
Normally, if abbreviation is used - the description of what this abbreviation stands for - comes at the very beginning,

Who is: "MFC"?...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdcc81c-612f-def3-d33c-9d82c69d6e1b
* Version Independent ID: 8faf20c2-819c-745b-e031-357569c4aca9
* Content: [MFC Application Architecture Classes](https://docs.microsoft.com/en-us/cpp/mfc/mfc-application-architecture-classes?view=msvc-160)
* Content Source: [docs/mfc/mfc-application-architecture-classes.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/mfc-application-architecture-classes.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @bugaevski , I've addressed this by defining MFC in the first sentence of the topic. The fix should be live by end of day 12/9/2020. Thank you for taking the time to help us improve the docs.
