### ISSUE TITLE
Where is the " General toolbar"?

### ISSUE THREAD

**Issue by adamsd5** [MicrosoftDocs/cpp-docs#2645]
This documentation mentions the " General toolbar", but I cannot find such a thing.   Do you mean "Standard"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7a4e8b-d422-93b1-e042-55c2acbf8ef3
* Version Independent ID: 0d55f5d8-846e-3282-b580-9b7770053958
* Content: [Configure CMake debugging sessions in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=msvc-160)
* Content Source: [docs/build/configure-cmake-debugging-sessions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configure-cmake-debugging-sessions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@adamsd5 
Yes. I think someone may have confused their toolbar names and their property page names.

**Comment by corob-msft** [comment]
An update without the problem toolbar name is available now.
