### ISSUE TITLE
Short on details

### ISSUE THREAD

**Issue by MrScottAtt** [MicrosoftDocs/cpp-docs#2648]
Could use more detail for the Exports.  Perhaps a line or two explaining that the mangled symbol is followed by the original unmangled declaration in parentheses.  Are there other formats?

Is the leading "?" significant?  

A reference to the mangling rules would be great.

Example line of output from /EXPORTS:
                  ?fixed64@UnknownField@protobuf@google@@QEBA_KXZ (public: unsigned __int64 __cdecl google::protobuf::UnknownField::fixed64(void)const )

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11e1c08-00a6-4f60-869e-ecddca28fa27
* Version Independent ID: fa1c97ce-025a-26c5-9918-a5728e4623cf
* Content: [/EXPORTS](https://docs.microsoft.com/en-us/cpp/build/reference/dash-exports?view=msvc-160)
* Content Source: [docs/build/reference/dash-exports.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dash-exports.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
