### ISSUE TITLE
Mark code as cpp

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/cpp-docs#265]
I read the CPP docs, and in many places, the code samples not mark as cpp- "```cpp" and the code look bad.

**Comment by mikeblome** [comment]
Thanks @baruchiro. We have a work item on our backlog to find and fix all these instances. I'll make a note that customers are noticing this, which will help us prioritize.  It's difficult to automate reliably because markdown unfortunately uses ``` for both beginning and end markers.

**Comment by mikeblome** [comment]
@baruchiro We updated the examples in the C++ language reference.  I'm closing this issue, but feel free to create a new one if you find additional problems.
