### ISSUE TITLE
EXPORTS statement in .def file needs clarification on internal_name decoration

### ISSUE THREAD

**Issue by tanzislam** [MicrosoftDocs/cpp-docs#2653]
Consider this `library.c` file, containing a global function without `__declspec(dllexport)`:

```c
int __cdecl multiply(int a, unsigned int b)
{
    int ret = 0;
    while (b--) ret += a;
    return ret;
}
```

I compile it with MSVC 2019 v16.8.3 Community Edition in a **x86 Native Tools Command Prompt for VS2019** window, and then `dumpbin` shows the symbol name with [leading underscore as expected](https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=msvc-160#FormatC):

```
>cl /W3 /nologo -c /Folibrary.obj library.c
>dumpbin /nologo /symbols library.obj
...
008 00000000 SECT3  notype ()    External     | _multiply
```

Now consider this `library.def` file, which has a _internal_name_ to match the symbol name exported by the compiler:

```
LIBRARY "LIBRARY"
EXPORTS
    multiply=_multiply
```

Trying to link a DLL with it results in an error:

```
>link /nologo /dll /incremental:no /def:library.def /out:library.dll library.obj
library.def : error LNK2001: unresolved external symbol _multiply
library.lib : fatal error LNK1120: 1 unresolved externals
```

If I remove the _internal_name_ (let's call it `library2.def`) then it succeeds:

```
LIBRARY "LIBRARY"
EXPORTS
    multiply
```
```
>link /nologo /dll /incremental:no /def:library2.def /out:library.dll library.obj
   Creating library library.lib and object library.exp
>dumpbin /nologo /exports library.dll
...
    ordinal hint RVA      name

          1    0 00001000 multiply
```

Changing the _internal_name_ to `multiply` (without the leading underscore) also works.

This seems to be contrary to (or at least confusing with regards to) what is currently documented in [this page](https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=msvc-160) about decorated names (as viewed with `dumpbin`) and what is to be used as the _internal_name_:

>Because the MSVC compiler uses name decoration for C++ functions, you must either use the decorated name _internal_name_ or define the exported functions by using `extern "C"` in the source code. The compiler also decorates C functions that use the __stdcall calling convention with an underscore (_) prefix and a suffix composed of the at sign (@) followed by the number of bytes (in decimal) in the argument list.

Doesn't the compiler also decorate `__cdecl` C functions with an underscore? (Otherwise why did `dumpbin /nologo /symbols library.obj` show a leading underscore?)

I only found a hint in the Remarks section of the page documenting the [`/EXPORT` command-line option to `link.exe`](https://docs.microsoft.com/en-us/cpp/build/reference/export-exports-a-function?view=msvc-160):

>**Note**
>Do not specify the decorated form of C identifiers that are declared `__cdecl` or `__stdcall`.

If the `EXPORTS` statement of a `.def` file behaves similarly to the `/EXPORT` command-line option (i.e. the user must provide un-decorated names for both `__cdecl` and `__stdcall` C identifiers) then this should be documented more prominently in both pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c796dd-5105-cdd2-7a4d-b4f7713d57dd
* Version Independent ID: 7698174e-3277-935a-4d3c-1c430133dbfd
* Content: [EXPORTS](https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=msvc-160&source=docs)
* Content Source: [docs/build/reference/exports.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/exports.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
