### ISSUE TITLE
Gibberish sentence in C4027 doc

### ISSUE THREAD

**Issue by mcclure** [MicrosoftDocs/cpp-docs#2654]
"The function declaration no formal parameters"

This sentence no verb. Maybe you meant "declares"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b66d61-7a6b-4f87-9a0f-0bc164a983b4
* Version Independent ID: d338526f-6627-c80d-5383-0a37d3e51da0
* Content: [Compiler Warning (level 1) C4027](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4027?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4027.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4027.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mcclure 
Thanks for the report. An update with readable grammar is available now.
