### ISSUE TITLE
Can't Compile successfully in reinterpret_cast example

### ISSUE THREAD

**Issue by GFLing** [MicrosoftDocs/cpp-docs#2657]
[Enter feedback here]
I had tried to compile the example, but I got the error below:
```
error: cast from ‘void*’ to ‘unsigned int’ loses precision [-fpermissive]
    6 |    unsigned int val = reinterpret_cast<unsigned int>( p );
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'm using g++ 10.2, but I think that's doesn't matter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af1d166-9a82-fd83-0e09-0c697459deb9
* Version Independent ID: 6c28faae-6871-efdf-0b0c-245716aaf57c
* Content: [reinterpret_cast Operator](https://docs.microsoft.com/en-us/cpp/cpp/reinterpret-cast-operator?view=msvc-160)
* Content Source: [docs/cpp/reinterpret-cast-operator.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/reinterpret-cast-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by rindlespot** [comment]
I'll bet you're compiling for 64bit.  Casting a 64bit pointer to a 32bit int would indeed "lose precision."  Code probably works fine for 32bit.

**Comment by corob-msft** [comment]
@GFLing 

@rindlespot has the right idea; there may be an unstated assumption in the code that pointers and `int` types are the same size. In any case, this doesn't seem like a documentation issue to be addressed, *per se*. Everything to do with `reinterpret_cast` is necessarily implementation-specific, and you may use it in ways that intentionally lose data or significance.
