### ISSUE TITLE
Article refers to NuGet package Microsoft.Gsl, which is no longer maintained

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/cpp-docs#2658]
The [Use the Guideline Support Library](https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=msvc-160#use-the-guideline-support-library) section says:

> The GSL is available at <http://www.nuget.org/packages/Microsoft.Gsl>.

However, the linked page in NuGet Gallery warns:

> This package has been deprecated as it is legacy and is no longer maintained.

I suppose the article should link to installation instructions within the GSL repository, instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725a4cd3-5880-a22b-c148-c594231a3ff3
* Version Independent ID: 295baf60-5b4e-162f-bc23-0675213477fc
* Content: [Using the C++ Core Guidelines checkers](https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=msvc-160)
* Content Source: [docs/code-quality/using-the-cpp-core-guidelines-checkers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/using-the-cpp-core-guidelines-checkers.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@KalleOlaviNiemitalo 
Thanks for the report. An update with a fix is available now.
