### ISSUE TITLE
Error in bold

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/cpp-docs#266]
If an operator can be used as either a unary or a binary operator (&, \, **+, and **-*), you can overload each use separately.
Should be '(&, \, +, and -)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e802674-94b5-95ba-3a7c-c183707d9af7
* Version Independent ID: 1317f21b-c61e-a987-2cef-f612f1ef7f67
* Content: [General Rules for Operator Overloading](https://docs.microsoft.com/en-us/cpp/cpp/general-rules-for-operator-overloading)
* Content Source: [docs/cpp/general-rules-for-operator-overloading.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/general-rules-for-operator-overloading.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed. Thanks @baruchiro !
