### ISSUE TITLE
The docs for "_Analysis_assume" are showing the incorrect name

### ISSUE THREAD

**Issue by rindlespot** [MicrosoftDocs/cpp-docs#2661]
The docs for "_Analysis_assume" are showing the incorrect name.  This macro (defined in SAL.h) uses a trailing underscore: "\_Analysis_assume\_".  The incorrect name is used several times on the page, including the sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614d6a8c-d35a-07df-ad34-2c1ac150f4d2
* Version Independent ID: c8fa0cf8-20ed-6ef0-80c8-4ca515eb73ec
* Content: [Use _Analysis_assume for code analysis hints](https://docs.microsoft.com/en-us/cpp/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume?view=msvc-160)
* Content Source: [docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rindlespot 
Thanks for the report. An update with the correct spelling is available now.

**Comment by rindlespot** [comment]
Of the 6 appearances of this macro on the page, you fixed 5.  While that is a significant improvement...

The final one follows the text "use the following function macro:" and appears in grey.

**Comment by rindlespot** [comment]
Somewhere along the way, the last one got corrected.

**Comment by rindlespot** [comment]
Closing.
