### ISSUE TITLE
C6295 error not balanced

### ISSUE THREAD

**Issue by Spidy104** [MicrosoftDocs/cpp-docs#2663]
For traversing a std::string from the back like (size_t i = str.size()-1;  i >= 0 ; i--)  I am getting this error, if I need to reach index 0 from the end then it will not traverse and in the end we would get std::string::npos.
Hence How to resolve this error??
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a14a74-31f1-1944-42c4-7e8172921a7f
* Version Independent ID: 644d7584-23d2-92dc-44f9-86233dd4874e
* Content: [C6295](https://docs.microsoft.com/en-us/cpp/code-quality/c6295?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C6295)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/code-quality/c6295.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6295.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Spidy104 
This isn't a support forum, but it looks like the warning has done its job: Your code is an infinite loop. `size_t` is an unsigned type and therefore `i` can never be less than zero. It will wrap to the max value and probably cause an access violation crash.

**Comment by Spidy104** [comment]
Thanks 

> @Spidy104
> This isn't a support forum, but it looks like the warning has done its job: Your code is an infinite loop. `size_t` is an unsigned type and therefore `i` can never be less than zero. It will wrap to the max value and probably cause an access violation crash.

Thanks got what you wanted to say
