### ISSUE TITLE
Option to disable for variable length argument list?

### ISSUE THREAD

**Issue by hesadude** [MicrosoftDocs/cpp-docs#2664]
Is there way to make Visual Studio VC not complain E0165 about this for functions with variable length argument list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3839db23-4549-ba31-b9d7-c14cd21d074d
* Version Independent ID: 7e336fe8-a792-fd46-a186-3fb4921dfa52
* Content: [Functions with Variable Argument Lists  (C++)](https://docs.microsoft.com/en-us/cpp/cpp/functions-with-variable-argument-lists-cpp?view=msvc-160)
* Content Source: [docs/cpp/functions-with-variable-argument-lists-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/functions-with-variable-argument-lists-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hesadude 

[There's a way to disable specific IntelliSense errors](https://stackoverflow.com/a/61810989/2002113), but I'd be very careful about using it for that specific error. IntelliSense recognizes variable-length argument lists, and if your function declaration demands any parameters you don't supply, you'll see this error. A call to a function with a variable-length parameter list must supply at least one argument. You can create an overload of your function that takes no arguments, if that's what you'd like to do. If IntelliSense complains, but the compiler doesn't, it's possible something else is going on. 

This doesn't seem like it requires a specific update to the documentation, so I'm closing the issue.
