### ISSUE TITLE
Ending on docs seems out of place

### ISSUE THREAD

**Issue by jonaslagoni** [MicrosoftDocs/cpp-docs#2665]
To me the last header section in the markdown are unnecessary

> **END Microsoft Specific**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b02cc93-0d7c-d1bf-64ab-e6111525c809
* Version Independent ID: 5a9af828-31a5-9042-d997-e662928753bf
* Content: [#include directive (C/C++)](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=msvc-160)
* Content Source: [docs/preprocessor/hash-include-directive-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/hash-include-directive-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by jonaslagoni** [comment]
Ahh, I can see multiple files contain this end statement such as [#undef](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-undef-directive-c-cpp?view=msvc-160) as well, I assume there is a reason for this then?

**Comment by corob-msft** [comment]
@jonaslagoni 

You've discovered an artifact of history. Many of our articles have sections bracketed by

**Microsoft Specific**

  - *Microsoft-specific content goes here.*

**END Microsoft Specific**

This convention dates back to our printed documentation days. It doesn't translate as well on the web. It's been migrated through several versions of content management systems. Sometimes it's been translated into an H2 or H3 header, and sometimes it just has bold formatting. When we touch a file with these markers, we'll often use a different, more subtle way to call out content that's specific to the Microsoft compiler or library implementation, or the Windows platform. Still, this form appears 339 times in 333 articles, by my count, so there's not much point in [addressing it piecemeal](https://github.com/MicrosoftDocs/cpp-docs/pull/2666). We'll come up with a global solution eventually. For now, it's just an object of curiosity.
