### ISSUE TITLE
Append in File

### ISSUE THREAD

**Issue by stfark** [MicrosoftDocs/cpp-docs#2669]
When one appends data to an existing file, this document says that the file pointer is positioned at the end of the file. Does that mean that when the new data record is output, it writes over the previous EOF marker and writes a new EOF marker at the end of the appended data? Sid Kraft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f8fadbc-d677-7b07-ade6-3bedcceb72ab
* Version Independent ID: e691566a-a690-3e69-d942-d9b72c44525b
* Content: [File Position in Append Mode](https://docs.microsoft.com/en-us/cpp/c-language/file-position-in-append-mode?view=msvc-160)
* Content Source: [docs/c-language/file-position-in-append-mode.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/file-position-in-append-mode.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@stfark 

The answer depends on how you open the file, The documentation for functions such as [`fopen`](https://docs.microsoft.com/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-160) and [`freopen`](https://docs.microsoft.com/cpp/c-runtime-library/reference/freopen-wfreopen?view=msvc-160) goes into more detail.
