### ISSUE TITLE
Does ClickOnce work with native C++ applications or just managed C++/CLI?

### ISSUE THREAD

**Issue by ctaggart** [MicrosoftDocs/cpp-docs#2671]
When I read this article, it appears to me like it should be possible to deploy native C++ applications with ClickOnce, especially when it starts talking about the dependencies. The article does not mention anything about .NET or building a C++/CLI  application.  Is it possible to deploy a native C++ application with ClickOnce? If so, can a minimal [ClickOnce application manifest](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-application-manifest?view=vs-2019) example be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b671e574-3870-6247-857d-09df0c47448c
* Version Independent ID: c1767959-a294-d432-ef80-314cdc483592
* Content: [ClickOnce Deployment for Visual C++ Applications](https://docs.microsoft.com/en-us/cpp/windows/clickonce-deployment-for-visual-cpp-applications?view=msvc-160)
* Content Source: [docs/windows/clickonce-deployment-for-visual-cpp-applications.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/clickonce-deployment-for-visual-cpp-applications.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ctaggart 
Sorry to disappoint, but [ClickOnce isn't available for purely native C++ apps](https://docs.microsoft.com/en-us/cpp/windows/deploying-native-desktop-applications-visual-cpp?view=msvc-160). The doc should be updated to clarify that, though it may not happen for a while.

**Comment by TylerMSFT** [comment]
I updated this doc to call out that ClickOnce does not support deployment of native C++ applications, but that you can use ClickOnce to deploy a Visual C++ application if it is a dependency of a Visual C# or VB.NET project. 
This update will be live Monday afternoon.
