### ISSUE TITLE
Which header is this class defined in?

### ISSUE THREAD

**Issue by ClintWeisbrod-ES** [MicrosoftDocs/cpp-docs#2676]
Great documentation except I don't see ANYWHERE on the page that says which header to include!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9b7acc-1ab4-e60c-7743-618751015b61
* Version Independent ID: 6a720992-abb5-3daa-e7be-3e7d9e0d6c66
* Content: [COleDropTarget Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/coledroptarget-class?view=msvc-160)
* Content Source: [docs/mfc/reference/coledroptarget-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/coledroptarget-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@ClintWeisbrod-ES 
This class is specifically defined in *`afxole.h`*, which is included by several headers, including *`stdafx.h`* and *`afxwin.h`*, if you're trying to avoid redundancy.

**Comment by ClintWeisbrod-ES** [comment]
Thanks! This is my bad. I did end up finding the header it in the doc I was bitching about. Sorry. Was just in a rush and was more scanning than carefully reading the page.

________________________________

**Comment by corob-msft** [comment]
@ClintWeisbrod-ES 
Ah, good, glad you found it. I didn't actually check that bit.
