### ISSUE TITLE
ATL::CImage::Save() needs clarity around RGB vs RGBA images

### ISSUE THREAD

**Issue by omatai** [MicrosoftDocs/cpp-docs#2678]
I have images with a fourth channel. Sometimes I want to save as 3-channel RGB; other times as 4-channel RGBA. I want the compression provided by the PNG format - how do I achieve it? The documentation (disappointingly) does not mention this (common) possibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa78f56-aed9-e282-4a30-6e0656f48074
* Version Independent ID: f428718a-ad6b-908b-5967-a6361ee977d8
* Content: [CImage Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cimage-class?view=msvc-160)
* Content Source: [docs/atl-mfc-shared/reference/cimage-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cimage-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
