### ISSUE TITLE
Testing types for validity in register passing for returns

### ISSUE THREAD

**Issue by Penguinwizzard** [MicrosoftDocs/cpp-docs#268]
Is there a good way with c++ templates to test a particular type to ensure that it is returned in registers? I'd like to static assert on that; for certain scenarios (e.g. JIT), it's highly significant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641311e5-13c2-b0c1-6f73-911c022e6487
* Version Independent ID: 0cb0bc33-c2c2-5031-4e53-28feb5fae0a8
* Content: [Return Values (C++)](https://docs.microsoft.com/en-us/cpp/build/return-values-cpp)
* Content Source: [docs/build/return-values-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/return-values-cpp.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This sounds like a good question for StackOverflow. I don't think it's one we could or should address in this document. Off the top of my head, there's no test I can think of that says "This object is definitely going to be returned by value in RAX." The best you can do is "This object can theoretically be returned by value in RAX" if it's POD and 64 bits or less.
