### ISSUE TITLE
[Feedback] E0070 Cause : Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by yeokaiwei** [MicrosoftDocs/cpp-docs#2681]
One very simple cause for E0070 'incomplete type is not allowed" is not including
"#include <array>". 

Once you add it in, it's solved. 

I hope this can be added into the error explaination.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71b9bef-b294-8d79-aaf8-f3df9aaa75af
* Version Independent ID: ad1889e2-413e-2adf-e820-168123f50ed4
* Content: [Incomplete Types](https://docs.microsoft.com/en-us/cpp/c-language/incomplete-types?view=msvc-160)
* Content Source: [docs/c-language/incomplete-types.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/incomplete-types.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
