### ISSUE TITLE
no reason provided

### ISSUE THREAD

**Issue by Ravenwater** [MicrosoftDocs/cpp-docs#2684]
the replacement of enum to enum class is not motivated, so lost opportunity to elucidate both the compiler as well as the language

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf7794d-48cb-0ace-c071-59c9a8ccf2b0
* Version Independent ID: d15818cc-3f5f-e618-6c8b-78ca0bbf7443
* Content: [c26812](https://docs.microsoft.com/en-us/cpp/code-quality/c26812?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26812)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/code-quality/c26812.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26812.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @JordanMaples
* Microsoft Alias: **jomaples**

**Comment by JordanMaples** [comment]
This warning aligns with the C++ Core Guidelines rule Enum.3, which is linked in the [See Also section](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums).
>To minimize surprises: traditional enums convert to int too readily.
