### ISSUE TITLE
Link to CMake site is broken

### ISSUE THREAD

**Issue by rquarry** [MicrosoftDocs/cpp-docs#2686]
The first paragraph contains a link to "learn more about" CMake that dumps the user at the CMake main site page (https://cmake.org). Was this supposed to link to the CMake tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rquarry 
The link isn't broken, as it goes to the intended target, but the link text could use some attention. The CMake site main page used to have [Build, Test and Package Your Software With CMake](https://web.archive.org/web/20180416181104/https://cmake.org/) (per archive.org) as its headline, so we just copied it for our link. I'll take a look at your proposed edit.
