### ISSUE TITLE
Download PDF feature

### ISSUE THREAD

**Issue by pauljurczak** [MicrosoftDocs/cpp-docs#269]
How about adding Download PDF for currently selected chapter only instead of the whole documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg-- A C++ package manager for Windows, Linux and MacOS](https://docs.microsoft.com/en-us/cpp/vcpkg)
* Content Source: [docs/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/vcpkg.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@pauljurczak Thanks for the suggestion. I agree this is a lot of content to put into one PDF. @dend Can we consider this feature request?

**Comment by dend** [comment]
+ @dastaffo who is the PM driving our offline documentation story.

**Comment by dastaffo** [comment]
@pauljurczak Thanks for the suggestion! We'll be looking into some ways to structure PDFs better in the future, so we'll take this into account, but for now this is by design.
