### ISSUE TITLE
Document Core Guideline Checker Warning C26457

### ISSUE THREAD

**Issue by TartanLlama** [MicrosoftDocs/cpp-docs#2694]
The C++ Core Guideline Checker Warning C26457 is not currently documented. Message:

    (void) should not be used to ignore return values, use ‘std::ignore =’ instead

Ticket created on behalf of customer based on [this Developer Community ticket](https://developercommunity2.visualstudio.com/t/Code-analysis-warning-C26457-void-sho/1287662).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5662f578-e59e-a775-a906-985ebb585110
* Version Independent ID: 2ba19d03-52d9-22b9-f536-333ede1edc92
* Content: [Code analysis for C/C++ overview](https://docs.microsoft.com/en-us/cpp/code-quality/code-analysis-for-c-cpp-overview?view=msvc-160)
* Content Source: [docs/code-quality/code-analysis-for-c-cpp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/code-analysis-for-c-cpp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Done - https://learn.microsoft.com/en-us/cpp/code-quality/c26457?view=msvc-170
