### ISSUE TITLE
Provided links not working

### ISSUE THREAD

**Issue by zhelyo** [MicrosoftDocs/cpp-docs#270]
The following links are not working:

AMD64 Instruction Set Reference Manuals 
Intel 64 and IA-32 Architectures Software Developer Manuals 

Best Regards,
Zhelyo Zhelev

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eaedaa6-1524-ecb4-6868-5ff3433ac4ad
* Version Independent ID: 52a76e2c-0b44-4d59-5caa-03592d0aaaa4
* Content: [Processor Manufacturer Programming Manuals](https://docs.microsoft.com/en-gb/cpp/assembler/masm/processor-manufacturer-programming-manuals)
* Content Source: [docs/assembler/masm/processor-manufacturer-programming-manuals.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/processor-manufacturer-programming-manuals.md)
* Service: **unspecified**
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Looks like the updates are live.
