### ISSUE TITLE
INCLUDE environment variable

### ISSUE THREAD

**Issue by 89z** [MicrosoftDocs/cpp-docs#2701]
The `INCLUDE` environment variable accepts a semicolon separated list of paths. However I see no mention of this in the Microsoft docs. So it would be difficult for someone to know what the syntax is, other than guessing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec7ea59-1270-7e09-8240-651d34d7e758
* Version Independent ID: e004b9b0-4031-8bd9-b2bf-247656829ebe
* Content: [/I (Additional include directories)](https://docs.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-160)
* Content Source: [docs/build/reference/i-additional-include-directories.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/i-additional-include-directories.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by 89z** [comment]
As a workaround, I found an example here:

https://stackoverflow.com/questions/60516987

**Comment by corob-msft** [comment]
@89z Thanks for the report. The fix should be visible now.

**Comment by 89z** [comment]
Thank you!
