### ISSUE TITLE
Is there a header file for this definitions? 

### ISSUE THREAD

**Issue by autoantwort** [MicrosoftDocs/cpp-docs#2705]
I don't see a header name. So we have to define the things ourselves? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c516073f-434d-8cba-5b37-796c1c314d28
* Version Independent ID: e0b59364-b0db-1a22-b0b4-a7ac9ec1c287
* Content: [Structure and Constant Definitions](https://docs.microsoft.com/en-us/cpp/build/reference/structure-and-constant-definitions?view=msvc-160)
* Content Source: [docs/build/reference/structure-and-constant-definitions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/structure-and-constant-definitions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by autoantwort** [comment]
Ok there is `delayimp.h` (Found this in the runtime source code). Please add this to the documentation :)

**Comment by autoantwort** [comment]
And the example code is wrong. The Last lines should be:
```cpp
/*
and then at global scope somewhere
const PfnDliHook __pfnDliNotifyHook2 = delayHook;
const PfnDliHook __pfnDliFailureHook2 = delayHook;
*/
```
And you should mention that this must be wrapped by `extern "C" { ... }` when using c++

**Comment by autoantwort** [comment]
And is there a way to do this in a static lib? I did not manage it. So maybe say that it only works in the application and not if you link against a static lib that registers the hooks.

**Comment by corob-msft** [comment]
@autoantwort 
Thanks for the report. I've made the required header a bit more prominent in the documentation. I've also cleaned up descriptions, updated the quoted header info, and clarified content in several related docs.

As far as I know, there's no reason you can't put delay load calls into a static library. You must still apply the delay load linker options to the application you build that calls the static library. Those options don't make sense when applied to a static library by itself - it's not an executable.
