### ISSUE TITLE
Direct Initialization vs Brace Initialization

### ISSUE THREAD

**Issue by bfamzz** [MicrosoftDocs/cpp-docs#2712]
The code presented in the section [Handling Exceptions](https://docs.microsoft.com/en-us/cpp/cpp/examples-of-lambda-expressions?view=msvc-160#ehLambdaExpressions) uses direct initialization instead of brace initialization. See screenshot below.

![image](https://user-images.githubusercontent.com/38426051/105166477-c60c4380-5b17-11eb-9e75-00ad0673baec.png)

`vector<int> indices(3)` will result in `[0, 0, 0]` making `indices[1]` valid.

`vector<int> indices{3}` will result in `[3]` making `indices[1]` invalid.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6232c6e0-d7c5-70d4-9b9d-623d25ced117
* Version Independent ID: bfc01a2a-12a3-5d14-a37d-d42c95deb27c
* Content: [Examples of Lambda Expressions](https://docs.microsoft.com/en-us/cpp/cpp/examples-of-lambda-expressions?view=msvc-160)
* Content Source: [docs/cpp/examples-of-lambda-expressions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/examples-of-lambda-expressions.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
I think the real typo is that it should have been indices[-1]=1; to throw the exception. I've fixed the topic which will be live Monday afternoon.
