### ISSUE TITLE
strncat page

### ISSUE THREAD

**Issue by evartanian** [MicrosoftDocs/cpp-docs#2713]
[Enter feedback here]
"The all cases, the resulting" needs to be fixed.  It doesn't make sense.  I think it should be "In all cases, the resulting..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae16ffa1-749c-854f-44c4-1501e92e2f6f
* Version Independent ID: 40317ea8-6eb3-0686-846b-2e975b806be9
* Content: [strncat, _strncat_l, wcsncat, _wcsncat_l, _mbsncat, _mbsncat_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncat-strncat-l-wcsncat-wcsncat-l-mbsncat-mbsncat-l?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/strncat-strncat-l-wcsncat-wcsncat-l-mbsncat-mbsncat-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strncat-strncat-l-wcsncat-wcsncat-l-mbsncat-mbsncat-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks, @evartanian. I've fixed the typo and it should be live tomorrow (1/21/2021)
Hey, thank you for taking the time to point that out so we can fix these things that detract from the docs.
