### ISSUE TITLE
How to build CMake project from command line...

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [MicrosoftDocs/cpp-docs#2714]
[Enter feedback here]

... and guarantee that CMake is invoked with the same arguments as-if the build was invoked from the IDE?

For example, I have created in the IDE a custom configuration following [https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-160], and I can see it is saved to the corresponding CMakeSettings.json file.

But now, how do I invoke that custom build from the command line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dmenendez-gruposantander 
That's a good question that we ought to have an answer for. Lots of people do development builds in Visual Studio but use the command line for production. Let me see if @esweet431 has any input.

**Comment by dmenendez-gruposantander** [comment]
I see that the latest version of CMake has a feature called *presets* https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#manual:cmake-presets(7) which seem similar in spirit to the Visual Studio CMakeSettings.json file.

It might make sense to add support for the CMake CMakePresets.json file in the IDE, and then the support for building using those settings comes from CMake itself.

**Comment by corob-msft** [comment]
@dmenendez-gruposantander 
Your new suggestion is precisely what the Visual Studio **Help** > **Send Feedback** > **Suggest a Feature** menu command is for. Or you can send ideas by using the [Developer Community](https://aka.ms/feedback/suggest?space=62) site directly. Making your suggestion to the documentation team is slightly more effective than telling your next door neighbor, but not as effective as telling the product team directly.

**Comment by dmenendez-gruposantander** [comment]
Well my neighbor didn't know about this Send Feedback thingy ;P so, thanks for the info!
