### ISSUE TITLE
`_IOB_ENTRIES` doesn't take Universal CRT changes into account

### ISSUE THREAD

**Issue by andrew-boyarshin** [MicrosoftDocs/cpp-docs#2719]
`_IOB_ENTRIES` is now `3` instead of `20`, since the introduction Universal CRT back in 2015. Both values should be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a251893e-fa73-d4f8-a376-22f788b09b92
* Version Independent ID: 155a280f-2ceb-85d4-8b23-c56c3f60b0fe
* Content: [_iob](https://docs.microsoft.com/en-us/cpp/c-runtime-library/iob?view=msvc-160&source=docs)
* Content Source: [docs/c-runtime-library/iob.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/iob.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This is fixed. The topic will be live tomorrow afternoon (7/11)
