### ISSUE TITLE
Wrong description of when the custom build is triggered

### ISSUE THREAD

**Issue by air2** [MicrosoftDocs/cpp-docs#272]
The following section looks incorrect, It states that " If the output file is newer than the input file " the build is started, I think it should be older instead of newer:

"In Outputs, specify the name of the output file. This is a required entry; without a value for this property, the custom build tool will not run. If a custom build tool has more than one output, separate file names with a semicolon.
The name of the output file should be the same as it is specified in the Command Line property. The project build system will look for the file and check its date. If the output file is newer than the input file or if the output file is not found, the custom build tool is run. If all of the Additional Dependencies files are older than the input file, and the input file is older than the file specified in the Outputs property, the custom build tool is not run."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d13cdf42-2636-a7df-d4f2-f47a0eebd413
* Version Independent ID: e2d96246-be14-771f-5dcb-1277e09909ca
* Content: [Specifying Custom Build Tools](https://docs.microsoft.com/en-us/cpp/ide/specifying-custom-build-tools?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCCustomBuildTool.Command)%26rd%3Dtrue)
* Content Source: [docs/ide/specifying-custom-build-tools.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/specifying-custom-build-tools.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for pointing this out. I think "input" and "output" may have been swapped in this sentence, but it was also easy to just swap "newer" to "older."
