### ISSUE TITLE
Information Outdated

### ISSUE THREAD

**Issue by Naryoril** [MicrosoftDocs/cpp-docs#2726]
According to [this article](https://devblogs.microsoft.com/cppblog/typelib-and-activex-now-supported-in-mfc-wizards/#comments) the wizard has been added again with Visual Studio 16.8, albeit at a different location, it's part of the "Add New Item" now instead of the Class Wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4eb019-2eb2-4eae-1642-92de76e13229
* Version Independent ID: 75c0a6b2-41c1-d9b5-5b00-d4a5a6639367
* Content: [Add Class from Typelib Wizard](https://docs.microsoft.com/en-us/cpp/mfc/reference/add-class-from-typelib-wizard?view=msvc-160)
* Content Source: [docs/mfc/reference/add-class-from-typelib-wizard.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/add-class-from-typelib-wizard.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@rachana-satao , could you see how this ties into the MFC work you are doing.

**Comment by rachana-satao** [comment]
@TylerMSFT ,working on this - https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1887171
