### ISSUE TITLE
Consider renaming the 'other' function

### ISSUE THREAD

**Issue by howlinweed** [MicrosoftDocs/cpp-docs#273]
Using the name `other` for the additional function in the above example creates ambiguous statements, e.g. `This a is visible only within the other function`. The comment could be interpreted as referring to the other named function (`main`), or to the function named other (`other`).  

Additionally, since the comment discussing the first `a` variable refers to the `main` function simply as `main` rather than `the main function`. The inconsistent descriptions add further to the confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3cfde1-0cf0-dd81-5820-86affa13e152
* Version Independent ID: a86d0b25-78ad-5617-ed75-6c260536289d
* Content: [extern Storage-Class Specifier](https://docs.microsoft.com/en-us/cpp/c-language/extern-storage-class-specifier)
* Content Source: [docs/c-language/extern-storage-class-specifier.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/extern-storage-class-specifier.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by howlinweed** [comment]
This appears to be a duplicate of #255.

**Comment by mikeblome** [comment]
thanks @howlinweed ! Yes it's the same issue. We'll be publishing an updated and improved version of this and related content very soon.

**Comment by mikeblome** [comment]
@howlinweed Page has been updated and hopefully improved per your suggestions. Should be live by 07/11.
