### ISSUE TITLE
Forwarders to ordinal functions

### ISSUE THREAD

**Issue by czMaxx** [MicrosoftDocs/cpp-docs#2730]
The documentation says that there are two ways to forward an export. First is by the name of function:

foo = other_library.bar

where 'foo' symbol does not have to be defined and the forwarder is included in the export table as is.

Second way is to reference the function by its ordinal number, which means:

foo = other_library.#1

This declaration REQUIRES foo symbol to be defined (even when I specify NONAME), which is weird, inconsistent and quite annoying. Otherwise, the linker reports an unresolved external. If you want to make a workaround for this bug, you have to define dummy symbols for each ordinal forwarder. Link.exe obviously fails to properly parse the ordinal form of export forwarder. Either fix link.exe or fix this documentation.

**Comment by corob-msft** [comment]
@czMaxx 
Sorry it's giving you grief. I'm pretty sure that the thirty-odd years the linker has been supporting imports by ordinals means it's not going to change anytime soon. Just so I'm clear, is there a particular page or pages you'd like to see updated?

**Comment by czMaxx** [comment]
Thanks for a prompt response ;-)
I know that the described scenario is not the most frequented in developer's life, but it meant few hours of experimenting, searching etc. (I could find several reports of the same issue, but no solution). I find it very inconvenient and irrational to require a "placeholder" symbol for the ordinal forwarder.

If you use this statement in your .def file:

foo = other_library.bar @1 NONAME

linker simply pastes the named forwarder to the export table and does not bother with foo, which is omitted. That's an expected behavior.

But if you use this statement in your .def file:

foo = other_library.#1 @1 NONAME

linker emits an error message that external symbol 'foo' cannot be found, which is kinda unexpected. In the basic principle, it's just a forwarder like the example above. If you want to suppress the error, you have to define foo somewhere, no matter what type it is, it only must be present in the symbol table.

This weird behavior gave me a hard time to compile my "proxy" dll with ordinal forwarders. The documentation of EXPORTS statement https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=msvc-160 says that you can use both ways - named forwarders and ordinal forwarders. There's no piece of information about this consequence, that you have to define the dummy symbol if you forward by ordinal.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
