### ISSUE TITLE
Incorrect info for enabling C++ core guidelines check using command line

### ISSUE THREAD

**Issue by Predelnik** [MicrosoftDocs/cpp-docs#2740]
Seems like `/analyze:pluginEspXEngine.dll` is a correct way but with split words like mentioned in docs `/analyze:plugin EspXEngine.dll` it ends up with 
```
Unable to load plug-in ' EspXEngine.dll'
```
Please fix!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725a4cd3-5880-a22b-c148-c594231a3ff3
* Version Independent ID: 295baf60-5b4e-162f-bc23-0675213477fc
* Content: [Using the C++ Core Guidelines checkers](https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=msvc-160)
* Content Source: [docs/code-quality/using-the-cpp-core-guidelines-checkers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/using-the-cpp-core-guidelines-checkers.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Predelnik 
This behavior is unexpected. The compiler should have no problem with a space between the **`/analyze:plugin`** option and the filename. There also shouldn't be a leading space in the filename in the reported error. That tells me that there may be a problem in your command line or compiler configuration.

@hwisungi Do you have any insight into this problem?

**Comment by corob-msft** [comment]
@Predelnik 
After some experimentation, I don't think there's an issue with the documentation, so I'm closing it. Your question is more likely to get a useful answer in the C++ forum in [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or in the Visual Studio C++ Developer Community](https://aka.ms/vsfeedback/browsecpp) site. Best of luck in solving your issue.

**Comment by versat** [comment]
I can confirm this behavior when using a CMake project (with Conan) with a CMakeSettings.json file where I added this configuration:
```json
  {
    "name": "Release_CodeAnalysis",
    "generator": "Visual Studio 17 2022 Win64",
    "configurationType": "Release",
    "buildRoot": "${projectDir}\\Build\\Windows_x64\\Release",
    "installRoot": "${projectDir}\\Build\\Windows_x64\\Release\\package",
    "cmakeCommandArgs": "",
    "buildCommandArgs": "-m",
    "ctestCommandArgs": "",
    "cmakeExecutable": "",
    "enableMicrosoftCodeAnalysis": true,
    "enableClangTidyCodeAnalysis": true,
    "clangTidyChecks": "clang-analyzer-*,bugprone-*,cert-*",
    "variables": [
      {
        "name": "IS_VISUAL_STUDIO",
        "value": "ON",
        "type": "BOOL"
      },
      {
        "name": "CMAKE_CXX_FLAGS_RELEASE",
        "value": "/Y- /analyze /analyze:WX- /analyze:plugin EspXEngine.dll",
        "type": "STRING"
      }
    ],
    "inheritEnvironments": [ "msvc_x64_x64" ]
  }
```
After removing the space as observed and reported by @Predelnik it works :)
