### ISSUE TITLE
Documentation for Creating a Bitmap in the Resouce Editor

### ISSUE THREAD

**Issue by patchell** [MicrosoftDocs/cpp-docs#2748]
The Documentation for Creating a new bitmap seems to be very limited in the scope of how to do it.  In the actual program, for instance, you get a properties pane that allows you to set the dimensions of the bitmap, color depth and "FILE NAME", but not the ID.  In order to edit the ID, it seems that you need to right click on the default ID in the resource view and ask for the properties.  This view also has a place to put a "FILE NAME", but NOWHERE in any of the docs I have found does it tell you exactly how one do and what order to do them should be done.  It seems to me that the software is silly enough, but somewhere there should be an explanation of how to proceed.  Trial and error, so far, does not seem to work, please make the explanation for this more complete and clear.

## Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0519e8-2b31-042a-50df-3308215a1565
* Version Independent ID: 4b7c345b-d454-4894-fc61-b83d225a018e
* Content: [How To: Create an Icon or Other Image](https://docs.microsoft.com/en-us/cpp/windows/creating-an-icon-or-other-image-image-editor-for-icons?view=msvc-160)
* Content Source: [docs/windows/creating-an-icon-or-other-image-image-editor-for-icons.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/creating-an-icon-or-other-image-image-editor-for-icons.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
