### ISSUE TITLE
example of CSimpleStringT::Truncate is misleading

### ISSUE THREAD

**Issue by chund** [MicrosoftDocs/cpp-docs#2749]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/atl-mfc-shared/reference/csimplestringt-class.md#truncate

it should better be:

CSimpleString str(_T("abcdefghi"));
_tprintf_s(_T("String length: %d / Allocated length: %d\n"), str.GetLength(), str.GetAllocLength());
_tprintf_s(_T("Contents: %s\n"), (LPCTSTR)str);
str.Truncate(4);
_tprintf_s(_T("String length: %d / Allocated length: %d\n"), str.GetLength(), , str.GetAllocLength());
_tprintf_s(_T("Contents: %s\n"), (LPCTSTR)str);

**Comment by TylerMSFT** [comment]
I happened to be in this file today, and incorporated your suggestion. It'll be live by Monday afternoon.
