### ISSUE TITLE
freopen_s, _wfreopen_s syntax summary incorrect

### ISSUE THREAD

**Issue by ZimFromIRK** [MicrosoftDocs/cpp-docs#2752]
The syntax summary box for `freopen_s, _wfreopen_s` uses `freopen` as the function name.  There are also references to the non-existent `_freopen_s` on the page that should just be `freopen_s`.

Sorry for submitting this twice - noticed the additional errors but couldn't find the original submission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cec881c-3ef8-59f5-8eaa-438c6b46f926
* Version Independent ID: a129cd43-8656-6d72-7c1a-665ec60c5f57
* Content: [freopen_s, _wfreopen_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/freopen-s-wfreopen-s?view=msvc-160#feedback)
* Content Source: [docs/c-runtime-library/reference/freopen-s-wfreopen-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/freopen-s-wfreopen-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@ZimFromIRK , thank you for pointing this out. I've fixed it and it should be live in a day or two.
Thank you for helping us improve the docs.

**Comment by TylerMSFT** [comment]
@ZimFromIRK , just FYI that we are having some issues with our publishing pipeline. I hope that the fix will be out sometime next week.
