### ISSUE TITLE
Missing modifier `x`?

### ISSUE THREAD

**Issue by WillerZ** [MicrosoftDocs/cpp-docs#2759]
Table containing "mode modifier"s doesn't mention modifier `x`. Is this modifier only available on the non-secure APIs? If so I would value some discussion of what to do instead while using secure APIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a2e737-afe6-a70d-8eb3-fe3a0aeda3e8
* Version Independent ID: 3a9bdb00-1d09-1b08-3dc3-029a6a0b16a2
* Content: [fopen_s, _wfopen_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/fopen-s-wfopen-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fopen-s-wfopen-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@WillerZ 
Did you try it? I haven't, but I expect it's supported, just not documented. We'll take a look.

**Comment by TylerMSFT** [comment]
@WillerZ - "x" is supported. I've updated the documentation. It's also supported for freopen(), _wfreopen(), freopen_s() and _wfreopen_s() so I also updated those pages.
This should be live by the end of the week.

**Comment by WillerZ** [comment]
Thanks!

**Comment by TylerMSFT** [comment]
@WillerZ , just FYI that we are having some issues with our publishing pipeline. I hope that the fix will be out sometime next week.
