### ISSUE TITLE
Concurrency Runtime pages give header file and namespace but not .LIB file to use

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#276]
UPDATE: Typo in subject – should be "... but NOT .LIB file to use". Sorry. Can't seem to edit the subject.

The pages in this section give the header file and the C++ namespace to use when building an application that uses the classes and functions in the Concurrency Runtime, but none of them give the name of the import libraries (.LIB files) to give to the linker. I assume some of these APIs are implemented in libconcrt.lib, libconcrt1.lib, libconcrtd.lib, libconrtd1.lib, etc. Shouldn't the import libraries (and also the static libraries – if available) also be listed? Otherwise, how will customers know how to configure their linker settings in a project that uses the Concurrency Runtime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b872d063-c672-03ce-b33a-543b5d00e201
* Version Independent ID: f2e3aa7e-fdff-81d9-8ebd-cb3050e7bca5
* Content: [Reference (Concurrency Runtime)](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/reference-concurrency-runtime)
* Content Source: [docs/parallel/concrt/reference/reference-concurrency-runtime.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/reference-concurrency-runtime.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Investigating.

**Comment by mikeblome** [comment]
@fpl9000 I'm still waiting for an answer. In the meantime, I'm curious--Have you actually seen a linker error trying to use ConcRT? If so, was it in an MSBuild (.vcxproj)  project?

**Comment by fpl9000** [comment]
No, I haven't seen a linker error. I just thought the API docs should give
the header and library file names for each API. Perhaps the VS project
wizard puts the appropriate .LIB file in the settings, but some users still
use makefiles or batch scripts to do builds. They would benefit from
knowing the name of the .LIB file for each API.
--
Fran

**Comment by mikeblome** [comment]
@fpl9000 Agreed. I have added this item to our backlog and it will prioritized along with other work items. Thanks for the input!
