### ISSUE TITLE
Improve & update intrinsics documentation

### ISSUE THREAD

**Issue by h-vetinari** [MicrosoftDocs/cpp-docs#2777]
Trying to navigate the docs for intrinsics can be difficult, _especially_ for trying to write portable intrinsics code. Here are a list of suggested improvements:

* [ ] Make relation between `/arch:AVX2` and FMA more explicit; it is mentioned only in passing [here](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-160).
* [ ] Mention conditions / implications for emitting F16C / POPCNT instructions. @walbourn clarified [here](https://stackoverflow.com/questions/50827769/how-is-the-arch-parameter-used-when-compiling-code-with-visual-studio/50829580#comment117002684_50829580) that F16C has no direct relation to `/arch:AVX2` (while  the only previous [reference](https://walbourn.github.io/directxmath-avx2/) I found - also by him - seemed to imply that)
* [ ] Specify SSE-support detection on 64-bit targets. This [page](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160) explains that just for  `_M_IX86_FP`, which is however only applicable to 32bit targets
* [ ] Update intrinsics [support page](https://docs.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list?view=msvc-160). The page wrongly claims `[2]` (=supported only on Intel processors) for everything upwards of (and including) `AVX`.
* [ ] Mention lack of operator overloads (`+`, `-`, `*`, `/` etc.) for `__m128` / `__m256`. 

Background: trying to get an existing unix-y library using intrinsics (e.g. `__SSEx__`, `__FMA__`, `__F16C__`, `-mpopcnt`, etc.) is [painful](https://github.com/facebookresearch/faiss/pull/1680).

**Comment by corob-msft** [comment]
@h-vetinari 
I appreciate that you've had some difficulty finding the information you need. You've got a large list of suggestions and improvements here, in content that is little visited, and hence a low priority for us. Only two people work on the C/C++ and Assembler docs, and we're pretty busy just keeping up with the regular changes in the tools and libraries. Frankly, the fastest way to see the changes you want in this content is to make them yourself. Fortunately, it's not terribly difficult to [edit the markdown sources and make a pull request](https://docs.microsoft.com/en-us/contribute/). We're delighted to review and edit such contributions. And thanks for your suggestions on improving the content.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
