### ISSUE TITLE
question about step 3

### ISSUE THREAD

**Issue by tarbear123** [MicrosoftDocs/cpp-docs#2778]
what does it mean when it says "Modify the portfile for the library to obtain the version you need"?

**Comment by corob-msft** [comment]
@tarbear123 
There's a *`portfile.cmake`* file for each library, which contains the instructions to download and build. That's where you'd make the edits to update the version. You'll find the portfile in a subdirectory named for the library, under the *`ports`* directory in your vcpkg clone. Some examples of creating a portfile exist under the **Examples** section of the [vcpkg repo docs](https://github.com/microsoft/vcpkg/blob/master/docs/index.md). Docs for the helper functions used can be found in [Portfile helper functions](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/portfile-functions.md). That's about the best documentation we have for portfiles right now.

**Comment by tarbear123** [comment]
> @tarbear123
> There's a _`portfile.cmake`_ file for each library, which contains the instructions to download and build. That's where you'd make the edits to update the version. You'll find the portfile in a subdirectory named for the library, under the _`ports`_ directory in your vcpkg clone. Some examples of creating a portfile exist under the **Examples** section of the [vcpkg repo docs](https://github.com/microsoft/vcpkg/blob/master/docs/index.md). Docs for the helper functions used can be found in [Portfile helper functions](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/portfile-functions.md). That's about the best documentation we have for portfiles right now.

i try and do this command cmake .. -DCMAKE_TOOLCHAIN_FILE=vcpkg\scripts\buildsystems\vcpkg.cmake but I keep getting 'cmake' is not recognized as an internal or external command,
operable program or batch file.

**Comment by corob-msft** [comment]
@tarbear123 
I'm sorry, we don't usually do product support through the documentation issues board. Your question is the sort of thing that [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) is designed for. I recommend giving that a try.
