### ISSUE TITLE
Please explain or reference how to rebuild precompiled headers.

### ISSUE THREAD

**Issue by MrScottAtt** [MicrosoftDocs/cpp-docs#2779]
The page assumes that the reader already knows how to rebuild precompiled headers.  Adding an explanation or reference to documentation on how to rebuild precompiled headers would improve the usability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec3cbf7f-4df3-76a3-bb9e-57c80e782701
* Version Independent ID: 898ea55c-a052-8555-1c81-829ecfd25b9b
* Content: [Compiler Error C2855](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2855?view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2855.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c2855.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MrScottAtt 
That seems like a reasonable suggestion. The precompiled header gets regenerated when you build the source file that has the **`/Yc`** compiler option applied to it. In projects created by Visual Studio, it's usually a source file named *`pch.cpp`* or *`stdafx.cpp`*.

**Comment by corob-msft** [comment]
Updated docs should appear sometime tomorrow.
