### ISSUE TITLE
Incorrect step

### ISSUE THREAD

**Issue by DaManDOH** [MicrosoftDocs/cpp-docs#278]
Step 1 under "To add an object to an ATL project" section should mention the Solutions Explorer, not the Class View. The New contextual menu option for the Polygon object in Class View only includes a new Class option and a new Resource option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d8323-d824-40eb-4954-2620d86a44b6
* Version Independent ID: a090fbda-31ee-a2d1-6f9c-9e495b4b4e08
* Content: [Adding a Control (ATL Tutorial, Part 2)](https://docs.microsoft.com/en-us/cpp/atl/adding-a-control-atl-tutorial-part-2)
* Content Source: [docs/atl/adding-a-control-atl-tutorial-part-2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/adding-a-control-atl-tutorial-part-2.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@DaManDOH thanks! Fixed and should appear on 6-19 or 6-20.
