### ISSUE TITLE
The description of the .rc file is incorrect and confusing

### ISSUE THREAD

**Issue by ScottHutchinson** [MicrosoftDocs/cpp-docs#279]
This statement about the .rc cannot be correct: "This file is overwritten by the .aps file whenever you save."
The script file, which is a text file, is not overwritten by a binary file. It would be very nice to have a better, more detailed description of how Viusal Studio uses all these files, along with a recommendation of which files should be included in Source Control and which should not.

I found some more detailed description, which could be incorporated into this page: https://social.msdn.microsoft.com/Forums/vstudio/en-US/acda5b17-b06a-4c20-8bdb-f4955c76358e/regarding-apssdf-files-in-vs2010?forum=vcgeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf9b07-0cfc-1f77-28cb-0c2cda7ed3e3
* Version Independent ID: edaf4af6-aaa2-0e5b-f3f4-ca1c065822a4
* Content: [Files Affected by Resource Editing](https://docs.microsoft.com/en-us/cpp/windows/files-affected-by-resource-editing)
* Content Source: [docs/windows/files-affected-by-resource-editing.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/files-affected-by-resource-editing.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@ScottHutchinson thanks for taking the time to report this! It looks like the current version of the topic already has info from that link you suggested. I added notes about which files to include in source control. Should be live by end of day on 6-19. Let me know if you are still seeing errors on that page.
