### ISSUE TITLE
Wrong picture?

### ISSUE THREAD

**Issue by duanqn** [MicrosoftDocs/cpp-docs#283]
The last picture which appears before 'Congratulations!' seems irrelevant to the text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Thanks for spotting this issue. Yes, that's the wrong picture. I thought I fixed that months ago, but apparently not. I'll add that to my list of things to fix.

**Comment by corob-msft** [comment]
Looks like the fix is live.

**Comment by Kafonin** [comment]
Copy pasted the working version of the code (at the bottom) and got an error.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	windowsDesktopProject	C:\Users\kafon\source\repos\windowsDesktopProject\MSVCRTD.lib(exe_main.obj)	1`	
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	windowsDesktopProject	C:\Users\kafon\source\repos\windowsDesktopProject\Debug\windowsDesktopProject.exe	1`
