### ISSUE TITLE
Semicolon does not separate the error or warning message from the additional line.

### ISSUE THREAD

**Issue by Puzomor** [MicrosoftDocs/cpp-docs#284]
Actual results on the compiler output when adding /WL switch do not include semicolon as a separator.
The lines are simply merged without any separator what so ever.
Tested on `cl.exe` Version 19.12.25835 for x64.
Example (also on that same version)
https://godbolt.org/g/ZqsXtU

Not sure if this is a compiler bug or documentation error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879c13df-8371-cf4b-f263-10d3cf046cfc
* Version Independent ID: 9d63cb48-d5f3-dc7e-81de-68925b10c2e6
* Content: [-WL (Enable One-Line Diagnostics)](https://docs.microsoft.com/en-us/cpp/build/reference/wl-enable-one-line-diagnostics)
* Content Source: [docs/build/reference/wl-enable-one-line-diagnostics.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/wl-enable-one-line-diagnostics.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for taking the time to report this. I think this is a product issue. I couldn't get the error to concatenate as described (with a semicolon) in VS2015, either. I don't have VS2013 on my machine, and VS2012 didn't report the extra info for that particular example. So I created a different sample, wl.cpp, that I was pretty sure would output an extra line at /W4:

```cpp
int main() {  
   int i = 42;
   {
      for (int i = 0; i < 10; i++) {}
      i = 36;
   }
} 
```

I compiled this in VS2017 with `cl /nologo /c /W4 wl.cpp`:

```Output
wl.cpp
wl.cpp(4): warning C4456: declaration of 'i' hides previous local declaration
wl.cpp(2): note: see declaration of 'i'
```

Then I added the /W4 flag: `cl /nologo /c /W4 /WL wl.cpp`:

```Output
wl.cpp
wl.cpp(4): warning C4456: declaration of 'i' hides previous local declarationwl.cpp(2): note: see declaration of 'i'
```

Ugly concatenation there. VS2015 behaved the same. However, VS2012 was interesting. It gave a different error for the first command line:

```Output
wl.cpp
wl.cpp(5) : warning C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        wl.cpp(4) : definition of 'i' ignored
        wl.cpp(2) : definition of 'i' used
```

And when run with /WL:

```Output
wl.cpp
wl.cpp(5) : warning C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used; wl.cpp(4) : definition of 'i' ignored; wl.cpp(2) : definition of 'i' used
```

Note the semicolons. Clearly the docs were correct for VS2012, but at some point before VS2015, the behavior changed..

So I'm guessing the thing to do is report this on the [Developer Community site for C++ questions](https://developercommunity.visualstudio.com/spaces/62/index.html), and see what the developers say. Do you want the honors?

**Comment by Puzomor** [comment]
Sure, thanks for feedback!
