### ISSUE TITLE
Code example for cpp Member Access overloading

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/cpp-docs#285]
I think we need to add a sample code that is not clear how to write.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172b35cb-118b-0887-a47f-1c3d33d43309
* Version Independent ID: 68a8a8aa-12d5-cb04-f935-77ed05559c0c
* Content: [Member Access](https://docs.microsoft.com/en-us/cpp/cpp/member-access)
* Content Source: [docs/cpp/member-access.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/member-access.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by baruchiro** [comment]
I think I have a code sample, what should I do?

**Comment by corob-msft** [comment]
We welcome code contributions! You can submit a PR if you have something in mind. We'll review it and suggest edits, or make them directly. 

If you've read the [Contributor guide](https://github.com/MicrosoftDocs/cpp-docs/blob/master/CONTRIBUTING.md), our [Voice and tone guidelines](https://github.com/MicrosoftDocs/cpp-docs/blob/master/styleguide/voice-tone.md) and the [Metadata and Markdown template](https://github.com/MicrosoftDocs/cpp-docs/blob/master/styleguide/template.md) guide, especially the [Code](https://github.com/MicrosoftDocs/cpp-docs/blob/master/styleguide/template.md#code) section, then you have most of the information you need on how our documentation works. 

Look at similar topics to see how code examples are formatted and explained. For example, you would probably create an **Example** H2 header between the **Remarks** section and the **See also** section. Then include a short introduction, "This sample shows how to ..." followed by a code block with the example code. The best examples show the simplest possible complete working console app that demonstrates the concept. Include a comment at the top that specifies the command line to use to build it.

**Comment by baruchiro** [comment]
PR #297

**Comment by mikeblome** [comment]
@baruchiro  Closing this issue. See my comment in the PR. Thanks!
