### ISSUE TITLE
How To page indicates WRL::Make cannot fail when it will return nullptr during any construction error

### ISSUE THREAD

**Issue by zjmoney** [MicrosoftDocs/cpp-docs#2875]
The page indicates that that a component created using WRL::Make cannot fail and will be usable in all cases. However, WRL::Make can fail and silently return a nullptr (such as in low memory conditions). The "How to" page should be updated to address this possibility.

Please contact zaneh@microsoft.com if more details are needed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebdfb763-569a-8e71-4430-5544760c0ce7
* Version Independent ID: 5d0d4ef6-4b59-100e-f6ce-edf13fe596a0
* Content: [How to: Instantiate WRL Components Directly](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/how-to-instantiate-wrl-components-directly?view=msvc-160)
* Content Source: [docs/cppcx/wrl/how-to-instantiate-wrl-components-directly.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/how-to-instantiate-wrl-components-directly.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@zjmoney 
Thanks for the feedback. I'd say there's a small distinction, in that there's guaranteed to be a `ComPtr<T>` object returned by `Make`, but its internal `_ptr` member can in fact be `nullptr`. You do have to check the result, perhaps using something like `Get`, before dereferencing it.

This is very low traffic content, and we're unlikely to address your feedback anytime soon. If you (or anyone else) would like to [edit the content and propose a pull request](https://docs.microsoft.com/en-us/contribute/), that's the fastest way this will get updated. Thanks for helping out.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
