### ISSUE TITLE
Null character data documentation note is wrong

### ISSUE THREAD

**Issue by gregg-miskelly** [MicrosoftDocs/cpp-docs#288]
The documentation says:

A CString object keeps character data in a CStringData object. CString accepts null-terminated C-style strings, **but does not retain the null character in the stored character data**. Instead, CString tracks string length. CString does provide a null terminator when it exports a C-style string. You can insert a null in a CString, but it may produce unexpected results.

The bolded part of that sentence is incorrect. Yes, CString does keep track of the length for fast access. But it also stores all strings as null terminated. It needs to since it supports conversion to LPCWSTR.

Here is the code that explicitly allocates the extra one character worth of space, and explicitly null terminates the new string after copy (note the use of `AtlAdd(..., 1)` and `m_pszData[nLength] = 0;`).

```
                virtual _Ret_maybenull_ _Post_writable_byte_size_(sizeof(CStringData) + nChars*nCharSize) CStringData* Allocate(
                                _In_ int nChars,
                                _In_ int nCharSize) throw()
                {
                                ATLENSURE_RETURN_VAL( nChars&gt;=0, NULL );

                                size_t nTotalSize;
                                CStringData* pData;
                                size_t nDataBytes;

                                if( FAILED(::ATL::AtlAdd(&nChars, nChars, 1)) )
                                {
                                                return NULL;
                                }

                                int nAlignedChars = ::ATL::AtlAlignUp( nChars, 8 );  // Prevent excessive reallocation.  The heap will usually round up anyway.
                                ATLENSURE_RETURN_VAL( nChars&lt;=nAlignedChars, NULL );

                                if(            FAILED(::ATL::AtlMultiply(&nDataBytes, static_cast&lt;size_t&gt;(nAlignedChars), static_cast&lt;size_t&gt;(nCharSize))) ||
                                                FAILED(::ATL::AtlAdd(&nTotalSize, static_cast&lt;size_t&gt;(sizeof( CStringData )), nDataBytes)))
                                {
                                                return NULL;
                                }
                                pData = static_cast&lt; CStringData* &gt;( m_pMemMgr-&gt;Allocate( nTotalSize ) );
                                if( pData == NULL )
                                {
                                                return( NULL );
                                }
...

                void SetLength(_In_ int nLength)
                {
                                ATLASSERT( nLength &gt;= 0 );
                                ATLASSERT( nLength &lt;= GetData()-&gt;nAllocLength );

                                if( nLength &lt; 0 || nLength &gt; GetData()-&gt;nAllocLength)
                                                AtlThrow(E_INVALIDARG);

                                GetData()-&gt;nDataLength = nLength;
                                m_pszData[nLength] = 0;
                }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b95afb3-52a8-384a-0f56-0ca891273f49
* Version Independent ID: 028dbc17-1b01-d64d-3f90-598e85a5bc2b
* Content: [Using CString](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/using-cstring)
* Content Source: [docs/atl-mfc-shared/using-cstring.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/using-cstring.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
thanks @gregg-miskelly . Fixed and should be live by 6-19 EOD.
