### ISSUE TITLE
bad sample for CString

### ISSUE THREAD

**Issue by ingconti** [MicrosoftDocs/cpp-docs#289]
you wrote:

CStringW str1;
CStringW str2;
str1.Format(L"%s", static_cast&lt;LPCWSTR&gt;(str2));

but in this way You throw away all the beauty of CString portability for multibyte/unicode:

do in THIS way:

	CString str1;
	CString str2 = _T("hello!");
	str1.Format(_T("%s"), static_cast&lt;LPCTSTR&gt;(str2));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52d20ec-2725-57ac-55ad-6584017059ff
* Version Independent ID: 38807675-ee62-3472-653b-d2d5d2433d45
* Content: [C++ conformance improvements](https://docs.microsoft.com/en-us/cpp/cpp-conformance-improvements-2017)
* Content Source: [docs/cpp-conformance-improvements-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp-conformance-improvements-2017.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@ingconti Suggestion accepted! will appear by 6-19. Thanks.
