### ISSUE TITLE
fgets sample code description could be more precise

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/cpp-docs#290]
All but the most trivial function man pages should have examples, and this one is outstanding. The only suggestion I have is to consider replacing "This program uses fgets to display a line from a file on the screen." with "This program uses fgets to display the first line from a file on the screen." As it is, studying the output caused me to scratch my head, then re-read the code. The second reading eventually made clear that it reads only the first line from the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324d5dda-c5c9-d08d-e4a6-6ede943ee807
* Version Independent ID: 54a8cbf0-2e0e-6e97-5f84-c5bd70cc2f51
* Content: [fgets, fgetws](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fgets-fgetws#parameters)
* Content Source: [docs/c-runtime-library/reference/fgets-fgetws.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fgets-fgetws.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for commenting and the kudos. It's easy to make a PR for a change like this if you're so inclined. I suppose "a line from a file" could imply any line, not just the first, though to me the description seems reasonable.

**Comment by mikeblome** [comment]
fixed.
