### ISSUE TITLE
The use of double underscore described is misleading

### ISSUE THREAD

**Issue by KillzoneKid** [MicrosoftDocs/cpp-docs#291]
The standard specifies that any use of double underscore in identifier is reserved, while this page suggests that it is only when double underscore is at the beginning. What is more this suggestion comes after "END Microsoft Specific", which clearly should be included into "Microsoft Specific" as it is not the standard. Quote from the standard: "Each name that contains a double underscore _ _ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f99764-49fd-4c28-e347-e0b36790b0e8
* Version Independent ID: 73b83fd9-4da8-d5fe-f0c1-9644c694b3c7
* Content: [Identifiers (C++)](https://docs.microsoft.com/en-us/cpp/cpp/identifiers-cpp)
* Content Source: [docs/cpp/identifiers-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/identifiers-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@KillzoneKid Doc has been updated and should be visible 07/11. Since the description is now in accordance with the standard, I have left the Microsoft Specific section unchanged. Thanks for the input!
