### ISSUE TITLE
Missing component/workload info for makefile projects

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/cpp-docs#293]
(Ported from Developer Community)

The document should have a clear statement of makefile project, it also should include the information about how to get the makefile project (e.g. The detailed workload and components)
 
Actual result:
There is no information in any of the documents about how to find makefile project template, and the instruction pages online all suggest it comes pre-installed.
 
I am trying to use VS 2017 Community to work with a cross-platform C project. Following the instructions found here on MS, it states I should do a New Project-&gt;VC++-&gt;Makefile project. However, that item does not exist on my VS. I also looked in the Online section of the templates, but there is nothing about makefiles in the VC++ or Other categories, and Searching turned up nothing as well. Is there a way to make a makefile project in Community?
 
The solution turns out to be to download the rather poorly named **VC++ for Universal Apps** package, which also downloads many other templates including the makefile one.
 
 I believe "Visual Studio Express for Windows Desktop" is the name of a product. It does not appear to be referring to the installer package.
If it is saying that, it needs to be fixed because it is very confusing!
Another problem is that Visual Studio Express no longer exists. This statement was found in the VS2017 documentation, so it is wrong. The statement should refer to Community.
Additionally, the package in question is not part of Visual Studio Express/Community so you cannot follow these instructions. That's what brought me here in the first place.
So it's three ways wrong!
All of this could be greatly improved by adding a leading statement that notes the template may not be installed in all VS installations and can be downloaded from the Online section of the New Project window. I attempted to find a link to a document that explains that process, but if one exists it is well hidden from Google.
 
View on [Developer Community](https://developercommunity.visualstudio.com/content/problem/204595/vs-2017-community-makefile-project.html)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18e6e35-06a1-33ab-f17a-a1a797dd415f
* Version Independent ID: b757e5d8-e72b-1fb5-1456-298f5bd67655
* Content: [Creating a Makefile Project](https://docs.microsoft.com/en-ca/cpp/ide/creating-a-makefile-project)
* Content Source: [docs/ide/creating-a-makefile-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/creating-a-makefile-project.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Investigating.

**Comment by mikeblome** [comment]
updated documentation to reflect that the template is installed with the C++ Desktop workload.
