### ISSUE TITLE
Add reentrancy details to `critical_section` docs

### ISSUE THREAD

**Issue by AaronMK** [MicrosoftDocs/cpp-docs#2936]
Add documentation on what happens if the current context already holds the critical section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070d4b7e-0914-15a3-e5b3-34245021427e
* Version Independent ID: eec7d4c2-be07-89d3-ca99-d88d2867baea
* Content: [critical_section Class](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/critical-section-class?view=msvc-160)
* Content Source: [docs/parallel/concrt/reference/critical-section-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/critical-section-class.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@AaronMK 
Have you tried it? Did it cause an issue?

[Edited title to clarify for later readers]

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
