### ISSUE TITLE
Add info about forward exports

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/cpp-docs#294]
This topic doesn't mention the syntax for defining forward exports. Suggested fix from Kevin Gao:

entryname[=internal_name|other_module.another_exported_name] [@ordinal [NONAME]] [[PRIVATE] | [DATA]]

entryname is the function or variable name that you want to export. This is required. If the name that you export differs from the name in the DLL, specify the export's name in the DLL by using internal_name. For example, if your DLL exports a function func1 and you want callers to use it as func2, you would specify:

EXPORTS  
   func2=func1

If the name that you export is from other module, specify the export's name in the DLL by using other_module.exported_name. For example, if your DLL exports a function other_module.func1 and you want callers to use it as func2, you would specify:

EXPORTS  
   func2=other_module.func1

Because the Visual C++ compiler uses name decoration for C++ functions, you must either use the decorated name internal_name or define the exported functions by using extern "C" in the source code. The compiler also decorates C functions that use the __stdcall calling convention with an underscore (_) prefix and a suffix composed of the at sign (@) followed by the number of bytes (in decimal) in the argument list.

[Original bug](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/529602) contains an email discussion about this if you need more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c796dd-5105-cdd2-7a4d-b4f7713d57dd
* Version Independent ID: 7698174e-3277-935a-4d3c-1c430133dbfd
* Content: [EXPORTS](https://docs.microsoft.com/en-us/cpp/build/reference/exports)
* Content Source: [docs/build/reference/exports.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/exports.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by matbech** [comment]
Please also include information about forwarders which point to ordinals.

**Comment by mikeblome** [comment]
@matbech This topic was updated. Did we answer your question?

**Comment by corob-msft** [comment]
The Old New Thing to the rescue: [How do I forward an exported function to an ordinal in another DLL?](https://blogs.msdn.microsoft.com/oldnewthing/20121116-00/?p=6073/)
