### ISSUE TITLE
atomic_compare_exchange functions: incorrect and incomplete

### ISSUE THREAD

**Issue by larvacea** [MicrosoftDocs/cpp-docs#295]
The documentation for the atomic_compare_exchange_... functions describes the return value as "indicating" the result of the computation. In fact, it is true if the values are equal and false if they are not equal. The C++ specification words this more clearly:  it describes the value comparison as an equality test, and the return value as equal to the result of that equality test.

The description of the weak flavor of atomic_compare_exchange is exactly backwards. To be precise: both the strong and weak flavors absolutely guarantee that they will not store the new value if the expected and current values are not equal. The strong flavor absolutely guarantees that it will store the new value if the expected and current values are equal. The weak flavor may sometimes return false and not store the new value even if the current and expected values are equal (that is, the function will return false, but examining the expected value afterwards will reveal that it did not change, and so should have compared as equal).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beec3676-ba42-faca-7d01-41bf5f8c7484
* Version Independent ID: 16b5df04-ed0e-def2-513c-0eb25e975e5a
* Content: [&lt;atomic&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/atomic-functions#feedback)
* Content Source: [docs/standard-library/atomic-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/atomic-functions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by larvacea** [comment]
The correctness issue is also present in the description of the methods compare_exchange_weak and compare_exchange_strong on the atomic struct.

**Comment by mikeblome** [comment]
Thanks @larvacea . The library team confirms your suggestion. I have updated the doc. Should be visible 07/12.
