### ISSUE TITLE
AfxIsValidAddress / AfxIsValidString do nothing

### ISSUE THREAD

**Issue by OfekShilon** [MicrosoftDocs/cpp-docs#296]
The code only checks for NULL. The documentation is false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb51741-60c9-fc00-3cd2-55f09698dae4
* Version Independent ID: 0ee1bf38-0cee-ca78-a6f5-101529878ff9
* Content: [Diagnostic Services](https://docs.microsoft.com/en-us/cpp/mfc/reference/diagnostic-services#afxisvalidstring)
* Content Source: [docs/mfc/reference/diagnostic-services.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/diagnostic-services.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@OfekShilon  Isn't this info in the Return Value section of each function? I.e. -- In non-debug builds, nonzero if *lpsz* is not NULL; otherwise 0.

**Comment by mikeblome** [comment]
Topic updated. The checks for valid memory space are performed by SAL annotations at compile-time.
