### ISSUE TITLE
Two Statements in the Sample Windows Desktop Application Appear to be Unnecessary

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/cpp-docs#2984]
Variable hInst is declared, and appears in an assignment statement. However, its purpose is not evident: The following two statements in which it appears can be removed without affecting the application's execution.

HINSTANCE hInst;
hInst = hInstance;

Please include an explanation of why these statements are included (or remove them if they are not needed).

  Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-160#create-the-code)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Robert-Tortorelli 
Thanks for the input. The statements are there because most Windows apps will need the instance handle as a parameter to certain Win32 API calls later, even though this simple sample app doesn't. I've added a comment to the global declaration to make this more clear.
