### ISSUE TITLE
unclear statement

### ISSUE THREAD

**Issue by accurate27** [MicrosoftDocs/cpp-docs#2985]
"Resources found in other file types such as .exe, .dll, and .res files are referred to as resources."

The sentence above is logically incorrect. You are telling me that resource is a resource. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ed6408-e037-b3ab-b7d5-da0db4b69af0
* Version Independent ID: 5ae42c1b-b357-f3f4-dbd4-b75be774ada2
* Content: [Resource Files (C++)](https://docs.microsoft.com/en-us/cpp/windows/resource-files-visual-studio?view=msvc-160#feedback)
* Content Source: [docs/windows/resource-files-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/resource-files-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updated content.
