### ISSUE TITLE
/Qpar Visual Studio instructions outdated

### ISSUE THREAD

**Issue by uncajesse** [MicrosoftDocs/cpp-docs#2986]
The instructions to enable in Visual Studio are outdated. The /Qpar option is now in Properties, C/C++, select Code Generation. In the "Enable Parallel Code Generation" property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe7ae02-1a89-2837-176c-8d5006574628
* Version Independent ID: ffe3641e-8c4f-c0b1-ad95-7b0c876a6254
* Content: [/Qpar (Auto-Parallelizer)](https://docs.microsoft.com/en-us/cpp/build/reference/qpar-auto-parallelizer?view=msvc-160)
* Content Source: [docs/build/reference/qpar-auto-parallelizer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/qpar-auto-parallelizer.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updated content.
