### ISSUE TITLE
What does /STACK do when building a DLL?

### ISSUE THREAD

**Issue by AndreVergison** [MicrosoftDocs/cpp-docs#2988]
[Enter feedback here]
About:
> The /STACK option sets the size of the stack in bytes. Use this option only when you build an .exe file.

This is very true, however developers may get confused by the Visual Studio linker ability to specify the /STACK option when building a dynamic link library (DLL). IMHO in this case that value simply won't do anything at all. It is the calling .exe which sets up the stack.

Ideally that linker field should be greyed out when building DLLs. At the least, the Stack Reserve Size hint text ("Specifies the total stack allocation size in virtual memory. Default is 1 MB." could add that field is valid is for EXEs only.

So my request is to make that a little more clear at this point of the page.

Thanks,
Andre Vergison
Product Architect, Quest Software.
andre.vergison@quest.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42d61db5-8769-a01a-b495-f4882c625a22
* Version Independent ID: 99f0363d-2c60-ce83-8ac3-ab3bbc3c3e50
* Content: [/STACK (Stack Allocations)](https://docs.microsoft.com/en-us/cpp/build/reference/stack-stack-allocations?view=msvc-160)
* Content Source: [docs/build/reference/stack-stack-allocations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/stack-stack-allocations.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AndreVergison 
I've updated the content with some extra clarification, but reading your original issue, it looks like you might be proposing an IDE change as well. That's the sort of thing you should propose to the product team, not the docs team. It's easy to do right in the IDE: Open **Help** > **Send Feedback** > **Suggest a Feature** and detail your idea. It will be posted to [Developer Community](https://aka.ms/vsfeedback/browsecpp), where people can upvote the idea. Best of luck.
