### ISSUE TITLE
Another Cause for LNK1181

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/cpp-docs#299]
I discovered that LNK1181 arises when the /P switch gets into the C/C++ compiler command line, preventing the compilation phase from producing an output file. This happened accidentally early in development, and for some reason remained enabled for my x86 Release build configuration. Once I removed the /P switch, the link step completed without errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97e9d31-d8c6-a40e-880b-88cb17d55489
* Version Independent ID: f609c72a-46c6-847d-bcff-870ea769a811
* Content: [Linker Tools Error LNK1181](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1181?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1181)%26rd%3Dtrue)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1181.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1181.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
thanks @txwizard we added a note about /P to the topic. should be visible by 08/22.
