### ISSUE TITLE
Specify default checks

### ISSUE THREAD

**Issue by WarrenMarshall** [MicrosoftDocs/cpp-docs#2990]
The "Clang-Tidy configuration" section leaves out the one question I naturally have ... if I don't specify any checks behavior, what happens by default?  Does it check everything?  Nothing?  A subset?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f9a6a82-c89c-673f-0db3-9d4e2689c956
* Version Independent ID: 93c77d1a-b248-a12e-b13f-9ab299e88066
* Content: [Using Clang-Tidy in Visual Studio](https://docs.microsoft.com/en-us/cpp/code-quality/clang-tidy?view=msvc-160)
* Content Source: [docs/code-quality/clang-tidy.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/clang-tidy.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@WarrenMarshall 
Good question. Short answer, no checks are run if you don't enable clang-tidy. It's not enabled by default. If you enable clang-tidy, it appears to run a default subset of checks if no checks are specified explicitly. 

You should be able to verify the default behavior on your own development system fairly easily. In a developer command prompt, run `clang-tidy --dump-config`. On my test machine, the `Checks:` section lists `'clang-diagnostic-*,clang-analyzer-*'`. I'm not sure that `clang-diagnostic-*` corresponds with any checks (I confess I'm no expert on clang-tidy behavior; maybe it's shorthand for the default clang diagnostics). The enabled `clang-analyzer-*` checks are listed individually if you run `clang-tidy -list-checks` in your developer command prompt.

**Comment by corob-msft** [comment]
Updated content.
