### ISSUE TITLE
Microsoft OpenMP should support omp_get_level()

### ISSUE THREAD

**Issue by imaginary-person** [MicrosoftDocs/cpp-docs#2991]
Functions such as `omp_get_level()` are very helpful because as per OpenMP specifications, `omp_in_parallel()` is supposed to return False if OpenMP is executing in a parallel region with just one thread.

`omp_get_level()` can thus make writing platform-independent code easier. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858287b0-06fa-b303-1410-06d08cfca040
* Version Independent ID: b877f886-b3de-4221-7d99-9c2354582108
* Content: [OpenMP Functions](https://docs.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-functions?view=msvc-160)
* Content Source: [docs/parallel/openmp/reference/openmp-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/openmp/reference/openmp-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @imaginary-person, I'm not clear what you are asking for here. Is it to add omp_get_level() to this page?

**Comment by imaginary-person** [comment]
@TylerMSFT

Oops, sorry! No, I was actually requesting for this function to be supported, but I see that I used the wrong medium to do so.

**Comment by TylerMSFT** [comment]
No worries. In parallel, I verified what you have concluded - we don't implement omp_get_level()
You can suggest that we add it on the Visual Studio C++ [Developer Community website](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fspaces%2F62%2Findex.html&data=02%7C01%7CTyler.Whitney%40microsoft.com%7C0cf35bbfab0346d1358c08d82e855f78%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637310497652186579&sdata=wRn3j8jzUZImHSHfSnFuj5sumyw31oozM24rKu081p8%3D&reserved=0), where other developers can see your proposal and upvote it.

**Comment by imaginary-person** [comment]
Thank you! I'll do that.
