### ISSUE TITLE
Derived from stl class

### ISSUE THREAD

**Issue by renvenuti** [MicrosoftDocs/cpp-docs#2992]
[Enter feedback here]
From Scott Meyers's Book Effective C++ Third Edition Item 7 page 43

The same analysis applies to any class lacking a virtual destructor,
including all the STL container types (e.g., vector, list, set,
tr1::unordered_map (see Item 54), etc.). If you’re ever tempted to inherit
from a standard container or any other class with a non-virtual
destructor, resist the temptation! 

Bye Renzo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c07441-073c-a4c5-a627-5fe0bf702fad
* Version Independent ID: 8854362d-1527-3ede-70b6-a801aff1f1e3
* Content: [Compiler Warning (level 1) C4251](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4251?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4251.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4251.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updated.
