### ISSUE TITLE
Conflicting Info...

### ISSUE THREAD

**Issue by DynConcepts** [MicrosoftDocs/cpp-docs#3002]
Text states you will get a load error if it is an assembly compiled with "/clr"... You do not... but there are negative effects... 

Unfortunately your examples actually use "/clr" contradicting the information in the text body.

Please update to supply PROPER and coherent (i.e. self-consistent) information regarding the impact of "#using" relative to "/clr" compiled assemblies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f576ff-ccf8-6f83-5da8-63878c6d137b
* Version Independent ID: 71e205c5-46df-c039-006e-c241d4a4d109
* Content: [#using directive (C++/CLI)](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-using-directive-cpp?view=msvc-160)
* Content Source: [docs/preprocessor/hash-using-directive-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/hash-using-directive-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DynConcepts 
Thanks for the report. Can you clarify the issue for me? The example at the bottom seems unrelated to the warning about loading an EXE compiled by using **`/clr`**. The example only loads DLL assemblies.

**Comment by TylerMSFT** [comment]
Closing - no response.
