### ISSUE TITLE
Doc on different inherit environments (CMake)

### ISSUE THREAD

**Issue by TylerMSFT** [MicrosoftDocs/cpp-docs#3004]
Do we have any documentation on the different inherit environments? If we do, it would be useful to add a link to it in the [Debug a CMake project on a remote Windows machine](https://docs.microsoft.com/en-us/cpp/build/cmake-remote-debugging?view=msvc-160) topic.

For someone that is new to CMake it might not be clear what msvc_arm64_x64 represents (i.e. host and target clients) and, therefore, might not know which option to select

**Comment by sinemakinci1** [comment]
@TylerMSFT This describes what the different environments are, but not in a CMake context: https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=msvc-170#pre-defined-environments

Would this be sufficient? I'm not sure if CMake-specific documentation exists at the moment

**Comment by TylerMSFT** [comment]
Added a link to the environments. Will be live 3/11/2022
