### ISSUE TITLE
Unclear implementation of the memory barrier

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/cpp-docs#3008]
> The effect is comparable to but faster than the `_mm_mfence` intrinsic on all x64 platforms.
> 
> On the AMD64 platform, this routine generates an instruction that is a faster store fence than the sfence instruction. For time-critical code, use this intrinsic instead of `_mm_sfence` only on AMD64 platforms. On Intel x64 platforms, the `_mm_sfence` instruction is faster.

Is it possible to clarify what is the **actual** x64 instruction that this function generates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233c421f-3875-6280-a549-5ffd471ddaca
* Version Independent ID: 50b879eb-145b-6fdb-877e-325e706d875b
* Content: [__faststorefence](https://docs.microsoft.com/en-us/cpp/intrinsics/faststorefence?view=msvc-160)
* Content Source: [docs/intrinsics/faststorefence.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/faststorefence.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@I-gor-C 
Thanks for the question. I'm inclined toward answering no on the issue of clarification. Being specific leads to being wrong when the compiler innards change. It's rare for intrinsics, but it happens. As a result, we tend to stick to general descriptions for the implementation of intrinsics where possible.

It's fairly easy to find out the actual instructions generated for any given intrinsic. Both the [`/FAs`](https://docs.microsoft.com/cpp/build/reference/fa-fa-listing-file) compiler option and the [Compiler Explorer](https://godbolt.org/) online compiler will report the instructions generated by the intrinsics. The latter shows the x64 instruction output by `__faststorefence();` as `lock or DWORD PTR [rsp], 0`. I'm not sufficiently versed in the arcana of the x64 instruction set cycle counts to know why that might be faster than an `sfence` or `mfence` opcode on a given platform.
