### ISSUE TITLE
Missing _MSC_VER numbers

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [MicrosoftDocs/cpp-docs#3009]
On the page https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros
the _MSC_VER  numbers for 16.9. and 16.10 are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I forgot to close this after updating the content.
