### ISSUE TITLE
what about gamma sign and reentrant ?

### ISSUE THREAD

**Issue by mu578** [MicrosoftDocs/cpp-docs#3010]
[Enter feedback here]

what about gamma sign and reentrant ? is your implementation POSIX.1-2001/iso-c99 meaning log|G(x)| or something fringy? 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c608645-b288-48eb-c92b-1a5353d7f3b0
* Version Independent ID: 28ae4224-b86d-5d70-9b73-ad051d131538
* Content: [tgamma, tgammaf, tgammal](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tgamma-tgammaf-tgammal?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/tgamma-tgammaf-tgammal.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/tgamma-tgammaf-tgammal.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@moe123 
The functions exposed by *`<math.h>`* are C99 conforming. If C99 diverges from POSIX, then I don't think that's a variant that we implement. Do the docs need clarification?

**Comment by moe123** [comment]
@corob-msft yes the `lgamma` call needs clarifications; you maintain close source; then you must be more talkative on internal behaviors ; as well as; if it is reentrant safe; if it is? does it hard-lock internally? do you somehow export the sign of the `|gamma|` somewhere? in `tgamma` do you `exp` directly the result of `ln(|gamma(x)|)` or are you smarter? what's your error rate? what's your most erroneous ranges?

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
