### ISSUE TITLE
Refers to old versions of VS only

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/cpp-docs#3011]
It says multi-targeting functionality is available for Visual Studio 2017 and 2015 and doesn't mention 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b719c9-2ec7-6d15-fa2c-91cb95130d50
* Version Independent ID: 5cb20d71-19b4-e87e-5e87-7bbf4da355b9
* Content: [Use native multi-targeting in Visual Studio to build old projects](https://docs.microsoft.com/en-us/cpp/porting/use-native-multi-targeting?view=msvc-160)
* Content Source: [docs/porting/use-native-multi-targeting.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/use-native-multi-targeting.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@r3m0t 
Thanks for the notice. Given the 9,000+ articles  in the C++ docs repo, most don't get updated for each release unless we're aware of a change to the feature or function. We usually revisit articles for features that get deprecated, so if we haven't done that, it's reasonable to assume that the feature still works. Did it work for you?

**Comment by r3m0t** [comment]
I haven't tried, but I'll assume!

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
