### ISSUE TITLE
C5208 correction?

### ISSUE THREAD

**Issue by neobis001** [MicrosoftDocs/cpp-docs#3013]
From https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5208?view=msvc-160:

Unnamed classes within a typedef declaration can't have any members other than:
--non-static data members,
--member classes,
--member enumerations,
--**and default member initializers.**

It links to some P1766R1 proposal. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1766r1.html
There, it says in section 2.3:

We propose disallowing any case where a class is given a typedef name for linkage and its members include anything other than:
--non-static data members with **no default member initializers** (and no lambda-expressions in the type of the member)
--...

,,,

The current docs seem to say that default member initializers are allowed, when they're not. For example, this doesn't compile, which is right:

typedef struct {
	int a = 2;
} test_struct;

,,,

I'd say you can combine that last bullet point with the first, just like the proposal did:

Unnamed classes within a typedef declaration can't have any members other than:
--non-static data members **with no default member initializers**
--...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e07f3a-1c01-34ce-d1c6-81d1930b8558
* Version Independent ID: ac120d98-3f23-2683-75e3-7519c6638f77
* Content: [Compiler Warning C5208, Error C7626](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5208?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C5208)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/c5208.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/c5208.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@neobis001 
Thanks for the report; the update should be visible now.
