### ISSUE TITLE
NMake references shows example with !copy, but no such preprocessor directive is documented

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/cpp-docs#3014]
The page has this example:

```
UPDATE : *.*
!COPY $** c:\product\release
```

But !COPY doesn't seem to exist as a directive, and nmake errors on it.  Was this supposed to be @COPY?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994aee97-7c77-b074-c966-0d6a4b47d093
* Version Independent ID: 52253d9f-148c-7586-7d44-25b2ba13b6c1
* Content: [Description blocks](https://docs.microsoft.com/en-us/cpp/build/reference/description-blocks?view=msvc-160)
* Content Source: [docs/build/reference/description-blocks.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/description-blocks.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
That's a typo. Fixed. Thanks for pointing it out. The updated topic should be visible Monday afternoon.
