### ISSUE TITLE
Same .cpp file needed for project with stdafx.h and another project that use pch.h

### ISSUE THREAD

**Issue by dershver** [MicrosoftDocs/cpp-docs#3016]
[Enter feedback here]
I have an older project that uses stdafx.h for pre-compiled headers and a newer project that uses pch.h. I want to reuse the same class (.cpp and .h files) for both. I attempted to use an #ifdef #else block. This would not compile failing on the #endif.
Please, provide explanation on how to handle this situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7710ea05-1307-eaaf-3ba0-86175eeaf184
* Version Independent ID: 30568a08-383b-1676-dfb3-e1dc6f28f38c
* Content: [Fatal Error C1010](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1010?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1010)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1010.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1010.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dershver 
I appreciate the trouble you're facing. While it sounds like a reasonable solution for your shared class code, based on how precompiled headers work, you can't wrap them in #ifdef blocks in a .cpp file. You've run afoul of this line in the error doc:

> - Make sure the *pch.h* or *stdafx.h* header file is included before any other code **or preprocessor directives** in your source files.

(Emphasis added.) Unfortunately, the `#include "pch.h"` (or `#include "stdafx.h"`) line is a magic PCH boundary in source files. You can't have any preprocessor directives come before it, and that includes a useful `#ifdef` to switch between two versions. Hence the error. 

I can think of a hacky way to get around the issue. For example, you could leave the `#include "pch.h"` (or `#include "stdafx.h"`) line out of your class implementation in *`my_class.cpp`*, and then create a new file for each project called something like *`my_class_wrapper.cpp`*. Inside, those files would just consist of:

```cpp
#include <stdafx.h>
#include "my_class.cpp"
```

or

```cpp
#include <pch.h>
#include "my_class.cpp"
```

for the respective projects. Then you'd need to include the wrapper source file in the builds for each project, and exclude the regular implementation. (Alternatively: rename the shared implementation source file something like *`my_class.i`* to exclude it from the build.) I haven't tried this, but I expect it would work. There may be other more elegant solutions available if you search the web.

**Comment by dershver** [comment]
The workaround I implemented was to create a Preprocessor Definition
MY_PCH. In one project this is defined as
MY_PCH="stdafx.h" and in the  other MY_PCH="pch.h" .  In the .cpp files, I
had #include MY_PCH.
This didi work. Actually, I needed to share three different classes so
there were three .cpp files that I modified
in this manner.

                                       Paul Klahr
