### ISSUE TITLE
Code listing doesn't compile, with suggested causes

### ISSUE THREAD

**Issue by NorthernBlunt** [MicrosoftDocs/cpp-docs#3018]
In the code listing the line:
      printf("sum: %s\n", passed  "Passed!" : "Failed!");
should be:
      printf("sum: %s\n", passed ?  "Passed!" : "Failed!");

There is also an error preventing successful compilation in the system file xxamp.h which I have reported separately to the Visual Studio team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec054a56-bc4a-198e-6fc1-8a9fbb78c2c2
* Version Independent ID: 0bb33ae4-3fb1-8683-b3c2-6773e3b20cfb
* Content: [Walkthrough: Debugging a C++ AMP Application](https://docs.microsoft.com/en-us/cpp/parallel/amp/walkthrough-debugging-a-cpp-amp-application?view=msvc-160)
* Content Source: [docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@NorthernBlunt 
Thanks for reporting the issue. The fix to the `printf` call should appear sometime in the next day.
