### ISSUE TITLE
Update documentation on encoding of linker response files

### ISSUE THREAD

**Issue by AntonLapounov** [MicrosoftDocs/cpp-docs#3019]
The page says:

> ### Linker response files and .DEF files
> Response files and DEF files can be either UTF-16 with a BOM, or ANSI.

A quick experiment shows that the linker supports UTF-8 with a BOM as well. Please update the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e7696-d625-cc8f-c01d-cf4484096616
* Version Independent ID: d932cdf5-d000-bcdc-d98d-cf6b82afe6d1
* Content: [Unicode Support in the Compiler and Linker](https://docs.microsoft.com/en-us/cpp/build/reference/unicode-support-in-the-compiler-and-linker?view=msvc-160)
* Content Source: [docs/build/reference/unicode-support-in-the-compiler-and-linker.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/unicode-support-in-the-compiler-and-linker.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
UTF-8 with BOM was added to the article. I think the writer just forgot to close this.
