### ISSUE TITLE
Unclear how to use

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/cpp-docs#302]
What does "if supported" mean? A simple example would I think make this so much more obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ff826c8-cf73-057a-d71e-24d27b012654
* Version Independent ID: 8ef10a89-2b0f-f085-b7f6-a33289c0516c
* Content: [ComPtr::AsIID Method](https://docs.microsoft.com/en-us/cpp/windows/comptr-asiid-method)
* Content Source: [docs/windows/comptr-asiid-method.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/comptr-asiid-method.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks amp64. I clarified the topic and it should be visible by 07/12.
