### ISSUE TITLE
this does not work at all

### ISSUE THREAD

**Issue by DavidEnglund** [MicrosoftDocs/cpp-docs#3020]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Create and use a static library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=msvc-160)
* Content Source: [docs/build/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DavidEnglund 
I'm sorry you're having difficulty. I know lots of others have run through this walkthrough successfully. What parts are you having trouble with?

**Comment by corob-msft** [comment]
Closing as unactionable.
