### ISSUE TITLE
Where is the Icon Editor?

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/cpp-docs#3026]
Using Visual Studio 2017, I can't see the Image Editor. Selecting an image opens up Paint. How does one load it. In Visual Studio 2010, this was never a problem.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195f6bf5-8435-ecda-e7c6-c705934e9fa6
* Version Independent ID: 8a714db6-0297-a0ec-3f3c-bb2156741192
* Content: [Image Editor for Icons (C++)](https://docs.microsoft.com/en-us/cpp/windows/image-editor-for-icons?view=msvc-160)
* Content Source: [docs/windows/image-editor-for-icons.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/image-editor-for-icons.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LukeChung 
Your issue sounds like an installation problem. Normally, the image editors get installed by the C++ workloads. If they're not installed, you might get the behavior you're seeing. You can install them separately: Launch the Visual Studio Installer. If you're on the main page, select **Modify** next to your VS installation. On the next page, choose the **Individual Components** tab at the top. Scroll down to the **Games and Graphics** section, and check the **Image and 3D model editors** box. Then, choose the Modify button at bottom right. When the installation completes, you should be able to edit image resources. For similar issues in the future, I recommend [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html).
