### ISSUE TITLE
WriteFile() documentation doesn't mention ERROR_NO_DATA when writing to a pipe

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/cpp-docs#3029]
This really belongs in sdk-api, but that doesn't have any place to file issues, just a place to file pull requests.  I'm not sure whether this issue is a *documentation* problem or a *code* problem (in either the NT kernel pipe code or in the VS library code to map Windows error codes to errno values), so I'm not about to file a pull request....

[The `WriteFile()` documentation](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile) says:

> If an anonymous pipe is being used and the read handle has been closed, when **WriteFile** attempts to write using the pipe's corresponding write handle, the function returns **FALSE** and GetLastError returns **ERROR_BROKEN_PIPE**.

If I compile this program:

```
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <io.h>
#include <windows.h>

static const char line[] = "Hello\r\n";

int
main(void)
{
	int ret;

	Sleep(20 * 1000);
	ret = _write(1, line, (unsigned int)(sizeof line - 1));
	if (ret == -1) {
		fprintf(stderr, "Write error: errno %d (%s), Windows status %d\n",
		    errno, strerror(errno), _doserrno);
		return 2;
	}
	return 0;
}
```

into writer.exe, and compile this program:

```
int
main(void)
{
	return 0;
}
```

into reader.exe, and run, from a cmd.exe command line, the command

    writer | reader

the error message I get is

    Write error: errno 22 (Invalid argument), Windows status 232

232 is `ERROR_NO_DATA`, not `ERROR_BROKEN_PIPE`.  `ERROR_NO_DATA` is described as "The pipe is being closed."; `ERROR_BROKEN_PIPE` is described as "The pipe has been ended."

So either:

1. cmd.exe doesn't use an anonymous pipe to implement pipes in command lines;
1. the read side pipe isn't getting closed when reader exits;
1. the failing call isn't a `WriteFile()` call;
1. the Microsoft documentation is mistaken when it claims that WriteFile() to an anonymous pipe of which the read side is closed fails with ERROR_BROKEN_PIPE.

"The failing call isn't a `WriteFile()` call" is probably not the problem, as I've seen similar comments online about `WriteFile()` calls.

I *suspect* "cmd.exe doesn't use an anonymous pipe to implement pipes in command lines" isn't the case, as it's an obvious choice (I have the impression that old MS-DOS shells implemented pipes with a temporary file, running each command sequentially one at a time, but NT supports multitasking and anonymous pipes, so it doesn't have to do that).

So that would leave "the read side pipe isn't getting closed when reader exits" and "the Microsoft documentation is mistaken when it claims that WriteFile() to an anonymous pipe of which the read side is closed fails with `ERROR_BROKEN_PIPE`", unless I'm missing a reason that's not any of the above.

[The Anonymous Pipe Operations documentation](https://docs.microsoft.com/en-us/windows/win32/ipc/anonymous-pipe-operations) says that

> An anonymous pipe exists until all pipe handles, both read and write, have been closed. A process can close its pipe handles by using the [**CloseHandle**](https://docs.microsoft.com/en-us/windows/desktop/api/handleapi/nf-handleapi-closehandle) function. All pipe handles are also closed when the process terminates.

which I'm assuming means that, when reader.exe exits, the pipe handle that I presume is its standard input is closed.

The pipe still exists, as writer.exe is still running (the `Sleep()` call is to make sure the write is delayed until after reader.exe exits).  `ERROR_BROKEN_PIPE` clearly can't be returned only if the pipe is gone, as there's nothing to which to write if the writer closes the handle.

This came up because of [a Wireshark bug](https://gitlab.com/wireshark/wireshark/-/issues/16192) in which Wireshark's command-line packet analyzer tshark, which checks for errors even when writing to the standard output (I'm fussy that way - the main concern is "what happens if the write fills up the file system or goes over the user's quota") and, except for `EPIPE`, reports the error.

It doesn't report `EPIPE` because, on UN\*Xes, that could just mean that tshark's output was being piped to another program, and that program had already exited; that just means tshark can quit, as there's nobody left reading its output.  However, `ERROR_NO_DATA` gets mapped to `EINVAL`, not `EPIPE`, and we don't check for `EINVAL`.

The `_write()` documentation says nothing about `EPIPE` or `EINVAL`, so it doesn't indicate what happens if you try to write to a pipe with no read handles open.

If all of this behavior (returning `ERROR_NO_DATA` on writes to a closed pipe, mapping `ERROR_NO_DATA` to `EINVAL`) is intentional, it should probably be noted in both the `WriteFile()` and the `_write()` documentation, or in pipe documentation to which both of those documents should refer.  If any of it is *not* intentional, it should be fixed if that can be done without unacceptably breaking compatibility.

**Comment by corob-msft** [comment]
@guyharris 

It's plausible that you're seeing something that would fit in your option 2, where the cmd process might wait for writer.exe to exit before it fully closes the pipe. In that case, the `ERROR_NO_DATA` value could make sense. I'm not privy to what goes in inside cmd, so I couldn't say. An internal `WriteFile` call is the most reasonable source for what's reported after the `_write` call. If either ERROR_NO_DATA or ERROR_BROKEN_PIPE gets returned by the internal call to `WriteFile`, EINVAL is what `_write` would report, and that matches your test experience. Hence I'm not sure I see anything to update in the C++ docs. 

So, what sort of resolution to this issue are you hoping for?

**Comment by corob-msft** [comment]
Following up, I see the `_write` docs don't mention several possible causes for EINVAL, which is an oversight. In fact, all `WriteFile` error results that aren't `ERROR_ACCESS_DENIED` get turned into EINVAL by a call to `_write`. That one turns into `EBADF`.

**Comment by corob-msft** [comment]
@drewbatgit FYI, possible issue in [`WriteFile`](https://cpubwin.visualstudio.com/win32/_git/sdk-api-build?path=%2Fsdk-api-src%2Fcontent%2Ffileapi%2Fnf-fileapi-writefile.md&version=GBlive) docs.

**Comment by guyharris** [comment]
> So, what sort of resolution to this issue are you hoping for?

Well, the first think I'd like would be better descriptions on [the System Error Codes (0-499) page](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) of `ERROR_BROKEN_PIPE` and `ERROR_NO_DATA` mean. 

What does "The pipe has been ended." for `ERROR_BROKEN_PIPE` mean?  Presumably it doesn't mean that both the read and write sides of the pipe are closed - there's at least *one* write-side handle for the pipe open, because `ERROR_BROKEN_PIPE`, not `ERROR_INVALID_HANDLE`, was returned.

And what does "The pipe is being closed." for `ERROR_NO_DATA` mean?  Presumably, the write side isn't being closed, because, again, there's at least one write-side handle for the pipe open.  If it means that the *read* side is being closed, then, unless that close can fail, leaving the pipe open so that more reads can be done on it, I'm not sure why "the read side of the pipe is being closed" should be treated differently from "the read side of the pipe is closed", unless the idea is that `CloseHandle()` is in progress on one thread but a `ReadFile()` in another thread should be able to read from the pipe until the `CloseHandle()` completes, in which case a `WriteFile()` on the write side shouldn't get an error.

**Comment by guyharris** [comment]
[The (no longer available) "How to spawn console processes with redirected standard handles" article on support.microsoft.com](https://web.archive.org/web/20070210075829/http://support.microsoft.com/kb/190351) has sample code that writes to an anonymous pipe and checks only for `ERROR_NO_DATA`, not for `ERROR_BROKEN_PIPE`.  It does check for `ERROR_BROKEN_PIPE` when *reading* from a pipe.  The comment for the `ERROR_NO_DATA` error from `WriteFile()` is "Pipe was closed (normal exit path)."

**Comment by drewbatgit** [comment]
@mikben This article is in your area, can you take a look?

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
