### ISSUE TITLE
Instructions are not accurate for VS2017

### ISSUE THREAD

**Issue by cphurley82** [MicrosoftDocs/cpp-docs#303]
When going through this tutorial with VS2017 there were several inaccuracies in the instructions.

Under #BKMK_CreateLibProject
Steps 2-3 should be...
2. In the left pane of the New Project dialog box, expand Installed, Visual C++, and then select Windows Desktop.
3. In the center pane, select Windows Desktop Wizard.

Steps 5-8 should be..
5. Under Application type, select Static Library (.lib).
6. Under Additioal Options, clear the Precompiled header check box.
7. Choose OK to create the project.

Under #BKMK_CreateAppToRefTheLib
Steps 2-3 should be...
2. In the left pane of the New Project dialog box, expand Installed, Visual C++, and then select Windows Desktop.
3. In the center pane, select Windows Desktop Wizard.

Steps 5-8 should be..
5. Under Application type, select Consol Application (.exe).
6. Under Additioal Options, clear the Precompiled header check box.
7. Choose OK to create the project.

Under #BKMK_UseLibInApp
Step 2 should be...
2. Before you can use the math routines in the static library, you must reference it. To do this, open the shortcut menu for the MyExecRefsLib project in Solution Explorer, and then choose Add, Reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-and-using-a-static-library-cpp#BKMK_CreateLibProject)
* Content Source: [docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
fixed. thanks @cphurley82 !
