### ISSUE TITLE
__is_pod(T)

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#3030]
It is Ok to mention?

- cl.exe intrinsic `__is_pod(T) ` 
- std::is_pod<> deprecation as from C++20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249da7e2-4135-6468-221b-d62df3af0f22
* Version Independent ID: 2e68cba5-e743-2d88-7b4c-7bb6f79c54cd
* Content: [Trivial, standard-layout, POD, and literal types](https://docs.microsoft.com/en-us/cpp/cpp/trivial-standard-layout-and-pod-types?view=msvc-160)
* Content Source: [docs/cpp/trivial-standard-layout-and-pod-types.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/trivial-standard-layout-and-pod-types.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ 

I'm inclined to say it's not necessary to mention `__is_pod(T)`, as that's a Microsoft-specific implementation detail that could change, and probably shouldn't be used anywhere except the library implementation of `std::is_pod`. 

The deprecation, on the other hand, is worth mentioning. I wasn't previously aware of it as specifically deprecated, just that there were now more specific tests for `is_trivial` and `is_standard_layout`. Thanks for pointing that out.

**Comment by DBJDBJ** [comment]
cl intrinsics are one very interesting subject.  Why is each made, when etc ... That would be a real thriller book.
