### ISSUE TITLE
appropriate use of the container type than std::vector in explaining ellipsis placement for function parameters

### ISSUE THREAD

**Issue by rahul-deshmukhpatil** [MicrosoftDocs/cpp-docs#3032]
n the section "More about ellipsis placement"

Can we use std::map or std::tuple as a container instead of std::vector? Because std::vector<Types...> does not make sense as a vector is of a single type element (unless used abstraction type std::variant<Types>).  It could be that Allocator is the 2nd type among Types for vector, but not so trivial to assume for this simple example.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516af34c-0d41-3ee3-2df1-e7d68eb17325
* Version Independent ID: 05d065d1-8cd4-d2b4-cbcb-4a68df79123c
* Content: [Ellipsis and Variadic Templates](https://docs.microsoft.com/en-us/cpp/cpp/ellipses-and-variadic-templates?view=msvc-160)
* Content Source: [docs/cpp/ellipses-and-variadic-templates.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/ellipses-and-variadic-templates.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
