### ISSUE TITLE
Include brew instructions

### ISSUE THREAD

**Issue by cxsmxx** [MicrosoftDocs/cpp-docs#3034]
Hi, 

I installed vcpkg using `brew install vcpkg` please check it and if it's valid and verified source also according to you, please consider adding this choice to page. Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b976f77-ad03-e4df-2110-547661be152d
* Version Independent ID: 1733f352-20e0-d14a-c8dc-28c19909ed35
* Content: [Install vcpkg on Windows, Linux, and macOS](https://docs.microsoft.com/en-us/cpp/build/install-vcpkg?view=msvc-160&tabs=macos)
* Content Source: [docs/build/install-vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/install-vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cxsmxx 
That's an interesting idea. The recipe isn't under Microsoft control or vetted by us, so it might lag updates or include patches that haven't been thoroughly tested. However, I'll run the idea past the product team.

@AugP FYI, and feel free to chime in on whether this is appropriate.

**Comment by cxsmxx** [comment]
Yeah I understand that it would need to be under some sort of control or at least put a disclaimer, however many osx programmers i know use brew for sake of centricity, so that might be a plus point. Thanks for prompt answer and if I can help further I am happy to!

**Comment by corob-msft** [comment]
@cxsmxx 
After some consideration, the engineering team doesn't recommend homebrew for vcpkg install. Thanks for the suggestion; we appreciate documentation ideas even if sometimes, as in this case, we can't implement them.
