### ISSUE TITLE
Example wrong?

### ISSUE THREAD

**Issue by CwTCwT** [MicrosoftDocs/cpp-docs#3038]
in the example for sin (https://docs.microsoft.com/en-us/cpp/standard-library/complex-functions?view=msvc-160&redirectedfrom=MSDN&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk%28std%253A%253Asin%29%3Bk%28std.sin%29%3Bk%28DevLang-C%252B%252B%29%3Bk%28TargetOS-Windows%29%26rd%3Dtrue#sin):

an output is made like following:

> // Values of sine of a complex number c1
>    complex <double> c2 = sin ( c1 );
>    cout << "Complex number c2 = sin ( c1 ) = " << c2 << endl;

but in the belonging example output following is visible:

> Complex number c2 = sin ( c1 ) = (3.85374,-27.0168)

that doesnt match?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c013d1-bb41-e479-d629-40c8c5810928
* Version Independent ID: edd129c7-ab02-9b77-8069-133e2633e0c9
* Content: [&lt;complex&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/complex-functions?view=msvc-160&redirectedfrom=MSDN&f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk%28std%253A%253Asin%29%3Bk%28std.sin%29%3Bk%28DevLang-C%252B%252B%29%3Bk%28TargetOS-Windows%29%26rd%3Dtrue#feedback)
* Content Source: [docs/standard-library/complex-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/complex-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @CwTCwT, 

The output looks correct and matches what I get when I run the sample.
One thing that may be confusing is that abs() means to get the modulus of a complex number (could be confused with getting the absolute value, but that's not the use here). 
Or maybe it is that complex numbers display as (number,number)? That's also correct.

I close this but reopen if I misunderstood what you were getting at.
