### ISSUE TITLE
Const

### ISSUE THREAD

**Issue by labm1ce** [MicrosoftDocs/cpp-docs#3043]
[Enter feedback here]
I like that it shows the example before the recommended change, but why not also show the example with the change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a86929-5371-935b-1dfa-937ab60c6f2e
* Version Independent ID: 8158217a-2688-19ee-4fa5-58848031a31b
* Content: [C26496](https://docs.microsoft.com/en-us/cpp/code-quality/c26496?view=msvc-160)
* Content Source: [docs/code-quality/c26496.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26496.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
