### ISSUE TITLE
"Quick start" link in install-vcpkg.md is broken

### ISSUE THREAD

**Issue by themaxdavitt** [MicrosoftDocs/cpp-docs#3046]
I believe https://github.com/microsoft/vcpkg/pull/16758 broke the "Quick start" link at the bottom of the `install-vcpkg.md` page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b976f77-ad03-e4df-2110-547661be152d
* Version Independent ID: 1733f352-20e0-d14a-c8dc-28c19909ed35
* Content: [Install vcpkg on Windows, Linux, and macOS](https://docs.microsoft.com/en-us/cpp/build/install-vcpkg?view=msvc-160&tabs=windows#feedback)
* Content Source: [docs/build/install-vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/install-vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@themaxdavitt 
A fix should appear sometime Monday.
