### ISSUE TITLE
my bad

### ISSUE THREAD

**Issue by JohnTheStudent122** [MicrosoftDocs/cpp-docs#3053]
[Enter feedback here]
earlier i gave this a thumbs down casue i thought it didnt help me actually fix my problem but i was just too daft to read the comments and those istantly fixed the problem and i was able to understand why as well, this is my apology to the author who actually did a pretty great job

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada1fb00-b641-58cf-0641-9302be5c497e
* Version Independent ID: 655f4082-3350-0b74-f8ca-7d89efbed776
* Content: [Compiler Error C2276](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2276?view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2276.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2276.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JohnTheStudent122 
Thanks for the feedback. People often react negatively to the sample introduction in these older error articles: "The following sample generates C2276", and with good reason. No one wants to know how to cause the error, they just want to know how to fix it. If they just skim the text and don't look any farther, they won't find the solutions. So, whenever I touch one of these articles, I try to clarify that intro, to make it more obvious that both the problem and the solutions are found in the example code. Something like "This sample shows several ways C2276 can occur, and how to fix them."  I'm glad you found what you needed when you looked more closely.
