### ISSUE TITLE
Parameter name incorrect in Remarks

### ISSUE THREAD

**Issue by ddocky** [MicrosoftDocs/cpp-docs#3056]
The Remarks section says

> use _TRUNCATE or adjust the _size_ parameter accordingly

but there is no parameter named _size_.  The parameter's name is _count_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9eb38e-2f45-9ddf-a705-a90f1a6e1575
* Version Independent ID: 7bce2c07-1089-cb74-a2e2-ca8b3effbd3d
* Content: [strncat_s, _strncat_s_l, wcsncat_s, _wcsncat_s_l, _mbsncat_s, _mbsncat_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncat-s-strncat-s-l-wcsncat-s-wcsncat-s-l-mbsncat-s-mbsncat-s-l?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/strncat-s-strncat-s-l-wcsncat-s-wcsncat-s-l-mbsncat-s-mbsncat-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strncat-s-strncat-s-l-wcsncat-s-wcsncat-s-l-mbsncat-s-mbsncat-s-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for pointing that out, @ddocky. I've fixed it and it should be live in a day or two.
