### ISSUE TITLE
C C++

### ISSUE THREAD

**Issue by seacock** [MicrosoftDocs/cpp-docs#3059]
keyword **inline** solved my problem of mixed compilation C++ C. If I had tried it before... (ignorance + obstination).
Good article.
thanks
Trevisan Andrea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e3f4058-9a81-d1d1-dbde-7622d2569d64
* Version Independent ID: 09efa20f-df41-b5ba-4158-a39a2a9553a1
* Content: [Linker Tools Error LNK2005](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(LNK2005)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2005.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2005.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@seacock 
Thanks for the comments. I'm closing, as this doesn't look like an issue to be addressed.
