### ISSUE TITLE
derivation specification for template parameters?

### ISSUE THREAD

**Issue by ChuckStarchaser** [MicrosoftDocs/cpp-docs#3062]
I'm sure there must be a way to specify that a class in a template argument must be derived from a particular class...
I tried

```
    class  foo
    {
        a_foo_function();
    }
    //.......
    template  < class F : foo >  // <<<=== my deceptively creative syntax
    class bar
    {
        F * pf;
        void f(){  pf->a_foo_function();  }  //guaranteed to work in my book
    }

```
But it doesn't compile.
There must be a way to specify derivation for a template parameter, though,
but neither this page nor anywhere else I go touches this subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a0926f1-2f1e-7d5c-d7cf-4e5fe92bcdbd
* Version Independent ID: ef51814b-f257-d8cf-2b77-90407604bd6b
* Content: [Templates (C++)](https://docs.microsoft.com/en-us/cpp/cpp/templates-cpp?view=msvc-160)
* Content Source: [docs/cpp/templates-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/templates-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ChuckStarchaser 
This article covers the basics of templates through C++14. There isn't an easy way to require a template argument match a particular constraint in C++14. You can do it with concepts and constraints in C++20, but that's not covered here, or anywhere in our docs, and won't be for some time. For now, the [constraints docs on cppreference.com](https://en.cppreference.com/w/cpp/language/constraints) are more up-to-date. 

As an example, something like this might work, provided you use /std:c++latest to compile:

```
#include <iostream>
#include <concepts>

class  foo
{
public:
    virtual void a_foo_function() { std::cout << "called a_foo_function.\n"; }
};

template <class D>
concept BasedOnFoo = std::is_base_of<foo, D>::value;

class foo_junior : public foo
{};

template  < typename F > requires BasedOnFoo<F> // Constrain F to be based on foo
class bar
{
    F _f;
public:
    void fn()
    {
        _f.a_foo_function();
    }
};

int main()
{
    bar<foo_junior> b;
    b.fn();
}
```

Closing this as currently outside of our scope.
