### ISSUE TITLE
ejemplo ON_WM_CTLCOLOR para un control estatico "Label"

### ISSUE THREAD

**Issue by jcat18** [MicrosoftDocs/cpp-docs#3065]
[Enter feedback here]

PAsos
**1) En la sección CDataExchange* pDX del formulario**

Un control estático se puede atar a a una variable tipo CSTring  ejemplo:
DDX_Text(pDX, IDC_LBL_FACTURABIGINT, m_lblFacturaBigint);

**2) sección BEGIN_MESSAGE_MAP**
Matriculamos el evento
ON_WM_CTLCOLOR(IDC_LBL_FACTURABIGINT, &CDlg::OnCtlColor)

* IDC_LBL_FACTURABIGINT  es el control estatico "label"
* CDlg es la clase del formulario

**2.1) implementacion del evento OnCtlColor()**

tomado de la documantación de Microsoft en la página de ayuda de C++
HBRUSH CDlg::OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor)
{
	// Call the base class implementation first! Otherwise, it may
   // undo what we're trying to accomplish here.
   HBRUSH hbr = CDialog::OnCtlColor(pDC, pWnd, nCtlColor);

   // Are we painting the IDC_MYSTATIC control? We can use
   // CWnd::GetDlgCtrlID() to perform the most efficient test.
   if (pWnd->GetDlgCtrlID() == IDC_LBL_FACTURABIGINT)
   {
      // Set the text color to red
      pDC->SetTextColor(RGB(255, 0, 0)); //"color rojo"

      // Set the background mode for text to transparent 
      // so background will show thru.
      pDC->SetBkMode(TRANSPARENT);

      // Return handle to our CBrush object
      //hbr = m_brush; no hay var hbr se comenta  <---ojo aca**
   }
   return hbr;
}
-->ojo aca**
no tenemos variable m_brush  pero solo queremos que un mensaje importante quede en "color rojo"

A la variable del control "label" le colocamos el valor
m_lblFacturaBigint = "15,250,000,000";  //en ambiente real viene de una base de datos				
UpdateData(false); //avtualkizamos la UI

**Efecto desado**
![image](https://user-images.githubusercontent.com/36974441/113237982-7fe90400-926d-11eb-926a-1317ce9ff52f.png)

(:  ok.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f567a739-943e-c85d-07a1-d43229fa6d4e
* Version Independent ID: c41ddd0d-df30-7ac0-407b-d7a9c9a18478
* Content: [CWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=msvc-160#onctlcolor)
* Content Source: [docs/mfc/reference/cwnd-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cwnd-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@jcat18 
In the [example](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=msvc-160#example-52), we explain `m_brush` in the comments. We assume you created `m_brush` as a member of `CPenWidthsDlg`. It exists only as a value to return from `CPenWidthsDlg::OnCtlColor`. The reason you create it as a member of the `CDlg` is so you can ensure you delete it later. You don't have to create or use `m_brush`. You can return a system brush from `OnCtlColor` instead. For example, a statement like 'return ::GetSysColorBrush( COLOR_3DFACE );` should also work fine.
