### ISSUE TITLE
no entiendo

### ISSUE THREAD

**Issue by Osvaldo-25** [MicrosoftDocs/cpp-docs#3073]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg: a C++ package manager for Windows, Linux, and macOS](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160)
* Content Source: [docs/build/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vcpkg.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Osvaldo-25 
I'm sorry to hear you don't understand. Unfortunately, we don't know what needs to change to help you, so we can't do anything about it. If you can be more specific, I'll reopen this issue.
