### ISSUE TITLE
adds

### ISSUE THREAD

**Issue by ytbigvinny27** [MicrosoftDocs/cpp-docs#3077]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6dd452-37f0-4bf1-b791-dfdaad2fcab7
* Version Independent ID: 7f114a50-c339-7527-c2fd-6bb73c599947
* Content: [AddressSanitizer](https://docs.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-160)
* Content Source: [docs/sanitizers/asan.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/sanitizers/asan.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ytbigvinny27 
I'm sorry, I can't tell what's wrong from your issue title alone. If you add a description of the problem you found, I'll reopen this issue.
