### ISSUE TITLE
wrong example

### ISSUE THREAD

**Issue by tobias-loew** [MicrosoftDocs/cpp-docs#3078]
the example doesn't mention __uuidof

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67e83777-3a00-6f8c-4402-7de4c052bf35
* Version Independent ID: 2cf531df-a2c9-adb4-3ead-835a14184c59
* Content: [__uuidof Operator](https://docs.microsoft.com/en-us/cpp/cpp/uuidof-operator?view=msvc-160)
* Content Source: [docs/cpp/uuidof-operator.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/uuidof-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tobias-loew 
The call to `__uuidof` is hiding in this line:

`   StringFromCLSID(__uuidof(MyLib), &lpolestr);`
