### ISSUE TITLE
MSVC's implementation of std::async does not behave as documented.

### ISSUE THREAD

**Issue by HPaulS** [MicrosoftDocs/cpp-docs#308]
When you say that "If policy is launch::async, the [std::async] function creates a thread that..." this is not strictly true (because the MSVC version of std::async is built on top of the ThreadPool).   You really should document what *your* implementation of std::async does properly to save people some pain, see:

https://stackoverflow.com/questions/50897768/in-visual-studio-thread-local-variables-destructor-not-called-when-used-with

(and my answer).

Tested in Visual Studio 2017, version 15.6.7 - Paul Sanders.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f75d083-01f1-c6c4-7e55-176ca439a980
* Version Independent ID: 39ae722e-53a2-997d-6510-63a2cdf07eef
* Content: [&lt;future&gt; functions](https://docs.microsoft.com/en-gb/cpp/standard-library/future-functions)
* Content Source: [docs/standard-library/future-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/future-functions.md)
* Product: **visual-cpp**
* GitHub Login: @Saisang

**Comment by mikeblome** [comment]
Thanks much Paul! The team verified your comments and advice, and I have updated the doc. Should be visible 07/12.

**Comment by HPaulS** [comment]
Yep, looks good, that should sort things out.  But why did I have to wait until December? :)

**Comment by Chronial** [comment]
Issue regarding the behavior itself: https://github.com/microsoft/STL/issues/949
