### ISSUE TITLE
There is no documentation on the Visual C++ compiler's /external command line option.

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/cpp-docs#3089]
There is no documentation on the Visual C++ compiler's "/external" command line option. This has been around for a while now and is getting further enhancement in Visual C++ 2019 Update 10 Preview 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2353367-e490-5dc3-fc39-3bcba30bf365
* Version Independent ID: 4300089e-7ea0-68bf-eb1f-c9c31cdb8d41
* Content: [Compiler options listed alphabetically](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=msvc-160)
* Content Source: [docs/build/reference/compiler-options-listed-alphabetically.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/compiler-options-listed-alphabetically.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed back in May, but failed to update this issue at the time.
