### ISSUE TITLE
Typo for FE_ALLEXCEPT

### ISSUE THREAD

**Issue by gvanem** [MicrosoftDocs/cpp-docs#309]
FE_ALLEXCEPT should be FE_ALL_EXCEPT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f53f5e72-861c-7526-d1af-fae8f3402edc
* Version Independent ID: 7b13b46e-33ba-5426-023e-d7a340ecf046
* Content: [feclearexcept1](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/feclearexcept1)
* Content Source: [docs/c-runtime-library/reference/feclearexcept1.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/feclearexcept1.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks. This is a great issue to test your GitHub pull request skills on, too. :)

**Comment by corob-msft** [comment]
Good work! Thanks for driving higher quality into our docs.
