### ISSUE TITLE
Signedness of char in Microsoft compiler?

### ISSUE THREAD

**Issue by fdwr** [MicrosoftDocs/cpp-docs#3100]
"In the Microsoft compiler, char is an 8-bit type."

Please clarify whether it is signed or unsigned. Of course, `signed` wouldn't make any sense, as there isn't such a thing as negative code points (characters range 0 to 255), the wchar is also unsigned, `signed char` has security issues when accessing arrays, and `isspace` asserts if you try passing valid ANSI text 128-255 to it, and so I'd logically assume it is unsigned too, but would be nice to confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b96635-cde4-f0e6-8848-606d346cb714
* Version Independent ID: 3745162c-993e-5f89-1188-bb3077d3a23d
* Content: [char, wchar_t, char16_t, char32_t](https://docs.microsoft.com/en-us/cpp/cpp/char-wchar-t-char16-t-char32-t?view=msvc-160)
* Content Source: [docs/cpp/char-wchar-t-char16-t-char32-t.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/char-wchar-t-char16-t-char32-t.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fdwr 

Naturally, **`char`** is more complicated than just signed or unsigned. In the Microsoft implementation, **`char`** acts like it's signed by default, but you can use the **`/J`** switch to make it act like it's unsigned. It's explained in the earlier topic on [Built-in types](https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=msvc-160), but for people who land here directly, I'll expand the text at the end of the first paragraph in the **Remarks** section:

"In the Microsoft compiler, **`char`** is an 8-bit type. It's a distinct type from both **`signed char`** and **`unsigned char`**. Variables of type **`char`** are promoted to **`int`** as if from type **`signed char`** by default, unless the [`/J`](../build/reference/j-default-char-type-is-unsigned.md) compiler option is used. Under **`/J`**, they're treated as type **`unsigned char`** and get promoted to **`int`** without sign extension."

Updated content should appear Monday.

**Comment by fdwr** [comment]
Thanks @corob-msft .
