### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by StockBrick** [MicrosoftDocs/cpp-docs#3102]
Worked for me. Found this easy to follow even as a novice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96f0a01-2e3a-6301-bba1-6a50252555b0
* Version Independent ID: 290ca773-a214-e81a-2ba3-c647f2b28a56
* Content: [Walkthrough: Compile a C program on the command line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-160)
* Content Source: [docs/build/walkthrough-compile-a-c-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-compile-a-c-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@StockBrick 
Thanks, we appreciate the positive feedback.
