### ISSUE TITLE
Documentation Bug: constructor for std::bitset

### ISSUE THREAD

**Issue by harithmanoj** [MicrosoftDocs/cpp-docs#3103]
There are 2 `constexpr` constructors for `std::bitset` , the default one and one that takes `unsigned long long`, while the constructors are implemented as `constexpr`, the documentation https://docs.microsoft.com/en-us/cpp/standard-library/bitset-class?view=msvc-160#bitset does not declare them as `constexpr`.

Reference: 
- cppreference: https://en.cppreference.com/w/cpp/utility/bitset/bitset
- C++17 final working draft (n4659): https://timsong-cpp.github.io/cppwp/n4659/bitset.cons
- code snippet showing `constexpr` constructor in use: https://godbolt.org/z/qMP5WsTe9

**Comment by TylerMSFT** [comment]
Thank you, @harithmanoj, I've fixed that, along with some other things I noticed that could be updated in that topic. Thank you for bringing this to our attention. The fix should be live by 6/10/2021
