### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by K1TCH** [MicrosoftDocs/cpp-docs#3106]
CAsyncSocket misspelled at the bottom.

![image](https://user-images.githubusercontent.com/8645722/116279616-5d071e00-a74d-11eb-8bd6-3fdb0642c2d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ccdd64a-197b-0d98-31c0-8278528b8603
* Version Independent ID: b94ce866-5452-c70d-a8b5-db859f506959
* Content: [Windows Sockets: Using Class CAsyncSocket](https://docs.microsoft.com/en-us/cpp/mfc/windows-sockets-using-class-casyncsocket?view=msvc-160)
* Content Source: [docs/mfc/windows-sockets-using-class-casyncsocket.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/windows-sockets-using-class-casyncsocket.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @KITCH. I fixed this and it should be live by 6/10/2021
