### ISSUE TITLE
C language documentation

### ISSUE THREAD

**Issue by SAINT-CHRIS** [MicrosoftDocs/cpp-docs#3109]
[i want to make this clear,the documentation does not contain what is new,in a sense that,the update.if i have knowledge of c programming already and there an update,how will i know Microsoft?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21945129-819f-b824-1448-7dcf82489dbb
* Version Independent ID: 4208a09f-059d-e29c-da34-6f37f12f2ca6
* Content: [Statements (C)](https://docs.microsoft.com/en-us/cpp/c-language/statements-c?view=msvc-160)
* Content Source: [docs/c-language/statements-c.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/statements-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SAINT-CHRIS 
I don't recall that there are any new statement types. Is something missing?

**Comment by corob-msft** [comment]
Closing, as this was probably addressed in #3111.
