### ISSUE TITLE
Additional Details on Headers

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/cpp-docs#311]
Please detail which libraries must be configured for this to work and any other project settings. #include afx.h is not sufficient, there must be other configurations required, these details are not listed in subsequent articles. Provide a code sample of how to set up UI and Worker threads for MFC based C++ application, please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8dd2e8-a55c-0459-f38b-f8c733a10dd5
* Version Independent ID: 4eb26d10-a308-2792-777a-7fc8df6c98f3
* Content: [Multithreading: Creating User-Interface Threads](https://docs.microsoft.com/en-us/cpp/parallel/multithreading-creating-user-interface-threads)
* Content Source: [docs/parallel/multithreading-creating-user-interface-threads.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/multithreading-creating-user-interface-threads.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@aaronstackpole Apologies for late response. Try including <afxwin.h>. If you create an MFC project in VS, it will create a "stdafx.h" header file for you. That files includes afxwin.h by default.
