### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SAINT-CHRIS** [MicrosoftDocs/cpp-docs#3110]
[Microsoft,you did not specify the ANSI standard update on the documentation,how can one know wherether this is an outdated documentation?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21945129-819f-b824-1448-7dcf82489dbb
* Version Independent ID: 4208a09f-059d-e29c-da34-6f37f12f2ca6
* Content: [Statements (C)](https://docs.microsoft.com/en-us/cpp/c-language/statements-c?view=msvc-160)
* Content Source: [docs/c-language/statements-c.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/statements-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SAINT-CHRIS 
Thanks for the question. Any reference to the ANSI standard specifically refers to the ANSI C89 standard. In some documentation we may also refer to the ISO standards ISO C99, ISO C11, or ISO C17. When something is unchanged in a newer standard, we don't update the standard referenced. I don't see a documentation issue to be addressed here, so I'm closing this.
