### ISSUE TITLE
C DOCUMENTATION

### ISSUE THREAD

**Issue by SAINT-CHRIS** [MicrosoftDocs/cpp-docs#3112]
[how would i know,whether this documentation has been updated?thank you,i love microsoft ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139d8805-bfe6-1aa7-c24f-f31afab77b43
* Version Independent ID: ff72cf3f-2332-aa0b-1fad-0ce6bfaf30d3
* Content: [C Language Reference](https://docs.microsoft.com/en-us/cpp/c-language/c-language-reference?view=msvc-160)
* Content Source: [docs/c-language/c-language-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/c-language-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SAINT-CHRIS 
There's a date just below the article title on every page in the C++ documentation on docs.microsoft.com. This date is either the date the documentation was last updated, or the date the documentation was ported from MSDN (usually early November 2016). The date is set manually for each page, and sometimes we forget to update it when we make a change, but it's a reasonable estimate for the last time a particular page has been touched. If you want more detail about what changed on a particular page, you can use the Edit control (it's an icon that looks like a pencil in the upper right of the page) to see the GitHub source for a page. From there you can look at the Blame listing, which shows who worked on which part the document, and when. I hope that answers your question. If not, feel free to ask for clarification.
