### ISSUE TITLE
How do we pass arguments to debug a project ?

### ISSUE THREAD

**Issue by RahulSisondia** [MicrosoftDocs/cpp-docs#312]
This is what I am trying to do once the build is completed on Linux box. 
1.  Right click on the executable in the solution explorer in VS and select  'Debug and launch settings" . 
2. That  opens a launch.vs.json file which has configurations JSON object corresponding to the project/binary I want to debug.  
3. I am unable to find out what property do I need to set in order to pass the argument before debugging the project.  Can someone help, please ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by RahulSisondia** [comment]
For the sake of completeness - 
What property has to be set in order to pass arguments to debug mysqld  process in the below configuration json ? 

"configurations": [
    {
      "type": "cppdbg",
      "name": "mysqld (\\runtime_output_directory\\mysqld)(2)",
      "project": "CMakeLists.txt",
      "projectTarget": "mysqld (\\runtime_output_directory\\mysqld)",
      "cwd": "${debugInfo.remoteWorkspaceRoot}",
      "program": "${debugInfo.fullTargetPath}",
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "${debugInfo.remoteMachineName}",
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}",
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}",
          "/p",
          "${debugInfo.parentProcessId}",
          "/c",
          "${debuggerCommand}",
          "--tty=${debugInfo.tty}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
  ]

**Comment by paulmaybee** [comment]
You need to specify the "args" element in your launch.vs.json, for example
      "args": ["one", "two", "three"]
will invoke you program with three parameters.

**Comment by RahulSisondia** [comment]
@paulmaybee   Thanks for the reply. I added the two arguments as following and expected them to retrieve in the main() method of the program but they were not passed to the main program.  Hope I am not missing something here.

"args": [
        "--port=15000",
        "--datadir=\"/work/trunk_datadir\""
      ],

**Comment by robotdad** [comment]
It may be a parsing issue with the second param try
"--datadir=/work/trunk_datadir"
or if you need the quotes passed
"--datadir=\"/work/trunk_datadir\""

**Comment by mikeblome** [comment]
@RahulSisondia is this working for you now?

**Comment by JonnyWaffles** [comment]
I tried the above solution with a simple C app, but the arguments were not passed to the executable.
