### ISSUE TITLE
Note about file seek altering stream read/write mode

### ISSUE THREAD

**Issue by Vineg** [MicrosoftDocs/cpp-docs#3124]
Hi! We've recently had an issue with file IO.
We've did a read / write operations on a file and used seekp and seekg as follows:
```
if (iostream.tellg() != position1) { iostream.seekg(position1); }
...do the reading
if (iostream.tellp() != position2) { iostream.seekp(position2); }
...do the writing
```
the problem I found is that seekg implicitly alters stream in read mode and if condition `stream.tellp() != position2` is not met - stream is remains in read mode and trying to write to it results in stream error without any description. Maybe it would be nice to have a note in the documentation about seekg / seekp modifying file stream read-write mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711d2223-7a8d-1054-89b3-69b5fa3bee0a
* Version Independent ID: 9009fe6b-9771-dd3a-672a-44dd639d153c
* Content: [Input Stream Member Functions](https://docs.microsoft.com/en-us/cpp/standard-library/input-stream-member-functions?view=msvc-160)
* Content Source: [docs/standard-library/input-stream-member-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/input-stream-member-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Vineg
Can you create a repro that demonstrates what you see? Your description doesn't match my expectation of stream behavior. If your stream has `ios_base::out` set before you call `seekg`, it should still be set after the call. There are lots of other reasons a write could fail, and you should check both `seekg` and `seekp` for failure. 

If the library behavior doesn't match the Standard, then I recommend creating a bug report on [Developer Community](https://aka.ms/vsfeedback/browsecpp).

**Comment by Vineg** [comment]
I don't currently have msvc nearby. We do check the stream for error right after seek like this:
```
if (!iostream)
	throw std::runtime_error("Stream error");
```
and it was OK. Error occured only on writing.
There is also was no issue when running the code on linux.

Removing condition `if (iostream.tellp() != position2)` for some reason fixed the problem.
I've wrongly interpret this as stream mode modification. Looking at the STL source it seems to be not the case as `seekpos` `openmode` value is ignored in basic_filebuf.
Sorry for wrong assumption.

Just in case, we compiled the project using visual studio 2015

**Comment by corob-msft** [comment]
@Vineg 
Thanks for the follow-up. Since this doesn't sound like a documentation bug, I'm closing the issue here.
