### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by mschifter** [MicrosoftDocs/cpp-docs#313]
what format is the color? RGB(r,g,b)?? What variable gets assigned? what else aren't you telling me here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268838a0-787f-78b1-2f55-588f31736cc6
* Version Independent ID: 76428f78-9cff-36f0-bf3d-79a7adee8e33
* Content: [Setting the Dialog Box’s Background Color](https://docs.microsoft.com/en-us/cpp/mfc/setting-the-dialog-boxs-background-color)
* Content Source: [docs/mfc/setting-the-dialog-boxs-background-color.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/setting-the-dialog-boxs-background-color.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @mschifter. Agreed that this topic is not very helpful. I added a link that shows how it's done. Fix should be visible on 07/13.
