### ISSUE TITLE
Missing list of possible Properties for a connection

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [MicrosoftDocs/cpp-docs#3133]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c2c4be-f5ec-2ba5-95bd-3ed46cf7a4fb
* Version Independent ID: fbbd166a-9b4c-900b-5600-8398242120d4
* Content: [ConnectionManager reference](https://docs.microsoft.com/en-us/cpp/linux/connectionmanager-reference?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/linux/connectionmanager-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connectionmanager-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by sinemakinci1** [comment]
@dmenendez-gruposantander  Can you clarify the scenario for the list of properties? list --properties provides the lists of properties for a connection, but these properties cannot be changed. However, there are some modifiable properties such as username, IsDefault, and shell.

**Comment by dmenendez-gruposantander** [comment]
I think I tried to use `list --properties` with no connections present.
I thought it might be helpful to have the list of properties explicitly listed in the documentation, so that you don't need to 1) `add` a connection and 2) `list --properties`, to get the list of properties.
To be honest, this was so long ago that I don't remember *what* I was trying to do, sorry for that.

**Comment by TylerMSFT** [comment]
Hi @dmenendez-gruposantander , I've added a list of common properties to the document, along with some examples of how to set them. Thank you for the suggestion. The doc updates should be live by end of day 3/16/2022
