### ISSUE TITLE
How to copy source directory?

### ISSUE THREAD

**Issue by wwc7654321** [MicrosoftDocs/cpp-docs#3135]
How to specify copy directory ?   localpath:=remotepath  only works when path is a file, not work if it's a directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8e98d3-1826-922e-b4fd-18bdaa5d44a8
* Version Independent ID: 387b1b26-43a3-1069-9d80-1ce39c58ecb7
* Content: [Copy Sources Project Properties (Linux C++)](https://docs.microsoft.com/en-us/cpp/linux/prop-pages/copy-sources-project?view=msvc-160)
* Content Source: [docs/linux/prop-pages/copy-sources-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/prop-pages/copy-sources-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by sinemakinci1** [comment]
Currently, there is no support for this. We can work on prioritizing this and update once complete.
