### ISSUE TITLE
Documentation for /analyze does not mention .sarif output

### ISSUE THREAD

**Issue by exjam** [MicrosoftDocs/cpp-docs#3136]
Given this blog post[1] I read today, I went searching for a way to generate .sarif log files from /analyze through cl.exe, unfortunately the documentation[2] does not mention how to do this and neither does the blog post. I figured it out myself by spying on visual studio, but the documentation should probably be updated to add this?

It seems the existing /analyze:log option is used but you just need to specify a filename with a .sarif extension e.g.
`/analyze:logfilename.sarif`

1. https://devblogs.microsoft.com/cppblog/microsoft-c-code-analysis-supports-sarif-2-1/
2. https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/build/reference/analyze-code-analysis.md

**Comment by corob-msft** [comment]
@exjam 
You're in luck, we're working on updates to the [`/analyze`](https://docs.microsoft.com/cpp/build/reference/analyze-code-analysis?view=msvc-160) docs now, and they should be live by early next week. Starting in Visual Studio 2019 version 16.9, the command to make all your code analysis logs use SARIF format is `/analyze:log:format:sarif`, along with whatever other analysis options you need.

Also, it's a lot easier to read the docs on our production site, [docs.microsoft.com/cpp](https://docs.microsoft.com/cpp). It formats things correctly, gives you access to the table of contents, and makes it easy to create feedback linked directly to the topic.
