### ISSUE TITLE
`<filesystem>` long path support

### ISSUE THREAD

**Issue by StephanTLavavej** [MicrosoftDocs/cpp-docs#3138]
ISO paper for this feature: [P0218R1](https://wg21.link/P0218R1)
First implemented in: VS 2017 15.7
Overall doc issue for `<filesystem>`: #2771

See https://github.com/microsoft/STL/issues/1921 for user questions about `<filesystem>`'s long path support that aren't answered by the current docs. I believe that the important things to document are:

* `<filesystem>` works with long paths, if and only if OS support is enabled
* `<experimental/filesystem>` never works with long paths - it's deprecated, will be removed, and we strongly discourage its use
* Long path support is unrelated to UNC path support; UNC paths are expert-only and should not be used by people who simply want long path support
* An example of long path support

**Comment by TylerMSFT** [comment]
Moved to quest for work tracking
