### ISSUE TITLE
Targetting Windows 7

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/cpp-docs#314]
It's not obvious whether you need to select 8.1 for an application to run on Windows 7/8.1.
For instance, can you select SDK 10.xxxx and the application still run on Windows 7 if you don't use any new SDK features... or can the compiler automatically use newer Windows features and so it is only safe to select 8.1?

E.g "This version [the default 10.x] of the Windows SDK is compatible with all recent Windows releases".  Ok.... well 7 is pretty recent. It's not say 3.1.  So can we leave it at 10 and run on 7? 

Please add some more clarification as to what options are permissible or required.  Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a35bc2-4bae-9562-e954-d90324105997
* Version Independent ID: 6aeca9d8-d1d8-9026-918a-7ca47ac3dead
* Content: [How to: Use the Windows 10 SDK in a Windows Desktop Application](https://docs.microsoft.com/en-us/cpp/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application)
* Content Source: [docs/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @pilcherd . Fix should be visible on 07/13.
