### ISSUE TITLE
Mixed UTF-8 codepage names

### ISSUE THREAD

**Issue by uecasm** [MicrosoftDocs/cpp-docs#3147]
In the "UTF-8 Support" section, it says to use "UTF-8" (with hyphen) as the codepage name, and then goes on to provide two examples of usage, neither of which use the hyphen and which differ between themselves in case.  Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160#utf-8-support)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @uecasm, I've clarified the topic to indicate that there are several ways to specify this string. The changes should be live 6/10. 

The UTF-8 string is:
- case-insensitive
- the hypen (-) is optional
- It must be in the code page part of the locale name, so must have a leading period '.'  For example, `"en_US.UTF8"` or `".utf8"`

The following are examples of ways to specify the UTF-8 string:

`".UTF8"`\
`".UTF-8"`\
`".utf8"`\
`".utf-8"`\
`"en_us.utf8"`\
`"ja_JP.Utf-8"`
