### ISSUE TITLE
This solution assumes  that the assemblies that are to be referenced are installed in a specific directory.

### ISSUE THREAD

**Issue by CateyeStrike** [MicrosoftDocs/cpp-docs#3148]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a872d6ff-6c5f-ebfb-c9ef-a56c1679d61d
* Version Independent ID: e8a0339d-1645-1253-4340-283dc960dad5
* Content: [Compiler Error C3624](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3624?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C3624)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c3624.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c3624.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as covered by #3149.
