### ISSUE TITLE
This solution does not cover the scenario where NuGet packages are being used

### ISSUE THREAD

**Issue by CateyeStrike** [MicrosoftDocs/cpp-docs#3149]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a872d6ff-6c5f-ebfb-c9ef-a56c1679d61d
* Version Independent ID: e8a0339d-1645-1253-4340-283dc960dad5
* Content: [Compiler Error C3624](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3624?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C3624)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c3624.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c3624.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CateyeStrike** [comment]
This example shown assumes that the assemblies are in the system path  (as implied by the the angled brackets <>)

If the user is using NuGet packages the assemblies can be held in a packages directory which can be in different places depending upon the solution involved.

How do you handle this?

**Comment by corob-msft** [comment]
@CateyeStrike 

The assumption implicit in the use of angle brackets is only that the assemblies are located somewhere in the *include* path, which is a safe assumption for `System` assemblies. 

You can [use double-quotes in your `#using` directives](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-using-directive-cpp?view=msvc-160), and you can also specify absolute or relative paths to your assemblies inside the double-quotes. That info is way outside of the scope of this particular error example, though, so I'm not inclined to add it here. However, a link to the `#using` doc might be useful.
