### ISSUE TITLE
Documentation for  IcmpSendEcho

### ISSUE THREAD

**Issue by HPaulS** [MicrosoftDocs/cpp-docs#315]
We (*) have determined by experiment that the documentation for the `IcmpSendEcho` family of functions (e.g. https://docs.microsoft.com/en-gb/windows/desktop/api/Icmpapi/nf-icmpapi-icmpsendecho) is way wrong on 64 bit Windows.  The references to `ICMP_ECHO_REPLY32` are incorrect and should be removed.

Or am I missing something?

(*) Please see https://stackoverflow.com/questions/51087679/winapi-icmpsendecho-on-64-bit-platform, and my answer there.

**Comment by mikeblome** [comment]
@HPaulS Thanks for the feedback. I have forwarded it to the doc owners for this API for further investigation.

**Comment by HPaulS** [comment]
@mikeblome Thank you, much appreciated.  I found the whole thing a bit weird, to be honest.

**Comment by mikeblome** [comment]
@mcleblanc Any update?

**Comment by stevewhims** [comment]
Thanks for pointing out this issue to us, @HPaulS! We've now resolved the issue. The topics fixed are: [IcmpSendEcho function](https://docs.microsoft.com/windows/desktop/api/Icmpapi/nf-icmpapi-icmpsendecho
), [IcmpSendEcho2 function](https://docs.microsoft.com/windows/desktop/api/Icmpapi/nf-icmpapi-icmpsendecho2), and [IcmpSendEcho2Ex function](https://docs.microsoft.com/windows/desktop/api/Icmpapi/nf-icmpapi-icmpsendecho2ex). ~Steve
