### ISSUE TITLE
ec explanation

### ISSUE THREAD

**Issue by nickledeg** [MicrosoftDocs/cpp-docs#3153]
After a quick skim of the document, it is not obvious to me what the values of the error code (ec) are likely to be.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4e66b74-13dd-eab7-a68b-b76e266adbe7
* Version Independent ID: 35b6cc52-be26-e9d0-2c27-56c6a5adcba8
* Content: [&lt;filesystem&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem-functions?view=msvc-160)
* Content Source: [docs/standard-library/filesystem-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/filesystem-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
