### ISSUE TITLE
Source code line numbers are missing and furthermore, some references to line numbers in the text are incorrect.

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/cpp-docs#3154]
Under "Declarations and definitions (C++)" in the C++ language reference, there is example source code near the beginning of the page. The text which follows the example refers to line numbers in the source code. But:
(a) the source code doesn't actually contain any line numbers, and
(b) even if mentally ascribing numbers to each line of code, the line references in the text do not match the order of lines in the source code.
For example, in the text, declarations for the variables obj and str refer to lines 9 and 10 respectively, yet they are declared in the reverse order (on lines 10 and 9) in the example source code..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d334fd48-9c18-fac4-b871-b75143c1a321
* Version Independent ID: b3bf7dfc-8c5d-0524-4eee-e5af07bcb9ae
* Content: [Declarations and definitions (C++)](https://docs.microsoft.com/en-us/cpp/cpp/declarations-and-definitions-cpp?view=msvc-160)
* Content Source: [docs/cpp/declarations-and-definitions-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/declarations-and-definitions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed.
