### ISSUE TITLE
STAT= [(MEAN/MEAN)] --Ğ [(SD/SD)]

### ISSUE THREAD

**Issue by Yeliz7889** [MicrosoftDocs/cpp-docs#3155]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e042d512-2b0b-d37e-b2ec-ef1c157590db
* Version Independent ID: df44eb21-c7d4-6722-2863-3bce67b9527f
* Content: [Understanding the Dependencies of a Visual C++ Application](https://docs.microsoft.com/en-us/cpp/windows/understanding-the-dependencies-of-a-visual-cpp-application?view=msvc-160)
* Content Source: [docs/windows/understanding-the-dependencies-of-a-visual-cpp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/understanding-the-dependencies-of-a-visual-cpp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Yeliz7889 
This doesn't appear to be an actionable issue, or even to make sense. Can you tell me why this issue should not be deleted as spam?
