### ISSUE TITLE
enhancement / typo

### ISSUE THREAD

**Issue by seedkar1** [MicrosoftDocs/cpp-docs#3158]
A 'typo' in file.
attached patch file for 
commit id: f34f9b4a3c4a6f2bb37c66bc5e6d0adece644b59
[algorithm-functions.md.patch.txt](https://github.com/MicrosoftDocs/cpp-docs/files/6535022/algorithm-functions.md.patch.txt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2345d5-8891-8d5d-5a8c-b7b4382d4541
* Version Independent ID: 03684e91-dbcd-5acc-b86d-7099dac5b473
* Content: [&lt;algorithm&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/algorithm-functions?view=msvc-160)
* Content Source: [docs/standard-library/algorithm-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/algorithm-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@seedkar1 
This looks fine. I'll suggest you go even further and [create a PR with this change](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents).

**Comment by corob-msft** [comment]
Thanks for the fix in PR #3168.
