### ISSUE TITLE
The final example is slightly unclear, and invokes undefined behavior

### ISSUE THREAD

**Issue by ubsan** [MicrosoftDocs/cpp-docs#316]
The actual issue is not that the dtor isn't called, but that the dtor isn't called _and_ the memory it lives in is freed. A more clear example, which doesn't invoke UB but still crashes, might be

```cpp
int main() {
  auto vect = std::vector<int>(10);
  auto sink = new auto(std::begin(vect));
  ::operator delete(sink); // frees the memory without calling ~iterator()
} // access violation
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c200cd0a-85db-45ed-8e50-2a5f563d3156
* Version Independent ID: d43ff7d9-9c13-7eb3-88e6-c0221a5e8a80
* Content: [Debug Iterator Support](https://docs.microsoft.com/en-us/cpp/standard-library/debug-iterator-support)
* Content Source: [docs/standard-library/debug-iterator-support.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/debug-iterator-support.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @ubsan. I have updated the example with your suggestion. Should be visible 07/12.
