### ISSUE TITLE
update for VS 16.10.0

### ISSUE THREAD

**Issue by PaulTopping** [MicrosoftDocs/cpp-docs#3164]
VS 16.10.0 includes support for P0645R10 <format> Text Formatting but it isn't mentioned on this page. I'm interested to know its status. Is it fully implemented? Are there pieces missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C++ language and standard library conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@PaulTopping 
Some product features have come in hot, and the 16.10 doc updates aren't all ready to be published yet. We'll have updates to this particular page next week. You can also expect a [C++ team blog](https://devblogs.microsoft.com/cppblog/) post about `<format>` support in the next week or so. For details on what's implemented, you can check the [status of the project on GitHub](https://github.com/microsoft/STL/projects/5) and correlate it to the release. This is apparently an area of active standardization development, with some LWG Defect Reports coming in that will affect C++20 implementations, so expect changes to continue in the future.
