### ISSUE TITLE
UTF-BOM doesn't affect execution-character-set but document mention it.

### ISSUE THREAD

**Issue by leozzyzheng** [MicrosoftDocs/cpp-docs#3165]
The remark in this page says:

> By default, Visual Studio uses the current code page as the source character set used to interpret your source code for output. When a file is read in, Visual Studio interprets it according to the current code page unless the file code page was set, or unless a byte-order mark (BOM) or UTF-16 characters are detected at the beginning of the file. 

After a quick test on my machine, the current code page is GB2312 which is CP936, here is a screenshot:
![image](https://user-images.githubusercontent.com/6134295/119930618-5967f080-bfb2-11eb-8b57-7bbd3c1e5ac2.png)
There is only one file in my win32 console application and it's UTF8-BOM encoded. Compile the code gives me no warning about unicode so I think the `source-charset-set` is set to utf-8. But the Chinese string is encoded as GB2312 in memory at runtime. So I believe BOM has no effect to `execution-character-set`.

If I'm right, I think the remark I quoted is something will mislead users think the BOM will have effect on `execution-character-set`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cab952c-9cec-18ed-7ae0-7dc82f0d0c2f
* Version Independent ID: be2542ed-2565-53ab-c155-581ba2042ff3
* Content: [execution_character_set pragma](https://docs.microsoft.com/en-us/cpp/preprocessor/execution-character-set?view=msvc-160)
* Content Source: [docs/preprocessor/execution-character-set.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/execution-character-set.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/8/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
