### ISSUE TITLE
capture v by reference in example code

### ISSUE THREAD

**Issue by albumcover** [MicrosoftDocs/cpp-docs#317]
for_each(v.begin(), v.end(), [v,i] (shared_ptr&lt;Controller&gt; p)

Here  vector v should be captured  by reference rather than by value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c879eb4-3a94-9968-63b1-1f4519ce11f8
* Version Independent ID: ae94388e-d305-321f-763d-f864aa7ecc32
* Content: [How to: Create and Use weak_ptr Instances](https://docs.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-weak-ptr-instances)
* Content Source: [docs/cpp/how-to-create-and-use-weak-ptr-instances.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/how-to-create-and-use-weak-ptr-instances.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @albumcover . Fix should be visible on 7/13.
