### ISSUE TITLE
SHARE_INFO_502  giving share permission to my folder but removing the user if added newer one

### ISSUE THREAD

**Issue by Medhawee** [MicrosoftDocs/cpp-docs#3175]
Hi Team, 
I am using SHARE_INFO_502 in my code to give sharing permission to a folder with access all for that particular user which it is giving after adding the NetShareAdd and as it was having duplicate share name so for that added NetShareGetInfo, after that the permission was successful in Sharing folder but when I am going to add new user, the previous user is getting removed and the newer user gets added with all permission.
Please help with the data which I need to pass on.
Thankyou in advance.

**Comment by corob-msft** [comment]
@Medhawee 
I appreciate your difficulty, and it's unfortunate that this isn't the right place to find help. We track issues in the [Microsoft C++ documentation](https://docs.microsoft.com/cpp/) here. We can't provide general technical support. If your question relates to a Microsoft product, you may have better results if you ask in the [Microsoft Docs Q&A](https://docs.microsoft.com/answers/products/) forums. Best of luck!
