### ISSUE TITLE
/external:* options is no longer experimental as of 16.10

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/cpp-docs#3181]
We should update the online document to reflect the behavior of the latest compiler behavior for /external:* options. AFAIK, /external:* options are no longer experimental, but this page still mentioned that as a requirement for /external:* options. It would be helpful if this is cleaned up to reflect the updated behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d17b537f-8093-16f6-e52f-b83cf4fc5c6f
* Version Independent ID: 6b66bc39-47d6-a2da-bb84-bab42702e925
* Content: [/external (External headers diagnostics)](https://docs.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics?view=msvc-160)
* Content Source: [docs/build/reference/external-external-headers-diagnostics.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/external-external-headers-diagnostics.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
The update is queued and should appear by tomorrow afternoon.
