### ISSUE TITLE
Tutorial did not work for me.

### ISSUE THREAD

**Issue by Thomas-Tran-UMKC** [MicrosoftDocs/cpp-docs#3189]
After researching more about .dll and following other instructions, I tried to follow this page after the others did not work. While the instructions are the same as other unofficial sources, it still did not work after I followed these instructions. 
I eventually just included each file into my project as a temporary fix.
Visual Studio 2019 16.10.1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-160)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Thomas-Tran-UMKC 
I'm afraid I can't fix "it still did not work" without some detailed information. I need to know what errors or failures you saw as you went along, and which steps you completed before the problems occurred. Thousands of people have followed this tutorial successfully, so there probably isn't a problem with the underlying procedure. We might be able to do a better job of explaining it, though.

**Comment by corob-msft** [comment]
Closing as not actionable without information.
