### ISSUE TITLE
Link to how to do this in C++/CX?

### ISSUE THREAD

**Issue by JBradon** [MicrosoftDocs/cpp-docs#319]
I'd like to use delegates in my application but "using namespace System;" doesn't work for me in a UWP app in Visual Studio 2017. I think this is because it uses C++/CX not C++/CLR. I'd appreciate any link or reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a1b63d-d227-382f-4140-e3a6ab23fbd7
* Version Independent ID: 6ff009ab-671f-f550-08ae-918449994ca4
* Content: [How to: Define and Use Delegates (C++/CLI)](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-define-and-use-delegates-cpp-cli)
* Content Source: [docs/dotnet/how-to-define-and-use-delegates-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-define-and-use-delegates-cpp-cli.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Hi, @JBradon -

This sounds like a support question, and not an issue with defining and using delegates in C++/CLI. A bit of searching will probably find what you want to know. For example, if you use the C++/WinRT library, then I'd recommend the article [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events). If you prefer to stick with C++/CX, then check out [Delegates (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/delegates-c-cx). Remember you're using WinRT, not .NET, so you're going to find events and handlers to delegate in the Platform namespace or one of the Windows::Foundation namespaces, not in System.

Closing as not actionable in this document.
