### ISSUE TITLE
Remove use of std::endl

### ISSUE THREAD

**Issue by Chris-Bond** [MicrosoftDocs/cpp-docs#3194]
Just output a newline. It's 2021. You're potentially teaching bad habits with std::endl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create a CMake Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=msvc-160)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I agree. Adding this to my queue.

**Comment by NegiAkash890** [comment]
Hi,  I can fix this one!

**Comment by TylerMSFT** [comment]
@NegiAkash890, that'd be awesome. Thank you!

**Comment by corob-msft** [comment]
Closing as fixed by #3215
