### ISSUE TITLE
__RTDynamicCast Required header wrong

### ISSUE THREAD

**Issue by Iamgublin** [MicrosoftDocs/cpp-docs#3195]
__RTDynamicCast Required header is rttidata.h now Instead of rtti.h.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362bb528-acc9-cd79-6814-75501b96da68
* Version Independent ID: 0d32c539-ec93-4e20-5006-d7a1a5a4354d
* Content: [__RTDynamicCast](https://docs.microsoft.com/en-us/cpp/c-runtime-library/rtdynamiccast?view=msvc-160)
* Content Source: [docs/c-runtime-library/rtdynamiccast.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/rtdynamiccast.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you. Adding to my queue to fix.

**Comment by TylerMSFT** [comment]
Fixed - thank you for pointing that out. The fix will go out tomorrow afternoon (Fri)
