### ISSUE TITLE
Possible Error in "RandRangeDemo" function

### ISSUE THREAD

**Issue by Al-B-Bach** [MicrosoftDocs/cpp-docs#3202]
While trying to learn about the "rand" function for C, came across a possible
error with the example function "RandRangeDemo."

Function appears to be producing a result which is 
```
-1 * [range_min, range_max)
```
rather than the intended result of 
```
[range_min, range_max)
```
I believe this to be due to this line of code:
```
int u = (double)rand() / (RAND_MAX + 1) * (range_max - range_min)+ range_min;
```
" (RAND_MAX+1) " appears to be causing an integer overflow or some other similar effect.
Testing appears to show that to achieve the intended result, the line should be
changed to " (RAND_MAX - 1) ."

In full, the line (with the suggested change) would read:
```
int u = (double)rand() / (RAND_MAX - 1) * (range_max - range_min)+ range_min;
```
Here is a link to the page in which I did the testing:

[Link to test of Example Implementation](http://pythontutor.com/cpp.html#code=%23include%20%3Ciostream%3E%0A%23include%20%3Cstdlib.h%3E%0A%0A//https%3A//docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand%3Fview%3Dmsvc-160%0Aint%20MicrosoftRandRange_Incorrect%28int%20range_min,%20int%20range_max%29%0A%7B%0A%20%20int%20u%20%3D%20%28double%29rand%28%29%20/%20%28RAND_MAX%20%2B%201%29%20*%20%28range_max%20-%20range_min%29%0A%20%20%20%20%20%20%20%20%20%20%2B%20range_min%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20return%20u%3B%0A%7D%0A%0Aint%20MicrosoftRandRange_Corrected%28int%20range_min,%20int%20range_max%29%0A%7B%0A%20%20int%20u%20%3D%20%28double%29rand%28%29%20/%20%28RAND_MAX%20-%201%29%20*%20%28range_max%20-%20range_min%29%0A%20%20%20%20%20%20%20%20%20%20%2B%20range_min%3B%20%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20return%20u%3B%0A%7D%0A%0Aint%20main%28%29%20%0A%7B%0A%20%20srand%2893%29%3B%20//%20Determined%20via%20random%20roll%20on%202d10%0A%0A%20%20std%3A%3Acout%3C%3C%22Incorrect%20%5B0-10%5D%20%28x20%29%3A%20%5Cn%22%3B%0A%20%20for%28int%20i%20%3D%200%3B%20i%3C20%3Bi%2B%2B%29%0A%20%20%7B%0A%20%20%20%20std%3A%3Acout%3C%3CMicrosoftRandRange_Incorrect%280,10%29%3C%3C%22%5Cn%22%3B%0A%20%20%7D%0A%20%20%0A%20%20std%3A%3Acout%3C%3C%22%5CCorrected%20%5B0-10%5D%20%28x20%29%3A%20%5Cn%22%3B%0A%20%20for%28int%20i%20%3D%200%3B%20i%3C20%3Bi%2B%2B%29%0A%20%20%7B%0A%20%20%20%20std%3A%3Acout%3C%3CBreakDown%280,10%29%3C%3C%22%5Cn%22%3B%0A%20%20%7D%0A%0A%20%20return%200%3B%0A%7D&mode=edit&origin=opt-frontend.js&py=cpp_g%2B%2B9.3.0&rawInputLstJSON=%5B%5D)

I hope this helps resolve this error, and I wish you all a pleasant day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29a1829-6726-2b46-a3f1-647732a81083
* Version Independent ID: 7f066cc1-c72e-3b2d-1453-9b420e0afab9
* Content: [rand](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/rand.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/rand.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @Al-B-Bach (great user name :-)
I didn't reproduce your problem, but updated the sample to remove the +1. What I think that's about is an attempt to lessen the bias of not selecting the highest value in the range. This approach is fraught with problems:
- rand() is low quality and has a small output range, which means that it isn't suitable for generating values across a large range.
- using srand() to seed with time(nullptr) has multiple problems, including introducing data loss when converting from the time_t to the unsigned int taken by srand(), and the fact that if you run this twice within the period of a second, the seed will be the same.
- using the formula in this sample will result in a non-uniform distribution. 
For more info about these issues, I recommend this talk: [rand() considered harmful](https://channel9.msdn.com/Events/GoingNative/2013/rand-Considered-Harmful). If you must use the CRT library rand() function, I'm not aware of anything better. But if you can use the C++ library <random> functions, you'll be better off if you need high quality random numbers.  Here's an example of how you could do it with that library:
```cpp
#include <iostream>
#include <random>

int main() {
    std::random_device rd; // cryptographically secure (in MSVC's implementation)
    const unsigned int seed = rd(); // 32-bit seed; production usage may need more entropy

    // A fresh seed is generated every time this program runs.
    // This is better than calling time(nullptr).

    std::mt19937 engine{seed}; // fast, but not cryptographically secure; know the difference for production usage

    // Calling engine() directly will generate a random 32-bit value.
    // We should NOT use the modulo operator (the % operator) to transform this to a desired range,
    // as that will produce biased results (some values will be more likely than others).
    // Instead, std::uniform_int_distribution will produce uniform results (all values equally likely).

    std::uniform_int_distribution<int> d20{1, 20}; // we want values 1 through 20, inclusive

    // Now we can simply call d20(engine) to use the engine and the distribution object together:

    std::cout << "Rolling a 20-sided die: ";

    for (int i = 0; i < 50; ++i) {
        std::cout << d20(engine) << ", ";
    }

    std::cout << "done!\n";
}
```
The update I made to the topic should be live by the weekend. Closing now.
