### ISSUE TITLE
On the `/F (Set Stack Size)` page, the /STACK hyperlink points to the EDITBIN option instead of the linker option

### ISSUE THREAD

**Issue by jagunter** [MicrosoftDocs/cpp-docs#3205]
> Using the /STACK linker option. For more information, see [/STACK](https://docs.microsoft.com/en-us/cpp/build/reference/stack?view=msvc-160).

The quoted link points to the EDITBIN `/STACK` option, but the surrounding context makes it clear the intent is to link to the linker option. The correct link should be https://docs.microsoft.com/en-us/cpp/build/reference/stack-stack-allocations?view=msvc-160 which is the reference for the `/STACK` linker option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6298fd-5773-69eb-c9e0-0c496310b537
* Version Independent ID: b3d903ea-1584-f503-8079-94e87b432c8a
* Content: [/F (Set Stack Size)](https://docs.microsoft.com/en-us/cpp/build/reference/f-set-stack-size?view=msvc-160)
* Content Source: [docs/build/reference/f-set-stack-size.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/f-set-stack-size.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jagunter 
Good catch. Since EDITBIN is really the linker in disguise, it's not a different command, but the context does matter.

**Comment by corob-msft** [comment]
Closing as fixed.
