### ISSUE TITLE
The docs is out of date, it describes the behavior of Visual Studio 2017, not 2019

### ISSUE THREAD

**Issue by AllenZz** [MicrosoftDocs/cpp-docs#3209]
Please refer to the docs: https://docs.microsoft.com/en-us/cpp/build/reference/qspectre?view=msvc-160#required-libraries.

_If you build your code by using /Qspectre and these libraries aren't installed, the build system reports **warning MSB8038**: Spectre mitigation is enabled but Spectre mitigated libraries are not found. If your MFC or ATL code fails to build, and the linker reports an error such as fatal error LNK1104: cannot open file 'oldnames.lib', these missing libraries may be the cause._

The description in the docs is the behavior of VS2017, not VS2019. Need to change the docs description to be consistent with VS2019 behavior.

VS 2017:
![image](https://user-images.githubusercontent.com/69228135/122520265-3e443b80-cfc8-11eb-8a9c-0d27aa1de8e7.png)

VS 2019:
![image](https://user-images.githubusercontent.com/69228135/122520492-819eaa00-cfc8-11eb-8826-57bf6baed7ca.png)

Thanks,
Allen
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad87698-8cd7-aaf9-87b1-eaf8c290017f
* Version Independent ID: be796703-261a-ec99-11e6-d023aa7ee849
* Content: [/Qspectre](https://docs.microsoft.com/en-us/cpp/build/reference/qspectre?view=msvc-160)
* Content Source: [docs/build/reference/qspectre.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/qspectre.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as fixed.
