### ISSUE TITLE
Minor error in comment about _Static_assert

### ISSUE THREAD

**Issue by daira** [MicrosoftDocs/cpp-docs#3212]
```
// Preferred: static_assert maps to _Static_Assert and is compatible with C++
```
This should be:
```
// Preferred: static_assert maps to _Static_assert and is compatible with C++
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e261e6-9001-6a5f-ce96-f73809a47d6e
* Version Independent ID: baf3ef9a-404c-945b-dba3-af7a9ad580ff
* Content: [_Static_assert keyword and static_assert macro (C11)](https://docs.microsoft.com/en-us/cpp/c-language/static-assert-c?view=msvc-160)
* Content Source: [docs/c-language/static-assert-c.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/static-assert-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as fixed.
