### ISSUE TITLE
Compiler Error C2208 with Including files with macros that exists as variable names in the winioctl.h

### ISSUE THREAD

**Issue by Mohido** [MicrosoftDocs/cpp-docs#3213]
I had this weird problem when I was trying to include some file that I created. Note that: It has the macro 'Geometry' defined to it. 
Anyway, the error "winioctl.h(8591,31): error C2208: '_DISK_GEOMETRY': no members defined using this type" kept showing on the stdout. Therefore, I wanted to note that the page that describe that error is not totally complete in describing the error and there might be some behaviors when trying to include a file with some macro defined to it. Anyways, I changed the name of the macro in the included file and it worked fine. So if possible can you add more information to that page (for example the thing I mentioned above). To whoever reading..... Have a nice day :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a55bca-c288-1142-2030-c47c68432f98
* Version Independent ID: 46f9acd6-6f21-630b-83b9-a6c71d2a908e
* Content: [Compiler Error C2208](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2208?view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2208.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2208.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Mohido 
Thanks, I appreciate that you've taken the time to comment here. However, I can't tell what's distinctive about your experience. The compiler reports what it sees at the point it finds a problem. If a macro causes a name collision that resolves to a type name in an aggregate where the compiler expects a declaration, that isn't a different way to cause the error. That's just one of an untold number of ways for buggy code to cause the error. I'm sorry that we can't afford the time to describe more than one or two of the many ways it could happen. So, I'm closing your issue.
