### ISSUE TITLE
this is my problem

### ISSUE THREAD

**Issue by lmx-superdino** [MicrosoftDocs/cpp-docs#322]
using namespace std;
#include&lt;iostream&gt;
namespace a 
{
	int b = 2;
}
namespace b
{
	int b = 3;
}
int main()
{
	
	cout &lt;&lt; b;
	   system("pause"); 
   return 0;
	Severity	Code	Description	Project	File	Line	Suppression State
Error	C2882	'b': illegal use of namespace identifier in expression	ConsoleApplication1	c:\users\lmx—computer\source\repos\consoleapplication1\consoleapplication1\consoleapplication1.cpp	18	

}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79831af-f3d9-e70a-56aa-4b4b1b9f01a7
* Version Independent ID: b49b5127-f9bc-6bb2-267f-0432a5feb6e2
* Content: [Compiler Error C2882](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2882?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2882)%26rd%3Dtrue)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2882.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c2882.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @lmx-superdino  - 

Can you be a little more specific about what you think is wrong with the documentation? The only thing named "b" in scope in your cout expression is the namespace, and you can't use the name of a namespace in an expression, just as the documentation says.

**Comment by lmx-superdino** [comment]
thank you !
