### ISSUE TITLE
Wrong description of RFX_Int_Bulk method

### ISSUE THREAD

**Issue by Nijegorodov** [MicrosoftDocs/cpp-docs#3224]
The Syntax, Parameters, Example are wrong for this method:
https://docs.microsoft.com/en-us/cpp/mfc/reference/record-field-exchange-functions?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(AFXDB%252FRFX_Bool_Bulk)%3Bk(RFX_Bool_Bulk)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=msvc-160#rfx_int_bulk

The correct method sibnature is (from "afxdb.h"):
void AFXAPI RFX_Int_Bulk(CFieldExchange* pFX, 
                                          LPCTSTR szName,
	                                  int** prgIntVals, 
                                          LONG_PTR** prgLengths);

However on this page it was claimed to be:
void RFX_Int(
   CFieldExchange* pFX,
   const char* szName,
   int& value);
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86180f3c-74b9-f064-223d-be5cc951645e
* Version Independent ID: 70063971-e2fa-bfcf-a28a-dae8a0645580
* Content: [Record Field Exchange Functions](https://docs.microsoft.com/en-us/cpp/mfc/reference/record-field-exchange-functions?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(AFXDB%252FRFX_Bool_Bulk)%3Bk(RFX_Bool_Bulk)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=msvc-160#rfx_int_bulk)
* Content Source: [docs/mfc/reference/record-field-exchange-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/record-field-exchange-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
