### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by jdekeij** [MicrosoftDocs/cpp-docs#3226]
[Enter feedback here]

Most of the function descriptions end with the required header file and in which static library the function sits. On this page this is not defined. Please add for consistency the library- and header file name for ease of use when the linker option /NODEFAULTS is defined in the build process.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dc580a-fc4a-6a2a-bdfc-d52fc7b24f00
* Version Independent ID: 6047a186-0908-915a-0f35-c4b3e3f1b199
* Content: [snprintf, _snprintf, _snprintf_l, _snwprintf, _snwprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @jdekeij, can you point me to an example of listing which static library the function resides in? I looked at several topics and didn't see that.

As for the header file, it's listed in the requirements section as we do for our other topics (search for <stdio.h> and you'll find the section)

**Comment by TylerMSFT** [comment]
Closing as I don't see the issue. Please reopen if I am in error.
