### ISSUE TITLE
Misleading statement in Capture Clause subsection of Parts of a Lambda Expression section in Lambda Expressions in C++

### ISSUE THREAD

**Issue by divyanshu14** [MicrosoftDocs/cpp-docs#3227]
In **Capture Clause** subsection of **Parts of a Lambda Expression** section, the following statement is written.

_Only variables that are mentioned in the lambda are captured when a capture-default is used._

This statement is completely wrong. When a capture-default is used, all variables in the surrounding scope are captured using the default capture, unless opposite mode is explicitly used for specific variables in the Capture Clause.

Consider changing the statement to the following.

_Only variables that are mentioned in the lambda are captured when a capture-default is **not** used._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 437be494-4752-c2de-a8c0-c4bc8563ddb4
* Version Independent ID: 51317bb8-4c01-146a-f1a7-eba0e54cb5e4
* Content: [Lambda Expressions in C++](https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-160)
* Content Source: [docs/cpp/lambda-expressions-in-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/lambda-expressions-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hmm, I don't know where my comment went that asked for clarification. I'll try to recreate it:

@divyanshu14 
I don't understand your objection or your suggested correction. I could clarify the statement as follows:

> Only variables that are mentioned in the lambda body are captured when a capture-default is used.

This represents the intent of the sentence. It's not trying to say anything about the variables listed explicitly in the capture clause, it's trying to say that locals that aren't referenced in the lambda body aren't captured by a capture-default. Does this differ from the standard?

**Comment by divyanshu14** [comment]
You are right @corob-msft . I mistook "variables that are mentioned in the lambda" as "variables that are mentioned in the capture clause". Thanks for the clarification.

However, I would suggest to change the word "lambda" to "lambda body" for more clarity, since "lambda" can mean the entire lambda expression as well. Even in the **Parts of a Lambda Expression** section of the doc, the sixth part is called the "lambda body" and not simply the "lambda".

**Comment by corob-msft** [comment]
An update with clarification is in the publishing pipeline and should appear tomorrow.
