### ISSUE TITLE
Where is NULL defined?

### ISSUE THREAD

**Issue by Pekka-Kalevi** [MicrosoftDocs/cpp-docs#3233]
Microsoft document incorrectly state that:

"NULL is defined in the following header files: CRTDBG.H, LOCALE.H, STDDEF.H, STDIO.H, STDLIB.H, STRING.H, TCHAR.H, TIME.H and WCHAR.H."

NULL is actually defined in the following header file:

 "C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\CORECRT.H"

File: corecrt.h Line: 244, 248

#ifndef NULL
    #ifdef __cplusplus
        #define NULL 0
    #else
        #define NULL ((void *)0)
    #endif
#endif

Those named header files just include <corecrt.h>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2325582b-6542-6543-b8f4-e00b089d8f85
* Version Independent ID: 98054d7c-13d0-926c-8307-2fb0b80ac5b6
* Content: [NULL (CRT)](https://docs.microsoft.com/en-us/cpp/c-runtime-library/null-crt?view=msvc-160)
* Content Source: [docs/c-runtime-library/null-crt.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/null-crt.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Pekka-Kalevi 
The list of files isn't correct, so your point is taken. For UCRT headers, the first definition of `NULL` encountered by the compiler is found in *`vcruntime.h`*, which is included by *`corecrt.h`*, and which in turn is directly or indirectly included by every other UCRT header file. If you press F12 on an instance of `NULL` in the IDE, that's probably where you'll see it defined.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
