### ISSUE TITLE
The managed code example fails in VS 2019

### ISSUE THREAD

**Issue by StefanLang-JCD** [MicrosoftDocs/cpp-docs#3239]
I have experienced C2259 with a managed class definition, and the example offered at the end of the page indicates how to solve it. However, the example fails to compile, even after uncommenting the 'public:' line!

Thanks to Intellisense, I was able to fix the code: the method implementation apparently requires the 'virtual' keyword!

On a sidenote, the reason I was getting this error was that I am not familiar with C++/CLI and didn't know I had to use the keyword, 'interface'. The code I originally tried was something like this:
ref class Base {
public:
   virtual void foo() = 0;
};
ref class Derived : public Base {
   void foo() override;
};
As you can see this corresponds to the syntax used in unmanaged C++. Intellisense shows no problems with this part of the code! Given that there is no way to implement the abstract method foo() using these apparently incorrect managed class definitions, why doesn't Intellisense show the problem right there? And why doesn't the compiler show any message referring to this class definition code? Error C2259 only states that Derived does not implement the abstract method foo - but not that the entire definition is wrong, including the definition of the base class and it's method!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c5dfc6-c9a1-3c9a-1e3c-c4364b19c8db
* Version Independent ID: a24ab752-ac17-1cb4-63cb-a969d29fb331
* Content: [Compiler Error C2259](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2259?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2259);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.7.2);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.7.2)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2259.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2259.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@StefanLang-JCD 
Thanks for the analysis. I don't think this code has been looked at in a long time. I'll push an update with a correction. 
As for the IntelliSense idea, that's something to bring up with the product team on [Developer Community](https://aka.ms/vsfeedback/browsecpp). It's the best place for product suggestions, and it's where you go if you use the IDE to provide feedback, too.

**Comment by corob-msft** [comment]
A fix should appear sometime tomorrow, so I'm closing the issue.
