### ISSUE TITLE
How exactly variables are catched when importing existing cache ?

### ISSUE THREAD

**Issue by Tryum** [MicrosoftDocs/cpp-docs#324]
When I tried, some variables appears in the CMakeSettings.json file and others don't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Tryum Do you recall which variables did not get cached?

**Comment by rchiodo** [comment]
Our algorithm looks for everything marked as `:UNITIALIZED` and then adds this to our list of variables we automatically specify in the generated CMakeSettings.json.

Here's an example:

`
//No help, variable specified on the command line.
`
`
CMAKE_CXX_COMPILER:UNINITIALIZED=C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/VC/Tools/MSVC/14.15.26726/bin/HostX86/x86/cl.exe
`

It's not very good at figuring out entries that weren't specified on the command line when first configured.
Feel free to log a bug. We need to improve this.

**Comment by Tryum** [comment]
Indeed all the missing variables I'm looking for have a specialized type.

**Comment by jakesays** [comment]
Can you document the format of 'variables'? Is it a json object, string of comma separated name=value's, or what?

**Comment by rchiodo** [comment]
Are you asking the format in the CMakeSettings.json? That's somewhat explained here:
https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017#cmake_settings

Essentially like so:

    {
      "name": "x86-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x86"
      ],
      "buildRoot": "${workspaceRoot}\\build\\${name}",
      "installRoot": "${workspaceRoot}\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_CXX_COMPILER",
          "value": "C:/Program Files (x86)/Microsoft Visual Studio/157/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX86/x86/cl.exe"
        },
        {
          "name": "CMAKE_C_COMPILER",
          "value": "C:/Program Files (x86)/Microsoft Visual Studio/157/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX86/x86/cl.exe"
        }
      ]
    }


The intellisense for the CMakeSettings.json should make it pretty easy to add new ones.

**Comment by jakesays** [comment]
@rchiodo Thank you - that is exactly the information I was looking for.

As far as the documentation you referenced is concerned, the only passage I could find related to variables is this:
`variables: contains a name-value pair of CMake variables that will get passed as -Dname=value to CMake. If your CMake project build instructions specify the addition of any variables directly to the CMake cache file, it is recommended that you add them here instead.`

As you are probably aware there are a zillion ways to describe name/value pairs in json (oddly enough the method chosen for CMakeSettings.json is not one of the more intuitive ones).

Anyway, thanks again for the info. hopefully your example will be added to the docs.

-Jake

**Comment by mikeblome** [comment]
Thanks @jakesays  and @rchiodo .  The updated doc will appear tomorrow.

**Comment by jakesays** [comment]
Thanks Mike! Appreciate the quick response.
