### ISSUE TITLE
Machine translation is converting "regular expressions" incorrectly.

### ISSUE THREAD

**Issue by maoutokagura** [MicrosoftDocs/cpp-docs#3252]
Machine translation  convert "regular expressions" incorrectly.

In English
        "[a-zA-Z0-9_]"*

In Japanese
       "[zA-A-za-z0-9_]"*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f13895a3-a0d7-77b6-0c6a-5431dfae2413
* Version Independent ID: 347e4a7e-7607-6e9d-bc21-358b70792852
* Content: [Regular Expressions (C++)](https://docs.microsoft.com/en-us/cpp/standard-library/regular-expressions-cpp?view=msvc-160#feedback)
* Content Source: [docs/standard-library/regular-expressions-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/regular-expressions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @maoutokagura, 

I have fixed this. It should be live in a couple days. Thank you for pointing out the issue so we could address it.
