### ISSUE TITLE
There does not appear to be a strict version of the float_control pragma

### ISSUE THREAD

**Issue by pecsa** [MicrosoftDocs/cpp-docs#3253]
This example is given:

```
#pragma float_control(strict, on, push)
// Code that uses /fp:strict mode
#pragma float_control(pop)

```

The pragma "float_control(strict, ...)" is not documented. On the page
https://docs.microsoft.com/en-us/cpp/preprocessor/float-control?view=msvc-160
there is no mention of the "strict" option for the float_control pragma.

I get the following warning if I try to use it (Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30037 for x64):

`warning C4081: expected ')'; found ','` 

Which I take to mean the compiler does not recognize the 'strict' version of the pragma. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58614da-89f6-0c10-790e-81251bcdc4a8
* Version Independent ID: d376287f-91b8-7887-9ab9-9887382fe409
* Content: [/fp (Specify floating-point behavior)](https://docs.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-160)
* Content Source: [docs/build/reference/fp-specify-floating-point-behavior.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fp-specify-floating-point-behavior.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pecsa 
Yes, that's a typo that I probably meant to be `precise`. Duplicating the effect of **`/fp:strict`** requires you set several pragma directives. The updated example should be available tomorrow.
