### ISSUE TITLE
/ZH:GIT

### ISSUE THREAD

**Issue by maharmstone** [MicrosoftDocs/cpp-docs#3256]
One trivial but very useful improvement to this would be an option to use the Git blob ID instead. This is identical to the SHA1 hash, but the source data is prepended with the word "blob" and the filesize. This would mean that Visual Studio would be able to fetch the right version of the file from the repo, rather than just telling you it doesn't match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a44fc24a-7d5b-f928-5088-5784fd3737d8
* Version Independent ID: ae775be9-88e6-4494-1ac5-a5b0308e8531
* Content: [/ZH (Hash algorithm for calculation of file checksum in debug info)](https://docs.microsoft.com/en-us/cpp/build/reference/zh?view=msvc-160)
* Content Source: [docs/build/reference/zh.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zh.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@maharmstone 
That's a fine idea. Unfortunately, you're proposing it in the wrong spot. This GitHub Issues board is for bugs or suggestions in the documentation, so I'm closing the issue as a product idea. To suggest an addition to the product, you'll want to use either the Visual Studio **Help** > **Send Feedback** > **Suggest a Feature** command, or go directly to the C++ [Developer Community](https://aka.ms/vsfeedback/browsecpp) site. That's a direct channel to the product team. They'll consider your idea for inclusion, especially if other people upvote it. Good luck!
