### ISSUE TITLE
Module partitions seem to be working

### ISSUE THREAD

**Issue by AbhimanyuVS** [MicrosoftDocs/cpp-docs#3262]
This page states that module partitions have not been implemented yet for the Microsoft C++ compilers. However, I have been able to successfully use module partitions. Perhaps this page should be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-160)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
This seems to have been updated since this issue was opened. Closing.
