### ISSUE TITLE
P0734R0 Concepts is wrongly reported as fully supported

### ISSUE THREAD

**Issue by Serikov** [MicrosoftDocs/cpp-docs#3263]
MSVC still does not implement p0734 as _requires-expression_ is only partially supported.

See ["C++20 Concepts Are Here in Visual Studio 2019 version 16.3" blog post](https://devblogs.microsoft.com/cppblog/c20-concepts-are-here-in-visual-studio-2019-version-16-3/):

> // Currently, MSVC doesn't support requires-expressions everywhere; they only work in concept definitions and in requires-clauses

and recent discussion on [r/cpp](https://old.reddit.com/r/cpp/comments/old0t6/why_does_msvc_blatantly_lies_about_its_supported/)

table row "P0734R0 Concepts | VS 2019 16.3" should be replaced with something along the lines of

P0734R0 Concepts | Partial in VS 2019 16.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C/C++ language conformance](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
I've forwarded this issue to the author of the blogpost. I can't do anything about it so closing.
