### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by hovansonn** [MicrosoftDocs/cpp-docs#3264]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a95e0-3932-5290-760a-5810a11f6c51
* Version Independent ID: 94dd41fb-a7fd-57c4-e5a3-12cd1c5b9f86
* Content: [Padding and Alignment of Structure Members](https://docs.microsoft.com/en-us/cpp/c-language/padding-and-alignment-of-structure-members?view=msvc-160)
* Content Source: [docs/c-language/padding-and-alignment-of-structure-members.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/padding-and-alignment-of-structure-members.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hovansonn 
I'm sorry, I don't see an actionable documentation issue in the title or description, so I'm closing it.
