### ISSUE TITLE
Declaration of void change into int

### ISSUE THREAD

**Issue by etomszo** [MicrosoftDocs/cpp-docs#3265]
Hi

Does **void f()** is proper declaration for **inf f(int)**. 
I mean it looks like a mistake for me, I try that on the compiler and it doesn't work. 
If that construction would work on VS only, you should add that information to that page.

BR
Tomasz
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d334fd48-9c18-fac4-b871-b75143c1a321
* Version Independent ID: b3bf7dfc-8c5d-0524-4eee-e5af07bcb9ae
* Content: [Declarations and definitions (C++)](https://docs.microsoft.com/en-us/cpp/cpp/declarations-and-definitions-cpp?view=msvc-160)
* Content Source: [docs/cpp/declarations-and-definitions-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/declarations-and-definitions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
@etomszo, thank you for bringing that to our attention. I have fixed the error and it should be live by Monday afternoon.
