### ISSUE TITLE
wrong diagnostic code used in text

### ISSUE THREAD

**Issue by bowie7070** [MicrosoftDocs/cpp-docs#3269]
The text in places uses the code 4034 rather than 4834.

> You can turn off the warning for a specific line of code by using the warning pragma, #pragma warning(suppress : 4034). You can also turn off the warning within a file by using the warning pragma, #pragma warning(disable : 4034). You can turn off the warning globally in command-line builds by using the /wd4034 command-line option.
> 
> To turn off the warning for an entire project in the Visual Studio IDE:
> 
> Open the Property Pages dialog for your project. For information on how to use the Property Pages dialog, see Property Pages.
> Select the Configuration Properties > C/C++ > Advanced page.
> Edit the Disable Specific Warnings property to add 4034. Choose OK to apply your changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7edfac9-2178-0e6a-d534-51ab9d3503ef
* Version Independent ID: 8993c7ff-6dd3-ddc3-4739-eb9a7594a713
* Content: [Compiler warning (Level 1) C4834](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4834?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/c4834.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/c4834.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bowie7070  Thanks for the report; the fix is now live.
