### ISSUE TITLE
"Object instantiation" is misleading.

### ISSUE THREAD

**Issue by marat-turaev** [MicrosoftDocs/cpp-docs#327]
Quoting "Object instantiation":
&gt;Reference (ref) types and value types can only be instantiated on the managed heap, not on the stack or on the native heap.
But the third example shows how to allocate value type on the stack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06850b6e-7bfc-36de-797f-a9410b4a078b
* Version Independent ID: 61283b57-e16a-ed21-defa-ed897b5152d8
* Content: [How to: Define and Consume Classes and Structs (C++/CLI)](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-define-and-consume-classes-and-structs-cpp-cli#BKMK_Object_instantiation)
* Content Source: [docs/dotnet/how-to-define-and-consume-classes-and-structs-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-define-and-consume-classes-and-structs-cpp-cli.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @marat-turaev I have fixed the doc. Should be visible 07/12.
