### ISSUE TITLE
Property page editing could be clearer

### ISSUE THREAD

**Issue by jdart1** [MicrosoftDocs/cpp-docs#3285]
The last sentence of the page says "In Property Manager, open the new property sheet and then set the properties you want to include." But it doesn't say how to "open the new property sheet." If you create the sheet by doing a right click on the project node of the Property Manager, then you don't see any sign of the new property sheet. You have to actually open up one the of configurations shown in the list and then you will see the new property sheet you created, and can double click on that to edit it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d14bcc9-b174-5949-035e-678a3939f031
* Version Independent ID: 03017dba-6921-5b6e-b6df-05a9d955da3d
* Content: [Share or reuse Visual Studio project settings - C++](https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=msvc-160)
* Content Source: [docs/build/create-reusable-property-configurations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/create-reusable-property-configurations.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Badreah87** [comment]
@uiu44

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
