### ISSUE TITLE
Incorrect signature for PostFix operator?

### ISSUE THREAD

**Issue by narayanpvs** [MicrosoftDocs/cpp-docs#3286]
friend Point& operator++( Point&, int ) // Postfix increment
friend Point& operator--( Point&, int ) // Postfix decrement

Shouldn't these be:

friend Point operator++( Point&, int ) // Postfix increment
friend Point operator--( Point&, int ) // Postfix decrement

It is not possible to return a reference to the object whose state is being changed without the change of state being reflected in the returned object ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd4ccbbe-a665-5cfe-e035-667d6dac152e
* Version Independent ID: b0b0a083-fa8c-b663-a98e-e26dcd19da17
* Content: [Increment and Decrement Operator Overloading (C++)](https://docs.microsoft.com/en-us/cpp/cpp/increment-and-decrement-operator-overloading-cpp?view=msvc-160)
* Content Source: [docs/cpp/increment-and-decrement-operator-overloading-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/increment-and-decrement-operator-overloading-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@narayanpvs 
Thanks for the report. It looks like you're right. I've fixed the friend declarations and the final example. The updated article should be published in a day or so.
