### ISSUE TITLE
The link export can also be achieved using the compiler #pragma comment( linker feature

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/cpp-docs#329]
This is useful if you need to export with an undecorated name, and have different exports depending on project build settings (such as 32/64 bit builds) - which as far as I'm aware can't be achieved without having different DEF files since you can't use pre-processor conditionals in DEF files.
Here's what seems to work OK for me:
#pragma comment(linker, "/export:PlainFuncName=_PlainFuncName@4")
BOOL CALLBACK PlainFuncName( Things * lpParams)

You do of course need to know what the decorated name would be.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45471fb1-5a57-afb0-15f3-34440d894946
* Version Independent ID: 9361aedb-f82a-b6ef-4af4-a18e55e60cab
* Content: [-EXPORT (Exports a Function)](https://docs.microsoft.com/en-gb/cpp/build/reference/export-exports-a-function)
* Content Source: [docs/build/reference/export-exports-a-function.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/export-exports-a-function.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @Dave-Lowndes ! We have added this to the docs.
