### ISSUE TITLE
Issue with declaration vs. definition

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/cpp-docs#3301]
This part at the top is very confusing:
> A _declaration_ introduces (or re-introduces) a name into the program. A _definition_ introduces a name.

Going by this alone, a declaration and definition are the same thing, which is not the case as the paragraph elaborates. I think it could be worded better. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d22551-f6be-bbd0-98e6-805b8875c07e
* Version Independent ID: c94795a2-814b-0c05-d2df-5ba3bc0425c7
* Content: [Translation units and linkage (C++)](https://docs.microsoft.com/en-us/cpp/cpp/program-and-linkage-cpp?view=msvc-160)
* Content Source: [docs/cpp/program-and-linkage-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/program-and-linkage-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@FrankAtHexagon 
Thanks for the report. A fix should appear tomorrow.

**Comment by FrankAtHexagon** [comment]
Awesome! Thanks for your help. I really like this article series.
