### ISSUE TITLE
Conformance mode set to No to avoid #include problems

### ISSUE THREAD

**Issue by francismosse** [MicrosoftDocs/cpp-docs#3306]
My project was including (#include) header files from another folder. Though those files could be included normally, the files _they_ wanted to include would not be accessible.
This problem was created by my project's "Conformance mode". The problem went away after I set it to **No**
Go to: Configuration Properties /C/C++/All Options/Conformance mode --> set it to "No"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0d833e-97f5-4f89-17c1-81c1e17b7dee
* Version Independent ID: a65aef11-0a11-eb2c-a46b-71dec82dead1
* Content: [Compiler Error C3861](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3861?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C3861)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c3861.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-error-c3861.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Hi @francismosse. I'm sorry you had this problem. Is there a specific documentation ask here? Please reopen if so with what you think we could do to the docs regarding this.
