### ISSUE TITLE
Page needs updating for C++20

### ISSUE THREAD

**Issue by maharmstone** [MicrosoftDocs/cpp-docs#3309]
There's multiple instances on this page where it says the `u8` prefix maps onto `char` / `std::string`, such as in the comments in the first code block. It needs to be updated to say that if you have MSVC set to C++20 mode, `u8` maps to `char8_t` / `std::u8string` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ebb90bf-a25a-cb4c-56d0-d46cc341d14b
* Version Independent ID: e709e8b2-2a41-f66b-26cd-762a631817cc
* Content: [String and character literals (C++)](https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=msvc-160)
* Content Source: [docs/cpp/string-and-character-literals-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/string-and-character-literals-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed some time ago, but I forgot to close the issue.
