### ISSUE TITLE
Note that /analyze:log log_path suppresses output to console.

### ISSUE THREAD

**Issue by hill-labs-developers** [MicrosoftDocs/cpp-docs#3311]
Setting **`/analyze:log`** _`log_path`_ seems to suppress all output to the console. This isn't clear in the documentation. And it seems there's no way to force output to the console as well as the single log file (i.e. the opposite of **`/analyze:quiet`**?

It would be good to note that **`/analyze:log`** _`log_path`_ suppresses output to the console and a way to enable, if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09296a0d-dea6-bcf6-7370-5ec2cf061835
* Version Independent ID: b6de3061-2d20-4508-6a76-663a2d61d098
* Content: [/analyze (Code analysis)](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=msvc-160)
* Content Source: [docs/build/reference/analyze-code-analysis.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/analyze-code-analysis.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
