### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by Jihadist** [MicrosoftDocs/cpp-docs#3317]
Missing keyword _final_ while article exists https://docs.microsoft.com/en-us/cpp/cpp/final-specifier?view=msvc-160 and also _override_ missed https://docs.microsoft.com/en-us/cpp/cpp/override-specifier?view=msvc-160

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b34a0f-3a54-b85b-ef26-175493e5c54c
* Version Independent ID: 216f06f3-ef2f-148c-3f11-ab92e5b7d803
* Content: [Keywords (C++)](https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/cpp/keywords-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/keywords-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
The entries are under Classes and structs > Overview of member functions in the TOC.  This is an old issue - maybe that was fixed in the last while or was just not obvious. Either way, closing.
