### ISSUE TITLE
Missing /Zc:char8_t

### ISSUE THREAD

**Issue by RobL371** [MicrosoftDocs/cpp-docs#3325]
This page is missing the option for char8_t conformance which is present in VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127ca431-7115-bc22-25f2-f67339efc59a
* Version Independent ID: 45759414-19a0-326b-bbac-08b59e23a661
* Content: [/Zc (Conformance)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-conformance?view=msvc-160)
* Content Source: [docs/build/reference/zc-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zc-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This was fixed about three weeks ago, but I forgot to follow up. Closing.
