### ISSUE TITLE
Compiler Warning (level 1) C4530 page example doesn't generate C4530.

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/cpp-docs#3327]
Compiler Warning (level 1) C4530 page example doesn't generate C4530.
I'm using Microsoft Visual Studio Enterprise 2019 Version 16.11.1.

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4530?view=msvc-160

int main() {
    try {}
    catch (int*) {}   // C4530
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a00ea2b-8677-83de-875f-b01637d76fe0
* Version Independent ID: 03938a2e-6e17-596d-eec1-96f89b103d89
* Content: [Compiler Warning (level 1) C4530](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4530?f1url=%3FappId%3DDev16IDEF1%26l%3DJA-JP%26k%3Dk%28C4530%29%26rd%3Dtrue&view=msvc-160&source=docs)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4530.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4530.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as not repro. If a repro case is supplied, I'll reopen this issue.
