### ISSUE TITLE
Typo in pragma examples

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/cpp-docs#3333]
[Enter feedback here]
```
// Report warning C4164 as an error.
#pragma warning( error : 164 )
```
Should this not be:
```
// Report warning C4164 as an error.
#pragma warning( error : 4164 )
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9651a718-4fc5-35ea-f5d8-b3d4fc355639
* Version Independent ID: be36f8da-7c38-53c7-7d25-c9ea1f0f6755
* Content: [warning pragma](https://docs.microsoft.com/en-us/cpp/preprocessor/warning?view=msvc-160)
* Content Source: [docs/preprocessor/warning.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/warning.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yowl 
Thanks for checking in. The example you cite is intentional; you can leave off the initial `4` from 4000-series warnings in the warning pragma. As it says right after the example, "The compiler adds 4000 to any warning number that is between 0 and 999."
