### ISSUE TITLE
Walkthrough just fails

### ISSUE THREAD

**Issue by marb07g** [MicrosoftDocs/cpp-docs#3334]
I've followed the steps in the walkthrough several times - all the setup steps work fine. after deleting code snippets in the .cpp file, I  "Copy(/paste) this example code and then paste it into HelloWindowsDesktop.cpp window VS immediately detects 36 errors (no point going to build). First 4 errors are  cannot open source files "window.h", "stdlib.h", "string.h", "tchar.h", then there is several identifier xxx is undefined, and "expected a declaration" errors (and some others). Am using VS  Community 2019 version 16.11.2 (as downloaded by Installer) and I made sure "Desktop development with C++ workload is checked".

Clearly environment hasn't got access to header files - what am I missing in the setup? (followed the walkthrough verbatim)

thank you
BTW first time coding a windows desktop app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-160#see-also)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@marb07g 

I'm sorry you're having trouble. The walkthrough works for me with a default install of the Desktop development with C++ workload. It sounds like something may have gone wrong with your installation. I'd run the installer again, and make sure that the current installation includes the **Windows 10 SDK (10.0.19041.0)** component. This is normally installed by default as part of the Desktop development with C++ workload. I imagine if it was deselected during your initial install, you might see the problems you're experiencing. We have a more C++-centric installation walkthrough in [Install C and C++ support in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-160).

If the SDK is installed, then the next thing to try is the [Create a console calculator in C++](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=msvc-160) walkthrough. It has some additional troubleshooting steps.

After doing that, if things still don't work, I recommend the [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) forums for help. The issues board here is for problems in the docs, not product support, and as I don't think this requires a fix in the docs, I'm closing this issue.

**Comment by marb07g** [comment]
Thanks Colin

 

Included component Windows 10 SDK (10.0.19041.0) (once I worked out how to find it and include it) and got zero source errors in cpp file and build worked first time. 

 

Being new to all this, I had no idea where to go – your few clues helped immensely. 

 

Martin

**Comment by marb07g** [comment]
Thanks Colin

Included component Windows 10 SDK (10.0.19041.0) (once I worked out how to find it and include it) and got zero source errors in cpp file and build worked first time. 

Being new to all this, I had no idea where to go – your few clues helped immensely. 

Martin
