### ISSUE TITLE
I want to install on a machine with no internet connection

### ISSUE THREAD

**Issue by chuckheaton6** [MicrosoftDocs/cpp-docs#3335]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6c6f6a-188a-7110-962c-89ff8e00eee9
* Version Independent ID: ffa45840-7fbb-b9c2-0dd9-43eb95b760cc
* Content: [Install C and C++ support in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/vscpp-step-0-installation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-0-installation.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chuckheaton6 
The C++ Visual Studio installation docs cover the most common case. For other scenarios, check out the Visual Studio docs.
[Create an offline installation of Visual Studio](https://docs.microsoft.com/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
