### ISSUE TITLE
Explicitly state wich API functions are allowed in a signal handler

### ISSUE THREAD

**Issue by Silicomancer** [MicrosoftDocs/cpp-docs#3341]
The documentation says in a very rough way which API functions one may NOT call from within a signal handler.
The more interesting thing is: What functions ARE allowed?

I would like to send data from a signal handler to a thread. This is very easy on Linux because an [official documentation](https://man7.org/linux/man-pages/man7/signal-safety.7.html) exists, that tells me what calls are legal in a signal handler (e.g. it is allowed to use `socketpair()` and `read()`/`write()` to exchange data with the thread).

So, what API functions are legal in a signal handler on Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a0d41c-42c0-a099-eaac-406cf50b79db
* Version Independent ID: a52350c9-7fa1-4428-37a8-2c07a3a18cb4
* Content: [signal](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/signal.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/signal.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Silicomancer 
While that would be interesting to research and list, it's not a task we have the bandwidth to take on. I expect the UCRT equivalents of the listed POSIX functions, where they exist, are probably safe to use when they don't fail any of the listed restrictions.
