### ISSUE TITLE
Procedure for Adding C++/CLI  support 

### ISSUE THREAD

**Issue by paulfwhite** [MicrosoftDocs/cpp-docs#3346]
Here are a couple of suggestions for improvement for newbies.  Noted the _Installed components_ tab is actually _Individual components_.

Add extra comment near this phrase
_open the Visual Studio Installer._
_The program name is vs_setup.exe_

Change this statement
_Select the Installed components tab_
to
_Select the Individual components tab_

Prior to this statement 
_Choose Modify to update Visual Studio._
add
_Note the installation details panel lists the selected component and dependencies if needed.  Check the Total space required at the bottom right of the window, confirm your system has sufficient space. The Visual Studio installer will download necessary files which it may take some time_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e59840-a55c-3282-0b9c-346c0687d48f
* Version Independent ID: 9bb354b6-d77a-1e8d-4cfe-94f77b9890e3
* Content: [.NET programming with C++/CLI](https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=msvc-160)
* Content Source: [docs/dotnet/dotnet-programming-with-cpp-cli-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/dotnet-programming-with-cpp-cli-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@paulfwhite - Thank you for the suggestions. We really appreciate it when the community helps improve things for everyone. I have added this to my list of things to address in the docs. If you want to try your hand at making updates to the docs before I get to it, you are welcome to do so. Here's some instructions: [Make quick edits](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents)  If you think it'd be interesting to try that, please do. If not, I will address this as soon as I can get to it. Thanks again!

**Comment by TylerMSFT** [comment]
@paulfwhite - I made the updates. I didn't add the part about checking for enough space because we assume a baseline of computer familiarity or else the docs would become prohibitively dense. 
Thank you for helping improve these docs. The update should be live by Wed afternoon.
