### ISSUE TITLE
Difference between CRT and UCRT

### ISSUE THREAD

**Issue by CaryFan** [MicrosoftDocs/cpp-docs#335]
It would be more descriptive if MS could draw some very brief diagrams to show what CRT was and what CRT is and will be starting from VS2015. After reading the first article, I guess MS are encouraging the C developers to let their code only depend on UCRT. The runtime will come from the so-called vcruntime libraries.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46783885-a8a2-383a-309b-0b3c4c004c0d
* Version Independent ID: bc3f7efa-42ba-ef01-ff2e-2b9fdf3846ad
* Content: [Upgrade your code to the Universal CRT](https://docs.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt)
* Content Source: [docs/porting/upgrade-your-code-to-the-universal-crt.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/upgrade-your-code-to-the-universal-crt.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Closing because the subject UCRT vs old CRT can't be clearly shown in a diagram and the text does explain the differences.
