### ISSUE TITLE
Windows XP support broken, not documented

### ISSUE THREAD

**Issue by SamVanheer** [MicrosoftDocs/cpp-docs#3351]
There is no information explaining to developers that the Visual C++ redistributable no longer supports Windows XP. You can compile a program with the XP toolset, but there is no matching redistributable that will install a working runtime on XP.

According to [this](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160) page:
```
The Redistributable your app uses has a similar binary-compatibility restriction. When you mix binaries built by different supported versions of the toolset, the Redistributable version must be at least as new as the latest toolset used by any app component.
```

If you use a version of VS 2019 later than 16.7 with the XP toolset, you will have a program that does not have a compatible Windows XP runtime to run it with.

This page should note three things:
1. Users need to install the redistributable (regardless of whether they're on XP or not)
2. Using the redistributable from Microsoft's downloads page will install a non-functional runtime on XP, programs will not be able to launch on XP due to missing APIs as a result
3. How to build a program that targets XP that will still work, such as which project settings to use and which redistributable to provide to users

The only place where you can find that the redistributable dropped Windows XP support is in bug reports:
https://developercommunity.visualstudio.com/t/xp-compatibility-broken-in-visual-c-runtime-2015-2/1406575
https://developercommunity.visualstudio.com/t/vc142crt-142829325-is-no-longer-supported-to-run-o/1251535
https://developercommunity.visualstudio.com/t/microsoft-visual-c-2019-redist-regression/1461474
https://developercommunity.visualstudio.com/t/microsoft-visual-c-2019-redist-regression-suggesti/1464567

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651c91cd-a0c3-f631-7bab-707ea4f1827b
* Version Independent ID: bfd995d2-6875-2301-ef78-4446ed268845
* Content: [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160)
* Content Source: [docs/build/configuring-programs-for-windows-xp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configuring-programs-for-windows-xp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SamVanheer 
Thanks for the report and the links. Updates to this and other relevant docs should be visible tomorrow.
