### ISSUE TITLE
Command-line project management tools, topic errantly prefers devenv.exe /build over msbuild...

### ISSUE THREAD

**Issue by EdDore** [MicrosoftDocs/cpp-docs#3355]
Command-line project management tools section of this page is wrong.

The Visual Studio IDE uses a native project build system based on MSBuild. You can invoke MSBuild directly, or use the native project system without using the IDE:

MSBuild
Use MSBuild (msbuild.exe) and a project file (.vcxproj) to configure a build and invoke the toolset indirectly. It's equivalent to running the Build project or Build Solution command in the Visual Studio IDE. Running MSBuild from the command line is an advanced scenario and not commonly recommended. Starting in Visual Studio 2019 version 16.5, MSBuild doesn't use the command-line environment to control the toolset and libraries used.

DEVENV
Use DEVENV (devenv.exe) combined with a command-line switch such as /Build or /Clean to execute certain build commands without displaying the Visual Studio IDE. **In general, DEVENV is preferred over using MSBuild directly**, because you can let Visual Studio handle the complexities of MSBuild. Starting in Visual Studio 2019 version 16.5, DEVENV doesn't use the command-line environment to control the toolset and libraries used.

The above bolded text runs counter to what msbuild developers and CSS has been recommending to customers for years now. Invoking MSBuild directly has always been preferred over using devenv /build to build projects. The ONLY time we ever recommend using devenv /build, is when there is a project in the solution that is not msbuild compatible (the old setup/install (.vdproj) projects for example).

There are a number of disadvantages using devenv /build

•	You have to install the VS IDE on all your build servers/build pipelines
•	You cannot leverage containerized build environments
•	You lose the ability to leverage msbuild’s binary logger (msbuildlog.com)
•	Unnecessary overhead of devenve.exe process, that uses msbuild to build the actual bits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#command-line-project-management-tools)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@EdDore 
Thanks for the report. While I found the [commit that made this change](https://github.com/MicrosoftDocs/cpp-docs-pr/commit/7efbd80387ceebddb2abee40998e39b43135d276), I couldn't find a matching work item or issue that called for it. The writer has since retired, so I may never know why this recommendation was made over, say, the recommendation in the [Devenv command line reference](https://docs.microsoft.com/visualstudio/ide/reference/devenv-command-line-switches). An update is in the works and should be visible tomorrow.
