### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by geoyar** [MicrosoftDocs/cpp-docs#3358]
[Enter feedback here]

tried this examples with VS 2019 16.11.2 with LUIV and ISO 17 platforms and had "Microsof" on LUIV and "Standard..."on ISO C++ 17 for all three combinations of /permissive- and /Zc.Souce was just copied into project.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6baa8f6-2c5d-81e0-0206-8af211d77ae4
* Version Independent ID: e8ba30e4-d745-f8f5-6bd7-4693e6795629
* Content: [/Zc:twoPhase- (disable two-phase name lookup)](https://docs.microsoft.com/en-us/cpp/build/reference/zc-twophase?view=msvc-160)
* Content Source: [docs/build/reference/zc-twophase.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zc-twophase.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@geoyar 
Thanks for the report. I'm not sure what you mean by LUIV. The examples are meant to be compiled at the command line, since the IDE sets many additional options by default. Here are the results I see using the VS 2019 16.11.2 x64 compiler in a developer command prompt window:

```
D:\proj\twophase>type zctwophase.cpp
// zctwophase.cpp
// To test options, compile by using
// cl /EHsc /nologo /W4 zctwophase.cpp
// cl /EHsc /nologo /W4 /permissive- zctwophase.cpp
// cl /EHsc /nologo /W4 /permissive- /Zc:twoPhase- zctwophase.cpp

#include <cstdio>

void func(long) { std::puts("Standard two-phase") ;}

template<typename T> void g(T x)
{
    x = 0; // Added to silence warning C4100
    func(0);
}

void func(int) { std::puts("Microsoft one-phase"); }

int main()
{
    g(6174);
}

D:\proj\twophase>cl /EHsc /nologo /W4 zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /permissive- zctwophase.cpp && zctwophase
zctwophase.cpp
Standard two-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /permissive- /Zc:twoPhase- zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++17 zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++17 /permissive- zctwophase.cpp && zctwophase
zctwophase.cpp
Standard two-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++17 /permissive- /Zc:twoPhase- zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++20 zctwophase.cpp && zctwophase
zctwophase.cpp
Standard two-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++20 /permissive zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++20 /permissive- zctwophase.cpp && zctwophase
zctwophase.cpp
Standard two-phase

D:\proj\twophase>cl /EHsc /nologo /W4 /std:c++20 /Zc:twoPhase- zctwophase.cpp && zctwophase
zctwophase.cpp
Microsoft one-phase
```

These all behave as I expected, since **`/std:c++20`** turns on **`/permissive-`** by default. Are you seeing different behavior? If so, what toolset and command line options are you using?

**Comment by corob-msft** [comment]
Closing as not repro. We'll revisit if a repro is provided.
