### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EricLengyel** [MicrosoftDocs/cpp-docs#3360]
The link to Intel's CET docs near the top is broken. It should be:

https://software.intel.com/content/www/us/en/develop/articles/technical-look-control-flow-enforcement-technology.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d8d73e-dcd5-67db-4050-54ec1c26463b
* Version Independent ID: ad26ab58-5b51-30ae-5201-46ab487484cb
* Content: [/CETCOMPAT (CET Shadow Stack compatible)](https://docs.microsoft.com/en-us/cpp/build/reference/cetcompat?view=msvc-160)
* Content Source: [docs/build/reference/cetcompat.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/cetcompat.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@EricLengyel 
Thanks for the update. The fix should appear sometime tomorrow.
