### ISSUE TITLE
Binary editor help outdated

### ISSUE THREAD

**Issue by jthorne68** [MicrosoftDocs/cpp-docs#3364]
Visual Studio 2019, Binary Editor page has ancient screenshot, and documents functions (such as Find) that no longer work.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3406b4da-3d4f-a3c8-a946-675cf3ff7bdc
* Version Independent ID: 3781d0ac-47eb-50bf-9b13-4b5d5c6bcea0
* Content: [Binary Editor (C++)](https://docs.microsoft.com/en-us/cpp/windows/binary-editor?view=msvc-160)
* Content Source: [docs/windows/binary-editor.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/binary-editor.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
