### ISSUE TITLE
One sentence in `memcpy` and `wmemcpy` is not correct

### ISSUE THREAD

**Issue by Zero0one1** [MicrosoftDocs/cpp-docs#3366]
This sentence in https://github.com/MicrosoftDocs/cpp-docs/blob/afad7ce969535386a0c1b69ebcecfddb3c27ae15/docs/c-runtime-library/reference/memcpy-wmemcpy.md is not correct.
> Make sure that the destination buffer is the same size or larger than the source buffer.

When the destination buffer is larger than `count`, it doesn't matter even if the destination buffer is smaller than the source buffer. Maybe we should modify this sentence to 

> The destination buffer should be larger than the minimum value between the size of the source buffer and the `count`.

**Comment by Zero0one1** [comment]
The same problem exists on `memmove` page.

**Comment by TylerMSFT** [comment]
I changed it to: Make sure that the destination buffer is large enough to accommodate the number of copied(/moved in the case of memmove) characters.
Will be live tomorrow afternoon (Thurs)
