### ISSUE TITLE
Floating Point Special Values code sample has errors

### ISSUE THREAD

**Issue by JeremyMorton** [MicrosoftDocs/cpp-docs#3369]
```
    e = gf0 / abs(f3);
    printf("std::signbit(-0.0/-INFINITY): %d\n", std::signbit(c));
```

The second line above should be calling `std::signbit` with `e`, not with `c`, and the calculation of `e` divides by `abs(f3)`, which is inconsistent with what is printed out as the calculation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58614da-89f6-0c10-790e-81251bcdc4a8
* Version Independent ID: d376287f-91b8-7887-9ab9-9887382fe409
* Content: [/fp (Specify floating-point behavior)](https://docs.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-160)
* Content Source: [docs/build/reference/fp-specify-floating-point-behavior.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fp-specify-floating-point-behavior.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JeremyMorton 
Thanks for spotting those issues; sorry for the delayed response. A fix is in the works and should appear in the docs in a day or so.
