### ISSUE TITLE
Installation successful.

### ISSUE THREAD

**Issue by abiancu** [MicrosoftDocs/cpp-docs#337]
Thank you for this tutorial. I had visual studio community 2017 configures for C# only. I wasn't sure as to which workload I would need for C++. This tutorial helped decide which workload I needed to develop with C++. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6c6f6a-188a-7110-962c-89ff8e00eee9
* Version Independent ID: ffa45840-7fbb-b9c2-0dd9-43eb95b760cc
* Content: [Install C++ support in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation)
* Content Source: [docs/build/vscpp-step-0-installation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-0-installation.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks!
