### ISSUE TITLE
-fsanitize=fuzzer not yet documented?

### ISSUE THREAD

**Issue by tycho** [MicrosoftDocs/cpp-docs#3370]
The VS2022 17.0 Preview 4 release notes, seen here:

https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.0.0-pre.4.0

Mention a new `-fsanitize=fuzzer` option, and say to go to this page for more information, but the page (at least, as of this writing) does not mention the option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4188aa57-8820-50cd-308e-08ee33ff1bd0
* Version Independent ID: f14d999f-67c6-bdd5-eac6-f02d8e32a2ec
* Content: [/fsanitize (Enable sanitizers)](https://docs.microsoft.com/en-us/cpp/build/reference/fsanitize?view=msvc-160&preserve-view=true)
* Content Source: [docs/build/reference/fsanitize.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fsanitize.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tycho 
Thanks for reaching out. The link will have relevant documentation by the product release, if not before. The fuzzer documentation is still in progress. We sometimes publish docs early for preview features, but it's the exception, not the rule.

**Comment by tycho** [comment]
Then perhaps the release notes shouldn't point to documentation that doesn't mention anything about it?

**Comment by corob-msft** [comment]
This was fixed some time ago, but I failed to update this issue at the time.
