### ISSUE TITLE
Also mention

### ISSUE THREAD

**Issue by olliechick** [MicrosoftDocs/cpp-docs#3372]
It would be good to mention that this can occur if you don't have a forward declaration of a function that doesn't return an int.

For example:

```
int main()
{
  float x = add(1.5, 2.5);
  printf("%f", x);
}

float add(float a, float b) { return a+b; }
```

Previously mentioned in #602

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d76d2fd-fd60-4fa2-59e4-73474d0a743e
* Version Independent ID: 33085254-0592-a16e-1b1d-40abaeeeb8aa
* Content: [Compiler Error C2371](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2371?view=msvc-160)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2371.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2371.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@olliechick 
Thanks for following up on your earlier report. I tried your source example, and it gave me some expected warnings, but not error C2371:

```
C:\Users\corob\Documents\Projects\errors\C2371>type C2371.c
// C2371.c
#include <stdio.h>

int main()
{
  float x = add(1.5, 2.5);
  printf("%f", x);
}

float add(float a, float b) { return a+b; }

C:\Users\corob\Documents\Projects\errors\C2371>cl /W4 C2371.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

C2371.c
C2371.c(6): warning C4013: 'add' undefined; assuming extern returning int
C2371.c(6): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
C2371.c(10): warning C4142: 'add': benign redefinition of type
Microsoft (R) Incremental Linker Version 14.29.30133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:C2371.exe
C2371.obj
```

Is the error compiler-specific? This is the result from running the Visual Studio 2019 version 16.11.1 compiler.
Since I'm not seeing a repro, I'm going to close this, but I'll reopen it if you have an update that produces the error.
