### ISSUE TITLE
Shared library with modules

### ISSUE THREAD

**Issue by alexpanter** [MicrosoftDocs/cpp-docs#3379]
It would be nice to see some info on how to place modules inside a shared library project (.dll, .so). If I build a shared library only with modules then what are the rules for compiling and linking it? And is this even possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b269d9-d8c6-3706-5550-c000ce0cdd75
* Version Independent ID: aef11501-ad70-82ab-a1ee-73114a6d3df7
* Content: [module, import, export](https://docs.microsoft.com/en-us/cpp/cpp/import-export-module?view=msvc-160)
* Content Source: [docs/cpp/import-export-module.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/import-export-module.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@alexpanter 

I can parse your description of "modules inside a shared library" a couple of ways. The obvious reading is that you can certainly build shared libraries using modules, just like you would from any other source code. Build as normal, but target a shared library.

If instead you're asking if it's possible to have the module implementation as a shared library, and include the module as such in another project, then the answer is still yes, but how it's done depends on how you consume shared libraries. In Windows code, that involves a bunch of extra compiler and linker machinery exposed through `__declspec(import)` and `__declspec(export)` decorations. It's whatever you'd do anyway to build code to either consume or share as a DLL. So, if you have existing headers for shared libraries, and you import them as modules, for the most part it will just work.

For now, I'm shelving the idea of special documentation for this combination, as it mixes two largely orthogonal concepts that are best described independently. I appreciate the idea, though.
