### ISSUE TITLE
Why it needs 6 bits for nMonthDay (0..31)? 5 bits should be enough

### ISSUE THREAD

**Issue by xiaozhongl** [MicrosoftDocs/cpp-docs#3380]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78c89c2-7d34-fac8-9043-4099bc8637dd
* Version Independent ID: e265dccc-e3f6-7464-a6cf-e0e19aea772f
* Content: [C++ Bit Fields](https://docs.microsoft.com/en-us/cpp/cpp/cpp-bit-fields?redirectedfrom=MSDN&view=msvc-160)
* Content Source: [docs/cpp/cpp-bit-fields.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-bit-fields.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@xiaozhongl 
Thanks for the report. I don't know why the author chose six bits for this field, but since it doesn't harm anything, and it would require updating the graphics to change it (graphic images are expensive to change), I'm not going to address the issue.

**Comment by xiaozhongl** [comment]
Thanks for replaying. Also in the second figure, starting from the least
most bit should the order of variables be nWeekDay, nMonthDay, alignments,
then nMonth and nYear?



Colin Robertson ***@***.***> 于2021年9月21日周二 上午6:18写道：

**Comment by xiaozhongl** [comment]
sorry, the least significant bit.

刘骁中 ***@***.***> 于2021年9月21日周二 上午8:28写道：

**Comment by corob-msft** [comment]
@xiaozhongl 
That is a good question. The diagrams look inconsistent, but I don't know which one is correct.  If both are correct, then I don't know why. It would take some research to find out, but I don't have time to spend on it. :(
