### ISSUE TITLE
Porting ATL Collections sample to c++ 20 standard

### ISSUE THREAD

**Issue by FStapenhorst** [MicrosoftDocs/cpp-docs#3381]
Hi,

would it be possible to update this document of how to port the samples to the c++ 20 standard?
Some of the samples do not compile anymore using c++ 20 - for example [ATL Collections Sample](https://github.com/microsoft/VCSamples/tree/master/VC2010Samples/ATL/General/ATLCollections).

That would be very much appreciated!

Ferdinand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71056b96-6399-71f4-992d-22958bf25fdc
* Version Independent ID: 9b1f2ead-350c-6242-3ca3-1981cede59c9
* Content: [Microsoft C++ porting and upgrading guide](https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-porting-and-upgrading-guide?view=msvc-160)
* Content Source: [docs/porting/visual-cpp-porting-and-upgrading-guide.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/visual-cpp-porting-and-upgrading-guide.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@FStapenhorst 
Thanks for reporting your concern. The unfortunate reality is, we don't have the resources to update the sample code for ATL or MFC projects. Most of them haven't been touched since they were moved to GitHub, and the repo is now in read-only archive mode.

Since you don't mention what problems you had when compiling the samples in C++20 mode, I don't have any specific advice. However, I know [other issues have been resolved by the judicious application of the `typename` keyword](https://github.com/microsoft/VCSamples/commit/85b0322bd5fc3fddd1ee1cd458935b2036f9ced6). 

I'm sorry to have to close the issue. I wish we did have the resources to maintain the old samples.

**Comment by FStapenhorst** [comment]
@corob-msft 
Thank you for your message. I understand the lack of resources.
The compile error is:
ATLCollections.cpp
```
VCUE_Collection.h(161,17): error C3861: 'm_coll': identifier not found
VCUE_Collection.h(169): message : see reference to class template instantiation 'VCUE::ICollectionOnSTLCopyImpl<T,CollType,ItemType,CopyItem,EnumType,Holder>' being compiled
```
It seems that the c++20 compiler is somewhat more strict that the c++ 17 (it works with c++ 17)
Maybe you have a hint..
Thanks.

**Comment by corob-msft** [comment]
@FStapenhorst 
If you don't care about strict C++20 conformance, you can use the **`/permissive`** option. I don't know if that will fix this particular issue, but it might.

Another possible fix is to add `typename` to the default template parameter `Holder` in VCUE_Collection.h, like so:

```
	template <class T, class CollType, class ItemType, class CopyItem, class EnumType, class Holder = typename CGenericDataHolder< CollType > >
	class ICollectionOnSTLCopyImpl :
		public ICollectionOnSTLImpl<T, CollType, ItemType, CopyItem, EnumType>
```

I haven't tried it, so I don't know if it will work.

**Comment by FStapenhorst** [comment]
Thanks for your suggestions and your time on this!
It did not work unfortunately using `/permissive.`



The template class `ICollectionOnSTLCopyImpl` is derived from `ICollectionOnSTLImpl` and uses the `m_coll` member which is defined in the derived template class.
For some reason, the member variable `m_coll `is undefined at this point. It is defined in `ICollectionOnSTLImpl`  but for some reason the template class in the `VCUE` namespace gets compiled before the derived class.

It seems the c++ 20 compiler compiles template classes in some stricter order?



The actual cpp file being compiled only contains:
```
#include "stdafx.h"
#include "ATLCollections.h"
#include "MapCollection.h"
```

```
// In atlcom.h, here is the template class where m_coll is defined (all the way at the bottom):

template <class T, class CollType, class ItemType, class CopyItem, class EnumType>
class ICollectionOnSTLImpl :
  public T
{
public:
  STDMETHOD(get_Count)(_Out_ long* pcount)
  {
    if (pcount == NULL)
      return E_POINTER;
    ATLASSUME(m_coll.size()<=LONG_MAX);

    *pcount = (long)m_coll.size();

    return S_OK;
  }
  STDMETHOD(get_Item)(
    _In_ long Index,
    _Out_ ItemType* pvar)
  {
    //Index is 1-based
    if (pvar == NULL)
      return E_POINTER;
    if (Index < 1)
      return E_INVALIDARG;
    HRESULT hr = E_FAIL;
    Index--;
    typename CollType::const_iterator iter = m_coll.begin();
    while (iter != m_coll.end() && Index > 0)
    {
      iter++;
      Index--;
    }
    if (iter != m_coll.end())
      hr = CopyItem::copy(pvar, &*iter);
    return hr;
  }
  STDMETHOD(get__NewEnum)(_Outptr_ IUnknown** ppUnk)
  {
    if (ppUnk == NULL)
      return E_POINTER;
    *ppUnk = NULL;
    HRESULT hRes = S_OK;
    CComObject<EnumType>* p;
    hRes = CComObject<EnumType>::CreateInstance(&p);
    if (SUCCEEDED(hRes))
    {
      hRes = p->Init(this, m_coll);
      if (hRes == S_OK)
        hRes = p->QueryInterface(__uuidof(IUnknown), (void**)ppUnk);
    }
    if (hRes != S_OK)
      delete p;
    return hRes;
  }
  CollType m_coll;
};


#include <AtlCom.h>
namespace VCUE
{
   //  some more methods here...

    template <class T, class CollType, class ItemType, class CopyItem, class EnumType, 
                    class Holder = typename CGenericDataHolder< CollType > >
    class ICollectionOnSTLCopyImpl :
		    public ICollectionOnSTLImpl<T, CollType, ItemType, CopyItem, EnumType>
    {
      public :
    
        STDMETHOD(get__NewEnum)(IUnknown** ppUnk)
        {
	        typedef CComObject< Holder > HolderObject;
	        HolderObject* p = NULL;
	        HRESULT hr = HolderObject::CreateInstance(&p);
	        if (FAILED(hr))
		        return hr;
// >>> If I comment out the next line, it compiles <<<
	        hr = p->Copy(m_coll);
	        if (FAILED(hr))
		        return hr;
        
	        return CreateSTLEnumerator<EnumType>(ppUnk, p, p->m_Data);
        
        } // STDMETHOD(get__NewEnum)(IUnknown** ppUnk)
    
    }; // class ICollectionOnSTLCopyImpl
}
```

Mapcollection.h looks like this:

```
#ifndef __MAPCOLLECTION_H_
#define __MAPCOLLECTION_H_

#pragma warning(push)
#pragma warning(disable:4702)
#include <map>
#pragma warning(pop)

#include "Reuse\VCUE_Copy.h"
#include "Reuse\VCUE_Collection.h"

namespace MapColl
{
  typedef std::map<CAdapt<CComBSTR>, CComVariant>  ContainerType;
  typedef VARIANT                                                                    ExposedType;
  typedef IEnumVARIANT                                                          EnumeratorInterface;
  typedef IItems                                                                         CollectionInterface;
  typedef VCUE::MapCopy<ContainerType, ExposedType> CopyType;
  typedef CComEnumOnSTL< EnumeratorInterface, 
                 &__uuidof(EnumeratorInterface), ExposedType,
                 CopyType, ContainerType >                                       EnumeratorType;
  
typedef ICollectionOnSTLImpl< CollectionInterface, ContainerType, ExposedType,
              CopyType, EnumeratorType >                                     CollectionType;
};

#endif
```

**Comment by corob-msft** [comment]
When I hear a language standard update causes template instantiation order problems, I suspect it's because of a difference between the legacy template parser and the [new, compliant two-phase parser](https://docs.microsoft.com/en-us/cpp/build/reference/zc-twophase?view=msvc-160). You can verify this by trying the **`/Zc:twoPhase-`** compiler option. (The link includes info on how to update your code.)

A less likely culprit, but one that's possible in macro-heavy code like ATL is the behavior difference between the legacy preprocessor and the [new, compliant preprocessor](https://docs.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-160). You can verify that by trying the **`/Zc:preprocessor-`** option to invoke the legacy preprocessor.

**Comment by FStapenhorst** [comment]
Thank you for your patient help on this issue. The /Zc:twoPhase- option does the trick and that compiles.

But I finally decided to use the standard ATL template `ICollectionOnSTLImpl` instead of the derived version `ICollectionOnSTLCopyImpl` since the extra feature that `ICollectionOnSTLCopyImpl` gives me isn't really required and I would like my code to be fully c++20 compliant.
That compiles fine.

Thanks again for your help on this!
