### ISSUE TITLE
Global UCRT state for _mkgmtime, _mkgmtime32, _mkgmtime64

### ISSUE THREAD

**Issue by darjeeling-uk** [MicrosoftDocs/cpp-docs#3386]
Reference page says "By default, this function's global state is scoped to the application. To change this, see Global state in the CRT."  I don't see anything on the page that explains why this function would have any global state, so I suspect the quoted sentence is nonsense.  (I may misunderstand something!)

Mike.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddd4a4d5-21ca-b885-5c3d-990e4e1b13fe
* Version Independent ID: 7bf9dd4e-a4f8-160e-9c92-740ff05ffaee
* Content: [_mkgmtime, _mkgmtime32, _mkgmtime64](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@darjeeling-uk, good call. Thank you for pointing that out. I've removed the reference to global state. The fix should be live by tomorrow afternoon (9/23)
