### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by supuflounder** [MicrosoftDocs/cpp-docs#3387]
[Enter feedback here]
Why is "ID2D1DCRenderTarget" not a hyperlink to whatever this thing is?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00146566-5ea9-fafa-fc39-c979cfba6716
* Version Independent ID: e0a68a65-e3f9-5c2d-e5a1-cedc659e91d0
* Content: [CDCRenderTarget Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cdcrendertarget-class?view=msvc-160)
* Content Source: [docs/mfc/reference/cdcrendertarget-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cdcrendertarget-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@supuflounder, thanks for pointing that out. I've added a link to the interface topic. Should be live by tomorrow afternoon (9/23)
