### ISSUE TITLE
Unclear if the parameters of /LTCG are supported

### ISSUE THREAD

**Issue by sigiesec** [MicrosoftDocs/cpp-docs#339]
The description notes that lib.exe has a /LTCG option. The description links to the /LTCG option documentation of link.exe, which lists several parameters of /LTCG. It is unclear if these are also supported by lib.exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64e0671-42d6-8a30-ebff-d2b501d731c1
* Version Independent ID: 2f675905-9ad0-14bd-2b1b-c2f08fd831dd
* Content: [Running LIB](https://docs.microsoft.com/en-us/cpp/build/reference/running-lib)
* Content Source: [docs/build/reference/running-lib.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/running-lib.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
doc is updated. thanks again!

**Comment by sigiesec** [comment]
Where? I can't see any PR referencing this issue, and  looking at https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/running-lib.md, I also cannot find any recent change.
