### ISSUE TITLE
How can I just gcc with no flags?

### ISSUE THREAD

**Issue by sron** [MicrosoftDocs/cpp-docs#340]
I want to quickly compile a c file that compiled well with just gcc but not so with VS compilation flags.
At, project properties-&gt;C/C++-&gt;Command Line, I have, 
"g++" -std=gnu++14 -w -fno-strict-aliasing -g1 "g++" -O3 "3600000" -fthreadsafe-statics -D "NDEBUG" -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -frtti -fomit-frame-pointer -std=c11 -fexceptions -o "C:\ePoll2\obj\ARM\Release\%(filename).o"
 How can I set VS to use just gcc? I tried to disable few things but still have these parameters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@sron Are you still having issues here? Does these blog posts help? https://blogs.msdn.microsoft.com/vcblog/2017/03/07/use-any-c-compiler-with-visual-studio/
https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

**Comment by m-ply** [comment]
@mikeblome Yes I still having these issues. As i saw at the links, it talking about setting different compilers/toolsets. But haw can I set VS to just use my compiler, without passing any flags to that compiler?
(see project properties->C/C++->Command Line). 
Thanks

**Comment by mikeblome** [comment]
@m-ply Apologies for late response! I'm sorry you are having difficulties here. The compiler options are set in this page: Project Properties > C/C++ Properties. https://docs.microsoft.com/en-us/cpp/linux/prop-pages/c-cpp-linux?view=vs-2017
