### ISSUE TITLE
Incorrect attribution in brace initialization?

### ISSUE THREAD

**Issue by AvidDrawer** [MicrosoftDocs/cpp-docs#3400]
(just above the 4th code snippet)

*If the default constructor is explicitly declared but marked as deleted, default brace initialization cannot be used:*
        This looks incorrect. According to [cppreference](https://en.cppreference.com/w/cpp/language/aggregate_initialization), you can use brace initialization in the presence of deleted/defaulted constructors. What is **wrong** is the use of brace initialization when user defined constructors are present. 
        
In the code snippet that follows the above statement, error C2280 is correctly marked but attributed incorrectly for aforementioned reasons. If you were to comment out the single parameter constructor, the program would compile correctly. 
```
class class_f {
public:
    class_f() = delete;
    class_f(string x): m_string { x } {}  // commenting this will remove C2280 error
    string m_string;
};
int main()
{
    class_f cf{ "hello" };
    class_f cf1{}; // compiler error C2280: attempting to reference a deleted function  
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 441b3ef5-7a22-0496-ddec-6baee7262991
* Version Independent ID: 711a8364-a43c-22fc-217a-30c95c5c946b
* Content: [Brace initialization for classes, structs, and unions](https://docs.microsoft.com/en-us/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=msvc-160)
* Content Source: [docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by AvidDrawer** [comment]
It would also be nice to expand upon the fact that brace initialization can also refer to constructors when appropriate. I don't have a complete grasp of the rules to suggest where/how it can be added.

**Comment by corob-msft** [comment]
@AvidDrawer 
Thanks for commenting here. I think there's some confusion about "default brace initialization", which here means initialization with an empty pair of braces. The statement above the fourth example isn't saying you're unable to use brace initialization with other user-defined constructors in this situation. It's just saying default brace initialization isn't going to work if the default constructor is explicitly deleted. I still see a C2280 compiler error in your example if I comment out the string-argument constructor in `class_f` (and the declaration of `cf` in `main`). 
I'm closing this as not repro, but feel free to argue your case if I've misunderstood your objection; we can reopen it.

**Comment by AvidDrawer** [comment]
@corob-msft  You're right, C++20 still throws compiler errors as you pointed out. I was testing on c++17 and referenced cppreference based on the change logs. 

Apologies for the misunderstanding!
