### ISSUE TITLE
NET

### ISSUE THREAD

**Issue by ALI0ne** [MicrosoftDocs/cpp-docs#3406]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a04e4fcc-fc70-6fb3-4562-a15659d7837b
* Version Independent ID: 2e2dc015-06b3-515f-f3bf-e19c4edbb4b4
* Content: [CComPtr Class](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptr-class?view=msvc-160)
* Content Source: [docs/atl/reference/ccomptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/ccomptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@ALI0ne 
This issue isn't actionable, since it doesn't have any description or other indication of what's wrong.
