### ISSUE TITLE
[PROBLEM] Unable to Find .DLL file : Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by yeokaiwei** [MicrosoftDocs/cpp-docs#3407]
"To verify that everything works so far, compile the dynamic link library. To compile, choose Build > Build Solution on the menu bar. The DLL and related compiler output are placed in a folder called Debug directly below the solution folder. If you create a Release build, the output is placed in a folder called Release. The output should look something like this:"

The problem occurs after this step.

**PROBLEM**
After building the solution in Debug and Release, I am unable to find a .DLL file.

**SOLUTION**
Unknown

Reference
https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-160

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-160)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yeokaiwei 
I'm sorry you're having a difficult time with the walkthrough. However, I know that most people complete it successfully, so I don't think there's a problem in the article. I don't have enough information to tell you why you're not succeeding, and this issues board isn't meant for product support. I think you'd get better help by asking about this issue on the Microsoft Docs Q&A [C++ board)(https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Good luck!
