### ISSUE TITLE
Correct the comment position.

### ISSUE THREAD

**Issue by hbsun2113** [MicrosoftDocs/cpp-docs#3408]
[Enter feedback here]

For this [page](https://docs.microsoft.com/en-us/cpp/sanitizers/error-stack-buffer-overflow?view=msvc-160)

should be:
```
// example3.cpp
// stack-buffer-overflow error
class Parent {
public:
    int field;
};

class Child : public Parent {
public:
    int extra_field;
};

int main(void) {

    Parent p;
    Child *c = (Child*)&p; 
    c->extra_field = 42;  // Boom !

    return 0;
}
```

not be:
```
// example3.cpp
// stack-buffer-overflow error
class Parent {
public:
    int field;
};

class Child : public Parent {
public:
    int extra_field;
};

int main(void) {

    Parent p;
    Child *c = (Child*)&p;  // Boom !
    c->extra_field = 42;

    return 0;
}
```
```
```
![image](https://user-images.githubusercontent.com/27994442/134801619-7c9893c4-82f4-4070-aa94-a9652b93794f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307a2a62-b3ae-7e6b-8b50-005a261a38a0
* Version Independent ID: 011a7e6d-a38a-a32e-8793-2db39d25df5a
* Content: [Error: stack-buffer-overflow](https://docs.microsoft.com/en-us/cpp/sanitizers/error-stack-buffer-overflow?view=msvc-160)
* Content Source: [docs/sanitizers/error-stack-buffer-overflow.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/sanitizers/error-stack-buffer-overflow.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hbsun2113 
Thanks for the report. I've moved the comment, and the fix should be visible in the next day or so.
