### ISSUE TITLE
asctime() etc. do not make adjustments for local time

### ISSUE THREAD

**Issue by darjeeling-uk** [MicrosoftDocs/cpp-docs#3409]
The documentation page says "The converted character string is also adjusted according to the local time zone settings. ".  However, the functions (asctime() etc.) make no such adjustment - they simply print a formatted version of the numeric values stored in the tm structure.

Regards,
Mike. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66cc47e7-1a13-2113-b6bb-bc3d9d0ba663
* Version Independent ID: 67ab5660-be1c-03aa-526d-c2e843d8ae61
* Content: [asctime, _wasctime](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/asctime-wasctime?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/asctime-wasctime.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/asctime-wasctime.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@darjeeling-uk, you are quite right. I have fixed the topic and it should be live by EOD Tues, 12/22
Thank you for pointing this out.
