### ISSUE TITLE
Where is the description of concrt.dll?

### ISSUE THREAD

**Issue by CaryFan** [MicrosoftDocs/cpp-docs#341]
The concrt.dll is not mentioned unfortunately. But we can see the VS specific version like concrt140.dll in the VS2017 VC Redist folder. I guess it is missing. Could you please add the description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
added. should be visible by 08/20. thanks @CaryFan !
