### ISSUE TITLE
Suggestion to save paper space

### ISSUE THREAD

**Issue by mohammad-ghasemi-2549** [MicrosoftDocs/cpp-docs#3413]
When printing MSDN articles a lot of paper space get wasted on the top of the page where "In this article" hyperlinks are located. That is because the links are arranged vertically. If they are arranged horizontally when printing, they occupy only one line most of the time. And this saves a lot of paper space.
Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5fca51-7296-4ddb-921a-79d8806fc5a8
* Version Independent ID: d6d6ee58-f60d-fbd0-ce86-c6be3c8ba9c1
* Content: [remove, _wremove](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/remove-wremove?view=msvc-160#feedback)
* Content Source: [docs/c-runtime-library/reference/remove-wremove.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/remove-wremove.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@mohammad-ghasemi-2549 
I like this issue, but it's in the wrong place. We don't control presentation or printing here in the C++ docs repo. Instead, there's another place for feedback about Microsoft Docs as a whole: [https://github.com/MicrosoftDocs/feedback/issues](https://github.com/MicrosoftDocs/feedback/issues). That's where to repeat this issue, and where people who can actually do something about it will look at the problem. Thanks for bringing it up with them. I'd like to see it fixed, too.
