### ISSUE TITLE
WTH does this mean?

### ISSUE THREAD

**Issue by AJMauger** [MicrosoftDocs/cpp-docs#3414]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592ebebd-cf8b-9621-efdd-08c159f7e716
* Version Independent ID: a6722576-e4e4-e7d1-34b1-f2a5074534e9
* Content: [Compiler Warning (level 3) C4192](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4192?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-3-c4192.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-3-c4192.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AJMauger 
Sorry it's giving you difficulty. The article does make some assumptions that you know something about type libraries and how they're defined and used. Can you be more specific about what you were expecting to find, that isn't explained here?
