### ISSUE TITLE
Outdated ANSI Conformance documentation.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/cpp-docs#3420]
Information outdated given that Visual Studio now supports C11 and C17.

https://docs.microsoft.com/en-us/cpp/overview/install-c17-support?view=msvc-160

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f12c7d5-d278-39ec-4430-285744352b39
* Version Independent ID: db65b75a-da36-00ee-6ee4-e7837d209eac
* Content: [ANSI Conformance](https://docs.microsoft.com/en-us/cpp/c-language/ansi-conformance?view=msvc-160)
* Content Source: [docs/c-language/ansi-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/ansi-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
We keep this info around for people who must use that toolset.
