### ISSUE TITLE
Move Definition Location Shortcut

### ISSUE THREAD

**Issue by jbpend** [MicrosoftDocs/cpp-docs#3427]
There is a shortcut now for Extract Function (Ctrl-R, Ctrl-M).  Is there a similar shortcut for Move Definition Location?  Or is there a way to create a shortcut that will do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9dc9776-384b-e7a0-c82b-f7a09c578978
* Version Independent ID: c3cd3278-c274-ffa5-cf56-c960694b0588
* Content: [Move Definition Location](https://docs.microsoft.com/en-us/cpp/ide/refactoring/move-definition-location?view=msvc-160)
* Content Source: [docs/ide/refactoring/move-definition-location.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/refactoring/move-definition-location.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jbpend 
There isn't a default shortcut for Move Definition Location. You can tell if a shortcut is set: On the **Tools** menu, choose **Options**. In the **Options** dialog, expand **Environment** and select **Keyboard**. In **Show commands containing**, search for `Edit.MoveDefinitionLocation`. If a shortcut exists, it will appear in **Shortcuts for selected command**.

If there isn't a shortcut, or if you'd like to change the shortcut, you can create one. Choose **Remove** to remove an existing shortcut, if any. Set the cursor in **Press shortcut keys** and then press the key combination you'd like to apply, such as **Ctrl+M, Ctrl+D**. Choose **Assign** to set the keyboard shortcut. Choose **OK** to close the dialog. You should be good to go.
