### ISSUE TITLE
Duplicate sections on the page

### ISSUE THREAD

**Issue by soldis** [MicrosoftDocs/cpp-docs#3428]
The "The goto statement" and "The case statement" subsections are further repeated as independent sections on the same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf407fc-4210-de79-9afb-f06452244844
* Version Independent ID: 72412cad-7448-a3da-15e9-313504553c08
* Content: [Labeled Statements](https://docs.microsoft.com/en-us/cpp/cpp/labeled-statements?view=msvc-160)
* Content Source: [docs/cpp/labeled-statements.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/labeled-statements.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@soldis 
Thanks for the report. A fix should appear in a day or so.
