### ISSUE TITLE
_strncnt not available in tchar.h

### ISSUE THREAD

**Issue by RickDaniels314** [MicrosoftDocs/cpp-docs#3429]
Problem
---------
tchar.h does not allow use of _strncnt when _UNICODE macro is defined.

Recommended Solution
---------------------------
Change tchar.h to allow use of both _strncnt and _wcsncnt independent of _UNICODE / UNICODE macros. 
(i.e., tchar.h should always make _strncnt and _wcsncnt avaiable (independent of _UNICODE / UNICODE macros).

That way a C program can use both _strncnt and _wcsncnt depending on the character set coming in from a file or other source.

The -UNICODE / UNICODE macros should only affect what _tcsnbcnt maps to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12099a42-d082-0656-41c2-c3520b5e256a
* Version Independent ID: fa6454b0-a369-a98b-15d2-265cd0c68e4d
* Content: [_strncnt, _wcsncnt, _mbsnbcnt, _mbsnbcnt_l, _mbsnccnt, _mbsnccnt_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncnt-wcsncnt-mbsnbcnt-mbsnbcnt-l-mbsnccnt-mbsnccnt-l?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/strncnt-wcsncnt-mbsnbcnt-mbsnbcnt-l-mbsnccnt-mbsnccnt-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strncnt-wcsncnt-mbsnbcnt-mbsnbcnt-l-mbsnccnt-mbsnccnt-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@RickDaniels314 
Thanks for creating a clear explanation of the issue and a way to fix it. Unfortunately, it's addressed to the wrong audience. The documentation team can't change the product. Instead, I recommend bringing this issue up on [Developer Community](https://aka.ms/vsfeedback/browsecpp), where it can be seen by the product team. They'll take this under consideration. In the meantime, I'm closing this as not a documentation issue.
