### ISSUE TITLE
Visual studio Compilation error

### ISSUE THREAD

**Issue by Susisasa** [MicrosoftDocs/cpp-docs#3439]
I don't even know how to explain this so i'll attach some images...Can someone help me please?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CVT1107	'C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\ole32.lib' is corrupt	Tavola ASCII-Tavola pitagorica	D:\Scuola\Informatica\Visual studio\Tavola ASCII-Tavola pitagorica\CVTRES	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1123	failure during conversion to COFF: file invalid or corrupt	Tavola ASCII-Tavola pitagorica	D:\Scuola\Informatica\Visual studio\Tavola ASCII-Tavola pitagorica\LINK	1	

![error](https://user-images.githubusercontent.com/92176972/136596420-ac05e301-fdaa-4a82-a6d8-92c3d5b3b00c.png)
![Error3](https://user-images.githubusercontent.com/92176972/136596425-a601dabf-c5c3-4500-b6ac-3351c5e9c770.png)
![Error 2](https://user-images.githubusercontent.com/92176972/136596426-66e8ff05-80b4-45f5-aa7d-db2aeecabfb9.png)

**Comment by corob-msft** [comment]
@Susisasa 
I'm sorry no one replied here. The trouble is, you're asking for help in the wrong place. A support question like this one belongs in [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or a similar forum, such as [StackOverflow](https://stackoverflow.com/questions/tagged/visual-c%2b%2b). I'm closing this as it's not a documentation issue.
