### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Fady1Hany** [MicrosoftDocs/cpp-docs#3441]
[Enter feedback here]
A void pointer can point to a function, but not to a class member in C++.
when i try i found that A void pointer could point to a static member function and could point to class members variables like ( int X , float Y )  
So i think when you wrote this statement you meant this "A void pointer can point to a function, but not to a class non static member function in C++."  ,right?
you did not mean that "A void pointer can not point to any class member in C++." , right?
If the answers two questions above is right please edit the statement .  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06924698-5d51-7597-3aa0-80738e561248
* Version Independent ID: 45016f75-582b-d9b2-0bdd-16854c1ddb3a
* Content: [void (C++)](https://docs.microsoft.com/en-us/cpp/cpp/void-cpp?view=msvc-160)
* Content Source: [docs/cpp/void-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/void-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Fady1Hany 
The sentence was apparently relying on context implied by the earlier part of the sentence, which is talking about pointers to functions. I've clarified it with a fix, which should be visible by the end of our next business day.
