### ISSUE TITLE
I want to compile the project with Microsoft "C++ Clang tools for Windows". but I don't know what to do.

### ISSUE THREAD

**Issue by send010** [MicrosoftDocs/cpp-docs#3442]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cabdd4-5ef1-1c19-4a82-5448a5901e8a
* Version Independent ID: 56fd7d96-62ec-07df-40df-aaf155d504d3
* Content: [Clang/LLVM support in Visual Studio projects](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-160)
* Content Source: [docs/build/clang-support-msbuild.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/clang-support-msbuild.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@send010 
I'm sorry you're having trouble, and for the delay in getting back to you. 
Your question doesn't have enough information for us to help you. The page describes how to set up a project to use the Clang tools. Once you've installed the clang tools in the Visual Studio Installer, and set up the project to use the tools, then they're used automatically when you build the project. Is there a particular part of the documentation that doesn't work for you?

**Comment by corob-msft** [comment]
Closing as not repro.
