### ISSUE TITLE
Update CMake Presets for compiling with clang-cl

### ISSUE THREAD

**Issue by sweemer** [MicrosoftDocs/cpp-docs#3446]
Currently the [instructions](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-160) for configuring clang-cl builds in Visual Studio with CMake Presets are as follows:

```json
"cacheVariables": {
  "CMAKE_BUILD_TYPE": "Debug",
  "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
  "CMAKE_C_COMPILER": "clang-cl",
  "CMAKE_CXX_COMPILER": "clang-cl"
},
```

However I'm wondering why the `toolset` configure preset is not used instead like so:

```json
"cacheVariables": {
  "CMAKE_BUILD_TYPE": "Debug",
  "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}"
},
"toolset": "ClangCL",
```

As far as I understand, this approach leverages the schema of CMake Presets more directly, so should be preferred.

Also this approach has the added benefit of working in Visual Studio Code as well with no additional configuration required. (The current instructions to use `CMAKE_CXX_COMPILER` do not work in Visual Studio Code or on the command line without `vcvarsall.bat`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-160)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by sfreed141** [comment]
@sweemer did you verify this works? I don't believe ClangCL is a valid toolset (I tried on command line):
<img width="624" alt="image" src="https://user-images.githubusercontent.com/6880264/145863028-650c81ad-4312-47d0-a3f4-56e0c330d3dc.png">

Another consideration is specifying the toolset (which maps to the -T flag) is only valid for certain generators.

**Comment by sweemer** [comment]
Thanks for taking a look at this @sfreed141.

This works just fine for me in a fresh Git Bash session. Not sure whether it works by accident in my environment, or whether it should work everywhere. I would hope the latter.

```
$ mkdir clangcl && cd clangcl

$ echo "project(clangcl LANGUAGES CXX)" > CMakeLists.txt

$ /e/cmake-3.22.1-windows-x86_64/bin/cmake.exe -G "Visual Studio 17 2022" -T ClangCL -B out
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The CXX compiler identification is Clang 12.0.0 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/Microsoft Visual Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Code/clangcl/out
```

Also note that this issue is titled _Update CMake Presets for compiling with clang-cl_, so it is specifically about getting CMake Presets to work with the ClangCL toolset, and not about using CMake without presets (although as shown above that works as well).

If I add a `CMakePresets.json` file to my sample project above then it also works as intended. Again not sure whether this is by accident or by design, but so far it has served me well and I believe other users should know about this functionality as well.

```
$ cat CMakePresets.json
{
    "version": 2,
    "configurePresets": [
      {
        "name": "windows-clang-x64",
        "binaryDir": "${sourceDir}/out",
        "generator": "Visual Studio 17 2022",
        "toolset": "ClangCL",
        "architecture": {
          "value": "x64",
          "strategy": "external"
        },
        "vendor": {
          "microsoft.com/VisualStudioSettings/CMake/1.0": {
            "intelliSenseMode": "windows-clang-x64",
            "hostOS": [
              "Windows"
            ]
          }
        }
      }
    ]
  }

$ /e/cmake-3.22.1-windows-x86_64/bin/cmake.exe --preset windows-clang-x64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The CXX compiler identification is Clang 12.0.0 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/Microsoft Visual Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Code/clangcl/out
```

**Comment by sfreed141** [comment]
Thanks for confirming. I dug into it some more and it wasn't working for me because of https://github.com/microsoft/vcpkg/issues/15623 :( After I removed vcpkg using ClangCl for the toolset works. I believe it only works for the VS generators though (based on [this bit in CMake source](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/CMakeDetermineCompilerId.cmake#L340))
