### ISSUE TITLE
Re-add 2005 redist

### ISSUE THREAD

**Issue by dxgldotorg** [MicrosoftDocs/cpp-docs#3457]
Consider re-adding the latest 2005 redists since some older applications still depend on them.  While platforms like Steam do distribute them, some freeware applications might not include them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-160)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dxgldotorg 
As far as I can discover, the VC 2005 Redistributables aren't available as a public download on Microsoft's servers. Microsoft may include these Redistributables with other software that is still in support, but I can't find them as a separate download. I have no reasonable expectation that this can be changed, given that the product has been out of extended support for six years. So, with nothing to link to, I can't address your request. Sorry.

**Comment by dxgldotorg** [comment]
Actually it is still offered for download:  https://www.microsoft.com/en-us/download/details.aspx?id=26347
