### ISSUE TITLE
Compiler warning C5033 is not documented.

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/cpp-docs#3462]
To see the warning:
1) Create a solution using the compiler in C++ 17 mode (e.g. /std:c++17 ), and include a variable declared using the old register keyword, e.g.:
	register int a = 13;
2) Try to compile it. A warning is seen on the variable declaration, similar to this:
warning C5033: 'register' is no longer a supported storage class

3) However there is no documentation for the C5033 warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc3041c-b233-bb3f-513f-b3df302b49a2
* Version Independent ID: aad153bd-a417-01fb-f2b7-50842269dcc0
* Content: [Compiler warnings C4800 Through C5999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MikeDiack 
Thanks for the report. We're aware of lots of missing detailed diagnostic articles, and filling them in is usually a low-priority task. Just for you, I wrote this one up, though as the current landing page warns, it's not going to tell you very much more than the warning itself. The `register` keyword was deprecated in C++11 and C++14, and removed from the language in C++17. It hasn't been used by the common C++ compilers to cause variables to be placed in registers in decades. Basically, `register` never did what you thought, and in recognition of the fact, the language standard has finally gotten around to booting it. Look for updated docs in a day or so.
