### ISSUE TITLE
Please provide all last versions of non supported applications dlls for download like vs2005/ vs2008

### ISSUE THREAD

**Issue by wesleyolis** [MicrosoftDocs/cpp-docs#3478]
[Enter feedback here]
Please provide all last versions of non supported applications dlls for download like vs2005/ vs2008,
as they still need due so much old source code lying around, which companies are now starting to re-write.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This was fixed in November, but I forgot to close this issue.
