### ISSUE TITLE
cl: 命令行 error D8049,文档未记录

### ISSUE THREAD

**Issue by Dylan-lijl** [MicrosoftDocs/cpp-docs#3481]
cl: 命令行 error D8049 :无法执行“C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\c1xx.dll”: 命令行太长，无法适应调试记录

**Comment by corob-msft** [comment]
@Dylan-lijl 
I'm sorry it's giving you trouble. For a description and possible solutions, see [Command-line error D8049](https://docs.microsoft.com/cpp/error-messages/tool-errors/command-line-error-d8049?view=msvc-160).
