### ISSUE TITLE
Add Class description does not reflect reality!

### ISSUE THREAD

**Issue by howardjones** [MicrosoftDocs/cpp-docs#3482]
I found this page while I was looking for how to extend an ATL project. It says that you can choose from different templates after you have selected Add Class. Here is what my Add Class dialog box looks like in VS 2019. There are no template options.

![image](https://user-images.githubusercontent.com/912421/139297836-092bc285-3dbb-48f5-849d-990d6d09445c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31466b00-8bc2-51bd-82ca-4a59d97b4e5e
* Version Independent ID: b473027e-c85e-bcea-6b8d-88947802f876
* Content: [Add a class](https://docs.microsoft.com/en-us/cpp/ide/adding-a-class-visual-cpp?view=msvc-160#add-class-dialog-box)
* Content Source: [docs/ide/adding-a-class-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/adding-a-class-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@howardjones 
I'm sorry the document is out of date for recent versions of Visual Studio. The ATL documentation is in maintenance-only mode, and we don't prioritize it, given our resource constraints. Some time ago, the Add new class dialog was redesigned for accessibility, so now you just get the the [generic class wizard](https://docs.microsoft.com/en-us/cpp/ide/adding-a-generic-cpp-class?view=msvc-140#generic-c-class-wizard). If you invoke the Class Wizard instead, you should be able to create classes from templates, if they're installed. Right-click your project in **Solution Explorer** and choose **Class Wizard** from the shortcut menu. The **Add Class** button on the dialog has a drop-down control for choosing a template. Some templates and wizards aren't supported anymore, such as OLE DB. If you need an older wizard, a copy of Visual Studio 2015 can generate the code, which you can bring into the current IDE.

**Comment by corob-msft** [comment]
The documentation has been updated for more recent versions of Visual Studio.
