### ISSUE TITLE
`thread_local` doc does not warn about incompatibility with `std::launch::async`

### ISSUE THREAD

**Issue by LittleBoxOfSunshine** [MicrosoftDocs/cpp-docs#3483]
As covered in https://github.com/microsoft/STL/issues/949 and https://github.com/MicrosoftDocs/cpp-docs/issues/308 MSVC's STL implementation violates the standard by using a thread pool to implement `std::launch::async` instead of the prescribed new thread.

Ideally this would receive it's own documentation page or FAQ entry (see discussion in https://github.com/microsoft/STL/issues/949), but failing that there should be a warning here that mirrors the warning found in the async docs:

> The C++ standard states that if policy is launch::async, the function creates a new thread. However the Microsoft implementation is currently non-conforming. It obtains its threads from the Windows ThreadPool, which in some cases may provide a recycled thread rather than a new one. This means that the launch::async policy is actually implemented as launch::async|launch::deferred. Another implication of the ThreadPool-based implementation is that there is no guarantee that thread-local variables will be destroyed when the thread completes. If the thread is recycled and provided to a new call to async, the old variables will still exist. We therefore recommend that you do not use thread-local variables with async.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66737d90-dbf1-88c9-3fa1-dcb00c335467
* Version Independent ID: 7292bb09-ee1a-1ae6-1985-631cdf24a27d
* Content: [Storage classes (C++)](https://docs.microsoft.com/en-us/cpp/cpp/storage-classes-cpp?view=msvc-160)
* Content Source: [docs/cpp/storage-classes-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/storage-classes-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LittleBoxOfSunshine 
Thanks for the report. I've added a bullet point in the `thread_local` section with a summary of the issue and a link to the discussion in [`<future>` functions](https://docs.microsoft.com/en-us/cpp/standard-library/future-functions?view=msvc-160).
