### ISSUE TITLE
<robuffer.h> issue

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/cpp-docs#349]
When I add the include for robuffer.h I get "Windows" is ambiguous several times, and everything else becomes errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e19502-b389-d887-6d40-1cb77a04e2a6
* Version Independent ID: 9c448eee-c06d-a0a3-e374-1eb0fd250a11
* Content: [Obtaining pointers to data buffers (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/obtaining-pointers-to-data-buffers-c-cx)
* Content Source: [docs/cppcx/obtaining-pointers-to-data-buffers-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/obtaining-pointers-to-data-buffers-c-cx.md)
* Product: **visual-cpp**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by mikeblome** [comment]
@Gavin-Williams apologies for delayed response! Is this still an issue for you? If so, is this happening in a C++ UWP project and which Windows SDK are you using?
