### ISSUE TITLE
double -> float conversion

### ISSUE THREAD

**Issue by dh1dm** [MicrosoftDocs/cpp-docs#3491]
When exceeding range in a double to float conversion the result is not undefined but infinity.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98997f65-f16f-0306-0255-58ddaa17617a
* Version Independent ID: 280ad276-c59b-7221-abf6-7b54ebf9e3db
* Content: [Conversions from floating-point types](https://docs.microsoft.com/en-us/cpp/c-language/conversions-from-floating-point-types?view=msvc-160)
* Content Source: [docs/c-language/conversions-from-floating-point-types.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/conversions-from-floating-point-types.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dh1dm 
Thanks for the report. The text had it right, but the table might have been confusing. An update should be visible shortly.
