### ISSUE TITLE
`experimental:module` and `/std:c++20`

### ISSUE THREAD

**Issue by andrewvaughanj** [MicrosoftDocs/cpp-docs#3494]
I believe that, if you want to use the standard library modules (e.g., `std.core`) with MSVC, you need to be using `/std:c++latest`, and `/std:c++20` is not sufficient.

Indeed, if you do just use `/std:c++20`, then you get a warning (which becomes an error with `/WX`):

- https://developercommunity.visualstudio.com/t/possible-incompatible-environment-while-importing/1567681

This then makes:

> You can use the modules feature to create single-partition modules and to import the Standard Library modules provided by Microsoft. To enable support for modules, compile with /experimental:module and /std:c++20 or later (such as /std:c++latest).
>

be misleading, because to use the standard library modules, you cannot just use `/std:c++20`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-160)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@andrewvaughanj 
Thanks for the report. You are correct. I've added some clarification to the relevant docs. C++ Standard modules are supported under **`/std:c++20`**, but the extension that implements standard library modules requires **`/std:c++latest`** and **`/experimental:module`** as those are proposed for the next standard.
