### ISSUE TITLE
Char to double is narrowing!

### ISSUE THREAD

**Issue by programehr** [MicrosoftDocs/cpp-docs#3496]
Hi,
The document says that converting from char to any built-in type is a widening conversion. However, I get C2397 from this code:
```
int main()
{
	char x = 3;
	double y{ x };
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4febd6ec-05d8-97cf-fb9f-fc41e4ee2142
* Version Independent ID: afe287bd-011f-90f2-eef4-2559e405d277
* Content: [Type conversions and type safety](https://docs.microsoft.com/en-us/cpp/cpp/type-conversions-and-type-safety-modern-cpp?view=msvc-160)
* Content Source: [docs/cpp/type-conversions-and-type-safety-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/type-conversions-and-type-safety-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@programehr 

Interesting. It appears to only happen when the initializer list contains a variable, not a literal. I recommend bringing this question up on [Developer Community](https://aka.ms/vsfeedback/browsecpp). It may be a product issue. I'm not willing to call it a documentation issue on the page you've cited, so I'm closing this, but feel free to follow up here with any response from the dev team.

Here's my expanded test code; notice how a double takes narrower literals just fine:

```
C:\Users\corob\Documents\Projects\curiosity\narrowing>type narrowing.cpp
int main()
{
    char c = 3;
    short s = 23;
    unsigned short us = 23;
    int n = 42;
    double dc { c };
    double ds { s };
    double dus{ us };
    double dn { n };
    double dlc { 'a' };
    double dls { (short)42 };
    double dlus { (unsigned short)14 };
    double dln { 1729 };
}

C:\Users\corob\Documents\Projects\curiosity\narrowing>cl /EHsc /diagnostics:caret narrowing.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30136 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

narrowing.cpp
narrowing.cpp(7,19): error C2397: conversion from 'char' to 'double' requires a narrowing conversion
    double dc { c };
                  ^
narrowing.cpp(8,19): error C2397: conversion from 'short' to 'double' requires a narrowing conversion
    double ds { s };
                  ^
narrowing.cpp(9,20): error C2397: conversion from 'unsigned short' to 'double' requires a narrowing conversion
    double dus{ us };
                   ^
narrowing.cpp(10,19): error C2397: conversion from 'int' to 'double' requires a narrowing conversion
    double dn { n };
                  ^
```
