### ISSUE TITLE
lib.exe missing doc

### ISSUE THREAD

**Issue by Brynyard** [MicrosoftDocs/cpp-docs#3498]
Most of the options to lib.exe isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64e0671-42d6-8a30-ebff-d2b501d731c1
* Version Independent ID: 2f675905-9ad0-14bd-2b1b-c2f08fd831dd
* Content: [Running LIB](https://docs.microsoft.com/en-us/cpp/build/reference/running-lib?view=msvc-160)
* Content Source: [docs/build/reference/running-lib.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/running-lib.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Brynyard 
I'm sorry you're having trouble finding information. The LIB tool options are all documented, but not in individual articles like the LINK options. You'll find them listed under [LIB Options](https://docs.microsoft.com/en-us/cpp/build/reference/overview-of-lib?view=msvc-160#lib-options) on the Overview page. Most options are identical to the LINK options with the same names. The LIB tool adds [/EXTRACT](https://docs.microsoft.com/cpp/build/reference/extracting-a-library-member), [/LIST](https://docs.microsoft.com/cpp/build/reference/managing-a-library), [/NAME](https://docs.microsoft.com/cpp/build/reference/managing-a-library), and [/REMOVE](https://docs.microsoft.com/cpp/build/reference/managing-a-library) options. 

Is there a specific option you're looking for more information about?

**Comment by Brynyard** [comment]
No, I was just fooled by the bad structure on the page, silly me thought
"Running LIB" actually contained information on options when running it, it
appears all the details are listed in the overview section instead.

 - Barnyard

**Comment by corob-msft** [comment]
Well, I can't say I'd organize LIB the docs like this either, but they haven't changed in many, many years, and while rearranging them for ease of use is a great idea, it's unfortunately such a low priority that, given our resources, I have to say it will probably never happen. So, I'm closing this issue with some disappointment that I can't make it better. Sorry.
