### ISSUE TITLE
The "Template friends" section is a copy of the next chapter!

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/cpp-docs#350]
https://docs.microsoft.com/en-us/cpp/cpp/class-templates#template-friends
equals to
https://docs.microsoft.com/en-us/cpp/cpp/template-friends

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1973bcf0-42db-7302-d4af-93b12b824b26
* Version Independent ID: 4766da4c-9620-ddc0-0251-dcaa644b0e51
* Content: [Class Templates](https://docs.microsoft.com/en-us/cpp/cpp/class-templates)
* Content Source: [docs/cpp/class-templates.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/class-templates.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
removed duplicate topic. should be visible 08/21. thanks @baruchiro  !
