### ISSUE TITLE
Union with methods

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/cpp-docs#351]
Add documentation for methods in unions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a72b499a-3b65-4005-32dd-a6be9100a975
* Version Independent ID: aaa2c0c5-677c-4fb6-cca8-9d4a7aa9122f
* Content: [Unions](https://docs.microsoft.com/en-us/cpp/cpp/unions)
* Content Source: [docs/cpp/unions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
thanks @baruchiro . I have added this work item to our backlog.

**Comment by mikeblome** [comment]
Closing as duplicate of internal work item.
