### ISSUE TITLE
Unable to view cmakesettings.json in Visual Studios 2022.

### ISSUE THREAD

**Issue by leekahwai** [MicrosoftDocs/cpp-docs#3512]
Have an cmakesettings.json in a cmake project that is working on Visual Studios 2019 professional - targeting Linux and Windows pipelines. Upon installing Visual Studios 2022 professional, the same cmakesettings.json is unable to be edited or view, with feedback on telling me that it needs more time on intellisense. However, the configuration seems to still able to detect the pipelines, which at least let me work.

Separate question on whether Microsoft intends developers to use cmakepresets now.

**Comment by corob-msft** [comment]
@leekahwai 
The first question is best directed at [Developer Community](https://aka.ms/vsfeedback/browsecpp). It sounds like a product issue to me, and we only support the docs here, not the product itself. As for the second question, yes, CMake presets files are supported now, but I wouldn't go so far as to ascribe intent to that other than making as many common development options available for CMake users as are practical, and reducing CMake friction points in Visual Studio.
