### ISSUE TITLE
C26462 misleading description

### ISSUE THREAD

**Issue by chrchr-github** [MicrosoftDocs/cpp-docs#3513]
_The value pointed to by 'p' is assigned only once, mark it as a pointer to const (con.4)._

I think this sentence is incorrect, since the value pointed to by `p` isn't assigned at all, which is why `p` can be `const int*`.
Suggestion:
_The value pointed to by 'p' is not modified, mark 'p' as a pointer to const (con.4)._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3b2ce4-5f2f-ed0b-d232-c4dd7eabd2c3
* Version Independent ID: 41ab21b5-ad62-00ad-cdc5-431279dfeb92
* Content: [C26462](https://docs.microsoft.com/en-us/cpp/code-quality/c26462?view=msvc-170)
* Content Source: [docs/code-quality/c26462.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26462.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chrchr-github 

Thanks for writing in. The text in the documentation is a quote of the error message itself. If you think the error message should be changed, then that's a product issue. You can submit product issues on [Developer Community](https://aka.ms/vsfeedback/browsecpp), where the product team will see it, and take action if appropriate. They'll let us know if the documentation needs to be changed to match.
