### ISSUE TITLE
The SAL documentation should really mention that you have to #include <sal.h>

### ISSUE THREAD

**Issue by DanielGibson** [MicrosoftDocs/cpp-docs#3517]
The examples would be a lot more helpful if at least the first one had an `#include <sal.h>` line, because the needed header generally isn't mentioned much in the documentation (and not at all together with "include" that one might search for).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a052b3f2-97ef-3c75-3b0c-432a072eb76b
* Version Independent ID: 1581c417-5ef9-e357-3e29-0b8bd453ad54
* Content: [Best Practices and Examples (SAL)](https://docs.microsoft.com/en-us/cpp/code-quality/best-practices-and-examples-sal?view=msvc-170)
* Content Source: [docs/code-quality/best-practices-and-examples-sal.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/best-practices-and-examples-sal.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DanielGibson 
Not a bad idea, thanks. A fix has been applied and the updated docs are now live.
