### ISSUE TITLE
If default capture is specified, it must be the first element in capture bracket

### ISSUE THREAD

**Issue by pstricks-fans** [MicrosoftDocs/cpp-docs#3518]
Two commented rows provided by MSDN will  not compile. Why? Because default capture & or = can only appear as the first element if we need it. 

```
[&total, factor]
[&total, =] // <-------- does not compile
[factor, &total]
[&, factor]
[factor, &]// <-------- does not compile
[=, &total]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 437be494-4752-c2de-a8c0-c4bc8563ddb4
* Version Independent ID: 51317bb8-4c01-146a-f1a7-eba0e54cb5e4
* Content: [Lambda expressions in C++](https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)
* Content Source: [docs/cpp/lambda-expressions-in-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/lambda-expressions-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pstricks-fans 
Thanks for pointing that out. A fix has been published and is visible now.
