### ISSUE TITLE
Formatting in remarks for strrchr appears incorrect

### ISSUE THREAD

**Issue by contre** [MicrosoftDocs/cpp-docs#352]
When looking at the remarks section, there appears to be an issue with the markup which is showing a few too many *s when discussing the various forms of the function.

> In C, these functions take a const ** pointer for the first argument. In C++, two overloads are available. The overload taking a pointer to **const ** returns a pointer to **const **; the version that takes a pointer to non-const ** returns a pointer to non-const **. The macro **_CRT_CONST_CORRECT_OVERLOADS is defined if both the const ** and non-const ** versions of these functions are available. If you require the non-const ** behavior for both C++ overloads, define the symbol **_CONST_RETURN.

I believe it is intended that some instances of ** should be single *s but in others I am not sure what the intention is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a34485-78c0-9f37-8cbe-dcbc7e29ad69
* Version Independent ID: dd892148-f8b3-6fdc-7c3b-4d702b911c4b
* Content: [strrchr, wcsrchr, _mbsrchr, _mbsrchr_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strrchr-wcsrchr-mbsrchr-mbsrchr-l)
* Content Source: [docs/c-runtime-library/reference/strrchr-wcsrchr-mbsrchr-mbsrchr-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strrchr-wcsrchr-mbsrchr-mbsrchr-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @contre ! Fixed.
