### ISSUE TITLE
Not clear how to use libfuzzer

### ISSUE THREAD

**Issue by Ono-Sendai** [MicrosoftDocs/cpp-docs#3520]
I enabled /fsanitize=fuzzer but it seems to have no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4188aa57-8820-50cd-308e-08ee33ff1bd0
* Version Independent ID: f14d999f-67c6-bdd5-eac6-f02d8e32a2ec
* Content: [/fsanitize (Enable sanitizers)](https://docs.microsoft.com/en-us/cpp/build/reference/fsanitize?view=msvc-160&preserve-view=true)
* Content Source: [docs/build/reference/fsanitize.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fsanitize.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ono-Sendai 
I'm sorry you're having trouble. There's no documentation issue I can identify here, so I'm closing it. If you can tell that your fuzzer test entry function isn't being called, then that sounds like an issue for the product team. You can describe what's going on and get assistance on [Developer Community](https://aka.ms/vsfeedback/browsecpp). Best of luck.

**Comment by Ono-Sendai** [comment]
What should the fuzzer test entry function be called?  What linkage should it have? etc..?
I didn't see that documented.

**Comment by corob-msft** [comment]
Our documentation on libFuzzer use with Visual Studio tools is in the Address Sanitizer docs under the heading [/fsanitize=fuzzer compiler option (experimental)](https://docs.microsoft.com/cpp/sanitizers/asan-building?view=msvc-160#fsanitizefuzzer-compiler-option-experimental). You need to create your own entry point function with a signature like so:

`extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size);`

We don't document libFuzzer itself, as it's an LLVM project. You'll find the documentation for the libfuzzer library at [libFuzzer – a library for coverage-guided fuzz testing](https://llvm.org/docs/LibFuzzer.html).

**Comment by corob-msft** [comment]
I may not have answered the linkage question. The `/fsanitize:fuzzer` compiler option will invoke the library that matches your library build option and target architecture. There are variants for `/MD`, `/MDd`, `/MT`, `/MTd`, in s86_64 or i386 flavors. I don't think ARM or ARM64 are supported, but I haven't installed those toolsets yet, so I don't know for sure.
