### ISSUE TITLE
absurd example

### ISSUE THREAD

**Issue by LambertWM** [MicrosoftDocs/cpp-docs#3521]
the example:
fopen( "test.c", "r" ); // C4996, C6031 return value ignored

is kind of absurd - who who would call fopen( ) to open a file for reading AND NOT store the result to read from the file?
a better example would be to ignore the result of fread( ) or fwrite( )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b4afca-d37c-2e80-7819-bd835396d39f
* Version Independent ID: 5543db08-c55c-9d39-b569-de9833c4be28
* Content: [C6031](https://docs.microsoft.com/en-us/cpp/code-quality/c6031?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C6031)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/code-quality/c6031.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6031.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LambertWM 
Thanks for commenting. While it does seem unlikely in practice, the first example has the advantage of being a clear issue with a single line of code, which we try to economize on in samples. For illustrative purposes, sometimes the obviously wrong is better than the realistically wrong. I don't feel a need to change it.
