### ISSUE TITLE
Function Type: Typo?

### ISSUE THREAD

**Issue by lmstearn** [MicrosoftDocs/cpp-docs#3524]
Regarding this extract

> Parameters
> Fey
> The type of the object to call.
> 
Fey is FT, function type. Correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 446d9664-c85d-efb0-23c6-3ee39e09ce6d
* Version Independent ID: 22d6993c-6d7e-cad6-f57a-0d70d44d918c
* Content: [&lt;functional&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/functional-functions?view=msvc-170)
* Content Source: [docs/standard-library/functional-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/functional-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@lmstearn, thank you for pointing this out. I fixed that, also documented the RTy parameter. The fix should be live by the afternoon of 12/13 (US Pacific time)
