### ISSUE TITLE
Declaration error

### ISSUE THREAD

**Issue by SzalonyOgrodnik** [MicrosoftDocs/cpp-docs#3528]
[Enter feedback here]
There is set_time declaration instead of get_time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e9f51e-f7f3-28e7-2257-1d4a17982278
* Version Independent ID: 48e5bc45-62f0-28b6-f9f1-9b4c922a136f
* Content: [&lt;iomanip&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/iomanip-functions?view=msvc-160&redirectedfrom=MSDN&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(std%253A%253Aput_time)%3Bk(put_time)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue#iomanip_put_time)
* Content Source: [docs/standard-library/iomanip-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/iomanip-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@SzalonyOgrodnik , thank you for bringing this to our attention. I fixed it and added an example. It should be live by Monday afternoon.
