### ISSUE TITLE
This does not appear to be written for VS2019

### ISSUE THREAD

**Issue by grantcurell** [MicrosoftDocs/cpp-docs#3529]
I'm not sure if this is out of date but my UI doesn't match these settings at all. Remote Build Machine is nowhere to be found under configuration properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a Linux MSBuild C++ project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=msvc-160#remote-settings)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
The screenshot may be out of date. I'll update it to match VS 2022.

**Comment by TylerMSFT** [comment]
@grantcurell, I'm not seeing what you report. I'm using VS 2022 and the screenshots are identical to what I see. And I see the Remote Build Machine option as expected in the project properties under General > Remote Build Machine. It's the 8th option down, under General (just under Platform Toolset).
Closing, but let me know if I'm missing something here.

**Comment by grantcurell** [comment]
@TylerMSFT I apologize for likely wasting your time. I just went back and reviewed. I hadn't used VS proper for about a decade and I probably was looking at the solution instead of the project or something. I have since got this working and it is where I expect it to be. I appreciate your taking a look though!
