### ISSUE TITLE
dup2() does not work anymore with universal CRT in msvc 2017

### ISSUE THREAD

**Issue by leok7v** [MicrosoftDocs/cpp-docs#353]
I just executed this code in msvc2017 and resulting "data" file is empty.
The reason is change in _iob[20] handling
_ACRTIMP_ALT FILE* __cdecl __acrt_iob_func(unsigned _Ix);
#define stdin  (__acrt_iob_func(0))
#define stdout (__acrt_iob_func(1))
#define stderr (__acrt_iob_func(2))
and _fileno(stdout) now returns -2
thus dup2(fd, 1) does NOT do what it suppose to do. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155c7b5a-b148-0736-b13f-fd271f15c832
* Version Independent ID: 60c21c6b-69ed-3458-1928-5172adb22a06
* Content: [_dup, _dup2](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/dup-dup2)
* Content Source: [docs/c-runtime-library/reference/dup-dup2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/dup-dup2.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by leok7v** [comment]
This was in SUBSYSTEM:WINDOWS and this is why _fileno(std***) returns -2
    freopen("NUL", "wt", stdout);
    int n1 = _fileno(stdout);
    // stdout now refers to file "data"
    if (-1 == _dup2(_fileno(DataFile), n1)) {
        perror("Can't _dup2 stdout");
        exit(1);
    }
Fixes the situation a bit but now both strings end up in data file.

**Comment by mikeblome** [comment]
@leok7v Hmmm I cannot repro this. The code example behaved exactly as advertised on my Visual Studio 15.8 build. Can you try upgrading and see if you still get the error?
