### ISSUE TITLE
missing entry for C3378

### ISSUE THREAD

**Issue by jessesna** [MicrosoftDocs/cpp-docs#3536]
A entry for
C3378: a declaration can be exported only from a module interface unit
is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2e5944-4d8c-4a65-1a8b-73d07d48421a
* Version Independent ID: 3d024d53-50a9-d41f-00b4-a4dbadfc041b
* Content: [Compiler errors C3300 Through C3399](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-errors-c3300-through-c3399?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-errors-c3300-through-c3399.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-2/compiler-errors-c3300-through-c3399.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Hi, we don't document all the compiler errors - only the ones that we think we can add some value to because they are unclear or obscure. This one is straightforward.
