### ISSUE TITLE
I don't understand why the locale is needed. In the example given I assume that the characters to be converted are U+3042 and U+3043. These are defined in the Unicode standard, and could be converted to a representation of the code point (a 23 bit number?) and then converted to UTS-16 following the Unicode standards without any reference to locales or code pages.

### ISSUE THREAD

**Issue by RichardAth** [MicrosoftDocs/cpp-docs#354]
I don't understand why the locale is needed. In the example given I assume that the characters to be converted are U+3042 and U+3043. These are defined in the Unicode standard, and could be converted to a representation of the code point (a 23 bit number?) and then converted to UTS-16 following the Unicode standards without any reference to locales or code pages.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc6ed00-cb96-a8a9-20e6-9442a199aea0
* Version Independent ID: 799bc7e4-3198-7b46-609a-d9863091bb06
* Content: [mbstowcs, _mbstowcs_l](https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/mbstowcs-mbstowcs-l)
* Content Source: [docs/c-runtime-library/reference/mbstowcs-mbstowcs-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/mbstowcs-mbstowcs-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by DefaultRyan** [comment]
The locale is needed to specify how the multibyte characters are encoded. In the example, the characters are encoded using the 932 Japanese code page. Alternatively, they could be encoded using UTF-8, which would interpret the bytes differently.

**Comment by mikeblome** [comment]
Thanks all!
