### ISSUE TITLE
MSVC v143 - VS 2019 C++ ARM64 build tools (latest)

### ISSUE THREAD

**Issue by dovdiienko-qlt** [MicrosoftDocs/cpp-docs#3546]
Looks like there is a typo:

```txt
 MSVC v143 - VS 2019 C++ ARM64 build tools (latest)
```
I believe it must be
```
MSVC v143 - VS 2022 C++ ARM64 build tools (latest)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee2df82f-2b71-839a-4817-7d4f863800a2
* Version Independent ID: fbf5b04c-6607-5dd6-c302-fe40fe79343b
* Content: [C++ Tools and Features in Visual Studio Editions](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-tools-and-features-in-visual-studio-editions?view=msvc-170)
* Content Source: [docs/overview/visual-cpp-tools-and-features-in-visual-studio-editions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-tools-and-features-in-visual-studio-editions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dovdiienko-qlt 
Thanks for the report. A fix should appear sometime tomorrow.
