### ISSUE TITLE
Simple Typo

### ISSUE THREAD

**Issue by bdlttp** [MicrosoftDocs/cpp-docs#3547]
[Enter feedback here]
It appears that there is a typo in the expected parsing - the second example. There are two slashes in the command line, and there are two slashes in the argv[0] item. Shouldn't there be only one slash in the argv[0] item? Note that in the situation where there are three slashes and a double-quote, the argv[0] item show (correctly) a single slash and a double-quote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c5ec8f-dc90-d0bd-5aa5-1340ccc877c3
* Version Independent ID: 19646aca-3da3-14e8-ea9a-fcb3020cf51c
* Content: [`main` function and command-line arguments (C++)](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170)
* Content Source: [docs/cpp/main-function-command-line-args.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/main-function-command-line-args.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bdlttp 
Armchair analysis of these examples is difficult. Sometimes the easiest way to find out what the parsing does is to try it. There's some handy example code right there you can use to test all of the examples. When I run it, I get exactly the results specified in the table.

It's easy to get confused by the `\` escape parsing done by the command processor before it invokes a program, and the `\` escape parsing done by the C runtime before `main` is invoked. It's especially annoying when the command is invoked in a batch file, which does another layer of its own parsing, or if you invoke your program by using a system call, which, unlike `cmd` or `ps`, skips any parsing before handing arguments off to the C runtime. At any rate, I believe the document is correct as written, so I'm closing the issue.
