### ISSUE TITLE
[wbuffer_convert] Incomplete class documentation

### ISSUE THREAD

**Issue by aprotyas** [MicrosoftDocs/cpp-docs#3549]
In the "Remarks" section of documentation for the [`wbuffer_convert Class`](https://docs.microsoft.com/en-us/cpp/standard-library/wbuffer-convert-class?view=msvc-170#remarks), the last line is incomplete.

Specifically, it reads:

```
A pointer to the allocated conversion object (which is freed when the wbuffer_convert
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bdeac4-a79e-bc17-06b7-548065646cba
* Version Independent ID: 8544bbdd-a81f-34a1-b383-0e0903f72d02
* Content: [wbuffer_convert Class](https://docs.microsoft.com/en-us/cpp/standard-library/wbuffer-convert-class?view=msvc-170)
* Content Source: [docs/standard-library/wbuffer-convert-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/wbuffer-convert-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@aprotyas, thank you for taking the time to point this out. I've fixed it to indicate that the conversion facet will be deleted when the wbuffer_convert is destroyed. The fix should be live tomorrow (11/30/2021)
