### ISSUE TITLE
Console APIs availability in RS4

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/cpp-docs#355]
Are the console APIs listed here supported now that UWP console apps are a thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0086976-3992-75a0-5cdc-0202b006a73a
* Version Independent ID: 26a32c12-0c9e-10a9-373c-85bae76e8555
* Content: [CRT functions not supported in Universal Windows Platform apps](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps)
* Content Source: [docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.md)
* Product: **visual-cpp**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by mikeblome** [comment]
Investigating.

**Comment by KevinLaMS** [comment]
Sorry for the delay Holo-Krzysztof:
At this point they are still not available.  It is on our backlog to consider.

Thanks for raising the issue.
Kevin Larkin 
Program Manager
