### ISSUE TITLE
This page is the number google result for me, yet doesn't describe how to get to the Property Page.

### ISSUE THREAD

**Issue by AdrianaIH** [MicrosoftDocs/cpp-docs#3553]
I see no Property Pages and the UI isn't intuitive to know what to click on to figure out how to add a .lib to my project.  I have to google more to find a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60125e5a-d81d-2d31-8eb6-7ff5e3bd8194
* Version Independent ID: b9d8af93-89cd-0a1a-8cde-63d7518eb512
* Content: [.Lib Files as Linker Input](https://docs.microsoft.com/en-us/cpp/build/reference/dot-lib-files-as-linker-input?view=msvc-170)
* Content Source: [docs/build/reference/dot-lib-files-as-linker-input.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dot-lib-files-as-linker-input.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AdrianaIH 
I'm sorry you had difficulty getting your task done. Lots of articles tell you to open the Property Pages dialog, so we have a common article, [Set C++ compiler and build properties in Visual Studio](https://docs.microsoft.com/cpp/build/working-with-project-properties?view=msvc-170), that explains how to open and use it. Did you see and follow the link? Was it helpful, or maybe it wasn't helpful?

**Comment by corob-msft** [comment]
Closed for lack of actionable info.
