### ISSUE TITLE
there's no decltype in unary expressions

### ISSUE THREAD

**Issue by markyin** [MicrosoftDocs/cpp-docs#3554]
[Enter feedback here]

decltype is not an operator. 

and it does not appear in the form of unary expression in cpp standard 2017(8.3 unary expressions).

so pls double check it . thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122b77d8-3c32-b5fd-856b-e5ddab9236c0
* Version Independent ID: c57ac308-5851-c966-3109-47c17a2cb1fc
* Content: [Expressions with Unary Operators](https://docs.microsoft.com/en-us/cpp/cpp/expressions-with-unary-operators?view=msvc-170)
* Content Source: [docs/cpp/expressions-with-unary-operators.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/expressions-with-unary-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@markyin 
Thanks for the report. An update should be visible sometime tomorrow.
