### ISSUE TITLE
"import module" doesn't work

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/cpp-docs#3558]
At least in vs2022, using the recommended syntax from this page `import module foo` doesn't work:
![image](https://user-images.githubusercontent.com/22989529/143792686-2495ee83-f25b-4f99-b09b-e68966b3a682.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b269d9-d8c6-3706-5550-c000ce0cdd75
* Version Independent ID: aef11501-ad70-82ab-a1ee-73114a6d3df7
* Content: [module, import, export](https://docs.microsoft.com/en-us/cpp/cpp/import-export-module?view=msvc-170)
* Content Source: [docs/cpp/import-export-module.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/import-export-module.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed by #3559 (thanks to @roxk) which should be published Monday.
