### ISSUE TITLE
Kill system

### ISSUE THREAD

**Issue by assasinfil** [MicrosoftDocs/cpp-docs#356]
explorer.exe couldnt start after reboot.
I added python tools in visual studio installer. This error was reproduced 2 times already. I use windows 10 installed updates: KB4103729 KB4287903 KB4338832 KB4338853 4343669 KB4338819.

**Comment by corob-msft** [comment]
I'm sorry the python installation is giving you trouble. Unfortunately, this isn't the best place to report such problems; this site is for documentation issues. I'd recommend trying the Visual Studio Developer Community pages. The [Visual Studio Questions](https://developercommunity.visualstudio.com/spaces/8/index.html) page is where to report problems with the IDE or installation. For issues specifically with the C++ compiler, linker, and other tools and libraries, use the [C++ Questions](https://developercommunity.visualstudio.com/spaces/62/index.html) page. Someone on one or the other of those sites may have reported a similar problem and found an answer, or you can create a new issue if you don't see a similar one.
