### ISSUE TITLE
white space in command line argument

### ISSUE THREAD

**Issue by joefiesta** [MicrosoftDocs/cpp-docs#3565]
[Enter feedback here]

The statement:
 
     "Arguments are delimited by white space, which is either a space or a tab."

is not entirely precise.   

"White space" can be any combination of any number of spaces or tab characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767a133c-6b2a-d353-f39a-9ced2772a1ff
* Version Independent ID: 03b704f2-39fc-f68a-f649-0ed46eb9282f
* Content: [Parsing C Command-Line Arguments](https://docs.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170)
* Content Source: [docs/c-language/parsing-c-command-line-arguments.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/parsing-c-command-line-arguments.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@joefiesta Thanks for the report. An update with a fix should be visible now.

**Comment by joefiesta** [comment]
awesome!  thanks
