### ISSUE TITLE
False positive on base classes with /clr

### ISSUE THREAD

**Issue by rogerorr** [MicrosoftDocs/cpp-docs#357]
The order of initialization of base classes and members when instantiating ref classes ("/clr" mode ) is different (see https://docs.microsoft.com/en-us/cpp/dotnet/changes-in-constructor-initialization-order) but the warning will triggers if you write a member initializer and base class constructor call in the order in which they are *actually* evaluated in managed code.

ref class A  
{  
public:  
   A() : _n(1)  
   {  
   }  

protected:  
   int _n;  
};  

ref class B : A  
{  
public:  
   B() : _m(_n), A() // An explicit base ctor call to the example in the cited page
   {  
   }  
private:  
   int _m;  
}; 

cl /we5038 /clr example.cpp
example.cpp(15): error C5038: data member 'B::_m' will be initialized after base class 'A'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22fb0300-991c-d1ee-bfb1-1f5cdd68ad55
* Version Independent ID: aa2e320d-7640-cbb1-d8d0-7826ad0d0bcb
* Content: [Compiler Warning C5038](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5038)
* Content Source: [docs/error-messages/compiler-warnings/c5038.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/c5038.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Would you call this a documentation issue, or a product issue? It sounds more like the latter, in this case.

**Comment by corob-msft** [comment]
Closing as not (yet) a doc issue. This may change depending on what the product team decides.
