### ISSUE TITLE
HTML encoding error "&lt;filesystem&gt; functions"

### ISSUE THREAD

**Issue by DerTee** [MicrosoftDocs/cpp-docs#3570]
There is a HTML encoding error in one list item of the section "Recommended content".
An item is displayed as `&lt;filesystem&gt; functions` but should be displayed as `<filesystem> functions`.
![htmlencodingerror_Screenshot 2021-12-03 011650](https://user-images.githubusercontent.com/4346532/144524031-d3552905-daa9-4cd2-a38c-39230b31cb7f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce53980f-0912-197f-7d58-b08ed318e951
* Version Independent ID: 22d32ad4-864a-6f86-1e29-c0877396b28c
* Content: [Run-Time Error Checking](https://docs.microsoft.com/en-us/cpp/c-runtime-library/run-time-error-checking?view=msvc-170)
* Content Source: [docs/c-runtime-library/run-time-error-checking.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/run-time-error-checking.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
A fix should appear Monday for this and any related issues in Recommended content.
