### ISSUE TITLE
This is not C++.

### ISSUE THREAD

**Issue by deanmsands3** [MicrosoftDocs/cpp-docs#3577]
[Enter feedback here]
This is **C** with **printf** replaced by **std::cout**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@deanmsands3 
Thanks for the commentary. I'll agree that the interface presented by the DLL is C, and intentionally so. A C interface means the DLL can be used by clients that aren't written in C++. That's more common in practice than an interface that uses C++ linkage. C++ linkage means all the parts of your application have to be built with the same toolchain and linked with the latest linker used for any part of the app. DLLs written with C++ interfaces have issues when handing off memory or other resource handles. Other restrictions can take surprising forms, such as link failures related to partial definitions of nested objects or uninstantiated template specializations. As a practical, software engineering matter, a C interface is usually the best choice for a DLL. Those are the reasons that drove the design of the DLL presented in this article. It's a feature, not a bug.

**Comment by shd8698766** [comment]
This is not C++.......??????
Sorry but I'm fed up with this type of comments.

**Comment by deanmsands3** [comment]
@corob-msft This is a very late response, but thank you for explaining that. I never got the full reason why none of the DLL examples I'd seen were real C++. This makes the reasoning clear. Thank you.

@shd8698766 That's fair, but in my experience, C and C++ are so wildly different that saying "C/C++" deserves its own swear jar. This is made worse when working with EE's.
