### ISSUE TITLE
Visible character code in recommended content link

### ISSUE THREAD

**Issue by owenjustin** [MicrosoftDocs/cpp-docs#3581]
Just wanted to point out something in case it's an issue elsewhere as well.
The "Recommended content" section displays a link titled "Logical OR operator: `&#142;&#124;`"
The character code is being displayed instead of the | character.  When I navigate to the page, the character seems to be displaying correctly.

You may also notice a link to an article about the left shift and right shift operators, `&gt;&gt;` and `&lt;&lt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262486b8-5d80-2c0b-f2eb-40c86aaf6a61
* Version Independent ID: 26b45954-2bcc-263f-7522-0c72941141bb
* Content: [Integer Limits](https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-170)
* Content Source: [docs/cpp/integer-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@owenjustin 
Thanks for the report, which is one we've heard before (#3570). We've updated content recently that used those escapes in titles and descriptions (we removed them), but apparently our change hasn't worked its way through the system yet. The "Recommended content" section is created by some independent publishing process that the C++ docs team has no control over. I expect this issue will clear itself up after some publishing process gets around to updating its database. I'm closing the issue as a duplicate for now, though if it persists, we may need to escalate it to the team responsible.
