### ISSUE TITLE
LNK1107 documentation didn't give the actual reason for the failure. 

### ISSUE THREAD

**Issue by chaitanyavaleti** [MicrosoftDocs/cpp-docs#3583]
[Enter feedback here]
LNK1107 documentation didn't give the actual reason for the failure. When i had added .dll file in the libraries instead of .lib then i was getting the mentioned linker error.

When i searched through the documentation it was misleading and didn't give the actual reason for solving the error.

.obj extension mentioned or checking if the binary was created with /NOASSEMBLY is completely irrelvant to the actual error.
So when i searched other places.. i got the immediate and straight solution.
https://stackoverflow.com/questions/35916703/error1-error-lnk1107-invalid-or-corrupt-file-cannot-read-at-0x2b0/35920570

So would like to see similar kind of improvement in microsoft docs so that it doen't mislead the actual problem and suggests a straight solution instead of going over and over to other irrelvant links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 389e3ae9-b2c7-652d-aa64-041b458babdd
* Version Independent ID: d69f5bdf-b17b-2b62-089d-ea3adcc17b82
* Content: [Linker Tools Error LNK1107](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1107?view=msvc-170)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1107.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1107.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chaitanyavaleti 
Thanks for creating the issue. I've pushed an update to address it that should be published Monday. I'll close #3578, since it's covered by the update.
