### ISSUE TITLE
microsoft visual c++ redistributable package

### ISSUE THREAD

**Issue by LuciferSacred** [MicrosoftDocs/cpp-docs#3584]
[Enter feedback here]
Hi, I wanted to ask about the Microsoft visual c++ redistributable package, so I may delete this? because I have the Microsoft c++ I don't need it longer, I do not want it, it is getting more space in my computer disk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LuciferSacred 
I'm not sure I understand. Is your question about whether you can safely remove some instances of the Microsoft Visual C++ {year} Redistributable found in your system settings for Apps and Features? If so, the answer is probably no. You've installed apps that need these redistributables, and the apps will quit working if you remove them. It's only safe to remove a redistributable if you also remove all the apps that need it. 

If you're asking whether you can delete a redistributable installer from your Downloads folder after you've installed it, then the answer is yes. Once it's installed, you don't need the download anymore.

There's another set of redistributable MSMs in the files installed by Visual Studio, though I don't think they're installed by default. These copies are included so you can add them to your installer packages for the apps you build. I suppose you could remove them if you're never going to create app installers. To remove them safely, open the Visual Studio Installer. Choose the Modify button for your version of Visual Studio, then select the Individual components tab at the top. Search for "redist". Uncheck C++ {year} Reistributable MSMs, then choose Modify. (If they aren't checked, they weren't installed, so there's nothing to uninstall.)

I hope this helps.
