### ISSUE TITLE
Architecture refers to the program, not the OS

### ISSUE THREAD

**Issue by mgcst99** [MicrosoftDocs/cpp-docs#3586]
In the download chart for Visual Studio 2015, 2017, 2019, and 2022, I think it would be helpful to clarify that the 'Architecture' column refers to how the program was compiled, not the Windows version (or the CPU architecture.)
For example, you should install vc_redist.x86.exe for your 32 bit program, whether you're installing it on an x86 or x64 version of Windows.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mgcst99 

Thanks for the idea. I read the article again to see where we might put this information, and I found it's already there in the opening paragraph: "The Redistributable package architecture must match your app's target architecture." Some people find redundant statements annoying, so I'd rather not duplicate this elsewhere in the doc.
