### ISSUE TITLE
cmake for supporting edit and continue specifies target_link_options of /ZI which is invalid 

### ISSUE THREAD

**Issue by StevenBonePgh** [MicrosoftDocs/cpp-docs#3588]
In the section _Edit and Continue for CMake projects_ it specifies that you need to add the following to CMakeLists.txt file to support edit and continue:
`target_link_options(<target> PUBLIC "/ZI" "/INCREMENTAL")`
However, the linker option `/ZI` is not a documented linker option and if this is specified, the linker will emit the warning:
`LINK : warning LNK4044: unrecognized option '/ZI'; ignored`
I believe the  `/ZI` should be eliminated from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170#language-services-for-cmake)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@StevenBonePgh 
Thanks for pointing that out. A fix is in publishing now and should be visible by tomorrow if it isn't already.
