### ISSUE TITLE
Typo in type name

### ISSUE THREAD

**Issue by Alan-FGR** [MicrosoftDocs/cpp-docs#359]
There's no `_m128` (single underscore) in `xmmintrin.h`, so I believe this line:
> Variables of type _m128 are automatically aligned on 16-byte boundaries. 

should read:
> Variables of type __m128 are automatically aligned on 16-byte boundaries. 

Note the double underscore (`__`).
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20b1a3f6-e9a6-abb2-3c88-7de26191fabf
* Version Independent ID: 2a42961c-5bb7-4d2a-09e4-55348b4d6da5
* Content: [__m128](https://docs.microsoft.com/en-us/cpp/cpp/m128)
* Content Source: [docs/cpp/m128.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/m128.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Good catch, thanks. If you make an edit, I'll approve it.

**Comment by Alan-FGR** [comment]
Here you go: https://github.com/MicrosoftDocs/cpp-docs/pull/361

**Comment by Alan-FGR** [comment]
I think it's fine to close this now. Thank you @corob-msft. I'm taking the initiative to close it, don't know if I really should though, feel free to reopen.
