### ISSUE TITLE
C6011 Incorrect when analyzing double-pointer for dereference of NULL.

### ISSUE THREAD

**Issue by drankinatty** [MicrosoftDocs/cpp-docs#3596]
**Version Info**
```none
Microsoft Visual Studio Community 2017 
Version 15.9.41
VisualStudio.15.Release/15.9.41+28307.1745
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA441
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info
```

There is an error in the C6011 warning in C when used with a double-pointer. Specifically, when a pointer-to-pointer-to-char is allocated and a sentinel `NULL` used as the last valid pointer, VS2017 flags the check for the sentinel `NULL` as a dereference of the `NULL` pointer. That is incorrect. No dereference takes place. Dereferencing the pointer-to-pointer results in a pointer which checked against `NULL` is valid and not a warning, For instance, in the following example, line 68 is warned for the condition test of `tokens[i]` in the `for` loop:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

#if defined (_WIN64) || defined (_WIN32)
#define PREFIX "Path="  /* constants for PREFIX and DELIM on windows */
#define DELIM ";\r\n"
#else
#define PREFIX "PATH="  /* constants for PREFIX and DELIM on Linux */
#define DELIM ":\n"
#endif

int main (int argc, char **argv, char **env)
{
    char path[PATH_MAX] = "",               /* storage for copy of environment string */
        *p = path,                          /* pointer - general use */
        **tokens = NULL;                    /* pointer to pointer for path components */

    size_t  prefixlen = strlen (PREFIX),    /* prefix length */
            ndx = 0;                        /* path tokens index */

    for (int i = 0; env[i]; i++) {          /* find PREFIX in environment */
#ifdef DEBUG
        puts (env[i]);
#endif
        if (strncmp (env[i], PREFIX, prefixlen) == 0) {
            strcpy (p, env[i] + prefixlen); /* copy path from env to path */
            break;
        }
    }

    if (!*p) {  /* if PREFIX not found */
        fprintf (stderr, "error: '%s' not found in environment.\n", PREFIX);
        return 1;
    }

    puts ("\nfull path:\n");    /* show full path to create tokens from */
    puts (p);

    /* loop moving ep (end-pointer) to next DELIM in p or last token */
    for (p = strtok (p, DELIM); p; p = strtok (NULL, DELIM)) {
        size_t  len = strlen (p);            /* length of token */
        /* realloc pointers using temporary pointer
         * adding two more than index to set sentinel NULL as last pointer
         * (sentinel NULL is optional, just add 1 if not wanted)
         */
        void *tmp = realloc (tokens, (ndx + 2) * sizeof *tokens);
        if (!tmp) {                                 /* validate realloc */
            perror ("realloc-tokens");
            break;
        }
        tokens = tmp;                               /* assign new block to tokens */
        tokens[ndx + 1] = NULL;                     /* set sentinel NULL */
        if (!(tokens[ndx] = malloc (len + 1))) {    /* allocate/validate string storage */
            perror ("malloc-tokens[ndx]");
            tokens[ndx] = NULL;
            break;
        }
        memcpy (tokens[ndx++], p, len + 1);         /* copy path component */
    }

    puts ("\npath components:\n");              /* output separated tokens */
    for (size_t i = 0; tokens[i]; i++) {        /* loop until sentinel NULL */
        puts (tokens[i]);
        free (tokens[i]);                       /* free string storage */
    }
    free (tokens);                              /* free pointers */

    (void)argc;     /* cast to prevent -Wunused warnings */
    (void)argv;
}
```

The test of `tokens[i]` isn't a dereference of a `NULL` pointer. The only way it could be a "potential" dereference of a `NULL` would be if `token` itself was assigned `NULL`, e.g. `tokens = NULL;` which does not occur in the code.

Now the warning says "potential", but the IDE flags and maintains the warning without the option of indicating that, "no, in fact that is not the derefernce of a `NULL`" to have the warning dismissed. Worth checking if that cannot be fixed. Likely to sew confusion in new programmers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f06b2b0-b8c7-8d02-1c6c-71bf6f2abe07
* Version Independent ID: d85395d3-d1ec-7863-5263-a142a424cbb1
* Content: [C6011](https://docs.microsoft.com/en-us/cpp/code-quality/c6011?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C6011)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/code-quality/c6011.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c6011.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@drankinatty 
Thanks for the report and apologies for the delayed response; we've been on vacation.

Unless I've missed something, the C6011 error in the above code looks correct to me. If the initial `realloc` call fails, you have a code path that can leave `tokens` with its initial value of `NULL`. Then a test of `tokens[i]` in your final loop does a null pointer dereference. You can fix it by initializing `tokens` with `malloc(sizeof *tokens);` and then `tokens[0] = NULL;`.

I'm closing the issue because as far as I can tell, it's not a documentation issue. If the product produces false positives in the analyzer, you should report that as a bug on [Developer Community](https://aka.ms/vsfeedback/browsecpp). That's where the development team looks for issues. For more info on reporting issues, see [How to report a problem](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170).

**Comment by drankinatty** [comment]
Okay, sorry for the noise. The initial `realloc()` fail code path through the condition in the `for(; ... ;)` loop merits the warning, but in that case there would be no possibility of initializing `tokens[0] = NULL;`
