### ISSUE TITLE
No mention of right-clicking a CButton.

### ISSUE THREAD

**Issue by jmporter34** [MicrosoftDocs/cpp-docs#360]
I understand that CButton does not support right-clicking.  Please provide information and example code for how to add support for right-clicking a CButton-derived object, including what has to be done in the dialog containing the button.  Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a02ca2-b5fa-5458-88e4-921e65538d24
* Version Independent ID: 7aa8d9d2-0fdb-ae00-af52-9c42b0f8e40b
* Content: [CButton Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cbutton-class)
* Content Source: [docs/mfc/reference/cbutton-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cbutton-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Hi, @jmporter34 - I'm sorry to say that our time commitments don't extend to doing new work in the MFC documentation. However, you can find an example of sub-classing the CButton control to handle right-click messages on StackOverflow in [Can Right-mouse click events be detected on a MFC Button control?](https://stackoverflow.com/questions/35454247/can-right-mouse-click-events-be-detected-on-a-mfc-button-control) and examples linked from there. Hope this helps.

**Comment by jmporter34** [comment]
Hi,
Yes I had actually seen that article and tried his method but it wasn't
working for me.  I had also read a bunch of other discussions on the
subject, before going to MSDN where I hoped to find the definitive
information on how to handle right-clicking a button in a dialog.  I left
my comment when I couldn't find anything.
I finally figured out that the author of the article you linked to had
neglected to mention that you have to call the SubclassWindow function for
your CButton-derived object in its parent's OnInitDialog function.
Anyway, thank you for trying to help.
