### ISSUE TITLE
GetItemData description is incorrect ( 32-bit application-specific value .. )

### ISSUE THREAD

**Issue by Eta76** [MicrosoftDocs/cpp-docs#3600]
Regarding:

      DWORD_PTR GetItemData(int nItem) const;
      Parameters
      nItem
      Index of the list item whose data is to be retrieved.
      
      Return Value
      A **32-bit application-specific value** associated with the specified item.
      
a DWORD_PTR would be a 64-bit value, when compiling a 64-bit application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3083dc89-da71-7bbf-d224-f434a7454434
* Version Independent ID: 021a392d-6ad0-0a52-9fca-9f24c44bede0
* Content: [CListCtrl Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/clistctrl-class?view=msvc-170)
* Content Source: [docs/mfc/reference/clistctrl-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/clistctrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Eta76, thank you for pointing this out. I've updated the doc to reflect that it will be 64-bits when compiling for x64. I updated several places in the doc like this one.
The updated doc should be live by tomorrow afternoon (1/4/2022)
