### ISSUE TITLE
c++ example code is wrong!!

### ISSUE THREAD

**Issue by willerwu** [MicrosoftDocs/cpp-docs#3601]
[Enter feedback here]

C++

Copy
int (**p) () = new (int (*[7]) ());
delete *p;

the code for C++ should be( without *):  

int (**p) () = new (int (*[7]) ());
delete p;

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba500f8a-29af-57af-704f-78b0cf3a1588
* Version Independent ID: a280744d-1e46-b36a-3d65-c33761c6835c
* Content: [new operator (C++)](https://docs.microsoft.com/en-us/cpp/cpp/new-operator-cpp?view=msvc-170)
* Content Source: [docs/cpp/new-operator-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/new-operator-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@willerwu 
Good catch, and thanks for the report. We've published a fix that's visible now.
