### ISSUE TITLE
Error in translating

### ISSUE THREAD

**Issue by whales-lee** [MicrosoftDocs/cpp-docs#3603]
[Enter feedback here]

Translating into Chinese got a error in section Syntax:
this is in English:
    [](auto[](auto, auto, auto) {};

after translating:
    [](auto[](auto, auto, auto) {};

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9afc46-4088-933e-89e6-1720593fa7cf
* Version Independent ID: 53d5f98c-c5bc-d9e0-0553-005ddd200d06
* Content: [auto (C++)](https://docs.microsoft.com/en-us/cpp/cpp/auto-cpp?view=msvc-170)
* Content Source: [docs/cpp/auto-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/auto-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
If I'm reading what you are describing right, this is intentional. Keywords and syntax shouldn't translate. It's probably ok for things like param1, declarator, etc. to translate, though I don't know if the auto translator attempts to.
