### ISSUE TITLE
cl vs c1

### ISSUE THREAD

**Issue by xrayextra** [MicrosoftDocs/cpp-docs#3606]
[Enter feedback here]
Great article.  I was looking to run a c program in visual studio but came across yours and gave it a shot.

You go into heavy detail about possible errors when entering cl to test the output to make sure everything was working.  I made the mistake of typing "c1" (that's cee-one) instead of "cl" (cee-ell) and was confused, read all the things about what might be wrong before realizing the mistake.  You may want to note that in your article to type cee-ell and not cee-one. :)

Raymond Johnson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96f0a01-2e3a-6301-bba1-6a50252555b0
* Version Independent ID: 290ca773-a214-e81a-2ba3-c647f2b28a56
* Content: [Walkthrough: Compile a C program on the command line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-170)
* Content Source: [docs/build/walkthrough-compile-a-c-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-compile-a-c-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@xrayextra 
Not a bad notion. You'd think a site that's intended for developers would choose typefaces with easier-to-distinguish letters and numbers, but that doesn't seem to have occurred to our designers.

**Comment by corob-msft** [comment]
There's a fix of sorts with a clear hint in the recently published docs.
