### ISSUE TITLE
C2075 error page show the error for C which is a syntax error

### ISSUE THREAD

**Issue by peter249** [MicrosoftDocs/cpp-docs#3608]
C2075 error page show the error for C which is a syntax error

in C you should be able to define a identifier as void *ptr[]; and not get a C2070 error as you would get on C++

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d28dbb-8752-6dde-84c8-c44211fb917e
* Version Independent ID: 7ef9e4f4-2073-bb88-d69e-30e92baeb191
* Content: [Compiler Error C2075](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2075?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2075)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2075.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2075.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@peter249 
I'm sorry you're having difficulty. I'm unable to reproduce the problem you seem to have in a way that generates C2075.

```
// C2075.c
int main()
{
    void * ptr[];
}
```

cl produces an error: 

```
error C2133: 'ptr': unknown size.
```

clang doesn't like it either:

```
error: definition of variable with array type needs an explicit size or an initializer
    void * ptr[];
```

gcc reports:

```
error: array size missing in ‘ptr’
     void * ptr[];
            ^~~
```

Do you have a repro that shows the issue?

**Comment by peter249** [comment]
As your example shows - you need to initialize the identifier with data.   I define it as void **ptr; but you  can get a null address value when you use something like  void *x = &ptr[0]; In generated assembly it can produce a address value multiplied by 0 which generates the null address  (I had found this and coded around it - don't have an example).

Another place you must code around is when defining variable sized structs, e.g.  struct thing { int a; int b; double array[]; };  You have to be careful taking address here as well.  It was good coding practice to define a pointer to an array as void *ptr[]; which was really a void **ptr; so you document to other developers that you were using it as a pointer to an array.  Can't do that anymore because it has to be initialized.

I'm a old guy and had 30+ years in assembly/C/C++ and just had to create a library in C to get some explicit performance and ran into these problems.  I use Go to Disassembly a lot, both Debug and Release.  C++ has gone to much into a high level language these days -- C# works well for a high level language for most cases....

So I will have to live with whatever.....
