### ISSUE TITLE
Linux Json Build Configuration File Typo

### ISSUE THREAD

**Issue by mattcoding4days** [MicrosoftDocs/cpp-docs#3618]
The web page shows this, the configurations list structure is missing.

![JsonTypo](https://user-images.githubusercontent.com/35334658/147646686-f3570975-690e-426f-a397-0277650db6e2.png)

But should be this:

```json
{
  "configurations": [
    {
      "name": "Linux-GCC-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "cmakeExecutable": "cmake",
      "remoteCopySourcesExclusionList": [ ".vs", ".git", "out" ],
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "linux_x64" ],
      "remoteMachineName": "${defaultRemoteMachineName}",
      "remoteCMakeListsRoot": "$HOME/.vs/${projectDirName}/${workspaceHash}/src",
      "remoteBuildRoot": "$HOME/.vs/${projectDirName}/${workspaceHash}/out/build/${name}",
      "remoteInstallRoot": "$HOME/.vs/${projectDirName}/${workspaceHash}/out/install/${name}",
      "remoteCopySources": true,
      "rsyncCommandArgs": "-t --delete --delete-excluded",
      "remoteCopyBuildOutput": false,
      "remoteCopySourcesMethod": "rsync",
      "variables": []
    }
  ]
}
```

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c9cfb6-69f7-cefc-9d73-826eb8d17751
* Version Independent ID: 360eda3d-21c9-eb6b-b0c9-8dbb3bbb97ea
* Content: [Configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-configure?view=msvc-160)
* Content Source: [docs/linux/cmake-linux-configure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-configure.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@mattcoding4days , thank you for pointing this out. I've updated the doc. This doc is version dependent. If you change the dropdown in the top left the JSON example changes per version. I updated the 2017 version and the 2019+ version.
The fix should be live by tomorrow afternoon (1/4/2022)

**Comment by TylerMSFT** [comment]
@mattcoding4days, the fix didn't get integrated into the main branch until today. It may be tomorrow (1/5/2022) before it's live.
