### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by MetallicPickaxe** [MicrosoftDocs/cpp-docs#362]
preverve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45f6269-45a0-436f-33f9-19d3815351ec
* Version Independent ID: 8851dcef-4f42-1864-d899-2c01c4d9d008
* Content: [Deployment in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/deployment-in-visual-cpp)
* Content Source: [docs/ide/deployment-in-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/deployment-in-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for spotting that. Closed as fixed. In the future, feel free edit the page and submit a PR with your corrections directly.
