### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by z4v4l** [MicrosoftDocs/cpp-docs#3622]
Hi, the line 10
`$(patsubst he%,_%_,Hello Hey Hi) # Evaluates to "_llo_ _y_ Hi" - patsubsti is case-insensitive`
in the example, should be
`$(patsubsti he%,_%_,Hello Hey Hi) # Evaluates to "_llo_ _y_ Hi" - patsubsti is case-insensitive`

:)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6633a5d9-ad62-1c23-c762-4505c6c0ebbe
* Version Independent ID: 1490c981-73a2-54c8-eecd-38b1fb718bbe
* Content: [patsubst, patsubsti NMAKE functions](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-function-patsubst?view=msvc-170)
* Content Source: [docs/build/reference/nmake-function-patsubst.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/nmake-function-patsubst.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@z4v4l 
Good catch, and thanks for the report. We've published a fix.
