### ISSUE TITLE
VCRedist packages version info

### ISSUE THREAD

**Issue by gmjdh** [MicrosoftDocs/cpp-docs#3623]
[Enter feedback here]
Hi! I would really like to see the version number for the "Visual Studio 2015, 2017, 2019, and 2022" redistributable packages on this site (for instance the current VC_redist.x64.exe pacakge has version 14.30.30704.30); but the only way to find out this, is to download the file and then view the file properties! I would rather see the version details nexxt to the download links, so that I can decide wether I need to download the file or not before doing it :)

Thank You!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gmjdh 
That's a great idea. It's unfortunate that the redist packages are updated independently of the documentation. We're just given some generic download links that stay the same across updates, and we aren't notified when updates happen, either. We don't have a way to do what you'd like, other than downloading the files ourselves every day and seeing what versions we get, and possibly being off by a version or two until we update the docs. That's not a task we're willing to undertake on the regular, and I don't know of an easy way to automate it, either. So, this goes in the file of good ideas we aren't going to implement. I'm sorry.
