### ISSUE TITLE
Showing `&lt;` and `&rt;` instead of `<` and `>` for links pertaining to `<filesystem>`, `<string> typedefs` and `<sstream> typedefs`

### ISSUE THREAD

**Issue by Ch-sriram** [MicrosoftDocs/cpp-docs#3625]
This is the screenshot of the issue I found:

![Screenshot from 2021-12-31 00-45-29](https://user-images.githubusercontent.com/26023903/147781718-459d0437-cf00-4b97-8d35-706b16235aaf.png)

I'm using Chrome Browser in Ubuntu 16.04 [although this issue I think is related to parsing the string, not anything related to browser].

Also, this is the link I was viewing: <https://docs.microsoft.com/en-us/cpp/standard-library/basic-string-class?view=msvc-170#see-also>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fedc7b-0ebe-766c-9089-548293b3b08f
* Version Independent ID: 451f8367-d247-95fb-03ec-0f9195e165e1
* Content: [basic_string Class](https://docs.microsoft.com/en-us/cpp/standard-library/basic-string-class?view=msvc-170#see-also)
* Content Source: [docs/standard-library/basic-string-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/basic-string-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Ch-sriram, I'll talk to the team that machine generates that part of the topic. Thanks for raising the issue.

**Comment by Ch-sriram** [comment]
@TylerMSFT can you point me to the source code if it's open to contributions?
I can try to contribute and fix it on my own.

**Comment by TylerMSFT** [comment]
@ch-sriram - it's not open to contributions. They are running it today, I understand. We'll see if this clears up in a day or two.  The cause is metadata in the topics. Many of those got cleaned up in December and when they regenerate the related content sections, it should clear up, though there are probably a handful that will still need to be updated.

**Comment by Ch-sriram** [comment]
@TylerMSFT cool. I understand 🙂.

**Comment by TylerMSFT** [comment]
@Ch-sriram , it looks like the tool ran and the particular topic you called out is fixed.
I bet there are other topics with this problem though (we have thousands of topics to look at) so if you see one, don't hesitate to reopen this issue and we'll take a look.
Hey, really appreciate you pointing this out so we can improve things.
