### ISSUE TITLE
wrong text for pragma

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/cpp-docs#3626]
This text is wrong.
> Unlike __pragma, _Pragma allows you to put pragma directives into a macro definition. The string literal should be what you would otherwise put following a #pragma statement. For example

The second term should be `#pragma` and read...

> Unlike #pragma, _Pragma allows you to put pragma directives into a macro definition. The string literal should be what you would otherwise put following a #pragma statement. For example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8f0a4b-8eeb-158f-3995-66fa674e67d1
* Version Independent ID: d9e7ec65-7238-a9fb-6ab3-dc71144e3a34
* Content: [Pragma directives and the __pragma and _Pragma keywords](https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=msvc-170)
* Content Source: [docs/preprocessor/pragma-directives-and-the-pragma-keyword.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/pragma-directives-and-the-pragma-keyword.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@diablodale 
Good catch, and thanks for the report. We've since published a fix.
