### ISSUE TITLE
cmake "Scan Sources for Module Dependencies"

### ISSUE THREAD

**Issue by laurentcau** [MicrosoftDocs/cpp-docs#3632]
[Enter feedback here]
Hi,
Do you know a way to set "Scan Sources for Module Dependencies" to "Yes" with cmake ?
I didn't find the corresponding compiler option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155fa1d1-ee01-ecec-c845-ca643185b6ad
* Version Independent ID: ff338253-ea22-428c-eb1f-4c88af2adc0c
* Content: [Walkthrough: Import STL libraries as header units](https://docs.microsoft.com/en-us/cpp/build/walkthrough-import-stl-header-units?view=msvc-170#approach1)
* Content Source: [docs/build/walkthrough-import-stl-header-units.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-import-stl-header-units.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, doc feedback is for raising issues about the documentation. This topic isn't intended to address that scenario. For questions like this, you might try the [developer community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fvsfeedback%2Fbrowsecpp&data=04%7C01%7CTyler.Whitney%40microsoft.com%7C5741446ac59c4b9db2fd08d9878e62a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637689867885607869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MF%2BRQ2YB96%2F8%2FGlewv2ttenU5mu%2FaAuBut8FcfVR12k%3D&reserved=0)
