### ISSUE TITLE
'Rep' template parameter referred as 'Ref'

### ISSUE THREAD

**Issue by zzxoto** [MicrosoftDocs/cpp-docs#3635]
```
max          Static. Returns the maximum allowable value of template parameter Ref.
```
`Ref` should actually be `Rep`, since the template declaration above was:
```
template <class Rep, class Period> class duration;
template <class Rep, class Period = ratio<1>> class duration;
template <class Rep, class Period1, class Period2> class duration <duration<Rep, Period1>, Period2>;
```
Look out for other `Ref` / `Rep` typos throughout `<chrono>` stl documentation (e.g. see time_point class).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111e1edd-c2c2-5d07-4331-1606e5d8895a
* Version Independent ID: 1d0eb9b9-97d0-14e9-3d6d-1040a5eb3578
* Content: [duration Class](https://docs.microsoft.com/en-us/cpp/standard-library/duration-class?view=msvc-150)
* Content Source: [docs/standard-library/duration-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/duration-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@zzxoto , thank you for flagging this. I fixed this topic and the time_point topic. I grepped for this mistake in other topics and didn't see other instances.
This fix should be live tomorrow afternoon (1/6/2022)
