### ISSUE TITLE
the loop definition is commented out

### ISSUE THREAD

**Issue by Raghavendrar403** [MicrosoftDocs/cpp-docs#364]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9f5429-d3ce-3c6c-cd5a-3f7ea5389677
* Version Independent ID: 4c5e1cca-316f-8488-ab0c-110013b51d42
* Content: [References to Pointers](https://docs.microsoft.com/en-us/cpp/cpp/references-to-pointers)
* Content Source: [docs/cpp/references-to-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/references-to-pointers.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

While learning C++ language from microsoft website in the section Reference to pointers ,
while (!cin.eof()) has been commented out. It should not be commented.

**Comment by mikeblome** [comment]
fixed. should be visible by 08/21. thanks @Raghavendrar403  !
