### ISSUE TITLE
Read CByteArray overload isn't what users would expect

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/cpp-docs#3641]
The documentation says there's a CByteArray specific overload, but what gets called is actually a CObject overload as there isn't a CByteArray overload.
Users will naively expect to be able to read raw BYTE data this way, when in fact they can't - it'll only work correctly if a CByteArray had been written in the first place.
Can this documentation be amended to mention this gotcha please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3f27a0-9dbd-dea5-dd87-66c542a12a06
* Version Independent ID: 3b64abb3-ddc3-fe22-a0e3-10757b5a4864
* Content: [CSettingsStore Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/csettingsstore-class?view=msvc-170)
* Content Source: [docs/mfc/reference/csettingsstore-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/csettingsstore-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
