### ISSUE TITLE
use C++ namespace in C# project

### ISSUE THREAD

**Issue by duzhongkai** [MicrosoftDocs/cpp-docs#3644]
[Enter feedback here]
Hello,

I want to add C++ dll reference into one C# project by managed way, then I find this document of wrapping native C++ class.
I have already generated C++ dll, and can add it to my C# project, but now the problem is that the namespace cannot be found which is defined in C++ dll. I've tried to change the target framework according to someone's experience, but it didn't work. Could you please give some suggestion or examples?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0400aa0c-0a2d-bce1-1be7-f89cdabf2ca7
* Version Independent ID: f97da8f0-701a-c110-53e1-c86b302739f8
* Content: [How to: Wrap Native Class for Use by C#](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-wrap-native-class-for-use-by-csharp?view=msvc-170#example)
* Content Source: [docs/dotnet/how-to-wrap-native-class-for-use-by-csharp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-wrap-native-class-for-use-by-csharp.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, this is better suited for the [C++ Q&A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
