### ISSUE TITLE
"The x87 register stack "

### ISSUE THREAD

**Issue by Tanya-Solyanik** [MicrosoftDocs/cpp-docs#3646]
Is this a typo:
**The x87 register stack is unused. It may be used by the callee, but consider it volatile across function calls. All floating point operations are done using the 16 XMM registers.**

https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#:~:text=The%20x64%20Application%20Binary%20Interface%20%28ABI%29%20uses%20a,arguments%20and%20the%20registers%20used%20for%20those%20arguments.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87b11e0-0214-175b-0926-0f8a4653e444
* Version Independent ID: 43e8bf4a-9a0d-ea28-d432-ead828604d5e
* Content: [x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170)
* Content Source: [docs/build/x64-calling-convention.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/x64-calling-convention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Tanya-Solyanik 
Can you clarify your question? I'm not sure which word you're referring to. "Callee" is correct here. It means the called function is free to use the x87 stack for floating-point operations, but any function the callee calls (which make the "callee" the "caller") may in turn invalidate that stack.

**Comment by Tanya-Solyanik** [comment]
Thank you!
