### ISSUE TITLE
CEdit::GetHighlight is only defined for UNICODE

### ISSUE THREAD

**Issue by jmporter34** [MicrosoftDocs/cpp-docs#365]
I tried to use CEdit::GetHighlight in a non-UNICODE project and kept getting
"error C2039: 'GetHighlight': is not a member of 'CEdit'".
I looked in afxwin.h and found both SetHighlight and GetHighlight are inside an "#if defined(UNICODE)" block.
Aside from the fact that I can't understand why this should be the case, the documentation should at least mention this fact. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b1a15-2ebf-6f85-4dad-06687c22be5c
* Version Independent ID: 4794949e-d6a0-4d30-747a-2fc47199aad4
* Content: [CEdit Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cedit-class#gethighlight)
* Content Source: [docs/mfc/reference/cedit-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cedit-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @jmporter34 . Investigating.

**Comment by mikeblome** [comment]
Possibly a product bug. Waiting on response from developer team.

**Comment by mikeblome** [comment]
@jmporter34  I have updated the doc to describe the actual behavior. Should be visible on 09-13. Since this is a product issue, possibly a bug, I encourage you to post it to the C++ forum on DeveloperCommunity: https://developercommunity.visualstudio.com/spaces/62/index.html
