### ISSUE TITLE
Add info about UNREFERENCED_PARAMETER as a viable fix

### ISSUE THREAD

**Issue by mpOzelot** [MicrosoftDocs/cpp-docs#3650]
[Enter feedback here]
I've encountered this issue and used the UNREFERENCED_PARAMETER macro defined in winnt.h, is it maybe a more viable option than the one presented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff5f8e3-be4c-3af7-cb5d-9a0c0017a222
* Version Independent ID: 5f78d743-c527-95e8-367b-0eb0ba811ec5
* Content: [Compiler Warning (level 4) C4100](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4100?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4100.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4100.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by AlexGuteniev** [comment]
I don't think compiler warning documentation that is about core language should suggest Platform SDK usage.
Maybe cast to `void` can be suggested.

**Comment by corob-msft** [comment]
@mpOzelot 

Thanks for the suggestion. There's nothing wrong with using the `UNREFERENCED_PARAMETER` preprocessor macro where it's defined. The macro creates an expression that evaluates its argument and does nothing with the result. You could do the same thing in standard C++ by writing code like this:

```cpp
void foo(int unused_param)
{
    (unused_param);  // same as code created by UNREFERENCED_PARAMETER(unused_param);
    return;
}
```

There's no appreciable difference in behavior between this approach and the recommended solutions. And as @AlexGuteniev  points out, we're documenting C++ compiler behavior whether building for Windows or not, so we're disinclined to use platform-specific examples.
