### ISSUE TITLE
Can you give an example of task_from_result?

### ISSUE THREAD

**Issue by ZhijunMS** [MicrosoftDocs/cpp-docs#3657]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed528ef-bb02-510b-0533-22ab102988f7
* Version Independent ID: 05f52861-5bbc-04b6-3b38-c5859bc3bd58
* Content: [concurrency namespace functions](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/concurrency-namespace-functions?view=msvc-170&redirectedfrom=MSDN&viewFallbackFrom=vs-2017)
* Content Source: [docs/parallel/concrt/reference/concurrency-namespace-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/concurrency-namespace-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
