### ISSUE TITLE
Goto has an important limitation

### ISSUE THREAD

**Issue by Dave-51** [MicrosoftDocs/cpp-docs#366]
Goto has an important (imho) limitation which definitely SHOULD be stated here. The limitation is clearly stated on the page "Transfers of Control", but really guys, we shouldn't have to search multiple pages to find out how to correctly use the statement that this page is supposed to be describing. (even if Visual Studio will flag the error). My *guess* is that encountering the error will be least too common to justify its being relegated to a "see elsewhere" reference.
 The first part of this should have an added paragraph which states:
"When the goto statement specifies a program branch which jumps past an initializer, the initializer must be in a block enclosed by the block in which the goto statement occurs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35725608-b181-d529-4fe6-fcd63c8748e7
* Version Independent ID: 0cc1dc44-fff9-731e-9346-84ef6f52b668
* Content: [goto Statement (C++)](https://docs.microsoft.com/en-us/cpp/cpp/goto-statement-cpp)
* Content Source: [docs/cpp/goto-statement-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/goto-statement-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @Dave-51. I have updated the topic and it should be visible by 08-15.

**Comment by mikeblome** [comment]
fixed. should be visible by 08/20. thanks @Dave-51 !
