### ISSUE TITLE
How to create property sheet at solution level?

### ISSUE THREAD

**Issue by 23W** [MicrosoftDocs/cpp-docs#3664]
Document contains following text:
> In large solutions that will have many projects, it can be useful to create a property sheet at the solution level

But there are no details how to do it. The document describes creating props at project level only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d14bcc9-b174-5949-035e-678a3939f031
* Version Independent ID: 03017dba-6921-5b6e-b6df-05a9d955da3d
* Content: [Share or reuse Visual Studio project settings - C++](https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=msvc-170)
* Content Source: [docs/build/create-reusable-property-configurations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/create-reusable-property-configurations.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@23W 

Thanks for commenting. The description might be confusing. There's no hierarchy of properties files, where solution-level properties files are automatically added to projects in that solution. A solution-level properties file is just a user-created properties file that you manually add to all of the projects in a solution. You create one the same way as a project-level properties file: Select a project in **Property Manager** and right-click, then choose **Add New Project Property Sheet**. In the **Add New Item** dialog, change the location for your property sheet file to the solution directory. (It could be saved anywhere, but this location makes it easy to find.) Choose **Add** to create the file and add it to that project. Then, for each other project in Property Manager, right-click and choose **Add Existing Property Sheet**. In the **Add Existing Property Sheet** dialog, navigate to the solution directory and select the props file you created, then choose **Open**. Now you've created a solution-level properties file.

**Comment by corob-msft** [comment]
I've clarified the documentation, and it should be visible in a couple of hours.
