### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by Dave-51** [MicrosoftDocs/cpp-docs#367]
This document is found in Docs / Visual C++/ Documentation / C Runtime Library. It is reasonable to assume that it describes the C runtime BUT it is NOT reasonable for ANY C++ document to ignore the standard C++ data structures (i.e. C++ strings). I shouldn't have to go somewhere else (outside of Visual C++ documentation) to find out about stod. (At this point, I'm assuming Visual C++ actually supports stod (etc.) which is certainly critcally important but has been totally neglected here.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 213492ed-78c7-8690-4122-1b45bdc8f60d
* Version Independent ID: ba6a11b4-b58d-8225-3326-c998933c17e1
* Content: [String to Numeric Value Functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/string-to-numeric-value-functions)
* Content Source: [docs/c-runtime-library/string-to-numeric-value-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/string-to-numeric-value-functions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @Dave-51 -

I'm sorry you didn't find the documentation you expected here. In general, all the Microsoft libraries, the C runtime library, the C++ standard library, MFC, ATL, ConcRT, OpenMP and AMP, OLEDB and ODBC and so on, have their own sections in the documentation. This particular overview is part of the CRT library documentation, which as the name suggests, covers only the CRT functions available to both C and C++. It's not meant as an overview of every Microsoft-supplied library that has string functions, of which there are many.

The [C++ Standard Library](https://docs.microsoft.com/en-us/cpp/standard-library/cpp-standard-library-reference) has its own documentation, organized by header. You'll find [std::stod](https://docs.microsoft.com/en-us/cpp/standard-library/string-functions#stod) and related functions described in the [\<string> functions](https://docs.microsoft.com/en-us/cpp/standard-library/string-functions) article. I recommend using the Search tool at the top of the page when you're looking for a particular function or set of functions.

I'm closing this issue as outside the scope of this particular document.
