### ISSUE TITLE
Missing MSVCP120.dll, MSVCR120.dll, MSVCR110.dll

### ISSUE THREAD

**Issue by Rdritik** [MicrosoftDocs/cpp-docs#3672]
While installing some softwares like wamp server in windows 11, showing errors like The code execution cannot proceed because MSVCP120.dll was not found. 
Same error for MSVCR120.dll , MSVCR110.dll was not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Rdritik 

I understand your difficulty, but I'm having trouble relating it to a content issue. Was there something you came here to find that you didn't see?

As a support request, it looks like you need the Visual Studio 2013 (12.0) and Visual Studio 2012 (11.0) redistributables. Those numbers match the numbers at the end of the missing DLLs.

**Comment by Rdritik** [comment]
Issue Resolved
