### ISSUE TITLE
Code snippets with header units are incorrect

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/cpp-docs#3679]
C++ header units require a semi-colon at the end, this example,

```cpp
import <vector>
import "myheader.h"
```

Should have been written as

```cpp
import <vector>;
import "myheader.h";
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pjmlp 
Good catch. A fix is in the works for later today.
