### ISSUE TITLE
Memory leak in the example

### ISSUE THREAD

**Issue by mduberstein** [MicrosoftDocs/cpp-docs#3680]
[Enter feedback here]
**void* pointer**s sample

pvoid is not not deleted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2284bc5b-569d-81ee-0b8d-38c711c92656
* Version Independent ID: d448ee76-816d-67a9-6c1d-19da30933822
* Content: [Raw pointers (C++)](https://docs.microsoft.com/en-us/cpp/cpp/raw-pointers?view=msvc-160)
* Content Source: [docs/cpp/raw-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/raw-pointers.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mduberstein 
Thanks for the report. An update is in the works and should be visible later today.
