### ISSUE TITLE
CMake target view is not present in VS2022 where the documentation shows it would be

### ISSUE THREAD

**Issue by patrikhuber** [MicrosoftDocs/cpp-docs#3683]
Hi,

My profound apology if I am just very blind or being stupid. The VS 2022 docs say that if I open a project from a CMakeLists.txt, I can access a CMake targets view here:

![image](https://user-images.githubusercontent.com/4967343/152458337-72aff506-7e22-4170-9cda-24527f9b8f14.png)

However, this button is just not present in my project:

![image](https://user-images.githubusercontent.com/4967343/152458366-2a3bec79-8dad-47ba-a55a-f3cb50f2fcd9.png)

I did File => Open => CMake..., VS's CMake has successfully run in my case - no errors in the VS "CMake" output window. I can also compile individual files or "Build All". But no target view.

This is VS 2022 17.0.5.

Thanks a lot for any help of what I might be doing wrong or misunderstanding in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@patrikhuber 

Sorry it's giving you trouble. No one told me about this change, so I didn't have a chance to update the docs. It looks like the control next to the house has changed from a drop-down to a toggle button in Visual Studio 2022. In a CMake project, you start out in **CMake Targets View** by default. Choose the toggle button to switch to a **Views** view. In the **Views** view you can select either a **Folder View** or **CMake Targets View** for your projects. The **Views** view replaces the drop-down. It shows the active view in bold. To go to your preferred view from the **Views** view, either double-click on that view in the list, or right-click it and choose **Open**. The toggle button now alternates between the **Views** view (say that three times fast) and your selected view.

**Comment by patrikhuber** [comment]
Hi @corob-msft, thanks a lot for the quick reply! And no worries.

Aah I see! I had pressed the button before of course, but that "Views view" was confusing me - and I had not seen that there's an entry there that said "CMake Targets View". I pressed that, and there it is, the target view - as you explained.

Interestingly, my CMake project started me off in the Folder View by default - not the Targets view.
Also, if I activate/open the Targets view, then close VS, and reopen my projects, it's back in the Folder view :( This is quite annoying (I have to switch the view every time I re-open my solution), and I would construe this as a bug. Should I be filing this somewhere?

I've got one final question - sorry if that's slightly too off-topic, but it's one of the reasons I was looking for the Targets view. Previously, and in a "traditional" solution project, one was able to right click on a target, select "Properties", and then get the property dialog like below, where one is able to see (and potentially edit) the compiler and linker flags, the command-line call of the compiler, etc.:

![image](https://user-images.githubusercontent.com/4967343/152618798-df9003f3-5ed0-4772-9fe8-afe726f5ec29.png)

For CMake targets, this has now gone and if I right-click->Properties on a target, I merely get this empty "Properties" side-panel:

![image](https://user-images.githubusercontent.com/4967343/152619053-b63e3e01-af52-4a98-b6e7-19284732dfb8.png)

I understand that one is not supposed to change settings, flags etc. in the above-mentioned Properties dialog, as they're not persistent and are overwritten as soon as CMake is re-run. But being able to view this Properties dialog, its settings, see the compiler command-line call, and also be able to change something as a one-off, just to test its impact (before modifying CMakeLists), was immensely useful.

Can I still find this window somewhere on a CMake project? And if not, would you consider forwarding my feedback?

Thanks a lot!

**Comment by corob-msft** [comment]
@patrikhuber 

I must have toggled the view once earlier, because after restarting VS I'm now seeing the same behavior for the default view you reported. I don't know why the view setting isn't persisted. The right place to make product suggestions is on [Developer Community](https://aka.ms/vsfeedback/browsecpp). You can also make suggestions from within Visual Studio, via **Help** > **Send Feedback** > **Suggest a Feature**.

The Property pages are fairly tightly coupled with the native MSBuild project system. MSBuild doesn't run for CMake projects, so there are no traditional project property pages to configure. The CMake configuration files are the equivalent. The current recommendation is to use a CMakePresets file for configuration. It's the new cross-platform wiredness, unlike the old CMakeSettings tiredness. Unfortunately, our tutorial doc is still mired in the past.

**Comment by corob-msft** [comment]
The documentation has been updated with a new screenshot and instructions.
