### ISSUE TITLE
Resource View menu item location wrong

### ISSUE THREAD

**Issue by ashemedai** [MicrosoftDocs/cpp-docs#3688]
In both VS 2019 and 2022 the location for the `Resource View` is directly under the `View` menu and not `View > Other Windows > Resource View`.

![image](https://user-images.githubusercontent.com/610865/152688335-6dcac24a-435d-4cc1-b142-d1f5ccd0db61.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 083a66ed-0671-9fce-8cf0-165fe8ba0c58
* Version Independent ID: 4317fe6c-3fb5-7a9a-4f35-dc1c2c4302b5
* Content: [Menu Editor (C++)](https://docs.microsoft.com/en-us/cpp/windows/menu-editor?view=msvc-170)
* Content Source: [docs/windows/menu-editor.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/menu-editor.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ashemedai 
Thanks for the report. An update should be visible later today.
