### ISSUE TITLE
Need to clarify the behavior 

### ISSUE THREAD

**Issue by santosh-kale** [MicrosoftDocs/cpp-docs#3690]
Following text under "Return Value" section is quiet hard to comprehend. 

If the buffer size specified by count isn't sufficiently large to contain the output specified by format and argptr, the return value of vsnprintf is the number of characters that would be written, not counting the null character, if count were sufficiently large. 

Maybe we can put it in this format: if a then x, if b then y 

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb683ba2-c8e8-9f2d-e265-f08b10495462
* Version Independent ID: 8b57f003-a4d3-48f1-e514-8a35b53d0bc7
* Content: [vsnprintf, _vsnprintf, _vsnprintf_l, _vsnwprintf, _vsnwprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I recently updated this topic with a table that does what you are asking for :-)
