### ISSUE TITLE
lower_bound function is missing a parameter.

### ISSUE THREAD

**Issue by fengbs** [MicrosoftDocs/cpp-docs#3691]
[Enter feedback here]
The code showed in title "Standard Library algorithms"，the parameter named val is missing in lower_bound function. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [Welcome back to C++ - Modern C++](https://docs.microsoft.com/en-us/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=msvc-170)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fengbs 
Thanks for the report. An update should appear later today.
