### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by kalosxx** [MicrosoftDocs/cpp-docs#3694]
[Enter feedback here]
    The code under sub title "Create a module unit implementation file" should be changed .
    in BasicPlane.Figures-Rectangle.cpp: change "module BasicPlane.Figures"  to "module BasicPlane.Figures:Rectangle",，otherwise,it can not be compiled correct.
    After changing，evne if this can compile and run correctly, the IDE will still prompt code errors in the document (IDE prompt taht the identifier of the structure that has been named in the module interface file is not found , although this error prompt will not prevent the compilation from proceeding correctly) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Version Independent ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Content: [Named modules tutorial in C++](https://docs.microsoft.com/en-us/cpp/cpp/tutorial-named-modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/tutorial-named-modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/tutorial-named-modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kalosxx Thanks for the report. This issue is now fixed.
