### ISSUE TITLE
Support files directory is missing for VS 2022

### ISSUE THREAD

**Issue by Syul968** [MicrosoftDocs/cpp-docs#3696]
The directory of support files for VS 2022 isn't listed in this reference page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374afe24-333d-6b11-f07f-8e6fc206f91d
* Version Independent ID: 423089d4-8106-c686-1903-2cac02595039
* Content: [MSBuild internals for C++ projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-visual-cpp-overview?view=msvc-170)
* Content Source: [docs/build/reference/msbuild-visual-cpp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/msbuild-visual-cpp-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Syul968 Thanks for the report. This issue is now fixed.
