### ISSUE TITLE
For some reason I have to use the clean command or I run into this error. 

### ISSUE THREAD

**Issue by Profit0004** [MicrosoftDocs/cpp-docs#370]
I am not sure what the exact mechanism is but if I do not run a clean command with certain programs I have wrote, it will throw this error.   Running clean seems to fix it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a03eb2c-c144-4c00-91e3-5d04ad54d367
* Version Independent ID: b2cc4888-d92a-f614-1d39-8e49a69ef243
* Content: [Linker Tools Error LNK2022](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2022?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2022)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%26rd%3Dtrue)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2022.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2022.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Profit0004 Hmmm we would need more information in order to be able to diagnose whether this is a product bug and/or whether we can improve the documentation. Did you try running  ildasm -tokens as suggested in the topic? That might provide a clue as to what is happening. In any case I'm glad you can fix it.
