### ISSUE TITLE
Example stack access code contains incorrect  immediate value

### ISSUE THREAD

**Issue by idcrook** [MicrosoftDocs/cpp-docs#3700]
Based on the prototype types (`int`) and correction for argument size

```asm 
        mov eax, [ebp+4] ; Get first argument
        mov ecx, [ebp+6] ; Get second argument
```

should instead be 

```diff 
         mov eax, [ebp+4] ; Get first argument
-        mov ecx, [ebp+6] ; Get second argument
+        mov ecx, [ebp+8] ; Get second argument
```

since it is referring to 32-bit int types, right? (4+4 == 8 not 6)

and actually it would be the following according to standard calling conventions:

```diff 
-        mov eax, [ebp+4] ; Get first argument
-        mov ecx, [ebp+6] ; Get second argument
+        mov eax, [ebp+8] ; Get first argument
+        mov ecx, [ebp+12] ; Get second argument
```

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98bfc236-120c-71db-ec5b-62ba2f843e45
* Version Independent ID: ff3fbc33-9193-3ece-1b4e-d134deb73b3c
* Content: [Writing Functions with Inline Assembly](https://docs.microsoft.com/en-us/cpp/assembler/inline/writing-functions-with-inline-assembly?view=msvc-170)
* Content Source: [docs/assembler/inline/writing-functions-with-inline-assembly.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/inline/writing-functions-with-inline-assembly.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@idcrook 
Thanks for the report. The sample assembly code has been updated, possibly for the first time since the 16-bit era.
