### ISSUE TITLE
why it not works if the memory is applied by 'new'?

### ISSUE THREAD

**Issue by 2021tzhanliw** [MicrosoftDocs/cpp-docs#3702]
![1644560651(1)](https://user-images.githubusercontent.com/88124064/153546240-6d99d250-259f-413b-9a49-7f40cebca880.png)

**Comment by corob-msft** [comment]
@2021tzhanliw 
That's a good question, but you're asking in the wrong place. A support question like this one belongs in [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or a similar forum, such as [StackOverflow](https://stackoverflow.com/questions/tagged/visual-c%2b%2b). I'm closing this as it's not a documentation issue. Best of luck.
