### ISSUE TITLE
Repeated sentence

### ISSUE THREAD

**Issue by JNjenga** [MicrosoftDocs/cpp-docs#3703]
>  If you do not declare a copy constructor, the compiler generates a member-wise copy constructor for you. If you do not declare a copy assignment operator, the compiler generates a member-wise copy assignment operator for you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002e4360-b090-f678-4b0d-8f6f19807a51
* Version Independent ID: 95c8ee85-464f-1196-3fa0-e3a6b0470f8b
* Content: [Copy Constructors and Copy Assignment Operators (C++)](https://docs.microsoft.com/en-us/cpp/cpp/copy-constructors-and-copy-assignment-operators-cpp?view=msvc-170)
* Content Source: [docs/cpp/copy-constructors-and-copy-assignment-operators-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/copy-constructors-and-copy-assignment-operators-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JNjenga 

There's a subtle but important difference between these two sentences:

> If you do not declare a **copy constructor**, the compiler generates a member-wise copy constructor for you. If you do not declare a **copy assignment operator**, the compiler generates a member-wise copy assignment operator for you.

I may add some clarification to highlight the difference.

**Comment by corob-msft** [comment]
Doc updated.
