### ISSUE TITLE
Incorrect struct in documentation for _fstat32 function

### ISSUE THREAD

**Issue by RickDaniels314** [MicrosoftDocs/cpp-docs#3706]
The documentation web page for the _fstat32 function shows a struct that has two underscores (__stat32) but there is no such struct in sys/types.h or sys/stat.h or anyother header they include.

int _fstat32(
   int fd,
   struct __stat32 *buffer
);

Also, in sys/stat.h, the definition for the _fstat32 function shows a struct with a single underscore (_stat32).

Consider changing the documentation web page for function _fstat32 to show:

    struct _stat32 *buffer
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8aa5d5d-582f-cd0f-7b8a-3f2dead80edd
* Version Independent ID: 3d7b89df-1937-d112-7479-c73fe7e8c21d
* Content: [_fstat, _fstat32, _fstat64, _fstati64, _fstat32i64, _fstat64i32](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fstat-fstat32-fstat64-fstati64-fstat32i64-fstat64i32?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/fstat-fstat32-fstat64-fstati64-fstat32i64-fstat64i32.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fstat-fstat32-fstat64-fstati64-fstat32i64-fstat64i32.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Fixed. Also fixed the extra leading underscore on __stat64
This will be live tomorrow afternoon (Thurs)
Thanks for taking the time to point this out.
