### ISSUE TITLE
Add mention of 'External Includes' page 

### ISSUE THREAD

**Issue by Snre3n** [MicrosoftDocs/cpp-docs#3713]
"Configuration Properties -> C/C++ -> External Includes "

There is no mention that this configuration page exist. I suggest adding a note about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d17b537f-8093-16f6-e52f-b83cf4fc5c6f
* Version Independent ID: 6b66bc39-47d6-a2da-bb84-bab42702e925
* Content: [/external (External headers diagnostics)](https://docs.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics?view=msvc-170)
* Content Source: [docs/build/reference/external-external-headers-diagnostics.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/external-external-headers-diagnostics.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Snre3n 
Thanks for the suggestion. I've updated the docs with the relevant IDE directions, and added the F1 links from the Property Pages dialog to the docs.
