### ISSUE TITLE
Reference URL's are broken

### ISSUE THREAD

**Issue by georgii-displayr** [MicrosoftDocs/cpp-docs#372]
The following references are broken in this document:
- http://go.microsoft.com/fwlink/p/?linkid=95428
- http://go.microsoft.com/fwlink/p/?linkid=20012

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6cac15-3494-2247-f162-06669c09ab5e
* Version Independent ID: eb8794ff-d93d-76fe-36d2-3a65f51132bf
* Content: [Porting from UNIX to Win32](https://docs.microsoft.com/en-au/cpp/porting/porting-from-unix-to-win32)
* Content Source: [docs/porting/porting-from-unix-to-win32.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/porting-from-unix-to-win32.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Thanks for spotting this issue. A fix is in the works and should be published in a day or two.
For now, you can use these updated links:

> The [UNIX Custom Application Migration Guide](https://technet.microsoft.com/library/bb656290.aspx) provides technical help on code migration from UNIX to the Win32 environment.  
  
> The [Unix Migration Project Guide](https://technet.microsoft.com/library/bb656287.aspx) supplements the UNIX Custom Application Migration Guide by providing high-level help on migrating substantial projects from UNIX to Win32. The Guide provides advice on issues to consider at each stage of project migration.

**Comment by corob-msft** [comment]
Closing as fixed.
