### ISSUE TITLE
There is no documentation for C4815

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#3728]
repro: https://godbolt.org/z/5xzEbx87x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc3041c-b233-bb3f-513f-b3df302b49a2
* Version Independent ID: aad153bd-a417-01fb-f2b7-50842269dcc0
* Content: [Compiler warnings C4800 Through C5999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
We don't document all of the warnings. Only the ones that we feel need additional explanation and would benefit from the time required to document them.
