### ISSUE TITLE
Address confusion about meaning of the properties that affect modules consumption

### ISSUE THREAD

**Issue by TylerMSFT** [MicrosoftDocs/cpp-docs#3729]
[The compiler ignores the properties 'Additional BMI Directories' and 'Public C++ Module Directories' for no apparent reason. - Visual Studio Feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Ft%2Fthe-compiler-ignores-the-properties-additional-bmi%2F1665757%3Ffrom%3Demail%26viewtype%3Dall%23T-ND1676302&data=04%7C01%7CTyler.Whitney%40microsoft.com%7C2af4614b5d9b4c4e0b9f08d9f7e3be99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813379800957706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z8b0c4OaMixzAvfDT5k4GUpxpcrCWv%2BhFL0TaC9pcJM%3D&reserved=0)

It would be good to add more info and maybe samples in the documentation for those properties:
  VC++ Directories – Public C++ Module Directories, All modules are public
  C/C++ - General – Additional BMI directories, Additional Module Dependencies
              Output Files – Module Output File Name

**Comment by corob-msft** [comment]
Right now, the F1 target for the **All Header Files are Public**, **Public C++ Module Directories**, and **All Modules are Public** properties is the [VC++ Directories property page doc](https://docs.microsoft.com/en-us/cpp/build/reference/vcpp-directories-property-page&view=msvc-170#public-project-content). This location isn't ideal for examples. The same is true for **Additional BMI Directories** where F1 takes you to the [C/C++ Property Pages doc](https://docs.microsoft.com/en-us/cpp/build/reference/c-cpp-prop-page?view=msvc-170#additional-bmi-directories). There's no `/ifcSearchDir[path]` compiler option article; this option isn't even advertised by the compiler, and I've seen no other mention of its existence.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
