### ISSUE TITLE
Code highlighting in assert macro usage example makes blue color out of variable name "string".

### ISSUE THREAD

**Issue by TilKenneth** [MicrosoftDocs/cpp-docs#3735]
Actual:
- The text "string" is highlighted as blue for a keyword.

Expected:
- "string" should be regular text color.

Maybe:
- also "stdout", strlen, printf?

![crt_assert c](https://user-images.githubusercontent.com/2411856/155879726-46d249cd-1bc0-4d2b-bebb-5ab11e4b83da.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84710ecd-e868-8f06-7e95-7f68538a4f07
* Version Independent ID: b737afb6-cb68-810d-5a99-b696f54d2640
* Content: [assert Macro, _assert, _wassert](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-macro-assert-wassert?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/assert-macro-assert-wassert.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/assert-macro-assert-wassert.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT 
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@TilKenneth 

Thanks for the report. This defect exists in the third-party code colorizer used by Microsoft Docs, and unfortunately, the C++ docs team doesn't have any way to fix it from within the C++ docs repo. It's annoying, but I'm going to resolve this as something we can't fix. I'll try to pursue it internally with the team that maintains the Docs infrastructure. Sorry I don't have a better solution for you.
