### ISSUE TITLE
Seeming contradiction in "Binary Compatibility between Visual Studio 2015 and Visual Studio 2017"?

### ISSUE THREAD

**Issue by dschepler** [MicrosoftDocs/cpp-docs#374]
I'm confused about what seems to be contradictory information on whether a DLL compiled using Visual Studio 2017 will work when linked with an executable compiled using Visual Studio 2015.

One exception listed is:
2. When consuming libraries built with a toolset whose version is greater than the toolset used to compile and link the application.

But the information also states that the toolset version is v140 for Visual Studio 2015 and v141 for Visual Studio 2017.  So, it seems to me that this restriction would make the VS2017 DLL + VS2015 main executable case impossible.

However, the document also explicitly states "This means, for example, that you can create a DLL in Visual Studio 2017, and consume it from an application compiled with Visual Studio 2015."

So, is there something I'm missing here that would resolve the contradiction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcccbfe4-34d9-67cb-efbb-6c15ff35b38e
* Version Independent ID: cc082cbf-a967-6709-f3ef-190e78cf84e9
* Content: [C++ Binary Compatibility between Visual Studio 2015 and Visual Studio 2017](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017)
* Content Source: [docs/porting/binary-compat-2015-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/binary-compat-2015-2017.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Hi @dschepler Agreed the text seems to contradict itself. We'll work on improving that soon. But the short answer is that this is definitely true: "you can create a DLL in Visual Studio 2017, and consume it from an application compiled with Visual Studio 2015."

**Comment by mikeblome** [comment]
@dschepler My previous response was incorrect and I have deleted it to avoid further confusion.  Binary compat between 2015 and 2017 is guaranteed only when the consuming code is built with a toolset/compiler version that is the same or newer than the toolset/compiler used to build the library. So, a VS2015 exe + VS2017 DLL is not guaranteed to be compatible. The doc will be updated. Apologies!

**Comment by fengsiri** [comment]
Let's assume there is a folder which contains a custom exe, a custom dll and crt dlls. Both the custom exe and the custom dll are linked dynamically to crt dlls. I'm confused by several combinations listed below. please tell me which combination's binary compatibility will be guaranteed.

1) exe built by vs2015 + dll/static lib built by vs2015 + crt dlls of vs2015
I think binary compatibility can be guaranteed in this case.

2) exe built by vs2015 + dll/static lib built by vs2015 + crt dlls of vs2017
based on case 1, crt dlls were replaced with newer version that's shipped with vs2017.

3) exe built by vs2015 + dll/static lib built by vs2017 + crt dlls of vs2015
base on case 1, the custom dll was rebuilt using vs2017.

4) exe built by vs2015 + dll/static lib built by vs2017 + crt dlls of vs2017
base on case 1, the custom dll was rebuilt using vs2017 and crt dlls were replaced with newer version that's shipped with vs2017.

5) exe built by vs2017 + dll/static lib built by vs2015 + crt dlls of vs2015
base on case 1, the custom exe was rebuilt using vs2017 and the import lib for the custom dll which was previously built by vs2015

6) exe built by vs2017 + dll/static lib built by vs2015 + crt dlls of vs2017
base on case 1, the custom exe was rebuilt using vs2017 and the import lib for the custom dll which was previously built by vs2015. Additionally crt dlls were replaced with newer version that's shipped with vs2017.
