### ISSUE TITLE
Page on Temporary Objects has confusing language in discussing const ref assignment and lifetime

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/cpp-docs#3745]
The C++ language deliberately specifies that binding to a const ref extends the lifetime of a temporary, and this doesn't really jive with the language on the "Temporary Objects" page, which never talks about extending the lifetime.  Instead it uses confusing language that makes it hard to know whether it's safe to bind a temporary to a const ref.

The page says:

> All temporaries created as a result of expression evaluation are destroyed at the end of the expression statement (that is, at the semicolon), or at the end of the controlling expressions for for, if, while, do, and switch statements.

And then:

> If an initializer is not an l-value of the same type as the reference being initialized, a temporary of the underlying object type is created and initialized with the initialization expression. This temporary object is destroyed immediately after the reference object to which it is bound is destroyed.

These statements appear not to be mutually exclusive, since initializers are expressions, and it does not sound like there is any "lifetime is extended" situation going on.

For Something like:

`
Object GetTemporaryObject() { return Object(); }
...

const auto& var = GetTemporaryObject();
`

The const ref assignment hits both entries in the table:  it is the result of an expression that results in a temporary object, and it is not an l-value of the same type (because it's an r-value), which results in another temporary object.  

I suspect the rules in the table were meant to be mutually exclusive, but the language is confusing; 

a. the use of the word "expression" doesn't preclude use as an initializer in assignment, and 
b. the page never talks about extending lifetimes, it instead talks about two different temporaries, one of which has a longer lifetime.

There may be an unambiguous interpretation of "expression" and "initializer" that precludes my interpretation here, but it seems like it would be clearer to just rewrite in terms of a temporary and in terms of the possibility of extending the lifetime of that temporary, the way the C++ language specifies it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 141455f0-b37a-a152-517c-7364ad6468b9
* Version Independent ID: f5ca5d19-2efa-164b-577e-7a03b2d388cc
* Content: [Temporary Objects](https://docs.microsoft.com/en-us/cpp/cpp/temporary-objects?view=msvc-170)
* Content Source: [docs/cpp/temporary-objects.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/temporary-objects.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Updated a week ago, so closing as fixed.
