### ISSUE TITLE
How to use API SetDisplayConfig to do turn off display?

### ISSUE THREAD

**Issue by meichunwu** [MicrosoftDocs/cpp-docs#3747]
After reviewed  [SetDisplayConfig ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setdisplayconfig) , no idea how do turn off display ? Would you provide some suggestion ?

**Comment by corob-msft** [comment]
@meichunwu 

I'm sorry, we don't have information about [`SetDisplayConfig`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setdisplayconfig) aside from what's in the documentation. It's not part of the C++ docs, so I'm closing this issue. You'll have a better chance of getting your Win32 API questions answered on [Windows Developer Support](https://developer.microsoft.com/windows/support) or [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/products/windows) for Windows, Best of luck!
