### ISSUE TITLE
atl com

### ISSUE THREAD

**Issue by JPSALI** [MicrosoftDocs/cpp-docs#3754]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed74a66-79ce-a12b-6b2f-ee575e0e013b
* Version Independent ID: cffec919-0f2c-ce74-2a68-90bcb69eb548
* Content: [Scope of ATL](https://docs.microsoft.com/en-us/cpp/atl/scope-of-atl?view=msvc-170)
* Content Source: [docs/atl/scope-of-atl.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/atl/scope-of-atl.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, no problem is described in this issue. Closing. @JPSALI, reopen if you recall what you wanted us to take a look at here.
