### ISSUE TITLE
There are no examples of how to use the special "File Name parts"

### ISSUE THREAD

**Issue by Martini-DJ** [MicrosoftDocs/cpp-docs#3756]
There are no examples of how to use the special "File Name parts"
It would be nice to see some working examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bb1aa3-a4ac-1bb5-f232-54eed4fca4c1
* Version Independent ID: da4631dd-bb32-73e7-83e6-7c1336a6c526
* Content: [Commands in a Makefile](https://docs.microsoft.com/en-us/cpp/build/reference/commands-in-a-makefile?view=msvc-170)
* Content Source: [docs/build/reference/commands-in-a-makefile.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/commands-in-a-makefile.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
