### ISSUE TITLE
Can user-defined types be returned by value from non-static member functions?

### ISSUE THREAD

**Issue by scyclzy** [MicrosoftDocs/cpp-docs#3758]
"User-defined types can be returned by value from global functions and static member functions. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87b11e0-0214-175b-0926-0f8a4653e444
* Version Independent ID: 43e8bf4a-9a0d-ea28-d432-ead828604d5e
* Content: [x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170)
* Content Source: [docs/build/x64-calling-convention.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/x64-calling-convention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@scyclzy 

Yes, but perhaps not efficiently in a register. For non-POD types too large to fit in a register, your caller has to allocate space for the return value and pass a pointer to this location as the first parameter. The C++ compiler does this behind the scenes on your behalf, but you need to know what's going on "under the hood" if you want to interface compiled code with x64 assembly.

**Comment by corob-msft** [comment]
Maybe I should say, "for *any* type too large to fit in a register" above.
