### ISSUE TITLE
Setting LTCG in Visual Studio 2017

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/cpp-docs#376]
I just spent a fair amount of time searching in vain for the "Whole Program Optimization" setting in the property sheets. Eventually, I found the /LTCG switch in the choices for "Link Time Code Generation." Perhaps the page should be amended to reflect this change, and whether the change is new in VS 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b1cf62-ddfd-ce9a-b43f-c1e59b675fb7
* Version Independent ID: 0926975c-6c19-0c88-a306-d2b960716a7f
* Content: [/LTCG (Link-time Code Generation)](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation)
* Content Source: [docs/build/reference/ltcg-link-time-code-generation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/ltcg-link-time-code-generation.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by txwizard** [comment]
![vs_2017_ltcg_switch_20180804_155342](https://user-images.githubusercontent.com/19792705/43680367-c00d63da-97fe-11e8-8993-1113803036a1.png)
The above link is a print screen of the property page in question.

**Comment by corob-msft** [comment]
These options have been around with these names for a long time. **Whole Program Optimization** is the [/GL](https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization) compiler option, found in your project's **Property Pages** dialog under **Configuration Properties > C/C++ > Optimization** at the end of the list. If you enable it, you should also enable **Link Time Code Generation** (the [/LTCG](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation) linker option) on the **Configuration Properties > Linker > Optimization** page. On the command line, the linker does the right thing by default if you've set /GL, but I would set it in the IDE anyway just to be sure, especially if you've set other non-default linker options.

**Comment by DBJDBJ** [comment]
I think this same issue caught up with me ... clang release build only. Visual Studio 2019 completely up to date as of 2020-JAN-18.  The [Solution is here](https://github.com/dbj-data/dbjsysloglib).

Pretty small-ish syslog win syslog client ...
