### ISSUE TITLE
Additional details on /external:I option

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/cpp-docs#3760]
Some users expect header files included through double-quotes to be treated as "external" headers if they reside in the directory specified in the /external:I option. However, only those that are included through angle brackets (e.g., #include <external.h>) will be treated as "external" header (if it is from the directory specified in /external:I option).

Please add this detail to the document (and hopefully with some explanation on why) so that users can have correct expectations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d17b537f-8093-16f6-e52f-b83cf4fc5c6f
* Version Independent ID: 6b66bc39-47d6-a2da-bb84-bab42702e925
* Content: [/external (External headers diagnostics)](https://docs.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics?view=msvc-170)
* Content Source: [docs/build/reference/external-external-headers-diagnostics.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/external-external-headers-diagnostics.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by hwisungi** [comment]
It seems that this is no longer the case. I will need to dig deeper to confirm the behavior.

**Comment by hwisungi** [comment]
It seems this behavior has changed since 17.0. 16.11 still requires angle brackets for headers to be considered as "external".

**Comment by corob-msft** [comment]
@hwisungi 
Does that mean we need to call out 16.11 behavior separately from 17+?
