### ISSUE TITLE
Difference between pin_ptr and GCHandle

### ISSUE THREAD

**Issue by davidwld** [MicrosoftDocs/cpp-docs#3761]
For a System.Boolean y:
Why can I use pin_ptr<bool> x = &y;

But I can't write
GCHandle handle = GCHandle::Alloc(y,GCHandleType::Pinned);

I understand that System::Boolean is not blittable but how does it then work for the pin_ptr ? 
Thank you for your answer!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0081ad48-5ba0-62a3-ea45-1b40a4ab1c3e
* Version Independent ID: 374b3001-5ef4-02b6-9bd2-f495a5f85ab5
* Content: [pin_ptr (C++/CLI)](https://docs.microsoft.com/en-us/cpp/extensions/pin-ptr-cpp-cli?view=msvc-170)
* Content Source: [docs/extensions/pin-ptr-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/extensions/pin-ptr-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@davidwld 
That's an interesting question, but it's out of scope for the docs issues board. We're not a equipped for answering support-like questions. Off the top of my head the answer would involve implicit boxing in the first instance, but I could be wrong. For questions like this one, I recommend asking on [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck!
