### ISSUE TITLE
Compiler option: does "/Zc:threadSafeInit" depend on CRT or UCRT?

### ISSUE THREAD

**Issue by pzhlkj6612** [MicrosoftDocs/cpp-docs#3763]
Hello!

First of all, I'm sorry that I'm not using any templates as my question is related two doc pages.

## Question

In _**Storage classes (C++)**_ ([docs](https://docs.microsoft.com/en-us/cpp/cpp/storage-classes-cpp), [github](https://github.com/MicrosoftDocs/cpp-docs/blob/aa5600508bddcb77052ae712924047a13cd7052a/docs/cpp/storage-classes-cpp.md)), we have:

> Starting in C++11, a **`static`** local variable initialization is guaranteed to be thread-safe. This feature is sometimes called *magic statics*. However, in a multithreaded application all subsequent assignments must be synchronized. The thread-safe static initialization feature can be disabled by using the [/Zc:threadSafeInit-](#) flag to avoid taking a dependency on the CRT.

In _**/Zc:threadSafeInit (Thread-safe Local Static Initialization)**_ ([docs](https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization), [github](https://github.com/MicrosoftDocs/cpp-docs/blob/aa5600508bddcb77052ae712924047a13cd7052a/docs/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization.md)), we also have:

> Thread-safe initialization of static local variables relies on code implemented in the Universal C run-time library (UCRT). To avoid taking a dependency on the UCRT, or to preserve the non-thread-safe initialization behavior of versions of Visual Studio prior to Visual Studio 2015, use the **/Zc:threadSafeInit-** option. If you know that thread-safety is not required, use this option to generate slightly smaller, faster code around static local declarations.

So, which one does the "/Zc:threadSafeInit" option depend on?

**Comment by corob-msft** [comment]
@pzhlkj6612 

The facetious answer to the question in the issue title is "Yes." There's no difference between the CRT and the UCRT. they're just slightly different names for the same thing. The CRT got renamed to UCRT when it was refactored and became a Windows component in the Visual Studio 2015 timeframe. We didn't change the name everywhere in the docs at the same time. Sorry if it seemed to trip you up here.
