### ISSUE TITLE
Modules overview claims that importing a header doesn't drag in macros transitively

### ISSUE THREAD

**Issue by StephanTLavavej** [MicrosoftDocs/cpp-docs#3766]
This says:

> Some headers are sufficiently self-contained that they can be brought in using the **`import`** keyword. The main difference between an imported header and an imported module is that any preprocessor definitions in the header are visible in the importing program immediately after the `import` statement. However, preprocessor definitions in any files included by that header aren't visible.

I don't believe that the final sentence ("However, preprocessor definitions in any files included by that header aren't visible.") is correct, according to the C++20 Standard. Here is a fully worked example, compiled with VS 2022 17.2 Preview 1, demonstrating that `import <vector>;` makes the preprocessor definition of `__cpp_lib_constexpr_vector` available, even though `<vector>` includes our internal header `<yvals_core.h>` to get that definition:

```
C:\Temp>"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.2.0-pre.1.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Temp>type macros.cpp
```
```cpp
import <vector>;

#include <stdio.h> // include UCRT, avoid including STL <cstdio>

int main() {
#ifdef __cpp_lib_constexpr_vector
    puts("__cpp_lib_constexpr_vector IS defined.");
#else
    puts("__cpp_lib_constexpr_vector is NOT defined.");
#endif
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /Zc:preprocessor /MD /exportHeader /headerName:angle /Fo /MP vector
vector

C:\Temp>cl /EHsc /nologo /W4 /std:c++latest /Zc:preprocessor /MD /headerUnit:angle vector=vector.ifc macros.cpp vector.obj
macros.cpp

C:\Temp>macros
__cpp_lib_constexpr_vector IS defined.

C:\Temp>grep -rP __cpp_lib_constexpr_vector "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31114\include"
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31114\include/yvals_core.h:#define __cpp_lib_constexpr_vector        201907L

C:\Temp>
```

Thanks to u/James20k on Reddit for finding this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@StephanTLavavej 

It's more than likely that the text has been superseded by implementation changes in the three years since that caveat was originally added.
