### ISSUE TITLE
Found small typo/inconsistency 

### ISSUE THREAD

**Issue by morgan-elder** [MicrosoftDocs/cpp-docs#3767]
The first step says open Games.cpp.
But in the other pages of the guide/doc, the file is called Game.cpp. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5318fad1-2580-ea35-5bd3-8a37ec5dc0b9
* Version Independent ID: 28cf188d-6993-eba0-0dde-99af44f25aca
* Content: [Walkthrough: Testing a Project (C++)](https://docs.microsoft.com/en-us/cpp/ide/walkthrough-testing-a-project-cpp?view=msvc-170)
* Content Source: [docs/ide/walkthrough-testing-a-project-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/ide/walkthrough-testing-a-project-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fixed.
