### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by jereytucker** [MicrosoftDocs/cpp-docs#3769]
#3764 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1fa38-809e-5525-1241-d2dca23c705d
* Version Independent ID: a3b2385f-5cf3-7ac6-ebce-d71dc39c83d9
* Content: [Build an OpenGL ES application on Android and iOS](https://docs.microsoft.com/en-us/cpp/cross-platform/build-an-opengl-es-application-on-android-and-ios?view=msvc-160)
* Content Source: [docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jereytucker 
I'm sorry, I don't see any actionable issue here. If you'd like to elaborate on what's incorrect or missing from the documentation, we can revisit this issue.
