### ISSUE TITLE
OKR: Discovery

### ISSUE THREAD

**Issue by mcleblanc** [MicrosoftDocs/cpp-docs#3775]
GOAL:
Drive discovery and awareness through SEO improvements.

OBJECTIVES:
Perform selective SEO audits on the following candidate topics:

[Create a console calculator in C++](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp)
[C and C++ in Visual Studio](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-in-visual-studio)
[Determining Which DLLs to Redistribute](https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute)
[Deploy an App By Using the Redistributable Package](https://docs.microsoft.com/en-us/cpp/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package)
[Desktop Applications (Visual C++)](https://docs.microsoft.com/en-us/cpp/windows/desktop-applications-visual-cpp)
[Walkthrough: Build and Debug C++ with Microsoft Windows Subsystem for Linux 2 (WSL 2) and Visual Studio 2022](https://docs.microsoft.com/en-us/cpp/build/walkthrough-build-debug-wsl2)
[C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis)
[Build an OpenGL ES application on Android and iOS](https://docs.microsoft.com/en-us/cpp/cross-platform/build-an-opengl-es-application-on-android-and-ios)
[Install the C++ Linux workload in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload)
[Redistributing Visual C++ ActiveX Controls](https://docs.microsoft.com/en-[us/cpp/windows/redistributing-visual-cpp-activex-controls)
[Deploy a Visual C++ Application By Using a Setup Project](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-by-using-a-setup-project)
[Running a C++ -clr Application on a Previous Runtime Version](https://docs.microsoft.com/en-us/cpp/windows/running-a-cpp-clr-application-on-a-previous-runtime-version)
[MSBuild on the command line - C++](https://docs.microsoft.com/en-us/cpp/build/msbuild-visual-cpp)
[ClickOnce Deployment for Visual C++ Applications](https://docs.microsoft.com/en-us/cpp/windows/clickonce-deployment-for-visual-cpp-applications)
[x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions)
[Install cross-platform mobile development with C++](https://docs.microsoft.com/en-us/cpp/cross-platform/install-visual-cpp-for-cross-platform-mobile-development) 
[Create an Android Native Activity App](https://docs.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app)
[Create a CMake Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project)
[Visual Studio Projects - C++](https://docs.microsoft.com/en-us/cpp/build/creating-and-managing-visual-cpp-projects)

RESULTS:
Improved organic search rates (>60%) for audited topics.

**Comment by corob-msft** [comment]
Working on [Deploy a Visual C++ Application By Using a Setup Project](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-by-using-a-setup-project).

**Comment by TylerMSFT** [comment]
Working on [Visual Studio Projects - C++](https://docs.microsoft.com/en-us/cpp/build/creating-and-managing-visual-cpp-projects)

**Comment by TylerMSFT** [comment]
Closing per resourcing.
