### ISSUE TITLE
Misleading info about _Pragma operator scope

### ISSUE THREAD

**Issue by Veggie13** [MicrosoftDocs/cpp-docs#3776]
Under the _Pragma Preprocessor Operator section, before the example it states "The _Pragma statement only applies to the line of code that follows it." While that's true of the particular code in the example because it is a warning(suppress), it is not true in general. _Pragma() seems to behave the same as #pragma.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce8f0a4b-8eeb-158f-3995-66fa674e67d1
* Version Independent ID: d9e7ec65-7238-a9fb-6ab3-dc71144e3a34
* Content: [Pragma directives and the __pragma and _Pragma keywords](https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=msvc-170)
* Content Source: [docs/preprocessor/pragma-directives-and-the-pragma-keyword.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/preprocessor/pragma-directives-and-the-pragma-keyword.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Veggie13 
I'm sorry you found the statement confusing. The line "The _Pragma statement only applies to the line of code that follows it" is context-specific, applying only to the example. In the interest of clarity, I'll add the phrase "in the example" to it somewhere.

**Comment by corob-msft** [comment]
Fixed.
