### ISSUE TITLE
Direct links to vcredist files for VC++ 10.0 SP1 are out of date

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/cpp-docs#3780]
Direct links to vcredist files for VC++ 10.0 SP1 are out of date. The links point to version 10.0.40219.1, while the download page at https://www.microsoft.com/en-ca/download/details.aspx?id=26999 has version 10.0.40219.235

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@amandeepmand 
Thanks for the report. An updated version of the article is available now.
