### ISSUE TITLE
Option checkbox "Use CMakePresets.json to drive ..." missing in VS2022 17.1.1

### ISSUE THREAD

**Issue by cromlegionar** [MicrosoftDocs/cpp-docs#3782]
Hello, 

i am using the Microsoft document to "Configure and build with CMake Presets in Visual Studio".
I noticed that in the section about enabling the usage of CMakePresets.json it says:
"In Visual Studio 2022 and Visual Studio 2019 version 16.10 and later, Tools > Options > CMake > General has a single option to enable CMakePresets.json integration."
I use VS 2022 17.1.1, but I have the radio button selection with 3 Options when to use CMakePresets rather than CMakeSettings. Is this correct? 
In my understanding according to the text I should have one checkbox instead of the 3 radio buttons selection.

Thank you very much for your answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#-enable--cmakepresetsjson-integration-in-visual-studio)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cromlegionar 
Thanks for the report. A clarification for the images and which versions they apply to is available now.
