### ISSUE TITLE
Error in GetFieldValue

### ISSUE THREAD

**Issue by Jeremyrx** [MicrosoftDocs/cpp-docs#3787]
GetFieldValue prototypes has the last two exactly the same.  One should allow the index name not the index number for the case of returning a string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71164027-2c34-9866-08c8-8ceef252b0a8
* Version Independent ID: 9a2b95ed-065d-cb52-29e5-669d232230c0
* Content: [CRecordset Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/crecordset-class?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(AFXDB%252FCRecordset%253A%253AGetFieldValue);k(CRecordset%253A%253AGetFieldValue);k(GetFieldValue);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/mfc/reference/crecordset-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/crecordset-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Jeremyrx, thank you for flagging this issue. I've put it in my queue to address.

**Comment by TylerMSFT** [comment]
Hi @Jeremyrx, I noticed that the last two aren't the same, they differ in type (CStringA vs CStringW). But I think your point was that there were a couple missing, which I added:
void GetFieldValue(
    LPCTSTR lpszName,
    CStringA& strValue
);
void GetFieldValue(
    LPCTSTR lpszName,
    CStringW& strValue
);
This fix should be live by end of day 5/12/2022
Thanks for pointing out the issue.
