### ISSUE TITLE
Alignment bug in "1. Chained, #localsz <= 512"

### ISSUE THREAD

**Issue by egelke** [MicrosoftDocs/cpp-docs#3790]
In the section "ARM64 stack frame layout", the first code snippet contains a alignment error.

It reads:
```asm
    stp    x19,x20,[sp,#-96]!        // pre-indexed, save in 1st FP/INT pair
    stp    d8,d9,[sp,#16]            // save in FP regs (optional)
    stp    x0,x1,[sp,#32]            // home params (optional)
    stp    x2,x3,[sp,#48]
    stp    x4,x5,[sp,#64]
    stp    x6,x7,[sp,#72]
    stp    x29,lr,[sp,#-localsz]!   // save <x29,lr> at bottom of local area
    mov    x29,sp                   // x29 points to bottom of local
    sub    sp,sp,#outsz             // (optional for #outsz != 0)
```

Line 6 says writes x6 and x7 to offset _72_, but it should be _82_.

So,  it should read:
```asm
    stp    x19,x20,[sp,#-96]!        // pre-indexed, save in 1st FP/INT pair
    stp    d8,d9,[sp,#16]            // save in FP regs (optional)
    stp    x0,x1,[sp,#32]            // home params (optional)
    stp    x2,x3,[sp,#48]
    stp    x4,x5,[sp,#64]
    stp    x6,x7,[sp,#82]
    stp    x29,lr,[sp,#-localsz]!   // save <x29,lr> at bottom of local area
    mov    x29,sp                   // x29 points to bottom of local
    sub    sp,sp,#outsz             // (optional for #outsz != 0)
```

It is the same issue with the other code snippets in the same section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425e365b-d9a1-365e-d33f-0ab2645ce4f2
* Version Independent ID: 63f31be3-6a82-dd87-6d5d-9aa4e748703f
* Content: [ARM64 exception handling](https://docs.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-160)
* Content Source: [docs/build/arm64-exception-handling.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/arm64-exception-handling.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@egelke 
Thanks for the report. An update with corrections is available now.
