### ISSUE TITLE
[question] what is the masm32.com website?

### ISSUE THREAD

**Issue by Foadsf** [MicrosoftDocs/cpp-docs#3796]
When looking for MASM tutorials on the internet, a lot of them suggest the [masm32.com](https://www.masm32.com/) as a place to download the Microsoft Macro Assembler. It is even the first search result on Google, at least for me. Is this an MS-certified website? Do you approve of it? And if it is an MS-controlled website, why not point to the current documentation? I would appreciate it if you could clarify and help me with the confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c3c771-9918-8405-925d-53f774e06e43
* Version Independent ID: c978ec3e-a8a7-c7ff-41fa-aa196df32b44
* Content: [MASM for x64 (ml64.exe)](https://docs.microsoft.com/en-us/cpp/assembler/masm/masm-for-x64-ml64-exe?view=msvc-170)
* Content Source: [docs/assembler/masm/masm-for-x64-ml64-exe.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/assembler/masm/masm-for-x64-ml64-exe.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Foadsf 

The masm32.com site has no connection to Microsoft. It appears to host an independent, alternative development environment for MASM called **MASM SDK Version 11**. It's not a Microsoft product. I haven't checked, but it appears from the [MASM SDK documentation](https://www.masm32.com/download.htm) that the MASM SDK installs a *very* old version of the Microsoft Assembler, contrary to the license. While I don't know whether this MASM SDK is any good, I'm *certain* that you don't want to use that old version of the MASM assembler.

In general, you should be wary of third-party hosts for Microsoft products, tools, DLLs, and so on. They're operating contrary to Microsoft licenses, and they could be sources of malware. Microsoft doesn't license its tools or header files for inclusion as part of another product. You can [download and install the tools and header files from Microsoft](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170) yourself and use them in any development environment you want. However, the makers of other development environments can't legally host Microsoft tools and headers as part of their own download and installation.
