### ISSUE TITLE
[BUG] C2280 occurs with std::unique_ptr : Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by yeokaiwei** [MicrosoftDocs/cpp-docs#3798]
### **PROBLEM**
Visual Studio 2019 has an issue with errors associated with std:;unique_ptr.

You can't use std::unique_ptr as a direct replacement for a raw pointer.

Intellisense will not notice a problem, it will just show the green tick and "No issues found"

The following code will spout out C2280 without any additional information.

The problem with C2280 is that it will not tell you which line/where the error occurred at. 

Please add your own int main(){}

Subject.h
```
#pragma once
#include "Observer.h"
#include <iostream>
#include <vector>
#include <memory>
#include <algorithm>
#include <bitset>
#include <array>

class Subject
{
private:
	std::vector< std::unique_ptr<Observer> > vupObservers;

protected:
	Subject();

public:
	virtual	~Subject();
       //C2280 occurs in the following line of code
	virtual void attach(std::unique_ptr<Observer> obs);
        
       //You have to use 
       //virtual void attach(Observer* obs);
};

```

Subject.cpp
```
#include "Subject.h"

Subject::Subject()
{}

Subject::~Subject()
{}

//C2280 occurs here
void Subject::attach(std::unique_ptr<Observer> test)
{
	vupObservers.emplace_back(test);
}

//This will not cause C2280
//void Subject::attach(Observer* test)
//{
//	vupObservers.emplace_back(test);
//}
```

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2280	'std::unique_ptr<Observer,std::default_delete<Observer>>::unique_ptr(const std::unique_ptr<Observer,std::default_delete<Observer>> &)': attempting to reference a deleted function	tet	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory	714	
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5bc2bb-82b6-a12c-2496-618f18757863
* Version Independent ID: 763e7e70-8432-841f-4d65-f5636778b9bf
* Content: [Compiler Error C2672](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2672?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2672.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-2/compiler-error-c2672.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yeokaiwei 

Sorry you've run into difficulties. This is not a bug in the compiler. The problem is that you're trying to copy a `unique_ptr` when you pass it as a parameter to `emplace_back`. Unfortunately, the error message shows how the standard library prevents the copy, and not what you're doing that's incorrect. This error report isn't unique to Microsoft. Both clang and gcc return similar error messages for your code. You may want to look at using `std::move` instead, depending on what you're trying to do with `unique_ptr`, or switch to using a `shared_ptr`. Best of luck.
