### ISSUE TITLE
cmake setting no find specific parameter

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3800]
here is my build command
```
cmake -G Ninja -DSYS_TYPE=123
```

ENV: visual studio 2019. 
I cant find any  SYS_TYPE on cmake setting.
So I build fail with visual studio 2019 (F5).
How can I add parameter ?

**Comment by alicera** [comment]
https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-170#command-arguments
Do you have the example 
cmakeCommandArgs and buildCommandArgs

**Comment by corob-msft** [comment]
@alicera 

If you use a *`CMakeSettings.json`* file,  then you can pass command-line arguments in a `buildCommandArgs` or `cmakeCommandArgs` setting in each configuration, like so:

```
{
  "configurations": [
    {
      "name": "x86",
      "buildCommandArgs": "-v",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "cmakeCommandArgs": "",
      "configurationType": "Debug",
      "ctestCommandArgs": "",
      "generator": "Ninja",
      "inheritEnvironments": [ "msvc_x86" ],
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "variables": []
    },
    {
      "name": "x64",
      "buildCommandArgs": "-v",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "cmakeCommandArgs": "",
      "configurationType": "Debug",
      "ctestCommandArgs": "",
      "generator": "Ninja",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "variables": []
    }
  ]
}
```

If you use *`CMakePresets.json`*, then you can set command line arguments in `buildPresets` items by using `nativeToolOptions`:

```
  "buildPresets": [
    {
      "name": "default-build-linux",
      "displayName": "Default",
      "configurePreset": "linux-debug",
      "description": "Vanilla build"
    },
    {
      "name": "verbose-build-linux",
      "displayName": "Verbose Build",
      "description": "Passes -v to Ninja",
      "configurePreset": "linux-debug",
      "nativeToolOptions": [ "-v" ]
    }
  ]
```

Where to add the `-DSYS_TYPE=123` flag depends on what it's an option for. I don't know the answer to that question.

**Comment by alicera** [comment]
Could you give me more information about how to type the cmakeCommandArgs and buildCommandArgs.
If there is a example, it will be good.

![image](https://user-images.githubusercontent.com/59388989/160800115-32ab7806-ca1b-4a41-a3f1-11ed7f13ec07.png)

**Comment by corob-msft** [comment]
@alicera 

Did you try entering something like your example, `-DSYS_TYPE=123` in the **Build command arguments** field? I don't know if this will work, since I don't know what that option means, but if it works on the cmake build command line, it should work here.

**Comment by alicera** [comment]
When use Cmake command arguments?

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
