### ISSUE TITLE
Editing CMakeLists.txt files sample

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3804]
In the image, it say could not find sqlite3.How do you solve it ?

https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-projects-in-visual-studio.md#editing-cmakeliststxt-files-1

![image](https://user-images.githubusercontent.com/59388989/160797882-b6f3c6b6-eb60-41f8-ae03-79774dca2f69.png)

**Comment by corob-msft** [comment]
@alicera 

This sounds suspiciously like a support question. Follow the [Vcpkg integration](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-projects-in-visual-studio.md#vcpkg-integration) directions above, and use a `.\vcpkg install sqlite3` command to make sqlite3 available. Next, follow the instructions in the error message to add the path to `Findsqlite3.cmake` into `CMAKE_MODULE_PATH`.

**Comment by alicera** [comment]
If I fix some sqlite3 code or I want to build some specific function about sqlite3.
How to do that? Is it still `.\vcpkg install sqlite3` ?

For example 
https://gist.github.com/ocdude/fe924f0c118274b65648#file-install-ffmpeg-sh-L65
ffmpeg have many enable lib.
vcpkg how to solve it
