### ISSUE TITLE
Different styles for commands

### ISSUE THREAD

**Issue by a-v-s** [MicrosoftDocs/cpp-docs#381]
In "Adding a class to the static library", the note about using the command line, has different formatting for the first and second command used to create the library.  &lt;code&gt; vs &lt;strong&gt;

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/nl-nl/cpp/windows/walkthrough-creating-and-using-a-static-library-cpp)
* Content Source: [docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@a-v-s Thanks! This is now fixed and should be visible on the public page today or tomorrow.
