### ISSUE TITLE
Page references a non-existent SAL annotation.

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/cpp-docs#3813]
> This warning indicates that the function prototype for the function being analyzed has a `__drv_acquiresMemory` annotation. The `__drv_acquiresMemory` annotation indicates that the function acquires memory in the designated result location, but in at least one path, the function did not acquire the memory.

No `__drv_acquiresMemory` can be found in any of the WDK headers. Instead I've observed C28195 being emitted when `__drv_allocatesMem` (found in driverspecs.h) is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc7a13e-b9ed-838f-12d1-c3d48b3ea7cf
* Version Independent ID: 6892ebb6-30c3-983a-a269-4443f130cc2a
* Content: [C28195](https://docs.microsoft.com/en-us/cpp/code-quality/c28195?view=msvc-170)
* Content Source: [docs/code-quality/c28195.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c28195.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wmjdgla Thanks for the report.

@sunnychatterjee The commenter makes a good point. Does C28195 match more than one annotation in use, or did the annotation name change at some point?

**Comment by sunnychatterjee** [comment]
The annotation name should indeed be changed to `__drv_allocatesMem`

**Comment by sunnychatterjee** [comment]
#3823 fixes the issue.

**Comment by corob-msft** [comment]
@sunnychatterjee Awesome, thanks! This update should appear in published content tomorrow.
