### ISSUE TITLE
vc142 vc143

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3814]
![image](https://user-images.githubusercontent.com/59388989/162111538-d29dc99c-5de5-48a9-bfe2-1b16a4bafc0b.png)

Do you have the table for checkout version ?
vc142=vs2019 ...

**Comment by corob-msft** [comment]
@alicera 

I'm sorry, I don't understand what you're asking for. What do you mean by "checkout version"? Given what's highlighted in your image, if you want to know more precisely which version of the v142 or v143 toolset is in use, you'll have to check the properties for the tools directly. Visual Studio will generally pick up the latest version of a toolset that you've installed. The Visual Studio Installer has several recent versions of the toolset available as optional components, if you need a specific version for your use case.

**Comment by alicera** [comment]
Don't worry.
Just a table.

**Comment by corob-msft** [comment]
While I appreciate documentation ideas, this one doesn't seem useful. It would only duplicate information already visible in the dialog.
