### ISSUE TITLE
Incorrect information about upgrade from earlier versions of Visual Studio for VS2022

### ISSUE THREAD

**Issue by levicki** [MicrosoftDocs/cpp-docs#3816]
The part which says:

> To upgrade a project created in an earlier version of Visual Studio, **just open the project in the latest version of Visual Studio**. Visual Studio offers to upgrade the project to the current schema.

Is flat out incorrect for Visual Studio 2022 -- you cannot upgrade `.dsw` and `.dsp` based projects from Visual C++ 6 in the latest Visual Studio even though it was possible as recently as in Visual Studio 2019. There is a community feedback for this issue and nobody from VS Team seems interested in addressing it:

https://developercommunity.visualstudio.com/t/how-can-i-upgrade-the-old-versionex-visual-c-60-pr/1557405

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349f9d38-ee28-e99a-6527-241d9a4bf8f3
* Version Independent ID: d2b2131f-38a8-2bbf-3403-1064a2b75a7c
* Content: [Upgrade C++ projects from earlier versions of Visual Studio](https://docs.microsoft.com/en-us/cpp/porting/upgrading-projects-from-earlier-versions-of-visual-cpp?view=msvc-170)
* Content Source: [docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/porting/upgrading-projects-from-earlier-versions-of-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@levicki 

Thanks for the report. Upgrade from VC6 projects and workspaces is deprecated in Visual Studio 2022. The docs now make this clear, and suggest a workaround.

**Comment by levicki** [comment]
@corob-msft Thanks for adding the note.

However, described "workaround" boils down to "install this other older multi-gigabyte software package to convert two small files because we removed conversion functionality for no good reason".

Many Windows programming books, especially on COM programming still come with code examples for VC6 which now cannot be opened in Visual Studio 2022.

I was hoping that someone from your team could raise awareness with VS Team that said functionality is still needed, and if it cannot be added back, at least they could release a standalone conversion tool.

**Comment by corob-msft** [comment]
@levicki 
The way to get attention from the developers is to upvote the Developer Community issue. If there's some sign of demand, it's more likely to get some of their limited time and attention. Lobbying the Docs team doesn't improve those chances unless we can also show them the numbers. One report is an anecdote. A hundred votes is data.

**Comment by levicki** [comment]
@corob-msft I understand.

By the way, if Microsoft had better COM documentation (with complete modern code examples of Out-Of-Process COM servers and proper registration procedures), we wouldn't need to convert outdated VC6 project examples from outdated COM programming books so there wouldn't even be this one report.

Sorry for the offtopic and have a nice day.
