### ISSUE TITLE
Differences in the How to for Visual Studio Pro

### ISSUE THREAD

**Issue by gunterfuchs** [MicrosoftDocs/cpp-docs#3818]
In Visual Studio 2019 Professional, some details in the steps are slightly different:

1. To create an MFC dialog based application, choose MFC App as the project type, not the Wizard. The Wizard creates a Window based application. The easiest way to find this project type is to search for "MFC". Then only one project type is found as a desktop application which is the right one to select. Also, for that project type don't hesitate pressing the _Create_ button. It will not yet create the project but will pop up a project configuration dialog in which one can configure the application type, for example a dialog based one.
2. The configuration for Common Language Runtime support, _\clr_, can be found at the project properties under "Configuration Properties / Advanced / Common Language Runtime Support".
3. In step 5, the _include_ line has to be inserted into _framework.h_, not _Stdafx.h_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6b9db41-a73f-73a3-fd0e-f4b756f38eb2
* Version Independent ID: 0970feb1-0b72-48c3-f5a0-fd568df9e36a
* Content: [How to: Create the User Control and Host in a Dialog Box](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box?view=msvc-160)
* Content Source: [docs/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/dotnet/how-to-create-the-user-control-and-host-in-a-dialog-box.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@gha2z, thank you for taking the time to write. The docs should generally target the latest version of Visual Studio. So, we wouldn't target them for 2019, but when resources allow, they should reflect the latest version of VS (2022, currently). Adding to the backlog.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
