### ISSUE TITLE
Single catch

### ISSUE THREAD

**Issue by stevev6** [MicrosoftDocs/cpp-docs#382]
The example shows how to catch a generic exception, how do you just catch one...like just the range_error exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9ea5ac-beae-be31-375a-45bcdf08c830
* Version Independent ID: 58acf6e9-cc30-4b42-9fcd-fe01f5e42e3d
* Content: [range_error Class](https://docs.microsoft.com/en-us/cpp/standard-library/range-error-class)
* Content Source: [docs/standard-library/range-error-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/range-error-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Ma-XX-oN** [comment]
You just catch that exception.
```c++
   try
   {
      throw range_error( "The range is in error!" );
   }
   catch (range_error &e)
   {
      cerr << "Caught: " << e.what( ) << endl;
      cerr << "Type: " << typeid( e ).name( ) << endl;
   };
```
Understanding how to use exception handling in C++ is IMO, beyond the scope of this particular help file.  Maybe under **See Also** there should be a link to a document on this subject?

**Comment by stevev6** [comment]
Thanks, that's the example i was looking for.
like
https://msdn.microsoft.com/en-us/library/6dekhbbc.aspx
you can add the specific , followed by the generic for a more complete description.
eg
 ```
try
   {
      throw range_error( "The range is in error!" );
   }
   catch (range_error &e)
   {
      cerr << "Caught: " << e.what( ) << endl;
      cerr << "Type: " << typeid( e ).name( ) << endl;
   }
 catch (exception &e)
   {
      cerr << "Caught: " << e.what( ) << endl;
      cerr << "Type: " << typeid( e ).name( ) << endl;
   };
```

Out of curiosity, what's the difference between 
`catch (exception &e)`
and
`catch ( ... )`

I would expect them to be equivalent.

**Comment by corob-msft** [comment]
> Out of curiosity, what's the difference between
> `catch (exception &e)`
> and
> `catch ( ... )`

The first expression catches anything of type `exception` or types derived from `exception`. However, you can throw exceptions of any type, not just ones derived from `exception`. The second expression catches all exceptions not already caught. If you've used the /EHa compiler option, this includes Structured Exceptions. This is almost never a good idea. You should only catch the exceptions you're prepared to handle, and leave the rest alone. If no higher-level code is prepared to catch a particular exception, then it's better to terminate than try to limp along in an unknowable state.
