### ISSUE TITLE
How to bind a constructor parameter to RUNTIME_CLASS class

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#3831]
Fx if I want to set the generated parameter, CWnd* pParent = NULL, to a value, if it can be done, then this page should tell me how to do it. If it can't be done, this page should say that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd00558d-bce5-b479-8eba-55f83b751857
* Version Independent ID: 7c4c6c5c-1834-da74-4990-dff4542070fa
* Content: [Run-Time Object Model Services](https://docs.microsoft.com/en-us/cpp/mfc/reference/run-time-object-model-services?view=msvc-170)
* Content Source: [docs/mfc/reference/run-time-object-model-services.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/run-time-object-model-services.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
