### ISSUE TITLE
The program does work in the way: "print please wait..., wait 5 seconds, and then print \nAll done." without "flush"

### ISSUE THREAD

**Issue by Xingchen1224** [MicrosoftDocs/cpp-docs#3836]
- Without flush
  - It seems that if I use Visual Studio 2019/2022 and XCode, copy and paste the code snippet below, and start the program with or without debugging , the program will work in the way - "print please wait..., wait 5 seconds, and then print \nAll done."
  - Even I use **_cl effects_buffering.cpp /EHsc_**, the program also works in the above way.
  - I also tried to compile the source code with "**_g++ effects_buffering.cpp_**" or "**_clang++ effects_buffering.cpp_**" on my mac terminal and launch the program, the behaviour matches the description in the document - "nothing printed, wait 5 seconds, and then print please wait... \nAll done."
- With flush
  - if `<< flush` is added after `cout << "Please wait...`
  - all of the situations above works in the same way: "print please wait..., wait 5 seconds, and then print \nAll done."

``` c++
// effects_buffering.cpp
// compile with: /EHsc
#include <iostream>
#include <time.h>
using namespace std;

int main( )
{
   time_t tm = time( NULL ) + 5;
   cout << "Please wait...";
   while ( time( NULL ) < tm )
      ;
   cout << "\nAll done" << endl;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f0ac96b-f76c-5a48-f8a3-40fe043f0c3c
* Version Independent ID: 0deafc25-dbcc-17f6-6c42-11ccea9ce084
* Content: [Effects of Buffering](https://docs.microsoft.com/en-us/cpp/standard-library/effects-of-buffering?view=msvc-170#feedback)
* Content Source: [docs/standard-library/effects-of-buffering.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/standard-library/effects-of-buffering.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
