### ISSUE TITLE
Unclear instructions for MFC walk-through

### ISSUE THREAD

**Issue by robcat2075** [MicrosoftDocs/cpp-docs#3839]
I'm reading the "Walkthrough: Using the New MFC Shell Controls" page.

[https://docs.microsoft.com/en-us/cpp/mfc/walkthrough-using-the-new-mfc-shell-controls?view=msvc-160](url)

What appears in Visual Studio does not match the directions...

Under "Prerequisites" it contains the sentence... 

> "Make sure the **Desktop Development with C++** tile is checked. Under **Optional Components**, check the **MFC Support** button."

In my Visual Studio 2019 >Modifying>Visual Studio Community 2019>16.11.12 window there is no item labeled "Optional Components"

Do you really mean to refer me to the "Optional" _heading_ under "Installation details"?

There is also no button labeled "MFC support"

Do you really mean that I should enable the checkbox labeled "C++ MCF for latest v142 build tools..."

See screen capture below...

![image](https://user-images.githubusercontent.com/103955095/163846853-0bc9b434-8944-4764-b5e7-483bb9149549.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42d62b6-ccf2-e5e6-fb25-25100c70fe38
* Version Independent ID: 51ede8ba-a8b3-0868-bee1-e2635309afb6
* Content: [Walkthrough: Using the New MFC Shell Controls](https://docs.microsoft.com/en-us/cpp/mfc/walkthrough-using-the-new-mfc-shell-controls?view=msvc-160)
* Content Source: [docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hello @robcat2075, thank you for pointing this out.

This documentation is older and we have been prioritizing getting content out for newer technology that we've added support for, such as the standard template library. 
I will add updating this tutorial to reflect the latest tools to my list of things to do, but it may be a bit until I can get to it.

**Comment by robcat2075** [comment]
But... what is the correct action to do here in this tutorial?

Are the items I pointed to indeed what is intended by the text?

**Comment by TylerMSFT** [comment]
@robcat2075 , yes, choose the options you have called out in your screenshot.

If you need support for MFC, consider the [Developer community](https://developercommunity.visualstudio.com/search?space=62&q=mfc). 

There is a MFC post on stackoverflow [here](https://stackoverflow.com/questions/43074045/mfc-development-in-vs2017/43075169#43075169) that may be useful if you have more questions.

**Comment by TylerMSFT** [comment]
Tagging for future followup.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
