### ISSUE TITLE
The new operators are missing

### ISSUE THREAD

**Issue by avifarah** [MicrosoftDocs/cpp-docs#384]
This article needs to be updated as per "?." operator precedence and order of evaluation.  (We need not guess that it is equivalent to the "." operator)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc4f59b-159f-5038-fc24-4e78c7dff783
* Version Independent ID: f0015080-14af-58f1-15bb-c2691ea4186f
* Content: [Precedence and Order of Evaluation](https://docs.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation)
* Content Source: [docs/c-language/precedence-and-order-of-evaluation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/precedence-and-order-of-evaluation.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@avifarah Can you please clarify? Do you mean the ? :  ternary operator?

**Comment by avifarah** [comment]
I do not mean the ternary operator but the Elvis operator, the "?." (also called the Safe Navigation Operator).  So for example if we have a class instance, x and a member m, then x.m is the correct way to access m.  However if x can be null then a safe way to access m is x?.m. Now if x is not null then x?.m will operate as x.m did, but if x is null then x?.m will not throw an exception instead x?.m will return null.  Please note that this Elvis operator is not the only missing operator.  Thank you for paying attention to my comment.

**Comment by corob-msft** [comment]
@avifarah You may be looking in the wrong place. This is the C++ documentation, not the C# documentation. If you're looking for the **?.** C# language feature, then you want to look at the [Null-conditional operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#null-conditional-operator) documentation. C++ has no such operator. (I was curious if it had been added to C++20, but the [latest draft standard](https://github.com/cplusplus/draft/blob/master/papers/n4762.pdf) mentions no such thing.) The gcc compiler does support a [non-standard "Elvis operator"](https://gcc.gnu.org/onlinedocs/gcc/Conditionals.html#Conditionals) **?:** with an absent second operand, but MSVC does not.

I'm closing this issue as not relevant to this document. I'm a little sorry the C++ language does not accommodate you; it looks like a feature that could simplify some code.

**Comment by corob-msft** [comment]
@avifarah You know what, I was looking at the wrong article, the one for C++ instead of C. However, the **?.** operator isn't supported by the C compiler, either. It's not part of the C11/C17/C18 language standard, nor C99, which is approximately what the MSVC C compiler supports.
