### ISSUE TITLE
Macro definitions in afx.h producing code analysis warnings

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/cpp-docs#3841]
The `IMPLEMENT_DYNAMIC` macro in afx.h takes the following arguments:

- the name of the class one is implementing
- the name of the base class that the implemented class is to inherit from

The macro defines functions that override those of the base class. As per documentation, the macro is to be accompanied by `DECLARE_DYNAMIC`, inserted in the class declaration.

However, `DECLARE_DYNAMIC` does not use the `noexcept` and `override` keyword when declaring the overriding `GetRuntimeClass` function. So VS code analysis would emit the following warning at `IMPLEMENT_DYNAMIC`:

> C26433 `Function 'MyClass:GetRuntimeClass' should be marked with 'override' (c.128).`
> C26440 `Function 'MyClass:GetRuntimeClass' can be declared 'noexcept' (f.6).`

Test sample:
In .h:
```c++
class MyClass : public CDialogEx
{
    DECLARE_DYNAMIC(MyClass)
}
```
In .cpp:
```c++
IMPLEMENT_DYNAMIC(MyClass, CDialogEx)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd00558d-bce5-b479-8eba-55f83b751857
* Version Independent ID: 7c4c6c5c-1834-da74-4990-dff4542070fa
* Content: [Run-Time Object Model Services](https://docs.microsoft.com/en-us/cpp/mfc/reference/run-time-object-model-services?view=msvc-170)
* Content Source: [docs/mfc/reference/run-time-object-model-services.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/run-time-object-model-services.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @wmjdgla, it seems that you are reporting a product issue rather than a documentation issue, in this case due to the march of progress in the C++ language vs. MFC which was released in 1992. 

If that is the case, you could consider bringing this up on 
[developer community](https://developercommunity.visualstudio.com/search?space=62) where it will be seen by the product team.
Take care.
