### ISSUE TITLE
Incorrect description of the "/headerUnit" option linked from the "/headerName" page.

### ISSUE THREAD

**Issue by tahonermann** [MicrosoftDocs/cpp-docs#3845]
The "Seel also" section of this page states:
- "/headerUnit (Create header units)"
That should state:
- "/headerUnit (Use header unit IFC)"

See https://docs.microsoft.com/en-us/cpp/build/reference/headerunit?view=msvc-160.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 864f2f33-4556-7728-cfe7-7059d20c69e4
* Version Independent ID: f62225a6-70f7-5a46-a1e2-c1bfd6d7fe4c
* Content: [/headerName (Build a header unit from the specified header)](https://docs.microsoft.com/en-us/cpp/build/reference/headername?view=msvc-160)
* Content Source: [docs/build/reference/headername.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/headername.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @tahonermann . Fixed.
The topic will update live by tomorrow afternoon (Fri, 4/22)
