### ISSUE TITLE
abs() overloaded

### ISSUE THREAD

**Issue by fabrinkman** [MicrosoftDocs/cpp-docs#3848]
My code :
			if (abs(num.re) < 9e-16)
				num.re = 0.0L;

num.re is of type long double. Why does this give an error C2668 and how can I correct it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d197e53e-a819-3761-eb32-479b3429377a
* Version Independent ID: d5f6ef3c-53af-bd1d-cbc2-51aed8224e52
* Content: [Compiler Error C2668](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2668?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2668)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2668.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-2/compiler-error-c2668.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fabrinkman 
I'm sorry you're having difficulty. I'm also sorry that this isn't the place for your question. We don't have the bandwidth to do product support here. Also, there isn't enough context in your example to tell you why you're seeing the error. You'll need to indicate what the type and type definition for `num` and `num.re` are, including any overloaded constructors and assignment operators. The compiler is complaining that it can't decide between alternatives for the operators used in `num.re = 0.0L;`.. Take this question (along with the extra information needed to help you) to a support forum such as [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck in your coding.
