### ISSUE TITLE
setlocale() crashes when given an invalid locale category

### ISSUE THREAD

**Issue by kevinushey** [MicrosoftDocs/cpp-docs#3859]
The documentation states:

> If the locale or category isn't valid, returns a null pointer, and the current locale settings of the program are unchanged.

However, it appears that invalid category numbers will actually cause a crash. For example:

```
#include <locale.h>

int main() {
    setlocale(42, NULL);
}
```

when compiled and executed with Visual Studio 2022, I get a debug assertion:

![image](https://user-images.githubusercontent.com/1976582/165813288-1683f65d-0005-41e9-beba-c4d86ba2588f.png)

And in release builds, I get a crash:

```
C:\Users\kevin\source\repos\SetLocale\x64\Release\SetLocale.exe (process 45688) exited with code -1073740791.
Press any key to close this window . . .
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170&viewFallbackFrom=msvc-171)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by kevinushey** [comment]
I also see (later in the documentation):

> This function validates the category parameter. If the category parameter isn't one of the values given in the previous table, the invalid parameter handler is invoked, as described in [Parameter Validation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=msvc-170). If execution is allowed to continue, the function sets errno to EINVAL and returns NULL.

Maybe that same documentation needs to be reflected in the description of the return value?

**Comment by kevinushey** [comment]
My proposal would be to update the Return value documentation to state something like:

> If a valid locale and category are given, returns a pointer to the string associated with the specified locale and category. If the locale or category isn't valid, the invalid parameter handler is invoked, as described in [Parameter Validation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=msvc-170). If execution is allowed to continue, the function sets errno to EINVAL and returns NULL. See [Remarks] for more details.

**Comment by TylerMSFT** [comment]
@kevinushey - thank you. I will work on incorporating this feedback as soon as I can. Really appreciate you taking the time to help make things better here.

**Comment by kevinushey** [comment]
@TylerMSFT and thank you for taking the time to respond and consider these changes, I appreciate it!

**Comment by TylerMSFT** [comment]
I think you make an excellent suggestion. The fix should be live by end of day tomorrow (5/6).
Thank you for helping us improve the docs.
