### ISSUE TITLE
Not conforming to standard.

### ISSUE THREAD

**Issue by Sorennnn** [MicrosoftDocs/cpp-docs#3864]
If Microsoft makes the modue std available then that does not conform to C++ standard, and code written importing std will not compile with other compilers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Sorennnn 
If the standard library modules feature was available in a standards conformance mode such as [`/std:c++20`](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170), you'd be correct. The requirements to use [`/std:c++latest` (Use](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170) and [`/experimental:module`](https://docs.microsoft.com/en-us/cpp/build/reference/experimental-module?view=msvc-170) are how we indicate that a feature doesn't conform to the current standard. The `/std:c++latest` option enables all currently implemented compiler and standard library features proposed for the *next* draft standard, as well as some in-progress and experimental features. We think this preview of a future standard feature is important and useful enough to highlight it here, but it won't compile with Microsoft C++ in C++20 mode, either.
