### ISSUE TITLE
TOOLTIPTEXT structure is missing documentation for the uflags member.

### ISSUE THREAD

**Issue by gshultz21** [MicrosoftDocs/cpp-docs#3867]
TOOLTIPTEXT structure is missing documentation for the uflags member.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7836ce52-5a5a-f154-2857-64a26595ce04
* Version Independent ID: 01b4782f-0303-b7ab-7538-bb7a9a365ae7
* Content: [TOOLTIPTEXT Structure](https://docs.microsoft.com/en-us/cpp/mfc/tooltiptext-structure?view=msvc-170)
* Content Source: [docs/mfc/tooltiptext-structure.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/tooltiptext-structure.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
