### ISSUE TITLE
straight forward and clear

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/cpp-docs#387]
I really appreciate the concise, precise, complete language I'm seeing in the C Language Reference.  There must have been a large effort to accomplish this.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bcbd9c-deb2-5a1a-d78b-ed4fc551bcc5
* Version Independent ID: 8c3ae6e2-9bd6-bbf4-d80b-a69576a84f8e
* Content: [Arguments to main](https://docs.microsoft.com/en-us/cpp/c-language/arguments-to-main)
* Content Source: [docs/c-language/arguments-to-main.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/arguments-to-main.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@mrmsbarnes Working on the docs from day to day, we mostly see the bugs and the areas that need updates, so it's good to hear our work is appreciated. Thanks!
