### ISSUE TITLE
Ampersand could be better aligned.

### ISSUE THREAD

**Issue by TypeICall** [MicrosoftDocs/cpp-docs#3872]
So obviously a written figure, not a representative figure. Needs changed. 
Looks something like-
|-|
but with connected lines... It could show up when people hit ampersand from now on.
maybe 
=|-|=
except with connected lines would also work....
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d1d88e-f68b-36e5-8451-a35edb6cfed4
* Version Independent ID: 0aa72a2b-cb1e-45c0-408f-0098fcb88da8
* Content: [Logical AND Operator: &&](https://docs.microsoft.com/en-us/cpp/cpp/logical-and-operator-amp-amp?view=msvc-170)
* Content Source: [docs/cpp/logical-and-operator-amp-amp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/logical-and-operator-amp-amp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TypeICall** [comment]
Geeze.... That didn't show up anywhere near properly...
Might have to break out the crayon box.

**Comment by corob-msft** [comment]
@TypeICall 
I'm sorry, I don't see anything like what you describe in the article. Is there a formatting issue you see?

> Looks something like-
> `|-|`
> but with connected lines... It could show up when people hit ampersand from now on.
> maybe 
> `=|-|=`
> except with connected lines would also work....

I'm not seeing anything that this comment could apply to here. Can you clarify the issue for me?

**Comment by TypeICall** [comment]
The ampersand symbol is not representative of the concept of 'and.'
It could be written similar to the OR symbol ||, except with a connection, making it look like capital 'H' or it could be typed '|-|'
I am uncertain of how to go in to unicode to pull out a character from there to make it show up when the ampersand button is struck while also having it read by the compiler as being representative of the same concept. It seems that their attribution of the Greek Capital Letter Lambda is also not representative of the concept of 'and' either or at least I see no visual acuity to that symbol befitting the concept it is said to represent in this programming language.

**Comment by corob-msft** [comment]
@TypeICall 
Thanks for sharing your notion. I don't think we need to invent a new symbol to replace something that already exists. [There are already several symbols for 'and' in common use.](https://en.wikipedia.org/wiki/List_of_logic_symbols) The inventors of C decided that `&&` was the way they'd represent a logical and operator, and we've been using it ever since. This isn't an issue we need to worry about, so I'm closing it.
