### ISSUE TITLE
cstdarg

### ISSUE THREAD

**Issue by haryouli90** [MicrosoftDocs/cpp-docs#3878]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6e98ac-3987-7225-e696-893da982c327
* Version Independent ID: 12952d1d-0573-a883-6359-00935d42f3eb
* Content: [&lt;cstdarg&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/cstdarg?view=msvc-170)
* Content Source: [docs/standard-library/cstdarg.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/standard-library/cstdarg.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@haryouli90  - I don't see any feedback here. Please reopen with what you'd like to comment on about this topic.
