### ISSUE TITLE
Print Capability

### ISSUE THREAD

**Issue by kringej** [MicrosoftDocs/cpp-docs#388]
Could you please add a button to print this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [Errors and Exception Handling (Modern C++)](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp#feedback)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@kringej Do you see a "Download PDF" link below the navigation pane on the left. You might need to scroll down to see it, depending on your display settings.
