### ISSUE TITLE
Mentioned requirements to compile a C file are unclear/outdated

### ISSUE THREAD

**Issue by berzi** [MicrosoftDocs/cpp-docs#3882]
The page mentions the requirement to install "the C++ build tools workload" but the installer contains no such entry under "Workloads" or elsewhere. It is presently nigh on impossible to determine what the minimum requirements to install just to compile a C file are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96f0a01-2e3a-6301-bba1-6a50252555b0
* Version Independent ID: 290ca773-a214-e81a-2ba3-c647f2b28a56
* Content: [Walkthrough: Compile a C program on the command line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-170)
* Content Source: [docs/build/walkthrough-compile-a-c-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/walkthrough-compile-a-c-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@berzi 
Thanks for the report, and sorry it's giving you difficulty. Use the **Desktop development with C++** workload to install the C, C++, and Assembly tools and libraries for Visual Studio 2022. This is the same workload name used for these tools when you install the full IDE. In older versions of Visual Studio, the workload was named **C++ build tools** when you downloaded the Build Tools version of the Visual Studio Installer. The documentation team wasn't warned about this change, so we didn't update the docs when the change occurred.
