### ISSUE TITLE
Lambda operator is absent in the precedence table

### ISSUE THREAD

**Issue by Vaskaran** [MicrosoftDocs/cpp-docs#3884]
It will be helpful to add the lambda operator in the operator precedence table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc4f59b-159f-5038-fc24-4e78c7dff783
* Version Independent ID: f0015080-14af-58f1-15bb-c2691ea4186f
* Content: [Precedence and order of evaluation](https://docs.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation?view=msvc-170)
* Content Source: [docs/c-language/precedence-and-order-of-evaluation.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-language/precedence-and-order-of-evaluation.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Vaskaran 
I'm not sure I understand what you're asking for. I'm not aware of a "lambda operator". There are *lambda expressions*, which act like any other expression in terms of precedence. Lambda expressions represent a class type called a *closure type*. They have a public inline function call operator, which is a long-winded way of saying that you can call a lambda immediately by appending `()` to it (with arguments, if needed). Can you clarify what you mean in your question? What problem are you trying to solve?

**Comment by Vaskaran** [comment]
> @Vaskaran I'm not sure I understand what you're asking for. I'm not aware of a "lambda operator". There are _lambda expressions_, which act like any other expression in terms of precedence. Lambda expressions represent a class type called a _closure type_. They have a public inline function call operator, which is a long-winded way of saying that you can call a lambda immediately by appending `()` to it (with arguments, if needed). Can you clarify what you mean in your question? What problem are you trying to solve?

[Vaskaran] Please refer this link: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions where the doc says "Use the lambda declaration operator( =>)  to separate the lambda's parameter list from its body."
The online link https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator also says about the lambda operator.

**Comment by corob-msft** [comment]
@Vaskaran 
If you want information about the C# lambda operator, you're looking at the wrong documentation. This article is about the C language, which doesn't have lambda constructs. (I was confused by the question and thought it was about C++, which does have lambda expressions.) You want the [Operator precedence](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence) table for C#, instead. I'm closing this issue as unrelated to the article. Best of luck with your coding.

**Comment by Vaskaran** [comment]
> 

Purely my mistake.Thanks for the help. My apologies.
