### ISSUE TITLE
MSVC /sourcedependencies needs update for 2022.2

### ISSUE THREAD

**Issue by ArcEarth** [MicrosoftDocs/cpp-docs#3889]
Updated to VS2022.2, and noticed the .json file produced by `cl /sourcedependencies` is now version 1.2.
It will be better to list the specs and changes from v1.1 -> v1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8697ff9c-9a88-50ff-9b23-a85cdbee123a
* Version Independent ID: be639a51-dc95-429f-ad7c-141c0717340c
* Content: [/sourceDependencies (Report source-level dependencies)](https://docs.microsoft.com/en-us/cpp/build/reference/sourcedependencies?view=msvc-170)
* Content Source: [docs/build/reference/sourcedependencies.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/sourcedependencies.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
