### ISSUE TITLE
`<algorithm>` doc file missing example implementation output + problem with `equal_range` example

### ISSUE THREAD

**Issue by BrandonPacewic** [MicrosoftDocs/cpp-docs#3892]
Doc file [algorithm-functions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/algorithm-functions.md) is missing output of example code in numerous locations. 

The code example for `equal_range` has compile errors when compiling with `c++17`.

ISO paper for this feature: [PaperID]()
First implemented in: VS YYYY major.minor

**Comment by TylerMSFT** [comment]
This is fixed by https://github.com/MicrosoftDocs/cpp-docs/pull/3893.  Thanks, Brandon.
