### ISSUE TITLE
About virtual list LVN_GETDISPINFO  notification.

### ISSUE THREAD

**Issue by williamdale** [MicrosoftDocs/cpp-docs#3895]
Hi there, 

I notice that when virtual list requires data, it will require all sub-items' information whether those sub-items are visible or not.
Is there some possible method that limits the virtual list to only requires sub-items that are to be displayed?
As the virtual list only requires  main items that are to be displayed, i guess it is also easy to be implemented for sub-items.
Any hints or suggestions?

best regards
william

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778584a2-910f-3974-f8de-8b532484f799
* Version Independent ID: 876fceb3-7d26-9117-09dd-593b1da7a0b7
* Content: [Virtual List Controls](https://docs.microsoft.com/en-us/cpp/mfc/virtual-list-controls?view=msvc-170)
* Content Source: [docs/mfc/virtual-list-controls.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/virtual-list-controls.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @williamdale, 
Unfortunately, I don't have a good answer for you. This question may be better suited for a MFC forum site like https://www.codeproject.com/Forums/1647/C-Cplusplus-MFC
