### ISSUE TITLE
Dereferencing iterator

### ISSUE THREAD

**Issue by GauthamBanasandra** [MicrosoftDocs/cpp-docs#390]
I'm getting this error even when I dereference an iterator as shown here -
https://github.com/GauthamBanasandra/CompetitiveCoding/blob/master/UVa/UVa/Problem%20solving%20paradigms/Divide%20and%20conquer/Binary%20search/10567/Helping%20Fill%20Bates.cpp#L55

The rest of the compilers like g++ etc didn't complain at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9c7ff1-d52c-4358-0506-6a99913fb36b
* Version Independent ID: 5cc874a7-23b2-9363-7cb7-de45fdeb27d0
* Content: [Compiler Error C2100](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2100?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2100)%26rd%3Dtrue)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2100.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2100.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@GauthamBanasandra I couldn't get your code to compile in MSVC, because it couldn't find a match for std::lower_bound that takes three arguments. Are you using a different standard library? If you build your code in the VS IDE and hover over the find_candidate variable, what type does the Intellisense report?

**Comment by GauthamBanasandra** [comment]
@corob-msft Thanks for you reply. I figured out the issue, I forgot to include the algorithm header - https://github.com/GauthamBanasandra/CompetitiveCoding/blob/master/UVa/UVa/Problem%20solving%20paradigms/Divide%20and%20conquer/Binary%20search/10567/Helping%20Fill%20Bates.cpp#L5-L8
Visual C++ compiles fine after adding that header file.
