### ISSUE TITLE
Compiler Error (NOT Warning) C4789

### ISSUE THREAD

**Issue by jmporter34** [MicrosoftDocs/cpp-docs#3905]
Hello,
I'm getting C4789 reported as an error, not a warning.  In the project properties, my warning level is set to 1 and Treat Warnings as Errors is set to No.  I added the recommended lines around the offending code:

#pragma warning( push )
#pragma warning( disable : 4789 )
// my code that generates compiler error (NOT warning) C4789`
#pragma warning( pop )

And it STILL fails to compile, reporting error C4789.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771af8fa-b7dd-3db1-7d4e-91462941d410
* Version Independent ID: 57d31fa1-7482-8bba-60c7-19e971d2483d
* Content: [Compiler Warning (Level 1) C4789](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4789?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4789.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4789.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jmporter34 
I'm sorry you're having trouble. The behavior you describe is unexpected. This sounds like a support issue, not a documentation issue, so I'm closing it. I recommend asking a product support forum that can help you figure out what's happening with your project settings. [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) is one possibility. Best of luck with your project.
