### ISSUE TITLE
Behavior with /MP and /sourceDependencies (+ etc) unclear

### ISSUE THREAD

**Issue by shuffle2** [MicrosoftDocs/cpp-docs#3908]
`/sourceDependencies` (and other options, like `/scanDependencies`, `/sourceDependencies:directives`) can output in 1 of 3 modes: stdout, a single file, or a directory.

They mention something like:
> When you specify the /MP compiler option, we recommend you use /scanDependencies with a directory argument. If you provide a single filename argument, two instances of the compiler may attempt to open the output file simultaneously and cause an error. For more information on /MP, see [/MP (Build with multiple processes)](https://docs.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170).

However this does not cover the case where `/MP` is used with the output to stdout mode. In testing, it seems to work, albeit the json output is a bit nonstandard (the json objects are listed back-to-back, without any delimiting commas or enclosing `[]` to make it an array). The compiler also does not indicate it is disabling `/MP` because the option is passed (unlike `/showIncludes`, for example, which does output e.g. `cl : Command line warning D9030 : '/showIncludes' is incompatible with multiprocessing; ignoring /MP switch`). Inspecting processes run during compilation makes it seem like `/MP` is operating normally: CL starts up a work server and children processes to handle the compilations.

Is the combination of `/sourceDependencies-` (+etc) and `/MP` supported? Is there any detrimental behavior to be aware of here? (Worse performance, possible garbled output, etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8697ff9c-9a88-50ff-9b23-a85cdbee123a
* Version Independent ID: be639a51-dc95-429f-ad7c-141c0717340c
* Content: [/sourceDependencies (Report source-level dependencies)](https://docs.microsoft.com/en-us/cpp/build/reference/sourcedependencies?view=msvc-170)
* Content Source: [docs/build/reference/sourcedependencies.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/sourcedependencies.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@shuffle2 
Thanks for the report. As described in all three articles, we recommend the directory argument whenever you also use `/MP`. While we don't call it out explicitly, based on the recommendation you might expect potential interleaving issues with output to `stdout`. However, you shouldn't see a file contention build error. Given the appearance of non-standard JSON output, I'd say it's really a possible issue for the dev team, and potentially an intractable one, given the way `/MP` works. I'd recommend you raise the question on [Developer Community](https://developercommunity.visualstudio.com/search?space=62) if you want to pursue it further.

**Comment by shuffle2** [comment]
> While we don't call it out explicitly, based on the recommendation you might expect potential interleaving issues with output to stdout

While I suspected this, it would certainly be nice if it's not the case :) I'll file on dev community, thanks.

**Comment by corob-msft** [comment]
@shuffle2 
While the developers mull your issue, I've clarified the language to describe the existing behavior in the `stdout` case. Thanks for the input.
