### ISSUE TITLE
/sourceDependencies (+ etc) behavior with directory mode unclear

### ISSUE THREAD

**Issue by shuffle2** [MicrosoftDocs/cpp-docs#3909]
`/sourceDependencies`, `/scanDependencies`, `/sourceDependencies:directives` all can output to a directory, but the documentation about how to use that is slightly wrong.

First off, https://docs.microsoft.com/en-us/cpp/build/reference/sourcedependencies-directives?view=msvc-170 and https://docs.microsoft.com/en-us/cpp/build/reference/scandependencies?view=msvc-170 show the syntax as `<cmd> directory\` whereas the trailing slash is not required.

Instead (and this behavior should be listed on all 3 pages), the compiler checks the given argument **exists and is a directory** (in other words, the directory must be pre-created before running the compiler) in order to enable "directory output mode". If the path does not exist or is a file, "file output mode" is used.

`directory\` (with the trailing slash) is confusing because if the path does not exist OR is an existing file instead of a directory, you get the same error: `fatal error C1083: Cannot open compiler generated file: 'directory\': Invalid argument`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8697ff9c-9a88-50ff-9b23-a85cdbee123a
* Version Independent ID: be639a51-dc95-429f-ad7c-141c0717340c
* Content: [/sourceDependencies (Report source-level dependencies)](https://docs.microsoft.com/en-us/cpp/build/reference/sourcedependencies?view=msvc-170)
* Content Source: [docs/build/reference/sourcedependencies.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/sourcedependencies.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@shuffle2 
Thanks for the report. There was a typo in the formatting for the syntax sections that unfortunately left a trailing `\` visible in these articles. I've fixed it so it shouldn't show up anymore. I've also clarified the language around the directory and filename behavior to indicate the directory must exist.
