### ISSUE TITLE
lost in translation

### ISSUE THREAD

**Issue by mecpp** [MicrosoftDocs/cpp-docs#3910]
Hi,

just in case you are able to forward this to the translation engine provider:
The term '(not) shareable' is set to mysterious 'beharrbar/anharrbar' in German translation. I've no idea on what base it translates the part 'share' to the obscure 'harr'. There is only this unique search result on Google and Bing for these words.

regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19df9b55-9ae6-9c08-b8e4-28518eaeb3bd
* Version Independent ID: c5941a32-c208-1b0a-c2be-6050cafcb33b
* Content: [_fsopen, _wfsopen](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fsopen-wfsopen?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/fsopen-wfsopen.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-runtime-library/reference/fsopen-wfsopen.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
This appears to be an issue on the German [`fopen_s`, `_wfopen_s`](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-170) article, rather than the one listed as content source.

**Comment by TylerMSFT** [comment]
@mecpp, thank you for raising this issue. I've forwarded it to our machine translation folks to take a look at.

**Comment by TylerMSFT** [comment]
@mecpp, our machine translation people will look at it, but it is unlikely to be fixed unless they determine it to be a high priority/urgent issue.
In the meantime, my colleague fixed the text so that it should translate better. That should be live by Monday, 5/23/2022
