### ISSUE TITLE
The article doesn't mention wWinMain

### ISSUE THREAD

**Issue by vefatica** [MicrosoftDocs/cpp-docs#3916]
[Enter feedback here]

The article doesn't mention wWinMain which is apparently necessary if __wargv is to be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0faa41c6-6098-ff61-9913-befee1a426ee
* Version Independent ID: a5c568cd-a78b-9fdf-2d57-0a9d5aa5c7a1
* Content: [__argc, __argv, __wargv](https://docs.microsoft.com/en-us/cpp/c-runtime-library/argc-argv-wargv?view=msvc-170)
* Content Source: [docs/c-runtime-library/argc-argv-wargv.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-runtime-library/argc-argv-wargv.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by lb90** [comment]
Hello! Looks like one may use [__wgetmainargs](https://learn.microsoft.com/en-us/cpp/c-runtime-library/getmainargs-wgetmainargs). However it would be nice if the documentation mentioned under what conditions exported global variables are initialized and can then be used safely. Alternatively, have functional versions that return the variables while taking care of thread-safe one-time initialization

**Comment by lb90** [comment]
Uh, actually it seems that `__wgetmainargs` is neither declard in UCRT headers (version 10.0.22000.0), neither exported from `ucrtbase.dll` (Windows 10 22H2)...

I see there is a `extern "C" errno_t _configure_wide_environment(_crt_argv_mode const mode)`, but is it safe for a library to call it? What happens if it's called multiple times?

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.

Also, for this issue, you may try [Microsoft Q&a](https://github.com/MicrosoftDocs/cpp-docs/assets/12305055/c81b5e03-dadc-4bac-b45b-2c9185544b04)
