### ISSUE TITLE
VS 2022 is `17.2.1` does not prompt at all to enable CMake functionality.

### ISSUE THREAD

**Issue by khteh** [MicrosoftDocs/cpp-docs#3917]
```
Starting in Visual Studio 2022 version 17.1 Preview 2, if your folder doesn't contain a root CMakeLists.txt you'll be prompted whether you'd like to enable CMake integration or not. For more information, see [CMake partial activation](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170#cmake-partial-activation).
```
That's not true at all. My VS 2022 is `17.2.1` and there is no prompt at all.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170#cmake-partial-activation)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This looks like a question for @sfreed141.

**Comment by sfreed141** [comment]
@khteh I am no longer on the CMake team, but my guess is your folder has a root CMakeLists.txt. If that's not the case then please provide more details (project structure, what you expect to see, etc). If you think this is a bug please file it on Developer Community (either directly on the website or through the Send Feedback button in Visual Studio).

@bobbrow fyi for any follow up, I'm unassigning myself from this

**Comment by khteh** [comment]
No `CMakeLists.txt` at all in the project structure. Trying to convert from my existing C++ solution to CMake so that I can run it too on Ubuntu.

**Comment by bobbrow** [comment]
@khteh The prompt does not happen if there are no CMakeLists.txt at all in your folder hierarchy.  I'm proposing to change the documentation to say: "if your top-level `CMakeLists.txt` exists in a subfolder and not at the root of the workspace" that the prompt will appear.

(I'm open to wording suggestions too if someone has a better idea)

**Comment by corob-msft** [comment]
@bobbrow Thanks for the update; I found the original language confusing, too.
@khteh It looks like this feature isn't a one-button solution to turn your code into a CMake project. I'm sorry we got your hopes up. With Bob's fix, I think we've clarified what Visual Studio actually does, so I'm closing the issue.
