### ISSUE TITLE
Improper heading level. Should be h2

### ISSUE THREAD

**Issue by Lemmingh** [MicrosoftDocs/cpp-docs#3918]
<https://github.com/MicrosoftDocs/cpp-docs/blob/03553b56d96d62b2e122b2bb0142e841bd150819/docs/cpp/welcome-back-to-cpp-modern-cpp.md#L145>

The heading "Uniform initialization" is currently h3, causing weird nesting and breaking TOC. Judging from the context, it should be h2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [Welcome back to C++ - Modern C++](https://docs.microsoft.com/en-us/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=msvc-170#resources-and-smart-pointers)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Lemmingh Thanks for the report. An update is now published.
