### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by GuidoSE** [MicrosoftDocs/cpp-docs#3919]
Useless as it does not explain properly how to fix the error, this page only shows the error, no help at all
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acaebf3a-9f03-a00d-d986-f79fa8998dd7
* Version Independent ID: dbb3d460-3ab5-46c1-9ec2-daef79dbec5c
* Content: [Compiler Warning (level 1) C4273](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4273?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4273)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4273.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4273.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@GuidoSE 
To fix the issue, delete the declaration that caused the error. That's explained in the comments in the first sample. In some cases, you may want to delete the first declaration instead, but if the first declaration is in a header file, you almost always want to delete the declaration where the warning is reported.

**Comment by GuidoSE** [comment]
Thank you for your reply however it does not help as the error is too generic. My issue is with a definition and declaration in C within a C++ DLL. If I delete the definition in the header, pointless as no code to write. If I delete the declaration then no code, nothing actually does anything. 

The comments compile with /W1 /clr /c mean little but could be traced to actually compiler settings after searching but it does not even touch on the solution to the problem.

**Comment by corob-msft** [comment]
@GuidoSE 
Warning C4273 occurs because the compiler found a symbol (a variable or function) that has two different, incompatible declarations. You can *declare* a symbol as often as you like, but the declarations all have to match. You can only *define* a symbol once, and the signature of the definition has to match the declaration, if there's a separate one. If you define the symbol inline in a header file, then including the header file is all you need to do to use the symbol; you don't have to declare it again. This should cover all the cases where warning C4273 can occur.

**Comment by corob-msft** [comment]
@GuidoSE 
Reading your reply a little more closely, there are some rules regarding `extern "C"` or `extern "C++"` that can affect declarations in a way that could cause C4273. It's possible to call C++ functions with decorated names from C code, but you have to capture the decorated name. It's much easier to declare a C++ function as `extern "C"`, wrapped in a preprocessor macro, if you want to call it from C code. The [Export C functions for use in C or C++ language executables](../../build/exporting-c-functions-for-use-in-c-or-cpp-language-executables.md) article has more details.

**Comment by corob-msft** [comment]
Published a fix for clarification.
