### ISSUE TITLE
Excessive ; in the code samples

### ISSUE THREAD

**Issue by TheCalligrapher** [MicrosoftDocs/cpp-docs#3921]
Code samples are formally correct but look unprofessional. Why is each closing '}' in class method's definition followed by a ';'? This is neither grammatically necessary nor a popular stylistic convention. This is usually seen in newbie-level code when people mistakenly believe that that ';' should be there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 293a9ef1-7673-6e92-bf9c-db3920488af0
* Version Independent ID: a70288f2-2829-bd04-3da1-e0a53d58e703
* Content: [C26495](https://docs.microsoft.com/en-us/cpp/code-quality/c26495?view=msvc-170)
* Content Source: [docs/code-quality/c26495.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c26495.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheCalligrapher Thanks for the report. A fix has been published.
