### ISSUE TITLE
RunCodeAnalysis for programmatic compiler option to enable /analyze

### ISSUE THREAD

**Issue by weikanglim** [MicrosoftDocs/cpp-docs#3926]
Based on some internal feedback from the C++ Static Analysis Team, I believe that the recommendation is to use `RunCodeAnalysis` over `EnablePREFast` as the programmatic MSBuild option. `EnablePREFast` will end up enabling `/analyze`, but does not enable the full set of static code analysis completely.

Would recommend replacing the section if my understanding is correct. At minimum, the programmatic option behavior should mirror the behavior of the Visual Studio developer environment option (which does end up setting `RunCodeAnalysis`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09296a0d-dea6-bcf6-7370-5ec2cf061835
* Version Independent ID: b6de3061-2d20-4508-6a76-663a2d61d098
* Content: [/analyze (Code analysis)](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?redirectedfrom=MSDN&view=msvc-170)
* Content Source: [docs/build/reference/analyze-code-analysis.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/analyze-code-analysis.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@weikanglim 
It appears that `RunCodeAnalysis` is undocumented, at least as part of the [`VCCLCompilerTool Interface`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.vcclcompilertool?view=visualstudiosdk-2022). The only exposed versions I see in the VSSDK come from the C#, J#, and VB libraries.

@sunnychatterjee Do you have any input here for the right interface to invoke?

**Comment by corob-msft** [comment]
@weikanglim 
As I look at the question again, I wonder if there's some confusion about what the **To set this compiler option programmatically** section is referring to. It's a pointer to the approximately equivalent .NET VS SDK method for Visual Studio extension writers. If you're looking for information on how to access the MSBuild properties set by the UI, you can find them in the Property Pages XML files, which on my system are found in "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\1033\" with these particular properties set in "code_analysis.xml". The "Enable Code Analysis on Build" property does in fact set a boolean property named `RunCodeAnalysis`. However, that's unrelated to why we mention `EnablePREfast` in the document.

MSBuild properties aren't in scope for the compiler options docs. We've seen requests to add them, but we don't have the resources in writer time to go through and add that information in preference to our other priorities. I'm closing this issue, as it's not something we plan to address. Thanks for understanding.
