### ISSUE TITLE
having issue with an error can anyone help?

### ISSUE THREAD

**Issue by Vanqious24** [MicrosoftDocs/cpp-docs#3929]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 153ebd5e-bb50-ab31-687f-6bc20a87548e
* Version Independent ID: f3bb7428-1c24-47aa-732b-9b935bed836d
* Content: [Fatal Error C1047](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1047?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1047)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1047.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/fatal-error-c1047.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Vanqious24 
I'm sorry you're having trouble. Unfortunately, the issues board here is intended to tell us about documentation problems, not for general programming support, so I'm closing this one. Support issues can be raised on [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck with your coding.
