### ISSUE TITLE
TN058 and cross-dll singletons

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#394]
It is time to update this article. Clearly C++ MFC  has proved its worth and is now begrudgingly been given top-shelf precedence by the likes of C++ ISO standard people like Herb Sutter and by implementing MFC on ARM64 May 11th, 2018. This was all predictable by a good architect.

TN058 needs some attention though. Over the years MFC pundits have categorically warned against using same-process global variables in different DLLs. But what if your project architecturally needs and protects an object singleton as is the case in my project? This article does not address that, and I wish it would. Please consider an update. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a509de5-c1a1-6a8a-db5d-8aa48cbb6994
* Version Independent ID: 51778cfa-fe57-614d-4f8a-6011e07f3370
* Content: [TN058: MFC Module State Implementation](https://docs.microsoft.com/en-us/cpp/mfc/tn058-mfc-module-state-implementation)
* Content Source: [docs/mfc/tn058-mfc-module-state-implementation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/tn058-mfc-module-state-implementation.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by rtischer8277** [comment]
@mikeblome C++ does not, nor will it have, any concept of processes and it wasn't before C++11 that threads came about. The DLL is therefore still far ahead in its ability to reference count its existence regardless of whether it is instantiated in a new process or multiple times within the same process. But MFC's TN058 article only addresses difficulties in the past in accessing global variables. Today's C++ has self-destroying smart pointers potentially making any cross-process object safely usable. Cross-process COM has never worked well because its architecture only dealt with binaries and the marshalling of same. Today's C++ not only generates source code on the fly (templates), but guarantees object safety (smart pointers) regardless of its context (thread or process). Given this, MS ought to see MFC as a strength and update its classes and articles like TN058 to reflect these developments. 

But MFC is in serious need of updating. Although Jeff Prosise long ago correctly described MFC's message maps as a more efficient virtual constructor implementation, they are implemented as macros. Macros are on their way out of the C++ language. MFC could be written much more cleanly today by using modern C++17 constructs. For example, in my apps I routinely pass std::tuple data across threads without leaks using std::unique_ptr and variadic templates. This kind of modern C++ code improvement ought to be added to the MFC infrastructure so developers don't have to do it themselves.

Whereas, as Bjarne Stroustrup created C++ as C with classes, MFC is C++ with processes. If Microsoft really wants to develop tools for Any Developer, Any App, Any Platform, then it needs to rescue MFC from cultural bias before it squanders its lead. The advent of ARM64 MFC is testimony that at least some of MS architects have gotten it right.

But there is a bug in MFC that involves cross-DLL access and objects, the stuff of TN058. I have posted it on the Visual Studio Developer Community under the title, "Handler never reached from PostThreadMessage" in mainframe exe". I have also written and posted sample code that illustrates the problem along with attached screen shots.

**Comment by mikeblome** [comment]
Thanks for the clarification. I have forwarded this to the MFC experts. The developercommunity site is the proper place to raise the issue, and I see you do have the attention of Microsoft people on that thread. If you have a specific idea for how to improve this topic, you are welcome to make a pull request by clicking the Edit button on the page.
