### ISSUE TITLE
Warnings and Errors need workaround or suggested fixes

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/cpp-docs#3942]
Getting into the documentation for warnings or errors that the compiler provides and finding that the documentation only states the obvious is not contributing to help the community completely. In this case, there is no much documentation arounod C++/WinRT on Internet and trying to figure out how to fix this warning is not easy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d15a4392-1017-fa73-b344-5f93ebbfa401
* Version Independent ID: 488ea8a7-51c5-f594-4c86-19ca3a271d8e
* Content: [C26811](https://docs.microsoft.com/en-us/cpp/code-quality/c26811?view=msvc-170)
* Content Source: [docs/code-quality/c26811.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c26811.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @sunnychatterjee
* Microsoft Alias: **sunnych**

**Comment by corob-msft** [comment]
@sunnychatterjee 
Sunny, do you have anything to add to [the example in question](https://docs.microsoft.com/en-us/cpp/code-quality/c26811?view=msvc-170), other than "don't do that"? The example doesn't follow our usual pattern of suggesting a solution. How would someone create an independent coroutine parameter that could satisfy the C26811 lifetime check?

**Comment by Xazax-hun** [comment]
The documentation has been updated to give more guidance on how to fix the warning.

**Comment by corob-msft** [comment]
Thank you, @Xazax-hun !
Closing as resolved.
