### ISSUE TITLE
Generic functions in C++/CLI -- the formal syntax description seems to be incorrect

### ISSUE THREAD

**Issue by alex-ht-work** [MicrosoftDocs/cpp-docs#3943]
The formal syntax description for a generic function in C++/CLI does not mention the `generic` keyword at all, and looks more like C# syntax. The examples though clearly show the use of `generic` keyword to declare generic functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1672a28a-eb80-5a3d-f046-f6b0b964a7fd
* Version Independent ID: 1b3046ee-b63b-a59f-9ef1-58f894e4d319
* Content: [Generic Functions (C++/CLI)](https://docs.microsoft.com/en-us/cpp/extensions/generic-functions-cpp-cli?view=msvc-170)
* Content Source: [docs/extensions/generic-functions-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/extensions/generic-functions-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@alex-ht-work 
Thanks for the report. I'm not really sure what this kind of syntax section is trying to do. It leaves out or handwaves away many of the possibilities, and in this case, left out entirely what makes a function generic. This change makes the syntax section more like the C and C++ language syntax sections, but now it's inconsistent with most other C++/CLI syntax sections. Someday someone may reconcile those sections.
