### ISSUE TITLE
Warning being triggered for cases unrelated to referenced C++ Core Guideline

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/cpp-docs#3949]
The referenced guideline advises against:
```C++
void f(int n)
{
    auto p = new Gadget{n};
    // ...
    delete p;
}
```
Because it can simply be achieved by:
```C++
void f(int n)
{
    Gadget g{n};
    // ...
}
```
Yet the warning is being triggered by the following (the example in the doc):
```C++
void unpack_and_send(const frame &f)
{
    auto buffer = std::make_unique<char[]>(f.size()); // C26414
    f.unpack(buffer.get());
    // ...
}
```
This makes no sense, because applying the guideline here means doing something the language doesn't support:
```C++
void unpack_and_send(const frame &f)
{
    char buffer[f.size()];
    f.unpack(buffer);
    // ...
}
```
Furthermore, if the example is meant to trigger C26414, why doesn't the following (which is even closer to the guideline's example) trigger it?
```C++
void unpack_and_send(const frame &f)
{
    auto buffer = new char[f.size()];
    f.unpack(buffer.get());
    // ...
}
```
The above instead triggers **[C26409](https://docs.microsoft.com/en-us/cpp/code-quality/c26409) which explicitly advises using `std::make_unique` for dynamic array allocation.** But if we do that, we get C26414. It's like a bad joke.

When all that's required is an array whose size is known only during runtime, a dynamically allocated array is the most appropriate and `std::make_unique` is simply used as a convenient means to delete the array automatically. The recommended solution of using `std::vector` is not appropriate because not only is it like using a sledgehammer on a thumbtack, it gives the false impression that the code would be changing the array's size - why else would it use a vector instead of a simple dynamic array?

I think this warning should make an exception for the use of `std::make_unique` with dynamic arrays just like it did for `new`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b46dcf5-a093-93d6-d5d6-e7abdacbbb99
* Version Independent ID: f963e84d-05f9-9ddc-7766-50a4578f4f38
* Content: [C26414](https://docs.microsoft.com/en-us/cpp/code-quality/c26414?view=msvc-170)
* Content Source: [docs/code-quality/c26414.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c26414.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wmjdgla 
Thanks for the comments. This could either be read either as a bug report or a suggestion for a product behavior change. As it's not really something we can address with a documentation change, I'm closing it. It's no reflection on the merits of your idea. Just a recommendation that you post it where it will get the attention it deserves. To put the idea in front of the analysis team, I recommend you make your case on [Developer Community](https://aka.ms/vsfeedback/browsecpp). Best of luck.
