### ISSUE TITLE
Examples are incorrect regarding arrays

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/cpp-docs#3952]
The examples imply the following code:
```cpp
data = new int[size];
```

is equivalent to the code below:
```
data = std::make_unique<int>(size);
```

However, the two are _not_ the same: the first example creates a pointer to an array of `int`'s whose capacity is `size`, while the second creates a pointer to an `int` whose value is `size`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4941a280-af7a-9fec-7dc0-cc5001735666
* Version Independent ID: 951f54c6-6ba0-6025-d34c-84a1024bd6bb
* Content: [Object lifetime and resource management (RAII)](https://docs.microsoft.com/en-us/cpp/cpp/object-lifetime-and-resource-management-modern-cpp?view=msvc-160)
* Content Source: [docs/cpp/object-lifetime-and-resource-management-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/object-lifetime-and-resource-management-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by FrankAtHexagon** [comment]
Which I now see you've also corrected, great work! 👏🏻

**Comment by corob-msft** [comment]
@FrankAtHexagon 
Thanks for the report, and yes, we do try to fix all instances of a class of reported issues when we can. That works out much better than waiting for them all to get reported individually.

**Comment by FrankAtHexagon** [comment]
I think that's a great strategy, if only more organizations were willing to follow it. 😅
