### ISSUE TITLE
Confusion over heap allocation

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/cpp-docs#3954]
In the _Value types and move efficiency_ section, the following is stated:
> Move is an optimization of copy. There is need for heap allocation as a workaround.

I can't figure out what is trying to be communicated here, should it actually say "There is _no_ need..."?

The example code shown below doesn't make things any clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc3b506-0cfd-07f1-6938-68f8aa3ac97e
* Version Independent ID: 15974f68-6a19-8641-9b34-a617a01b5032
* Content: [C++ classes as value types](https://docs.microsoft.com/en-us/cpp/cpp/value-types-modern-cpp?view=msvc-160)
* Content Source: [docs/cpp/value-types-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/value-types-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@FrankAtHexagon 
Thanks for the report. I've updated the relevant article, and the changes are now visible.
