### ISSUE TITLE
Provide a sample Open from Exsiting Code option

### ISSUE THREAD

**Issue by jecalderon** [MicrosoftDocs/cpp-docs#396]
[Apply a sample code environment that benefits from the Open from Existing Code option. One example is to create a OpenCV project from another existing code.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3925d061-52dd-b10e-50f8-a408292d7278
* Version Independent ID: 99a1184b-b28e-4d89-e4ff-b57240494ff0
* Content: [How to: Create a C++ Project from Existing Code](https://docs.microsoft.com/en-us/cpp/ide/how-to-create-a-cpp-project-from-existing-code)
* Content Source: [docs/ide/how-to-create-a-cpp-project-from-existing-code.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/how-to-create-a-cpp-project-from-existing-code.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@jecalderon I agree we could use an example here. I have added it to our backlog.

**Comment by mikeblome** [comment]
Closing because the issue is tracked on our backlog and will be prioritized against other work.
