### ISSUE TITLE
Documentation for `_M_ARM` is unclear

### ISSUE THREAD

**Issue by aaronfranke** [MicrosoftDocs/cpp-docs#3960]
https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/predefined-macros.md

> * `_M_ARM` Defined as the integer literal value 7 for compilations that target ARM processors. Otherwise, undefined.

It's unclear if `_M_ARM` is defined on 32-bit ARM, 64-bit ARM, or both. The documentation needs to be updated.

Also, would it be possible for MSVC to add `_M_ARM32`, like how there's already `_M_ARM64`?

**Comment by corob-msft** [comment]
I've clarified the documentation in Predefined Macros, which should be visible tomorrow.
