### ISSUE TITLE
_BitScanReverse incorrectly documents effects

### ISSUE THREAD

**Issue by rindlespot** [MicrosoftDocs/cpp-docs#3961]
While the docs say the return value is *Nonzero if Index was set*, Index is ALWAYS set, no matter the return value.  If the mask is 0, index is set to zero too.  

However, since this is apparently based on the [x86 BSR instruction](https://www.felixcloutier.com/x86/bsr), perhaps it would be more accurate to say:

> If the content of the source operand is 0, the content of the destination operand is undefined.

It's annoyingly useless since 'undefined' means you can't *depend* on it being zero (or "not being set"), but more accurate.  Wouldn't want some new processor to come out where they change the behavior (which they never guaranteed) and have people get annoyed about broken promises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a483f515-06b4-cfed-e8ac-4c72e9f59ed0
* Version Independent ID: 9837d168-817f-f86e-0c44-a9035bd90827
* Content: [_BitScanReverse, _BitScanReverse64](https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanreverse-bitscanreverse64?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(INTRIN0.INL%252F_BitScanReverse64)%3Bk(_BitScanReverse64)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/intrinsics/bitscanreverse-bitscanreverse64.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/intrinsics/bitscanreverse-bitscanreverse64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rindlespot 
Thanks for the feedback and your patience. The intrinsics are based on the `BSR` instruction on Intel, but it's a little more complex on ARM/ARM64. It's true that `*index` is set unconditionally, and the Intel docs say the value is undefined when the source (`mask`) is zero. Based on some fiddling with Compiler Explorer, it looks like `*index` is explicitly set on ARM64 as well and will have an unsigned value equivalent to -1 if `mask` is 0, but I don't know ARM assembly well enough to be certain. A fix to the docs should appear when we publish next, which is probably next week sometime after the holiday.
