### ISSUE TITLE
The linker can embed the manifest since vs2012

### ISSUE THREAD

**Issue by dlaugt** [MicrosoftDocs/cpp-docs#3972]
The following line is not correct anymore:
_The linker does not embed the manifest file inside the binary, and can only generate the manifest as an external file._

Since vs2012, the linker can embed a manifest with the option /MANIFEST:EMBED.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19fc05a-4a89-75a5-aec4-681c8c4db974
* Version Independent ID: f37e4381-34f5-7079-0939-bfe7c6db2ce3
* Content: [Understanding Manifest Generation for C/C++ Programs](https://docs.microsoft.com/en-us/cpp/build/understanding-manifest-generation-for-c-cpp-programs?view=msvc-170)
* Content Source: [docs/build/understanding-manifest-generation-for-c-cpp-programs.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/understanding-manifest-generation-for-c-cpp-programs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dlaugt 
Thanks for the report. I've updated the content here and elsewhere to reflect the current linker capabilities, and these changes are now visible on the site.
