### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by PitFroehlich** [MicrosoftDocs/cpp-docs#3974]
Hey there, I just read the doc about Function Overloading in German. The first paragraph seemed kind of weird to me, so I switched to English. Actually the translation there is wrong. It is not just the usual grammar or wording caused by machine translation but there is also some information that is wrong. 

For example:

"Beispielsweise kann eine print Funktion, die ein Argument verwendet, sehr unterschiedliche Aufgaben ausführen als eine, die ein std::string Argument vom Typ doubleverwendet."

This means a print function can perform different tasks with std::string arguments of the type double. 

Correct would be: 

"Beispielsweise kann eine print Funktion, welche ein Argument vom Typ std:string verwendet, andere Aufgaben ausführen als eine Funktion welche ein Argument vom Typ double verwendet."

Kind regards, Pit 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105d147e-9d10-7820-c326-39e00945d9cc
* Version Independent ID: 6c24ebf1-014c-a004-fd50-a390b0ab42a1
* Content: [Function Overloading](https://docs.microsoft.com/en-us/cpp/cpp/function-overloading?view=msvc-170)
* Content Source: [docs/cpp/function-overloading.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/function-overloading.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by brunolewin-msft** [comment]
Thanks for the feedback @PitFroehlich. Note that the localization team is working on a better way of addressing these type of problem than individual GitHub issues! 

FYI @JasonCard

**Comment by corob-msft** [comment]
@PitFroehlich 

The problem of poor localizations belongs to our localization team, but they don't have a direct feedback channel, and they aren't staffed to handle individual issues from readers. I made an update to the English content to simplify the grammar, so it would be easier for machine translation to parse. The change appears to have improved the German translation, at least as far as I can tell with my *sehr schlechte Deutschkenntnisse*. Thanks for helping us improve the docs for everyone.

**Comment by PitFroehlich** [comment]
@corob-msft thank you for the reply! I read the article again and the sentence is better but just one sentence later there is another issue. I changed one word so it may have a better translation. Maybe it is a bit much to try to correct them all by hand.
