### ISSUE TITLE
Usdc testing

### ISSUE THREAD

**Issue by Princeprince559** [MicrosoftDocs/cpp-docs#3980]
{Use this template to request **new** documentation to cover a feature area in the ISO C++17 standard library. Replace this text in curly braces with a description of the feature area to cover. Include a link to the proposal paper that introduced the issue (for example, `[N4086 Removing Trigraphs??!](https://wg21.link/n4086)`), or cite the chapter and section number or \[short.name] in the C++ standard that describes the feature. Add the Visual Studio version that first implements this feature. If you don't know or don't have these values, then this issue template probably isn't the right one to use.

If documentation already exists on docs.microsoft.com for this feature area, and you're requesting an update, bug fix, or clarification, don't use this template. Go to the article on docs.microsoft.com and use the **This page** button in the **Feedback** section at the bottom of the document to create a GitHub issue. Include a citation for the ISO standard feature area in your description.}

ISO paper or location in the standard for this feature: {insert link or section here}
First implemented in: {VS 20YY major.minor}

**Comment by corob-msft** [comment]
@Princeprince559 This doesn't appear to be a docs issue.
