### ISSUE TITLE
Confusing use of the term Animation

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#3982]
> Animation controls can play only simple AVI clips

The example code pointed to on this doc page supports the notion of animation simply being the playing an avi file clip. 

But there is another notion of animation regarding controls. That notion is a control that moves or rotates resembling certain physical laws. The **CAccelerateDecelerateTransition** class supports that notion. Fx, one could apply CAccelerateDecelerateTransition to a slider control. Or another kind of motion like Decelerate only. I think this page should at the very very least make a distinction between these two types of animation: playing a file clip and control transition.

How about adding an adjective to discern between the two? That would be _control animation_ and _clip animation_. Then you could begin his page with a Note that explains.

If anyone agrees with my assessment, I would be glad to put in a doc change to that effect. Although, I think at this point it is better for MS to decide where the breakdown is really occurring.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e40d24-8005-739b-be5b-0cd219890ab3
* Version Independent ID: e57c25e3-2365-7b24-960a-0e4207af3c40
* Content: [CAnimateCtrl Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/canimatectrl-class?view=msvc-170)
* Content Source: [docs/mfc/reference/canimatectrl-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/canimatectrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@rtischer8277, feel free to propose the doc change you suggest. It will be some time before I can get to this if I do it.

**Comment by rtischer8277** [comment]
Will do right after I finish implementing a .avi clip vs ctrl transition with the current MFC library. This, in order to verify what I am proposing.

**Comment by TylerMSFT** [comment]
Unfortunately, due to doc resources and priorities, closing.
