### ISSUE TITLE
AFX_DIALOG_LAYOUT needs better explanation

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#3983]
I happen to know that AFX_DIALOG_LAYOUT is a section in the resource script (.rc) file. But the reader would not necessarily know that from this page. AFX_DIALOG_LAYOUT should be a link to some .rc page description. That description should minimally describe how, fx, Ribbon Designer creates such a section. Fx, I don't know what resource creates such a section but I know it looks like this:
```
/////////////////////////////////////////////////////////////////////////////
//
// AFX_DIALOG_LAYOUT
//

IDD_BACKSTAGE_DIALOG AFX_DIALOG_LAYOUT
BEGIN
    0
END
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1344cab-19ce-6364-ca20-ee7a8a677b32
* Version Independent ID: 5ff6c1de-fc18-50d3-8e84-a5a8ea9a1d08
* Content: [CMFCDynamicLayout Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfcdynamiclayout-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cmfcdynamiclayout-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/cmfcdynamiclayout-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
