### ISSUE TITLE
Unclear explanation on memory allocation and cleanup behavior

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/cpp-docs#3985]
## Issue 1
> C++ objects are allocated in the application's heap and HWNDs are allocated in system resources by the window manager.

This seems to imply that in this context, C++ objects are always allocated on the heap. But then it goes on to say:
> ... for window objects that are allocated on the **stack** frame ...
> The following classes aren't designed for auto-cleanup. They're typically embedded in other C++ objects or on the **stack**: ...

## Issue 2
> Classes designed for allocation alone on the heap override the `PostNcDestroy` method to perform a `delete this;`. This statement will free any memory associated with the C++ object. Even though the default `CWnd` destructor calls `DestroyWindow` if `m_hWnd` isn't `NULL`, this call doesn't lead to infinite recursion because the handle will be detached and `NULL` during the cleanup phase.

It is unclear how the recursion will occur. The documentation for `CWnd::DestroyWindow` states that it'll generate a `WM_NCDESTROY` message. So if my understanding is correct, the recursion could occur via `PostNcDestroy` > `delete this` > `~CWnd()` > `DestroyWindow` > `WM_NCDESTROY` > `PostNcDestroy`. I think this should be explained in the article to make things clearer.

In addition, it does not explain how detaching the handle prevents the recursion. Does detaching the handle mean that the object will not receive the `WM_NCDESTROY` message generated by `DestroyWindow`, and thus prevents the recursive `PostNcDestroy` call?

## Issue 3
The article only considers 2 cases - classes that are always allocated on the stack and classes that are always allocated on the heap. But what about classes that are allocated on the stack in some cases and on the heap in others? How should memory cleanup be handled then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea407a3c-2efe-4da6-ae0c-34ac276b904c
* Version Independent ID: 2680ee4a-0a0b-dec2-9609-999c7898282f
* Content: [TN017: Destroying window objects](https://docs.microsoft.com/en-us/cpp/mfc/tn017-destroying-window-objects?view=msvc-170)
* Content Source: [docs/mfc/tn017-destroying-window-objects.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/tn017-destroying-window-objects.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@wmjdgla, It'll be a little while until I can dig into this, but in broad strokes, developers generally don't allocate large objects on the stack, particularly if the function is recursive, because that's a limited resource. It's nice that the destructor will be automatically called when the function goes out of scope for objects on the stack, but you have to make a decision about whether having it on the stack is how you want to use that memory, or whether it makes more sense to have it in the larger heap area. 
But that's just a high-level view. I need to look more carefully at what the discussion is in this topic to see what nuance needs to be called out.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
