### ISSUE TITLE
Is there any way to specify commands to be executed without  specify  generator

### ISSUE THREAD

**Issue by Frankenstein-bit** [MicrosoftDocs/cpp-docs#3986]
[Enter feedback here]
I do remote linux development via VS, I don't specify a generator, I use my own compile commands. In this case, I found that the command in remotePreGenerateCommand is not executed. Is there any way to specify commands to be executed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4cb5d3-4f66-32e8-8b74-522738eb5215
* Version Independent ID: ae7afcc9-5c5e-6dc5-cd6a-9b1aa25ac149
* Content: [CMake predefined configuration reference](https://docs.microsoft.com/en-us/cpp/build/cmake-predefined-configuration-reference?view=msvc-170)
* Content Source: [docs/build/cmake-predefined-configuration-reference.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/cmake-predefined-configuration-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Frankenstein-bit 
I don't know. This might be a good question for [Developer Community](https://aka.ms/vsfeedback/browsecpp).

@sinemakinci1 Do you have any insights to add here?

**Comment by corob-msft** [comment]
@bobbrow Any info to share here?

**Comment by paulmaybee** [comment]
I'm afraid I don't quite understand how you are configuring your project. Can you provide a small example to demonstrate what you are trying to do?

**Comment by corob-msft** [comment]
Given a month without feedback, and a consensus that this isn't a supported scenario, I'm closing the issue.
