### ISSUE TITLE
Mixed mode debugging for cmake projects

### ISSUE THREAD

**Issue by einaren** [MicrosoftDocs/cpp-docs#399]
Is there a way to enable mixed mode debugging (C++/Python) for CMake projects? 

Similar to what is described here for .sln projects: https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by rchiodo** [comment]
Sorry but not from CMake integration.
The way to do this would be to open the built executable as a project in a separate instance of Visual Studio. From there you can force it to pick a specific debugger.

**Comment by einaren** [comment]
Ok, thanks! At least it is good to know I can stop trying to make it work :-)

**Comment by einaren** [comment]
If anyone wants this feature, please vote here: 

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/35226301-enable-mixed-mode-debugging-in-cmake-openfolder-pr

**Comment by MatthieuHernandez** [comment]
Any news about this feature?
