### ISSUE TITLE
Inconsistencies in Class member overview

### ISSUE THREAD

**Issue by haferburg** [MicrosoftDocs/cpp-docs#3990]
This link here
![image](https://user-images.githubusercontent.com/4941909/174251623-6a86ed19-478e-461d-aa4b-4e25ac13da46.png)
is labeled "Data members" but only points to static data members.

---
And here is an incomplete sentence:
![image](https://user-images.githubusercontent.com/4941909/174251843-e87709bc-28b6-4fb3-9d8e-95c26f4f8354.png)
Is there a link missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb1bd2-96b4-fe9d-b884-cf176b8fec5a
* Version Independent ID: d5f3930c-0d83-5faf-ece9-a14fcaa416ca
* Content: [Class member overview](https://docs.microsoft.com/en-us/cpp/cpp/class-member-overview?view=msvc-170)
* Content Source: [docs/cpp/class-member-overview.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/class-member-overview.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@haferburg 
Thanks for the report; a fix should be visible now.
