### ISSUE TITLE
Android OpenGLES native example not threadsafe?

### ISSUE THREAD

**Issue by mdmcgrath** [MicrosoftDocs/cpp-docs#3994]
The sample code, provided by Visual Studio 2019, 2022, does not appear to implement methods to call OpenGLES on the OpenGLES thread created when the surface is created.  Instead, it calls its rendering APIs on the UI thread, which is inherently unsafe, and unsuitable for anything but the simplest tasks, which may conveniently dodge threading issues.

All that should be needed, to remedy this issue, should be to implement callbacks for the nativeRedrawWindow and nativeResizeWindow mechanisms in the native glue, and properly comment them, to note that all GLES calls must be made inside those function scopes, along with the create and destroy windiw scopes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1fa38-809e-5525-1241-d2dca23c705d
* Version Independent ID: a3b2385f-5cf3-7ac6-ebce-d71dc39c83d9
* Content: [Build an OpenGL ES application on Android and iOS](https://docs.microsoft.com/en-us/cpp/cross-platform/build-an-opengl-es-application-on-android-and-ios?view=msvc-170)
* Content Source: [docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mdmcgrath 
Thanks for the report. It took me some time to install the relevant software to determine that you were referring to the template-generated code. I believe, given the copyright notices reproduced in the source files, that the code in question is actually quoted from the NDK samples available at the time the template was created. At any rate, the Visual Studio templates are not part of the documentation team's content. We can't address the product issue you've raised here, so I'm closing it. To bring your issue to the attention of the development team, you should make your suggestion on [Developer Community](https://aka.ms/vsfeedback/browsecpp), where it will be seen by the people who can do something about it. Best of luck!
