### ISSUE TITLE
x64 intrinsic table shouldn't try to track which cpus implement which instructions

### ISSUE THREAD

**Issue by shuffle2** [MicrosoftDocs/cpp-docs#4000]
> Use the [__cpuid](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-170) intrinsic to determine instruction-set support at run time.

This is correct

> A [1] indicates the intrinsic is available only on AMD processors. A [2] indicates the intrinsic is available only on Intel processors.

That is not correct.

As each feature set depends on the specific architecture of the cpu (as opposed to just the manufacturer), the [1] and [2] markings become out of date and incorrect relatively quickly, and generally aren't helpful (the manufacturer could remove support for a previously-present intrinsic, for example, or only support it in server CPUs, etc...). IMO those markings should just be removed from the table. For example, currently many of the things marked intel-only have actually been available on AMD cpus for some years (like ADX, BMI, AVX, AESNI, CLMUL ...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49106a1-0948-39a6-199a-4318567a3e6e
* Version Independent ID: 576b1498-7b28-9b1d-1954-78705b6ac1ee
* Content: [x64 (amd64) intrinsics list](https://docs.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list?view=msvc-170)
* Content Source: [docs/intrinsics/x64-amd64-intrinsics-list.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/intrinsics/x64-amd64-intrinsics-list.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shuffle2 

The annotations are in fact redundant. You can see they correspond to the header file specified. The `immintrin.h` and `ammintrin.h` files (and the feature set-specific headers they in turn include) are, respectively, maintained by Intel and AMD engineers working with the Microsoft C++ compiler development team. The intrinsics themselves aren't necessarily manufacturer-specific, but the noted headers are. I'll look into clarifying that.
