### ISSUE TITLE
Makefile equivalent of Linker/Input Application (.exe)

### ISSUE THREAD

**Issue by GameGameNoGG** [MicrosoftDocs/cpp-docs#4008]
I am tring to write a C++ project (.exe) with my DLL using nmake. But from the [document](https://docs.microsoft.com/en-us/cpp/build/reference/sample-makefile?view=msvc-170),  it's hard to find similar  options like Add additional dependency and Input in Visual  Studio.

**Comment by corob-msft** [comment]
@GameGameNoGG 
I'm sorry it's giving you trouble. I'm not sure I understand the issue. The properties you set in Visual Studio generally correspond to command-line options for the compiler or linker. You can add dependencies to your makefile just by listing them after whatever file requires that dependency:

```makefile
example.lib: part1.obj part2.obj
  $(link) $(ldebug) $(conflags) /DLL /OUT:example.dll /IMPLIB:example.lib part1.obj part2.obj $(conlibs)

my_app.exe: my_app.obj example.lib
  $(link) $(ldebug) $(conflags) /OUT:myapp.exe $my_app.obj $(conlibs) example.lib
```

The `example.lib` rule also builds the DLL `example.dll` that you need as a runtime dependency.

We're not currently planning to expand the NMAKE documentation. Your best resource for questions like this one is either the support forums available in [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or an external resource such as [StackOverflow](https://stackoverflow.com/questions/tagged/c%2b%2b%20visual-studio). I wish you well in your coding endeavors.

**Comment by GameGameNoGG** [comment]
Thank you for your reply.
