### ISSUE TITLE
Missing /arch information for ARM64

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#4011]
ARM64 matters... For one, choosing the architecture results in different implementations of atomic operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66875a44-174b-6ce4-732c-8159146e44de
* Version Independent ID: 83dd8c4d-7df7-5200-1b99-c17f13cb6ce8
* Content: [/arch (Minimum CPU Architecture)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-minimum-cpu-architecture?view=msvc-170)
* Content Source: [docs/build/reference/arch-minimum-cpu-architecture.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/arch-minimum-cpu-architecture.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheJCAB 
Thanks for the report. Until Visual Studio 2022 version 17.2, there weren't any ARM64-specific **`/arch`** options. There is one now that lets you specify a higher minimum processor architecture requirement. I've added an article for this option to the docs. While I haven't seen any intrinsics mentioned as requiring the higher architecture level, it wouldn't surprise me if such exist.
