### ISSUE TITLE
Unsupported modification of Executable Directories property for Clang custom installation needs to be updated in the documentation

### ISSUE THREAD

**Issue by lisbecg** [MicrosoftDocs/cpp-docs#4014]
The last paragraph of this [section](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#configure-a-windows-project-to-use-clang-tools) should be changed since we do not offer support to modify the Executable Directories property for LLVM. 

[Current paragraph]
If you're using a custom Clang installation, you can either modify Project > Properties > VC++ Directories > Configuration Properties > Executable Directories by adding the custom Clang installation root as the first directory there, or change the value of the LLVMInstallDir property. For more information, see [Set a custom LLVM location](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_location).

[Recommended update]
If you're using a custom Clang installation, you can change the value of the LLVMInstallDir property. For more information, see [Set a custom LLVM location](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_location).

Please reach out if you have any questions or concerns.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cabdd4-5ef1-1c19-4a82-5448a5901e8a
* Version Independent ID: 56fd7d96-62ec-07df-40df-aaf155d504d3
* Content: [Clang/LLVM support in Visual Studio projects](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_location)
* Content Source: [docs/build/clang-support-msbuild.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/clang-support-msbuild.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@lisbecg Thanks for the update. It should be visible in content now.
