### ISSUE TITLE
@Anthonysidesapps  http://www.w3.org/2005/Atom

### ISSUE THREAD

**Issue by Anthonysidesappss** [MicrosoftDocs/cpp-docs#4016]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d8f4cb9-2629-1ea5-86b1-f74df9c5e86b
* Version Independent ID: f320eb63-0320-769e-498c-b4dc008ce1ce
* Content: [Namespaces (C++)](https://docs.microsoft.com/en-us/cpp/cpp/namespaces-cpp?view=msvc-170)
* Content Source: [docs/cpp/namespaces-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cpp/namespaces-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing, as this doesn't appear to be an actionable defect report.
@Anthonysidesappss, if you have an issue with the content on the page in question, could you elaborate on it for us? Thanks for taking the time to make the docs better.
