### ISSUE TITLE
Typographical Error in Table of Operators

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/cpp-docs#4033]
The name of the less-than-and-equal-to operator includes an incorrect '\\' (single backslash).  It should be "_operator<=_" vice "_operator\\<=_".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3671a82-d813-9202-63cc-e72bfd21a55e
* Version Independent ID: 88ccf649-32ec-9683-e33b-561fefde432d
* Content: [&lt;vector&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/vector?view=msvc-170)
* Content Source: [docs/standard-library/vector.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/standard-library/vector.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@JustaSimpleUser , thank you for pointing that out. I've fixed it. It should be live by Monday.
Appreciate you helping us improve the quality of the docs.
