### ISSUE TITLE
Obsolete....

### ISSUE THREAD

**Issue by dcorbin-wintellect** [MicrosoftDocs/cpp-docs#4036]
NOTE: This page WAS edited in 2021....

Under the section "Compile with Visual C++" it states one should compile with Visual Studio 2010....

This is a severe problem, as I currently am using 2022 and the oldest version I have is 2019.....  

Do I have to set up a VM with the 12 year old version???

David
[Former Visual Studio MVP and ALM Ranger]

ps: Have a great day, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202280ec-5cf8-31d5-2d38-1a60a9035ff5
* Version Independent ID: 733c8347-4f2d-1d20-5968-48541aeecb7f
* Content: [How to: Migrate to -clr](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-migrate-to-clr?view=msvc-170)
* Content Source: [docs/dotnet/how-to-migrate-to-clr.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/dotnet/how-to-migrate-to-clr.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This topic appears to have been updated. I don't see the reference to 2010 anymore.
