### ISSUE TITLE
Compiler Warning (level 4) C4127 documentation clarification

### ISSUE THREAD

**Issue by stringarray** [MicrosoftDocs/cpp-docs#404]
The documentation for Compiler Warning (level 4) C4127 says that "Because of their common idiomatic usage, trivial constants such as 1 or true do not trigger the warning". But I find that:
`while (true) { break; }`
triggers the warning. Can you clarify, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88a50e7-ed43-5fe5-e3f7-7e243af2e290
* Version Independent ID: 7ed7dfe9-7959-4e04-30d0-1c39e33af8e8
* Content: [Compiler Warning (level 4) C4127](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4127)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by stringarray** [comment]
Note: Visual Studio 2013 emits the warning, Visual Studio 2017 does not. Maybe you can point this out somewhere, adding more info about this change.

**Comment by corob-msft** [comment]
Hi, @stringarray - A check of my email archive tells me the behavior was changed in or a little before VS 2015 Update 3. We weren't as conscientious about noting when changes occurred mid-version at the time. While it appears the text was updated, the sample was never touched at all, and clearly it's now wrong. I'll stick a task on my backlog to update it and note when the behavior changed.

**Comment by corob-msft** [comment]
Should be up-to-date now.
