### ISSUE TITLE
memset() document should mention whether a NULL target is supported.

### ISSUE THREAD

**Issue by PhilDavidson-Ivory** [MicrosoftDocs/cpp-docs#4043]
Please mention whether dest may be NULL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0534e0f-1550-6652-e1da-74c1a766b3f0
* Version Independent ID: 87d4edc0-d837-6b83-c63d-1d7c49d6ff0a
* Content: [memset, wmemset](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/memset-wmemset?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/memset-wmemset.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-runtime-library/reference/memset-wmemset.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
It can't. It'll throw. 

Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
