### ISSUE TITLE
What are guards for switch statements?

### ISSUE THREAD

**Issue by H0w1** [MicrosoftDocs/cpp-docs#4047]
Hi there.  I am a PhD student in software security and I am very interested in CFI. CFG is great. Thanks for your work. 

I have some questions about the guards for switch statements.

> Visual Studio 2017 and later: This option adds guards for switch statements that generate jump tables.

Could you tell me what are such guards? I searched for this on the Internet but found nothing about this. And I did some experiments with Visual Studio 2022 but found the compiler just generated the same code for switch statements with or without CFG.

Thanks so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b43bfa2-be10-6d04-3fc6-21cb40e3587d
* Version Independent ID: 9d6ae01a-aced-5e97-07f3-73b8203a1fa1
* Content: [/guard (Enable Control Flow Guard)](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-170)
* Content Source: [docs/build/reference/guard-enable-control-flow-guard.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/reference/guard-enable-control-flow-guard.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@H0w1 

Expanding on the [Control Flow Guard](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard) docs, when a switch statement creates a jump table, those jump source and destination addresses get added to the control flow FID tables in the PE header. The source and target tables are generated and stored independently as part of the image header, so there's not much difference in the generated code other than an added compiler intrinsic call to an internal check routine. If you don't see the intrinsic call near the jump, then it may fall in the category of a statically identifiable target, which doesn't get a check for the sake of performance. Or so I understand. If you have further questions, the proper forum is in [Developer Community](https://aka.ms/vsfeedback/browsecpp) where the actual experts will see them. Best of luck with your studies.
