### ISSUE TITLE
cwchar

### ISSUE THREAD

**Issue by fernandoammmmmm** [MicrosoftDocs/cpp-docs#4050]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e441cf-541f-f1ca-d680-6107c36aa980
* Version Independent ID: 3c1c9355-ccdb-2d7b-d25f-03590211988e
* Content: [&lt;cwchar&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/cwchar?view=msvc-170)
* Content Source: [docs/standard-library/cwchar.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/standard-library/cwchar.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@fernandoammmmmm 
There doesn't seem to be an actionable issue here, so I'm closing it. If you'd like to explain the issue you found with the `cwchar` documentation, we can reopen the issue.
