### ISSUE TITLE
Improve description of CMutex

### ISSUE THREAD

**Issue by IceBreaker80** [MicrosoftDocs/cpp-docs#4051]
Description of class could be more detailed:

- Required lifetime for pointers used in constructor of CMutex. Do they have to persist over the lifetime of CMutex object or are they copied as part of constructor call?
- Exception safety of constructor call.
- Destructor behavior: is "Unlock()" called automatically as part of destruction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e222033-5c08-6c74-5a4b-b19b71eb4835
* Version Independent ID: b904fc9c-e945-9771-2a93-8786f037c2e4
* Content: [CMutex Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmutex-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cmutex-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/cmutex-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
