### ISSUE TITLE
This doesn't help...

### ISSUE THREAD

**Issue by AgoraIOT** [MicrosoftDocs/cpp-docs#4054]
Did everything this said to do, and I have the same issue.  Also, one should clarify that "some other properties may need to be set" (something like that).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0476b0-bd59-b76c-b7ea-4483160b7948
* Version Independent ID: 52e614c4-4033-f14f-c438-0445b397688e
* Content: [Fatal Error C1107](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1107?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1107.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/fatal-error-c1107.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AgoraIOT 
Sorry it's giving you trouble. The phrase "you must set certain properties to build your project" should read "you must set the following properties to build your project", in case you assumed that the phrasing implied other, unnamed properties.
In cases where simple edits to project properties aren't sufficient to create a working build, I recommend you create a new version of the project file in VS 2022 from a template, then add the existing source files, verifying that the build succeeds as you go. Source changes may also be needed to use the updated frameworks.

**Comment by AgoraIOT** [comment]
It actually does imply other unnamed properties.  For example /EHc, /Zc:twoPhase- (there is no explanation for that anywhere in Visual Studio, btw), and two others (I think).  

It is easy enough to test... just turn on /clr and VS will start complaining about incompatible flags which you'll spend a good 30 minutes to an hour trying to find and set using the Project Setup.

I tried to just get a "Hello World" to run using essentially Console.Writeline via our SDK which provides a Logging feature... this is the code:

int main()
{
    Log.Write("Hello World");
}

After I modified everything that Visual Studio complained about in terms of compatibility issues, the linker can't find mscorlib using either LIBPATH or AI - spent another two hours trying to figure out why that did not work - no solution.

**Comment by corob-msft** [comment]
@AgoraIOT 

Perhaps I misunderstood your scenario. Were you retargeting an older C++/CLI project to VS 2022? Or were you trying to turn a project that was originally a native or console app into a C++/CLI app? The changes required are different, and the C1107 article only describes the first case. We don't expect an error article to cover the second scenario. It would wind up recapitulating a lot of content from the [.NET programming with C++/CLI](https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=msvc-170) documentation.

The changes recommended for `/clr` in [How to: Convert between various string types](https://docs.microsoft.com/en-us/cpp/text/how-to-convert-between-various-string-types?view=msvc-170#run-the-examples) may apply. [The `/EHc` flag is redundant under `/clr`](https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170#exception-handling-under-clr), which implies `/EHa`. [`/Zc:twoPhase-`](https://docs.microsoft.com/en-us/cpp/build/reference/zc-twophase?view=msvc-170) is normally only required by old code that relies on Microsoft's previous preprocessor behavior. As far as I know, it isn't implied by `/clr` except in some library code that may use a `static_assert` (causing error C2338) to require it. 

The location of mscorlib.dll depends on the version of .NET you target. When I create a simple CLR Console App from a template, for example, the External Dependencies folder in Solution Explorer lists the full path to mscorlib.dll as "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll". The component is installed by the Visual Studio Installer, just in case your Visual Studio 2022 installation is missing the .NET library component.

This has turned into a support case, and we can't do more. For further questions, I recommend [Developer Community](https://aka.ms/vsfeedback/browsecpp). Best of luck with your code.
