### ISSUE TITLE
All your docs don't tell me a header file

### ISSUE THREAD

**Issue by rlewkowicz** [MicrosoftDocs/cpp-docs#4056]
I think this is afxwin.h, but that's not said anywhere. For those of us that have not been doing this for 20 years, something as simple as how to include this falls through the cracks. 

Imo opencv docs are the c++ gold standard for docs based on what I've seen so far. It defines all the classes and what header files contain them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f567a739-943e-c85d-07a1-d43229fa6d4e
* Version Independent ID: c41ddd0d-df30-7ac0-407b-d7a9c9a18478
* Content: [CWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cwnd-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/cwnd-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@rlewkowicz 
Ah, good, you found it. You'll find the required header files for all MFC classes listed in a **Requirements** section in the class documentation. If it's missing, that's a doc bug that we'll address. Since in this instance, it's present, I'm closing the issue.
