### ISSUE TITLE
Please include which sample that illustrates use of CMFCEditBrowserCtrl

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#4064]
It is too difficult to search through all the examples in order to find a specific example using the CMFCEditBRowserCtrl. Just tell the docs reader what it is up front.

> CMFCEditBrowseCtrl class: EnableFolderBrowseButton and EnableFileBrowseButton. This example is part of the [New Controls sample](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-samples?view=msvc-170).

Simple say, "This example can be found in the *insert-project-name* of the [New Controls sample](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-samples?view=msvc-170).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8daef0b6-ff4f-0e8b-3317-d70061dfb364
* Version Independent ID: 3afe406e-2182-ea0a-0622-4596f56754f6
* Content: [CMFCEditBrowseCtrl Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfceditbrowsectrl-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cmfceditbrowsectrl-class.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/cmfceditbrowsectrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
