### ISSUE TITLE
Walkthrough: Using the New MFC Shell Controls

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#4066]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42d62b6-ccf2-e5e6-fb25-25100c70fe38
* Version Independent ID: 51ede8ba-a8b3-0868-bee1-e2635309afb6
* Content: [Walkthrough: Using the New MFC Shell Controls](https://docs.microsoft.com/en-us/cpp/mfc/walkthrough-using-the-new-mfc-shell-controls?view=msvc-170)
* Content Source: [docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
Closing, as I assume this was an attempt to create what became issue #4067.
