### ISSUE TITLE
Walkthrough: Using the New MFC Shell Controls.

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#4067]
This following instruction is incorrect, or it did not work for me when I implemented it:

Copied from the Page: Because we're calling methods from the CMainFrame class, we must add an #include directive at the top of the MFCShellControlsView.cpp source file.

The above instruction produced an extensive list of errors. But when I listed #include "MainFrm.h" in the include file of the WALKTHROUGH instead, it worked! I was relieved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42d62b6-ccf2-e5e6-fb25-25100c70fe38
* Version Independent ID: 51ede8ba-a8b3-0868-bee1-e2635309afb6
* Content: [Walkthrough: Using the New MFC Shell Controls](https://docs.microsoft.com/en-us/cpp/mfc/walkthrough-using-the-new-mfc-shell-controls?view=msvc-170)
* Content Source: [docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/walkthrough-using-the-new-mfc-shell-controls.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@makelyblakley , thank you for bringing this to our attention. I have added it to the backlog to address.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
