### ISSUE TITLE
C2254.com

### ISSUE THREAD

**Issue by Huynhnhuoi9** [MicrosoftDocs/cpp-docs#4068]
[Nhập phản hồi vào đây]

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: b0e73442-a481-a3c2-9d35-b7233a342ac0
* Version Independent ID: ac0a97ff-0ee0-420e-201f-af2e27547aaf
* Content: [Compiler Error C2254](https://docs.microsoft.com/vi-vn/cpp/error-messages/compiler-errors-1/compiler-error-c2254?view=msvc-140)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2254.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/compiler-error-c2254.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Huynhnhuoi9 
I'm sorry, I'm closing this issue because there isn't a description of a documentation problem. If you've found a problem in the C2254 documentation, please add a description in a comment here, and we will reopen it.
