### ISSUE TITLE
Compiler Error C2250 - Unable to resolve error if a Covariant return type is used

### ISSUE THREAD

**Issue by Atijaf** [MicrosoftDocs/cpp-docs#4074]
The solution to resolve Compiler Error C2250 does not solve the issue if a covariant return type is used.

```
class A{
protected:
    virtual A* Get() = 0;
};

class B : public virtual A {
protected:
    B* Get() override {
        return this;
    }
};

class C : public virtual A {
protected:
    C* Get() override {
        return this;
    }
};

class D : public B, public C{
protected:
    D* Get() override{
        return this;
    }
    //Compiler Error C2250 ambiguous inheritance of 'B *A::Get(void)'
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04c46f2-21e2-0354-b5c8-b27844e885dd
* Version Independent ID: b3da2ed1-d64d-5e80-0a8e-080651ff0493
* Content: [Compiler Error C2250](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2250?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2250.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/compiler-error-c2250.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Atijaf 
Thanks for the report. This behavior is unexpected. Neither gcc nor clang report an issue with the code sample, so you may have discovered a compiler bug. I recommend you report it either [from the IDE](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170), or directly to [Developer Community](https://aka.ms/vsfeedback/browsecpp). If you add a link to your bug report here, we can track it and update the docs if required. Thanks!

**Comment by Atijaf** [comment]
@corob-msft
I appreciate the recommendation.  I've created the bug report [here](https://developercommunity.visualstudio.com/t/Compiler-Error-C2250---Unable-to-resolve/10109726?entry=myfeedback)
