### ISSUE TITLE
Example Code Incorrect - Create a module unit implementation file Section

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/cpp-docs#4082]
The text in the 7th para of the _**Create a module unit implementation file**_ section states:

_The line module BasicPlane.Figures; identifies this file as part of the named module BasicPlane.Figures._

However, there is no such line in the most recent code fragment.  Instead there is:

`module BasicPlane.Figures:Rectangle;`

As a consequence, the supplied code does not compile since the Rectangles struct is not visible.  Removing the ":Rectangle" partition from the module declaration resolves the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Version Independent ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Content: [Named modules tutorial in C++](https://docs.microsoft.com/en-us/cpp/cpp/tutorial-named-modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/tutorial-named-modules-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/tutorial-named-modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JustaSimpleUser 

I'm sorry the code is giving you trouble. I'm not seeing the same issue. Can you elaborate on the compiler error you see in the tutorial code as written?

When I build the tutorial code, I don't get a compiler error; the code runs as expected. The IntelliSense compiler does report E0020 issues, but they don't affect the build; I expect the EDG compiler isn't quite up to date and can safely be ignored here.

Thanks for getting back to me.

**Comment by JustaSimpleUser** [comment]
My bad.  You're absolutely correct, the code does, in fact, compile and run.  I, too, get the E0020 I guess I was relying on IntelliSense to predict those errors.

Two issues remain, however:

1. As first mentioned, the text in the paragraph doesn't reflect the example code; and,
2. IntelliSense is screwing up (again).  And, rhetorically, why does removing ":Rectangle" solve the E0020 error?

Anyway, thanks for paying attention to this.

**Comment by corob-msft** [comment]
@JustaSimpleUser 
Thanks for reporting the issue. An update to the text to clarify some UI interactions and fix the statement you described is in publishing now and should be visible within a day. As for why the change you made worked, it's just expanding the scope of the implementation file to the entire module. That's fine in this case, because it's the only one.
