### ISSUE TITLE
Substitution of a wrong image

### ISSUE THREAD

**Issue by Eschivo** [MicrosoftDocs/cpp-docs#4084]
In the guide [Walkthrough: Import STL libraries as header units](https://github.com/MicrosoftDocs/cpp-docs/blob/32eeb8e357a1984d2346fb80e37d05ead25b0446/docs/build/walkthrough-import-stl-header-units.md) the second image in the section "Set project options and run the project" of the second approach is wrong since it repeats the previous one. In particular, I'm referring to this:

https://github.com/MicrosoftDocs/cpp-docs/blob/32eeb8e357a1984d2346fb80e37d05ead25b0446/docs/build/walkthrough-import-stl-header-units.md?plain=1#L204

That repeats the previously shown image:

https://github.com/MicrosoftDocs/cpp-docs/blob/32eeb8e357a1984d2346fb80e37d05ead25b0446/docs/build/walkthrough-import-stl-header-units.md?plain=1#L198

Instead, the last image (the first referred here) should show how to set the C++ 20 standard in the General Configuration properties. 

I maybe can file a PR with the right image but it seems that those files are handled locally and not through this repo.

**Comment by TylerMSFT** [comment]
This image has been fixed.
