### ISSUE TITLE
Specify instructions/extensions used for each /arch option

### ISSUE THREAD

**Issue by fpelliccioni** [MicrosoftDocs/cpp-docs#4088]
According to the documentation:

> Each /arch option may also enable the use of other non-vector instructions that are associated with that option. An example is the use of certain BMI instructions when /arch:AVX2 is specified.

This has been given as an example but I think it is necessary to specify what instructions/extensions will be used by the compiler for each of the `/arch` flag options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732983a0-a628-77d4-a224-0db096ade499
* Version Independent ID: e7aae128-bb82-c6b5-3389-2f4470d66d11
* Content: [/arch (x64)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170)
* Content Source: [docs/build/reference/arch-x64.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/arch-x64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fpelliccioni 
Thanks for the input. The best information available is that instruction set extensions from prior to the introduction of each **`/arch`** option are included in that option. For a definition of "prior", you'll have to consult the historical record of [Intel](https://www.intel.com/content/www/us/en/support/articles/000005779/processors.html) and [AMD](https://www.amd.com/system/files/TechDocs/24594.pdf) instruction set introductions. For information on whether to execute code created for a particular instruction set in your app, use the `__cpuid` intrinsic. We don't plan to enumerate the specific instruction support available here, but we appreciate the idea.

**Comment by fpelliccioni** [comment]
Ok, at least you can use your text as a "specification".
