### ISSUE TITLE
spelling in (Sub-)title?

### ISSUE THREAD

**Issue by dhoke4tdb** [MicrosoftDocs/cpp-docs#4089]
Un?itialized iterators ==> unINitialized iterators ? (or has a new word entered the language, quite possible Im out of touch)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c200cd0a-85db-45ed-8e50-2a5f563d3156
* Version Independent ID: d43ff7d9-9c13-7eb3-88e6-c0221a5e8a80
* Content: [Debug Iterator Support](https://docs.microsoft.com/en-us/cpp/standard-library/debug-iterator-support?view=msvc-170)
* Content Source: [docs/standard-library/debug-iterator-support.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/debug-iterator-support.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks, @dhoke4tdb. Fixed. How embarrassing :-) The fix will be live Monday.
