### ISSUE TITLE
InstallShield not supported in VS 2017

### ISSUE THREAD

**Issue by RonFredericks** [MicrosoftDocs/cpp-docs#409]
This article is for an older version of Visual Studio. InstallShield is not available for VS 2017 for example. In general it would be nice for authors to include which version of VS they are discussing in every article published on this site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be979440-bf90-6756-304c-883363a10073
* Version Independent ID: 4aea40e0-a221-acf0-2421-0ad5194fe03e
* Content: [Walkthrough: Deploying Your Program (C++)](https://docs.microsoft.com/en-us/cpp/ide/walkthrough-deploying-your-program-cpp?view=vs-2017)
* Content Source: [docs/ide/walkthrough-deploying-your-program-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/walkthrough-deploying-your-program-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Thanks @RonFredericks we are updating these topics and they should be visible within a few days. I'll leave this open until they appear.

**Comment by mikeblome** [comment]
fixed
