### ISSUE TITLE
NO Entry Point for Kernel Drivers

### ISSUE THREAD

**Issue by Mike191919** [MicrosoftDocs/cpp-docs#4091]
There is no entry point for kernel drivers. How can I get rid of this nasty pseudo error message LNK1561???
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361ad94f-165c-a218-a436-0046f7b23416
* Version Independent ID: 95aef15e-dd24-cc35-934a-e10c81d8e154
* Content: [/ENTRY (Entry-Point Symbol)](https://docs.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol?view=msvc-170)
* Content Source: [docs/build/reference/entry-entry-point-symbol.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/entry-entry-point-symbol.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Mike191919 
Sorry you're having trouble. This is a support question, not a documentation question. You shouldn't need to use the **`/ENTRY`** option on a kernel driver. If the linker reports LNK1561 on a kernel driver project then there's something wrong with the way your project is set up. Did you start with an app or DLL project template and edit it to create a driver project? I'd recommend you recreate the project as a kernel driver project and copy the code over. Best of luck with your code.
