### ISSUE TITLE
Title needs correction since STL refers to Standard Template Library, not C++ Standard Library

### ISSUE THREAD

**Issue by tohtorizorro** [MicrosoftDocs/cpp-docs#4092]
According to Wikipedia, STL stands for Standard Template Library designed by Alexander Stepanov which influenced many parts of the C++ Standard Library. Thus, it seems the title of the page really should be corrected.

I'm aware that wikipedia isn't really the proper authority on this but I can't dive in the actual C++ standard
right now, so I urge You to do it.

https://en.wikipedia.org/wiki/Standard_Template_Library
https://en.wikipedia.org/wiki/C%2B%2B_Standard_Library

all the best!
Mikko Rintala

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [C runtime (CRT) and C++ Standard Library .lib files](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks, @tohtorizorro. This fix should be visible Monday.

**Comment by TylerMSFT** [comment]
This isn't as straightforward as I thought. When I resolve this, I'll write about why.

**Comment by tohtorizorro** [comment]
No probs whatsoever, this isn't really super important to me but as a beginner with C++ I'm all confused all the time even when everything checks out and thought this might be somerhing that might leave someone else baffled so it should be better straightened out. And it's kinda cool to spot a typo etc. and think afterwarfs that thanks to ME the internet is now just a bit better :)
I'm also a somewhat intrigued now to eventually know about your hardships on the matter.

**Comment by TylerMSFT** [comment]
@tohtorizorro , you ARE making the internet a little bit better :-) Thank you for taking the time to comment on our docs. Whether I've made it a little worse with how I've dealt with the issue you raised remains to be seen :-)

This is a long-standing naming issue in the C++ community. The historical origin is that Alexander Stepanov created a library called the Standard Template Library (STL) that became popular. In fact, parts of it were adapted and standardized as *part* of what is officially called the C++ Standard Library. To make it even more confusing, some people use the term "STL" to refer to just the containers and algorithms parts of the C++ Standard Library. You can search the internet for wonderful debates about the wisdom of this naming.

I'm not taking a side in the debate, but do need to ensure that customers can find our docs when they do an internet search. I've written a small bit about our naming convention and added it to this topic and to one other that introduces our docs for the standard library.

Thank you for opening this issue. It was fun to revisit this history and how previous writers of our docs have dealt with it.

My updates will be live by tomorrow afternoon (8/16, Tues, PST)
