### ISSUE TITLE
Two members of the MFC class CMDIFrameWndEx are misspelled in the documentation

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/cpp-docs#4096]
A member function of the MFC class `CMDIFrameWndEx` and its associated member variable are misspelled in the documentation.
Their correct names (per header files and linked libraries) are:
```
CanConvertControlBarToMDIChild();
m_bCanConvertControlBarToMDIChild;
```
But in several places in the docs, they are missing the n in _Convert_,
rendering them _Covert_ (in more ways than one):
```
CanCovertControlBarToMDIChild();
m_bCanCovertControlBarToMDIChild;
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b54896e-732a-6832-ba4b-99236452b2cf
* Version Independent ID: 446ba2dd-8fe2-cad8-dc7f-b65f37e0352c
* Content: [CMDIFrameWndEx Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmdiframewndex-class?view=msvc-160)
* Content Source: [docs/mfc/reference/cmdiframewndex-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/cmdiframewndex-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@ChristopherBenson, thank you for pointing this out. That's a weird one. Seems like perhaps a search-and-replace went bad at some point.
Fixed. The updates should go live by Wed.
