### ISSUE TITLE
Missing parameters in Smart Lock table

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/cpp-docs#4097]
Shouldn't the `_Analysis_assume_smart_lock_acquired_` and `_Analysis_assume_smart_lock_released_` annotations in the table be followed by an `(expr)` parameter? The description text for each says "This annotation expects a reference lock type as its parameter," but the parameter is not shown in the table for either.

It would also be nice to see usage examples, or at least get an explanation of why the other annotations are insufficient for RAII. There seems to be nothing else on the web about these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 931f6d06-0989-bd7f-8309-226f6b1c9963
* Version Independent ID: df8d1904-3c4b-1b88-d8bb-fb999b13e7a2
* Content: [Annotating Locking Behavior](https://docs.microsoft.com/en-us/cpp/code-quality/annotating-locking-behavior?view=msvc-170)
* Content Source: [docs/code-quality/annotating-locking-behavior.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/annotating-locking-behavior.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@druske 
I added the missing lock parameters to the table. I don't know enough about these SAL annotations to make good examples, but I believe they're meant to assert that you know the locks are used correctly, even if it's not obvious to the code analysis engine.
