### ISSUE TITLE
typo in "func(1)->GetValue()++  " example

### ISSUE THREAD

**Issue by bboysil** [MicrosoftDocs/cpp-docs#410]
The C++ example code is "func(1)-&gt;GetValue()++" but in the explanation it says "...func(1)-&gt;GetData is a postfix expression specifying a member of the class, func(1)-&gt;GetData() is another function postfix expression,..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b27ebf-1ef8-7d0f-3e72-eb11f7219788
* Version Independent ID: 2eb3a736-b19f-dd14-f3fc-95b2c6059e28
* Content: [Postfix Expressions](https://docs.microsoft.com/en-us/cpp/cpp/postfix-expressions?view=vs-2017)
* Content Source: [docs/cpp/postfix-expressions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/postfix-expressions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@bboysil thanks! Fixed and should be visible by 09-05.
