### ISSUE TITLE
Incorrect default value?

### ISSUE THREAD

**Issue by AA11BB22** [MicrosoftDocs/cpp-docs#4102]
> By default, **/sdl** is off.

This doesn't seem to be the case for C++ projects (at least on Empty and Console project templates).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16261866-311b-cb4e-4e9f-9412e3d93e3c
* Version Independent ID: f8bbc8e5-67d3-38ba-fd52-ad1e86364f11
* Content: [/sdl (Enable Additional Security Checks)](https://docs.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-170#feedback)
* Content Source: [docs/build/reference/sdl-enable-additional-security-checks.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/sdl-enable-additional-security-checks.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AA11BB22 
There's no inconsistency here. These documents cover the compiler command-line options, and the default compiler option if otherwise unspecified is **`/sdl-`**. However, there's nothing that stops a template from setting a different value for this option. In the IDE, if the **SDL checks** property value is in bold, then it's been set by the template.

**Comment by AA11BB22** [comment]
There **is** an inconsistency. Shouldn't those non-conforming templates be fixed then, i.e., follow MSVC default value? Or place a remark mentioning that some templates don't conform/override the default value.

**Comment by corob-msft** [comment]
@AA11BB22 
I can see the appeal of adding a remark, if that was all it took. However, there are a lot of templates, and each one might set dozens of options, each of which may differ based on the version of Visual Studio in use, the project type and configuration, the target architecture, or whether a build is debug or release. That's a recipe for a giant multi-column table in every compiler option article that would need constant maintenance as templates change. Instead, we list the compiler command-line default for each option, if there is one, and rely on readers to look at the property pages for their projects to discover and set the option values they actually use. The whole point of templates is to set the specific, non-default options and properties needed for a particular project type, so you don't have to dig through the options and set them all yourself. Templates also usually set the options for building the safest, most conforming code, at a warning level that catches most errors without being excessively noisy. **`/sdl`** is a good example of a safety option. The command-line compiler. on the other hand, defaults to the minimum warning level, some minimal conformance enforcement, and a basic level of code safety. It's a complex tool for people willing to spend the effort to understand its settings so they can set the options exactly the way they want them. The IDE and the templates take away a lot of that effort and make the compiler a lot easier to use. They get things set up nicely with minimal esoteric knowledge required.

**Comment by AA11BB22** [comment]
Yes, I see your point (on documenting every template may not be possible) and I do agree that the "default" should be the safest option...

However, /sdl treats a few warnings as errors, namely C4996 which treats `[[deprecated]]` as an error (not just a warning).

It isn't very obvious that /sdl was the culprit, personally, I dug through the more common ones like treat specific/all warnings as errors options but none of them were enabled ... eventually found out that /sdl was the cause somehow.

Any other idea/suggestion that can improve this poor experience?

**Comment by corob-msft** [comment]
@AA11BB22 
I thought about the experience you had and figured that the place you'd go looking for answers when a warning was treated as an error would be the warning article. So, I've added a sentence to the eight or so warnings that are turned into errors by `/sdl` with a statement to that effect. Then at least you have an indication of what you're looking for in your build settings.
