### ISSUE TITLE
_setjump3() argument type in 64-bit Windows?

### ISSUE THREAD

**Issue by PerMildner** [MicrosoftDocs/cpp-docs#4115]
The documentation says

> The first `DWORD` is a function pointer

However, on 64-bit Windows a function pointer is 64-bit, which does not fit in a `DWORD` (which is always 32-bit). Should it say `DWORD_PTR`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc2d69e9-b911-5eef-06a6-3212d01942a6
* Version Independent ID: c3325f30-ebed-5481-cb16-705a8c777361
* Content: [_setjmp3](https://docs.microsoft.com/en-us/cpp/c-runtime-library/setjmp3?view=msvc-170)
* Content Source: [docs/c-runtime-library/setjmp3.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/setjmp3.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@PerMildner 
Interesting question, but not a correct surmise. `_setjmp3` is an internal implementation detail of `setjmp` that's only available on the x86 platform. There is no x64 version, so parameter width isn't an issue. We document `_setjmp3` for people who are stepping through code in the debugger and wonder what that symbol means. It's not meant to be called directly by user code.
