### ISSUE TITLE
Status of inline keyword support in C

### ISSUE THREAD

**Issue by shuffle2** [MicrosoftDocs/cpp-docs#4117]
The page has the text:
`The inline keyword is available only in C++. The __inline and __forceinline keywords are available in both C and C++.`

However, the compiler appears to accept `inline` as a keyword when compiling C (not C++) code, as well.

Is `inline` supported (with standard semantics, assuming `/std:c11` / `/std:c17` are used)? It would be nice to state that in the documentation if so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09138391-a316-0222-7db1-3cd461316773
* Version Independent ID: 2cd32c3f-d4c0-69b5-d09c-f8a2638f79e0
* Content: [Inline Functions (C++)](https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-170)
* Content Source: [docs/cpp/inline-functions-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/inline-functions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shuffle2 
GitHub ate my comment, the upshot of which was that, yes, the doc is out of date, and **`inline`** is supported in C in all modes since at least VS 2015.

**Comment by corob-msft** [comment]
Updates to the C++ article and the equivalent C language documentation for [Inline functions](https://docs.microsoft.com/en-us/cpp/c-language/inline-functions?view=msvc-170) are now available.
