### ISSUE TITLE
/arch lists incorrect values for arm64

### ISSUE THREAD

**Issue by shuffle2** [MicrosoftDocs/cpp-docs#4119]
The blog: https://devblogs.microsoft.com/cppblog/msvc-backend-updates-in-visual-studio-2022-version-17-2/

mentions `/arch:armv8.0` and `/arch:armv8.1`, whereas the current msdn page mentions only `/arch:armv8.0` and `/arch:armv8.8`

Somewhat interestingly, `cl /?` outputs:
`/arch:armv8.<0|8> minimum CPU extension requirements for Armv8.x-A`
it appears this actually means "armv8.0 through armv8.8, inclusive", judging by which arguments do not cause "invalid value" error to be generated from `cl` cmdline parser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f3e4cf-ede0-fccd-f678-7de958952ef2
* Version Independent ID: a9f3e4cf-ede0-fccd-f678-7de958952ef2
* Content: [/arch (ARM64)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-arm64?view=msvc-170)
* Content Source: [docs/build/reference/arch-arm64.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/arch-arm64.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shuffle2 
Thanks for the clarification. I was confused by the pipe in the command-line help and thought it was an alternation symbol, but that clearly leaves out the `/arch:armv8.1` case. An update just published should make it clearer, though I'm still wondering if there isn't a better way to indicate the range in the command-line help.
