### ISSUE TITLE
Sample code seems off

### ISSUE THREAD

**Issue by yuslepukhin** [MicrosoftDocs/cpp-docs#4123]
[Enter feedback here]

For a 64-bit pointer we need to allocate 64 bit space to point to and, therefore, second malloc arg needs be 8 (bytes) not 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64deafb-3fa3-6a4d-3b96-0058aec7701e
* Version Independent ID: 05070f5c-d97e-9d5f-d6ec-1714cb74e267
* Content: [__ptr32, __ptr64](https://docs.microsoft.com/en-us/cpp/cpp/ptr32-ptr64?view=msvc-170)
* Content Source: [docs/cpp/ptr32-ptr64.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/ptr32-ptr64.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yuslepukhin 
The space being allocated by `malloc` is for an `int`, which is 4 bytes on any platform. It's the size of the `void *` returned by `malloc` that depends on the platform, and that is what the casts are for. The code looks correct to me, so I'm closing the issue, but I'm open to change if you can show the code is incorrect.
