### ISSUE TITLE
/FR is *STILL USED* by the IDE!!!

### ISSUE THREAD

**Issue by dcorbin-wintellect** [MicrosoftDocs/cpp-docs#4125]
Try to show a project on CodeMaps without it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3eb6dd-250a-ae3f-1b6d-11a4a3cf11fc
* Version Independent ID: 8acc7e48-1a00-8ff1-0088-b7e5f3bdba94
* Content: [/FR, /Fr (Create .Sbr File)](https://docs.microsoft.com/en-us/cpp/build/reference/fr-fr-create-dot-sbr-file?view=msvc-170)
* Content Source: [docs/build/reference/fr-fr-create-dot-sbr-file.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/fr-fr-create-dot-sbr-file.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dcorbin-wintellect 
Thanks for the concern. I'm looking at the article, and I don't see anywhere that it says `/FR` is not used by the IDE. It says that BSCMAKE is not used by the IDE. The [Code maps for C++ projects](https://docs.microsoft.com/en-us/visualstudio/modeling/code-maps-for-cpp?view=vs-2022) article is pretty clear that it requires the `/FR` option. What am I missing?

**Comment by dcorbin-wintellect** [comment]
Implication... The following paragraph (bold added)

"During the build process, the Microsoft Browse Information File Maintenance Utility **(BSCMAKE) uses these files** to create a .BSC file, which is used to display browse information.:

Reading JUST THIS PAGE, there is no direct indication that anything (such as code maps) also uses this. Clarity could be improved.

This is not theoretical. On a major production project, a few close to 1000 projects when through a full PR and core review sample. Since only about 2% of the developer base has Enterprise, the fact that turning this off broke CodeMaps was not detected.... this means an entire Dev/Qa/PRod update costing thousands of dollars (conservatively).  

Better content could have saved this money (and this is simply one tangible occurance out of the many thousands of customers 
out there.

**Comment by corob-msft** [comment]
@dcorbin-wintellect 
Just published an update that should make the use cases and caveats clearer. Thanks for the input.
