### ISSUE TITLE
Document /LTCGOUT

### ISSUE THREAD

**Issue by TomHolmes343** [MicrosoftDocs/cpp-docs#4129]
The /LTCGOUTswitch is undocumented but is set by default in /LTCG configurations, to $(IntDir)$(TargetName).iobj

AFAIK This output file is required for /LTCG:Incremental, but is not needed for base /LTCG, and complex projects can fail to write out this iobj file, as it has the typical COFF 32-bit limit. When somebody runs into this link error, it can be difficult to self-diagnose what is going on, and documenting the flag and its use would help. 

The link error when the iobj cannot be written will look something like this

fatal error LNK1248: image size (100000000) exceeds maximum allowable size (FFFFFFFF)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b1cf62-ddfd-ce9a-b43f-c1e59b675fb7
* Version Independent ID: 0926975c-6c19-0c88-a306-d2b960716a7f
* Content: [/LTCG (Link-time code generation)](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-170)
* Content Source: [docs/build/reference/ltcg-link-time-code-generation.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/ltcg-link-time-code-generation.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by RussKeldorph** [comment]
We should not document this for use with /LTCG.  We'll likely want to deprecate and/or disable the current behavior with /LTCG, since it's easy to disable /LTCG:INCREMENTAL and leave /LTCGOUT on the command line, which is almost certainly wasting a massive amount of I/O and disk space.

**Comment by seuponder** [comment]
I have a same problem. 
To make matters worse, /LTCGOUT can only be manually removed from the ide. When I generated the project with cmake, I couldn't remove this option correctly. So much so that I couldn't automate the compilation. Do you have a better idea?

**Comment by corob-msft** [comment]
The [`/LTCGOUT`](https://learn.microsoft.com/en-us/cpp/build/reference/ltcgout?view=msvc-170) option was documented shortly after this issue was reported, but I failed to close the issue back in September when it was published. I have no suggestions for fixing projects generated by cmake where you remove `/LTCG` after the fact, other than perhaps regenerating the project. It should be trivial to remove `/LTCGOUT` from both the command line and the IDE.
