### ISSUE TITLE
how to PreProcess all mesage at ATL?

### ISSUE THREAD

**Issue by sgf** [MicrosoftDocs/cpp-docs#413]
just like override the WndProc in C#.
how can i do that in ATL?

**Comment by corob-msft** [comment]
Hi, @sgf -

This sounds like a programming question. I'd suggest a forum like [StackOverflow](https://stackoverflow.com/questions/tagged/atl) for questions like this one. They will probably recommend that you override [CAtlExeModuleT::RunMessageLoop](https://docs.microsoft.com/en-us/cpp/atl/reference/catlexemodulet-class?view=vs-2017#runmessageloop).

Closing this issue as it doesn't appear to describe a documentation defect.

**Comment by sgf** [comment]
im using ProcessWindowMessage now.
but cant use  message-map macros, thank you.
