### ISSUE TITLE
Missing AVX-512 registers

### ISSUE THREAD

**Issue by phuclv90** [MicrosoftDocs/cpp-docs#4131]
There's no mention of the zmm registers in the document and [here](https://en.wikipedia.org/wiki/X86_calling_conventions#List_of_x86_calling_conventions) it's assumed that zmm registers aren't allowed to be used for passing arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4fb0fe3-a57f-4253-3540-ab06afa5e793
* Version Independent ID: 590ac519-724c-d9e8-1b17-9840d8b8463e
* Content: [__vectorcall](https://docs.microsoft.com/en-us/cpp/cpp/vectorcall?view=msvc-170)
* Content Source: [docs/cpp/vectorcall.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/vectorcall.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@phuclv90 
The documentation is out of date since full AVX512 support was added in VS 2019. `__m512` types or equivalent HVAs can be passed in ZMM registers by `__vectorcall`, in the same order as the smaller types, and with the same spill to stack limits.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
