### ISSUE TITLE
Let's Stop This Curlied Nonsense

### ISSUE THREAD

**Issue by MarkMoretto** [MicrosoftDocs/cpp-docs#4137]
Hi,

Let's stem the trend of having opening curly braces on a new line.  Inline curlies works great and keeps code compact and very readable.

Even on the page in question, your `try-catch` block keeps things inline.  How were y'all able to type that if you didn't know what was going on due to confusing curly brace placement?

Here's an example from [another page](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=msvc-170) in the MS docs:

```cpp
    try
    {
        MyFunc(256); //cause an exception to throw
    }

    catch (invalid_argument& e)
    {
        cerr << e.what() << endl;
        return -1;
    }
```

Is this too confusing?

```cpp
    try {
        MyFunc(256); //cause an exception to throw
    } catch (invalid_argument& e) {
        cerr << e.what() << endl;
        return -1;
    }
```

Or, even better:

```cpp
    try {
        MyFunc(256); //cause an exception to throw
    // } catch (invalid_argument& e) {
    } catch (invalid_argument const& e) {
        cerr << e.what() << endl;
        return -1;
    }
```

How about this?

```cpp
    try { MyFunc(256); } catch (invalid_argument const& e) { cerr << e.what() << endl; return -1; }
```

We can do better...

```cpp
#define t try
#define c catch
#define r return
#define pr cout
#define ia std::invalid_argument
#define TC(f,E) t{f;}c(E& e){pr<<e.what();r -1;}

TC(MyFunc(256),ia);
```

...maybe that's a little too far.

The [next page](https://docs.microsoft.com/en-us/cpp/cpp/how-to-design-for-exception-safety?view=msvc-170) is back to common-sense bracketry.  So, I think in Microsoft's heart-of-hearts, it knows that inline curly braces are the best option.

Don't take my word for it, see LLVM's best-practices for C++ syntax structure for more info. Y'all know what LLVM is, right? Kind of a small, insignificant library made by people who don't know how to write C++. (*cough*justkidding*cough*)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a1d03d-a2f4-0b09-63d3-9ef0798d6bf9
* Version Independent ID: 6f1fbb61-074c-d65c-4a1d-ed97687ffff6
* Content: [try, throw, and catch Statements (C++)](https://docs.microsoft.com/en-us/cpp/cpp/try-throw-and-catch-statements-cpp?view=msvc-170)
* Content Source: [docs/cpp/try-throw-and-catch-statements-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/try-throw-and-catch-statements-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MarkMoretto

We have samples using various K&R and column-matching block styles in the docs, created over the last thirty-plus years of shifting standards. Compact styles date to when twenty-four rows of screen real estate were common and code was regularly printed on paper, so vertical economy was vital. Nowadays, screens are huge and paper listings are practically non-existent outside of textbooks. Code readability is paramount. Studies show [K&R blocks are judged less readable than alternative block formats](https://www.researchgate.net/publication/326500880_Impacts_of_coding_practices_on_readability), [LLVM coding standards](https://llvm.org/docs/CodingStandards.html) notwithstanding, so we don't usually use that style. New and reworked code gets the current default Visual Studio block formatting style of unindented braces surrounding indented statements.

We don't have the bandwidth to reformat everything in Docs to the *mode du jour*, but if you copy a block of sample code into your own editor, reformatting it however you like is only a keystroke or two away. Ctrl-K, Ctrl-D in VS, or Shift-Alt-F in VS Code. Having it your way couldn't be much easier.
