### ISSUE TITLE
Indicate that __umulh() is supported on arm64

### ISSUE THREAD

**Issue by szhorvat** [MicrosoftDocs/cpp-docs#4149]
`__umulh()` is marked as supported only on the x64 architecture, but in fact it is also supported on arm64.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21c6c14-b72e-7f99-41e7-197b7e1b3609
* Version Independent ID: e31a869d-935f-2262-3137-cd217720e6e4
* Content: [__umulh](https://docs.microsoft.com/en-gb/cpp/intrinsics/umulh?view=msvc-170)
* Content Source: [docs/intrinsics/umulh.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/umulh.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@szhorvat 
Thanks for the report. I fixed this a couple of weeks ago but forgot to close the loop here.
