### ISSUE TITLE
Problem in sample code

### ISSUE THREAD

**Issue by krishty** [MicrosoftDocs/cpp-docs#4150]
I think the code in the **Example** section is wrong: It should be double backslashes instead of single backslashes.

With single backslashes (as in the article), Visual Studio complains _“invalid escape sequence”_ because backslashes are escaping characters:

![image](https://user-images.githubusercontent.com/51880096/189150746-d19f2ff5-9e69-4a2c-bcac-9643bbc65c1a.png)

Should be changed to double backslashes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed0104b-8ba3-0b4d-5765-29f20e842b5c
* Version Independent ID: 7d5cc7af-86de-89cd-c86f-61f050ce7d1b
* Content: [CppProperties.json reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=msvc-170)
* Content Source: [docs/build/cppproperties-schema-reference.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cppproperties-schema-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@krishty 
Thanks for the report. I fixed this in docs published last week, but I forgot to update the issue here.
