### ISSUE TITLE
Inefficient primality test in example

### ISSUE THREAD

**Issue by moe6477** [MicrosoftDocs/cpp-docs#4153]
For the primality test, it suffices to check the divisors up to the square root of n.

```
bool is_prime(int n)
{
    if (n < 2)
        return false;
    for (int i = 2; i < int(std::sqrt(n))+1; ++i)
    {
        if ((n % i) == 0)
            return false;
    }
    return true;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c997775-b4db-e7f2-6aa7-0e79967617e1
* Version Independent ID: b7bf9d1d-626b-a2b6-dc9a-fa8487d71918
* Content: [How to: Write a parallel_for_each Loop](https://docs.microsoft.com/en-us/cpp/parallel/concrt/how-to-write-a-parallel-for-each-loop?view=msvc-170)
* Content Source: [docs/parallel/concrt/how-to-write-a-parallel-for-each-loop.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/parallel/concrt/how-to-write-a-parallel-for-each-loop.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@moe6477 - I'm not clear on your comment. You indicate that it suffices to check up to the square root of n; isn't that what this code is doing? Or are you objecting to the +1?

**Comment by moe6477** [comment]
Hi Tyler,

this is the corrected version. The code given in the example https://docs.microsoft.com/en-us/cpp/parallel/concrt/how-to-write-a-parallel-for-each-loop?view=msvc-170 loops until n.
This is just a minor thing, but as the article is about gaining performance using parallelism, it catched my eye, that the actual primality test was wasting computation time.

Regards
Mesut

**Comment by TylerMSFT** [comment]
I see. I agree with you that it'd be good to fix this. I'll take care of it this week.

**Comment by TylerMSFT** [comment]
@moe6477 , thank you for the suggestion to improve this code. The update will be out early this week.
