### ISSUE TITLE
Missing documentation for the ATL CRegKey::m_samWOW64 public member

### ISSUE THREAD

**Issue by GiovanniDicanio** [MicrosoftDocs/cpp-docs#4155]
The `m_samWOW64` _public_ data member of the `ATL::CRegKey` class is undocumented (related [StackOverflow question](https://stackoverflow.com/q/73574044/1629821)).

Please add some official documentation about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84697dbc-43ce-bf25-2cc1-de85d335d431
* Version Independent ID: 2a45c4c2-605e-6ec7-a271-5dd251bc40f4
* Content: [CRegKey Class](https://docs.microsoft.com/en-us/cpp/atl/reference/cregkey-class?view=msvc-160#attach)
* Content Source: [docs/atl/reference/cregkey-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/atl/reference/cregkey-class.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.

**Comment by GiovanniDicanio** [comment]
_> If you think this issue should not have been closed, reopen it with a comment explaining why._

We have a **public** data member of an **important** ATL C++ class, which is **undocumented**. I mean: it's not an implementation detail. If this is not an enough reason to reopen this issue, I don't know what else could be.
