### ISSUE TITLE
[ATL/MFC CString]: Sample code explicitly states to *not* call ReleaseBuffer after GetBufferSetLength, contradicting the previous documentation

### ISSUE THREAD

**Issue by GiovanniDicanio** [MicrosoftDocs/cpp-docs#4158]
The documentation for `CString::GetBufferSetLength()` advises to call `ReleaseBuffer()` to update the string object internal state _before_ invoking other `CString `methods.

But the associated sample code does the opposite, and it even contains the following comment:

```
[...]
// No need for trailing zero or call to ReleaseBuffer()
// because GetBufferSetLength() set it for us.
```

Either the documentation or the code snippet should be fixed.

Related [topic](https://stackoverflow.com/questions/39275259/should-cstrings-getbuffersetlength-have-a-matching-releasebuffer-call) on StackOverflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1602476d-1f52-7b9b-1316-e9d5b5859d65
* Version Independent ID: d3541eb2-f249-2f17-a31d-adc0654ce49c
* Content: [CSimpleStringT Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/csimplestringt-class?view=msvc-160&redirectedfrom=MSDN#getbuffersetlength)
* Content Source: [docs/atl-mfc-shared/reference/csimplestringt-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/atl-mfc-shared/reference/csimplestringt-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@GiovanniDicanio , I've updated the topic to show calling ReleaseBuffer(), and got rid of the comment about not needing to call it.
I walked through the implementation in the debugger and it's *technically* true that for this particular example it wasn't necessary to call ReleaseBuffer(). But the document should speak to the general case and the best practice and so I've updated it. It'll be live by Monday afternoon.
