### ISSUE TITLE
Where is information on ‘extern “C++”’?

### ISSUE THREAD

**Issue by random9q** [MicrosoftDocs/cpp-docs#4159]
I actually came to this page _specifically_ to learn the difference. There isn’t a lot of good information out there on that, and even in this page the only examples shown provide ‘extern “C”’.

What if I don’t care about interop with C or other languages? What if what I really want to do is make a C++ class library (not a mere function library) that’s strictly to be consumed by other C++ code? If it’s an option that exists right alongside ‘extern “C”’, why was that implemented? What does it do/accomplish (and what does it not do/accomplish)?

Furthermore: How do I best go about generating .lib and .dll class library projects (again, that are strictly to be consumed by other C++ code) and how might ‘extern “C++”’ fit or not fit into that kind of project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5507963a-8f67-1de6-d164-28469e956006
* Version Independent ID: d4155e73-d05d-997b-8454-09564ea117d8
* Content: [extern (C++)](https://docs.microsoft.com/en-us/cpp/cpp/extern-cpp?view=msvc-170)
* Content Source: [docs/cpp/extern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/extern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@random9q 
Those are good questions. For the headline question, the answer is simple. `extern "C++"` exists for symmetry with `extern "C"`. The `extern "language"` pattern specifies something called a *language linkage*, which is an implementation-specific set of naming and calling convention rules applied to external symbols for variables and function names. When you specify `extern`, it's also `extern "C++"` by default. `extern "C"` means use the C naming and calling convention for the declared name, while `extern "C++"` means use the C++ naming and calling convention. The only practical use for `extern "C++"` is to declare a function or variable with C++ linkage that's nested inside of an `extern "C"` block. I'd question such an item in code review; as it's almost certainly in the wrong place. In decades of coding, I've never had occasion to use `extern "C++"` except when writing about it, like this. You'll probably never need it, either.

As for creating C++ DLL or static library projects, I recommend using the templates in Visual Studio. If your code will never need to interoperate with other languages, then it's safe to ignore `extern "C"` for interfaces, and just use regular `extern` declarations to call your static library functions, or `__declspec(dllimport)` for DLL function declarations. All functions and global or thread-local variables that do require `extern "C"`, such as those in the CRT or the Win32 APIs, specify it in the relevant header files, so you'll never need to worry about it in your own code. Hope that helps.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
