### ISSUE TITLE
On the web page, there was no text display.

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#416]
When I open the web page in the browser no text was display and I followed the instructions exactly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058d8323-d824-40eb-4954-2620d86a44b6
* Version Independent ID: a090fbda-31ee-a2d1-6f9c-9e495b4b4e08
* Content: [Adding a Control (ATL Tutorial, Part 2)](https://docs.microsoft.com/en-us/cpp/atl/adding-a-control-atl-tutorial-part-2?view=vs-2017)
* Content Source: [docs/atl/adding-a-control-atl-tutorial-part-2.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/adding-a-control-atl-tutorial-part-2.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@makelyblakley We have verified that the topic is still accurate. The most likely cause for your problem is the ActiveX settings in IE. This page tells how to adjust those settings: https://support.microsoft.com/en-in/help/17469/windows-internet-explorer-use-activex-controls
