### ISSUE TITLE
Supported file version incorrect

### ISSUE THREAD

**Issue by adara9** [MicrosoftDocs/cpp-docs#4161]
In the "Supported CMake and CMakePresets.json versions" section, the first sentence says "Visual Studio supports version 2 or later for the CMakePresets.json and CMakeUserPresets.json files." However, when I try to use any version later than 3, VS 2022 gives an error that it only supports file versions 2 to 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@adara9 
Thanks for the report. While I can update the document with this limitation, you'd probably rather have the product support the later versions of the CMakePresets files. To request this capability, I recommend using the **Suggest a Feature** command in the VS IDE (accessible via the **Help** > **Send Feedback** > **Suggest a Feature** menu). That will create a new issue in [Developer Community](https://aka.ms/vsfeedback/browsecpp) where it will get the attention of the relevant product team members. When and if that feature is adopted, we'll update the docs again accordingly.

**Comment by adara9** [comment]
Thanks! The webpage that took me to said to search for similar issues
first, and I see that the team has already added support for file version 4
in the current preview release. Looking forward to seeing that in a full
release.

**Comment by corob-msft** [comment]
Update posted.
