### ISSUE TITLE
The process was not automated.

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#417]
The "get" and "put" statements were not automatically inserted into the PolyCtl.h and PolyCtl.cpp files. I had to do it manually. The IDL file created a Get function but Put was inserted as Set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29408b51-59df-3afb-b521-7fcdb259803f
* Version Independent ID: e32689f9-74c1-3055-79fd-c32728dbf665
* Content: [Adding a Property to the Control (ATL Tutorial, Part 3)](https://docs.microsoft.com/en-us/cpp/atl/adding-a-property-to-the-control-atl-tutorial-part-3?view=vs-2017)
* Content Source: [docs/atl/adding-a-property-to-the-control-atl-tutorial-part-3.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/adding-a-property-to-the-control-atl-tutorial-part-3.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Investigating

**Comment by mikeblome** [comment]
@makelyblakley thanks for the feedback! This has now been fixed.
