### ISSUE TITLE
What is the maximum length of additional including directories for C++ in vs2019/vs2022?

### ISSUE THREAD

**Issue by zchrissirhcz** [MicrosoftDocs/cpp-docs#4173]
Hi, cpp-docs maintainers

We use vs2019 for C++ development, and I configured many additional directories. Some of them works, some ain't.

I just wonder if there is maximum length limitation of additional path ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec7ea59-1270-7e09-8240-651d34d7e758
* Version Independent ID: e004b9b0-4031-8bd9-b2bf-247656829ebe
* Content: [/I (Additional include directories)](https://learn.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-170)
* Content Source: [docs/build/reference/i-additional-include-directories.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/i-additional-include-directories.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@zchrissirhcz 
Visual Studio doesn't impose a maximum length on this value (it depends on available heap space). The operating system limits how long a command line can be, and how long the block of environment variables can be. Both are limited to 32K characters. Other components such as CMD.EXE have lower limits on command line length - I think 8K characters. If you're getting close to the limit, then you should consider refactoring your include directories to use shorter path names. Hope this helps.
