### ISSUE TITLE
The intro part of this page may have some ambiguity

### ISSUE THREAD

**Issue by KSroido** [MicrosoftDocs/cpp-docs#4178]
I think the intro part of [this page](https://learn.microsoft.com/en-us/cpp/cpp/overload-resolution-of-function-template-calls?view=msvc-170) may have some ambiguity. 

A function template can overload nontemplate functions of the same name,  In this scenario, **function**(template ones? or non-template ones?) ....... first using template...( it seems like using template ones, but the actual debugging and the rest doc shows it should be nontemplate ones)

I think this might be better:

A function template can overload nontemplate functions of the same name,  In this scenario,  **function template** should fit ....., If template argument deduction fails(don't fit those thing), then nontemplate functions will....

thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8b6a2ca-7524-bef7-fab2-ee7d05956eb4
* Version Independent ID: c1fe9a80-b7f1-d7cb-1ecd-ca09752de996
* Content: [Overload Resolution of Function Template Calls](https://learn.microsoft.com/en-us/cpp/cpp/overload-resolution-of-function-template-calls?view=msvc-170)
* Content Source: [docs/cpp/overload-resolution-of-function-template-calls.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/overload-resolution-of-function-template-calls.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@KSroido 
Thanks for the report. I've updated the text in a way that I hope reduces the ambiguity and clarifies the sequence of events and candidate choices. Some complexity remains, because the process is complex.

**Comment by KSroido** [comment]
thank you!
