### ISSUE TITLE
Question about "dup2()" and MFC

### ISSUE THREAD

**Issue by Getwang959** [MicrosoftDocs/cpp-docs#4180]
[Enter feedback here]

As for the example of “dup2()”, it can be used normally in WIN32, but can't achieve redirection in MFC program. What is the reason? Is there any solution ？
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 155c7b5a-b148-0736-b13f-fd271f15c832
* Version Independent ID: 60c21c6b-69ed-3458-1928-5172adb22a06
* Content: [_dup, _dup2](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/dup-dup2?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/dup-dup2.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/dup-dup2.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Getwang959 , can you provide a concrete example of what you are trying to do that doesn't work in MFC?

**Comment by Getwang959** [comment]
The "testFunction" is my test case，as follows：
#include <io.h>
#include <stdio.h>
#include <iostream>
 void testFunction()
{
    FILE* f = fopen("test.txt", "w");
    _dup2(_fileno(f), 1);
    std::cout << "Test For dup2 To File!\n";
};

You can add the function to the OnInitDialog function of the MFC Dialog Project ， "Test For dup2 To File!\n"  can not be printed out to "test.txt" .But if  you add the function to the Win32 ConsoleApplication Project ,"Test For dup2 To File!\n"  can be printed out to "test.txt"

**Comment by TylerMSFT** [comment]
@Getwang959, the problem here isn't `_dup2`, but `cout`. MFC applications are not console applications, so `cout` will not work at all even if you try to redirect it to a file.

**Comment by Getwang959** [comment]
Is there anyway if I want to implement redirection in mfc application?And I have tested this test case in qt widget application and it works, please tell me why, I would be very grateful to you.

**Comment by Getwang959** [comment]
Is there anyway if I want to implement redirection in mfc application?And I have tested this test case in qt widget application and it works, please tell me why, I would be very grateful to you.

**Comment by TylerMSFT** [comment]
@Getwang959, I'm not aware of a way to do it. But I am not an MFC expert. Unfortunately, we aren't equipped here in the doc org to provide MFC support. You might take this up in the [Developer Community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fvsfeedback%2Fbrowsecpp&data=04%7C01%7CTyler.Whitney%40microsoft.com%7C5741446ac59c4b9db2fd08d9878e62a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637689867885607869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MF%2BRQ2YB96%2F8%2FGlewv2ttenU5mu%2FaAuBut8FcfVR12k%3D&reserved=0), or a MFC developer support site. I'm sorry I can't be of more help.
