### ISSUE TITLE
Possibly incorrect/lacking information for visual studio 2022

### ISSUE THREAD

**Issue by naota29** [MicrosoftDocs/cpp-docs#4181]
This page says StdAfx.h is used, in visual studio 2022, but isn't pch.h now being used instead?

Also this page does not mention anything regarding the generated files which contain the interface definitions (projectname_i.h and projectname_i.c).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2736e8c-70b7-d64f-a6e3-d73de8243326
* Version Independent ID: 07097902-0b23-4c63-e6ea-b82e7e80bada
* Content: [ATL Program or Control Source and Header Files](https://learn.microsoft.com/en-us/cpp/build/reference/atl-program-or-control-source-and-header-files?view=msvc-170)
* Content Source: [docs/build/reference/atl-program-or-control-source-and-header-files.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/atl-program-or-control-source-and-header-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@naota29 Thanks for the report. An update will be published tomorrow with a fix.
