### ISSUE TITLE
Mislabeled code boxes

### ISSUE THREAD

**Issue by RHolton** [MicrosoftDocs/cpp-docs#4186]
[Enter feedback here]
In the section "C and C++ const differences", the first two code example boxes are labeled as C++, but should be labeled as C.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2101a0d-2ec0-5192-38bf-73a026387ec2
* Version Independent ID: 1a4b1cce-492e-9083-0be9-6a62d6a24e6e
* Content: [const (C++)](https://learn.microsoft.com/en-us/cpp/cpp/const-cpp?view=msvc-170)
* Content Source: [docs/cpp/const-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/const-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@RHolton 
Thanks for the report. I've updated the code box labels, so the result should be visible sometime tomorrow when the update is published.
