### ISSUE TITLE
Missing definition/explanation

### ISSUE THREAD

**Issue by houseofwealth** [MicrosoftDocs/cpp-docs#4193]
The 
[Enter feedback here]
The argument EXCEPTION_EXECUTE_HANDLER to the except statement in the Example isn't explained or defined anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6820eb86-7922-fc81-a6cd-80fbf6143726
* Version Independent ID: 3e2936b4-498d-0656-17d3-d4fa6566630c
* Content: [Structured Exception Handling (C/C++)](https://learn.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-170)
* Content Source: [docs/cpp/structured-exception-handling-c-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/structured-exception-handling-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@houseofwealth 
Thanks for the report. That's not an unreasonable request, so I've added some links to the `try-except` statement docs that go into more detail, and I added the preprocessor macro constants for the exception handling filter expression to the descriptions. The update should be visible tomorrow with our next publishing cycle.
