### ISSUE TITLE
/ILK is missing

### ISSUE THREAD

**Issue by CatShootingStar** [MicrosoftDocs/cpp-docs#4194]
`/ILK` is missing from the list

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0255b2-cf9d-3325-ccd7-e34aed553311
* Version Independent ID: d1664a56-cee1-bdd9-bb77-3acb62670a41
* Content: [MSVC Linker options](https://learn.microsoft.com/en-gb/cpp/build/reference/linker-options?view=msvc-170)
* Content Source: [docs/build/reference/linker-options.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/linker-options.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CatShootingStar 
So it is. I forget sometimes about all the places that need updates when I add an article; thanks for pointing this one out. The update should be visible after our next publishing cycle, sometime tomorrow.
