### ISSUE TITLE
Why is wmain shown without a return type?

### ISSUE THREAD

**Issue by Keith-S-Thompson** [MicrosoftDocs/cpp-docs#4195]
The declaration for `wmain` is shown as:
```
wmain( int argc, wchar_t *argv[ ], wchar_t *envp[ ] )
```

This relies on the obsolete "implicit `int`" feature, which has been invalid in C since the 1999 standard and in C++ for even longer.

The correct version:
```
int wmain( int argc, wchar_t *argv[ ], wchar_t *envp[ ] )
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26b1131c-87d8-3199-9275-b3fe094aba40
* Version Independent ID: 473540ca-baa7-d6bb-8f3c-327a29ef3804
* Content: [Using wmain](https://learn.microsoft.com/en-us/cpp/c-language/using-wmain?view=msvc-170)
* Content Source: [docs/c-language/using-wmain.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/using-wmain.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Keith-S-Thompson** [comment]
The same problem occurs in `docs/c-language/main-function-and-program-execution.md`.

**Comment by corob-msft** [comment]
@Keith-S-Thompson 
Thanks for the report. These articles may be some of the oldest in our C-language content. They almost certainly predate the change from default `int` return types. A fix is ready to publish later today.
