### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by kingofDaniel** [MicrosoftDocs/cpp-docs#4198]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8649ec5-09cf-8157-8bbb-f71dc329b669
* Version Independent ID: d991cbe7-79f0-a43d-5331-f16e9632deab
* Content: [Preprocessor directives](https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-directives?view=msvc-170)
* Content Source: [docs/preprocessor/preprocessor-directives.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/preprocessor-directives.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kingofDaniel 
It appears there's no issue here to address.
