### ISSUE TITLE
Should the doc cover dependency headers of static libraries?

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/cpp-docs#420]
Hi, recently I've followed this tutorial and everything has gone quite well. 

But the problem arose when my static library (as I'm a beginner in C++) referred to some other headers/libraries (DirectX in this case). My target application where I use the static library could not understand what was written in the library. Well, header got included, and the app could see it. But it took me awhile to solve it. Here is the link to my question: https://stackoverflow.com/questions/52217025/static-library-is-fine-alone-but-throws-errors-when-being-referred

In short, I didn't know that I need to include all needed headers in my target application. ... :( So, I'm wondering if we can expand this document to cover that area as well? Possibly be a big help for beginners like me.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9992332-7b7b-d08a-704a-9fe928fdbd56
* Version Independent ID: 181bf5b3-50bd-dd0b-d8ec-2cce408397a1
* Content: [Walkthrough: Creating and Using a Static Library (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-and-using-a-static-library-cpp?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@nguyenlamlll Thanks for the feedback and sorry for very late response here. I looked at the topic and it actually does say to add the headers to your library, under the section "Using the functionality from the static library in the app".
