### ISSUE TITLE
Possible error in code example in article regarding .NET (un)boxing

### ISSUE THREAD

**Issue by th0masjk** [MicrosoftDocs/cpp-docs#4200]
In the code example that uses generics (the last code example on that page) a comment says a boxing operation is performed, like in the less efficient, non-generic previous example where all objects pushed onto the stack are converted to System.Objects). Later on, in the same example with generics, a comment says no unboxing occurs since a value type is popped off of the Stack<T>.
Shouldn't the comment stating that boxing takes place when pushing an System.Int32 onto the Stack<int> be removed? I assume it is wrong in this code example, and a remainder from the previous example which was probably just copied and slightly altered so that it uses generics.
I am referring to this page:
https://learn.microsoft.com/en-us/cpp/extensions/how-to-improve-performance-with-generics-visual-cpp?view=msvc-170

And if you scroll down to the last example, you will see this in the code:

    Stack<int> ^s = gcnew Stack<int>();

    // Push an integer to the Stack.
    // A boxing operation is performed here.         <-- Is this correct?
    s->Push(7);
    s->Push(14);
,,,
,,,
    // Pop an item off the Stack.
    // The item is returned as the type of the collection, so no
    // casting is necessary and no unboxing is performed for        <-- Author says no unboxing, i.e. no boxing to begin with?
    // value types.
    int i = s->Pop();

Please tell me if I am right or wrong by e-mailing me here: thomas_kappel@hotmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43f50096-8c43-a8d8-484f-73ca1cc26832
* Version Independent ID: a1c12fcb-eb65-525a-22f5-c7bd174b3ccb
* Content: [How to: Improve Performance with Generics (C++/CLI)](https://learn.microsoft.com/en-us/cpp/extensions/how-to-improve-performance-with-generics-visual-cpp?view=msvc-170)
* Content Source: [docs/extensions/how-to-improve-performance-with-generics-visual-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/extensions/how-to-improve-performance-with-generics-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@th0masjk 
Thanks for pointing out this issue. The comment is incorrect, as a quick check of the output of ildasm will show. There's no boxing or unboxing of `int` types in a `Stack<int>` collection. I've updated the docs, and the fix should go live tomorrow.

**Comment by th0masjk** [comment]
It's a great feeling, having had a (positive?) impact on an MSDN article / anything Microsoft. I can now brag to my friends by telling them I helped Microsoft once...!
