### ISSUE TITLE
LNK1104 error code   

### ISSUE THREAD

**Issue by RodneyJones666** [MicrosoftDocs/cpp-docs#4206]
LNK1104 error code says cannot open python36_d.lib file.  but I'm not aware of that file even existing anywhere within my code.  I'm at a loss. I'm trying to set up python to be called by C++ in Visual Studio and it's just been a hassle.  Really the file it should be reading is the python36.dll file. what should i do?

**Comment by corob-msft** [comment]
@RodneyJones666 
While this isn't a help forum (better choices exist, such as [Microsoft Learn Q&A](https://learn.microsoft.com/en-us/answers/topics/c%2B%2B.html) or [Developer Community](https://aka.ms/vsfeedback/browsecpp)), it sounds like you may not have set up your project configuration correctly for release and debug. You may have set the debug library to be included in the project configurations for both. Check the **Configuration** drop-down at the top of the project's Property Pages dialog where you specify the additional libraries, and see what is set for different configurations. If that doesn't show what's wrong, then I'd check one of the other forums, or StackOverflow, for deeper assistance. Sorry I'm not more help. I'm closing this as not a documentation issue.
