### ISSUE TITLE
Only edit projects in the IDE? does not scale well

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/cpp-docs#4213]
> We recommend you only create and modify .vcxproj projects in the IDE

This should be qualified for individual projects. For projects with many .vcxproj files, build configuration should be factored into `Directory.Build.Props` and other re-usable specifications to enable maintenance that scales. In fact, the [MS Build Sdks](https://github.com/nirin/msbuild-sdks#available-sdks) support these scenarios (and require manual project editing to convert to use them).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 825f837e-aced-b5bd-719e-af3e5199c3c0
* Version Independent ID: 7663ace3-0f28-5eb1-6fd8-0fa9c10da834
* Content: [.vcxproj and .props file structure](https://learn.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=msvc-170)
* Content Source: [docs/build/reference/vcxproj-file-structure.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/vcxproj-file-structure.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ChrisGuzak 

I appreciate where you're coming from. You're right, there's significant value to be gained by editing project files. Use of common *`.props`* files across multiple projects to maintain company- or department-wide common libraries and build settings can eventually save person-years of effort. However, doing it safely requires a non-trivial investment in time and learning about MSBuild and the project system.

The current recommendations were added at the request of people on the dev team in response to problems reported on Developer Community. They're intended to scare off anyone who isn't willing to invest in that deeper understanding of MSBuild project files before fiddling with them. Poorly understood editing of project files with StackOverflow copypasta is fraught with danger. Apparently, it's all too easy to break the 2-way sync between the IDE property pages and the *`.vcxproj`* file by editing the latter in a text editor, and difficult to diagnose the build issues that result. 

The upshot is, we're trying to maintain a balance in our recommendations. We get all audiences in the docs, so we have to tailor our messages accordingly: Dabblers - *Here There Be Dragons, With Ketchup Ready*. Experts - *Flying On Dragons is Useful, Here's How Without Getting Burnt to a Crisp*. Thus, our first recommendation is "Don't." The second recommendation adds some qualifications to "Don't." And then the article goes on and says "If you do, here are issues you'll need to watch out for."

I'm happy to consider some other wording, if you have any to suggest. Just remember [the curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge).

**Comment by ChrisGuzak** [comment]
Please describe the exceptions. I had someone that owns a repo with hundreds of projects point to this as the reason for not consolidating build logic. we need to differentiate large- and small-scale development. 

> For simple projects, we recommend using the IDE UI for managing project files, but as the number of projects scale up, there is a point where re-factoring, by experts of the project file format, is a significant win; see these MSBuild SDKs that are useful for the large-scale case.

**Comment by ChrisGuzak** [comment]
@corob-msft please consider that update.

**Comment by corob-msft** [comment]
An update should be visible by noon PST.
