### ISSUE TITLE
Example code for CMFCPropertyGridProperty::SetValue appears twice

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#4222]
[Enter feedback here]
Only the second Example entry is the correct entry. Since I probably caused the double entry by submitting two PRs, I am going to leave it alone and let you guys sort it out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1c6e558-795c-347d-f09e-56cfdc9602fe
* Version Independent ID: 210b19b2-9b99-0e84-938c-f96be5b96082
* Content: [CMFCPropertyGridCtrl Class](https://learn.microsoft.com/en-us/cpp/mfc/reference/cmfcpropertygridctrl-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cmfcpropertygridctrl-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/cmfcpropertygridctrl-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@rtischer8277 
Yes, we spotted that. A fix is in the works. It'll be right in a few hours, once the next publishing event happens.
