### ISSUE TITLE
Tools > Options > CMake Fig, Not Current Version

### ISSUE THREAD

**Issue by Ohgochi** [MicrosoftDocs/cpp-docs#4228]
"Cross-platform CMake development with a WSL 2 distro"
"5.Enable Visual Studio's CMake Presets integration. Select Tools > Options > CMake > General. " 
The figure shown here is different from the current version.

My current version: 
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.6
The current version has the following configuration

CMake configuration file:
  Always use CMake Oresets
  Use CMake Presets if ....

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04407792-a1b1-4238-16c0-2627f0aef2c9
* Version Independent ID: 04407792-a1b1-4238-16c0-2627f0aef2c9
* Content: [Walkthrough: Build and Debug C++ with Microsoft Windows Subsystem for Linux 2 (WSL 2) and Visual Studio 2022](https://learn.microsoft.com/en-us/cpp/build/walkthrough-build-debug-wsl2?view=msvc-170)
* Content Source: [docs/build/walkthrough-build-debug-wsl2.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-build-debug-wsl2.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @Ohgochi, I've updated the UI in the doc. Thank you for bringing this to our attention. This should be live early next week.
