### ISSUE TITLE
C4623: Inaccurate sentence about creating stack objects.

### ISSUE THREAD

**Issue by golvok** [MicrosoftDocs/cpp-docs#4235]
The following is not true:
> Any attempt to create an object of this type on the stack will cause a compiler error.

Suggest:
> Any attempt to create an object of this type without arguments will cause a compiler error.

[godbolt link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:13,endLineNumber:19,positionColumn:13,positionLineNumber:19,selectionStartColumn:13,selectionStartLineNumber:19,startColumn:13,startLineNumber:19),source:'%0A//+C4623.cpp%0A//+compile+with:+/W4%0A%23pragma+warning(default+:+4623)%0Aclass+B+%7B%0A+++B()+%7B%7D%0Apublic:%0A+++B(int)+%7B%7D%0A%7D%3B%0A%0Aclass+F+:+public+B+%7B%0A+++using+B::B%3B%0A%7D%3B%0A%0Aint+main()+%7B%0A+++//+F+f1%3B+//+will+cause+an+error%0A+++//+new+F%3B+//+also+compile+error%0A+++F+f2(1)%3B+//+no+compile+error%0A+++new+F(1)%3B+//+no+compile+error%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:51.22715404699739,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:/W4,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x64+msvc+v19.latest+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'0'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:48.77284595300261,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

Also, the page lacks motivation about why you would want this warning... I'm not sure what the intent is (in my experience, an inaccessible or deleted default constructor is usually on purpose), but my best guess is:

> This may be surprising to users, since it is not obvious from the class definition alone that it cannot be default constructed. Explicitly deleting the default constructor in the derived class waives this warning and shows this in an obvious way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e217485c-be10-0214-7daf-7c37667b3ae3
* Version Independent ID: 341c33d3-26ae-cd40-ddb5-06e0cbe22fef
* Content: [Compiler Warning (level 4) C4623](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4623?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4623.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4623.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@golvok 
Thanks for the report. I published an update that's not specific to stack instances. Hopefully the description makes it easier to identify the issue, without making too many assumptions about what's obvious or surprising to readers.
