### ISSUE TITLE
Article on `constexpr` incorrectly states that virtual functions can't be constexpr

### ISSUE THREAD

**Issue by DavidJCobb** [MicrosoftDocs/cpp-docs#4245]
One of the rules that the page lists for `constexpr` functions is

> It can't be [virtual](https://learn.microsoft.com/en-us/cpp/cpp/virtual-cpp?view=msvc-170). A constructor can't be defined as `constexpr` when the enclosing class has any virtual base classes.

However, as of C++20, this is no longer true. MSVC appears to support the C++20 change as well.

Tested [in Godbolt](https://godbolt.org/z/xKdb8GWGT) just to be sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09262045-27b3-a35c-f382-6ab08604eed5
* Version Independent ID: 95bf2505-64a6-026c-f33c-3f1931d6985e
* Content: [constexpr (C++)](https://learn.microsoft.com/en-us/cpp/cpp/constexpr-cpp?view=msvc-170)
* Content Source: [docs/cpp/constexpr-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/constexpr-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by frederick-vs-ja** [comment]
In C++23 the restrictions are furtherly relaxed, although MSVC hasn't implemented the changes at this moment.
