### ISSUE TITLE
Please, turn the examples easier to begginers

### ISSUE THREAD

**Issue by xwendel** [MicrosoftDocs/cpp-docs#4246]
It is supposed the main goal of this article is explaining and demonstrating weak_ptr usage. It is supposed also this article should be didactic. If a user is researching about a basic thing like weak_ptr, probably he or she does not have advanced knowledge about C++. From this, I would recommend the code example presented here be as simple as possible. The example is not so easy for a beginner understanding, since advanced resources like _explict_, _lambda_, and _for_each_ are being used. In other words, a beginner who is trying to understand this article about weak_ptr probably will need stop his/her lecture to find information about that advanced resources, and that turns this article not so good. It is important to note also these advanced resources are not really necessary here. Same functionality could be got from a more basic C++ structure, and that would turn easier for a beginner c++ reader, specially students that just learned C language. I would recommend refactor the example making code easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c879eb4-3a94-9968-63b1-1f4519ce11f8
* Version Independent ID: ae94388e-d305-321f-763d-f864aa7ecc32
* Content: [How to: Create and use weak_ptr instances](https://learn.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-weak-ptr-instances?view=msvc-170)
* Content Source: [docs/cpp/how-to-create-and-use-weak-ptr-instances.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/how-to-create-and-use-weak-ptr-instances.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
