### ISSUE TITLE
Does not match 2022

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#4251]
The tutorial appears not to be updated for version VS 2022. Very frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 058d8323-d824-40eb-4954-2620d86a44b6
* Version Independent ID: a090fbda-31ee-a2d1-6f9c-9e495b4b4e08
* Content: [Adding a Control (ATL Tutorial, Part 2)](https://learn.microsoft.com/en-us/cpp/atl/adding-a-control-atl-tutorial-part-2?view=msvc-170)
* Content Source: [docs/atl/adding-a-control-atl-tutorial-part-2.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/atl/adding-a-control-atl-tutorial-part-2.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @makelyblakley, I wish I had time to come back and update that tutorial someday, but our resources are directed towards documenting new C++ standard library features that are implemented but not documented yet.
