### ISSUE TITLE
Insufficient documentation for warning C4770

### ISSUE THREAD

**Issue by danieljennings** [MicrosoftDocs/cpp-docs#4253]
The only documentation for warning C4770 is the re-statement of the message on this page.

Can I request some more details about that warning, since I've started seeing it in one of our projects and don't know what it means or what the implications are.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b453bef-7a9d-b904-16cd-1c575d8e34f9
* Version Independent ID: 5e564e6f-2ac2-d898-690f-bcdd4502ed5d
* Content: [Compiler warnings C4600 Through C4799](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@danieljennings 

You'll see this warning if you cast or alias an enum value as an integral type to use as an index, but don't validate that the resulting value is non-negative and possibly also that it's <= the maximum enum value of that type. (This is what "partially validated" means in this context). This warning isn't new; it's been in the product since VS 2013, and the code that checks for the warning condition hasn't changed in at least five years. I'd be very surprised if it started appearing in code you haven't changed, unless you're upgrading from an older version than VS 2013, or enabling warnings that weren't enabled before.

**Comment by danieljennings** [comment]
Thank you! I will dig into this more tomorrow but thanks to your note re: timeframe I've found that this is occurring in a project that didn't have LTCG enabled before but had it enabled recently due to a lower-level project change. Not the sort of warning I would have predicted to come from LTCG, but now I have an explanation for how it started happening and for what it means, so thank you, @corob-msft .

**Comment by danieljennings** [comment]
I realize that this is an optional warning, but I wanted to close the loop here with why I was confused before I head out for trick or treating :) In our case we're not using it as an "index" in the strict sense of the word but we are turning two `enum`s into an integral value to use for other things. I can start to understand the warning if the intention is along the lines of "you're using an `int` derived from an `enum` and only range-checking one piece that went into that `int`", but since we aren't actually doing any "indexing" I was confused at first. (Also I initially didn't expect compiler-looking warnings to pop up after enabling `/GL` but that's less surprising the more I think about it, too.)

Here's a trimmed down repro case for what we hit, in case it's either surprising to your team that it produces the warning or somehow otherwise useful to see where it hits in real-world scenarios. In our case here we've just disabled the warning for the project in question, so it's no big deal even if nothing changes here.

```cpp
// Compiled with: /w14770 /GL

enum MyEnum_t
{
	MyEnum_A,
	MyEnum_B,
	MyEnum_C,
};

int main( const char *[], int argc )
{
    // Obviously dummy not-known-at-compile/link-time values
    const MyEnum_t nFirst = (MyEnum_t)argc;
    const MyEnum_t nSecond = (MyEnum_t)( argc + 1 );

    const int nTotal = ( nFirst + nSecond ); // <---- this line triggers C4770
    if ( nFirst <= MyEnum_B )
    {
        return nTotal;
    }

    return 0;
}
```

Again, I appreciate your (especially quick!) response here. Thank you, and have a great Halloween :)

**Comment by corob-msft** [comment]
Content is available at [Compiler Warning (level 4) C4770](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4770?view=msvc-170).

**Comment by danieljennings** [comment]
Thank you!
