### ISSUE TITLE
the second "_wcstoui64" in Syntax box is missing _l suffix

### ISSUE THREAD

**Issue by JiongWang** [MicrosoftDocs/cpp-docs#4255]
It looks to me the second "_wcstoui64" in Syntax box is missing _l suffix, you got two "_wcstoui64" inside Syntax box

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdaed1d8-0f85-4613-5625-321f4c1829f6
* Version Independent ID: 40717edb-6742-e61c-7517-0baa3e3bd61c
* Content: [_strtoui64, _wcstoui64, _strtoui64_l, _wcstoui64_l](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strtoui64-wcstoui64-strtoui64-l-wcstoui64-l?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/strtoui64-wcstoui64-strtoui64-l-wcstoui64-l.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/strtoui64-wcstoui64-strtoui64-l-wcstoui64-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@JiongWang 
You're right, thanks for the report. I'll have a fix in soon.

**Comment by TylerMSFT** [comment]
Looks like Colin addressed this in Nov of 2022.  Closing.
