### ISSUE TITLE
Description of "native" function is inadequate.

### ISSUE THREAD

**Issue by RHolton** [MicrosoftDocs/cpp-docs#4259]
The entire description of the "native" function is "Returns myname."

That is not at all helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c75fe219-1699-a208-f101-4cf493950cea
* Version Independent ID: 92f865c3-405b-59c7-ce24-14342ee8583b
* Content: [path Class](https://learn.microsoft.com/en-us/cpp/standard-library/path-class?view=msvc-170)
* Content Source: [docs/standard-library/path-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/path-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@RHolton, agreed. I added some color and a code example to show the difference (on Windows at least) between the native and generic path string.
