### ISSUE TITLE
Excelent introduction to C++ Visual Studio

### ISSUE THREAD

**Issue by GRoaM** [MicrosoftDocs/cpp-docs#426]
Excelent introduction to C++ Visual Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 417f5323-ac82-40f1-59c2-181ae9f2426a
* Version Independent ID: 153a0220-8514-3257-69fd-e190cbb3ab0a
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-1-create?view=vs-2017#add-a-source-code-file-issues)
* Content Source: [docs/build/vscpp-step-1-create.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-1-create.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks!

**Comment by pajenterprisesllc** [comment]
committee
