### ISSUE TITLE
Clarify C++ redistributable downloads supported language

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/cpp-docs#4266]
In the below mentioned page, it reads:

> This table lists the latest supported English (en-US) Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022.
> [...]
> Download other languages and versions, including versions for long term servicing release channels (LTSC), from [my.visualstudio.com](https://my.visualstudio.com/).

However, at [my.visualstudio.com](https://my.visualstudio.com/), there is no download available comprising all the above Visual Studio redistributable packages in a single file for none of the architectures.

Moreover, the downloads available at [my.visualstudio.com](https://my.visualstudio.com/) are all multilingual. So why is the download available from this page only available in US English?

Please clarify this situation in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
The doc has been updated and should be live by tomorrow afternoon.
