### ISSUE TITLE
dialog

### ISSUE THREAD

**Issue by Dr-arare** [MicrosoftDocs/cpp-docs#4268]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5dcd19ec-2f94-d529-c65e-a5daef1c1d09
* Version Independent ID: 233b3e09-b4b2-5938-7ba7-a9e164a9b0e5
* Content: [Creating a Forms-Based MFC Application](https://learn.microsoft.com/en-us/cpp/mfc/reference/creating-a-forms-based-mfc-application?view=msvc-160)
* Content Source: [docs/mfc/reference/creating-a-forms-based-mfc-application.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/creating-a-forms-based-mfc-application.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing since there's no actional feedback
