### ISSUE TITLE
Several C++ keywords are missing from this list

### ISSUE THREAD

**Issue by kengr2** [MicrosoftDocs/cpp-docs#427]
The following keywords are missing from this list, but are documented elsewhere as being supported in Visual C++: alignas, char16_t, char32_t, constexpr, and noexcept.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b34a0f-3a54-b85b-ef26-175493e5c54c
* Version Independent ID: 216f06f3-ef2f-148c-3f11-ab92e5b7d803
* Content: [Keywords (C++)](https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp?view=vs-2017)
* Content Source: [docs/cpp/keywords-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/keywords-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @kengr2 I have added the missing keywords and they should get published in a few days from now.
