### ISSUE TITLE
Environment of Build Presets and their consumption

### ISSUE THREAD

**Issue by harshakm-50063** [MicrosoftDocs/cpp-docs#4271]
Hi,

Wanted to know how and where the environment variables of build presets are used. There is a statement in this page that environment of configPresets are inherited by buildPresets (using that config). 
However, environment of buildPreset must be used somewhere? where? 

Harsha Kodnad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-160#configure-and-build)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@harshakm-50063 
That's a good question. The general answer is that the presets are used to set up the environment and parameters for a generator in a consistent way. For the details, let me refer you to the [CMake Presets documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html). We don't want to create our own version of the CMake docs, as staying in sync would be a continuous maintenance problem. Our documentation is only meant to cover how to use the CMake Presets tools in Visual Studio. For broader information about what each entry in the file is for and what it does, you need to go to the source. Thanks for asking, and best of luck with your code.
