### ISSUE TITLE
Working Resolution

### ISSUE THREAD

**Issue by ravimohan1991** [MicrosoftDocs/cpp-docs#4279]
Thanks a lot for suggesting a resolution that fits and works. 
Just want to paint the perspective picture, that the same code doesn't generate the warning with gcc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4935b51-59e1-7f9c-e803-7fcb81637146
* Version Independent ID: abbecc1f-0bf3-860d-60b9-469fe8c42055
* Content: [Compiler Warning (level 1) C4293](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4293?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4293.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4293.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by ravimohan1991** [comment]
Dear Reader, 
Thanks for speedy and almost satisfactory reply. 
I tried with ```-Wconversion``` flag (gcc running in Ubuntu) like so
```
05:09:12: Running steps for project BiosReader...
05:09:12: Starting: "/snap/bin/cmake" --build /home/the_cowboy/build-BiosReader-Desktop_Qt_6_3_0_GCC_64bit-Debug --target BiosReader
```
Although I got 47 more warnings (which is good), but it seems gcc is just fine with the bitshift gymnastic.
Also there is a stackoverflow [thread](https://stackoverflow.com/questions/3020913/shift-count-negative-or-too-big-error-correct-solution) discussing the topic in some more detail.
My interest, based on the premise, is that all compilers producing (Turing) machine code should concur and if the premise is right, then certainly either C standards is missing something or the compilers.

My 2 pennies!
A Compiler Fan

**Comment by corob-msft** [comment]
If you look for the phrase "implementation-defined" in the C and C++ standards, you'll see that implementations are given a great deal of leeway in how they behave. Compilers can pick their own sizes for `short`, `int`, and `long`, for example. It's surprisingly difficult to create code that works consistently across multiple platforms, even when all of them have a standard-conforming compiler.
