### ISSUE TITLE
Urgent Help Needed - Runtime Customization of Toolbar ToolTip for class CMDIFrameWndEx

### ISSUE THREAD

**Issue by sratneshfit** [MicrosoftDocs/cpp-docs#4280]
Hi All , 

I need step by step guide to customize the tool tip on run time 

My class is derived from CMDIFrameWndEx 

I have a ToolBar with Tooltip already implements and currently Tooltip comes from STRING TABLE OF resource file . 

Now on runtime I want to change the Tooltip for my application 

Please guide me with step by step help 

Looking to hear from floks as early as possible 

Thank You

**Comment by corob-msft** [comment]
@sratneshfit 
This issues board is for bug fixes or feature requests for the C/C++ documentation. For coding support, we recommend [Microsoft Learn Q&A](https://learn.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck with your code.
