### ISSUE TITLE
Syntax section is incorrectly listing deleted functions

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#429]
"Syntax" is listing the deleted copy constructor and assignment operator.  They cannot be used, and should not be listed under "Syntax".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0636cf1f-35f6-3ea2-0fe5-a03568fb4eb8
* Version Independent ID: ee23bcc6-494a-1498-be63-e1e2185bcae7
* Content: [once_flag Structure](https://docs.microsoft.com/en-us/cpp/standard-library/once-flag-structure?view=vs-2017)
* Content Source: [docs/standard-library/once-flag-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/once-flag-structure.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@ScotBren thanks! Fix will appear tomorrow.
