### ISSUE TITLE
All values of Compile As property should be documented

### ISSUE THREAD

**Issue by olgaark** [MicrosoftDocs/cpp-docs#4293]
Compile As property has more values now: (copy from cl.xml rule used in the property page)

```
 <Value Name="Default" DisplayName="Default" Description="Default." />
      <Value Name="CompileAsC" Switch="TC"  DisplayName="Compile as C Code" Description="Compile as C Code." />
      <Value Name="CompileAsCpp" Switch="TP"   DisplayName="Compile as C++ Code" Description="Compile as C++ Code." />
      <Value Name="CompileAsCppModule" Switch="interface "   DisplayName="Compile as C++ Module Code" Description="Compile as C++ Module Interace." />
      <Value Name="CompileAsCppModuleInternalPartition" Switch="internalPartition "   DisplayName="Compile as C++ Module Internal Partition" Description="Compile as C++ Module Internal Partition." />
      <Value Name="CompileAsHeaderUnit" Switch="exportHeader "  DisplayName="Compile as C++ Header Unit" Description="Compile as C++ Header Unit." />

```
Default is determined by file extension.
.c = Compile As C Code
.ixx and .cppm - Compile As C++ Module Interface
.h - Compile As Header Unit
everything else - Compile As C++ code

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a11fb4b4-1fcd-1e8d-7548-2442475187d9
* Version Independent ID: 3ec2f924-1608-12c7-d44a-5881db375475
* Content: [C/C++ Project Properties (Visual Studio)](https://learn.microsoft.com/en-us/cpp/build/reference/c-cpp-prop-page?view=msvc-170#scan-sources-for-module-dependencies)
* Content Source: [docs/build/reference/c-cpp-prop-page.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/c-cpp-prop-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@olgaark 
Which product version was first to expose the new property values?

**Comment by corob-msft** [comment]
@olgaark 
A fix is in and should be published tomorrow. Thanks for the report.
