### ISSUE TITLE
vcremote docs are stale, hard to use without experimentation

### ISSUE THREAD

**Issue by gkarabin** [MicrosoftDocs/cpp-docs#4295]
My team builds native cross-platform libraries for use in our Xamarin and MAUI apps using Visual Studio. We currently build using Visual Studio 2019 and are in the process of migrating releases for next year to Visual Studio 2022.

The instructions on this page are very dated - it seems to me that they are set up to become obsolete quickly.

1. The instructions indicate that one should install "[Node.js](https://nodejs.org/) version 12.14.1 and npm version 6.13.4", but provide a link to the nodejs home page that has long since buried that release.  A direct link to https://nodejs.org/download/release/v12.14.1/node-v12.14.1.pkg would be easier for people to use.  For people on enterprise-managed computers, the installer is not a great choice because it cannot be validated by MacOS, and a privileged user has to grant access.  In that case, it might make sense to build instructions around a non-package installer like https://nodejs.org/download/release/v12.14.1/node-v12.14.1-darwin-x64.tar.gz - better yet, it would be nice to see the software be updated to support more modern / secure node builds.

2. Actually installing vcremote with that version of node (or a more modern one) installs vcremote 1.0.19. Running that version with this document's instructions does not generate a PIN - instead it generates a certificate that has to be installed on the remote Windows computer. Neither Visual Studio 2019 or Visual Studio 2022 seem to have a way to pair to a Mac - when setting secure pairing a PIN is required.

```
% vcremote
Copyright (C) 2014 Microsoft Corporation. All rights reserved.
1.0.19

VC build library initialized.
Verifying lldb-mi for debugging is installed under path: /usr/local/lib/node_modules/vcremote/node_modules/vcremote-lib/debugger
lldb-mi is installed.
Use the following information under Tools, Options, Cross Platform, iOS, then press Pair:

Host Name: HONC02XR4APJGH6
Port: 3030
Secure: [x]
Move server certificate to Visual Studio machine.
Server Certificate Path: /Users/georgekarabin/vcremote/certs/server-cert.pem

Remote build server listening on [https] port 3030
```

3. If I instead opt to use the insecure mode of operation, vcremote logs an error and fails to pair when I connect from Visual Studio 2019 (16.11.21):

```
% vcremote --secure false
vcremote
Copyright (C) 2014 Microsoft Corporation. All rights reserved.
1.0.19

VC build library initialized.
Verifying lldb-mi for debugging is installed under path: /usr/local/lib/node_modules/vcremote/node_modules/vcremote-lib/debugger
Remote build server listening on [http] port 3030
lldb-mi is installed.
GET / 500 8.639 ms - 2051
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.readdirSync (fs.js:849:10)
    at isClientAuthorized (/usr/local/lib/node_modules/vcremote/lib/server.js:205:38)
    at /usr/local/lib/node_modules/vcremote/lib/server.js:38:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/vcremote/node_modules/express/lib/router/index.js:280:10)
    at logger (/usr/local/lib/node_modules/vcremote/node_modules/morgan/index.js:144:5)
```

Finally, and _**not completely related to this ticket**_, I attempted to work around this issue by using npm to install an older vcremote using `npm install -g vcremote@1.0.16`. It manages to pair, but it seems that the current versions of Visual Studio 2019 (16.11.21) and Visual Studio 2022 (17.4.0) both fail to build my iOS project when connected to vcremote. The issue seems to be related to Shared C++ projects, where some files and projects specified in Visual Studio use relative paths "..\...\some_other_project\foo.cpp", for instance. Those files are not copied to the remote Mac, and the build fails when trying to compile them. Files that are instead referenced absolutely using build variables like "$(SolutionDir)\some_other_project\foo.cpp" are copied to the Mac and build just fine. An older version of Visual Studio 2019 installed on an old build node (16.7.5) builds the same source code with no issues, even if files and projects are referenced relatively. You might run into this if you are trying to update these documents. I think I am going to need to file another issue, but haven't put together an easy reproduction for it yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 979a9ec0-92ff-f30b-7450-1f1f4aa71007
* Version Independent ID: c4f5878e-3e7d-7303-e4f6-db07489cff9b
* Content: [Install and configure tools to build using iOS](https://learn.microsoft.com/en-us/cpp/cross-platform/install-and-configure-tools-to-build-using-ios?view=msvc-170&source=docs)
* Content Source: [docs/cross-platform/install-and-configure-tools-to-build-using-ios.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cross-platform/install-and-configure-tools-to-build-using-ios.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gkarabin 
Thanks for the detailed report. An updated doc is in the works, along with updates to the tools in the latest preview version of Visual Studio 2022 version 17.5 Preview 1.

@DavidARaygoza for awareness.

**Comment by gkarabin** [comment]
Thanks. Is there any likelihood of also fixing the issue on a LTS branch of Visual Studio 2019? 

We have a number of hurdles to solve to move to Visual Studio 2022. If we can use a newer build of Visual Studio 2019 as a bridge, that would be ideal (from our point of view, anyway).

**Comment by corob-msft** [comment]
@gkarabin 
Product feature requests work best when made directly to the product team on [Developer Community](https://aka.ms/vsfeedback/browsecpp), which you can also get to from **Help** > **Send Feedback** > **Suggest a Feature** in the IDE. It's conceivable that changes could be made to the 16.11.*latest* version, but I wouldn't pin my hopes on it, as I expect the bar is high and mainly intended for backporting bug and security fixes.

**Comment by DavidARaygoza** [comment]
@gkarabin Thank you for reaching out. If using a Visual Studio version older than 17.5.0 Preview 1.0 please revert to vcremote version 1.0.17. If using Visual Studio version older than 17.5.0 Preview 1.0 or later it is compatible with the latest vcremote version.
By the way, the non-secure mode bug in vcremote version 1.0.19 has already been fixed and will ship soon.

**Comment by gkarabin** [comment]
@corob-msft - thanks! I understand the prioritization - I'm pleasantly surprised to see that I may not need to refactor my iOS build, so I'll stick to VS2022 and forgo filing the 2019 ticket unless a blocker comes up along the migration.

**Comment by gkarabin** [comment]
I noticed the new commit for the doc - looks good! I look forward to trying out 17.5 and using he new cert approach.

**Comment by DavidARaygoza** [comment]
@gkarabin FYI non-secure mode bug has been resolved in latest Vcremote version 1.0.21.

**Comment by gkarabin** [comment]
@DavidARaygoza - how do I try out 1.0.21? I am trying to install vcremote today and running into

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target x86_64-apple-macos10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -L/Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/EagerLinkingTBDs/Release -L/Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/Release -F/Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/EagerLinkingTBDs/Release -F/Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/Release -F/Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/_Frameworks -filelist /Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_lto.o -fobjc-arc -fobjc-link-runtime -framework MobileDevice -framework Foundation -framework CoreFoundation -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_dependency_info.dat -o /Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/Binary/ios-deploy
npm ERR! ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
npm ERR! clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gkarabin** [comment]
For what it's worth, it seems that MacOS Ventura defaults to require Xcode 14+. While supposedly Xcode 13 is not supported on Ventura, I was able to install/select Xcode 13.4.1 with https://github.com/XcodesOrg/xcodes, and then get vcremote to build as documented.

vcremote itself does not run if I select "y" at the installing homebrew prompt:

```
% vcremote               
vcremote
Copyright (C) 2014 Microsoft Corporation. All rights reserved.
1.0.24

Configuring first-run dependencies.
To deploy to physical iOS devices, or to debug a device or simulator, we need some packages from Homebrew.
Installing Homebrew may ask you for an admin password. Do you want to continue?
[y]/n? y
TypeError: child_process.exec(...).then is not a function
    at /Users/georgekarabin/.nvm/versions/node/v18.12.1/lib/node_modules/vcremote/lib/darwin/darwin-specifics.js:114:28
```

If I re-run vcremote, selecting "n", it runs as expected.

I noticed that at least some of the home-brew installs completed. I made sure these packages were not installed, ran vcremote, selected "y", and then saw that they were installed:

brew list --versions|egrep 'ideviceinstaller|libimobiledevice|usbmuxd'
ideviceinstaller 1.1.1
libimobiledevice 1.3.0
libusbmuxd 2.0.2

**Comment by DavidARaygoza** [comment]
Thank you for the feedback @gkarabin, we will look into these issues and update you.

**Comment by gkarabin** [comment]
Thanks. For what it’s worth, I noticed and commented on a similar ticket here: https://developercommunity.visualstudio.com/t/vcremote-fails-to-install/10385475?q=vcremote

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
