### ISSUE TITLE
_com_error constructor: incorrect default behavior documented

### ISSUE THREAD

**Issue by devbandido** [MicrosoftDocs/cpp-docs#4296]
The documentation states that by default, `_com_error` takes ownership of `perrinfo`  by calling `AddRef`. The default value of the `fAddRef` constructor argument states **otherwise**:

`_com_error( HRESULT hr, IErrorInfo* perrinfo = NULL, bool fAddRef=false)`

The implementation in `comdef.h` underscores this:

```
inline _com_error::_com_error(HRESULT hr,
                              IErrorInfo* perrinfo,
                              bool fAddRef) throw()
    : m_hresult(hr), m_perrinfo(perrinfo), m_pszMsg(NULL)
{
    if (m_perrinfo != NULL && fAddRef) {
        m_perrinfo->AddRef();
    }
}
```

Can the documentation be corrected?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbe35be2-3626-287a-b1f3-d9263d0ced08
* Version Independent ID: b9e0169f-9a9a-93af-f54f-44fd7e2ac0b5
* Content: [_com_error::_com_error](https://learn.microsoft.com/en-us/cpp/cpp/com-error-com-error?view=msvc-170)
* Content Source: [docs/cpp/com-error-com-error.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/com-error-com-error.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by devbandido** [comment]
It seems that the issue has already been reported a couple of years ago: #2128

**Comment by corob-msft** [comment]
@devbandido 
You are correct, as was @Dirksche. A fix is in the works and should be available tomorrow.
