### ISSUE TITLE
What is the purpose of the 2nd bullet point in "Parsing C++ command-line arguments", given that argv[0] never uses double quotes ('')?

### ISSUE THREAD

**Issue by jabelloc** [MicrosoftDocs/cpp-docs#4298]
### 2nd bullet-point in "[Parsing C++ command-line arguments](https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170#parsing-c-command-line-arguments)":

`The first argument (`argv[0]`) is treated specially. It represents the program name. Because it must be a valid pathname, parts surrounded by double quote marks (") are allowed. The double quote marks aren't included in the `argv[0]` output. The parts surrounded by double quote marks prevent interpretation of a space or tab character as the end of the argument. The later rules in this list don't apply.`

I know that the double quote marks aren't included in the `argv[0]` output, **but the characters themselves, stored in memory at the address given by `argv[0]`, never seem to show double quotes**. So, what is the reason for the paragraph above?

I have used the "[Example of command-line argument parsing](https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170#example-of-command-line-argument-parsing)" to arrive at my conclusion:

```
// command_line_arguments.cpp
// compile with: /EHsc
#include <iostream>

using namespace std;
int main( int argc,      // Number of strings in array argv
          char *argv[],   // Array of command-line argument strings
          char *envp[] )  // Array of environment variable strings
{
    int count;

    // Display each command-line argument.
    cout << "\nCommand-line arguments:\n";
    for( count = 0; count < argc; count++ )
         cout << "  argv[" << count << "]   "
                << argv[count] << "\n";
}
```
The results I have obtained for `argv[1]`, `argv[2]` and `argv[3]` were equivalent to the results shown in the section "[Results of parsing command lines](https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170#results-of-parsing-command-lines)", but as I wrote before, the characters contained in `argv[0]` for each one of those processes, didn't have a double quote ('') in the string of characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0c5ec8f-dc90-d0bd-5aa5-1340ccc877c3
* Version Independent ID: 19646aca-3da3-14e8-ea9a-fcb3020cf51c
* Content: [`main` function and command-line arguments (C++)](https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170)
* Content Source: [docs/cpp/main-function-command-line-args.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/main-function-command-line-args.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jabelloc 
The bullet point is meant to draw a distinction between the double-quote processing of the program name and double-quote processing for the rest of the arguments, which is more complex. It isn't possible to create an executable with a double-quote character in the name, so the more complex rules aren't needed. There isn't an easy way to illustrate it, but here's an example of a program name in quotes, using your example code, with the executable renamed to "command line args.exe":

```cmd
C:\test\command_line_args>"command line args.exe" arg1 "arg 2" "arg ""3"""

Command-line arguments:
  argv[0]   command line args.exe
  argv[1]   arg1
  argv[2]   arg 2
  argv[3]   arg "3"
```

The example shows the extra processing done for the `argv[3]` value, which isn't done for the executable name because it isn't needed.
