### ISSUE TITLE
No "CLR Empty Project"

### ISSUE THREAD

**Issue by stevebroshar** [MicrosoftDocs/cpp-docs#4300]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f38955a-ed30-202b-1131-ad1f3f99fd57
* Version Independent ID: 1e47e2ee-6c4f-ef6c-eba9-8b2b2b754347
* Content: [How to: Create CLR Empty Projects](https://learn.microsoft.com/en-us/cpp/dotnet/how-to-create-clr-empty-projects?view=msvc-170)
* Content Source: [docs/dotnet/how-to-create-clr-empty-projects.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/dotnet/how-to-create-clr-empty-projects.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
No actionable feedback (it's blank). Closing.

**Comment by TylerMSFT** [comment]
I see - your subject is supposed to be the feedback.
In VS 2022, in the Create a new project dialog, type CLR into the search box and you'll see the CLR Empty Project project type.

**Comment by TylerMSFT** [comment]
@stevebroshar, thanks for clarifying. On my side, the feedback form is blank. I take your point about indicating how to install the template. I'll add that.

**Comment by TylerMSFT** [comment]
@stevebroshar, I added some text regarding what to do if the template doesn't appear, and a link to instructions to install the templates. Should be live by tomorrow afternoon (12/6)
