### ISSUE TITLE
/QSpectre is supported fgor debug builds now

### ISSUE THREAD

**Issue by paddymcd-MSFT** [MicrosoftDocs/cpp-docs#431]
As per April update to VCBlog post on /Qspectre - https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/

 
"Update 4 April 2018 With Visual Studio 2017 version 15.7 Preview 3 we have two new features to announce with regards to our Spectre mitigations. First, the /Qspectre switch is now supported regardless of the selected optimization level. Second, we have provided Spectre-mitigated implementations of the Microsoft Visual C++ libraries. See below for details."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad87698-8cd7-aaf9-87b1-eaf8c290017f
* Version Independent ID: be796703-261a-ec99-11e6-d023aa7ee849
* Content: [/Qspectre](https://docs.microsoft.com/en-us/cpp/build/reference/qspectre?view=vs-2017)
* Content Source: [docs/build/reference/qspectre.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/qspectre.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@corob-msft. I made a stab at updating this per the blog post.

**Comment by mikeblome** [comment]
fixed. @paddymcd-MSFT thanks!
