### ISSUE TITLE
x64 register usage documentation should cover ZMM registers

### ISSUE THREAD

**Issue by BruceForstall** [MicrosoftDocs/cpp-docs#4310]
The x64 register usage documentation, as well as other x64 ABI and calling convention documentation, should cover the AVX-512 ZMM registers (including the additional registers ZMM16-ZMM31).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7052f5eb-e592-2920-e58a-30a6d4bbc3b8
* Version Independent ID: dfe35b76-1b05-7914-70a8-e35e17ef6624
* Content: [x64 ABI conventions](https://learn.microsoft.com/en-us/cpp/build/x64-software-conventions?view=msvc-170#x64-register-usage)
* Content Source: [docs/build/x64-software-conventions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/x64-software-conventions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
