### ISSUE TITLE
No information about deprecation

### ISSUE THREAD

**Issue by UrzaSL** [MicrosoftDocs/cpp-docs#4317]
This function is deprecated, but article doesn't mention that, neither provide info on what function(s) to be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0534e0f-1550-6652-e1da-74c1a766b3f0
* Version Independent ID: 87d4edc0-d837-6b83-c63d-1d7c49d6ff0a
* Content: [memset, wmemset](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/memset-wmemset?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VCRUNTIME_STRING%252Fmemset)%3Bk(memset)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/memset-wmemset.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/memset-wmemset.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@UrzaSL 

Thanks for the report. I haven't seen evidence the `memset` function is deprecated by either the [latest C23 draft](https://open-std.org/JTC1/SC22/WG14/www/docs/n3054.pdf), or in the [C++23 draft standard](https://isocpp.org/files/papers/N4910.pdf), either. As far as I can tell, only the `asctime` and `ctime` functions are officially deprecated. `memset` isn't deprecated in MSVC, which currently supports C17, but doesn't fully support C23 yet. The C23 standard `memset_explicit` or `memset_s` functions, not yet implemented in MSVC, could be used instead. The docs reflect the current state of affairs in MSVC. I can't officially say when C23 support will ship. Until it does, and if `memset` actually becomes deprecated, this isn't an issue we can address in the docs, so I'm closing it.
