### ISSUE TITLE
A few minor issues in "Standard library named module considerations"

### ISSUE THREAD

**Issue by davidhunter22** [MicrosoftDocs/cpp-docs#4319]
These a comment about the "Standard library named module considerations" section

1) It states "Don't mix and match importing header units and name modules. That is, don't `#include <vector>` and `import std;` in the same file, for example." This should say header files not header units.

2) You should probably also say that old "C" style headers are fine to use, so don't use `<cmath>` but `<math.h>` is OK

3) You should also add `<version>` to the standard library headers you may wany to include, it contains the feature macros which you can't get from the `std` module

4) It says "If you need to use the errno macro, `#include <assert.h>`. Because named modules don't expose macros, this is the workaround if you need to check for errors from `<cmath>` functions." It should say use `<errno.h>`, `<assert.h>` may or may not pull in `<errno.h>`. In the same paragraph you say "this is the workaround if you need to check for errors from `<cmath>` functions". You should probably say `<math.h>` and also `errno` is used for far more than just math functions.

5) It says "INT_MIN is defined by `<limits.h>` and `<climits>` and works with header files/header units." You should probably not mention `<climits>` which encourages people to pull in headers that use the std namespace. Also, you should probably say "INT_MIN and may other math related macros like NAN and INFINITY" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Version Independent ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Content: [Tutorial: Import the standard library (STL) using modules (C++)](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
* Content Source: [docs/cpp/tutorial-import-stl-named-module.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/tutorial-import-stl-named-module.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@davidhunter22, thank you for the great feedback. Really appreciate you taking the time. I have updated the topic, which will be live Monday. 

I addressed INT_MIN, NAN, etc. slightly differently than you suggested. I added text that you can instead `import std;` and use `numeric_limits` which supercede those macros with things such as: std::numeric_limits<int>::min(), numeric_limits<double>::quiet_NaN(), etc.

I didn't mention including <version> because while in theory it will bring in feature-test macros, in practice it will duplicate one of the STL's central internal headers. We don't presently recommend that.

Thanks again for taking the time to read the docs and offer suggestions. The changes I made to address this feedback will show up by Monday afternoon or so (Pacific Standard Time).

**Comment by davidhunter22** [comment]
<version> If you don't recommend including <version> that's find but I think you need to say what you are meant to do instead. In partice many code bases, and probably more in future use the feature testing macros.

I agree using numeric_limits<double>::quiet_NaN() and friends are the correct way to go. However this requires people to start modifying implementation code rather than just tinkering with headers, maybe say do that but also give the short term work around as well.

I forgot one thing. There are a number of functions like printf_s and gmtime_s. These are defined in Annex K of the C standard, https://open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm. They are explicity excluded from the std namespace and therefore not in the std module. You need to include C headers to get them.

Note I did a port of the type_safe library and am doing github, see https://github.com/catchorg/Catch2/issues/2575 for my write up.

**Comment by davidhunter22** [comment]
Thinking more I would suggest a "How to port a code base to using the standard library module" page in you documentation.

Also not sure if you wantt o mention it but there is a bug in the VC compiler that hoists names like uint8_t back into the global namespace if you use `import std;` which can be very suprising. Cameron DaCamara  said  "The underlying technical problem cannot be easily solved without rearchitecting how name lookup works, which is an insanely risky change but necessary to fix the problem."

**Comment by TylerMSFT** [comment]
@davidhunter22, thank you for the comments. The idea for a porting guide is a good one. I'm drowning in good ideas, though, so it will be a bit before I can get there :-)

**Comment by davidhunter22** [comment]
Do you want me to have a go at writing a porting guide?
I think the main issue would be how much it would mention current issues
rather than some ideal future world.

**Comment by TylerMSFT** [comment]
I think that would be a fine idea :-)
