### ISSUE TITLE
The Compiler Should Issue Warning

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [MicrosoftDocs/cpp-docs#432]
The %n format specifier is standard in C99. The compiler should not silently build code using %n only to let the runtime fail. A conforming implementation should support the usage or issue a diagnostic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f465b1-da07-d877-9872-b6e12159522f
* Version Independent ID: 00f52d5b-64d7-c66b-30e5-038efded5cf6
* Content: [_set_printf_count_output](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-printf-count-output?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/set-printf-count-output.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/set-printf-count-output.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@QwazyWabbitWOS Yes, I agree, the lack of a diagnostic for a silently ignored %n in your format string seems like an obvious omission. I don't think it's a documentation omission, though, as that's the whole point of this particular topic.

Adding a new warning is a suggestion you should make to the product team. You can reach them through developercommunity.visualstudio.com, on the [C++ Questions](https://developercommunity.visualstudio.com/spaces/62/index.html) page. Feel free to tell them I sent you. Be sure to mention that this is also a C++ issue, not just a C issue, and the %n parameter was part of the C89 specification as well.
