### ISSUE TITLE
Android developer associate

### ISSUE THREAD

**Issue by Nachiketa-Sharma** [MicrosoftDocs/cpp-docs#4324]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b965be6-8dfd-db91-84e3-345e70d7c302
* Version Independent ID: 291bf1e4-c8f7-12e9-3f38-f54bbd822bc7
* Content: [Create an Android Native Activity App](https://learn.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app?source=recommendations&view=msvc-170)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Nachiketa-Sharma** [comment]
Never let this github away from me, please all of you.

**Comment by corob-msft** [comment]
@Nachiketa-Sharma, I'm closing your issue because it has no actionable content. If you have a documentation issue to report, please create it from the relevant page in the feedback section. Thanks!
