### ISSUE TITLE
_fpclass and fpclassify documentation doesn't specify behavior of denormal inputs under DAZ

### ISSUE THREAD

**Issue by arsenm** [MicrosoftDocs/cpp-docs#4328]
The documents for _fpclass and fpclassify don't state the behavior if the floating point mode is set to treat input denormals as zero. This could plausibly read a canonicalized input and treat them as 0, or could not observe the FP mode and classify as denormal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0fda8-1ab9-7167-47ab-fe1ca34dacf7
* Version Independent ID: acd97ebc-b0b4-55c6-5a50-118ada185654
* Content: [_fpclass, _fpclassf](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fpclass-fpclassf?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/fpclass-fpclassf.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/fpclass-fpclassf.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.

**Comment by arsenm** [comment]
Do not close issues for the sake of closing issues. It's highly disrespectful to anyone who takes the time to submit something  actionable

**Comment by arsenm** [comment]
> If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.

Non-project members also cannot re-open issues

**Comment by TylerMSFT** [comment]
Hi, no disrespect intended. I've captured this issue and added it to my work queue. What I'm doing is in advance of GitHub issues being turned off and non-operative for the C++ doc content. Which isn't my decision. I don't want to lose issues people have taken the time to log. So, I ported this to a place where I won't lose it.
