### ISSUE TITLE
Difference between the flag /arch and -march 

### ISSUE THREAD

**Issue by manickavela29** [MicrosoftDocs/cpp-docs#4329]
What is the difference between the flags **/arch** and **-march**
I have a C++ project on a AMD machine and i want to set the flag **-march=znver2**(a flag supported by GCC).
Would I be able to get the same result with setting **/arch:avx2**
or Should I set both the flags when I am compiling in windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba360ffb-9bd7-1f1d-59a6-2470e73b5e0f
* Version Independent ID: 9547430b-2596-7d71-89e0-fbbafe187160
* Content: [/arch (x86)](https://learn.microsoft.com/en-us/cpp/build/reference/arch-x86?source=recommendations&view=msvc-170)
* Content Source: [docs/build/reference/arch-x86.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/arch-x86.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@manickavela29 
Technical questions about other compilers' options are a bit outside of our scope, so I'm closing this issue. MSVC doesn't provide the fine-grained instruction-set control over code generation that would let you specifically select AMD Zen 2 output. To the extent that AVX-512 and Zen2 instructions overlap, /arch:AVX512 will cover the common set. I don't have any other details available to share. Hope this helps.
