### ISSUE TITLE
Errors in the example

### ISSUE THREAD

**Issue by kaczorrrro** [MicrosoftDocs/cpp-docs#433]
First problem with this example it that it doesn't compile, since MyFunc is a member of MyClass (btw using class is unnecessary, and clutters the example). Even after moving MyFunc out of class body, the example still doesn't work.
In no case can char c be &gt; numeric_limits&lt;char&gt;::max(), since max() means biggest possible char. In current example, function call converts (implicit int constant) 256 into char, turning it into 0 (due to bit representation, but in general this is an undefined behavior). And since 0 &gt; max() is false, no expection is thrown.
To make this example functional, argument to MyFunc should be of type int.

Here is my corrected version
```
#include &lt;stdexcept&gt;  
#include &lt;limits&gt;  
#include &lt;iostream&gt;  

using namespace std;    
   void MyFunc(int c)  
   {  
      if(c &gt; numeric_limits&lt;char&gt;::max())  
         throw invalid_argument("MyFunc argument too large.");  
      //...  
   }

int main()  
{  
   try  
   {  
      MyFunc(256); //cause an exception to throw  
   }  

   catch(invalid_argument& e)  
   {  
      cerr &lt;&lt; e.what() &lt;&lt; endl;  
      return -1;  
   }  
   //...  
   return 0;  
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [Errors and Exception Handling (Modern C++)](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=vs-2017)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@kaczorrrro thanks very much. your fix will appear tomorrow.
