### ISSUE TITLE
_findFirst documentation could be clearer regarding when to call _findclose

### ISSUE THREAD

**Issue by Mike4Online** [MicrosoftDocs/cpp-docs#4334]
In the documentation for `_findFirst`, the **Remarks** section begins:

> You must call `_findclose` after you're finished with either the `_findfirst` or `_findnext` function (or any variants).

I suggest an edit (below, **in bold**) to make this clearer and more precise:

> You must call `_findclose` after you're finished with either the `_findfirst` or `_findnext` function (or any variants) **provided the `_findfirst` call succeeded and returned a valid handle**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6203d9-4a2d-5a6b-ad1a-e2d9a5356628
* Version Independent ID: c3214724-4556-986c-6859-e5188d00959b
* Content: [_findfirst, _findfirst32, _findfirst32i64, _findfirst64, _findfirst64i32, _findfirsti64, _wfindfirst, _wfindfirst32, _wfindfirst32i64, _wfindfirst64, _wfindfirst64i32, _wfindfirsti64](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/findfirst-functions?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/findfirst-functions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/findfirst-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Mike4Online , good suggestion. I've added some text very close to your suggestion and it will appear in the docs by EOD Monday 12/12. Thanks for taking the time to suggest the improvement.

**Comment by Mike4Online** [comment]
That was fast.

Thanks!
