### ISSUE TITLE
VC redist installers command line option documentation?

### ISSUE THREAD

**Issue by DaveInCaz** [MicrosoftDocs/cpp-docs#4345]
So far I have not been able to find a page on https://learn.microsoft.com/ which documents the command line options for the VC redist installers.

The page here or at least this overall section seems like it would be the right place for this information. Or maybe on https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 in case the options varied with older versions.

I can see that posts like https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c3efcec4-d4a1-4eee-ac2c-43ce9c892913/how-to-install-vc-redistributable-package-silently?forum=vssetup do seem to contain this information, but its not very authoritative and obviously won't be up to date.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfdd5052-e8a5-633e-3c31-74e5ac664917
* Version Independent ID: 1f1321f2-8de8-80a9-fa29-06c71c71d573
* Content: [Redistributing Visual C++ Files](https://learn.microsoft.com/en-US/cpp/windows/redistributing-visual-cpp-files?view=msvc-170)
* Content Source: [docs/windows/redistributing-visual-cpp-files.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/redistributing-visual-cpp-files.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DaveInCaz 
Thanks for the report. It surprised me that there's apparently never been such documentation for the Redistributable. You'll find a very brief introduction now in the article.
