### ISSUE TITLE
RETURN

### ISSUE THREAD

**Issue by king1234east** [MicrosoftDocs/cpp-docs#4348]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3bc1075-0be8-2629-89ef-537720fa186c
* Version Independent ID: 956b457a-f537-0b12-7d04-78d96e77adbe
* Content: [return Statement (C)](https://learn.microsoft.com/en-us/cpp/c-language/return-statement-c?view=msvc-170)
* Content Source: [docs/c-language/return-statement-c.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/return-statement-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@king1234east 
I can't tell what you've found a problem with in the documentation from the title and description you've provided, so I'm closing this issue. If you can be more specific, I can reopen it to address the problem.
