### ISSUE TITLE
Document seems incorrect or unclear about macros in paths

### ISSUE THREAD

**Issue by solvingj** [MicrosoftDocs/cpp-docs#435]
"The Visual C++ project system currently does not support macros in project item paths. "

We use them regularly in our project and props files, for example, the following works: 

`<ClCompile Include="$(MSBuildThisFileDirectory)src\somefile.c" />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7beb1d6-9b03-5440-1dd3-99148a22d5cc
* Version Independent ID: 080c3597-2275-a711-d265-c6d7f41db618
* Content: [.vcxproj and .props file structure](https://docs.microsoft.com/en-us/cpp/ide/vcxproj-file-structure?view=vs-2017)
* Content Source: [docs/ide/vcxproj-file-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/vcxproj-file-structure.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by solvingj** [comment]
Also, since that seems to be incorrect, I've just tested the following other statement from that post: 
> The Visual C++ project system currently does not support wildcards in project items. For example, this is not supported:  `<ClCompile Include="*.cpp"/>`

Again, I found this to be false in our case.

**Comment by mikeblome** [comment]
Investigating.

**Comment by mikeblome** [comment]
@solvingj This is the response from the C++team: 

"Not supported" means that we don’t guarantee it working for all operations in the IDE. 

The macros which don’t change their value in different configurations should be fine most of the time, but might not be preserved when an item is moved to a different filter or project.

The macros which change their value for different configurations will cause more trouble as we don’t expect project items paths to be different for different project configurations
