### ISSUE TITLE
Examples and output are incorrect

### ISSUE THREAD

**Issue by trong8820** [MicrosoftDocs/cpp-docs#4356]
[Enter feedback here]

cout << "f[0] = " << f[0] << ", f[1] = " << f[1] << endl;
cout << "f[1] = " << f[1] << ", f[3] = " << f[3] << endl;

Duplicate f[1]

f[0] = -1, f[1] = -2
f[2] = -3, f[3] = 3

Output f[3] = 0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5016d5f7-462a-5ff9-bb3c-b98984709c13
* Version Independent ID: 5878a982-5ab2-c456-8f1d-0b2d55a6db09
* Content: [_mm_stream_ss](https://learn.microsoft.com/en-us/cpp/intrinsics/mm-stream-ss?view=msvc-170)
* Content Source: [docs/intrinsics/mm-stream-ss.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/mm-stream-ss.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@trong8820 
Thanks for letting us know. A fix should be available sometime tomorrow.
