### ISSUE TITLE
Example not in accordance with code implementation

### ISSUE THREAD

**Issue by DevMatSolutions** [MicrosoftDocs/cpp-docs#4365]
Example is totally wrong and adds confusion

```
void MultiRowSet::DoBulkFieldExchange( CFieldExchange* pFX )
{
   // call the Bulk RFX functions
   // for field data members
   pFX->SetFieldType( CFieldExchange::outputColumn );
   RFX_Long_Bulk( pFX, _T( "[colRecID]" ),
                  &m_rgID, &m_rgIDLengths );
   RFX_Text_Bulk( pFX, _T( "[colName]" ),
                  &m_rgName, &m_rgNameLengths, 30 );

   // call the RFX functions for
   // for parameter data members
   pFX->SetFieldType( CFieldExchange::inputParam );
   RFX_Text( pFX, "NameParam", m_strNameParam );
}
```

Please check again the calls while binding parameters during Bulk implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30cbc2-f3b4-3375-2746-67fc16b2ee59
* Version Independent ID: 0b637418-7f7c-352f-df18-e1933f0820d7
* Content: [Recordset: Fetching Records in Bulk (ODBC)](https://learn.microsoft.com/en-us/cpp/data/odbc/recordset-fetching-records-in-bulk-odbc?view=msvc-170)
* Content Source: [docs/data/odbc/recordset-fetching-records-in-bulk-odbc.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/data/odbc/recordset-fetching-records-in-bulk-odbc.md)
* Product: **visual-cpp**
* Technology: **cpp-data**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
@DevMatSolutions , if you have any suggestions you'd like to make, I'd be happy to incorporate them.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
