### ISSUE TITLE
Did not compile.

### ISSUE THREAD

**Issue by makelyblakley** [MicrosoftDocs/cpp-docs#4369]
C++ amp.h did not compile because it is depreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec054a56-bc4a-198e-6fc1-8a9fbb78c2c2
* Version Independent ID: 0bb33ae4-3fb1-8683-b3c2-6773e3b20cfb
* Content: [Walkthrough: Debugging a C++ AMP application](https://learn.microsoft.com/en-us/cpp/parallel/amp/walkthrough-debugging-a-cpp-amp-application?view=msvc-170)
* Content Source: [docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I'll check to see if it has a deprecation notice.

**Comment by TylerMSFT** [comment]
I updated the tutorials with a notice about the deprecated AMP headers. Also added the suggestion to define `_SILENCE_AMP_DEPRECATION_WARNINGS` before including any AMP headers to silence the warnings.  Will be live by end of day tomorrow (1/24).
