### ISSUE TITLE
Missing `Output` section

### ISSUE THREAD

**Issue by md-pix4d** [MicrosoftDocs/cpp-docs#4372]
The section regarding `vector<bool>::operator[]` contains an example with a code excerpt containing `std::cout` statements, however there is no display of the expected output when running the code. That would be quite helpful to add.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44ef310b-8a0f-0788-739b-b7890aedb17f
* Version Independent ID: 0175f823-7354-7661-8d88-35e0566c3e84
* Content: [vector&lt;bool&gt; Class](https://learn.microsoft.com/en-us/cpp/standard-library/vector-bool-class?view=msvc-170)
* Content Source: [docs/standard-library/vector-bool-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/vector-bool-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @md-pix4d, thank you for taking the time to log this issue. I've added the output section and it should be live by EOD tomorrow (Fri).
