### ISSUE TITLE
example doesnt call _pclose

### ISSUE THREAD

**Issue by JeffMill** [MicrosoftDocs/cpp-docs#4384]
Code example should call _pclose() when done with pipe.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b85181a9-588c-8ec0-a1b6-ffc18fc8856b
* Version Independent ID: 55212126-bfa9-d3ed-202b-1c27e2ad3689
* Content: [_popen, _wpopen](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/popen-wpopen.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/popen-wpopen.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @JeffMill, I fixed the code sample to call _pclose() in all code paths instead of just the success case.
Should be live by end of day tomorrow, 1/26/2023. Thanks for helping improve the docs!
