### ISSUE TITLE
How to set for Intel oneAPI compilers, otherwise, how to source environment variables in build terminal.

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/cpp-docs#4386]
Using Intel oneAPI may be outside the scope of Linux configuration for Microsoft, but being able to source the build environment should be possible and documented.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a Linux MSBuild C++ project in Visual Studio](https://learn.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=msvc-170)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
