### ISSUE TITLE
C6001 Incorrect when analyzing test of Pointer && Pointer[x] in VS2022

### ISSUE THREAD

**Issue by drankinatty** [MicrosoftDocs/cpp-docs#4387]
This is a follow-on to the earlier from VS2017 described here [C6011 Incorrect when analyzing double-pointer for dereference of NULL](https://github.com/MicrosoftDocs/cpp-docs/issues/3596) where in that case a logic issue generated a proper warning on the line:

```c
   for (size_t i = 0; tokens[i]; i++) {  /* loop until sentinel NULL */
```

The logic issue was corrected by first including a check of the pointer `tokens` and only continuing to dereference the pointer (`tokens[i]`) if `tokens` is non-`NULL`., e.g.

```c
   for (size_t i = 0; tokens && tokens[i]; i++) {  /* loop until sentinel NULL */
```
Despite the logic correction, VS2022 continues to display a Yellow Triangle warning at this point. The warning being:

```none
Warning	C6001	Using uninitialized memory '*tmp'.	PathTokens	C:\Users\david\source\repos\PathTokens\PathTokens\PathTokens.c	67	
```

The VS2022 version information is:

```none
Microsoft Visual Studio Community 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
```

The warning is incorrect. The code is the same as in the prior issue with the logic corrected and is a simple program that displays the `path` from the environment on either Linux or Windows. The full code is included below:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

#if defined (_WIN64) || defined (_WIN32)
#define PREFIX "Path="  /* constants for PREFIX and DELIM on windows */
#define DELIM ";\r\n"
#else
#define PREFIX "PATH="  /* constants for PREFIX and DELIM on Linux */
#define DELIM ":\n"
#endif

int main(int argc, char** argv, char** env)
{
    char path[PATH_MAX] = "",               /* storage for copy of environment string */
        *p = path,                          /* pointer - general use */
        **tokens = NULL;                    /* pointer to pointer for path components */

    size_t  prefixlen = strlen (PREFIX),    /* prefix length */
            ndx = 0;                        /* path tokens index */

    for (int i = 0; env[i]; i++) {          /* find PREFIX in environment */
#ifdef DEBUG
        puts (env[i]);
#endif
        if (strncmp (env[i], PREFIX, prefixlen) == 0) {
            strcpy (p, env[i] + prefixlen); /* copy path from env to path */
            break;
        }
    }

    if (!*p) {  /* if PREFIX not found */
        fprintf(stderr, "error: '%s' not found in environment.\n", PREFIX);
        return 1;
    }

    puts ("\nfull path:\n");    /* show full path to create tokens from */
    puts (p);

    /* loop moving ep (end-pointer) to next DELIM in p or last token */
    for (p = strtok(p, DELIM); p; p = strtok(NULL, DELIM)) {
        size_t  len = strlen(p);            /* length of token */
        /* realloc pointers using temporary pointer
         * adding two more than index to set sentinel NULL as last pointer
         * (sentinel NULL is optional, just add 1 if not wanted)
         */
        void *tmp = realloc(tokens, (ndx + 2) * sizeof * tokens);
        if (!tmp) {                                 /* validate realloc */
            perror("realloc-tokens");
            break;
        }
        tokens = tmp;                               /* assign new block to tokens */
        tokens[ndx + 1] = NULL;                     /* set sentinel NULL */
        if (!(tokens[ndx] = malloc (len + 1))) {    /* allocate/validate string storage */
            perror("malloc-tokens[ndx]");
            break;
        }
        memcpy (tokens[ndx++], p, len + 1);         /* copy path component */
    }

    puts ("\npath components:\n");                  /* output separated tokens */
    for (size_t i = 0; tokens && tokens[i]; i++) {  /* loop until sentinel NULL */
        puts (tokens[i]);
        free (tokens[i]);                           /* free string storage */
    }
    free (tokens);                                  /* free pointers */

    (void)argc;     /* cast to prevent -Wunused warnings */
    (void)argv;
}
```

Specifically, `tokens` is initialized `NULL` when defined, then in the tokenization loop, `tokens` is reallocated with `realloc()` which will either succeed or return `NULL`, and if it succeeds, storage for the path component is created with `malloc()` which will either succeed or fail returning `NULL`. Regardless of which occurs, `tokens` is validly initialized either `NULL` or with a valid memory address.

Worth noting the C6001 warning refers to the variable `tmp` used to ensure the existing pointer address is not overwritten in the event `realloc()` fails returning `NULL` -- and which went out of scope upon exit of the tokenization block.

The crux of the issue is the test `tokens && tokens[i]` ensures `tokens` is not `NULL` prior to the test of `tokens[i]`. If `tokens` is `NULL`, there is no access of `tokens[i]`.  `tokens[i]` itself is a pointer that either holds a valid memory address or `NULL` in the case `malloc()` fails. In either case it does not represent a C6001 uninitialized variable. The intellisense warning should not be present.

Let me know if you need any additional information.

**Comment by corob-msft** [comment]
@drankinatty 

Thanks for the report. From your description, this appears to be a product issue in code analysis, rather than a documentation issue, so I'm closing it. I recommend raising the issue instead in the C++ [Developer Community](https://aka.ms/vsfeedback/browsecpp) forum. That's where the development team looks for issues. We here on the docs team also find product issues from time to time (since we're often the first to try out new features), and the dev team wants us to report them the same way. For more info on reporting issues, see [How to report a problem](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset). If I'm wrong, and this is something to be fixed in the documentation, then let me know, and I'll reopen the issue.

**Comment by drankinatty** [comment]
Thank you -- I'll take it there.
