### ISSUE TITLE
Latest VCRedist 2010 is `10.0.40219.473`

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/cpp-docs#4389]
Microsoft docs says `10.0.40219.325` is the latest version of VCRedist 2010:

* https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported

But there seems to be a newer `10.0.40219.473`:

* https://github.com/abbodi1406/vcredist/tree/master/source_links#microsoft-visual-c-2010-redistributables---v10

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by TylerMSFT** [comment]
updated
