### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by sffc** [MicrosoftDocs/cpp-docs#439]
I cannot figure out how to execute a program in preprocessing.  The docs say to use brackets, but I cannot get that to work.  An example would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2251415-a141-e237-5ab3-5c277bb5d9a2
* Version Independent ID: 4a5a5319-33ee-9e76-6d28-252e1e6ecbba
* Content: [Executing a Program in Preprocessing](https://docs.microsoft.com/en-us/cpp/build/executing-a-program-in-preprocessing?view=vs-2017)
* Content Source: [docs/build/executing-a-program-in-preprocessing.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/executing-a-program-in-preprocessing.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by tommai78101** [comment]
@sffc 

The "brackets" are referring to the parameters from this article:

https://docs.microsoft.com/en-us/cpp/build/makefile-preprocessing-directives?view=vs-2017

It's the previous section before the page you are reading. And presumably, the page you were on is actually the chapter of the section.

**Comment by bin601** [comment]
Smaple 
```
!IF [dir /s]
!ENDIF
```

**Comment by corob-msft** [comment]
Cleaning up old issues. There's a very simple example in the relevant article now.
