### ISSUE TITLE
/WX documentation is missing warning numbers

### ISSUE THREAD

**Issue by erwanhmsft** [MicrosoftDocs/cpp-docs#4391]
Starting with Visual Studio 2022, LINK /WX supports specific warning numbers to be treated as error. See https://developercommunity.visualstudio.com/t/treat-specific-linker-warnings-as-errors/1470628. 

The new syntax appears to be the following -- guessed via experiments: LINK /WX[:num1[,num2[,...]]], where num1 and num2 are linker warning numbers. Here is the output of one such experiments:

>\>link LinkerWarning.obj OSLayer.obj Util.lib **/WX:4075,4006**
>Microsoft (R) Incremental Linker Version 14.35.32213.0
>Copyright (C) Microsoft Corporation.  All rights reserved.
>
>LinkerWarning.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification
>**LINK : error LNK1218: warning treated as error; no output file generated**

Please update the documentation to describe the new options of LINK /WX that are available in VS2022 and above.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abd121e9-da7d-891c-c881-773cb9756aec
* Version Independent ID: cc4a6be7-8eaa-6f09-c32a-631ae4f551bf
* Content: [/WX (Treat linker warnings as errors)](https://learn.microsoft.com/en-us/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=msvc-170)
* Content Source: [docs/build/reference/wx-treat-linker-warnings-as-errors.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/wx-treat-linker-warnings-as-errors.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by erwanhmsft** [comment]
See also Developer Community Ticket https://developercommunity.visualstudio.com/t/post/10269090

**Comment by corob-msft** [comment]
@erwanhmsft 

Thanks for the request. The docs have been updated, though the linker itself doesn't mention the additional option in the command-line help. That's a separate issue that must be addressed by the dev team.
