### ISSUE TITLE
management

### ISSUE THREAD

**Issue by Samuyuththa** [MicrosoftDocs/cpp-docs#4393]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7d9e962-1eea-a7f6-74a9-baa20fd37977
* Version Independent ID: 8a6c1479-8b1e-e0c7-d1ab-631323b239f7
* Content: [Visual Studio Projects - C++](https://learn.microsoft.com/en-us/cpp/build/creating-and-managing-visual-cpp-projects?view=msvc-170)
* Content Source: [docs/build/creating-and-managing-visual-cpp-projects.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/creating-and-managing-visual-cpp-projects.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Samuyuththa 
Thanks for entering an issue. Unfortunately, it doesn't appear to be actionable. If you could explain the problem in more detail, that would be useful. Until then, I'm closing this as not fixable given the information available.
