### ISSUE TITLE
log1p not related to factorials

### ISSUE THREAD

**Issue by WilliamCushing** [MicrosoftDocs/cpp-docs#4394]
"If x is a natural number, this function returns the logarithm of the factorial of (x - 1)."

That sentence is bogus.  log1p(5) == log(6), not log((5-1)!) == log(24) == log(4 * 3 * 2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20ef772f-e5b7-cf44-fa4e-2a30e4c968e7
* Version Independent ID: c0be2613-1e99-b26d-b6aa-114653a3c7bf
* Content: [log1p, log1pf, log1pl2](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/log1p-log1pf-log1pl2?view=msvc-170#see-also)
* Content Source: [docs/c-runtime-library/reference/log1p-log1pf-log1pl2.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/log1p-log1pf-log1pl2.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@WilliamCushing, thank you for taking the time to note that problem. I've fixed it and the fix should be live by tomorrow afternoon (2/2/2023).

**Comment by WilliamCushing** [comment]
Thanks :)
