### ISSUE TITLE
Built-in types (C++) is not included in Microsoft Help Viewer 2.3 - Visual Studio Documentation

### ISSUE THREAD

**Issue by pampas-gaucho** [MicrosoftDocs/cpp-docs#4401]
"Built-in types (C++)" is not included in Microsoft Help Viewer 2.3 - Visual Studio Documentation (with data updated up to February 2023).

This item is essential in understanding C++.

Please consider adding this item so it can be viewed offline.

Many Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54d070a7-f545-f407-4374-c37ec7211943
* Version Independent ID: 3a41a9c9-07b8-3281-3b31-1ea497a08008
* Content: [Built-in types  (C++)](https://learn.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=msvc-160)
* Content Source: [docs/cpp/fundamental-types-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/fundamental-types-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
I rebuilt the offline docs a couple months ago. It should address this.
