### ISSUE TITLE
Wrong size of unsigned long type

### ISSUE THREAD

**Issue by Pastelhorizon** [MicrosoftDocs/cpp-docs#4406]
[Enter feedback here]
The size of unsigned long here must be 8 bytes, not 4 bytes. Its wrong here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3252f3-2390-77d1-75ee-00ff08584173
* Version Independent ID: 53786641-f25d-638f-18d5-8c7e19712776
* Content: [Data Type Ranges](https://learn.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-170)
* Content Source: [docs/cpp/data-type-ranges.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/data-type-ranges.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Pastelhorizon 

All flavors of `long` in the Microsoft C/C++ compiler are 32-bit (4-byte) integers, the same size as `int`. This differs from some other compilers, such as gcc. If you require portable specific sizes of integers, use the explicitly sized types, such as `uint64_t`. I'm closing this issue as it doesn't appear to identify a real issue in the documentation.
