### ISSUE TITLE
/DTEST in preprocessor does not work (the example is broken)

### ISSUE THREAD

**Issue by jnewth** [MicrosoftDocs/cpp-docs#441]
Repro:
1. Copy and Paste the example exactly as above.
2. Compile, confirm output is "TEST not defined".
3. Add "/DTEST=" to Project&gt;C/C++ Properties&gt;Preprocessor Definitions" so the full definition list looks like:
WIN32
_DEBUG
_CONSOLE
/DTEST=
4. Clean and compile. Expected result: "TEST defined". Actual result: "TEST not defined".
Observed on Visual Studio Community 2017, version 15.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a87ec45-dd47-8b9c-3f4f-4d4643a8ff57
* Version Independent ID: e8236d27-55c6-5857-62f7-2a9137cd3b43
* Content: [-D (Preprocessor Definitions)](https://docs.microsoft.com/en-us/cpp/build/reference/d-preprocessor-definitions?view=vs-2017)
* Content Source: [docs/build/reference/d-preprocessor-definitions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/d-preprocessor-definitions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jnewth Ah, I see what you did there. In the IDE, you defined a preprocessor macro named "/DTEST" with no value. It doesn't match the `#ifdef TEST` line, so the following line isn't compiled, and it probably appears in light gray in the editor, showing that it's not the active code path. In the IDE, you just need to enter the preprocessor macro name and optionally assign a value. That is, in the **Preprocessor Definitions** dialog, you only need to enter *TEST* or *TEST=*, without the **/D** command line option prefixed. I can see we don't make that very clear. I'll put a task on my backlog to clean that up.

After you've edited a value in the **Property Pages** dialog, you can look at the command line by opening the **Configuration Properties** > **C/C++** > **Command Line** page, where you'll see the list in **All Options**. In this case, look for the **/D "TEST"** option to see what effect your additional definition had on what gets passed to the compiler.

**Comment by jnewth** [comment]
@corob-msft Thanks for that! I did in fact try various tweaks first, but before bugfiling I wanted to do *exactly* what I *thought* was being instructed to do. As you say, it may be helpful to clarify the language, or perhaps provide a screenshot of the properties panel used in the example, so people have an excessively well-defined example to work from. Regardless: You got me sorted out. Much appreciated.

**Comment by Predelnik** [comment]
Is it true that defining macro functions like /DSOMEFUNC(X)=(X*4) is oficially unsupported and there is no way to define one through command line?
Seems a bit unclear regarding "/D has the same effect as the #define directive at the beginning of a source code file"

**Comment by ericleigh007** [comment]
I "believe" that the /D option may be used multiple times to define multiple definitions, but this help doesn't seem to include that information.  Perhaps the syntax above should be updated?  And perhaps a description of multiple use should be added?

I believe that this is valid:
CL /DONE=1 /DTWO=2

and we can also define 
SET CL = /DONE#1 /DTWO#2

Correct?

Or is it 
CL /DONE=1,TWO=2
SET CL /DONE#1,TWO#2

-thanks
-e

**Comment by corob-msft** [comment]
[-D (Preprocessor Definitions)](https://docs.microsoft.com/en-us/cpp/build/reference/d-preprocessor-definitions) updated.
