### ISSUE TITLE
COleDateTime::SetDate wrong documentation on RETURN values

### ISSUE THREAD

**Issue by DevMatSolutions** [MicrosoftDocs/cpp-docs#4413]
COleDateTime::SetDate returns one of the enumerator for COleDateTime::status. In this respect, return of 1 corresponds to invalid, while 0 to valid

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26c31362-cb6f-cd6a-f0cb-b03a6f23cda0
* Version Independent ID: 64066ad0-5778-4f58-9d0e-7ef1978f9f86
* Content: [COleDateTime Class](https://learn.microsoft.com/en-us/cpp/atl-mfc-shared/reference/coledatetime-class?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(ATLCOMTIME%252FATL%253A%253ACOleDateTime%253A%253ASetDate)%3Bk(ATL%253A%253ACOleDateTime%253A%253ASetDate)%3Bk(SetDate)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/atl-mfc-shared/reference/coledatetime-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/atl-mfc-shared/reference/coledatetime-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, that's what the topic says: Zero if the value of this COleDateTime object was set successfully; otherwise, 1
Closing.
