### ISSUE TITLE
Typo in max value for /Gs?

### ISSUE THREAD

**Issue by KenSykes** [MicrosoftDocs/cpp-docs#4418]
Based on experimentation 2147483647 is the max value (4th digit from right is 3 not 5):

C:\temp>cl /EHsc /Gs2147483648 /Fa wccstr.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31942 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

wccstr.cpp
fatal error C1049: invalid numerical argument '2147483648'

C:\temp>cl /EHsc /Gs2147483647 /Fa wccstr.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31942 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

wccstr.cpp
Microsoft (R) Incremental Linker Version 14.34.31942.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:wccstr.exe
wccstr.obj

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7677050-221f-18a7-7f9f-0ce6c76fd878
* Version Independent ID: efdfd190-b9e8-d951-5256-41132bf4c743
* Content: [/Gs (Control Stack Checking Calls)](https://learn.microsoft.com/en-us/cpp/build/reference/gs-control-stack-checking-calls?view=msvc-170)
* Content Source: [docs/build/reference/gs-control-stack-checking-calls.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/gs-control-stack-checking-calls.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@KenSykes 
Thanks for the report. A fix for the typo ought to be visible by sometime tomorrow.
