### ISSUE TITLE
Lambda expression components are not explained

### ISSUE THREAD

**Issue by ShippyMSFT** [MicrosoftDocs/cpp-docs#4419]
There are illustrations on the main page about C++ lambda expressions that have numbers, but there is no explanation for what the numbers mean. I think this article used to define what each number referred to and have a description of what they are. The page feels like it was truncated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 437be494-4752-c2de-a8c0-c4bc8563ddb4
* Version Independent ID: 51317bb8-4c01-146a-f1a7-eba0e54cb5e4
* Content: [Lambda expressions in C++](https://learn.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)
* Content Source: [docs/cpp/lambda-expressions-in-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/lambda-expressions-in-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ShippyMSFT 
Yes, that article got viciously truncated somehow during publishing. I'll look into it.

**Comment by corob-msft** [comment]
Handing this off to @TylerMSFT, who made the change recently that caused the issue. The article has a redundant image and might also have broken image syntax, causing the rest of the article not to render correctly.

**Comment by TylerMSFT** [comment]
@ShippyMSFT - thank you for letting us know. This is fixed (it'll be live in a couple days).  Aside from not removing the previous link when I was converting it to a syntax that would allow for richer screen reader text, I think what was cutting the article off is that the long-form alt-text didn't start on its own line :-|
