### ISSUE TITLE
Description of path class on documentation website has typos

### ISSUE THREAD

**Issue by SaurabhGautam** [MicrosoftDocs/cpp-docs#442]
[Enter feedback here]
The description of the path class on https://docs.microsoft.com/en-us/cpp/standard-library/path-class?view=vs-2017 is incorrect. 

It currently reads as:
string_type is a synonym for basic_string<value_type>, where value_type is a synonym for **char** under Windows or **wchar_t** under Posix.

but it should read as

string_type is a synonym for basic_string<value_type>, where value_type is a synonym for ~char~ **wchar_t** under Windows or ~char~ **wchar_t** under Posix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c75fe219-1699-a208-f101-4cf493950cea
* Version Independent ID: 92f865c3-405b-59c7-ce24-14342ee8583b
* Content: [path Class](https://docs.microsoft.com/en-us/cpp/standard-library/path-class?view=vs-2017)
* Content Source: [docs/standard-library/path-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/path-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
thanks @SaurabhGautam you are correct and the fixed topic should appear tomorrow.
