### ISSUE TITLE
template literal operator

### ISSUE THREAD

**Issue by OptimumCpp** [MicrosoftDocs/cpp-docs#4422]
The template literal operator has been added to standard since C++17, but as of this day(6 years later) visual studio cannot compile standard code. When is it going to be fixed??
the links below show how Microsoft treats developer feedbacks. We have been await for 6 years. Do we need to wait for another 60 years??

---
#### Document Details

https://developercommunity.visualstudio.com/t/C20-String-literal-operator-template-u/1318552
https://developercommunity.visualstudio.com/t/literal-operator-template-fails-to-compile-when-us/681493

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba17b29c-7421-ef5a-5817-dc1d7cde6e64
* Version Independent ID: a5405b59-608f-eaa8-c5c2-e38b6c89248a
* Content: [User-defined literals (C++)](https://learn.microsoft.com/en-us/cpp/cpp/user-defined-literals-cpp?view=msvc-170)
* Content Source: [docs/cpp/user-defined-literals-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/user-defined-literals-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@OptimumCpp 
I understand this issue is fixed in Visual Studio 2022 version 17.5, which is now in preview mode and should be released to production shortly. Since it's a product issue rather than a documentation issue, I'm closing it.

**Comment by OptimumCpp** [comment]
Thanks for rapid response. I will check it on.

در تاریخ جمعه ۱۷ فوریهٔ ۲۰۲۳،‏ ۰۳:۴۳ Colin Robertson <
***@***.***> نوشت:
