### ISSUE TITLE
error C3474: could not open output file 'std.ifc' on module build

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/cpp-docs#4428]
I'm following the tutorial and am attempting to build the std module files std.ixx and std.ifc.  I open a Developer PowerShell window from within VS 2022 17.5, and navigate to the Visual Studio 2022 directory.  When I run the cl command, I get the subject error.

It appears that one cannot create these files under the Visual Studio 2022 folder.  Although the tutorial "suggests" a path on C:\ (which is, IMHO, a terrible place to create the module files), perhaps a warning about write permissions and a note about this error might be prudent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Version Independent ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Content: [Tutorial: Import the standard library (STL) using modules (C++)](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
* Content Source: [docs/cpp/tutorial-import-stl-named-module.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/tutorial-import-stl-named-module.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@JustaSimpleUser , thank you for taking the time to comment on the doc. I've made the suggested change. It should be live by EOD tomorrow (2/23)
