### ISSUE TITLE
link errors

### ISSUE THREAD

**Issue by anybody3** [MicrosoftDocs/cpp-docs#4432]
[Enter feedback here]This code fails over and over with these errors in vs 2022:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __cdecl Cardgame::Cardgame(int)" (??0Cardgame@@QEAA@H@Z) referenced in function "void __cdecl PlayGames(void)" (?PlayGames@@YAXXZ)	Game	C:\C++\Game\Game.obj	1	
Error	LNK2019	unresolved external symbol "public: __cdecl Cardgame::~Cardgame(void)" (??1Cardgame@@QEAA@XZ) referenced in function "void __cdecl PlayGames(void)" (?PlayGames@@YAXXZ)	Game	C:\C++\Game\Game.obj	1	
Error	LNK1120	2 unresolved externals	Game	C:\C++\Game\x64\Debug\Game.exe	1	

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40c5ecf4-574c-acb1-26fe-26904d2f2cee
* Version Independent ID: 7c8f2413-033f-5cad-8e11-00c4e12a10ec
* Content: [Walkthrough: Working with Projects and Solutions (C++)](https://learn.microsoft.com/en-us/cpp/ide/walkthrough-working-with-projects-and-solutions-cpp?view=msvc-170)
* Content Source: [docs/ide/walkthrough-working-with-projects-and-solutions-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/ide/walkthrough-working-with-projects-and-solutions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by anybody3** [comment]
The code for the game, sorry i dont know how to use this system.....I thought it would list the page its on here so it could be fixed directly.    This is the page the code is on.

**Comment by anybody3** [comment]
https://learn.microsoft.com/en-us/cpp/ide/walkthrough-working-with-projects-and-solutions-cpp?view=msvc-170

**Comment by corob-msft** [comment]
@anybody3 
I'll preface my comment by saying this isn't a support forum, it's for reporting problems in the documentation. A better place for questions like this one is in the [Microsoft Learn Q&A C++ forum](https://learn.microsoft.com/en-us/answers/tags/314/cpp). A quick run-through of the article steps shows the project builds as expected for me, so odds are you've made a mistake while copying the code. Normally, a LNK2019 error implies either a problem with names in your code, or a project configuration error, such as leaving an object file or library out of the link step. In this case, I'd guess you've misplaced the `public:` label in the `Cardgame` class declaration, so the constructor and destructor aren't visible to the calling code in `PlayGames`. I might be wrong, but as I said, it works when I follow the steps, so recheck your code and see if it has an issue. Best of luck with your coding.
