### ISSUE TITLE
Please specify the last version of Visual C++ Redistributable that works on Windows Vista

### ISSUE THREAD

**Issue by win98se** [MicrosoftDocs/cpp-docs#4434]
Under “Notes” in [this page](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist), it is specified the last version of Visual C++ Redistributable that works on Windows XP.

Recently, a friend of mine tried to install the latest version of Visual C++ Redistributable on his Windows Vista computer, that displays this error message -
![image](https://user-images.githubusercontent.com/11819816/221057938-781d7f25-3915-4f67-bb97-d6fe9f0452b1.png)

It's not easy to find the version available for Windows Vista.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by stdin82** [comment]
Officially, Visual Studio 2022 toolset (MSVC >= 14.30) does not support targeting Windows Vista
Technically, `14.31.30919` is the last VC_redist installer that is permitted on NT 6.0 (with SHA-2 support)
Practically, `14.32.31332` is the last version that works on NT 6.0 (with SHA-2 support)

for reference:
https://github.com/microsoft/STL/pull/2317

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
