### ISSUE TITLE
optimize("ts", on) is a valid preprocessor directive, however documentation for it is non-existence or misleading 

### ISSUE THREAD

**Issue by killerswin2** [MicrosoftDocs/cpp-docs#4437]
Optimize pragma, current has three tables Parameters of the optimize Pragma. Please create a fourth table, below s or t that explains what "s and t" means. Reading the docs having both seams to mean that they are almost mutual elusive of each other. Which is not the case, as using  optimize("ts", on) visibly reduces pdb file sizes, meaning that short is working. However with the addition of "T" is is unclear if fast machine code is produce along with short code. 

[optimize](https://learn.microsoft.com/en-us/cpp/preprocessor/optimize?view=msvc-170)

**Comment by corob-msft** [comment]
@killerswin2 
It may be possible to specify both `s` and `t` in the optimize pragma string, but it's not possible to actually have both set at the same time. Internally, there's only a speed optimization flag for the compiler, and the `s` and `t` flags toggle it on or off. The last one specified wins on the command line. I'd expect similar behavior from the pragma, but I can't tell how it actually behaves in my quick search. Perhaps there should be a specific warning generated for such pragma invocations, akin to C4426. You could suggest such a thing in [Developer Community](https://aka.ms/vsfeedback/browsecpp).

**Comment by killerswin2** [comment]
@corob-msft Thank you so much for your time. I will suggest such a thing over in the dev community.
