### ISSUE TITLE
Wizzard dosent exists

### ISSUE THREAD

**Issue by KahnSoft** [MicrosoftDocs/cpp-docs#4440]
[Enter feedback here]

This Wizzard to add an Class from ActiveX Cotrl dosent exists anymore 

[Add class from ActiveX control wizard](https://learn.microsoft.com/en-us/cpp/ide/adding-a-class-from-an-activex-control-visual-cpp?view=msvc-170#add-class-from-activex-control-wizard)

This View can not bring up  FATAL !

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 228e7ee0-b20c-e53b-2bfb-92f17fbde981
* Version Independent ID: 0560f78d-ca49-d9df-2e58-c7891fead238
* Content: [Add a class from an ActiveX control](https://learn.microsoft.com/en-us/cpp/ide/adding-a-class-from-an-activex-control-visual-cpp?view=msvc-170)
* Content Source: [docs/ide/adding-a-class-from-an-activex-control-visual-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/ide/adding-a-class-from-an-activex-control-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
@KahnSoft, some of the Wizards were removed at one point, but some were restored in March of 2022.
I see this wizard in VS 2022 (I'm running 17.5.4)
I think they started coming back in VS 2019 (see this [post](https://devblogs.microsoft.com/cppblog/author/anjudelmoralgonzalez/) and [this post](https://devblogs.microsoft.com/cppblog/typelib-and-activex-now-supported-in-mfc-wizards/)
For the wizards to appear, you have to be in the right project type. For example, I created a MFC Active X control project type, and the wizard was available when I right-clicked the project name and choose Add > New Item > MFC Class From ActiveX Control
