### ISSUE TITLE
`_getch` *does* read Ctrl+C

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#4442]
The documentation states that `_getch` doesn't read Ctrl+C, but a simple test program reveals that it does.  It does not intercept Ctrl+Break.

```
#include <iostream>
#include <conio.h>

int main()
{
    while (true)
    {
        int ch = _getch();
        std::cout << "Got character " << ch << '\n';
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72c56cd0-6b04-3472-ce56-fe749a238b70
* Version Independent ID: 5e6e3834-0c3c-0677-9dc2-9e7a96d31f0c
* Content: [_getch, _getwch](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/getch-getwch.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/getch-getwch.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@vaanwd - you are right. I don't know what the original writer was thinking here. Regardless, I've fixed it by removing the statement about Ctrl+C. The fix will be live sometime tomorrow.
Thank you for taking the time to point this out so we can fix it.
