### ISSUE TITLE
Name is Completely Wrong

### ISSUE THREAD

**Issue by smolbach** [MicrosoftDocs/cpp-docs#4443]
This article is supposed to be about C++ development. Why in the world does it include the Basic Android Application template that creates a project in JAVA? Furthermore, why in the world is that bug identified as "Closed - Not Bug" at https://developercommunity.visualstudio.com/t/c-android-project-template-creates-in-fact-a-java/8149?

Makes absolutely zero sense.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3558cc94-e230-8596-f2bb-19dde4230493
* Version Independent ID: 726e26ac-298a-e650-0267-a20846899722
* Content: [Cross-platform mobile development with C++](https://learn.microsoft.com/en-us/cpp/cross-platform/visual-cpp-for-cross-platform-mobile-development?view=msvc-170)
* Content Source: [docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@smolbach 
I can't speak to why the VS C++ cross-platform templates let you create Java projects, but they do, so we document the fact. A product issue should be taken up with Developer Community, since the docs team can't fix those.
