### ISSUE TITLE
Visual Studio 2012 is end of extended support. Is 2012 redistributed package end of support as well?

### ISSUE THREAD

**Issue by hansenrsap** [MicrosoftDocs/cpp-docs#4448]
Visual studio 2012 is end of extended support
https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2012

Does this mean the document needs to be updated to show:
(no longer supported)
Note
Visual Studio 2012 [reached end of extended support on January 10, 2023](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2012)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by r-heimann** [comment]
Any update? Visual Studio 2012 is EOL For months and this page has not been updated.

**Comment by TylerMSFT** [comment]
The doc has been updated and should be live by tomorrow afternoon.
