### ISSUE TITLE
Explicit way to add images to an icon file would be helpful

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/cpp-docs#4450]
It would be helpful to have explicit instructions in how to create an icon file from image with whatever restrictions and add more image sizes to icon from image.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 195f6bf5-8435-ecda-e7c6-c705934e9fa6
* Version Independent ID: 8a714db6-0297-a0ec-3f3c-bb2156741192
* Content: [Image Editor for Icons (C++)](https://learn.microsoft.com/en-us/cpp/windows/image-editor-for-icons?view=msvc-170)
* Content Source: [docs/windows/image-editor-for-icons.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/image-editor-for-icons.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, @troglobytor , I can see why this would be helpful. Unfortunately, given current and foreseeable priorities, it is something we would just never get to.  Closing this issue so we don't create the false impression that we will eventually get to it. Sorry about that.
