### ISSUE TITLE
Hello dunia

### ISSUE THREAD

**Issue by Karl2013** [MicrosoftDocs/cpp-docs#4452]
Hello dunia
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d597b582-59ec-2014-699b-6aac8db69cf6
* Version Independent ID: 81941537-4446-9c5a-6af3-25318396420d
* Content: [Build and run a C++ console app project](https://learn.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=msvc-170)
* Content Source: [docs/build/vscpp-step-2-build.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/vscpp-step-2-build.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as there is no actionable feedback
