### ISSUE TITLE
Example 5

### ISSUE THREAD

**Issue by R3dMage** [MicrosoftDocs/cpp-docs#4461]
Would be nice if Example 5 had actual code examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69cc6836-826c-9f95-0b59-29bf9180d343
* Version Independent ID: 29f62ae3-670b-9fe6-b938-e1441d4a8e3c
* Content: [How to: Create and use shared_ptr instances](https://learn.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-shared-ptr-instances?view=msvc-170)
* Content Source: [docs/cpp/how-to-create-and-use-shared-ptr-instances.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/how-to-create-and-use-shared-ptr-instances.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@R3dMage , this will be updated by EOD 5/31.  @fsb4000 kindly took care of this for the community. Thanks, Igor!
