### ISSUE TITLE
Question about "Width specification" in "Format specification" for various 'printf' and 'wprintf' functions

### ISSUE THREAD

**Issue by ltorok** [MicrosoftDocs/cpp-docs#4465]
This is not issue, but more of a question.
Relates with documentation on [Format specification syntax: printf and wprintf functions](https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170).

In the section "Width specification" is noted:
_The width argument is a **non-negative decimal integer** that controls the minimum number of characters that are output._
and later yet this
_If the width specification is an asterisk (*), an **int** argument from the argument list supplies the value._

Question:
What is max/limit value of this **non-negative decimal integer/int** width argument (for Microsoft Visual C++ (MSVC) )?
Is it
<html><body>

INT_MAX | Maximum value for a variable of type int. | 2147483647
-- | -- | --

</body>
</html>
?

Thanks for Your answer.

**Comment by TylerMSFT** [comment]
Hi, this is better suited for [Microsoft Q&A](https://github.com/MicrosoftDocs/cpp-docs/assets/12305055/6bd64eeb-5f65-45b0-81f1-e2507ba0ec1e)
