### ISSUE TITLE
Unrelated pages listed in "Recommended content" section

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/cpp-docs#4470]
Pages listed in the "Recommended content" section for this page are mostly unrelated to the current page's content. I wonder how they are collected and added there. Are they static list added to the page, or dynamically collected? Either way, they do not help learning the content of the current page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd137f17-dac2-ead3-a451-4e7afcf95ed5
* Version Independent ID: 09b1e018-42eb-6e47-1ae6-f80e5278ec6c
* Content: [Warning C26819](https://learn.microsoft.com/en-us/cpp/code-quality/c26819?view=msvc-170)
* Content Source: [docs/code-quality/c26819.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c26819.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @hwisungi , yes, that's a problem. They are dynamically generated so nothing I can do about it. I'll provide feedback to the team that provides that feature.
