### ISSUE TITLE
no relevant data

### ISSUE THREAD

**Issue by AvatharBehemoth** [MicrosoftDocs/cpp-docs#4471]
[Enter feedback here]
this is a nonsense document. it has no relevant data as to what is wrong. nor does it help me in any way, shape or form.
this is a page by autists for autists.

i have created a class with a constructor. a .h and a .cpp file. if i put relevant variables in .h i get a linker error when creating the class object. when i put the data in .cpp i get this error. 
basically this is annoying to the max.

and it reminds me of the error carousel you suggest in visual studio. it is not helping. nor even adressing what the error is.
your message is "we dont know what you are doing wrong. its "something".
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2fe6ac8-ec23-1557-c3a5-021ed28c701a
* Version Independent ID: eb8b438d-ec05-0ab8-dc2e-5cb30a09e58f
* Content: [Compiler Error C2084](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2084?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2084)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2084.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/compiler-error-c2084.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
The document is correct, insofar as saying what compiler error C2084 means. 
Compiler errors can be frustrating depending on the situation. I'm not in a position to diagnose that, but you might try the [Microsoft Q/A site][(https://developercommunity.visualstudio.com/VisualStudio?ftype=problem) (https://learn.microsoft.com/en-us/answers/questions/)) to see if you can get some traction on your particular issue.

**Comment by AvatharBehemoth** [comment]
Sure just dismiss criticism and frustration. 
what this document does, and what visual studio has as a tendency is to take you on a carousel of errors.

basically due to the inability of "programmers" to communicate with other programmers.
so good job! you failed miserably,
