### ISSUE TITLE
Unupdated guide regarding Creating an Android Native Activity App

### ISSUE THREAD

**Issue by ScInglorion** [MicrosoftDocs/cpp-docs#4475]
As in version 17.4 there was this chage:
"Ant scripts have been removed, so users will no longer see Ant-based templates in the New Project dialog. For help migrating from Ant templates to Gradle templates, please see: Migrating Builds From Apache Ant (gradle.org)"
I feel like the article is a bit misleading for people trying to Create an Android Native Activity App

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b965be6-8dfd-db91-84e3-345e70d7c302
* Version Independent ID: 291bf1e4-c8f7-12e9-3f38-f54bbd822bc7
* Content: [Create an Android Native Activity App](https://learn.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app?view=msvc-170)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
One reason we keep the article around for people who are using the older version. But for those who are using 17.4 and above, we have the note about what has changed.
