### ISSUE TITLE
Page is missing in the list of CA warnings

### ISSUE THREAD

**Issue by hwisungi** [MicrosoftDocs/cpp-docs#4477]
This page is missing from the list of warnings in "C/C++ Code Analysis Warnings" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e00a4005-74bd-e77d-e5cd-dbcdb5e1fec2
* Version Independent ID: e00a4005-74bd-e77d-e5cd-dbcdb5e1fec2
* Content: [Warning C6030](https://learn.microsoft.com/en-us/cpp/code-quality/c6030?view=msvc-170)
* Content Source: [docs/code-quality/c6030.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c6030.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
We know. I submitted a fix for this earlier this morning. 
[4851](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/4851)  It'll be live tomorrow morning.
