### ISSUE TITLE
What is '&&=' ?

### ISSUE THREAD

**Issue by simnalamburt** [MicrosoftDocs/cpp-docs#448]
<img width="700" alt="2018-10-01 9 58 01" src="https://user-images.githubusercontent.com/4435445/46289817-17017200-c5c5-11e8-94b8-73e9b15ef4e5.png">

The documentation says `&&=` operator does exist, which is known to be non-existent.

<br>

I still see `&&=` operator neither in the C++11/14/17 standard nor in the N4762 which is the latest C++20 draft. And no latest GCC, Clang, or MSVC could successfully compile `&&=` operator.

The commit https://github.com/MicrosoftDocs/cpp-docs/commit/f44f4e introduced `&&=` operator, but there's no explanation. What is that?

<img width="400" alt="2018-10-01 10 02 25" src="https://user-images.githubusercontent.com/4435445/46290053-b58dd300-c5c5-11e8-9423-340b014b1dee.png">

<img width="400" alt="2018-10-01 9 43 47" src="https://user-images.githubusercontent.com/4435445/46290433-cdb22200-c5c6-11e8-944c-9c9a12115792.png">

<img width="400" alt="2018-10-01 9 44 23" src="https://user-images.githubusercontent.com/4435445/46290434-cf7be580-c5c6-11e8-8923-6876a1eda7a6.png">

###### Reference
- https://docs.microsoft.com/en-us/cpp/cpp/assignment-operators
- https://github.com/MicrosoftDocs/cpp-docs/commit/f44f4e
- https://github.com/cplusplus/draft/blob/master/papers/n4762.pdf
- https://github.com/cplusplus/draft/blob/50a00f/source/lex.tex#L806

**Comment by simnalamburt** [comment]
If no one understand what "996966 move operations" is, I'll just create a PR to remove those `&&=` from it. Shall I?

By the by, I wanted to hear a reason why the documentation of non-existent `&&=` operator was  created in the first place.

**Comment by mikeblome** [comment]
@simnalamburt Thanks very much for catching this error. Please feel free to submit a PR!

**Comment by simnalamburt** [comment]
OK. I'll send a PR

2018년 10월 5일 (금) 오전 1:19, Mike B <notifications@github.com>님이 작성:
