### ISSUE TITLE
Warning C26812  unscoped enum ???

### ISSUE THREAD

**Issue by Steve1776** [MicrosoftDocs/cpp-docs#4482]
I get this warning for my enums.  The warning says it prefers "enum class" over "enum".

 My enums exist inside my classes.  Are they not scoped by the class?

I'm using VS  community 2019  v142

**Comment by TylerMSFT** [comment]
This is better suited for the Microsoft Q&A, not doc feedback.
I happen to know the answer, though. [Read this](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums)
