### ISSUE TITLE
Visual Studio 2022 CMake+MinGW+GDB cannot debug target

### ISSUE THREAD

**Issue by WittonBell** [MicrosoftDocs/cpp-docs#4497]
Sorry, I couldn't find a suitable place to ask the question, so I have to raise it here. Sorry, if possible, please help me solve it. Thank you!
I used the "Open Folder" method to open the source code of qtcreator in VS2022. After successfully compiling with the compiler in MinGW, I was unable to configure `launch. vs. json` to correctly use GDB in MinGW for debugging. For example, I wanted to use GDB to debug `qtcreator. exe `, but it doesn't work. I don't know how to configure debugging for this complex CMake project.

I used `launch.vs.json`:
```json
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "project": "CMakeLists.txt",
      "name": "qtcreator.exe", // I tried `bin/qtcreator.exe` and so on, with other path, couldn't start debug also
      "projectTarget": "qtcreator.exe", // I tried `bin/qtcreator.exe` and so on, with other path, couldn't start debug also
      "cwd": "${workspaceRoot}",
      "program": "${debugInfo.target}",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb.exe",
      "externalConsole": true
    }
  ]
}
```
gdb.exe can find in PATH.  VS2022 report the error:
```
错误：找不到目标“qtcreator.exe"。请检查 launch.vs.json 中 projectTarget 的值
```

Could not found the target `qtcreator.exe`，check the value of `projectTarget` in `launch.vs.json`.

I don't know how to configure it to solve it.

**Comment by WittonBell** [comment]
I use VS2022(17.5.3,cmake version 3.25.1-msvc1) open a simply cmake project in directory `t`

root file `CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.0.0)
project(t VERSION 0.1.0)

add_subdirectory(src)
```

`t` has a subdirectory `src`, it has two file: `main.cpp` and `CMakeLists.txt`:

`main.cpp`:
```cpp
#include <iostream>

int main(int, char**) {
    std::cout << "Hello, world!\n";
}
```

`CMakeLists.txt`:
```
add_executable(t main.cpp)
```

I use `CMake Settting` add `Mingw64-Debug` confiure for use gcc/g++, then use root `CMakeFiles.txt` add debug configure, generate `launch. vs. json`, how to configure to use GDB for debugging normally?

`launch. vs. json`:
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "src/t.exe",
      "project": "CMakeLists.txt",
      "projectTarget": "src/t.exe",
      "cwd": "${workspaceRoot}",
      "program": "${debugInfo.fullTargetPath}",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb.exe",
      "externalConsole": true
    }
  ]
}
```

**Comment by WittonBell** [comment]
resolved

**Comment by EleberZ** [comment]
您好，我想问一下，你的VS2022+CMAKE项目+MinGW。。在项目里面的cpp h文件能不能跳转到标准库头文件？要怎么解决呢？
Hello, I would like to ask about your VS2022+CMAKE project+MinGW project. Can the. cpp. h file in your project be redirected to the standard library header file? How to solve it?

**Comment by WittonBell** [comment]
@EleberZ 可以看看博文[Visual Studio 2022使用MinGW来编译调试C/C++程序](https://blog.csdn.net/witton/article/details/126211289?spm=1001.2014.3001.5501)及其评论。
