### ISSUE TITLE
github killed code run

### ISSUE THREAD

**Issue by mcodding-sowo** [MicrosoftDocs/cpp-docs#4500]
I created a github for my calculator project; thereafter, it would not run due to a security violation, not authorized to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a console calculator in C++](https://learn.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=msvc-170)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as not a doc issue. Sounds like you have a configuration issue.
