### ISSUE TITLE
Put "(no longer supported)" to Visual Studio 2012

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/cpp-docs#4501]
[Enter feedback here]
Visual Studio 2012 have reached its end of support in January 2023. In this doc, older version is indicated as "(no longer supported". It should state that it is no longer supported for Visual Studio 2012 too, just like other old versions. 

Ref:
https://learn.microsoft.com/ja-jp/lifecycle/products/visual-studio-2012
https://devblogs.microsoft.com/visualstudio/support-ends-for-older-versions-of-visual-studio-feb2022/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by TylerMSFT** [comment]
@shunkino, I'm not quite sure what you would like done here. Are you saying it should say **no longer supported** in the title or something? I tried VS 2010 and it doesn't have any text like that: https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2010

**Comment by TylerMSFT** [comment]
Closing per no response.

**Comment by shunkino** [comment]
@TylerMSFT 
Hi, sorry I missed your message. What I meant is that we need to clarify that VS2012 is no longer supported on this [page](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported).

Following commit have already added this information to the doc. Thanks!
https://github.com/MicrosoftDocs/cpp-docs/blame/170745305d93daf3da659088af637ae31ed80977/docs/windows/latest-supported-vc-redist.md#L65
