### ISSUE TITLE
The description of currentDir inside launch.vs.json is wrong

### ISSUE THREAD

**Issue by amasciotta** [MicrosoftDocs/cpp-docs#4503]
Inside the [`launch.vs.json` schema reference](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/launch-vs-schema-reference-cpp.md#default-properties), section [Default properties](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/launch-vs-schema-reference-cpp.md#default-properties), the description of the parameter `currentDir ` states: 

> Specifies the full directory path to the Build Target. The directory is detected automatically unless this parameter is set.

It is not clear to me what this means... However, it is very clear to me what happens if I change that value: the working directory of the exe is changed according to the value provided.

The description should state something like: "The directory where the program will run".

I feel however that I'm missing something: the parameter `cwd` seems to be what I was looking for (a way to change the working directory of my program), but it doesn't seem to do anything.

I'm using CMake with Visual Studio v17.5.3 on Windows, and I'm developing locally.

**Comment by voltamund** [comment]
`cwd` is for Linux and `currentDir` for Windows. Not clear why different attributes are used.
Some attributes are not documented at all like `symbolLoadInfo`. This is documented for vscode but also works in vs. Both use the Visual Studio MI Debug Engine from what I understand.

**Comment by TylerMSFT** [comment]
Hi, the reason for the different attributes is that they are implementation-specific. As voltamund says, `cwd` is Linux, `currentdir` is Windows.

When I get some time, I'll take a look at updating the docs for attributes like `symbolLoadInfo`.

**Comment by TylerMSFT** [comment]
We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 2/23/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information, please see [Announcing a new way to give feedback on Microsoft Learn](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635)
