### ISSUE TITLE
Sources?

### ISSUE THREAD

**Issue by AbeerHaroon** [MicrosoftDocs/cpp-docs#4506]
Really great information and am grateful. Am I misunderstanding if asking for sources? Would be nice to have a link underneath the page linking the sources if possible. I understand other tasks can take priority
Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8592c227-2f48-9265-14a3-11b1a52fe1d3
* Version Independent ID: 204e8283-834c-0317-b212-9d2fb25b879f
* Content: [Security Best Practices for C++](https://learn.microsoft.com/en-us/cpp/security/security-best-practices-for-cpp?view=msvc-170)
* Content Source: [docs/security/security-best-practices-for-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/security/security-best-practices-for-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @AbeerHaroon , I'm not sure what you mean by sources? 
I did notice the broken link at the bottom of the topic that I'll fix.

**Comment by TylerMSFT** [comment]
Closing as no additional info on what was meant by sources. Feel free to reopen if you can provide more details.
