### ISSUE TITLE
setlocale failed but not call invalid_parameter_handler

### ISSUE THREAD

**Issue by zuohuiyang** [MicrosoftDocs/cpp-docs#4510]
document "If the locale or category isn't valid, **the invalid parameter handler is invoked**, as described in [Parameter validation](https://learn.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=msvc-170). If execution is allowed to continue, each function sets errno to EINVAL, and returns NULL."

but i write a code to test, invalid parameter handler is not invoked, setlocale just return null

```
void myInvalidParameterHandler(const wchar_t* expression,
                               const wchar_t* function, const wchar_t* file,
                               unsigned int line, uintptr_t pReserved) {
  wprintf(
      L"Invalid parameter detected in function %s."
      L" File: %s Line: %d\n",
      function, file, line);
  wprintf(L"Expression: %s\n", expression);
  abort();
}

int main() {
  _set_invalid_parameter_handler(myInvalidParameterHandler);
  char* ret = setlocale(LC_ALL, "1111");
}
```
sdk:10.0.22621.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @zuohuiyang , I duplicated your result. I will look into this.

**Comment by TylerMSFT** [comment]
Hi @zuohuiyang , the matrix of possibilities is interesting, here. The invalid parameter handler is only called when the category parameters is invalid. I created a table for what happens in the doc:

|Function | Invalid parameter | Invalid handler invoked as described in [Parameter validation](../parameter-validation.md)| Sets `errno` |
|---------|---------|---------|
| `setlocale` | *`category`*  | yes | yes |
| `setlocale` | *`locale`*  | no | no |
| `_wsetlocale` | *`category`* | yes | yes |
| `_wsetlocale` | *`locale`*  | no | no |

Also, [bug 44270864](https://microsoft.visualstudio.com/OS/_workitems/edit/44270864) is logged to look into why this isn't consistent between `setlocale` and `_wsetlocale`

The doc fix will be live by end of day tomorrow (4/21/2023)
