### ISSUE TITLE
CMyObject definition missing in example

### ISSUE THREAD

**Issue by DocDJ** [MicrosoftDocs/cpp-docs#4512]
[Enter feedback here]
CMyObject is used as a datatype in the example, but is not defined anywhere, either in the text or in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df247807-87d5-c66a-f9b4-3d195e72a331
* Version Independent ID: 68a68d87-832f-bbe1-7279-576bc975ab4d
* Content: [Multithreading: Creating Worker Threads in MFC](https://learn.microsoft.com/en-us/cpp/parallel/multithreading-creating-worker-threads?view=msvc-170)
* Content Source: [docs/parallel/multithreading-creating-worker-threads.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/parallel/multithreading-creating-worker-threads.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, that example is more pseudocode. It's trying to give an example of how you'd use it in principle, not provide a running example. Whether that was a good choice by the original writer is another matter, but we have accrued more issues than our resources can manage so unfortunately, I won't be able to do more here.
