### ISSUE TITLE
dllimport is obsolete

### ISSUE THREAD

**Issue by OfekShilon** [MicrosoftDocs/cpp-docs#4514]
`__declspec(dllimport)` is advertised both in this page and [here](https://learn.microsoft.com/en-us/cpp/build/importing-into-an-application-using-declspec-dllimport?view=msvc-170) as an optimization which eliminates import-stubs where possible.

This might have been true at some point in the past and can still be seen in debug builds, but today (don't know from which MSVC version) the compiler is able to optimize away redundant stubs without the hint.  
Take this code for example:
```cpp
__declspec(dllimport) void dll1_func1();
void dll1_func2();

int main()
{
    dll1_func1();
    dll1_func2();
}
```

In Debug it is indeed compiled to -
```
...
    dll1_func1();
00007FF742CB1A0B  call        qword ptr [__imp_dll1_func1 (07FF742CC3008h)]  
    dll1_func2();
00007FF742CB1A11  call        dll1_func2 (07FF742CB117Ch)       ; import stub
...
```

But in Release they are identical:
```
...
    dll1_func1();
00007FF7F4451004  call        qword ptr [__imp_dll1_func1 (07FF7F4452000h)]  
    dll1_func2();
00007FF7F445100A  call        qword ptr [__imp_dll1_func2 (07FF7F4452008h)]  
...
```
(both compiled with VS2022 for x64, checked on x86 too).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7f37b-1563-7dbd-7fd2-58648c4d2260
* Version Independent ID: 0e2fc14d-4646-661a-8e9e-289411081d6e
* Content: [Importing function calls using __declspec(dllimport)](https://learn.microsoft.com/en-us/cpp/build/importing-function-calls-using-declspec-dllimport?view=msvc-170)
* Content Source: [docs/build/importing-function-calls-using-declspec-dllimport.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/importing-function-calls-using-declspec-dllimport.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by binarycrusader** [comment]
The claimed performance optimization of __declspec(dllimport) might be obsolete text, but the other uses of __declspec(dllimport) are not as far as I know:

https://learn.microsoft.com/en-us/cpp/build/importing-data-using-declspec-dllimport?view=msvc-170

___declspec(dllimport) is always required to access exported DLL data._
https://learn.microsoft.com/en-us/cpp/build/importing-function-calls-using-declspec-dllimport?view=msvc-170

**Comment by OfekShilon** [comment]
@binarycrusader thanks, that's entirely true. I do believe this (importing data) is the sole effective usage remaining.

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
