### ISSUE TITLE
queue::pop description issue

### ISSUE THREAD

**Issue by 89036045696** [MicrosoftDocs/cpp-docs#4518]
[Enter feedback here]
Please correct the description for "queue::pop": need to be "Removes the first element." instead of "Removes the last element.". And inside "Remarks" section - too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 474e5bb1-fc71-f320-a55d-e994f5a8300c
* Version Independent ID: d2249291-ea4d-7e55-c85f-17eb90f06242
* Content: [queue (STL/CLR)](https://learn.microsoft.com/en-us/cpp/dotnet/queue-stl-clr?view=msvc-170#pop)
* Content Source: [docs/dotnet/queue-stl-clr.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/dotnet/queue-stl-clr.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@89036045696 , thank you for catching this. Fixed. I also updated the code examples to #include "pch.h" and added instructions for how to install the C++/CLI toolset.
The fix should be live by the end of day tomorrow (4/21/2023).
