### ISSUE TITLE
fopen_s, _wfopen_s mode text is incorrect for short-lived / "temporary" file mode flag

### ISSUE THREAD

**Issue by binarycrusader** [MicrosoftDocs/cpp-docs#4522]
The mode / modifier tables for fopen_s, _wfopen_s are not correct. It lists the same mode flag twice (lowercase 't') with different meanings:

mode modifier	Translation mode
_t_	Open in text (translated) mode.

mode modifier	Behavior
**t**	Specifies a file as temporary. If possible, it isn't flushed to disk.

Characters in mode string	Equivalent oflag value for _open/_sopen
_t_	_O_TEXT
**t**	_O_SHORTLIVED

't' (lowercase 't') is for 'text' mode; uppercase 'T' is for "temporary".

This is already correct on other pages:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fsopen-wfsopen?view=msvc-170

But 'T' temporary is also misleading; see #4523 since 'T' actually maps to '_O_SHORTLIVED' while 'D' maps to '_O_TEMPORARY'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5a2e737-afe6-a70d-8eb3-fe3a0aeda3e8
* Version Independent ID: 3a9bdb00-1d09-1b08-3dc3-029a6a0b16a2
* Content: [fopen_s, _wfopen_s](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-170&source=docs)
* Content Source: [docs/c-runtime-library/reference/fopen-s-wfopen-s.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/fopen-s-wfopen-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Fixed. Also did some work in conjunction with #4523. Will be live Monday afternoon.
