### ISSUE TITLE
_fsopen, _wfsopen mode text for temporary files can be misleading

### ISSUE THREAD

**Issue by binarycrusader** [MicrosoftDocs/cpp-docs#4523]
The mode text for 'D' may imply to some readers that 'T' is implied by 'D' when specified. It is not. While 'D' does cause _O_TEMPORARY to be set, it does not cause _O_SHORTLIVED to be set.

Put differently, readers of the documentation may assume that because the definition of 'T' and 'D' start the same way, that 'D' offers the same behavior as 'T' but also causes the file to be deleted when the last file pointer is closed:

Term	Definition
T	Specifies a file as temporary. If possible, it isn't flushed to disk.
D	Specifies a file as temporary. It's deleted when the last file pointer is closed.

A literal reading of other pages might cause the developer to add 'T', but if a developer never reads the other pages or relies solely on the definitions in the tables, they may not get the result they expected.

Those other pages are:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-170
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

A slightly different, consistent definition on all of these pages that might help developers avoid this potential problem could be something like this:

Term	Definition
T	Specifies a file has a short lifetime. If possible, the file isn't written to storage until it is closed.
D	Specifies a file as temporary. It's deleted when the last file pointer is closed.

In short, 'T' only avoids writing data to disk per documentation for FILE_ATTRIBUTE_TEMPORARY (https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants see also https://learn.microsoft.com/en-us/archive/blogs/larryosterman/its-only-temporary). Meanwhile, 'D' only provides the semantics of deletion on close but won't avoid writing to storage. To achieve both, developers must combine the two as 'TD'.

Changing the definition can help avoid implying the flags provide the same behavior. It might also be helpful to either link to the https://learn.microsoft.com/en-us/archive/blogs/larryosterman/its-only-temporary page or also add a note to the developer that they must combine 'T' and 'D' to obtain both behaviors.

Note that this concern also applies to the other pages linked above.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19df9b55-9ae6-9c08-b8e4-28518eaeb3bd
* Version Independent ID: c5941a32-c208-1b0a-c2be-6050cafcb33b
* Content: [_fsopen, _wfsopen](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fsopen-wfsopen?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/fsopen-wfsopen.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/fsopen-wfsopen.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@binarycrusader, I think this was a particularly good suggestion. I've changed the wording in these sections.  It'll be live Monday afternoon.
