### ISSUE TITLE
Citing "experimental" as a requirement is confusing

### ISSUE THREAD

**Issue by da40** [MicrosoftDocs/cpp-docs#4524]
[Enter feedback here]
Both <experimental/filesystem> and <filesystem> are cited as requirements. This library is no longer experimental.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02ad4206-e69a-bf6b-1243-6efce34c3d4f
* Version Independent ID: 5747ef04-7cea-1242-9c89-59ea0754eba0
* Content: [directory_iterator Class](https://learn.microsoft.com/en-us/cpp/standard-library/directory-iterator-class?view=msvc-170)
* Content Source: [docs/standard-library/directory-iterator-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/directory-iterator-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@da40, thanks for pointing that out. I removed 'experimental'.  It'll be live by Monday afternoon.
