### ISSUE TITLE
CD2DBrush::SetTransform wrong description

### ISSUE THREAD

**Issue by ocucu** [MicrosoftDocs/cpp-docs#4529]
CD2DBrush::SetTransform applies transforms to the brush and not to the render target.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49277a47-c900-78dd-8559-df40d6643fb7
* Version Independent ID: 05e0fcd0-2a04-9230-3402-507d875b6a4c
* Content: [CD2DBrush Class](https://learn.microsoft.com/en-us/cpp/mfc/reference/cd2dbrush-class?view=msvc-170)
* Content Source: [docs/mfc/reference/cd2dbrush-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/cd2dbrush-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by ocucu** [comment]
See for example this article on my blog: [Direct2D – Brush Transforms](https://codexpertro.wordpress.com/2023/04/27/direct2d-brush-transforms/)

**Comment by TylerMSFT** [comment]
Would you like to give updating this article a shot?
I don't have the resources/time to do so, unfortunately. Closing as a result of that reality.
