### ISSUE TITLE
Link to info on WinMD

### ISSUE THREAD

**Issue by drewnoakes** [MicrosoftDocs/cpp-docs#453]
I came here to find out about WinMD in general. It'd be useful if this page linked to general information about the feature.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5ddabc-66a5-efed-8606-db4f2b1e78f3
* Version Independent ID: 6c234edb-14a5-1a5e-c2d8-7422e835ef38
* Content: [-WINMD (Generate Windows Metadata)](https://docs.microsoft.com/en-gb/cpp/build/reference/winmd-generate-windows-metadata?view=vs-2017)
* Content Source: [docs/build/reference/winmd-generate-windows-metadata.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/winmd-generate-windows-metadata.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@drewnoakes There is no page that's only a general reference to .winmd files. They're standard metadata format files for describing an ABI. They're used to generate matching interfaces that can be used by other UWP programs written in any language. What are you trying to find out?

**Comment by drewnoakes** [comment]
@corob-msft 

> What are you trying to find out?

Basically what the files are. I saw a reference to WinMD in an issue report and the best info I could find online was [this blog post](https://mariusbancila.ro/blog/2011/10/30/winrt-and-winmd-files/), which is at risk of disappearing from the internet. Even if there's not much to say about them, it'd be useful if this docs page provided at least some information about what the files contain, and what they're used for.

**Comment by corob-msft** [comment]
@drewnoakes This topic has apparently landed as a top search result for "winmd" for curious people like you who want to know what a .winmd file is. Unfortunately, that's not what this topic is about, and annoyingly, I can't find a good alternative target. As far as I can tell, the only descriptions of .winmd files on docs.microsoft.com are tangential references in topics such as [Walkthrough: Creating a Simple Windows Runtime component and calling it from JavaScript](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript) and [Introduction to Microsoft Interface Definition Language 3.0](https://docs.microsoft.com/en-us/uwp/midl-3/intro). If you read enough of these tangents, you'll eventually learn that a .winmd file is a kind of DLL that contains .NET-like metadata for Windows Runtime types and, in the case of runtime components, the implementations of those types. I'll take a stab at some minimal clarification, but be forewarned not to expect much. It's just a linker option topic.

**Comment by drewnoakes** [comment]
In the absence of a dedicated topic page, I would have been happy with a single paragraph on the original document with a brief summary such as the one you just gave. Right now if you hit that page (a top search result) without knowing anything about WinMD then you leave none-the-wiser.

**Comment by corob-msft** [comment]
Fix is live: [-WINMD (Generate Windows Metadata)](https://docs.microsoft.com/en-gb/cpp/build/reference/winmd-generate-windows-metadata?view=vs-2017)

**Comment by drewnoakes** [comment]
@corob-msft That's fantastic. Thank you very much.
