### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by spudwa** [MicrosoftDocs/cpp-docs#4531]
namespace versions of these functions such as ::printf, ::scanf, ::fopoen, ::size_t, and so on

fopeon should be fopen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Version Independent ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Content: [Tutorial: Import the standard library (STL) using modules from the command line (C++)](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
* Content Source: [docs/cpp/tutorial-import-stl-named-module.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/tutorial-import-stl-named-module.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Fixed. Thanks for calling that out. Update should be live Monday.
