### ISSUE TITLE
Refers to three exception handling modes, but enumerates only two

### ISSUE THREAD

**Issue by dacabdi** [MicrosoftDocs/cpp-docs#4533]
In the section [](https://learn.microsoft.com/en-us/cpp/cpp/transporting-exceptions-between-threads?view=msvc-170#exception-handling-models-and-compiler-options) it refers to THREE exception handling but later enumerates only TWO. Is this an error?

> Visual C++ supports three models that can handle C++ exceptions, structured exception handling (SEH) exceptions, and common language runtime (CLR) exceptions. Use the [/EH](https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170) and [/clr](https://learn.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=msvc-170) compiler options to specify your application's exception-handling model.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39d1b5c4-4ad9-5e64-5995-1d3a1216b023
* Version Independent ID: 69e417fc-caa4-b10e-e765-02350e0f3aeb
* Content: [Transporting exceptions between threads](https://learn.microsoft.com/en-us/cpp/cpp/transporting-exceptions-between-threads?view=msvc-170)
* Content Source: [docs/cpp/transporting-exceptions-between-threads.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/transporting-exceptions-between-threads.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for calling that out. Yes, that's a mistake. It should have also listed ISO-standard C++ exception handling. The fix should be live tomorrow afternoon.
Thanks again for taking the time to help improve the docs.
