### ISSUE TITLE
Where is the example for a vector of vectors?

### ISSUE THREAD

**Issue by tcjohnson71** [MicrosoftDocs/cpp-docs#4545]
We need an example for a vector of vectors - the vector version of multi-dimensioned arrays.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cd55b4-5345-3493-9d05-12868315571d
* Version Independent ID: 8e501921-6f1d-7705-231b-7ed0eded02ae
* Content: [vector class](https://learn.microsoft.com/en-us/cpp/standard-library/vector-class?view=msvc-170)
* Content Source: [docs/standard-library/vector-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/vector-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
