### ISSUE TITLE
Instead of repeating what the error says, give direction on how to fix it, like how to set the entry point in this case.

### ISSUE THREAD

**Issue by greenliquidlight** [MicrosoftDocs/cpp-docs#4548]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16cc003c-aa9a-56f8-560d-3b1063911055
* Version Independent ID: 1a3603c5-c5c0-0fad-1ba3-53fe82798fc6
* Content: [Linker Tools Error LNK1561](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1561?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(LNK1561)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1561.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/tool-errors/linker-tools-error-lnk1561.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
This article lists a few things that may be wrong that suggest ways to fix the problem. I get that adding how to add main() would be good, but I've been given hundreds of these and have to focus on some other things.
