### ISSUE TITLE
`COleVariant.operator ==` is completely screwed up 

### ISSUE THREAD

**Issue by tobias-loew** [MicrosoftDocs/cpp-docs#4550]
[Enter feedback here]
`COleVariant.operator ==` is completely screwed up in documentation and the source:

`COleVariant.operator ==` does NOT compare two COleVariants. It either compares with a `const VARIANT&` or with `LPCVARIANT`. When compiling with the latest version of MSVC (version 193632532), the comparison of two COleVariant fails with
```
 error C2666: 'COleVariant::operator ==': overloaded functions have similar conversions
```

A possible workaroud is defining a better match
```
BOOL operator==(const COleVariant& var1, const COleVariant& var2);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0ef9c3-f7af-2dd7-2c7a-bc39394f3edc
* Version Independent ID: d0bcfae9-e185-44ae-f981-b2a7973fbe80
* Content: [COleVariant Class](https://learn.microsoft.com/en-us/cpp/mfc/reference/colevariant-class?view=msvc-170)
* Content Source: [docs/mfc/reference/colevariant-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/colevariant-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by tobias-loew** [comment]
@criddell 
> I would add that if you implement `operator==`, you probably also want `operator!=`.

Adding `operator!=` would only be necessary for pre c++20, as c++20 introduced rewrite rules for operators, see https://eel.is/c++draft/over.match.oper#3.4

**Comment by TylerMSFT** [comment]
Unfortunately, due to doc resources and priorities, closing this issue.
