### ISSUE TITLE
Can I use CWinFormsControl in project targeting /clr:netcore?

### ISSUE THREAD

**Issue by tomaszkot** [MicrosoftDocs/cpp-docs#4551]
I have MFC dll with /clr:netcore switch. When trying to use  CWinFormsControl  I get:
fatal  error C1107: could not find assembly 'System.Windows.Forms.dll': please specify the assembly search path using /AI or by setting the LIBPATH environment variable
2>Done building project "MFCLibrary1.vcxproj" -- FAILED.

Tested project is at: https://github.com/tomaszkot/MFC2Net (switch build to x64) 

P.S.
1. I added  
`<ItemGroup><FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" /></ItemGroup>`

  to the project file.

4. Set C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.16\ref\net6.0\System.Windows.Forms.dll for /AI switch

**Comment by TylerMSFT** [comment]
Product questions like this should go to [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)

**Comment by pigcivil** [comment]
```swift
![Uploading D9951C1A-5471-44EC-BB96-0A247CC5BD9B.png…]()

```
