### ISSUE TITLE
No Release Notes

### ISSUE THREAD

**Issue by tfcu-sdow** [MicrosoftDocs/cpp-docs#4553]
This page doesn't appear to link to release notes or have any information about what has changed between builds. Please provide links to such documentation on download pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by TylerMSFT** [comment]
Release notes are provided elsewhere, e.g. https://learn.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-170 and https://learn.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2022?view=vs-2022&preserve-view=true or https://devblogs.microsoft.com/cppblog/whats-new-for-cpp-developers-in-visual-studio-2022-17-8/

**Comment by tfcu-sdow** [comment]
This isn’t particularly helpful for those in IT just trying to determine whether there is security content in the release.


Steven Dow | Senior Infrastructure Engineer III
Tucson Federal Credit Union
T 520-322-7423 | ***@***.******@***.***>

**Comment by TylerMSFT** [comment]
I misread this initially. Adding a link to release notes, conformance notes, etc. is certainly doable. I'll do that this week.

**Comment by TylerMSFT** [comment]
I added some release note links.
