### ISSUE TITLE
Missing documentation for C5266

### ISSUE THREAD

**Issue by marekr** [MicrosoftDocs/cpp-docs#4554]
C5266 is not listed at all on the list of compiler warnings but is emitted at least on VS 2022 17.5.4

Example:
```
21:21:22  C:\jenkins\workspace\build-windows-kicad-msvc-master\.build\kicad\include\settings/bom_settings.h(41): warning C5266: 'const' qualifier on return type has no effect
21:21:22  C:\jenkins\workspace\build-windows-kicad-msvc-master\.build\kicad\include\settings/bom_settings.h(66): warning C5266: 'const' qualifier on return type has no effect
21:21:22  C:\jenkins\workspace\build-windows-kicad-msvc-master\.build\kicad\include\settings/bom_settings.h(67): warning C5266: 'const' qualifier on return type has no effect
21:21:22  C:\jenkins\workspace\build-windows-kicad-msvc-master\.build\kicad\include\settings/bom_settings.h(92): warning C5266: 'const' qualifier on return type has no effect
21:21:22  C:\jenkins\workspace\build-windows-kicad-msvc-master\.build\kicad\include\settings/bom_settings.h(93): warning C5266: 'const' qualifier on return type has no effect
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddc3041c-b233-bb3f-513f-b3df302b49a2
* Version Independent ID: aad153bd-a417-01fb-f2b7-50842269dcc0
* Content: [Compiler warnings C4800 Through C5999](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, we don't document all of the warnings.  The ones that we wouldn't add any value to, in addition to the text the warning provides, we don't doc. Resources...
