### ISSUE TITLE
REDIST.txt is not updated with api-ms-win-core-fibers-l1-1-0.dll  and api-ms-win-core-console-l1-2-0.dll files

### ISSUE THREAD

**Issue by napetrov** [MicrosoftDocs/cpp-docs#4556]
Sorry - not sure on correct palace for issue, so would try here. 
Online REDIST.txt file for Windows SDK http://go.microsoft.com/fwlink/?LinkId=524842

Current versions of SDKs contain 2 following libs that are not reflected in online REDIST.TXT 
api-ms-win-core-fibers-l1-1-0.dll
api-ms-win-core-console-l1-2-0.dll

In same time SDK itself doesn't contain separate REDIST file in installation, so at the moment seems that redistribution of those 2 libs prohibited. However it seems that intent was to allow redistribution

**Comment by TylerMSFT** [comment]
Hi, this is a product issue which you can log here: [developer community](https://developercommunity.visualstudio.com/VisualStudio?ftype=idea)

I've also forwarded this feedback on to the dev manager in this area.
