### ISSUE TITLE
Documentation for '_strerror_s' Incorrectly States Return String Terminates with Newline

### ISSUE THREAD

**Issue by heksterb** [MicrosoftDocs/cpp-docs#4570]
The documentation for `_strerror_s` claims that

> If strErrMsg is NULL, [...] the error-message string is terminated by the newline character ('\n').

and

> If strErrMsg isn't equal to NULL, then _strerror_s returns a string in buffer that contains [...] and a newline character.

However, the following test in my environment shows that, in both cases, the returned string is in fact **not** terminated by a newline:

```
#include <stdio.h>
#include <string.h>


int main()
{
// try to open file (expect failure)
FILE *result;
if (_wfopen_s(&result, L"does not exist", L"r") == 0) return 1;

/* Case 1: strErrMsg is NULL */ {
	/* "If strErrMsg is NULL, _strerror_s returns a string in buffer that contains
	   the system error message for the last library call that produced an error.
	   The error-message string is terminated by the newline character ('\n')." */
	// try to get system error message (expect success)
	char message[80];
	if (_strerror_s(message, sizeof message, NULL) != 0) return 1;
	
	// as per documentation, expecting last character to be a newline-- but it is not
	fprintf(stderr, "Case 1: last character %s a newline\n", message[strlen(message) - 1] == '\n' ? "is" : "is NOT");
	}

/* Case 2: strErrMsg is not NULL */ {
	/* "If strErrMsg isn't equal to NULL, then _strerror_s returns a string in buffer
	   that contains (in order) your string message, a colon, a space, the system error message
	   for the last library call that produced an error, and a newline character." */
	// try to get system error message (expect success)
	const static char prefix[] = "can't open file";
	char message[80];
	if (_strerror_s(message, sizeof message, prefix) != 0) return 1;

	// as per documentation, expecting last character to be a newline-- but it is not
	fprintf(stderr, "Case 2: last character %s a newline\n", message[strlen(message) - 1] == '\n' ? "is" : "is NOT");
	}

return 0;
}
```

Running produces the following output:

```
Case 1: last character is NOT a newline
Case 2: last character is NOT a newline
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba2ec2-b636-574d-f749-c3a6060a73dc
* Version Independent ID: ba19e8ab-6b4f-295d-e4e7-ee6a6cb0d302
* Content: [strerror_s, _strerror_s, _wcserror_s, __wcserror_s](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/strerror-s-strerror-s-wcserror-s-wcserror-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@heksterb , thank you for pointing this out. You are correct. I got curious about the related functions, and found an interesting thing. Of all the related functions, only __wcserror() adds a newline. I updated the docs accordingly.  Here's a little table of what I found:

|Func | \n added to the end?|
|-- | --
|strerror | No|
|_strerror_s | No|
|_strerror_s case 2 | No|
|__wcserror | Yes   (x00, x0A)|
|__wcserror_s | No|
|__wcserror_s case 2 | No|


The changes should be live by tomorrow afternoon (6/2)
