### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AGoh2019** [MicrosoftDocs/cpp-docs#4575]
Ok, the documentation looks okay.  But it doesn't say how to build a C program or a Assembly one.  

Basically I am crossing over from the JVM to NET Core 6LTS/7 stack though not fully.

At the same time, with IDE for heavy lifting, I am also into Java, Rust (with IntelliJ IDEA), Racket/Clojure (with DrRacket etc), Prolog (with SWI-Prolog or other IDEs), Kotlin (with Android Studio).  And I am trying to find my way around Emacs.  Comparing Julia with Visual Basic, waiting for a Windows version of Oberon-07, using four databases and basically happy coding around.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a console calculator in C++](https://learn.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=msvc-170&viewFallbackFrom=vs-2022)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
