### ISSUE TITLE
Slight Correction to Characterization of 'swprintf()'

### ISSUE THREAD

**Issue by heksterb** [MicrosoftDocs/cpp-docs#4578]
This page states that:

> swprintf is a wide-character version of sprintf; the pointer arguments to swprintf are wide-character strings

The interface of `swprintf` is

```
int swprintf(
   wchar_t *buffer,
   size_t count,
   const wchar_t *format [,
   argument]...
);
```

and, in particular, supports the `count` parameter "to specify the maximum number of characters to write."  As such, it seems that this function is instead better characterized as the wide-character version of [`snprintf`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-170):

```
int snprintf(
   char *buffer,
   size_t count,
   const char *format [,
   argument] ...
);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a209539e-aeec-2bb4-5887-c4cf90467204
* Version Independent ID: ed0abe24-9562-5db6-29dc-c7ad7588081a
* Content: [sprintf, _sprintf_l, swprintf, _swprintf_l, __swprintf_l](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, [heksterb](https://github.com/heksterb).
I don't think I'll make this change. The function is explicitly named after sprintf because it's a secure version of sprintf. The count is about security (not overrunning the buffer) and is only coincidentally similar to snprintf.
