### ISSUE TITLE
Unclear instructions for installing the WPA extension (perf_msvcbuildinsights.dll)

### ISSUE THREAD

**Issue by exoosh** [MicrosoftDocs/cpp-docs#4580]
Quote:

>Visual Studio 2019 version 16.6 **and above.**
... unfortunately there is no `perf_msvcbuildinsights.dll` in VS2022.

The alternative, the instructions state, is the use of [this NuGet package](https://www.nuget.org/packages/Microsoft.Cpp.BuildInsights/) (moniker `Microsoft.Cpp.Buildsights`); alas, again no `perf_msvcbuildinsights.dll` to be found far and wide after downloading and unpacking the package (I am unable to follow the `dotnet add package` instructions, it seems).

So where does one get the `perf_msvcbuildinsights.dll` file from?

Does one really need to keep a VS2019 installation around to make use of this?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8c6235-3094-06cd-e709-bec9d0d8a294
* Version Independent ID: 45e56020-cbf8-7c83-2728-772e65755bdd
* Content: [Tutorial: vcperf and Windows Performance Analyzer](https://learn.microsoft.com/en-us/cpp/build-insights/tutorials/vcperf-and-wpa?view=msvc-170)
* Content Source: [docs/build-insights/tutorials/vcperf-and-wpa.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build-insights/tutorials/vcperf-and-wpa.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @kevcadieux
* Microsoft Alias: **kevca**

**Comment by TylerMSFT** [comment]
We are in the process of moving away from GitHub issues for C++ documentation (we still accept pull requests). For details, please see [Announcing a new way to give feedback on Microsoft Learn](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) This issue will be closed after it is copied to an internal system.

**Comment by NelsonDaniel** [comment]
@exoosh **Thank you** for bringing this to our attention. We need to update the document.

There is no need to copy that file anymore. It already comes with the Windows Performance Toolkit (WPA is part of it) AND the Windows Performance Toolkit gets installed by default with C++ Build Insights (VS 2022)

**Comment by exoosh** [comment]
> @exoosh **Thank you** for bringing this to our attention. We need to update the document.
> 
> There is no need to copy that file anymore. It already comes with the Windows Performance Toolkit (WPA is part of it) AND the Windows Performance Toolkit gets installed by default with C++ Build Insights (VS 2022)

@NelsonDaniel Thanks for leaving this info here already. And thanks for tending to it!

PS: please close at your discretion as I don't know if you still _track_ stuff here until it is done.

**Comment by TylerMSFT** [comment]
Thanks @NelsonDaniel!  And thank you @exoosh  for taking the time to improve the docs. Unfortunately, I need to close this as we are in the process of moving away from GitHub issues. I know that this is being worked on and that your issue will be addressed. Take care.
