### ISSUE TITLE
Broken links in page "Configure and build with CMake Presets in Visual Studio"

### ISSUE THREAD

**Issue by ivancho-ifa** [MicrosoftDocs/cpp-docs#4581]
While browsing [Configure and build with CMake Presets in Visual Studio](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170) I noticed some links are broken. These are the links I've found so far:
- In [Enable vcpkg integration](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#enable-vcpkg-integration)
    - [vcpkg environment variables](https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md)
    - [Using multiple toolchain files](https://github.com/microsoft/vcpkg/blob/master/docs/users/buildsystems/integration.md#using-multiple-toolchain-files)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#enable-vcpkg-integration)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@ivancho-ifa, thank you for pointing this out. I've fixed the links. The fix will be live midday on Monday.
