### ISSUE TITLE
Typo: "atomic::operator|;=" should be changed to "atomic::operator|="

### ISSUE THREAD

**Issue by Alice2O3** [MicrosoftDocs/cpp-docs#4583]
In this document, the title "atomic::operator|;=" should be changed to "atomic::operator|=" (I guess it's simple typo but you know what I mean)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b297703b-5d37-a7d1-945d-22c4791a5448
* Version Independent ID: d642d241-72c1-74c8-8335-ca241679058b
* Content: [atomic Structure](https://learn.microsoft.com/en-us/cpp/standard-library/atomic-structure?view=msvc-170)
* Content Source: [docs/standard-library/atomic-structure.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/atomic-structure.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by Alice2O3** [comment]
Sent a PR, will mark this issue as closed.

**Comment by TylerMSFT** [comment]
Thank you! Alice2O3 (Alice with an 'O') :-)
