### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by gvanem** [MicrosoftDocs/cpp-docs#4589]
The link in this document, https://wg14.link/n2148#dr_400, is dead as a dodo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6183aaac-1eb4-f704-4bf5-1c3fe67ae2fe
* Version Independent ID: d3f24754-fcba-3eee-e34d-445962c5485c
* Content: [/std (Specify Language Standard Version)](https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170)
* Content Source: [docs/build/reference/std-specify-language-standard-version.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/std-specify-language-standard-version.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I have fixed the link. The fix will be live 6/21 afternoon or so.  The Raphus cucullatus lives again ;-)
