### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by BKSHARMA** [MicrosoftDocs/cpp-docs#459]
Excellent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66d18ba-6353-f13c-893f-4f9e3e07047e
* Version Independent ID: d0587f08-db4c-520b-7d34-5c2308ec4ae0
* Content: [Return Value of cl.exe](https://docs.microsoft.com/en-us/cpp/build/reference/return-value-of-cl-exe?view=vs-2017)
* Content Source: [docs/build/reference/return-value-of-cl-exe.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/return-value-of-cl-exe.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@BKSHARMA Glad you liked it.
