### ISSUE TITLE
CWnd class documentation does not load properly

### ISSUE THREAD

**Issue by jdv85** [MicrosoftDocs/cpp-docs#4593]
I don't know if this is the proper place to report this problem, but here goes. When opening https://learn.microsoft.com/en-us/cpp/mfc/reference/cwnd-class, the page never finishes loading. I've tried in both Edge and Chrome.

**Comment by JoshHarmon** [comment]
Ran into this today. It finishes loading, but it takes long enough to go well past the duration after which Chrome pops the Wait dialog.

![image](https://github.com/MicrosoftDocs/cpp-docs/assets/2958794/62e8e47c-eedf-4935-b0d3-a845a76220bb)

**Comment by TylerMSFT** [comment]
I think that years ago they consolidated pages that used to be individual topics. That page is way, way too big.
But it's also not in an area I have time to invest time in, unfortunately :-( We have accrued more issues than our resources can manage so sadly I'm going to have to close this.

**Comment by orcmid** [comment]
The file seems to have been around for about 5 years in its present form.  It appears that performance differences are not related to the file as such (although it is so large that GitHub can't provide a diff).  The publishing process may have changed the creation of HTML and styling/scripting in a manner that does not perform well.  So not much to be done at the authored-form markdown level.
