### ISSUE TITLE
Logic behind default value of MSVC Toolset Version is not documented

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/cpp-docs#4596]
Using the default value for the MSVC Toolset Version doesn't equate using the latest version.

For example, if I have both 14.36 and 14.35 installed in VS 17.6.4:

![image](https://github.com/MicrosoftDocs/cpp-docs/assets/944894/40466a67-1d1b-48b6-8119-ed6c1b1083bb)

It will choose 14.35.

It's hard to tell if it's intended or not, as the documentation doesn't tell what the logic is behind the selection of the default value.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69b82557-4a26-70f9-c7ae-ca21c91318ec
* Version Independent ID: d93c9b26-7bde-7186-0d27-b37ade129b3c
* Content: [Advanced Property Page (Project)](https://learn.microsoft.com/en-us/cpp/build/reference/advanced-property-page?view=msvc-170)
* Content Source: [docs/build/reference/advanced-property-page.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/advanced-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This doesn't look like a doc question but rather product commentary. You can get this in front of the product team by opening Help> Send Feedback> Suggest a Feature, and make your case. If it gets enough upvotes on [Developer Community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fvsfeedback%2Fbrowsecpp&data=04%7C01%7CTyler.Whitney%40microsoft.com%7C8bfd8d05599043e6ac8508d9f73535db%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637812630189523820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JcXLCcvEXjnY5pfU53wsAitE5JMYr%2FO0KzrroO4DxsU%3D&reserved=0), it's just possible it could result in a change. Best of luck.

**Comment by Thieum** [comment]
@TylerMSFT Thanks!

Here is the feedback: https://developercommunity.visualstudio.com/t/Default-value-of-MSVC-Toolset-is-not-doc/10398953?
