### ISSUE TITLE
Link to an online example has gone bad. Suggested replacement included.

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/cpp-docs#4599]
A link to an example at '_codexpert blog_' was added to this page in July 2018. But as of June 2023, that link points to an unrelated webpage (in Romania). To avoid similar external issues in the future, I suggest inserting something along the following lines:

1. In Class Wizard, select the class representing the dialog box.
2. Add a message handler for the `WM_CTLCOLOR `message.
    It will override the CWnd virtual function:
        `HBRUSH CWnd::OnCtlColor(CDC *pDC, CWnd* pWnd, UINT nCtrlColor);`
3. Your derived `OnCtlColor()` must return an `HBRUSH`, so start by calling the base function
    `CWnd::OnCtlColor() `with the same parameters, and save the return value.
4. If ` nCtrlColor ` has the value `CTLCOLOR_DLG`, manipulate the HBRUSH's CDC context as desired, e.g.
    `pDC->SetBkColor( yourRGBvalue );`
5. And finally, return the `HBRUSH `obtained in Step 3.

For more details, such as other `nCtrlColor `values of interest, please refer to` CWnd::OnCtlColor()`,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 268838a0-787f-78b1-2f55-588f31736cc6
* Version Independent ID: 76428f78-9cff-36f0-bf3d-79a7adee8e33
* Content: [Setting the Dialog Box's Background Color](https://learn.microsoft.com/en-us/cpp/mfc/setting-the-dialog-boxs-background-color?view=msvc-170&viewFallbackFrom=vs-2017)
* Content Source: [docs/mfc/setting-the-dialog-boxs-background-color.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/setting-the-dialog-boxs-background-color.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I don't see a link to an example in this topic. Closing.
