### ISSUE TITLE
/Zo (Enhance Optimized Debugging) switch is missing from this list

### ISSUE THREAD

**Issue by reye** [MicrosoftDocs/cpp-docs#460]
See https://docs.microsoft.com/en-us/cpp/build/reference/zo-enhance-optimized-debugging?view=vs-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2353367-e490-5dc3-fc39-3bcba30bf365
* Version Independent ID: 4300089e-7ea0-68bf-eb1f-c9c31cdb8d41
* Content: [Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2017)
* Content Source: [docs/build/reference/compiler-options-listed-alphabetically.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/compiler-options-listed-alphabetically.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@reye You're right, that's an obvious oversight. This is the sort of thing you can propose an edit PR for, if you're so inclined.

**Comment by PritishSehzpaul** [comment]
Hi. Is this still open? Can I contribute somehow?

**Comment by reye** [comment]
Does PR mean Pull Request?

**Comment by reye** [comment]
Does PR mean Pull Request?

**Comment by mikeblome** [comment]
@reye yes PR is pull request.

**Comment by mikeblome** [comment]
fixed
