### ISSUE TITLE
ODBC and MFC - thinks ODBC 13 is the latest.

### ISSUE THREAD

**Issue by Gilesey** [MicrosoftDocs/cpp-docs#4600]
This article states that the `Microsoft ODBC Driver 13 for SQL Server` is the latest driver.
Is that true? I've successfully been running a highly complex CDatabase/MFC monolith with ODBC 17 and ODBC 18 drivers. 
Should this article link to a version agnostic ODBC Driver page so that it's less brittle in future?
Or is there really a compatibility issue between MFC that restricts it to the 13 driver?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6a9d-d5ba-6246-063f-ede88395ace1
* Version Independent ID: 8c8ae57a-7f08-799b-7118-0cc7c1b8281b
* Content: [ODBC and MFC](https://learn.microsoft.com/en-us/cpp/data/odbc/odbc-and-mfc?view=msvc-170)
* Content Source: [docs/data/odbc/odbc-and-mfc.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/data/odbc/odbc-and-mfc.md)
* Product: **visual-cpp**
* Technology: **cpp-data**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
