### ISSUE TITLE
Not helpful.

### ISSUE THREAD

**Issue by conqueran** [MicrosoftDocs/cpp-docs#4601]
This wasn't helpful. Despite following the instructions here. My project still can't find the files. I do not know what I'm doing wrong. The examples aren't clear.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cec7ea59-1270-7e09-8240-651d34d7e758
* Version Independent ID: e004b9b0-4031-8bd9-b2bf-247656829ebe
* Content: [/I (Additional include directories)](https://learn.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-170)
* Content Source: [docs/build/reference/i-additional-include-directories.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/i-additional-include-directories.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This may be something to take up on [C++ Q & A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
