### ISSUE TITLE
FYI: the diamond problem is solved!

### ISSUE THREAD

**Issue by joortcom** [MicrosoftDocs/cpp-docs#4603]
@TylerMSFT

I'm reading your doc about multiple inheritance at:

https://learn.microsoft.com/en-us/cpp/cpp/multiple-base-classes?view=msvc-170

And I just want to let you know: the diamond problem is solved! please check here:

https://github.com/joortcom/DDIFI

**The diamond problem solved!** Using virtual property to decouple the data dependency of the subclass on the superclass, as a **clean** and **general** solution to multiple inheritance.

If the company are interested, I can goto Microsoft and give a presentation talk about the design pattern.

Regards.

**Comment by joortcom** [comment]
@corob-msft FYI.

**Comment by TylerMSFT** [comment]
@joortcom - thank you for your note. Sorry for the delay - I am swamped.
Thank you for your kind offer, but I'm not in a position to invite people to speak at MSFT. 
I think that's cool that you've worked out a solution to this problem. I have to doc to the typical case, and noticed the patent pending in your link. So I wouldn't be able to refer to that. I do wish you well!
