### ISSUE TITLE
/openmp:llvm - Documentation does not list all supported platforms.

### ISSUE THREAD

**Issue by exo-dbahadir** [MicrosoftDocs/cpp-docs#4607]
The documentation says:
> Currently, the /openmp:llvm option only works on the x64 architecture.

However, according the the [Microsoft Blog](https://devblogs.microsoft.com/cppblog/openmp-updates-and-fixes-for-cpp-in-visual-studio-2019-16-10/) support for x86 and arm64 platform has already been added in 2021.

I think, the documentation should be fixed to reflect the correct state of development.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c23f71d-4fe6-e91a-2331-900bc86f78b1
* Version Independent ID: 37bcd3b7-8072-c6b7-4da1-97258dc85883
* Content: [/openmp (Enable OpenMP Support)](https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170)
* Content Source: [docs/build/reference/openmp-enable-openmp-2-0-support.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/openmp-enable-openmp-2-0-support.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@exo-dbahadir , thank  you for catching this. I've updated the doc. It should be live tomorrow afternoon.
