### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by RGSS3** [MicrosoftDocs/cpp-docs#4608]
There is a typo in the first example, `for_each_string1.cpp`
it reads

```C++
   wprintf("/n");
```

which seems to be
```C++
   wprintf("\n");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3640d4-67c5-85a7-dae9-01ea1296f231
* Version Independent ID: 8f262c1b-6b36-81a1-c65f-885f9d572cbd
* Content: [for each, in](https://learn.microsoft.com/en-us/cpp/dotnet/for-each-in?view=msvc-170)
* Content Source: [docs/dotnet/for-each-in.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/dotnet/for-each-in.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@RGSS3, thank you for pointing that out. I've fixed it. The topic will be updated live by tomorrow (6/30).
