### ISSUE TITLE
WPF Equivalent?

### ISSUE THREAD

**Issue by laserbeak** [MicrosoftDocs/cpp-docs#461]
WPF Equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e83cfa3-5607-eee5-3dcc-ff6f9d7a38a7
* Version Independent ID: e9776687-d719-8709-7b58-eff33d5b587a
* Content: [Evening the Spacing Between Controls](https://docs.microsoft.com/en-us/cpp/windows/evening-the-spacing-between-controls?view=vs-2017)
* Content Source: [docs/windows/evening-the-spacing-between-controls.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/evening-the-spacing-between-controls.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@laserbeak The resource editor in C++ doesn't understand WPF and C++/CLI is not really intended for UI development. If you still need an answer here I suggest starting here: https://docs.microsoft.com/en-us/visualstudio/designers/designing-xaml-in-visual-studio?view=vs-2017 .
