### ISSUE TITLE
C26478 (move from const) issued on correct code

### ISSUE THREAD

**Issue by Taw3e8** [MicrosoftDocs/cpp-docs#4610]
I believe warning C26478 is based on incorrect information. The [article](https://learn.microsoft.com/en-us/cpp/code-quality/c26478?view=msvc-170#remarks) states:
"When called on a const object, `std::move` returns a copy of the object, which is likely not the developer's intent."

Which is clearly wrong since `std::move` is a cast to rvalue - it only changes value category of the expression. As such it performs no actual operations. 
The article cites one source: paragraph [ES.56](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es56-write-stdmove-only-when-you-need-to-explicitly-move-an-object-to-another-scope) of CppCoreGuidelines which in turn cites: S. Meyers. Effective Modern C++ (O’Reilly, 2015) in which Mayers writes: "Move requests on const objects are silently transformed into copy operations.". This is true only if said object (function) provides no `const &&` overload and `const &` one is used instead where move semantics cannot apply.

Example of a use case is shown here: https://godbolt.org/z/53Mce4TnP
MSVC issues C26478 warning on both (correctly) used: (const) move assignment operator and (const) move constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10fa6596-5586-bc91-5434-fb86e078d5aa
* Version Independent ID: d914fbd5-a0f9-d522-8ff2-5cf876db58f2
* Content: [Warning C26478](https://learn.microsoft.com/en-us/cpp/code-quality/c26478?view=msvc-170#remarks)
* Content Source: [docs/code-quality/c26478.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c26478.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by Taw3e8** [comment]
Warning C26478 Article 10/24/2023:
"Because const objects can't be moved, calling std::move on them has no effect."
The effect of calling `std::move` is change of the value category of the expression.

**Comment by TylerMSFT** [comment]
We recently updated the wording for this topic. If it doesn't address your concern, please reopen this issue.
