### ISSUE TITLE
Folder description wrong

### ISSUE THREAD

**Issue by HarryDolan** [MicrosoftDocs/cpp-docs#4612]
[Enter feedback here]

You say to open the File Explorer to find the Debug folder.  But there is none.  However there is a 'x86' folder and THAT contains the Debug folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d597b582-59ec-2014-699b-6aac8db69cf6
* Version Independent ID: 81941537-4446-9c5a-6af3-25318396420d
* Content: [Build and run a C++ console app project](https://learn.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=msvc-170)
* Content Source: [docs/build/vscpp-step-2-build.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/vscpp-step-2-build.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@HarryDolan - Hi. You're right--for certain versions of Visual Studio. For 2015, 2017, and 2019 it is `debug` as specified. In `2022` it became `x64\debug`  I've updated the topic so that depending on the VS version selector, it refers the right place. The update should be live by tomorrow, 7/6
