### ISSUE TITLE
ML /Gz for __stdcall conventions for function calls and names.

### ISSUE THREAD

**Issue by yodacodem** [MicrosoftDocs/cpp-docs#4613]
This is completely trite, but the page uses an upper case 'Z' when in fact ML requires a lower case 'z' in the /Gz command line option. When compiling with the upper case 'Z' the following is displayed: MASM : warning A4018: invalid command-line option : /GZ. When the lower case 'z' is used it works fine. I should add I am using a very old version of masm32. See, told you it was trite!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4eaa981-a205-47f7-12f9-09f8b3c95919
* Version Independent ID: 43ba0448-bad1-4298-cedb-e8580051ebea
* Content: [ML and ML64 command-line reference](https://learn.microsoft.com/en-us/cpp/assembler/masm/ml-and-ml64-command-line-reference?view=msvc-170)
* Content Source: [docs/assembler/masm/ml-and-ml64-command-line-reference.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/assembler/masm/ml-and-ml64-command-line-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@yodacodem - this is a good thing to fix. Thank you for pointing it out.
I fixed it and it'll go live tomorrow (or maybe Wed because of the July 4th holiday). Thanks for taking the time to point this out.
