### ISSUE TITLE
git

### ISSUE THREAD

**Issue by AnibestJose** [MicrosoftDocs/cpp-docs#4622]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 797397ff-b0bb-2e4f-dddc-88f8c5691817
* Version Independent ID: 86034cb0-358a-9fd4-e522-7dca10d627ae
* Content: [Deploy an App By Using the Redistributable Package (C++)](https://learn.microsoft.com/en-us/cpp/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package?view=msvc-170&source=recommendations)
* Content Source: [docs/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, no feedback provided so I don't know what you want here. Please reopen with details.
