### ISSUE TITLE
IOS samples

### ISSUE THREAD

**Issue by gkarabin** [MicrosoftDocs/cpp-docs#4624]
[Enter feedback here]

It would be helpful to see iOS samples. Android is relatively straightforward and little has changed since Xamarin.Android. iOS seems to have had more changes, or at least, nugets that I am preparing for static libraries for net7.0-ios are not easy to port from Xamarin.iOS. Any up-to-date examples could only help.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18740be5-c9f7-69aa-a5cb-505f562298b9
* Version Independent ID: 32400d1a-db89-c42e-d9a1-b02a33392e31
* Content: [Cross-platform mobile development examples](https://learn.microsoft.com/en-us/cpp/cross-platform/cross-platform-mobile-development-examples?view=msvc-170)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-examples.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cross-platform/cross-platform-mobile-development-examples.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I agree. We are not resourced right now for many things we'd like to do. I'll keep this on the list but it may be some time before I can get to it. I've also tagged this for community help if someone would like to contribute an example.

**Comment by gkarabin** [comment]
Thanks, @TylerMSFT. I'm somewhat limited by my company's corporate on code release, but if I manage to get the appropriate releases I will see what I can do.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
