### ISSUE TITLE
Warning C5262 does not work in VS 17.4.4

### ISSUE THREAD

**Issue by jtooker** [MicrosoftDocs/cpp-docs#4625]
I tried enabling warning C5262 in visual studio 17.4.4 and it would give me any warnings (or errors if I enabled this warning as an error).  Everything compiled just fine, even with missing [[fallthroughs]].

A coworker was on VS 17.5 and said the warning worked just fine when turned on.

I upgraded to VS 17.6.4 and it is working fine for me too.

So my complaint is that this page says support was added in 17.4, but it was not so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f06ab37-d9d8-0f3d-51df-6a1b787174f0
* Version Independent ID: 1f06ab37-d9d8-0f3d-51df-6a1b787174f0
* Content: [Compiler warning (level 1, error, off) C5262](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5262?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/c5262.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/c5262.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TartanLlama** [comment]
You can see it working on VS 17.4 here: https://godbolt.org/z/qWTTWKj4Y
