### ISSUE TITLE
Extremely Helpful!!

### ISSUE THREAD

**Issue by AllisonBrand** [MicrosoftDocs/cpp-docs#4626]
Everytime I've read C or C++ code, I'd get so confused by the flow of it. Where are all the definitions? I go to the header file, but unlike a library in Java or Python module, it's just got declarations. How is that even running? I find defintions in isolated files that aren't included anywhere, so I figure they must not be used and barely read them. What do all these mystery functions do? What runs first? I know C++ is supposed to be like Java so I expected to be able to read the code without explicitly knowing the language. 

Now it makes so much sense! The declarations are the only thing that has to be explicitly shared. The linker finds the definitions during build. Things can only be defined once, and that definition connects to the declaration that _is_ included.

I know this is supposed to be used for raising an issue, but the button was under **Feedback** and I want to give feedback.

This page clears up so much confusion!  It's times like this that make me wish I could rate webpages - 5 stars all around.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c99df644-075c-fe3f-3e5a-94cb7f7edde8
* Version Independent ID: 0d48190e-803b-316b-5b79-82245d103c46
* Content: [Header files (C++)](https://learn.microsoft.com/en-us/cpp/cpp/header-files-cpp?view=msvc-170)
* Content Source: [docs/cpp/header-files-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/header-files-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you! Appreciate you taking the time to comment.
Have a great day.
