### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by paule32** [MicrosoftDocs/cpp-docs#4633]
[Enter feedback here]
Thanks for the exploration. Some code Examples will be good.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87848fec-98e6-32fe-8edb-c90b2ac0cd20
* Version Independent ID: e4e9df75-c5bf-59f1-3eac-14f3becaee0e
* Content: [Process and Environment Control](https://learn.microsoft.com/en-us/cpp/c-runtime-library/process-and-environment-control?view=msvc-170)
* Content Source: [docs/c-runtime-library/process-and-environment-control.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/process-and-environment-control.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I agree, but unfortunately, due to resourcing, I won't be able to get to this.
I've tagged it for community help and will leave it open for a while to see if we get any takers. If not, I'll close it.
