### ISSUE TITLE
Message pragma example is not properly formatted to act as a link in visual studio

### ISSUE THREAD

**Issue by stoopdapoop** [MicrosoftDocs/cpp-docs#4634]
The example code on the message page has this line:
`#pragma message (__FILE__ "[" STRING(__LINE__) "]: test")`

This doesn't work as intended. The square brackets need to be replaced with parenthesis or else the user won't be able to click on the message line and get directed to the file and line being referenced.

It should look like this:
`#pragma message (__FILE__ "(" STRING(__LINE__) "): test")`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3061ec67-e5c7-3bbe-7736-40934923bb53
* Version Independent ID: edce594a-08f1-a658-5435-e854eb1b3781
* Content: [message pragma](https://learn.microsoft.com/en-us/cpp/preprocessor/message?view=msvc-170&redirectedfrom=MSDN)
* Content Source: [docs/preprocessor/message.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/message.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stoopdapoop** [comment]
Ok, well then here's a pull request.

https://github.com/MicrosoftDocs/cpp-docs/pull/4945

**Comment by TylerMSFT** [comment]
Thank you. I merged your PR - it should be live tomorrow. Thank you for going the extra mile, here.
