### ISSUE TITLE
"Configure and build with CMake Presets in Visual Studio" lists incorrect supported CMakePresets versions

### ISSUE THREAD

**Issue by yeputons** [MicrosoftDocs/cpp-docs#4635]
The "Supported CMake and CMakePresets.json versions" section says the following:

> Visual Studio 2019 version 16.10 and later support schema versions 2 and 3.
> Visual Studio 2022 version 17.4 preview 2 adds support for schema versions 4 and 5.

However, it is definitely not the case for Visual Studio 2022 version 17.4: it does not support version 5. I was unable to loading a project using schema version 5.

[Changelogs for 17.4](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.4) say the following:

> Added support for CMake Presets version 4. See the [CMake release notes](https://cmake.org/cmake/help/v3.23/release/3.23.html#id6) for details of what is available.

[Changelogs for 17.5](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.5) say the following:

> Added support for CMakePresets.json version 5. See the [CMake documentation](https://cmake.org/cmake/help/v3.24/manual/cmake-presets.7.html) for information of new features.

It seems that schema version 5 was only supported in 17.4. I'm not sure about support for versions 2 and 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by sinemakinci1** [comment]
@yeputons Thank you for your feedback! The documentation has been updated with the right VS versions for CMake support. Hope this helps

**Comment by sinemakinci1** [comment]
Hi @yeputons , thank you for the feedback. We have updated the documentation for the right preset support mapping. Please let us know if you have any other issues!
