### ISSUE TITLE
Description of stdin, stdout, and stderr is off the mark

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/cpp-docs#4640]
Odd, I just left feedback another way and wanted to PS about it.

OK, the C language example here is crazy.  One would not write 

```C
FILE* stdin;
FILE* stdout;
FILE* stderr;
#include <stdio.h>
```

I would expect this to fail badly somehow.  Especially because it seems that in the current `stdio.h`, these symbols are pre-processor defined and expanded to calls on a procedure
that returns FILE* results.

I Have no idea how to clean this up without a deep-ending TMI, but the explanation about them being constants is just not it.  (I suspect this technique is what provides for run-time reassignment of those FILE choices.)   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 095f605e-d578-a7bb-ceca-63c938e6f591
* Version Independent ID: ab97e366-18c6-61d0-fe98-43dc6c2201cb
* Content: [stdin, stdout, stderr](https://learn.microsoft.com/en-us/cpp/c-runtime-library/stdin-stdout-stderr?view=msvc-170)
* Content Source: [docs/c-runtime-library/stdin-stdout-stderr.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/stdin-stdout-stderr.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
Here's what I'm talking about.  This is in VS Code with Build Tools (and SDK) 17.6.0.

![F23xy061-2023-07-21-0930-VS-17 6 0-stdout-Intellisense](https://github.com/MicrosoftDocs/cpp-docs/assets/3372580/3877029c-c2ee-46d0-b74d-581793ce94e9)

**Comment by TylerMSFT** [comment]
Yes - that's weird. I replaced the syntax block with their actual definitions. Should be live by midday tomorrow. Thanks for pointing this out.

**Comment by orcmid** [comment]
I hope you didn't expose the `__acrt_iob_func()`, leaking the implementation.

I'll take a look.

**Comment by orcmid** [comment]
OK, "implementation-defined" is much better.
