### ISSUE TITLE
Bad __declspec(noreturn) example

### ISSUE THREAD

**Issue by Kipt** [MicrosoftDocs/cpp-docs#4649]
The example on `__declspec(noreturn)` uses the attribute to avoid warnings regarding missing return statements. However, the example uses `int main` which is guaranteed by the standard to `return 0` - _even if no return statement is issued_.

I suggest using _any_ other function to illustrate the benefit of the functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415b2ec5-015d-3db4-2fe1-2ec6f843757b
* Version Independent ID: 3420886f-4874-cf7d-fc1b-4f42becf5d76
* Content: [noreturn](https://learn.microsoft.com/en-us/cpp/cpp/noreturn?view=msvc-170)
* Content Source: [docs/cpp/noreturn.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/noreturn.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
True. Will add to the queue.
