### ISSUE TITLE
Can we add a link to a simple how to page here?

### ISSUE THREAD

**Issue by ChrisOfTheLewi** [MicrosoftDocs/cpp-docs#4655]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

My team and I were looking through this page, and while it has some great advanced information, I'm not seeing it show the steps needed to configure an existing C++ project in visual studio.  While that is not hard for someone who knows VS well, it has come up as an ask from developers to us several times.  Id be happy to contribute here with some guidance or an attempt at drafting it too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6aef91f3-0339-5375-2afb-b3ff3fdb3d00
* Version Independent ID: f7f7ed30-fa93-d7b8-9aa6-5ed372338568
* Content: [Configure C++ projects for ARM processors](https://review.learn.microsoft.com/en-us/cpp/build/configuring-programs-for-arm-processors-visual-cpp?view=msvc-170&branch=main)
* Content Source: [docs/build/configuring-programs-for-arm-processors-visual-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/configuring-programs-for-arm-processors-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This is done. Will be live 7/27
