### ISSUE TITLE
Code example errors in page: "How to: Modify C++ project properties and targets without changing the project file"

### ISSUE THREAD

**Issue by p-soma** [MicrosoftDocs/cpp-docs#4659]
There are syntax errors in the example .vcxproj imports at the bottom of this page. Also, the example code is labeled as 'Windows Command Prompt' but it seems to be an example from a Visual Studio project file rather than command prompt.

![image](https://github.com/MicrosoftDocs/cpp-docs/assets/46449481/218ca55e-6b5c-414c-bb13-69b2012ec74c)

If I copy this example as-is into a .vcxproj file in VisualStudio 2022, then the project fails to load.

I think the example should be like this instead:

```xml
<Import Project="C:\sources\my_props.props" />
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
<Import Project="C:\sources\my_target.targets" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2b9695-6c7e-79bb-5169-0bb4b0af3797
* Version Independent ID: 1b91693b-6f6a-9da1-94a9-e0c0a4650286
* Content: [How to: Modify C++ project properties and targets without changing the project file](https://learn.microsoft.com/en-us/cpp/build/modify-project-properties-without-changing-project-file?view=msvc-170)
* Content Source: [docs/build/modify-project-properties-without-changing-project-file.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/modify-project-properties-without-changing-project-file.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for pointing that out @p-soma. Fixed. The updates will be live early next week.
