### ISSUE TITLE
Incorrect error

### ISSUE THREAD

**Issue by DrrMorris** [MicrosoftDocs/cpp-docs#466]
Why doesn't visual studio properly handle C programs anymore.

#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;

int main()
{
    sayHi();
    return 0;
}

void sayHi(){
    printf("Hello User");
}

the preceding code is properly formatted, but because it is a .c and not a .cpp Visual studio cant' handle it.
I would like to be able to use your tool, as I do other development work, but is doesn't handle anything but Microsoft Centric languages easily. I will be going back to linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d76d2fd-fd60-4fa2-59e4-73474d0a743e
* Version Independent ID: 33085254-0592-a16e-1b1d-40abaeeeb8aa
* Content: [Compiler Error C2371](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2371?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2371)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2371.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2371.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DrrMorris Your code doesn't compile because it's not legal C code. You need a forward declaration of your `sayHi` function before you call it, unless it returns an `int`.

```
C:\Users\corob\Documents\Projects\curiosity\sayhi>type sayhi.c
#include <stdio.h>
#include <stdlib.h>

int main()
{
    sayHi();
    return 0;
}

void sayHi(){
    printf("Hello User");
}

C:\Users\corob\Documents\Projects\curiosity\sayhi>cl /W4 sayhi.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

sayhi.c
sayhi.c(6): warning C4013: 'sayHi' undefined; assuming extern returning int
sayhi.c(10): error C2371: 'sayHi': redefinition; different basic types
```

The C compiler is invoked by default on source files that have a .c extension. For strict ANSI C89 compatibility, use the /Za compiler option.
