### ISSUE TITLE
I'm happy to report that this page was informative and helpful. 

### ISSUE THREAD

**Issue by BubblyBerty** [MicrosoftDocs/cpp-docs#4660]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a console calculator in C++](https://learn.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=msvc-170&viewFallbackFrom=vs-2022)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by GitTyler** [comment]
Thank you! Appreciate it :-)
