### ISSUE TITLE
Unmatched parentheses on the first paragraph, second line.

### ISSUE THREAD

**Issue by Rageking8** [MicrosoftDocs/cpp-docs#4661]
There seems to be an unmatched parentheses on the first paragraph, second line.

> A module is a set of source code files that are compiled independently of the source files (or more precisely, the [translation units](https://wikipedia.org/wiki/Translation_unit_(programming)) that import them ...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://learn.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Sure enough. Fixed. The fix will go live early next week.
