### ISSUE TITLE
c#questinons answer project text file

### ISSUE THREAD

**Issue by codingidris** [MicrosoftDocs/cpp-docs#4666]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc7f434-4ad2-d8ca-76c3-0ef7043ffcf1
* Version Independent ID: 089283c8-d094-213f-606d-1c19e4308581
* Content: [Compiler Error C2039](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2039?view=msvc-170&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2039)%26rd%3Dtrue)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2039.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/compiler-error-c2039.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by r124c41** [comment]
Yes, the `C2039_d.cs` examples is a bit murky and misplaced here regardless.

**Comment by TylerMSFT** [comment]
@r124c41 - it looks like part of your feedback is missing. What I see that the code sample isn't in a proper code block, which I'll fix.

I don't know what you mean by being misplaced. It is demonstrating a C# component, that is then accessed from C++ to show an example of C2039.

**Comment by TylerMSFT** [comment]
Got it. I fixed the code sample to be in a proper code block, then I added some explanatory text to explain the scenario better. It'll be live tomorrow by mid-morning or so.
