### ISSUE TITLE
What the heck are with the ampersands in the example compare() function??

### ISSUE THREAD

**Issue by leehunt** [MicrosoftDocs/cpp-docs#4669]
[Enter feedback here]

This:
  
  compare( (void *) & elem1, (void *) & elem2 );

Is very misleading.  It should be this:

  int compare( const void *elem1, const void *elem2 );

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 135f5795-2d27-fded-f416-2f5723b85b14
* Version Independent ID: 245a2a7a-b1b4-dcc3-9581-9d6101ed0292
* Content: [qsort](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/qsort.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/qsort.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Yeah, that's messed up. I have fixed it and it'll be live tomorrow by mid-afternoon.
