### ISSUE TITLE
The actual results I obtained during execution are different from those in the article.

### ISSUE THREAD

**Issue by 100001010** [MicrosoftDocs/cpp-docs#4672]
vector v5(5);
for (auto i : v5) {
v5[i] = i;
}

The results I obtained from running the code are different from the results in the article. My results are: v5=0 0 0 0 0, while the results in the article are: v5=1 2 3 4 5.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cd55b4-5345-3493-9d05-12868315571d
* Version Independent ID: 8e501921-6f1d-7705-231b-7ed0eded02ae
* Content: [vector class](https://learn.microsoft.com/en-us/cpp/standard-library/vector-class?view=msvc-170#vector)
* Content Source: [docs/standard-library/vector-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/vector-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by 100001010** [comment]
The content you provided earlier is the last part of an article.

**Comment by TylerMSFT** [comment]
Fixed. I also made a small fix to call out the output for v8 and reformatted the output so it's not all one line, which was also incorrect.
Fix will be live Monday afternoon or so.
