### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool Error	RC2135	file not found: E:\202\GG bY\GG-app-1.ico	SNAKE BYPASS	C:\Users\A\Desktop\BYPASS-PUBG-MOBILE-IMGUI-main\example.rc	46	Build		RC

### ISSUE THREAD

**Issue by Nibras88** [MicrosoftDocs/cpp-docs#4681]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: def241c8-dad4-f404-2a78-cd4c37511bba
* Version Independent ID: cdbf9208-fa7b-8f32-2662-b35ccc356604
* Content: [Resource Compiler Error RC2135](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/resource-compiler-error-rc2135?view=msvc-170&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(RC2135)%26rd%3Dtrue)
* Content Source: [docs/error-messages/tool-errors/resource-compiler-error-rc2135.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/tool-errors/resource-compiler-error-rc2135.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
No feedback on what you want to see here. Closing.
