### ISSUE TITLE
Problems with utf8 chars over ASCII 127

### ISSUE THREAD

**Issue by LuiggyMadrid** [MicrosoftDocs/cpp-docs#4682]
With this code:
`std::string wstr2str(const std::wstring& utf16Str)
{
	std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> conv;
	return conv.to_bytes(utf16Str);
}
`
For example, utf16 char L'á' (ASCII 225 = 0x00E1) is converted as 2 bytes utf8 string "Ã¡" (0xC3 0xA1) instead of 'á' (0xE1)

Znd with this code:
`std::wstring str2wstr(const std::string & utf8Str)
{
	std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> conv;
	return conv.from_bytes(utf8Str);
}`

When you try to convert utf8 "á" (0xE1), an exception arises

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1bafd3-c257-5243-f093-4cf25bde7649
* Version Independent ID: 8e32ffc1-4e29-b4e8-5c82-9e74ff82d476
* Content: [wstring_convert Class](https://learn.microsoft.com/en-us/cpp/standard-library/wstring-convert-class?view=msvc-170&viewFallbackFrom=vs-2017&redirectedfrom=MSDN&devlangs=cpp&f1url=%3FappId%3DDev16IDEF1%26l%3DES-ES%26k%3Dk(XLOCBUF%252Fstd%253A%253Awstring_convert%253A%253Afrom_bytes)%3Bk(std%253A%253Awstring_convert%253A%253Afrom_bytes)%3Bk(from_bytes)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [docs/standard-library/wstring-convert-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/wstring-convert-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by LuiggyMadrid** [comment]
Thanks for the explanation, @orcmid . So, this class can't be used to convert std::string ("á") into std::wstring (L"á") or viceversa

**Comment by TylerMSFT** [comment]
Thanks, orcmid. These issues are meant to raise problems with the docs. A better place for questions like this is https://learn.microsoft.com/en-us/answers/tags/314/cpp.
Closing.
