### ISSUE TITLE
/kernel documentation doesnt exist in msvc linker docs

### ISSUE THREAD

**Issue by wmmc88** [MicrosoftDocs/cpp-docs#4684]
This page indicates that the `/kernel` flag is passed along to the linker, but documentation for a `/kernel` option does not exist in the msvc link documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab4cd21-5a26-620f-9bd4-403a02b2b915
* Version Independent ID: 41e125c3-a7bc-69cb-7142-43974c5fe519
* Content: [/kernel (Create kernel mode binary)](https://learn.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary?view=msvc-170)
* Content Source: [docs/build/reference/kernel-create-kernel-mode-binary.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/kernel-create-kernel-mode-binary.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
I don't know what page you are referring to.

But, does this help?

https://learn.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary

**Comment by wmmc88** [comment]
> I don't know what page you are referring to.
> 
> But, does this help?
> 
> https://learn.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary
> 
> Perhaps a cross-reference would be valuable.

That link is content that i link to in my OP. It is a section under the MSVC **_compiler_** options. Given that the `/kernel` flag is supposed to be passed to both the compiler and the linker, I was expecting to see a corresponding page under the MSVC **_linker_** options section (ie. somewhere in https://learn.microsoft.com/en-us/cpp/build/reference/linker-options?view=msvc-170).

**Comment by orcmid** [comment]
I don't know about any compiler option.  It is definitely a linker option.  If you run

'''bat
link /? | more
```

you'll see it.  If you do the same with `cl /?` there is no /kernel option listed.  It lists the
`/link` option but does not list the linker options that can be included. It has to come in after a `CL /link` option and that has nothing to do with compile-time anything. 

I just checked those with the 17.7.1  VS2022 Command Prompt for x64 environment.

So omission in the list of linker options is a defect on the linker-options page. 

 Could there be a confusion about how CL.exe will run link.exe automatically under the covers unless told not to (`/c` option)?  If you are running that way, yes you give CL the `/link /kernel` options but it has nothing to do with the compilation stage, just the link stage.  Everything I am seeing is consistent with that.

**Comment by TylerMSFT** [comment]
I'll give myself a workitem to doc the /KERNEL flag for the linker. Thanks for calling this out.

**Comment by TylerMSFT** [comment]
I documented /kernel. It'll be live by tomorrow (Tues) afternoon.
