### ISSUE TITLE
Detail __fastcall behaviour for enum and PODs

### ISSUE THREAD

**Issue by Lectem** [MicrosoftDocs/cpp-docs#4688]
I think it would be nice to document that all types that are not numeric or enums, even if PODs, will not be passed by registers.

I would change 

> The __fastcall calling convention specifies that arguments to functions are to be passed in registers, when possible.

To 

> The __fastcall calling convention specifies that arguments to functions are to be passed in registers, when possible. `enum` types will be passed in registers if their underlying type would be passed in registers. `class`, `struct` and `union` types are always pushed on the stack. 

See example here:

https://godbolt.org/z/KPj144n13

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2a242-562b-5751-a390-5266a00a8536
* Version Independent ID: b9767a75-83b6-d0d2-53e3-50315874ee06
* Content: [__fastcall](https://learn.microsoft.com/en-us/cpp/cpp/fastcall?view=msvc-170)
* Content Source: [docs/cpp/fastcall.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/fastcall.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, @Lectem,
I will add this info. Basically:
-	classes, structs, and unions are all lumped together by the backend as “multibyte” types (regardless of size). 
-	enums and enum classes are represented in the backend by their underlying type, INT or UINT of various sizes.
-	When handling params/args for __fastcall, operands that the backend sees as INT and UINT of size 8, 16, or 32 bits can be passed in registers.
o	This will include enums if their underlying types fit those descriptions.
-	Multibyte types are always passed on the stack, even if they could fit into a register.
I have another work item I'm focused on, but I'll return to this.

**Comment by Lectem** [comment]
Awesome thanks!

**Comment by TylerMSFT** [comment]
I've made these updates. The changes should be live by tomorrow afternoon.
