### ISSUE TITLE
Please add that if you set the code page in the UTF-8 encoded resource file to a code page that only accepts ASCII, it will cause RC2104 error as well

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/cpp-docs#4692]
I would like to suggest adding a message indicating that, if the resource file is encoded in UTF-8, yet the code page defined is using a code page where it can only accept ASCII (for example, SHIFT_JIS code page 932 only accepts ASCII encoded text), then it will cause the compiler to throw the error message RC2104.

As an example, if you have a resource file that auto-generated the following `#if` guard:

```cpp
#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_JPN)
#ifdef _WIN32
LANGUAGE LANG_JAPANESE, SUBLANG_DEFAULT
#pragma code_page(932)
#endif //_WIN32
```

Be aware of the encoding of the file's content.

Thank you. Please consider this feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e440c9b9-0002-e345-373b-e9597f63b80b
* Version Independent ID: 48b54450-ba87-9a4b-dca8-f62e630d9b0d
* Content: [Resource Compiler Error RC2104](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/resource-compiler-error-rc2104?view=msvc-170)
* Content Source: [docs/error-messages/tool-errors/resource-compiler-error-rc2104.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/tool-errors/resource-compiler-error-rc2104.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hello, yes, code pages are tricky. The compiler is doing what it's supposed to do and I'm not sure calling out that it's going to do it adds any value. What would be required is a discussion of the principles behind what's going on and I simply don't have time to do that and won't for a very long time given my current schedule. What I've done is flag this to see if anyone in the community wants to give it a go. If I don't see a response after a week or two, I'll close it out, unfortunately.

**Comment by tommai78101** [comment]
Ah, I see. Understandable, given how this requires a specific domain knowledge in order to dig deeper and make out what is happening down there.

**Comment by TylerMSFT** [comment]
Hi,
Closing as part of backlog grooming. We have accrued more issues than our resources can manage.
Criteria for closing include severity of the issue, how broadly applicable it is, whether the issue enough information is provide to act on the issue, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.

**Comment by tommai78101** [comment]
@TylerMSFT Thanks again for the help.
