### ISSUE TITLE
CMakeSettings documentation should be replaced/updated with CMakePresets

### ISSUE THREAD

**Issue by jeffkohn-swi** [MicrosoftDocs/cpp-docs#4695]
CMakeSettings.json is obsolete, most CMake projects are using CMakePresets.json these days. Updated info on how to configure clang-tidy with CMakePresets.json would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f9a6a82-c89c-673f-0db3-9d4e2689c956
* Version Independent ID: 93c77d1a-b248-a12e-b13f-9ab299e88066
* Content: [Using Clang-Tidy in Visual Studio](https://learn.microsoft.com/en-us/cpp/code-quality/clang-tidy?view=msvc-170)
* Content Source: [docs/code-quality/clang-tidy.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/clang-tidy.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I'm sorry to have to close this but we have accrued more issues than our resources can manage. Criteria for closing include severity of the issue, how broadly applicable it is, how well it lines up with current priorities, etc.
If you think this issue should not have been closed, reopen it with a comment explaining why.
