### ISSUE TITLE
Clarify whether link.exe's /APPCONTAINER option applies to DLLs

### ISSUE THREAD

**Issue by jakepetroules** [MicrosoftDocs/cpp-docs#47]
As seen on https://docs.microsoft.com/en-us/cpp/build/reference/appcontainer-windows-store-app, the documentation is not explicitly clear whether this option applies only to EXEs, or DLLs as well.

If I build a native DLL with cl.exe and pass /APPCONTAINER to the linker, the 0x1000 (IMAGE_DLLCHARACTERISTICS_APPCONTAINER) bit **is** present in the resulting PE file's DllCharacteristics field. However the C# compiler only has a separate /out: option for app containerized _EXEs_, but not DLLs, which would seem to suggest that either link.exe (by adding the flag) or csc (by lacking an option to set the flag for DLLs) is in error.

So: is /APPCONTAINER supposed to apply to DLLs as well? If so, why doesn't the C# compiler have such an option as well?

**Comment by corob-msft** [comment]
The IMAGE_DLLCHARACTERISTICS_APPCONTAINER bit set by the linker /APPCONTAINER option tells the OS that this image can only run in an appcontainer. This bit is not required for every code image that runs in an appcontainer. So, the short answer to your question is that the /APPCONTAINER switch can apply to any DLL or EXE, as you would expect. You can set the bit on C# DLLs by using EDITBIN /APPCONTAINER *filename*.dll if you like. This restricts that DLL to running in an appcontainer, so presumably it can only be loaded by an executable that is also running in an appcontainer. The IMAGE_DLLCHARACTERISTICS_APPCONTAINER bit is apparently not required for DLLs that are loaded by appcontainer apps, as long as the DLLs don't call disallowed APIs. I don't have an explanation for why CSC does not include an option to set it in libraries.

**Comment by jakepetroules** [comment]
> The IMAGE_DLLCHARACTERISTICS_APPCONTAINER bit is apparently not required for DLLs that are loaded by appcontainer apps, as long as the DLLs don't call disallowed APIs.

Exactly what I was looking for, thank you!
