### ISSUE TITLE
Presentation leaves much to be desired...

### ISSUE THREAD

**Issue by death2gods** [MicrosoftDocs/cpp-docs#4701]
[Enter feedback here]
Left nav panel can't be collapsed or resized ... got to the indicate page via 'net search and frankly don't want or need the nav panel.  It's wasting space; if this page doesn't have what I need I'll got back to the window with the search results, I pretty much never, ever use the nav panel.  If it would collapse I could at least get it out of my way, and if I did decided to browse the site for some reason, I may always expand it.

Right "Additional Resources" panel is a flat-out useless waste of screen space.  It literally contains nothing that even pays lip service to being remotely related to the current page, which means it's not resourceful in context.  As in if it suggested updating the firmware in my car's ECU, it would be just as relevant as what I see.  Best remedy: REMOVE THE RIGHT SIDE PANEL FOREVER.  Second best: make that a flyout I may hover over if I WANT to see it, don't shove irrelevent garbage in my face.

I don't surf with a full-screen window, but when I do make it full screen, the useless, space wasting left & right panels grow significantly, insuring that even full-screen users have the least desirable, most screen-wasting, useless scroll-fest experience possible, where the main content area enjoys barely a third of the available width.  The point of this page IS the main content, it IS NOT useless "navigation" and "suggestion" panels, which should remain narrow and unobtrusive at worst, and be hidden or missing entirely at best.

If the intent to make the content, the actual real page information, as illegible as possible, then the presentation is perfect.  Don't touch a thing.  If the intent is to make the content user friendly, there's room for improvement.  Lots of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01d1fc7d-eeb2-d7c6-3d79-0a69732864a3
* Version Independent ID: 8e53ef60-ff33-38af-8ee9-73a6bf8b8853
* Content: [How to: Create a C++ Project from Existing Code](https://learn.microsoft.com/en-us/cpp/build/how-to-create-a-cpp-project-from-existing-code?view=msvc-170)
* Content Source: [docs/build/how-to-create-a-cpp-project-from-existing-code.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/how-to-create-a-cpp-project-from-existing-code.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
The learn creation to web publication process is rather complex.  I am uncertain where to provide this feedback.  I suspect it is not here though.  Here it must be about content, not the publishing system.  I have seen some related issues over on the Microsoft/Docs Contribute pages.  

I hope @TylerMSFT can find a place to pass this on.

**Comment by TylerMSFT** [comment]
This site is about content. I don't have any control over the publishing system. I'll try to find who to even forward this on to. Closing.
