### ISSUE TITLE
#warning is not listed which is a bit annoying because it means there is no cpp doc with all directives in msvc listed.

### ISSUE THREAD

**Issue by thatTPR** [MicrosoftDocs/cpp-docs#4703]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8649ec5-09cf-8157-8bbb-f71dc329b669
* Version Independent ID: d991cbe7-79f0-a43d-5331-f16e9632deab
* Content: [Preprocessor directives](https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-directives?view=msvc-170)
* Content Source: [docs/preprocessor/preprocessor-directives.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/preprocessor-directives.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
That's because we don't support this preprocessor directive yet.
