### ISSUE TITLE
Issue with LONG_MIN, LONG_MAX value in the document

### ISSUE THREAD

**Issue by Mayank-Jain-1** [MicrosoftDocs/cpp-docs#4705]
I was reading the document for finding the Limit values of different types in C++, when i noticed that INT_MIN and LONG_MIN has the same values. It seemed wrong to me so i confirmed by running it my local cpp compiler and also checked some other documents for the correct value i.e. -9223372036854775808. Same goes for the LONG_MAX value. 

There might be some other corrections as well.
If you find the problem i highlighted as an issue i will be glad to contribute. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3172ab8c-37b9-1ce6-eeac-339ffed758b1
* Version Independent ID: b262c777-3978-8cd2-0173-b7f95b77ca1e
* Content: [C and C++ Integer Limits](https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170)
* Content Source: [docs/c-language/cpp-integer-limits.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/cpp-integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
The documentation is correct and it is specific to the VC/C++ compiler, CL.exe, and its standard libraries.

It is permissible for INT and LONG  Limit values to be the same and that is in fact the Microsoft implementation on x64.  The ISO Standard rule is that the range of LONGs cannot be smaller than that of INT, and the INT range must be included.

For VC/C++, if you want gigantic INTs, use LONG LONG.

You can confirm what the case is by `#include <limits.h>` (or the C++ equivalent).  This came up previously.  It is an useful programming exercise.  

See https://github.com/MicrosoftDocs/cpp-docs/issues/4679#issuecomment-1679658999

There are bonus points for why some of the MIN values are expressed the way they are.

**Comment by Mayank-Jain-1** [comment]
Thanks @orcmid for this detailed explanation. 

I understand the reason for the values now. I am just a student learning and practicing on leetcode. I encountered this today while solving one of the question where i needed lower and upper bound for INT values. 

I surely learnt something new today.
