### ISSUE TITLE
Mention `initterm` in CRT init article

### ISSUE THREAD

**Issue by Rageking8** [MicrosoftDocs/cpp-docs#4706]
I was wondering if it was a good idea to mention the function [initterm](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/initterm-initterm-e?view=msvc-170) somewhere here, when the article talks about walking of the function pointers for initialization. If this idea is not sound, feel free to close this issue directly. Thanks.

>When you browse the functions on the stack, you'll see that the CRT is calling a list of function pointers. These functions are similar to func(), or constructors for class instances.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9d57a7-b035-5ba2-c442-fdf43c69b886
* Version Independent ID: d8107b93-e133-fe61-125d-23383c195861
* Content: [CRT Initialization](https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-initialization?view=msvc-170)
* Content Source: [docs/c-runtime-library/crt-initialization.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/crt-initialization.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I've added it as a see-also link. The change will be live tomorrow.
