### ISSUE TITLE
Cant find "setup"

### ISSUE THREAD

**Issue by AndresdoSantos** [MicrosoftDocs/cpp-docs#4708]
Hi everyone, I can't find Setup Project in the list of choices in the dialog box.

It is step 3 of the [deployment guide](https://learn.microsoft.com/en-us/cpp/ide/walkthrough-deploying-your-program-cpp?view=msvc-170).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be979440-bf90-6756-304c-883363a10073
* Version Independent ID: 4aea40e0-a221-acf0-2421-0ad5194fe03e
* Content: [Walkthrough: Deploying Your Program (C++)](https://learn.microsoft.com/en-us/cpp/ide/walkthrough-deploying-your-program-cpp?view=msvc-170)
* Content Source: [docs/ide/walkthrough-deploying-your-program-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/ide/walkthrough-deploying-your-program-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Did you follow the step to add the setup and deployment project template extension? Not having that extension installed is most likely what went wrong.
I updated the steps for more clarity (will be live in a couple days) but following the steps as written worked fine for me.
