### ISSUE TITLE
Fix error in codeblock: expected ‘;’ after struct definition

### ISSUE THREAD

**Issue by NikhilPatel42** [MicrosoftDocs/cpp-docs#4709]
Error:
In the first codeblock, 
```cpp
int var;
const int&& fx();
struct A { double x; }
const A* a = new A();
```

on line 3, the statement
```cpp
struct A { double x; }
```
doesn't have a terminating `;` at the end of struct definition.

Fix:
```cpp
struct A { double x; };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adc3f091-d6fa-cb05-fe7d-03394a1d221d
* Version Independent ID: 9f3a60fb-d7de-0c82-f84f-9516cc1cb9fa
* Content: [decltype (C++)](https://learn.microsoft.com/en-us/cpp/cpp/decltype-cpp?view=msvc-170)
* Content Source: [docs/cpp/decltype-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/decltype-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
True - fixed. Thanks for taking the time to point that out. The fix will be live by tomorrow.
