### ISSUE TITLE
Installation Prerequisites

### ISSUE THREAD

**Issue by dlwlb** [MicrosoftDocs/cpp-docs#4714]
Should the article contain installation prerequisites? https://learn.microsoft.com/en-us/cpp/mfc/reference/creating-an-mfc-application?view=msvc-170 has a side-bar with Version "Visual Studio 2022". Article is dated "02/13/2023". Section "To create an MFC forms or dialog-based application" step 2, search for "MFC" says "No exact matches found", no "MFC App". Below the templates is a note "Not finding what you're looking for? <Install more tools and features>" which opens Visual Studio Installer dialog "Modifying -- Visual Studio Professional 2022 -- 17.4.5", Individual components tab, Search for "MFG" lists numerous versions/platforms.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0128902a-afb9-2399-a378-3d5d6ca046b4
* Version Independent ID: 484ada2f-c1ed-1a3d-9d19-5bbfcb1cc705
* Content: [Creating an MFC Application](https://learn.microsoft.com/en-us/cpp/mfc/reference/creating-an-mfc-application?view=msvc-170)
* Content Source: [docs/mfc/reference/creating-an-mfc-application.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/creating-an-mfc-application.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Unfortunately, due to doc resources and current priorities, closing.
