### ISSUE TITLE
should be new_delete_type_mismatch=0?

### ISSUE THREAD

**Issue by sunxdc15** [MicrosoftDocs/cpp-docs#4721]
[Enter feedback here]
should be new_delete_type_mismatch=0? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d70ca275-507f-5463-5c1c-ee561efd3963
* Version Independent ID: c90172ef-57b2-9f22-4541-97b13dcca120
* Content: [Error: alloc-dealloc-mismatch](https://learn.microsoft.com/en-us/cpp/sanitizers/error-alloc-dealloc-mismatch?view=msvc-170)
* Content Source: [docs/sanitizers/error-alloc-dealloc-mismatch.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/sanitizers/error-alloc-dealloc-mismatch.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, I'm not sure what your feedback means here. I assume you are referring to setting the ASAN_OPTIONS environment variable. We wouldn't set it to 0 since we are trying to turn it on. Are you saying the flag is wrong?
Reopen with clarification if I've missed the point.

**Comment by sunxdc15** [comment]
I apologize for the confusion. I just identified a mistake in the document. the correct key to toggle the feature should be "new_delete_type_mismatch" instead of "alloc_dealloc_mismatch".   I am using VS2019 and 2022.

**Comment by TylerMSFT** [comment]
Thanks for the clarification. I don't think it's a mistake in the doc. I use alloc_dealloc_mismatch to turn on the error and it works as advertised.  The new_delete_type_mismatch is a different error, described in [this topic](https://learn.microsoft.com/en-us/cpp/sanitizers/error-new-delete-type-mismatch?view=msvc-170)
