### ISSUE TITLE
Warning C4834 docs should clarify it is enabled in C++14 mode

### ISSUE THREAD

**Issue by joemmett** [MicrosoftDocs/cpp-docs#4725]
The docs for this warning correctly state it was introduced in C++17, but we (and all other major compiler vendors) actually respect this attribute and will emit warnings related to it in C++14 mode too. The docs could use a clarifying note here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7edfac9-2178-0e6a-d534-51ab9d3503ef
* Version Independent ID: 8993c7ff-6dd3-ddc3-4739-eb9a7594a713
* Content: [Compiler warning (Level 1) C4834](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4834?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/c4834.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/c4834.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Done. It'll go live with a batch of other warning work that I'll have published by Monday.
