### ISSUE TITLE
cpp.hint was created with the empty function definition. Add it to your CMakeLists.txt file to include it in your project

### ISSUE THREAD

**Issue by eugeniomiro** [MicrosoftDocs/cpp-docs#4729]
I'm getting this message

> cpp.hint was created with the empty function definition. Add it to your CMakeLists.txt file to include it in your project

I can't find any reference to cpp.hint files anywhere, not in VS documentation nor in CMake documentation. Could you please help me with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be02c0ec-bd7d-a99e-099c-9db58eec5e20
* Version Independent ID: b9ec50f6-f265-4310-c1e0-f49bf3842f84
* Content: [Hint Files](https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170)
* Content Source: [docs/build/reference/hint-files.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/hint-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by Atliac** [comment]
There is no need to add anything to the CMakeLists.txt file.

The `cpp.hint` can be found automatically in the path from the root directory of a source file to the directory that contains the source file itself.

> **Important**
> If you modify or add a hint file, you need to take additional steps in order for the changes to take effect:
>- In versions before Visual Studio 2017 version 15.6: Delete the .sdf file and/or VC.db file in the solution for all changes.
>- In Visual Studio 2017 version 15.6 and later: Close and reopen the solution after adding new hint files.

**Comment by TylerMSFT** [comment]
Also, for support help, see [C++ Q & A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
