### ISSUE TITLE
Results of compound assignment expressions

### ISSUE THREAD

**Issue by KKamishima** [MicrosoftDocs/cpp-docs#4745]
The 'Result of assignment operators' section is vague about whether it is also applicable to compound assignment operators; in fact, it does but with a caveat.

Compound assignment operators return the object specified by the left operand, which has been already modified by the operation despite the operators are apparently placed after variables. In contrast, postfix operators result in the pre-modification values of the variables. Such difference may cause confusions to those who are careless like me.

```
int i1 = 2;
int postfix_op = i1++; // == 2

int i2 = 2;
int assign_op = i2 += 1; // == 3
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb7e11f-cd0d-5e4d-fcf2-6b1060b7586c
* Version Independent ID: 90046753-8233-1a30-09d8-126f8350b3fc
* Content: [Assignment operators](https://learn.microsoft.com/en-us/cpp/cpp/assignment-operators?view=msvc-170)
* Content Source: [docs/cpp/assignment-operators.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/assignment-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
We are in the process of moving away from GitHub issues for C++ documentation (we still accept pull requests). For details, please see [Announcing a new way to give feedback on Microsoft Learn](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) This issue will be closed after it is copied to an internal system.
