### ISSUE TITLE
VS2022 can specify /std:c17 /std:c++20 together but NMAKE cannot

### ISSUE THREAD

**Issue by RayOfDaylon** [MicrosoftDocs/cpp-docs#4746]
Using Visual Studio 2022 Community Edition, version 17.7.3

I can build VS2022 projects that have the /std:c17 /std:c++20 switches set in the project's properties, and confirm they are both in the resulting command line used when building by examining the "C/C++, Command Line" section of the project's property page.

However, NMAKE reports:
cl : Command line error D8016 : '/std:c17' and '/std:c++20' command-line options are incompatible

I'm guessing NMAKE thinks that the /std switch is mutually exclusive?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6183aaac-1eb4-f704-4bf5-1c3fe67ae2fe
* Version Independent ID: d3f24754-fcba-3eee-e34d-445962c5485c
* Content: [/std (Specify Language Standard Version)](https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170)
* Content Source: [docs/build/reference/std-specify-language-standard-version.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/std-specify-language-standard-version.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Correct. The MSVC compiler will pick the latest version specified, but nmake doesn't.
For instance, cl /std:c++17 /std:c++20 test.cpp will compile with c++20 and generate a warning that c++20 is overriding c++17.
