### ISSUE TITLE
No indicate as to how to launch/get it?

### ISSUE THREAD

**Issue by rboy1** [MicrosoftDocs/cpp-docs#475]
Is this a plugin? Is this is a standard module? This is a separate program? Is this an extension? Where does one get it. Documentation without context of how to launch or get the associated program might as well be non existent, it's good reading but you can't do anything with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195f6bf5-8435-ecda-e7c6-c705934e9fa6
* Version Independent ID: 8a714db6-0297-a0ec-3f3c-bb2156741192
* Content: [Image Editor for Icons](https://docs.microsoft.com/en-us/cpp/windows/image-editor-for-icons?view=vs-2017)
* Content Source: [docs/windows/image-editor-for-icons.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/image-editor-for-icons.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@rboy1 Thanks for the feedback. Yes that's missing an important piece of information. Probably written 20 years ago before we learned how to do this stuff :-\  Anyway, the Image Editor opens automatically when you open an .ico file from solution explorer. You will see the icon, and a different toolbar and an "Image" menu in the main menu. Right now there's an annoying display bug in my beta version of 15.9. When that gets fixed I'll update this topic with a screenshot.

**Comment by mikeblome** [comment]
Topic is updated.
