### ISSUE TITLE
My program still terminate when asan throw exception, evn if I set ASAN_OPTIONS=continue_on_error=1 before execute my program.

### ISSUE THREAD

**Issue by konlil** [MicrosoftDocs/cpp-docs#4763]
[Enter feedback here]
My program still terminate when asan throw exception, evn if I set ASAN_OPTIONS=continue_on_error=1 before execute my program.
Btw, my program is a game client build from Unreal Engine 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd73e73c-253e-81b3-7570-b9d4fbed2e95
* Version Independent ID: dd73e73c-253e-81b3-7570-b9d4fbed2e95
* Content: [Walkthrough: Use Address Sanitizer Continue On Error to find memory safety issues](https://learn.microsoft.com/en-us/cpp/sanitizers/asan-continue-on-error?view=msvc-170)
* Content Source: [docs/sanitizers/asan-continue-on-error.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/sanitizers/asan-continue-on-error.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, sorry to hear that. This is something you should take up on [C++ Q & A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
