### ISSUE TITLE
Wrong warning level in title

### ISSUE THREAD

**Issue by misuo** [MicrosoftDocs/cpp-docs#4764]
Shouldn't this title be listing this as belonging to category warning level 4 (not 3) since the example clearly states that it requires /W4 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39d1ef07-bd1a-06c5-d02d-98f638ebea09
* Version Independent ID: eae492b7-b8bc-e49e-772e-cebbcc9c4e48
* Content: [Compiler Warning (level 3) C4310](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4310?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-3-c4310.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-3-c4310.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for pointing that out. Fixed.
The fix will be live tomorrow.
