### ISSUE TITLE
VersionHelper.h requires windows.h

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/cpp-docs#4767]
This arises in several places starting with (https://learn.microsoft.com/en-us/windows/win32/SysInfo/version-helper-apis).  At the moment it is missing from examples and requirements entries.  

The requirement does become obvious if the helper header is included without `windows.h`.

**Comment by alvinashcraft** [comment]
Hi @orcmid. Thanks for calling this out. The page has been updated to include windows.h in the example code. I also added a note about including windows.h when including VersionHelper.h. The changes are live now.

I think this issue can be closed, @TylerMSFT. I don't have permissions to close it myself. Thanks for the heads-up!

**Comment by TylerMSFT** [comment]
Closing per Alvin's fix.
