### ISSUE TITLE
Error syntax in if-else statement

### ISSUE THREAD

**Issue by ChenZhongPu** [MicrosoftDocs/cpp-docs#4768]
```cpp
class C {
public:
    void do_something() {
    }
};

void init(C) {}

int main() {
    C *c;
    init(c);
}
```

The code above is problematic, since the calling and defining of `init` are not matched.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b385eb6a-6880-d24d-99de-4618f11db864
* Version Independent ID: f74e6e06-29b0-8ead-c9a6-e0ffc7070f24
* Content: [if-else statement (C++)](https://learn.microsoft.com/en-us/cpp/cpp/if-else-statement-cpp?view=msvc-170)
* Content Source: [docs/cpp/if-else-statement-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/if-else-statement-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I improved the example. Also improved the other two while I was there.
Fixes should be live by tomorrow afternoon.
