### ISSUE TITLE
`int j = 1;` is irrelevant. I suggest removing. 

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/cpp-docs#4789]
`int j = 1;` is irrelevant. I suggest removing. Or correct it to refer to useful example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8375f9a-0d32-df9b-f5c2-8b2d73f0bf52
* Version Independent ID: bf6d61f4-4b1c-ab2f-ec08-226900a2a973
* Content: [Compiler Error C2450](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2450?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2450.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/compiler-error-c2450.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@diablodale, yes, that's weird. Removed. Will be live tomorrow.
