### ISSUE TITLE
No clue what include file I need, which is all I asked.

### ISSUE THREAD

**Issue by julie-mindcapers** [MicrosoftDocs/cpp-docs#4795]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa78f56-aed9-e282-4a30-6e0656f48074
* Version Independent ID: f428718a-ad6b-908b-5967-a6361ee977d8
* Content: [CImage Class](https://learn.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cimage-class?view=msvc-170)
* Content Source: [docs/atl-mfc-shared/reference/cimage-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/atl-mfc-shared/reference/cimage-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
The topic says which include file to use:  atlimage.h
These topics have a Requirements section towards the end that say what header file is needed.
Closing.
