### ISSUE TITLE
The values of FE_UPWARD and FE_DOWNWARD have changed

### ISSUE THREAD

**Issue by bhaible** [MicrosoftDocs/cpp-docs#4796]
The documentation should say something about this, since this is an ABI break:

The values of the constants `FE_UPWARD` and `FE_DOWNWARD`, defined by `<fenv.h>`, have changed between MSVC 14.00 and MSVC 14.30.

How to reproduce:
```
#include <fenv.h>
#include <stdio.h>

int
main ()
{
  printf ("_MSC_VER = %d  _MSC_FULL_VER = %d  FE_UPWARD = 0x%x  FE_DOWNWARD = 0x%x\n",
          _MSC_VER, _MSC_FULL_VER, FE_UPWARD, FE_DOWNWARD);
  return 0;
}
```

Output with MSVC 14.00 (= Visual C++ 2015):
```
_MSC_VER = 1900  _MSC_FULL_VER = 190024210  FE_UPWARD = 0x100  FE_DOWNWARD = 0x200
```

Output with MSVC 14.30 (= Visual C++ 2022):
```
_MSC_VER = 1935  _MSC_FULL_VER = 193532217  FE_UPWARD = 0x200  FE_DOWNWARD = 0x100
```

This means that when binary code compiled with MSVC 14.00 and binary code compiled with MSVC 14.30 are combined, and a rounding mode is passed between these two parts of the code, unspecified behaviour is the result. Where the programmer has expected to pass FE_UPWARD, the other part of the code receives FE_DOWNWARD, and vice versa.

Depending on the compilation environments used by the programmers in the various stages of the build, this means that `fegetround` and `fesetround` are broken beyond repair.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3b5bba8-6129-56e0-bd04-22c1e558306e
* Version Independent ID: 2948d9e2-4712-8796-aa85-cb263a938380
* Content: [fegetround, fesetround](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fegetround-fesetround2?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/fegetround-fesetround2.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/fegetround-fesetround2.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
Yikes!!

**Comment by TylerMSFT** [comment]
Researching with the dev team.

**Comment by TylerMSFT** [comment]
Ok, what happened is that this was an intentional breaking change. I'll update this doc accordingly. 

Prior to Windows 10 version 14393, the fenv.h header used the set values of FE_UPWARD as 0x0100 and FE_DOWNWARD as 0x0200. In Windows version 14393, this header was updated to use the same values as _RC_UP (0x0200) and _RC_DOWN (0x0100). The reason was that our internals use the latter macros for implementation, so some APIs would interpret FE_UPWARD as FE_DOWNWARD and vice versa. 

You have to get a pretty old Windows SDK version (it depends on SDK version, not OS version or VS version) to trigger the issue. In general, recommend updating to use the latest Windows SDK available and this should work with Visual C++ 2015.

**Comment by TylerMSFT** [comment]
I updated the doc to call out the change. It'll be live tomorrow.

**Comment by bhaible** [comment]
> this was an intentional breaking change

This is incredible.

Every developer of a shared library knows what it means to preserve backward compatibility: Don't remove exported symbols, don't change the signature of an exported symbol, don't change the size of a type that the user may allocate on the stack, don't change the values of enums and constant macros, etc. There's even a tool for checking against ABI breaks: https://lvc.github.io/abi-compliance-checker/ . Microsoft does such an ABI break not in a random shared library, but in the central library that every C and C++ program uses.

It would have been forgivable if the ABI break was unintentional. Because everyone occasionally makes mistakes, and not everyone uses the best QA techniques (like the ABI checker mentioned above). But to break an ABI intentionally...!
