### ISSUE TITLE
lack of info cmake

### ISSUE THREAD

**Issue by Piekarnik** [MicrosoftDocs/cpp-docs#4797]
It could be easier to inform that packet "cmake tools for c++" need to be installed in visual studio installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b25c8d-63c4-e903-69cc-a90b88f7b13d
* Version Independent ID: 113c6b83-1457-d4ac-93d0-4177abb3b993
* Content: [Walkthrough: Compiling a Native C++ Program on the Command Line](https://learn.microsoft.com/en-us/cpp/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line?view=msvc-170)
* Content Source: [docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
@Piekarnik 
> It could be easier to inform that packet "cmake tools for c++" need to be installed in visual studio installer.

I think the point of the questioned page and example is about command-line use of the compiler and how the single command line will compile and link without any need for knowledge of additional tools.

I do think the instructions are a bit gnarly around preparing the code.  That's a different problem and `cmake` will not improve it.  My impressions is that the page on "Hello World" is much better as a starter.

If we're talking about building outside of Visual Studio (but using the build tools from a command prompt), I think introduction of `make` and `cmake` is best deferred until a beginner encounters the situations that these different tools facilitate.   I have no idea how that is (or could be) handled at Microsoft Learn.
