### ISSUE TITLE
Comment in example code is incorrect

### ISSUE THREAD

**Issue by bradthor** [MicrosoftDocs/cpp-docs#480]
The example indicates (in the comments) that popping stack1 off the stack would result in the next variable being located in segment "stack_data1":

#pragma data_seg(pop, stack1)   // pop stack1 off the stack  
int m = 3;                     // stored in "stack_data1"  

I assume the last comment should be:  // stored in "my_data1"

Hopefully, I'm not misunderstanding how this works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ca1648-0aab-34de-d07f-d62a9249fbda
* Version Independent ID: e341d591-4590-fc7c-f17f-8d654d3765d5
* Content: [data_seg](https://docs.microsoft.com/en-us/cpp/preprocessor/data-seg?view=vs-2017)
* Content Source: [docs/preprocessor/data-seg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/data-seg.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bradthor Your understanding is correct, and the comment is wrong. Looks like a missed edit.

**Comment by corob-msft** [comment]
Closing as fixed.
