### ISSUE TITLE
Link is to blog article from 2013 that doesn't exist, the whole blog site does not exist.

### ISSUE THREAD

**Issue by julie-mindcapers** [MicrosoftDocs/cpp-docs#4819]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 268838a0-787f-78b1-2f55-588f31736cc6
* Version Independent ID: 76428f78-9cff-36f0-bf3d-79a7adee8e33
* Content: [Setting the Dialog Box's Background Color](https://learn.microsoft.com/en-us/cpp/mfc/setting-the-dialog-boxs-background-color?view=msvc-170)
* Content Source: [docs/mfc/setting-the-dialog-boxs-background-color.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/setting-the-dialog-boxs-background-color.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thanks for taking the time to point that out. Fixed. I added a small example that will be live Monday.
