### ISSUE TITLE
Less secure tmpfile()

### ISSUE THREAD

**Issue by Veltas** [MicrosoftDocs/cpp-docs#4820]
The documentation for `tmpfile()` states that it is *deprecated* and that a *more secure* version is `tmpfile_s()`.

Is `tmpfile_s()` actually *more secure*, and if so, how? I think this needs explaining or changing in the documentation, because there's no obvious improvement to security, and it seems that it should be possible to implement `tmpfile()` in a safe manner.

I'm thinking of developers who will likely see this and be forced to change it out of an abundance of caution and as an act of diligence even though I suspect the only reason it's deprecated is because there's an `_s` variant, which was added just for consistent error reporting with the other `_s` functions, rather than to patch a security hole.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 414314a8-bd8d-99fc-1f6c-5df80b3cc1e3
* Version Independent ID: ee91da15-7833-1638-7745-a0d8ee2329b0
* Content: [tmpfile](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/tmpfile?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/tmpfile.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/tmpfile.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
`tmpfile_s` is part of the safe-code practice extensions that are in at least ISO C11.  I agree it is not obvious what the edge case is, if any.  However, consistency is not entirely a bad thing, although `tmpfile_s` and the rest do feel a bit clumsier.  I agree these are not all about threat surface, many are about code safety.

This form does encourage always checking the return value, without having to go an extra step to check for a NULL pointer return.  Now the extra step is separate declaration of the FILE* to be set :).
