### ISSUE TITLE
Wrong prototype for CStringArray::GetAt()

### ISSUE THREAD

**Issue by UsuallyLogical** [MicrosoftDocs/cpp-docs#4824]
[Enter feedback here]
This page falsely says that the prototype is:
    CStringArray | CString GetAt(INT_PTR nIndex) const;
in reality, the afxcoll.cpp says that it is:
   const CString& CStringArray::GetAt(INT_PTR nIndex) const;

So it returns a const reference rather than a CString (copy).    

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5cdd99-113f-4f02-3bf6-5d1d55a69089
* Version Independent ID: 299ec27c-0c12-76cd-d1bc-073565a78337
* Content: [CObArray Class](https://learn.microsoft.com/en-us/cpp/mfc/reference/cobarray-class?view=msvc-170#getat)
* Content Source: [docs/mfc/reference/cobarray-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/cobarray-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**[CStringArray](https://learn.microsoft.com/en-us/cpp/mfc/reference/cstringarray-class?view=msvc-170)	CString GetAt(INT_PTR nIndex) const;

**Comment by TylerMSFT** [comment]
Thanks for pointing this out. The fix will be live Monday afternoon.
