### ISSUE TITLE
Application not launching when converting from 32bit to 64bit in VS 2019

### ISSUE THREAD

**Issue by ThejaswiniN** [MicrosoftDocs/cpp-docs#4825]
Recently I have converted the application from 32bit to 64bit in VS 2019,all sources are saying the application is of 64bit but I'm unable to launch the application,
![64bit Cmd](https://github.com/MicrosoftDocs/cpp-docs/assets/74773490/cfd56718-c3d2-45cf-814f-8b20c49fc429)
and I am not able to debug the application because the application need to be attach to process for debugging , when searched in the event viewer, I am encountering BEX64 error as attached
<img width="691" alt="BEX64 error" src="https://github.com/MicrosoftDocs/cpp-docs/assets/74773490/0e5c95c8-d189-484c-98e2-c06815db2d87">
and have made sure that all the dependent DLL's are of 64bit ,
<img width="937" alt="64bit dll issues" src="https://github.com/MicrosoftDocs/cpp-docs/assets/74773490/500127e4-78a4-4599-8154-1cc0ae9034a5">
 Can anyone please help me to resolve this issue.

I am able to open the application from visual Studio 2019, but not able to launch from .exe file 
<img width="923" alt="application launching" src="https://github.com/MicrosoftDocs/cpp-docs/assets/74773490/5b0bb07c-2fb2-4327-b007-d7f9f2dec1c0">

**Comment by TylerMSFT** [comment]
Hi, this area is for identifying bugs/questions about the documentation. We don't troubleshoot development problems here. For that, you might try [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) for Visual Studio.
