### ISSUE TITLE
Copy File Property Pages

### ISSUE THREAD

**Issue by NPatch** [MicrosoftDocs/cpp-docs#483]
In VS 2017 15.8.7 there's an extra page called Copy File. Is that an easier way to define copy operations for deployment after building? Or is it unrelated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ddf139-230c-93df-1a39-0384c28dbf95
* Version Independent ID: 7d944ce3-0423-309c-97fe-99eb5949234b
* Content: [Working with Project Properties](https://docs.microsoft.com/en-us/cpp/ide/working-with-project-properties?view=vs-2017)
* Content Source: [docs/ide/working-with-project-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/working-with-project-properties.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@NPatch what kind of project do you have open?

**Comment by NPatch** [comment]
It's a c++ static library.

**Comment by mikeblome** [comment]
Hmmm I don't see that option anywhere, but I'm on 15.9. I have asked the dev team.  You can set the Output Directory for the binary, but that's not going to copy the header file. Is there a reason you don't want to create a post-build event?

**Comment by NPatch** [comment]
I was trying to avoid robocopy as it gave me some grief in prior cases. I ended up doing it anyway. Still Copy File does need some documentation since it's a new feature so the original post still stands.
Kind of weird though how you couldn't see it in 15.9 as I had a previous version. Also I saw it in the Property Manager while configuring props files.
