### ISSUE TITLE
A wonderful way to get Started in Visual Studio/C++

### ISSUE THREAD

**Issue by Not-the-mama** [MicrosoftDocs/cpp-docs#4831]
Thank you for this tutorial - I am a mentor for final year System Engineering Students tasked with building a device based on Arduino Nano and a pressure transducer.  I specifically asked for the code for the GUI to be written using Visual Studio, and C++. Therefore I thought I should learn Visual Studio and C++ myself so as to be a better mentor.

I've programmed in other languages using other IDEs (editors really) many years ago, so I found the learning curve steep. I trolled YouTube for tutorials... wonderful for learning other things in the past but not for this! So I thought that I would go to get instruction right from the "horses mouth".

Your tutorial founded on the console calculator got me going really quickly - and it was fun!!!

I am hoping that one day I will be able to confidently code Windows/multiplatform GUIs that control read data from and processing data from the Arduino Nano in various ways.

Thanks again  * * * * *

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a console calculator in C++](https://learn.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=msvc-170)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you, @Not-the-mama 
Super glad it helped. You made my day.
