### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by FraserRoss** [MicrosoftDocs/cpp-docs#4833]
The text says the function returns EINVAL but it returns nothing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e932ee57-662b-dd17-a113-a70f8cb8f86f
* Version Independent ID: 79dd5ab5-fdf5-f6c1-c266-7668bd523da3
* Content: [_splitpath, _wsplitpath](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/splitpath-wsplitpath?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/splitpath-wsplitpath.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/splitpath-wsplitpath.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
Yup.  I think that is a generic remark that doesn't apply here.  I presume it sets `errno` but the function simply returns if continuation is allowed.

**Comment by TylerMSFT** [comment]
Fixed. Will be live tomorrow. Thanks for flagging that.
