### ISSUE TITLE
TZNAME_MAX does not appear in limits.h anymore.

### ISSUE THREAD

**Issue by mscottmueller** [MicrosoftDocs/cpp-docs#484]
To determine the length of the array to pass in for _get_tzname, including the NULL terminator, pass in a nullptr as the address of the array and zero as the length. This will cause _get_tzname to return the size in the first parameter. Allocate an array of this length and then invoke _get_tzname again with the allocated array and known size.

   size_t tznamesize = 0;
   std::string standardname;
   ret = _get_tzname(&tznamesize, nullptr, 0, 0); // Standard time
   if (!ret)
   {
      auto tzname = std::unique_ptr&lt;char[]&gt;(new char[tznamesize]);
      ret = _get_tzname(&tznamesize, tzname.get(), tznamesize, 0; // standard time
      if (!ret)
      {
         _standardname = {tzname.get(), tznamesize};
      }
   }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9757fce-1f9a-da3a-5d18-e1c12d6f0c68
* Version Independent ID: faf79f9a-de0c-2c44-cd6e-553eb0960cbc
* Content: [TZNAME_MAX](https://docs.microsoft.com/en-us/cpp/c-runtime-library/tzname-max?view=vs-2017)
* Content Source: [docs/c-runtime-library/tzname-max.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/tzname-max.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mscottmueller Apparently this constant was removed between Visual Studio 2012 and Visual Studio 2013. I'll see about updating references to it appropriately.

**Comment by corob-msft** [comment]
Closed as fixed.
