### ISSUE TITLE
you need some examples

### ISSUE THREAD

**Issue by AlpinChisholm** [MicrosoftDocs/cpp-docs#4844]
you need some examples of macros on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74ffaeff-91ef-c49b-a450-e633b9c794b6
* Version Independent ID: c04186e4-ef68-b025-06a2-4116d76ecbb2
* Content: [MACRO](https://learn.microsoft.com/en-us/cpp/assembler/masm/macro?view=msvc-170)
* Content Source: [docs/assembler/masm/macro.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/assembler/masm/macro.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I agree. The sad reality is that I'll never get to this given other priorities and where we are focusing our attention.
