### ISSUE TITLE
List of FAST_FAIL_<description> codes missing from the __fastfail() documentation page

### ISSUE THREAD

**Issue by axelriet** [MicrosoftDocs/cpp-docs#4847]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42909159-a3dd-e93b-e2d4-b46f027c1b6c
* Version Independent ID: 1daba1b8-bd36-308e-be70-57eb6df38b86
* Content: [__fastfail](https://learn.microsoft.com/en-us/cpp/intrinsics/fastfail?view=msvc-170)
* Content Source: [docs/intrinsics/fastfail.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/fastfail.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
@axelriet The codes are not missing.  The article specifies two header files where they are to be found.  I looked in a copy of `winnt.h` on my computer and see there are 68 of them, plus two that are not meant to be used, including `FAST_FAIL_INVALID_FAST_FAIL_CODE`.   The `FAIL_CODE`s (and the `__fastfail` intrinsic) seem extremely-specialized.  I suspect listing them here would invite more question than it answers.

**Comment by TylerMSFT** [comment]
Hi @axelriet. They are not listed because they are available via winnt.h or wdm.h, which the doc mentions in a couple places. I can see why you'd like a list here, but given other priorities and current resources, I would not get to it. So rather than create false hope, closing.
