### ISSUE TITLE
No exporting variable section

### ISSUE THREAD

**Issue by sjhowe888** [MicrosoftDocs/cpp-docs#4854]
The is no exporting variable example

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a00ef41-1841-538c-6c85-d34107239627
* Version Independent ID: 8df53966-0e8e-824f-512c-4a568753bbcb
* Content: [Exporting from a DLL Using DEF Files](https://learn.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=msvc-170)
* Content Source: [docs/build/exporting-from-a-dll-using-def-files.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/exporting-from-a-dll-using-def-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by sjhowe888** [comment]
There is no exporting variable sample from the DLL, just classes and free functions

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please reopen it and provide a comment explaining why.
