### ISSUE TITLE
Move Constructors and Move Assignment Operators (C++)

### ISSUE THREAD

**Issue by the-alchemist88** [MicrosoftDocs/cpp-docs#4856]
[Enter feedback here]

This example is surely beneficial and serves its main purpose well. However, I cannot figure out how to assign values to dynamic int array(**int\* _data**) that the **MemoryBlock** class wraps. Programmer can only default construct a object with a **length** parameter without any initial value, so it will be filled with indeterminate values in the heap I suppose. Other operators can only take the object of the same type so, it seems no way to assign values from containers(including C arrays). In my opinion, if this class had implemented as an example of class **std::string**, it would be more practical since the programmer could play around and practice with values inside. For example by providing a constructor like this:
`
class String
{
public:
	String(const char* s) : length{strlen(s)}, p{new char[length + 1]} // intentionally not explicit
	{
		strcpy(m_str, p);
	}

//code for other ctors, dtor, operators etc.

private:
	int m_len;
	char* m_str;
};

`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9ddde55-d01d-81d5-b3bf-49b77e2bff1c
* Version Independent ID: 109327f1-3d30-07e9-1e04-d5a52a5cc7ec
* Content: [How to: Define move constructors and move assignment operators (C++)](https://learn.microsoft.com/en-us/cpp/cpp/move-constructors-and-move-assignment-operators-cpp?view=msvc-170)
* Content Source: [docs/cpp/move-constructors-and-move-assignment-operators-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/move-constructors-and-move-assignment-operators-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, I think this is better suited for the [C++ Q & A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
