### ISSUE TITLE
Comment in example code is incorrect

### ISSUE THREAD

**Issue by bradthor** [MicrosoftDocs/cpp-docs#486]
Similar to issue #480:
The last comment should be: // stored in "my_data1"

FYI: the examples in the doc page for bss_seg and data_seq vs. code_seg vs. const_seg are not consistent.
bss_seg and data_seg uses "my_data1" <- segment name surrounded by quotes
code_seg uses my_data1 <- segment name without quotes
const_seg uses .my_data1 <- segment name with leading .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a0edbb-b6e9-8fd1-197c-c39353ab706b
* Version Independent ID: 9767e759-c6bc-ed4e-cd27-60d46df1c840
* Content: [bss_seg](https://docs.microsoft.com/en-us/cpp/preprocessor/bss-seg?view=vs-2017)
* Content Source: [docs/preprocessor/bss-seg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/bss-seg.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closing as fixed.
