### ISSUE TITLE
There is a statement: "Nesting of include files can continue up to 10 levels." But C99 has a minimum limit 15 nesting levels for #include files.

### ISSUE THREAD

**Issue by water-chika** [MicrosoftDocs/cpp-docs#4866]
There is a statement: "Nesting of include files can continue up to 10 levels." But C99 has a minimum limit of 15 for nesting levels for #include files.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b02cc93-0d7c-d1bf-64ab-e6111525c809
* Version Independent ID: 5a9af828-31a5-9042-d997-e662928753bf
* Content: [#include directive (C/C++)](https://learn.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=msvc-170)
* Content Source: [docs/preprocessor/hash-include-directive-c-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/hash-include-directive-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
I don't believe Microsoft has claimed full compliance with C99 (or C11 where the same minimum requirement is stated).

I would accept the Microsoft-stated limit as factual though.   Unless an implementer advises that the limit has been changed to a number at least 15 :).
