### ISSUE TITLE
visual studio being visual studio ... not making sense and not intelligent.

### ISSUE THREAD

**Issue by AvatharBehemoth** [MicrosoftDocs/cpp-docs#4868]
my loop 
for (int i = 40; i >= 1; i--)
warning C6293 ??!!?? 
so now i cant make a declining for loop??!!? 
i also tried i <= 1
i = 1 
visual studio isnt the best product ... is it....
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2cc6c58-8acb-104a-0ebb-1628c890184a
* Version Independent ID: f9485c5f-030d-0971-8e4b-61ed6e5fb6f4
* Content: [Warning C6293](https://learn.microsoft.com/en-us/cpp/code-quality/c6293?view=msvc-170)
* Content Source: [docs/code-quality/c6293.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c6293.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by AvatharBehemoth** [comment]
i modified the loop to
for (int i = 0; i <= 40; i++)
warning DID NOT DISAPEAR. saving closing and restarting removed the warning??!!?? what kind of product is this? isnt intellisense supposed to help? in stead of wasting time

**Comment by TylerMSFT** [comment]
Hi, I don't see this behavior, i.e. I don't get the warning with your code.
Since you seem to be having a product issue, to get that in front of the right person do from the IDE do Help > Send Feedback > Report a problem.
