### ISSUE TITLE
Example in inline functions page

### ISSUE THREAD

**Issue by Mr-Auto** [MicrosoftDocs/cpp-docs#4871]
Small thing with the last example:
```cpp
#define sqr(a) ((a) * (a))

int main()
{
    int c = 5;
    std::cout << sqr(c++) << std::endl; // outputs 25
    std::cout << c << std::endl; // outputs 7!
}
```
The first output will be 30 not 25, actually the 25 would make sense if it was a function instead of macro

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09138391-a316-0222-7db1-3cd461316773
* Version Independent ID: 2cd32c3f-d4c0-69b5-d09c-f8a2638f79e0
* Content: [Inline Functions (C++)](https://learn.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=msvc-170)
* Content Source: [docs/cpp/inline-functions-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/inline-functions-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
If you run the code, you'll see that it outputs 25.
