### ISSUE TITLE
Two functions same docs

### ISSUE THREAD

**Issue by Xyndra** [MicrosoftDocs/cpp-docs#4875]
There are two functions, _initterm and _initterm_e, however there is only a difference in some weird pointer names

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9b9551b-39c9-c4e9-bb64-7a702fac3baf
* Version Independent ID: d3ff44f5-4b0e-ea77-0253-209f8162e8ec
* Content: [_initterm, _initterm_e](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/initterm-initterm-e?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/initterm-initterm-e.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/initterm-initterm-e.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
`_initterm` returns a `void` (i.e., nothing), `_initterm_e` returns an `int` result code as specified in the description.

**Comment by TylerMSFT** [comment]
Thanks, @orcmid. I hope you had a relaxing holiday.
Closing this.
