### ISSUE TITLE
C4019: Warning is no longer reproduced with given example for new versions of Visual Studio

### ISSUE THREAD

**Issue by semushin-s** [MicrosoftDocs/cpp-docs#4876]
It's either issue with example in documentation, bug in a compiler or warning is deprecated.

Here's my reproduction:
https://gcc.godbolt.org/z/aPzb5zW51

If the example is correct, I can report it to Visual Studio bug tracker.
If warning is not supposed to work anymore, should be marked as deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57ffc081-160d-8a89-18ed-721f4c9314f8
* Version Independent ID: dfea9bd6-4358-5cb9-1b82-7dacce30b1e9
* Content: [Compiler Warning (level 4) C4019](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4019?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4019.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4019.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I repro'd this. Looking into it.

**Comment by TylerMSFT** [comment]
Hi, this warning only applies to C programs (not C++ programs).
I tried VS 2022 17.8.3 (Compiler Version 19.38.33133 for x86) and it worked fine. 
I've updated the article to indicate that it only applies to C programs. It'll be live sometime Monday afternoon.

**Comment by semushin-s** [comment]
Thanks, I guess  /TC could be added to command line in example to make it more clear as well.

**Comment by orcmid** [comment]
@sumushin-s > Thanks, I guess /TC could be added to command line in example to make it more clear as well.

It already emphasizes that the example is in C and the file name ends in `.c`.  `/TC` is overkill.  I am thinking the emphasis in the text will be fine.
