### ISSUE TITLE
Example code and example output do not match.

### ISSUE THREAD

**Issue by peter01242** [MicrosoftDocs/cpp-docs#4879]
Minor issue but the example refers to:
        printf("The **date** in en-US locale is: '%s'\n\n", str);
      
but the output shows:
        The **time** in en-US locale is: 'Wednesday, May 12, 2004'

This is in both cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for pointing that out. Fixed.
I also fixed the code example to compile with VS 2022.
This will be live by tomorrow afternoon (1/5/2024)
