### ISSUE TITLE
How To Disable lnt-make-member-function-const Message?

### ISSUE THREAD

**Issue by SpriteTheCat** [MicrosoftDocs/cpp-docs#4880]
[Enter feedback here]
 Visual Studio 17.8.3 is reporting that various afx_msg functions can be made const.  For instance:

Header:
afx_msg void OnKillFocusFind();

Source:
void CSQLMainFrame::OnKillFocusFind()
{
	SendMessage(WM_SETMESSAGESTRING, (WPARAM) AFX_IDS_IDLEMESSAGE);
}

has this message

lnt-make-member-function-const	The member function can be made const.

However making it const results in this message:

Error	C2440	'static_cast': cannot convert from 'void (__cdecl CSQLMainFrame::* )(void) const' to 'AFX_PMSG'

for this line in the message map

ON_EN_KILLFOCUS(IDC_FIND_1, &CMainFrame::OnKillFocusFind)

So it would be nice to be able to disable that message in places where it cannot be applied due to the way MFC code is constructed.

Thanks,

Clifford Bass

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec0df040-3ae9-12e9-a102-0185d9b9163e
* Version Independent ID: ec0df040-3ae9-12e9-a102-0185d9b9163e
* Content: [lnt-make-member-function-const](https://learn.microsoft.com/en-us/cpp/ide/lnt-make-member-function-const?view=msvc-170)
* Content Source: [docs/ide/lnt-make-member-function-const.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/ide/lnt-make-member-function-const.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, this sounds like a feature request, which should be made here: [Developer community - C++](https://developercommunity.visualstudio.com/cpp?q=%5Bvs-cpp-roadmap%5D&ftype=idea&stateGroup=active)

**Comment by SpriteTheCat** [comment]
Hi Tyler,

It was not clear if disabling the message was already possible or not.  If it were then it should have been documented on that page.  Apparently it is not possible based on your reply.  Also, the issue is in some ways a bug because it is promoting doing something that does not work and therefore should not be suggesting the change.  Regardless I will submit the request where you indicated.  Or it there some other place that would be more appropriate?

Thanks,

Clifford Bass

**Comment by TylerMSFT** [comment]
The link I provided is a good place.
