### ISSUE TITLE
How about XP

### ISSUE THREAD

**Issue by lwahonen** [MicrosoftDocs/cpp-docs#489]
I've installed the Windows XP support for the compilers. How do I convince vcvarsall to target XP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Build C/C++ Code on the Command Line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2017)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@lwahonen I'll only suggest that targeting the now *way* past end-of-service-life Windows XP is an iffy idea once. Any such machines connected to the internet are likely malware victims. Visual Studio 2019 previews do not include an XP targeting option, as deprecation is complete. There, I'm done.

That said, the command line environment batch files do not support using the XP toolset. The earliest Windows SDK they can target is Windows 8.1.

In the IDE, XP targeting via the built-in VC Project system sets the default SDK to Windows 7.1a, and adds its executable, include, library, etc. directories to the respective PATH, INCLUDE, LIBRARY and so on environment variables, and adds at least one define to the compiler command line (/D_USING_V110_SDK71_). There may be other things it does that I didn't notice. You can roll your own batch file that does the same thing. The project properties file I looked at for this information was "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141_xp\Toolset.props" on my system; yours may vary slightly based on your installation choices.

Good luck.

**Comment by hlsantos** [comment]
Serious? VS 2019 will not have support for targeting XP/2003?   wow!
