### ISSUE TITLE
Documentation says "trailing slash" instead of "trailing backslash"

### ISSUE THREAD

**Issue by marckruzik** [MicrosoftDocs/cpp-docs#4890]
Here are two extracts of the page, where it says "trailing slash":

> $(OutDir) | Path to the output file directory. If it's a relative path, output files go to this path appended to the project directory. This path should have a trailing slash.

> $(IntDir) | Path to the directory specified for intermediate files. If it's a relative path, intermediate files go to this path appended to the project directory. This path should have a trailing slash.

Instead of "trailing slash", it should be "trailing backslash".

Reminder, as I see some confusion online: slash is `/` (for url), backslash is `\` (for Windows paths).

</body>
</html>

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b46cf831-faea-6357-0e06-3284f114c879
* Version Independent ID: 0345affe-ce33-c438-d3e4-d134f905d084
* Content: [Common macros for MSBuild commands and properties](https://learn.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170)
* Content Source: [docs/build/reference/common-macros-for-build-commands-and-properties.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/common-macros-for-build-commands-and-properties.md)
* Service: **visual-cpp**
* Sub-service: **tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@marckruzik , good point. I'll fix that today. It'll be live by Monday afternoon.
