### ISSUE TITLE
'include' mechansim advantage

### ISSUE THREAD

**Issue by Yukimura-2K** [MicrosoftDocs/cpp-docs#4893]
In contract to 'module' unit, are there some experts conclude that the disadvantage of include mechanism

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Version Independent ID: 427d2c09-b55f-4258-0d84-f77a2e0140cb
* Content: [Tutorial: Import the standard library (STL) using modules from the command line (C++)](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
* Content Source: [docs/cpp/tutorial-import-stl-named-module.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/tutorial-import-stl-named-module.md)
* Service: **visual-cpp**
* Sub-service: **cpp-lang**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
@Yukimura-2K Please say your question another way.  It is not clear what some experts might conclude.

**Comment by TylerMSFT** [comment]
Unfortunately , we don't have the bandwidth to handle general Q&A here. This is for feedback about problems with the docs.
You might try reframing the question and asking on the [C++ Q&A site](https://github.com/MicrosoftDocs/cpp-docs/assets/12305055/48d59f6d-d58e-4232-944c-a7a0f5fcb3ac)
