### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by davidly** [MicrosoftDocs/cpp-docs#4898]
[Enter feedback here]

When I build apps, the switch statement jump tables are still in _TEXT. How can I force it to work?

I'm using
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33321 for x64

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93be4de-f5c6-6c19-9764-9b05d68b93d5
* Version Independent ID: e93be4de-f5c6-6c19-9764-9b05d68b93d5
* Content: [/jumptablerdata (put switch case jump tables in `.rdata`)](https://learn.microsoft.com/en-us/cpp/build/reference/jump-table-rdata?view=msvc-170)
* Content Source: [docs/build/reference/jump-table-rdata.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/jump-table-rdata.md)
* Service: **visual-cpp**
* Sub-service: **tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, are you generating an x64 image (it only applies to x64 code). 
You might try building with and without the switch, do a dumpbin /all > somefile.txt after each build, and do a diff of the text files to see if there's a difference.
We don't have the bandwidth to troubleshoot here on the doc feedback alias. If the above doesn't resolve the issue, I encourage you to post at 
[Microsoft Q&A for C++](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
