### ISSUE TITLE
No InitInstance

### ISSUE THREAD

**Issue by greggman** [MicrosoftDocs/cpp-docs#490]
There is no "InitInstance" in a standard C++ program. These docs seem out of date. How do you just take a simple hello world style example and check for memory corruption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff3d639e-f047-92ff-2971-7dc974125e6f
* Version Independent ID: 2b16ec8e-d3ab-190e-7e99-ae76ebc99d7c
* Content: [Using the Debug Build to Check for Memory Overwrite](https://docs.microsoft.com/en-us/cpp/build/reference/using-the-debug-build-to-check-for-memory-overwrite?view=vs-2017)
* Content Source: [docs/build/reference/using-the-debug-build-to-check-for-memory-overwrite.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/using-the-debug-build-to-check-for-memory-overwrite.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@greggman This article is about the tools available for checking memory issues in MFC apps. There's an `InitInstance` call in every MFC program. I admit the doc doesn't really make this clear if you came to it from a search, so it's probably very confusing.

From your question, I assume you were looking for a different article - perhaps this one? The article [Finding Memory Leaks Using the CRT Library](https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2017) has a good overview of using the debug heap functions in your code and in the debugger. [CRT Debug Heap Details](https://docs.microsoft.com/en-us/visualstudio/debugger/crt-debug-heap-details?view=vs-2017) is all about the C Runtime Library facilities for allocation tracking and heap debugging. These are part of the [CRT Debugging techniques](https://docs.microsoft.com/en-us/visualstudio/debugger/crt-debugging-techniques?view=vs-2017) articles, which might be a good place to start for an overview. Be warned, it's definitely advanced if you're only starting at the "Hello, World" level.

**Comment by greggman** [comment]
I'm a little sad you just closed this with no changes. There is absolutely nothing on that entire page that says anything about MFC. Even the Table of Contents of the left makes this seem like the correct page. Isn't there something to done here? Change the title and the table of contents to make it clear this page is about MFC and this entire topic is under some MFC section?

**Comment by corob-msft** [comment]
@greggman You're not wrong, and I didn't mean to give you the impression you're being ignored. Your issue is one of several we've gotten in this section of the documentation. You couldn't know this, but we plan to rework and rearrange this set of articles by the time the next version of Visual Studio comes around, and this specific one may not even exist as a stand-alone article when we're done. I was trying to save myself a bit of work to find and mark this issue closed potentially some months later when the other tasks are finished.

**Comment by MPJansen** [comment]
Just to confirm @greggman s issue with the article, I was very much similarly confused.
