### ISSUE TITLE
Wrong argument in Screenshot of command prompt example

### ISSUE THREAD

**Issue by AndrzejKowalski9917** [MicrosoftDocs/cpp-docs#4900]
The screenshot showing the command prompt example (https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170#command-prompt) shows the option `-fsanitize=address` instead of the correct `/fsanitize=address`.

[Screenshot](https://learn.microsoft.com/en-us/cpp/sanitizers/media/asan-command-basic-global-overflow.png?view=msvc-170)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6dd452-37f0-4bf1-b791-dfdaad2fcab7
* Version Independent ID: 7f114a50-c339-7527-c2fd-6bb73c599947
* Content: [AddressSanitizer](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170)
* Content Source: [docs/sanitizers/asan.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/sanitizers/asan.md)
* Service: **visual-cpp**
* Sub-service: **tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Both -option and /option are accepted.
It's a little unfortunate that they don't match, but it works fine. Given the other things on my plate, I'll never get to this and it doesn't functionally matter.
