### ISSUE TITLE
What does embedding mean in "... array type when embedding is important"?

### ISSUE THREAD

**Issue by ChrisEAlfred** [MicrosoftDocs/cpp-docs#4905]
See title

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [Welcome back to C++ - Modern C++](https://learn.microsoft.com/en-us/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=msvc-170)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Service: **visual-cpp**
* Sub-service: **cpp-lang**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
That's a good question. I'm not sure what the original author was thinking there. Perhaps they were thinking that there is some performance benefit (memory consumption perhaps?) to using an array when it is a member of a class or struct and you don't need the benefits of a vector and you anticipate many instances of the class/struct? Whatever the reason, that's overly broad guidance that seems destined to miss many subtleties. I'm going to remove that from the article. The update will be live by Monday afternoon.
