### ISSUE TITLE
Missing documentation for MV environment variable

### ISSUE THREAD

**Issue by e4lam** [MicrosoftDocs/cpp-docs#4911]
From practical experience, setting the MV environment variable to random strings will confuse cl.exe (the C++ compiler). Please add documentation for this environment variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4afc238-4349-65b7-8e67-ad24e1129018
* Version Independent ID: d4cab2f6-222c-ec99-cf7d-cf178af099a8
* Content: [CL environment variables](https://learn.microsoft.com/en-us/cpp/build/reference/cl-environment-variables?view=msvc-170)
* Content Source: [docs/build/reference/cl-environment-variables.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/cl-environment-variables.md)
* Service: **visual-cpp**
* Sub-service: **tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, as far as I know, MV isn't one of the compiler environment variables. This might be a good question to run past [C++ Q & A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)
