### ISSUE TITLE
Insufficient information about decorated names.

### ISSUE THREAD

**Issue by crazydef** [MicrosoftDocs/cpp-docs#4932]
Regardless of whether the format of decorated names is internal or not, the format should be described fully here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39b37f92-1905-750c-3bea-4500081ab4d6
* Version Independent ID: 8130ccd2-2db8-4ca8-1d65-4f1e5534c8b1
* Content: [Decorated names](https://learn.microsoft.com/en-us/cpp/build/reference/decorated-names?view=msvc-170)
* Content Source: [docs/build/reference/decorated-names.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/decorated-names.md)
* Service: **visual-cpp**
* Sub-service: **tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
This is something we will never get to.
