### ISSUE TITLE
Missing the type returned by sizeof()

### ISSUE THREAD

**Issue by Bob64375** [MicrosoftDocs/cpp-docs#4938]
What type is returned by sizeof() ?

int? unsigned int? unsigned long long?

Depends on if it's the 32 bit compiler or the 64 bit compiler.

I think the answer is size_t

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5963bde5-e75d-6f45-c6ec-da18928db61c
* Version Independent ID: 45921119-671e-494a-a91c-c3c0066e7b6a
* Content: [sizeof Operator](https://learn.microsoft.com/en-us/cpp/cpp/sizeof-operator?view=msvc-170)
* Content Source: [docs/cpp/sizeof-operator.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/sizeof-operator.md)
* Service: **visual-cpp**
* Sub-service: **cpp-lang**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
`sizeof()` is not a library feature of course, it is a C/C++ language feature (operator).
