### ISSUE TITLE
Add Best Practices and Common Mistakes to C++ Documentation

### ISSUE THREAD

**Issue by Njoxpy** [MicrosoftDocs/cpp-docs#4944]
The C++ documentation in this repository would benefit from the inclusion of best practices and common mistakes encountered when working with different parts of the language. By providing guidance on both optimal approaches and potential pitfalls, we can better support users in their development journey.

## Details

- Current State: While the documentation covers basic syntax and usage, it lacks insights into best practices and typical errors.
- Proposed Changes: Integrate sections dedicated to best practices and common mistakes for key aspects of C++ development, including functions, variables, pointers, and other relevant topics.
 - Rationale: Equipping users with best practices can enhance code quality, while highlighting common mistakes can help them avoid errors and improve debugging skills.
 - Expected Impact: Improved comprehension, reduced errors, and enhanced user confidence in working with C++.

**Comment by TylerMSFT** [comment]
Hi, thank you for the suggestion, but that is out of scope for what we are resourced to do.
You may find the [CPP Core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) helpful, though.

**Comment by Njoxpy** [comment]
> Hi, thank you for the suggestion, but that is out of scope for what we are resourced to do. You may find the [CPP Core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) helpful, though.

Ok!
