### ISSUE TITLE
Add ATL Support to MFC project does not work in VS 2022 17.9.0

### ISSUE THREAD

**Issue by mylesdunlop** [MicrosoftDocs/cpp-docs#4949]
STEPS
1. Use the new project wizard to create a new MFC application with default settings
2. Compile and test
3. Select New Item -> ATL -> ATL Support
4. Select New Item -> ATL -> ATL Simple Object

EXPECTED
New ATL object with IDL

ACTUAL
![image](https://github.com/MicrosoftDocs/cpp-docs/assets/14820998/1a145e69-1d0f-4d0a-8e1e-1ae731f3d565)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9a277c7-9a63-bb8d-6b8d-85b7a2178c48
* Version Independent ID: 9f81c54d-8f11-6179-890a-af3afedebc7d
* Content: [Adding ATL Support to Your MFC Project](https://learn.microsoft.com/en-us/cpp/mfc/reference/adding-atl-support-to-your-mfc-project?view=msvc-170)
* Content Source: [docs/mfc/reference/adding-atl-support-to-your-mfc-project.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/adding-atl-support-to-your-mfc-project.md)
* Service: **visual-cpp**
* Sub-service: **mfc-library**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by mylesdunlop** [comment]
I'm aware this is a documentation repository rather than Visual Studio functionality, so please transfer the issue as appropriate.

**Comment by TylerMSFT** [comment]
For things like this, visit [C++ Q&A](https://learn.microsoft.com/en-us/answers/tags/314/cpp)

What's probably happening is you need to add support to Visual Studio for ATL. You do that via the Visual Studio Installer under Individual components and search for ATL in the search box.

**Comment by mylesdunlop** [comment]
Already been down the VS installer route, but thanks for the prompt reply and for the link.
