### ISSUE TITLE
How many bits?

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/cpp-docs#495]
There should be a link somewhere on this page
https://docs.microsoft.com/en-us/cpp/standard-library/complex-long-double?view=vs-2017
to long double type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b8e63a-155d-7dd9-2c05-6310a9a86d23
* Version Independent ID: 862bb5c5-b9c0-7f80-85c2-b9af90e1eb27
* Content: [complex&lt;long double&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/complex-long-double?view=vs-2017)
* Content Source: [docs/standard-library/complex-long-double.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/complex-long-double.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mrmsbarnes Do you have a target article in mind?

**Comment by mrmsbarnes** [comment]
To Colin Robertson,

 

I thought pages referenced themselves when we submit feedback or click ‘No’ on ‘Is this page helpful’

·         I can’t find the article ( <https://docs.microsoft.com/en-us/?view=vs-2017> Docs >  <https://docs.microsoft.com/en-us/cpp?view=vs-2017> Visual C++ >  <https://docs.microsoft.com/en-us/cpp/visual-cpp-in-visual-studio?view=vs-2017> Documentation) page now, but wherever it was it should reference this page:

https://docs.microsoft.com/en-us/cpp/c-language/type-long-double

**Comment by mrmsbarnes** [comment]
I remember now.  See original post.

**Comment by corob-msft** [comment]
@mrmsbarnes The closest equivalent in the C++ language reference is [Fundamental Types (C++)](https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp), but you have to search for the long double type on the page. I've got a fix with that link in progress that clarifies that Microsoft considers **long double** and **double** to be distinct types, but uses the same representation for both.

**Comment by corob-msft** [comment]
The fixed content is live.
