### ISSUE TITLE
Documentation says __VA_OPT__ is enabled by /std:c++20, but it is not

### ISSUE THREAD

**Issue by fredemmott** [MicrosoftDocs/cpp-docs#4953]
https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170

> 20 In versions through Visual Studio 2019 version 16.10, these features are enabled by the /std:c++latest compiler option. Visual Studio 2019 version 16.11 added the /std:c++20 compiler option to enable these features.

This is incorrect; `__VA_OPT__` also requires `/Zc:preprocessor`, which is incompatible with Microsoft libraries such as ETW tracelogging, and is not enabled by `/std:c++20`

According to Microsoft response on https://developercommunity.visualstudio.com/t/__VA_OPT__-should-be-enabled-by-std:c/10565399 , the `/Zc:preprocessor` requirement is expected, so this is a documentation issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C/C++ language conformance](https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/overview/visual-cpp-language-conformance.md)
* Service: **visual-cpp**
* Sub-service: **cpp-lang**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Got it - will update the doc. Thanks for letting me know.

**Comment by TylerMSFT** [comment]
Fixed. Will be live by the middle of the day or so, Monday (2/26)
