### ISSUE TITLE
Where to set /clr in project properties?

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/cpp-docs#496]
This page
https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2017
should somehow link here.  How-to's Step 8 - no "Any CPU" option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d1e8ce-e0d5-321a-1cd3-8d96fecde8ad
* Version Independent ID: 04343afb-ac3b-a7cb-6322-f5608442f554
* Content: [-clr (Common Language Runtime Compilation)](https://docs.microsoft.com/en-us/cpp/build/reference/clr-common-language-runtime-compilation?view=vs-2017)
* Content Source: [docs/build/reference/clr-common-language-runtime-compilation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/clr-common-language-runtime-compilation.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@mrmsbarnes Apologies for the very delayed response. The debugger topic you mention is not using a C++/CLI project and therefore the /clr option doesn't apply in that case. If you create a C++/CLI project you should see the Any CPU option.

**Comment by mrmsbarnes** [comment]
To Mike B,

Thank you.  Makes perfect sense [now].

Oh, to have the sight of a hind.  Re, a drop of golden sun.  Thanks again.
