### ISSUE TITLE
The example code of C4743 seems not to generate any errors

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#497]
The example code of C4743 seems not to generate any errors

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4743?view=vs-2017
https://godbolt.org/z/q0_4Rd

If I try locally on my machine I get a different linker error:
error LNK2001: unresolved external symbol "public: virtual void __cdecl C::f3(void)" (?f3@C@@UEAAXXZ)
error LNK2001: unresolved external symbol "public: virtual void __cdecl C::f2(void)" (?f2@C@@UEAAXXZ)
error LNK2001: unresolved external symbol "public: virtual void __cdecl C::f1(void)" (?f1@C@@UEAAXXZ)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 822a8719-eac1-7597-86ef-c3800560c37e
* Version Independent ID: a3edb0ad-07a8-2183-c81f-0945db70f619
* Content: [Compiler Warning (Level 1) C4743](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4743?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4743.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4743.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by tiagomacarios** [comment]
@corob-msft  Any update on this one?

**Comment by corob-msft** [comment]
@tiagomacarios It looks like the instructions in the second sample are incorrect, or at least, incomplete. If you create both sample files in the same directory, then run

> cl /EHsc /W1 /GL /O2 C4743a.cpp C4743b.cpp

you should get the expected error message.

This is what my output looks like when I do that:
```
C:\Users\corob\Documents\Projects\errors\C4743>cl /EHsc /W1 /GL /O2 C4743a.cpp C4743b.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26732.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

C4743a.cpp
C4743b.cpp
Microsoft (R) Incremental Linker Version 14.15.26732.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:C4743a.exe
/ltcg
C4743a.obj
C4743b.obj
Generating code
warning C4743: 'const C::`vftable'' has different size in 'c:\users\corob\documents\projects\errors\c4743\c4743b.cpp' and 'c:\users\corob\documents\projects\errors\c4743\c4743a.cpp': 24 and 16 bytes
Finished generating code
```

Does this clarify things? I'll look at updating the "compile with" line in the sample to match.

**Comment by mikeblome** [comment]
@tiagomacarios thanks for the feedback. The topic has been updated and the fix should appear in a day or so.
