### ISSUE TITLE
Need documentation or possibility to retrieve the Linux username (or use ~)

### ISSUE THREAD

**Issue by sineang01** [MicrosoftDocs/cpp-docs#506]
I'm trying to setup the remote builds so that every user with a valid SSH login will see his list of remote builds in his own Linux home.
`"remoteCMakeListsRoot": "/home/simone/${workspaceHash}/${name}/src",`
`"remoteBuildRoot": "/home/simone/${workspaceHash}/${name}/build",`
I can't find any way to avoid hard-coding the username in the script because I would like to submit CMakeSettings.json in the repository and there shouldn't be my username in there.

I tried using ~ instead, but it didn't work:
`"remoteCMakeListsRoot": "~/${workspaceHash}/${name}/src",`
`"remoteBuildRoot": "~/${workspaceHash}/${name}/build",`
It can copy files to the remote server in the correct folder but then the configuration system fails without any other warning/error displayed in the console output and when I click the CMake top menu to "Build All", the button is not there and instead it asks again to generate the CMake cache.

Since by default Visual Studio chooses the first remote system in the list under Tools &gt; Options &gt; Cross Platform &gt; Connection Manager it would be great if we can access the User Name specified in this page from a {env. variable} or similar. I can't find any documentation about that though.
`"remoteCMakeListsRoot": "/home/${env.CrossPlatform.DefaultUserName}/${workspaceHash}/${name}/src",`
`"remoteBuildRoot": "/home/${env.CrossPlatform.DefaultUserName}/${workspaceHash}/${name}/build",`
(or similar)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2017)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by sineang01** [comment]
[CMakeSettings.zip](https://github.com/MicrosoftDocs/cpp-docs/files/2519732/CMakeSettings.zip)

**Comment by sfreed141** [comment]
I believe $HOME (or $USER) should work.

**Comment by sineang01** [comment]
Hello Sam,

thanks for your answer! $USER is working :)
So now the line looks like this:
`"remoteCMakeListsRoot": "/home/$USER/${workspaceHash}/${name}/src",`

Cheers,
Simone

**Comment by sineang01** [comment]
By the way after further testing, $USER works perfectly in all cases. $HOME sometimes doesn't work. I couldn't understand exactly what conditions make it working... seems to be after $USER has been used and successfully compiled code at least once.
