### ISSUE TITLE
issue on Dependency Walker description

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/cpp-docs#514]
@BaeMinCheon commented on [Sat Oct 27 2018](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/issues/63)

The "Dependency Walker" is not compatible after Windows 10. Thus, I suggest to mention about the incompatibility or to give some tools for Windows 10 user.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: d0582c64-876f-0044-e004-feaca588d7cb
* Version Independent ID: ca607a95-94bb-e162-2b77-828e5acbc5ed
* Content: [Visual C++ 응용 프로그램의 종속성 이해](https://docs.microsoft.com/ko-kr/cpp/ide/understanding-the-dependencies-of-a-visual-cpp-application?view=vs-2017)
* Content Source: [docs/ide/understanding-the-dependencies-of-a-visual-cpp-application.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/ide/understanding-the-dependencies-of-a-visual-cpp-application.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by LisandroSu** [comment]
Hi team,

Please check the feedback provided by the user.

Thanks!

**Comment by corob-msft** [comment]
@BaeMinCheon I asked the Windows SDK team if they have an updated dependency tool that we can publish. There hasn't been an answer yet. However, there is a third-party tool available that might help you at [https://github.com/lucasg/Dependencies](https://github.com/lucasg/Dependencies). (Microsoft does not have any connection to this project.)

**Comment by BaeMinCheon** [comment]
@LisandroSu @corob-msft
Thank you for the feedback on my suggestion. And, actually, I am already using that tool (lucasg/Dependencies). Just in my view, it seems that the document needs to be updated.

**Comment by mikeblome** [comment]
updated the text to mention the github project. Update will appear within the next week or so. @LisandroSu thanks!
