### ISSUE TITLE
Example in error

### ISSUE THREAD

**Issue by kurt-krueckeberg** [MicrosoftDocs/cpp-docs#516]
The example given of 
#include &lt;iostream&gt;
using namespace std;
// A class that contains a memory resource.
class MemoryBlock
{
   // TODO: Add resources for the class here.
};
void g(const MemoryBlock&)
{
   cout &lt;&lt; "In g(const MemoryBlock&)." &lt;&lt; endl;
}
void g(MemoryBlock&&)
{
   cout &lt;&lt; "In g(MemoryBlock&&)." &lt;&lt; endl;
}
MemoryBlock&& f(MemoryBlock&& block)
{
   g(block);
   return block; /*  error: cannot bind rvalue reference of type ‘MemoryBlock&&’ to lvalue of type ‘MemoryBlock’ */
}
int main()
{
   g(f(MemoryBlock()));
}
Results in a compile error in the function:
MemoryBlock&& f(MemoryBlock&& block)
{
   g(block);
   return block; /*  error: cannot bind rvalue reference of type ‘MemoryBlock&&’ to lvalue of type ‘MemoryBlock’. Solution: return move(block); */
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68443dd2-4598-7964-726f-ab09dda93fc8
* Version Independent ID: 5dd4bc99-a410-a265-50df-31a95a279a11
* Content: [Rvalue Reference Declarator: &&](https://docs.microsoft.com/en-us/cpp/cpp/rvalue-reference-declarator-amp-amp?view=vs-2017)
* Content Source: [docs/cpp/rvalue-reference-declarator-amp-amp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/rvalue-reference-declarator-amp-amp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@kurt-krueckeberg Thank you! Code example is fixed and should be visible soon.
