### ISSUE TITLE
Help missing for IDispatch::Invoke

### ISSUE THREAD

**Issue by deanwiles** [MicrosoftDocs/cpp-docs#517]
IDispatchImpl Class says "See IDispatch::Invoke in the Windows SDK." but that link is broken. Developers still need help for existing products like Windows SDK! Where can we get Microsoft help for Windows SDK API's?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6d5835-61f5-5e03-c052-910150489396
* Version Independent ID: 4c5670ef-74d6-3d11-b32c-8bd8b3a1cfe9
* Content: [IDispatchImpl Class](https://docs.microsoft.com/en-us/cpp/atl/reference/idispatchimpl-class?view=vs-2017#invoke)
* Content Source: [docs/atl/reference/idispatchimpl-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/idispatchimpl-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@mikeblome It looks like the Windows team may have fixed the issue with material mistakenly going into the archive. This will work if you remove the /previous-versions part of the link. Maybe Mark has a list of similar content?

**Comment by mikeblome** [comment]
@deanwiles The link is working now. Thanks for the feedback!
