### ISSUE TITLE
Document __declspec(allocator)

### ISSUE THREAD

**Issue by Donpedro13** [MicrosoftDocs/cpp-docs#518]
__declspec(allocator) is available ~since Visual Studio 2015 and should be documented on this page. It's briefly mentioned here: https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?view=vs-2017
and here: https://docs.microsoft.com/en-us/visualstudio/profiling/custom-native-etw-heap-events?view=vs-2017#how-to-use

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 0b97db02-7e53-f7b2-c1b3-d406b6e293b7
* Version Independent ID: a97cb658-b551-7324-4d44-6f6d676c3870
* Content: [__declspec](https://docs.microsoft.com/hu-hu/cpp/cpp/declspec?view=vs-2017)
* Content Source: [docs/cpp/declspec.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/declspec.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Donpedro13 this is fixed and should be published later today. thanks!
