### ISSUE TITLE
"Connect to Your Remote Linux Computer" from a TFS Build Agent?

### ISSUE THREAD

**Issue by loicmorvan-ansys** [MicrosoftDocs/cpp-docs#523]
The document does not explain how to configure the remote linux computer to be used in a build agent.
Can you add this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Connect to your remote Linux computer  in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2017)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Investigating

**Comment by mlearned** [comment]
@loicmorvan-ansys  are you talking about an Azure DevOps (Formerly VSTS) build agent?  If so, see this article  https://docs.microsoft.com/azure/devops/pipelines/agents/v2-linux

**Comment by loicmorvan-ansys** [comment]
Nope. We use Linux vcxproj in our solution along with csporj and Windows vcxproj. We just need to configure a ssh connection to a Linux in order to let the Linux projects to be built during the Build (thus on a regular Windows Build Agent).

**Comment by corob-msft** [comment]
@loicmorvan-ansys Unless you have an unusual file system layout on your Linux box, it should be sufficient just to run the ssh service, as described in step 2 of either the [Ubuntu](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=vs-2017#linux-setup-ubuntu) or [Fedora](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=vs-2017#linux-setup-fedora) set-up instructions. If you can access your Linux box from a Windows command prompt by using the **ssh** command, then once you've configured Visual Studio to connect, it should have no problem, either. Or maybe I'm not understanding the problem.

**Comment by adnanshaheen** [comment]
I'm using an opensuse leap 42.2 box and trying to connect to remote system. It can't verify my credentials. Whereas I can login via ssh from cmd using same credentials. Is opensuse leap 42.2 not supported?

**Comment by corob-msft** [comment]
@adnanshaheen The docs team can't help you with this sort of question. If you have an issue with the product or libraries, the best place to bring it up is the [Developer Community C++ forum](https://developercommunity.visualstudio.com/spaces/62/index.html). Odds are at least fair that someone else has run into the issue and reported it already, so it pays to search first. If you don't see your particular issue, we have some instructions on how to write a bug report that's easy for the developers to reproduce and fix in [How to report a problem with the Visual C++ toolset or documentation](https://docs.microsoft.com/en-us/cpp/how-to-report-a-problem-with-the-visual-cpp-toolset).

**Comment by DamianSuess** [comment]
Are there any plans to support C#? I'd like to perform remote debugging with our prototypes on the Raspberry Pi. So far there are 3rd-party solutions with limited support and would prefer a baked-in Visual Studio solution. Previously, I'd use MonoDevelop (Xamarin Studio) for this.
