### ISSUE TITLE
Link is leading to non-existing page

### ISSUE THREAD

**Issue by Dirksche** [MicrosoftDocs/cpp-docs#526]
The link in
&gt; See IErrorRecords::GetErrorInfo in the OLE DB Programmer's Reference.

is leading to a non-existing page.

The same applies to the link in:
&gt; See IErrorRecords::GetBasicErrorInfo in the OLE DB Programmer's Reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8cd525d-0bbe-70ca-246d-35307185d61c
* Version Independent ID: c097db11-aae7-bd92-f479-ee04d4b31a0f
* Content: [IErrorRecordsImpl Class](https://docs.microsoft.com/en-us/cpp/data/oledb/ierrorrecordsimpl-class?view=vs-2017#geterrorinfo)
* Content Source: [docs/data/oledb/ierrorrecordsimpl-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/data/oledb/ierrorrecordsimpl-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Dirksche thanks for the heads-up. This along with all the other broken links in this section should be fixed in tomorrow's build.

**Comment by corob-msft** [comment]
Fixes are live.
