### ISSUE TITLE
HString does not have a constructor that takes an HSTRING

### ISSUE THREAD

**Issue by bviglietta** [MicrosoftDocs/cpp-docs#527]
This documented constructor does not exist:

HString(HSTRING hstr = nullptr) throw();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dac57d-a52b-8a76-76dd-726d5579a984
* Version Independent ID: 6a4ef894-94a6-0888-af31-a4d7f3d7e680
* Content: [HString Class](https://docs.microsoft.com/en-us/cpp/windows/hstring-class?view=vs-2017#hstring)
* Content Source: [docs/windows/hstring-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/hstring-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@bviglietta thanks! Fix should appear later today.
