### ISSUE TITLE
CMakeSettings, IntelliSense, 3rd-party tool chains, & predefined symbols: How to declare?

### ISSUE THREAD

**Issue by SkySchulz** [MicrosoftDocs/cpp-docs#529]
Greetings,

I am attempting to configure our VS/CMake build using a 3rd-party tool chain (and VSC). I can find no way to inform IntelliSense of the predefined symbols for the 3rd-party tool chain. This results in invalid warnings/errors when the non-VSC-based configurations are selected and the 3rd-party SYSROOT include files are parsed by IntelliSense.

I attempted to add a `CppProperties.json` file with a `"defines"` list to the project root, but alas, this did nothing useful:

```json
{
    "configurations": [
        {
            "name": "ThirdParty-x64-Debug",
            "defines": [
                "__THIRD_PARTY__"
            ]
        }
    ]
}
```

Is there a way to inject predefined symbols in the `environment` I have defined for the 3rd-party tool chain in `CMakeSettings.json` ?

```JSON
{
    "environments": [
        {
            "NINJA_STATUS": "[${name} %f/%t %es] "
        },
        {
            "environment": "thirdparty_x64",
            "defines":  [ "__THIRD_PARTY__" ],
            "INCLUDE": "${env.__THIRD_PARTY__}/host_tools/lib/clang/include;${env.__THIRD_PARTY__}/target/include;${env.__THIRD_PARTY__}/target/include_common;"
        }
    ],
    "configurations": [
        {
            "name": "ThirdParty-x64-Debug",
            "generator": "Ninja",
            "configurationType": "Debug",
            "buildRoot": "${projectDir}/target/cmake/${name}",
            "installRoot": "c:/thirdparty",
            "intelliSenseMode": "windows-clang-x64",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "-v",
            "ctestCommandArgs": "",
            "inheritEnvironments": [ "thirdparty_x64" ],
            "variables": [
                {
                    "name": "CMAKE_TOOLCHAIN_FILE",
                    "value": "${projectDir}/toolchains/thirdparty/THIRDPARTY.cmake"
                }
            ]
        },
    ],
}
```

Any guidance would be appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Investigating

**Comment by SkySchulz** [comment]
@sineang01 In general, yes, predefined symbols for the build live in CMakeLists.txt. In this specific case, the symbols in question are defined by the tool chain itself and should _not_ be redefined in the build configuration, as doing so generates loads of warnings about redefining already defined symbols and increases the overall complexity of correctly managing a cross-platform build.

@mikeblome  The ideal would be to have IntelliSense query CMake (and the tool chain) about the predefined symbols for a particular build configuration, and keep the configuration DRY.

Cheers!

**Comment by mikeblome** [comment]
@SkySchulz Thanks for the feedback! We have improved the Cmake documentation recently so hopefully the questions you had are addressed more clearly now. For product suggestions, please post them on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) page.
