### ISSUE TITLE
Option is deprecated

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/cpp-docs#531]
The latest C++ compiler generates D9035 for this option now. The warning doesn't generate any information about how to resolve it though. I found a reference to the deprecation in this issue (https://developercommunity.visualstudio.com/content/problem/99877/vs2017-1532-c-minimalrebuild-incorrectly-skips-com.html) report. I think it makes sense to update the docs with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea6ed650-440a-2727-27ca-a0d525bedb36
* Version Independent ID: 6bca3499-1315-133a-81fd-711f00bffedf
* Content: [/Gm (Enable Minimal Rebuild)](https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild?view=vs-2017)
* Content Source: [docs/build/reference/gm-enable-minimal-rebuild.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/gm-enable-minimal-rebuild.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Fix is live.

**Comment by CoolDadTx** [comment]
Thanks
