### ISSUE TITLE
Link to TechNet under the "Guidance" section returns 404

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/cpp-docs#533]
@MasterMann commented on [Sat Nov 10 2018](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/issues/35)

Title. Please look into this and fix the link.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8ac840f5-eb3b-455b-472b-85d680a6f6ff
* Version Independent ID: 50510bc9-006c-ee1a-711f-9736736c9069
* Content: [/hotpatch (Создать образ с обновлениями)](https://docs.microsoft.com/ru-ru/cpp/build/reference/hotpatch-create-hotpatchable-image?view=vs-2017)
* Content Source: [docs/build/reference/hotpatch-create-hotpatchable-image.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/build/reference/hotpatch-create-hotpatchable-image.md)
* Product: **visual-cpp**
* GitHub Login: @v-anpasi

**Comment by LisandroSu** [comment]
Hi team,

Please check the link under guidance that returns 404.

Thanks!

**Comment by corob-msft** [comment]
@LisandroSu @MasterMann This link is to obsolete content, so I'm going to delete it. If you're curious, the last version of the linked document is available in the TechNet archive under [Standardizing the Patch Experience](https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc700838(v%3dtechnet.10)).
