### ISSUE TITLE
Error Convert Standard String to System::String

### ISSUE THREAD

**Issue by refactormyself** [MicrosoftDocs/cpp-docs#534]
This is giving me error:

> E0289 no instance of constructor "System::String::String" matches the argument list	
>argument types are: (std::basic_string<char, std::char_traits<char>, std::allocator<char>>)

Here is my code

```
std::string txt = "please, simplify things";
String ^ text = gcnew String(txt); 

```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a92c5f6-460e-5bdf-3a21-3d35871dbfbe
* Version Independent ID: d42af46a-a611-19fb-429d-28f3ea6f774d
* Content: [How to: Convert Standard String to System::String](https://docs.microsoft.com/en-gb/cpp/dotnet/how-to-convert-standard-string-to-system-string?view=vs-2017)
* Content Source: [docs/dotnet/how-to-convert-standard-string-to-system-string.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-convert-standard-string-to-system-string.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@refactormyself did you try passing the c_str() member like this?
String ^ text = gcnew String(txt.c_str());
