### ISSUE TITLE
Predefined Macros _MSC_VER needs to be updated for 15.8 and 15.9

### ISSUE THREAD

**Issue by StephanTLavavej** [MicrosoftDocs/cpp-docs#535]
The table of _MSC_VER values needs to be updated for VS 2017 15.8 and 15.9.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined Macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2017)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@StephanTLavavej Thanks for the problem report. The fix appears to be live now, so I'm closing it.
