### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by yves-dolce** [MicrosoftDocs/cpp-docs#538]
Where is the documentation for reduce(), transform_reduce(), inclusive_scan(), .... ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b715ca60-7363-e775-4dc5-7723dea2178a
* Version Independent ID: 276f458f-7934-e858-9475-3766496e6f4d
* Content: [&lt;numeric&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/numeric-functions?view=vs-2017#feedback)
* Content Source: [docs/standard-library/numeric-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/numeric-functions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yves-dolce Same place as gcd and lcm. Sadly, the new-for-C++17 library additions are relatively low on the documentation priority list. We are aware of the deficit, and the tasks are on the backlog, but there's no timeline for them yet.

**Comment by yves-dolce** [comment]
Late thank you.. for answering. :-)

**Comment by mikeblome** [comment]
closing this issue as we are tracking it internally. we have started work on C++17 library updates.
