### ISSUE TITLE
Link to MSBuild - Overview of MSBuild concepts

### ISSUE THREAD

**Issue by darrenkorman** [MicrosoftDocs/cpp-docs#54]
On page https://docs.microsoft.com/en-us/cpp/build/msbuild-visual-cpp-overview,
the link to [MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild1) - Overview of MSBuild concepts results in "page not found".  Perhaps the "1" at the end of the URL is a typo?

**Comment by corob-msft** [comment]
Thanks! Fixed with PR #55. For future reference, you're welcome to propose your own edit for issues like this and submit a pull request, too.
