### ISSUE TITLE
The dispid of Click should be (-600)

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/cpp-docs#541]
@hoodlum1980 commented on [Tue Nov 13 2018](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/issues/41)

I review the demo c++ code, and found the dispid of Click event in the code is not correct.
I took a look of the typelib (with the OLEVIEW tool provided together with VC6.0 ) of the Calender OCX (By the way, the full path of the ocx on my pc is:
"D:\Program Files (x86)\Microsoft Office\Office12\MSCAL.OCX"), 
and found the Click event 's dispid should be (-600 in decimal) (or 0xfffffda8 in hex ).
while the dispid of 1 belongs to the event of "AfterUpdate", according to the typelib.
DISPID_CLICK is pre defined as (-600) in "olectl.h", so I think the correction should be like this, thanks.
```
BEGIN_SINK_MAP(CMainWindow)
      //SINK_ENTRY_EX(1, __uuidof(DCalendarEvents), 1, OnClick) //this is the original code.
    SINK_ENTRY_EX(1, __uuidof(DCalendarEvents), DISPID_CLICK, OnClick) //correction;
END_SINK_MAP()
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a7baa37c-bb08-3884-5df6-91de2ab6f32b
* Version Independent ID: bca4c39e-a7ac-cbe8-9569-1c48cfa42719
* Content: [ATL 控件包含常见问题](https://docs.microsoft.com/zh-cn/cpp/atl/atl-control-containment-faq?view=vs-2017)
* Content Source: [docs/atl/atl-control-containment-faq.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/atl/atl-control-containment-faq.md)
* Product: **visual-cpp**
* GitHub Login: @v-anpasi

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported by the user.

Thanks!

**Comment by mikeblome** [comment]
fixed! Thanks.
