### ISSUE TITLE
Should mention that Release 15.9 introduces "warning C4866: compiler may not enforce left-to-right evaluation order for <XXX>"

### ISSUE THREAD

**Issue by KorkyPlunger** [MicrosoftDocs/cpp-docs#557]
Our code that compiled cleanly under 15.8.9 now encounters several instances of this warning after installing 15.9. It would be helpful to mention this here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52d20ec-2725-57ac-55ad-6584017059ff
* Version Independent ID: 38807675-ee62-3472-653b-d2d5d2433d45
* Content: [C++ conformance improvements](https://docs.microsoft.com/en-us/cpp/cpp-conformance-improvements-2017?view=vs-2017#update_159)
* Content Source: [docs/cpp-conformance-improvements-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp-conformance-improvements-2017.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating.

**Comment by mikeblome** [comment]
@KorkyPlunger Sorry for delayed response. The product team agrees this new warning should be listed on conformance improvements page. Look for an update later today. Thanks!
