### ISSUE TITLE
dynamic_cast documentation

### ISSUE THREAD

**Issue by joshg47** [MicrosoftDocs/cpp-docs#559]
It says "Use dynamic_cast when you cast an object (more specifically, a hat ^) to a more derived type, you expect either that the target object might sometimes be nullptr or that the cast might fail, and you want to handle that condition as a regular code path instead of an exception."

This part shouldn't be included "Expect either that the target object might sometimes be nullptr" because static and safe cast will convert a null pointer value to the null pointer value of the destination type. You only need dynamic cast when the cast might fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9be2a7-0a97-4269-a555-f4f450ddcfa5
* Version Independent ID: eb0b159b-3c76-6c92-39cd-751dac5e66fa
* Content: [Casting (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/casting-c-cx?view=vs-2017)
* Content Source: [docs/cppcx/casting-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/casting-c-cx.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@joshg47 The example that follows the sentence shows the use of dynamic_cast to handle a nullptr as a normal program execution path. I am assuming that the Microsoft engineers who created that template boilerplate code chose dynamic_cast for a good reason. So I think the sentence is accurate. Whether another kind of cast could be used in this context is a separate question.
