### ISSUE TITLE
/Oy is not just x86.

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/cpp-docs#560]
This doc say "/Oy is available only in x86 compilers.".
However, the ARM ABI and ARM64 ABI doc suggests that /Oy- can be used.
https://docs.microsoft.com/en-us/cpp/build/overview-of-arm-abi-conventions?view=vs-2017#stack-walking
https://docs.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions?view=vs-2017#stack-walking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd14f34-9a79-51c8-5691-0af44764db45
* Version Independent ID: fc84eed6-cfc6-aa7d-1ac7-f3cb8278572d
* Content: [/Oy (Frame-Pointer Omission)](https://docs.microsoft.com/en-us/cpp/build/reference/oy-frame-pointer-omission?view=vs-2017)
* Content Source: [docs/build/reference/oy-frame-pointer-omission.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/oy-frame-pointer-omission.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@0xbadfca11 You're right. I've updated the topic for a more general scenario.

**Comment by corob-msft** [comment]
This should be live shortly.
