### ISSUE TITLE
Variables declared in local environments of CppProperties.json aren't visible in tasks

### ISSUE THREAD

**Issue by AlvaroBurnett** [MicrosoftDocs/cpp-docs#561]
This is a bug report. In the following example, the make utility won't see LOCAL_VAR when the "My config" configuration is selected in the IDE, but it will see GLOBAL_VAR.

//CppProperties.json
{
  "environments": [
    {
		GLOBAL_VAR:"This is a global var"
    }
  ],
  "configurations": [
    {
      "name": "My config",
	  "environments": [
		{
		  "LOCAL_VAR":"This is a local var"
		}
	  ]
    }
  ]
}

//tasks.vs.json
{
  "version": "0.2.1",
  "tasks": [
    {
      "taskName": "make",
      "appliesTo": "*",
      "type": "command",
      "contextType": "build",
      "command": "${env.COMSPEC}",
      "args": [
        "make"
      ]
    }
  ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017)
* Content Source: [docs/ide/non-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/non-msbuild-projects.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by sfreed141** [comment]
Hi @AlvaroBurnett,
I was able to access a local variable using `${env.LOCAL_VAR}`. Does that work for you?

If it's still an issue, could you please open an issue on [Developer Community](https://developercommunity.visualstudio.com) so we can track it better?

**Comment by mikeblome** [comment]
closing as not a documentation issue.
