### ISSUE TITLE
Order of expressions in the example.

### ISSUE THREAD

**Issue by jimmybenz** [MicrosoftDocs/cpp-docs#568]
I'd like to suggest that const int ci =7 example above appears below the ((i &lt; 3) ? i : j) = 7 example. The only reason I say this is that it can be a little difficult to determine why the last example is correct when it doesn't contain the constant ci.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237f8fe6-6e21-6d53-6be4-d1c9fd22b561
* Version Independent ID: 8efc4852-cc33-2918-98a2-4fed3d3984e5
* Content: [Value Categories: Lvalues and Rvalues (Visual C++)](https://docs.microsoft.com/en-us/cpp/cpp/lvalues-and-rvalues-visual-cpp?view=vs-2017)
* Content Source: [docs/cpp/lvalues-and-rvalues-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/lvalues-and-rvalues-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by jb-lsc** [comment]
Other than this this is a great example.

**Comment by corob-msft** [comment]
@jb-lsc This seems perfectly reasonable. Would you like to make a PR with that change? That's exactly the sort of thing that the **edit** button in the upper right area of the topic is meant for. [Here's a quick guide for contributors](https://docs.microsoft.com/contribute/).

**Comment by corob-msft** [comment]
Looks like the fix is live. Thanks!
