### ISSUE TITLE
Clarify "Initializing a reference with a bit field" restriction

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/cpp-docs#57]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cpp/cpp-bit-fields.md

The page says:

> Restrictions on bit fields
> The following list details erroneous operations on bit fields:
> *  Taking the address of a bit field.
> *  Initializing a reference with a bit field.

The second point is not accurate.
* If it says that both references, const and non-const, are erroneous, then entire section should go to the **Microsoft Specific** section.
* Otherwise, it the page should distinguish those types of references clarifying which are supported and which are not, for bit fields, in comparison to C++ standard

http://en.cppreference.com/w/cpp/language/bit_field says
> When initializing a const reference from a bit field, a temporary is created (its type is the type of the bit field), copy initialized with the value of the bit field, and the reference is bound to that temporary.

**Comment by ghogen** [comment]
@mikeblome

**Comment by corob-msft** [comment]
This has a fix that's waiting on @mikeblome to review.

**Comment by mloskot** [comment]
Thanks!
