### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/cpp-docs#576]
In the section "Removing an event handler from the subscriber side" how and why is the following true " However, the original handler could still be invoked even after it's removed."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa0c454-4197-8ee4-e54b-772772da7b6a
* Version Independent ID: f2e3fc35-8517-186a-9c6e-18b14de7ff1e
* Content: [Events (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/events-c-cx?view=vs-2017)
* Content Source: [docs/cppcx/events-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/events-c-cx.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@fman028 This is describing a race condition where the the event source gets a list of handlers and starts invoking them, but in the meantime you have removed yourself so that list is actually out of date.

**Comment by fman028** [comment]
Ah I see, that makes sense.  Thanks Mike!
