### ISSUE TITLE
想快速得到需要的结果却始终没有找到！

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#577]
@wxyGitHub20181128 commented on [Wed Nov 28 2018](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/issues/43)

[在此处输入反馈]
没有一个例子说明怎样做一个批处理文件，打开命令行窗口，然后执行编译链接生成可执行文件；

我实验的结果是只能打开，配置环境，但没能编译！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fbe5bf92-274e-ebfd-401e-f3740dd60644
* Version Independent ID: de36ca5c-c165-9d48-bbe5-2e3e17afbbb5
* Content: [演练： 创建标准 c + + 程序 （c + +）](https://docs.microsoft.com/zh-cn/cpp/windows/walkthrough-creating-a-standard-cpp-program-cpp?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hi team, 
the contributor is asking for more examples.
Rough translation:

> 
> There is no example of how to make a batch file, open a command line window, and then execute the build link to generate the executable file;
> 
> The result of my experiment is that I can only open, configure the environment, but failed to compile!

**Comment by mikeblome** [comment]
This topic is intended to show how to build from the Visual Studio IDE, not the command line. For command-line builds, see https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2017
