### ISSUE TITLE
pReturnValue parameter documentation needs additional clarity

### ISSUE THREAD

**Issue by jeffwick-msft** [MicrosoftDocs/cpp-docs#580]
wcstombs_s documentation for parameter pReturnValue is unclear. In the Parameters section, it is stated to be "The number of characters converted" where as later in the Remarks section it states "it puts the size in bytes of the converted string, including the null terminator, into *pReturnValue". Given there may be multi-byte characters, and a null terminator, the first definition of the parameter is lacking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79027810-d629-5a02-4e23-58164db42d1e
* Version Independent ID: fb2f489f-343d-9967-7965-fbea40443d53
* Content: [wcstombs_s, _wcstombs_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/wcstombs-s-wcstombs-s-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/wcstombs-s-wcstombs-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/wcstombs-s-wcstombs-s-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jeffwick-msft You're right, the short description in the Parameters section could use more clarity. The Remarks section describes the actual behavior. Would you like to submit a fix? We've got a handy [contributor's guide](https://docs.microsoft.com/contribute/) that describes the not-too-complicated process.

**Comment by corob-msft** [comment]
Fixed courtesy of @MSDN-WhiteKnight, this should appear by the next scheduled publication date (next Monday by noon Pacific time).
