### ISSUE TITLE
wrong doc about INTERNET_STATUS_CONNECTING_TO_SERVER

### ISSUE THREAD

**Issue by tongzhipeng** [MicrosoftDocs/cpp-docs#583]
document about the following two status of OnStatusCallback  is wrong
 INTERNET_STATUS_CONNECTING_TO_SERVER
 INTERNET_STATUS_CONNECTED_TO_SERVER
the doc indicates that lpvStatusInformation is a pointer of SOCKADDR struct, while it's not, I have tested it on vc6 and VS2015,  lpvStatusInformation  is an IP string, like "123.123.123.123"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def91c87-caa5-c44d-c0c5-b74e401b8cd4
* Version Independent ID: 7791d315-a5ea-365a-48f8-ee2517faed2b
* Content: [CInternetSession Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cinternetsession-class?view=vs-2017#onstatuscallback)
* Content Source: [docs/mfc/reference/cinternetsession-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cinternetsession-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@tongzhipeng In C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\src\mfc\inet.cpp I see this code which tells me the document is correct. The call to TRACE shows only the sa_data member, which perhaps is IP string?

	case INTERNET_STATUS_CONNECTING_TO_SERVER:
		{
		sockaddr* pSockAddr = (sockaddr*) lpvStatusInformation;
		TRACE(traceInternet, 1, _T("connecting to socket address '%Ts'\n"), pSockAddr->sa_data);
		}
		break;

**Comment by tongzhipeng** [comment]
I haven't test it on VS2017,  the sockaddr struct definition is:
typedef struct sockaddr {
  u_short sa_family;
  char    sa_data[14];
} SOCKADDR, *PSOCKADDR, *LPSOCKADDR;
which means the first two bytes should be sa_family,  my test result shows lpvStatusInformation just starts with ip, not the sa family value.

**Comment by mikeblome** [comment]
@tongzhipeng Sorry, I don't have expertise to know what's happening here, and the topic seems correct based on mfc source. Maybe something in Windows DLL is the root cause? Can you raise the issue on the [C++ Developer Community forum](https://developercommunity.visualstudio.com/topics/C%2B%2B.html)

**Comment by tongzhipeng** [comment]
@mikeblome  could i just close the issue?

**Comment by mikeblome** [comment]
yes let's close here and please ask on the Developer Community. Someone there should be able to answer.
