### ISSUE TITLE
Incorrect structure member

### ISSUE THREAD

**Issue by sinsi1998** [MicrosoftDocs/cpp-docs#592]
BYTE rgbReserved[16]

should be

BYTE rgbReserved[32]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49078fa0-ede6-a590-c24d-24161ba813b3
* Version Independent ID: 60d9d5a5-23a6-0a08-f260-1fd9cb3c93a6
* Content: [PAINTSTRUCT Structure](https://docs.microsoft.com/en-au/cpp/mfc/reference/paintstruct-structure?view=vs-2017)
* Content Source: [docs/mfc/reference/paintstruct-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/paintstruct-structure.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@sinsi1998 It looks like we have removed this page, along with all its errors, and now redirect to the windows topic which does have the correct length for rgbReserved.
