### ISSUE TITLE
__rdtscp documentation incorrectly claims it as serializing - underlying CPU instruction AIN'T serializing

### ISSUE THREAD

**Issue by no-identd** [MicrosoftDocs/cpp-docs#594]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/intrinsics/rdtscp.md

This contains the following claim:

"Unlike rdtsc, rdtscp is a serializing instruction"

However, one can only view this as simply a wrong claim, as outlined here for the actual underlying instruction, it just acts VERY SIMILAR to a serializing instruction, but that doesn't make it truly serializing:
https://www.felixcloutier.com/x86/RDTSCP.html

Please figure out a way to more properly document this function - I can't, as I have no idea what you actually internally do with this thing. It seems oddly concerning that you only quote AMD documentation in this entry, too.

And you might want to make explicit mention of LFENCE & MFENCE here, too (as the entry by @zneak already does), especially in light of the whole Spectre debacle...

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@no-identd yep you are correct. we have fixed the topic and it should get published in a day or so. thanks!

**Comment by no-identd** [comment]
@mikeblome great news!

I however can't help but feel like the documentation containing this error for so long must have left a lot of hubris(I at the moment don't quite recall how I ran into it and can't access my notes rn), in a sort of nega-butterfly effect?

You might want to go over where all y'all use this internally @ MS/inside Windows source code (or have someone else @ MS do so for you?), 'just' to make sure this hasn't left any issues? idqk rn

**Comment by mikeblome** [comment]
@no-identd I will pass your recommendation on to the developer teams!
