### ISSUE TITLE
FileSystem should not be experimental any more

### ISSUE THREAD

**Issue by malidiab** [MicrosoftDocs/cpp-docs#596]
According to https://blogs.msdn.microsoft.com/vcblog/2018/05/07/announcing-msvc-conforms-to-the-c-standard/ 
New Features: Filesystem

C++17’s &lt;filesystem&gt; is supported. This is a completely new implementation, incompatible with the previous std::experimental version, necessitated by symlink support, bug fixes, and changes in standard-required behavior. Currently, including &lt;filesystem&gt; provides the new std::filesystem and the previous std::experimental::filesystem, and including &lt;experimental/filesystem&gt; provides only the old experimental implementation. The experimental implementation will be REMOVED in the next ABI-breaking release of the libraries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c5e891-c7cb-d51b-b061-7b0135e6cf96
* Version Independent ID: dfe5d8be-0ac3-7bfd-7ca3-68842c1425d7
* Content: [File System Navigation](https://docs.microsoft.com/en-us/cpp/standard-library/file-system-navigation?view=vs-2017)
* Content Source: [docs/standard-library/file-system-navigation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/file-system-navigation.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@malidiab Thanks for the comment! In VS2017 the filesystem namespace is still under "experimental" so we have to document it as such.

**Comment by DarranRowe** [comment]
Just to pop in a note from 2020, the code on this page still accesses the experimental namespace and in VS2019 16.5 it will fail to compile. The experimental namespace no longer exists in <filesystem> and it will block you from using it if /std is not set to c++17.
