### ISSUE TITLE
US dates

### ISSUE THREAD

**Issue by SamMackrill** [MicrosoftDocs/cpp-docs#597]
Dates at top do not respect localisation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20d9a71-dacd-a845-90a8-d67e09a8cd2d
* Version Independent ID: 379f606d-f996-fa56-a38b-fa02c8b21adb
* Content: [/SOURCELINK (Include Sourcelink file in PDB)](https://docs.microsoft.com/en-us/cpp/build/reference/sourcelink?view=vs-2017)
* Content Source: [docs/build/reference/sourcelink.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/sourcelink.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SamMackrill Is this a documentation issue, or a product issue? I don't see a mention of date formats in this topic.
