### ISSUE TITLE
Seems to be missing C4199

### ISSUE THREAD

**Issue by PeterPann23** [MicrosoftDocs/cpp-docs#598]
Title claims C4199 though doesn't mention C4198 and C4199

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f6c31e-bf83-d8b2-ba3b-bffffe6ab01d
* Version Independent ID: a121ec1e-0cb4-3851-7c56-c3af989990df
* Content: [Compiler Warnings C4000 Through C4199](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4000-through-c4199?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4000-through-c4199.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warnings-c4000-through-c4199.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@PeterPann23 
Not all the numbers are assigned to messages, but they might in the future, so we're just future-proofing here.
