### ISSUE TITLE
CWnd::OnNcHitTest (#onnchittest) missing hit-test codes

### ISSUE THREAD

**Issue by Ry-Fi** [MicrosoftDocs/cpp-docs#599]
CWnd::OnNcHitTest (#onnchittest) says "One of the mouse hit-test enumerated values listed below", and many occurrences of "hit-test" link to #onnchittest, but the codes are not listed here or anywhere in cwnd-class.

I realize they're in the linked WM_NCHITTEST documentation, but the wording is very misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f567a739-943e-c85d-07a1-d43229fa6d4e
* Version Independent ID: c41ddd0d-df30-7ac0-407b-d7a9c9a18478
* Content: [CWnd Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwnd-class?view=vs-2017#feedback)
* Content Source: [docs/mfc/reference/cwnd-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cwnd-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Ry-Fi agreed that it's confusing. Link to the Windows message topic has been added in a few places. thanks! Updated topic should be visible tomorrow.
