### ISSUE TITLE
Doc "Cancellation in the PPL" references obsolete function is_task_cancellation_requested()

### ISSUE THREAD

**Issue by jjakubovic** [MicrosoftDocs/cpp-docs#60]
In this doc:

https://docs.microsoft.com/en-us/cpp/parallel/concrt/cancellation-in-the-ppl

In second example, obsolete, no longer existing function is_task_cancellation_requested() is used to check for task cancellation. Token should be probably checked instead (cancellation_token::is_canceled). It would also be good to describe in the text, how to check for task cancellation.

**Comment by mikeblome** [comment]
Good catch thank you! The code and text have been updated and the changes should be live later today.

**Comment by jjakubovic** [comment]
Thanks, I can see the change.

There's a small glitch in reference to is_canceled() in updated text:
Work that is already active can use the [is_canceled]((../../parallel/concrt/reference/cancellation-token-class.md#is_canceled) member function to monitor the cancellation token and stop when it can.

**Comment by corob-msft** [comment]
We appear to have forgotten to follow up on this. I've pushed a fix for the typo that caused the formatting error. Thanks for pointing it out.
