### ISSUE TITLE
Wrong example?

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/cpp-docs#600]
The example seems to be about some other warning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7d825e-82d7-7de3-780a-872ccd08cdef
* Version Independent ID: 5579c819-8e42-ab9a-2465-f2bf2b76f722
* Content: [Compiler Warning (level 1) C4172](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4172?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C4172)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4172.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4172.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by WebDancer69** [comment]
The example is correct. Since f is float "return f" creates a temporary double and returns a reference to it.

**Comment by corob-msft** [comment]
@WebDancer69 is correct (thanks for pointing that out!), and I'm guessing that's why this particular example was created. Most instances of the warning probably have a clearer cause.

**Comment by user2150** [comment]
The example proved to be more subtle than I was expecting. Thanks
