### ISSUE TITLE
Text does not follow the grammar

### ISSUE THREAD

**Issue by yuslepukhin** [MicrosoftDocs/cpp-docs#601]
How come  the grammar features underscore but the text features dashes all the way through?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22cca2d-19d9-e58f-03e4-4c6a573eccc9
* Version Independent ID: 5d9b058c-6cdf-4e61-dd06-ae6ed9b6f0e6
* Content: [Locale Names, Languages, and Country-Region Strings](https://docs.microsoft.com/en-us/cpp/c-runtime-library/locale-names-languages-and-country-region-strings?view=vs-2017)
* Content Source: [docs/c-runtime-library/locale-names-languages-and-country-region-strings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/locale-names-languages-and-country-region-strings.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yuslepukhin There are some formatting issues in this page. In the grammar, the underscore between the *language* and an optional *country-region* name is a literal. That is, you separate the language name from the region or country name by using an underscore. The underscore inside *code_page* is not a literal, although the period or dot at the beginning is a literal. The underscore in *code_page* is part of the parameter name, and should probably be a dash instead, like this:

*language*\[**\_**_country-region_\[.*code-page*]]

For example, if you wanted to specify a locale for Spanish (*language*) in the United States (*country-region*) that used the Latin 1 ANSI code page (*code-page*), it would be written `spanish_united states.1252` in long form, although `es-US` would probably be a better way to write it.

I'll see about fixing the formatting.

**Comment by yuslepukhin** [comment]
Not to belabor the point but the latest update to MS Studio takes en_US.* locale for C++ std::locale which is great because it is compatible with the way Linux works. Otherwise we’d be forced to have #ifdefs everywhere OR force the user to use different locale strings which is already an issue.

Dmitri

**Comment by corob-msft** [comment]
I could be wrong, but I believe a *locale-name* that uses an underscore (`en_US`) will fail in calls to CRT functions such as `setlocale`. When parsing the locale, the code first checks for a leading "LC_" and if it doesn't find one, it assumes an underscore must be a separator between a language and a country/region. Might be worth experimenting to find out.

**Comment by yuslepukhin** [comment]
One thing worth mentioning is that C and C++ locals are different.

Thanks,
Dmitri

Dmitri

________________________________

**Comment by corob-msft** [comment]
Updated but not closed at the time.
