### ISSUE TITLE
Also mention

### ISSUE THREAD

**Issue by olliechick** [MicrosoftDocs/cpp-docs#602]
It would be good to mention that this can occur if you don't have a forward declaration of a function that doesn't return an int.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d76d2fd-fd60-4fa2-59e4-73474d0a743e
* Version Independent ID: 33085254-0592-a16e-1b1d-40abaeeeb8aa
* Content: [Compiler Error C2371](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2371?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2371)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2371.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2371.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@olliechick apologies for late response. I'm not sure I understand your comment here. But we can add that if you can provide a code example that demonstrates.

**Comment by olliechick** [comment]
I think I meant something like this, although now (months later) I'm not sure.

```cpp
int main()
{
  float x = add(1.5, 2.5);
  printf("%f", x);
}

float add(float a, float b) { return a+b; }
```
