### ISSUE TITLE
Outdated information regarding console applications

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/cpp-docs#603]
UWP does support console apps on desktop/iot, so this seems kind of misleading. Can you clarify this document a bit more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d1de40-cedd-bf3f-e257-6338ba1a3e27
* Version Independent ID: 86d8877d-94b7-8402-195e-65e9cf6a260c
* Content: [UWP Apps, the Windows Runtime, and the C Run-Time](https://docs.microsoft.com/en-us/cpp/c-runtime-library/windows-store-apps-the-windows-runtime-and-the-c-run-time?view=vs-2017)
* Content Source: [docs/c-runtime-library/windows-store-apps-the-windows-runtime-and-the-c-run-time.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/windows-store-apps-the-windows-runtime-and-the-c-run-time.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Holo-Krzysztof fixed. thanks!
