### ISSUE TITLE
No more Goto's

### ISSUE THREAD

**Issue by NWoodruff** [MicrosoftDocs/cpp-docs#604]
// get rid of goto's
#include &lt;stdio.h&gt;
int main()
{
    int i, j;

    for ( i = 0; i &lt; 10; i++ )
    {
        printf_s( "Outer loop executing. i = %d\n", i );
        for ( j = 0; j &lt; 2; j++ )
        {
            printf_s( " Inner loop executing. j = %d\n", j );
            if ( i == 3 )
                i = 10; // some error occurred
        }
    }

    if ( I &lt; 11)
    // This message does not print:
        printf_s( "Loop exited. i = %d\n", i );
    else
        printf_s( "Jumped to stop. i = %d\n", i );
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35725608-b181-d529-4fe6-fcd63c8748e7
* Version Independent ID: 0cc1dc44-fff9-731e-9346-84ef6f52b668
* Content: [goto Statement (C++)](https://docs.microsoft.com/en-us/cpp/cpp/goto-statement-cpp?view=vs-2017)
* Content Source: [docs/cpp/goto-statement-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/goto-statement-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@NWoodruff The goto statement still exists in C++ and has its uses, although as you imply it should be avoided as a general rule. The example on this page can be written without goto, but since this topic is titled "goto Statement", it would not be helpful to have examples that don't show how to use it.
