### ISSUE TITLE
Contradiction

### ISSUE THREAD

**Issue by SamusArin** [MicrosoftDocs/cpp-docs#605]
Specifying variable and function types
C++ is a strongly typed language and it is also statically-typed; every object has a type and that type never changes

User-defined types
They do not have to be statically typed (the rule that an object's type never changes). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a22c8bac-8d8a-a9c8-4167-26f21f7e4a78
* Version Independent ID: cf220c62-e61f-c64e-8e68-075d9273e305
* Content: [C++ Type System (Modern C++)](https://docs.microsoft.com/en-us/cpp/cpp/cpp-type-system-modern-cpp?view=vs-2017)
* Content Source: [docs/cpp/cpp-type-system-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/cpp-type-system-modern-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@SamusArin Thanks! I have deleted the "User-defined types" bullet. It was very confusing and not well stated. It was referring to the concept of polymorphism and the ability to implicitly cast the type of a pointer-to-Derived object to a pointer-to-Base object. But even in that case both objects are statically typed. It's only the pointer that is dynamic.
