### ISSUE TITLE
the line is not clearly described.

### ISSUE THREAD

**Issue by sohagHub** [MicrosoftDocs/cpp-docs#606]
"When you encapsulate manual resource management in classes, use a class that does nothing else to manage each resource; otherwise, you might introduce leaks. "

I do not understand what the author wants to say here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3417e1d5-33ea-43b5-c676-1ef2604b5df7
* Version Independent ID: e9894c42-8485-74f6-fdf1-f5786d80dff8
* Content: [How to: Design for Exception Safety](https://docs.microsoft.com/en-us/cpp/cpp/how-to-design-for-exception-safety?view=vs-2017#keep-resource-classes-simple)
* Content Source: [docs/cpp/how-to-design-for-exception-safety.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/how-to-design-for-exception-safety.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@sohagHub Agreed this text was confusing. We have updated it, and the fix should appear in 2-3 days.
