### ISSUE TITLE
No longer used

### ISSUE THREAD

**Issue by mikeblas** [MicrosoftDocs/cpp-docs#607]
This might be a good place to point out that the SBR and BSC files are no longer used by the IDE. That information appears elsewhere in the documentation, but it's not a bad idea to make facts more discoverable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3eb6dd-250a-ae3f-1b6d-11a4a3cf11fc
* Version Independent ID: 8acc7e48-1a00-8ff1-0088-b7e5f3bdba94
* Content: [/FR, /Fr (Create .Sbr File)](https://docs.microsoft.com/en-us/cpp/build/reference/fr-fr-create-dot-sbr-file?view=vs-2017)
* Content Source: [docs/build/reference/fr-fr-create-dot-sbr-file.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fr-fr-create-dot-sbr-file.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@mikeblas thanks! I added the info to this file and a few others. Fix should appear in 1-2 days.
