### ISSUE TITLE
What is the error return?

### ISSUE THREAD

**Issue by yuslepukhin** [MicrosoftDocs/cpp-docs#608]
The doc states the return value 'If a valid locale and category are given`. How do I know if the function succeeded? The locale name is an argument coming from elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f166520-6634-c0f5-794d-f912c588c65f
* Version Independent ID: 3665b96c-13cf-2162-04bf-ef9fd9648418
* Content: [_create_locale, _wcreate_locale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/create-locale-wcreate-locale?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/create-locale-wcreate-locale.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/create-locale-wcreate-locale.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yuslepukhin A `_locale_t` is an opaque pointer type. On error, it's set to **nullptr** by calls to `_create_locale` or `_wcreate_locale`. You can make the usual tests for this result.
