### ISSUE TITLE
Allow passing debugger commands through CMakeSettings.json

### ISSUE THREAD

**Issue by sineang01** [MicrosoftDocs/cpp-docs#609]
At the moment doesn't seem to be a way to pass debugger arguments through **CMakeSettings.json**

In a classical Linux project built using "File|New Project|Cross Platform|Empty project (Linux)", the user can access the debugging options and pass additional debugger commands through the project "Properties|Debugging" window.
This option doesn't seem to be accessible in a CMake project opened natively using VS2017 and configured to build/run under Linux using CMakeSettings.json

It would be great if we could pass debugger commands with another configuration option in the json:
`"debuggerCommandArgs", ""`
so, for example, one could write...
`"debuggerCommandArgs", "handle SIGUSR1 nostop noprint"`
...and tell gdb to continue execution and ignore SIGUSR1 signal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@sineang01 Debugger commands are passed in launch.vs.json. See the "Configure CMake debugging sessions" in this topic.
