### ISSUE TITLE
Linux setup: Fedora - outdated instructions

### ISSUE THREAD

**Issue by AndrewAMD** [MicrosoftDocs/cpp-docs#612]
The command shown here does not work any more:
"sudo dnf install openssh-server g++ gdb gdbserver zip"

The problem is that some of the packages have been renamed. Here is the updated command:
"sudo dnf install openssh-server gcc-g++ gdb gdb-gdbserver zip"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0acbb6-5b9f-b28d-a7c8-196049ee561f
* Version Independent ID: c77469e1-7c9f-3dcd-c2e5-63c75f160e1a
* Content: [Install the C++ Linux workload in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload?view=vs-2017)
* Content Source: [docs/linux/download-install-and-setup-the-linux-development-workload.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/download-install-and-setup-the-linux-development-workload.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@AndrewAMD fixed. thanks! should appear in a day or so.
