### ISSUE TITLE
Instructions on exporting functions via DEF file are incomplete

### ISSUE THREAD

**Issue by oldnewthing** [MicrosoftDocs/cpp-docs#614]
> For non-MFC DLLs, you must create the .def file yourself and add it to your project.

These instructions are incomplete. In addition to adding the `.def` file to the project, you must go to Project, Properties, Linker, Input, Module Definition File, then enter the name of the `.def` file. Repeat for each configuration and platform, or do it all at once by selecting Configuration = All Configurations, and Platform = All Platforms..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a00ef41-1841-538c-6c85-d34107239627
* Version Independent ID: 8df53966-0e8e-824f-512c-4a568753bbcb
* Content: [Exporting from a DLL Using DEF Files](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=vs-2017)
* Content Source: [docs/build/exporting-from-a-dll-using-def-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exporting-from-a-dll-using-def-files.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@oldnewthing thanks! source doc has been updated and should be live by 1/11/2019.
