### ISSUE TITLE
Typo - "prevents the prevents"

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/cpp-docs#615]
In the Remarks section of make_unique

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec5d7ac7-0acc-63e3-9f87-cdfc4997c29b
* Version Independent ID: 03f518f7-2f57-7a0d-235e-136aa11a1364
* Content: [&lt;memory&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/memory-functions?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(MEMORY%2Fstd%3A%3Amake_unique)%3Bk(std%3A%3Amake_unique)%3Bk(make_unique)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017#make_unique)
* Content Source: [docs/standard-library/memory-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/memory-functions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@Dave-Lowndes thanks! Fixed and should appear in a day or so.
