### ISSUE TITLE
Reference to non-existing "count" argument

### ISSUE THREAD

**Issue by dragmz** [MicrosoftDocs/cpp-docs#620]
The document says "if count is zero" while there is no "count" argument. This should probably refer to "numberOfElements" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88716ce9-516c-c1d4-15c8-70824cf589b2
* Version Independent ID: cb3f43bf-77ba-f8d2-f1d9-c7c13529b9ec
* Content: [vsprintf_s, _vsprintf_s_l, vswprintf_s, _vswprintf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsprintf-s-vsprintf-s-l-vswprintf-s-vswprintf-s-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/vsprintf-s-vsprintf-s-l-vswprintf-s-vswprintf-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/vsprintf-s-vsprintf-s-l-vswprintf-s-vswprintf-s-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@dragmz fix should appear later today. Thanks!
