### ISSUE TITLE
CMakeSettings.json default 'buildRoot'

### ISSUE THREAD

**Issue by nl-n** [MicrosoftDocs/cpp-docs#621]
Surprised no-one has commented on this thus-far, but what is the reasoning behind that absurd default 'buildRoot'? 

Build artifacts should be placed in a dedicated subdirectory in the solution root, NOT as yet another fluff folder polluting the user directory.

Reminds of the whole Source\repos debacle that was decided upon. Is there any way at all to provide a global default for this? to at least override the built-in behaviour as a work-around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by sfreed141** [comment]
Hi @nl-n,
Currently there is not a way to provide a global default. The best way to request this feature is by suggesting it on [Developer Community](https://developercommunity.visualstudio.com). Thanks!

**Comment by mikeblome** [comment]
Closing as not a documentation issue.
