### ISSUE TITLE
excelente

### ISSUE THREAD

**Issue by EdgarJonathan** [MicrosoftDocs/cpp-docs#622]
excelente

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9524c1-6a81-93c1-ff4d-bc53f6903ffa
* Version Independent ID: 24871971-a1e9-807a-192e-6a2473289283
* Content: [Destructors (C++)](https://docs.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=vs-2017)
* Content Source: [docs/cpp/destructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/destructors-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@EdgarJonathan thanks!
