### ISSUE TITLE
fail if follow the instructions

### ISSUE THREAD

**Issue by xuxuedong** [MicrosoftDocs/cpp-docs#624]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E1696	无法打开 源 文件 "MathLibrary.h"	MathClient	C:\Users\xcblj\source\repos\MathClient\MathClient\MathClient.cpp	4	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2017)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by xuxuedong** [comment]
i use vs2017 community 15.9.4 + win10

**Comment by mikeblome** [comment]
@xuxuedong When you set the relative path for "Include Directories" in Project Properties, you have to make sure it goes from the folder with mathclient.cpp to the folder with Mathlibrary.h. That path might be different from what is shown in the topic. sorry for the confusion! I have updated the topic to make this more clear.
