### ISSUE TITLE
C2059 error is vague when enum/class element clashes with macro

### ISSUE THREAD

**Issue by mikeaich** [MicrosoftDocs/cpp-docs#638]
Error C2059 also appears in the following case:

```
#def FOO 0
enum class BAR {
    BAZ,
    FOO, /* error C2059 */
    QUX
};
```

**error C2059: syntax error: 'constant'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716bf099-c81d-233c-5c45-4bafb5ed4064
* Version Independent ID: 03f6ded3-3cca-0c59-7368-fa7bf0275ce3
* Content: [Compiler Error C2059](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2059?view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2059.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2059.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
This was apparently fixed awhile ago. Thanks @mikeaich !
