### ISSUE TITLE
linux cmake project , IntelliSense can't find the std header 

### ISSUE THREAD

**Issue by iclodq** [MicrosoftDocs/cpp-docs#641]
I read the "IntelliSense for remote headers (Visual Studio 2017 version 15.7 and later)" topic, do it.
But the problem is also exists. 
And I can start and attach the bin via VS, I don't know why the IntelliSense  don't find the std header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76faa92-c3bc-f26a-e4d6-24c037793ce3
* Version Independent ID: 0f60b926-5fc4-5013-1459-deb032f84826
* Content: [Configure a C++ Linux project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/configure-a-linux-project?view=vs-2017#remote_intellisense)
* Content Source: [docs/linux/configure-a-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/configure-a-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@iclodq The documention is correct here as far as I can tell. Please post your issue on https://developercommunity.visualstudio.com/spaces/8/index.html to get help from the product team or community.
