### ISSUE TITLE
strcpy_s to strncpy

### ISSUE THREAD

**Issue by jerviedog** [MicrosoftDocs/cpp-docs#643]
It seems that strcpy_s is not in c++ standard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9f5429-d3ce-3c6c-cd5a-3f7ea5389677
* Version Independent ID: 4c5e1cca-316f-8488-ab0c-110013b51d42
* Content: [References to Pointers](https://docs.microsoft.com/en-us/cpp/cpp/references-to-pointers?view=vs-2017)
* Content Source: [docs/cpp/references-to-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/references-to-pointers.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
The [strcpy_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s) function was originally a Microsoft extension to C and C++, one of the [security-enhanced CRT functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/security-enhanced-versions-of-crt-functions) created to make it more difficult to write code that overruns a buffer. These new functions were proposed to the ISO C and C++ standards committees, and some have been adopted in C11, including [strcpy_s](https://en.cppreference.com/w/c/string/byte/strcpy). (Unfortunately, some of the other functions were adopted with different signatures, or different names, so you need to be careful when moving code that uses them to other platforms.) Some of the C11 CRT was adopted by C++17, but I don't think these functions were included. I understand it's under consideration for C++20.
