### ISSUE TITLE
The famous "unresolved external symbol" linker error.

### ISSUE THREAD

**Issue by bssoyer** [MicrosoftDocs/cpp-docs#644]
This article explains very well what is meant by "unresolved external symbol.." linker error.
I would like to thank to the people who worked to make this article understandable and useful for the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3daf282f-f58d-a07c-9498-162d5f428e2a
* Version Independent ID: 20b5d713-059d-ba9e-359f-ad5c5d3f09e3
* Content: [Linker Tools Error LNK2001](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2001.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2001.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bssoyer Thanks!
