### ISSUE TITLE
MASM

### ISSUE THREAD

**Issue by billrrx** [MicrosoftDocs/cpp-docs#651]
Very nice summary ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d47dd35-d319-548d-db9f-6e1d754a4dc6
* Version Independent ID: f97c5b9d-b51c-860d-b644-11fb50f43884
* Content: [Microsoft Macro Assembler Reference](https://docs.microsoft.com/en-us/cpp/assembler/masm/microsoft-macro-assembler-reference?view=vs-2017)
* Content Source: [docs/assembler/masm/microsoft-macro-assembler-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/assembler/masm/microsoft-macro-assembler-reference.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@billrrx Thanks!
