### ISSUE TITLE
"vcredist_x64.exe installs the 32-bit and 64-bit libraries for x64 computers" is not correct.

### ISSUE THREAD

**Issue by K-Ubu** [MicrosoftDocs/cpp-docs#655]
The second paragraph says"vcredist_x64.exe installs the 32-bit and 64-bit libraries for x64 computers".
This sentence is not correct. vcredist_x64.exe installs ONLY 64-bit libraries for x64 computers.
If you execute a 32-bit application on an x64 computer,  you need to execute vcredist_x86.exe to install 32-bit libraries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4915eca-69ba-e784-96b2-d9774e9c0640
* Version Independent ID: 1c30cb1b-87a0-0b8a-16cc-83ecd37cf10a
* Content: [Determining Which DLLs to Redistribute](https://docs.microsoft.com/en-US/cpp/ide/determining-which-dlls-to-redistribute?view=vs-2017)
* Content Source: [docs/ide/determining-which-dlls-to-redistribute.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/determining-which-dlls-to-redistribute.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@K-Ubu thanks very much. Fix should be visible by July 15.
