### ISSUE TITLE
Bug in _read() function example

### ISSUE THREAD

**Issue by misuo** [MicrosoftDocs/cpp-docs#656]
Regarding the example given in documentation for [_read()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/read) function.

    int main( void )
    {
      ...
      unsigned int nbytes = 60000, bytesread;
    
      ...
      
      /* Read in input: */
      if( ( bytesread = _read( fh, buffer, nbytes ) ) <= 0 )
        perror( "Problem reading file" );
      ...
    }

Since `bytesread` is an `unsigned int` the if-statement checking for error value -1 will not work. So I believe the example is having a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1d4511-a144-242e-8c51-f3543246da51
* Version Independent ID: cde3b84b-c9fd-f246-b9e5-55bbceea6ebc
* Content: [_read](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/read?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/read.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/read.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by DaVieS007** [comment]
All MS examples having ton of bugs, actually cross-compiling into windows is a nightmare.

**Comment by corob-msft** [comment]
The sample code has been updated with variables of the correct types.

**Comment by misuo** [comment]
Shouldn't then the `printf( "Read %u bytes from file\n", bytesread );` be updated as well to using `%i`?

**Comment by corob-msft** [comment]
@misuo Probably. I'm partial to %d, myself.
