### ISSUE TITLE
Need clarity in explanation of floating-point type

### ISSUE THREAD

**Issue by b1nch3f** [MicrosoftDocs/cpp-docs#662]
Here, "You can omit either the digits before the decimal point (the integer portion of the value) or the digits after the decimal point (the fractional portion), but not both."

Does this part - "or the digits after the decimal point" mean a number can be like this - 45.

Following the "or" part in the above statement, there is no digit after the dot(.) following 45. Looks odd if i declare something like 
//float testFloat = 45.; \
instead of \
float testFloat = 45.0;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912b4e0a-4a70-e07b-130e-7a0b33955fcb
* Version Independent ID: 2235cd2d-77f5-1fb8-20b3-833828394c60
* Content: [C Floating-Point Constants](https://docs.microsoft.com/en-us/cpp/c-language/c-floating-point-constants?view=vs-2017)
* Content Source: [docs/c-language/c-floating-point-constants.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/c-floating-point-constants.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@b1nch3f So we're a bit behind on some of our follow-up. 

Yes, that sentence basically means you can't declare a floating point number just as a bare decimal point, or a decimal point followed by an exponent, but constants like 45. with no digits following, or 45.e25f, are perfectly legitimate.
