### ISSUE TITLE
Alternative solution (Windows)

### ISSUE THREAD

**Issue by Glitched-Manual** [MicrosoftDocs/cpp-docs#663]
add int argc, char* args[] or int arc, char** to main

example: int main(int argc, char* args[]) or int main(int arc, char**)

Linker -&gt; subsystem 
select console (command prompt still visible) or Windows (no command prompt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16cc003c-aa9a-56f8-560d-3b1063911055
* Version Independent ID: 1a3603c5-c5c0-0fad-1ba3-53fe82798fc6
* Content: [Linker Tools Error LNK1561](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1561?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1561)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1561.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1561.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Glitched-Manual We don't list every possible signature here, but we do mention one example. The subsystem option may control whether we look for a `main` or `wmain`, or for a `WinMain`, or `wWinMain` entry point. If the linker doesn't find a subsystem value, it should give a different warning, such as LNK1221, first. I'm not seeing something that needs to be addressed here. If you disagree, feel free to reopen the issue and explain what you have in mind.
