### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kuangdongwei** [MicrosoftDocs/cpp-docs#667]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b33927-964a-d2e3-902a-9f23f944800f
* Version Independent ID: 06d063cb-b6e3-896b-6e7d-7102c1a41f4c
* Content: [Compiler Error C2065](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2065?view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2065.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2065.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kuangdongwei There's no actionable information here.
