### ISSUE TITLE
Why does a second _getch() not block?

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/cpp-docs#670]
do
   {
      ch = _getch();
      ch = toupper( ch );
   } while( ch != 'Y' );

   _putch( ch );
   _putch( '\r' );    // Carriage return
   _putch( '\n' );    // Line feed
   _getch();

I want to pause and hence put the second _getch() however it is ineffective!! I put a cin that paused it but that also never continued further just hung. 
   do
   {
      ch = _getch();
      ch = toupper( ch );
   } while( ch != 'Y' );

   _putch( ch );
   _putch( '\r' );    // Carriage return
   _putch( '\n' );    // Line feed
	cout << "Type any key to continue scanning";
	cin >> ch;
	printf("Done\n");
In this case typing any key did not get me out and Done did not get printed. Running in debug mode CTRL-C got me out of the cin!! Totally confused please help. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c56cd0-6b04-3472-ce56-fe749a238b70
* Version Independent ID: 5e6e3834-0c3c-0677-9dc2-9e7a96d31f0c
* Content: [_getch, _getwch](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/getch-getwch.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/getch-getwch.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@agvardha Normally, `_getch()` does block, except for certain control keys. `std::cin` waits for a carriage return. This doesn't look like a documentation issue, so I'm closing it. Just a note, there was a bug affecting input functions in some versions of the UCRT that shipped with Windows for a while, so make sure your copy of the UCRT is up-to-date by checking for and applying any Windows updates, and use the Visual Studio Installer to install the latest Windows SDK available.
