### ISSUE TITLE
const global linkage?

### ISSUE THREAD

**Issue by lijiansong** [MicrosoftDocs/cpp-docs#673]
I have 5 files:
a.h:
```
extern const int a;
```
a.cpp:
```
#include "a.h"
const int a = 1;
```
b.h:
```
extern const int a;
extern const int b;
```

b.cpp:
```
#include "b.h"
const int b = a + 1;
```

main.cpp:
```
#include <stdio.h>
#include "a.h"
#include "b.h"
int c = a + 1;
int d = b + 1;
int main() {
  printf("c: %d\n", c);
  printf("d: %d\n", d);
  return 0;
}
```
I compile them with the following order:
```
gcc -c *.cpp
gcc a.o b.o main.o -o after
gcc main.o a.o b.o -o before
```
When I run `after` and `before`:
./after
c: 2
d: 3
./before
c: 2
d: 1
Someone else can explain the linkage of these globals? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d22551-f6be-bbd0-98e6-805b8875c07e
* Version Independent ID: c94795a2-814b-0c05-d2df-5ba3bc0425c7
* Content: [Programs and Linkage  (C++)](https://docs.microsoft.com/en-us/cpp/cpp/program-and-linkage-cpp?view=vs-2017)
* Content Source: [docs/cpp/program-and-linkage-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/program-and-linkage-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@lijiansong I suggest that you ask this question on StackOverflow and/or check out the gcc documentation on const linkage. Since this is not really an error in our documentation I am closing this as not a doc bug.
