### ISSUE TITLE
Question: Is there a walkthrough "creating a DLL in C++ but consuming it in C#"?

### ISSUE THREAD

**Issue by sadqiang** [MicrosoftDocs/cpp-docs#676]
Hi guys, 

I am interested in learning how to create a DLL in C++ but consuming it in C# (rather than C++). Is there such a tutorial that is officially written by Microsoft team?

**Comment by mikeblome** [comment]
If the code is only to be consumed by C#, then make sure you have the C++/CLI support component installed (if using VS2017) , and under File > New > Project find Visual C++ > CLR > CLR Class Library.  I thought we had a tutorial on how to create a C++/CLI DLL but I can't find it so perhaps that's something we should add to the documentation.

**Comment by mikeblome** [comment]
Sorry for delayed response. @sadqiang does this page have the info you were/are looking for? https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2017

**Comment by sadqiang** [comment]
@mikeblome Thank you for informing the links. It is very helpful. 👍
