### ISSUE TITLE
Error: cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'

### ISSUE THREAD

**Issue by JamesKIMSTI** [MicrosoftDocs/cpp-docs#679]
OS: win10 64bit Python 3.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a49966-cfcd-4d5f-3a3c-fa74d92b151c
* Version Independent ID: 3cfc6236-941e-c3ad-09c9-e7a9b4a18b09
* Content: [Command-Line Error D8021](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/command-line-error-d8021?view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/command-line-error-d8021.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/command-line-error-d8021.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JamesKIMSTI It looks like you have a project that's using Clang or gcc switches. Unsurprisingly, MSVC doesn't understand those. If this comes from a build script for a library or source code you've imported from a different platform, you'll need to go through and translate the [compiler options](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options?view=vs-2017) to ones MSVC understands. This isn't a documentation issue, so I'm closing it.
