### ISSUE TITLE
syntax

### ISSUE THREAD

**Issue by evilteach** [MicrosoftDocs/cpp-docs#698]
The syntax entry above has an extra closing parenthesis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7caa1335-25b5-dbc1-8a3c-b7e201eddd50
* Version Independent ID: f5f3e4d8-3865-8a56-b87b-7c0b5cb35212
* Content: [detect_mismatch](https://docs.microsoft.com/en-us/cpp/preprocessor/detect-mismatch?view=vs-2017)
* Content Source: [docs/preprocessor/detect-mismatch.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/detect-mismatch.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
thanks @evilteach ! It looks like this is fixed now.
