### ISSUE TITLE
HString/HStringReference missing GetRawBuffer methods

### ISSUE THREAD

**Issue by nkronlage** [MicrosoftDocs/cpp-docs#706]
The pages https://docs.microsoft.com/en-us/cpp/windows/hstring-class and https://docs.microsoft.com/en-us/cpp/windows/hstringreference-class are missing the GetRawBuffer() methods:

    const wchar_t* GetRawBuffer(_Out_opt_ unsigned int* length) const
    {
        return ::WindowsGetStringRawBuffer(hstr_, length);
    }

There may be others missing, but I didn't check.

**Comment by mikeblome** [comment]
@nkronlage fixed now (as of July 15). thanks!
