### ISSUE TITLE
False positive when assert() references parameter

### ISSUE THREAD

**Issue by mcandre** [MicrosoftDocs/cpp-docs#707]
This C4100 warning triggers a spurious message when a parameter is used, but only within an assert(). This happens even when _DEBUG is defined.

As a workaround, I am changing some of my void assertion procedures to returning boolean expressions. But it would be better if this warning did not trigger for this case. It's misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff5f8e3-be4c-3af7-cb5d-9a0c0017a222
* Version Independent ID: 5f78d743-c527-95e8-367b-0eb0ba811ec5
* Content: [Compiler Warning (level 4) C4100](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4100?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4100.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4100.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mcandre You can get a C4100 warning for a parameter used only in an [assert](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-macro-assert-wassert) macro if you have defined **NDEBUG**.  Only the [_ASSERT, _ASSERTE, and _ASSERT_EXPR](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-asserte-assert-expr-macros) macros are controlled by the **_DEBUG** macro.

This doesn't seem like you think it's a documentation issue so much as a product issue, and therefore, I'm closing it. If you have an issue with the product or libraries, the best place to bring it up is the [Developer Community C++ forum](https://developercommunity.visualstudio.com/spaces/62/index.html). For issues in features that are widely used, odds are at least fair that someone else has run into the issue and reported it already, so it pays to search first. If you don't see your particular issue, we have some instructions on how to write a bug report that's easy for the developers to reproduce and fix in [How to report a problem with the Visual C++ toolset or documentation](https://docs.microsoft.com/en-us/cpp/how-to-report-a-problem-with-the-visual-cpp-toolset). Best of luck.
