### ISSUE TITLE
Find within a data structure based array

### ISSUE THREAD

**Issue by haephrati** [MicrosoftDocs/cpp-docs#708]
Can the Find method be used to find specific data that is part of a data structure when the array contains elements of that structure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8134a2a-bd1c-2fae-fdb2-f3268bd20c44
* Version Independent ID: 6b316148-edfc-50c5-20c6-d2a91721b03a
* Content: [CSimpleArray Class](https://docs.microsoft.com/en-us/cpp/atl/reference/csimplearray-class?view=vs-2017#find)
* Content Source: [docs/atl/reference/csimplearray-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/csimplearray-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@haephrati  Apologies for late response.  Yes, you can use Find to do that when you define a CSimpleArrayHelper class that compares each element in the array to an element that has the values you are looking for.  See the remarks for the class at the top of the topic. Also, StackOverflow is a great place to ask questions like this.
