### ISSUE TITLE
Linking error after folowing the steps!

### ISSUE THREAD

**Issue by saquibntt** [MicrosoftDocs/cpp-docs#709]
1&gt;------ Build started: Project: MthClient, Configuration: Debug Win32 ------
1&gt;MthClient.obj : error LNK2019: unresolved external symbol __imp__fibonacci_init referenced in function _main
1&gt;MthClient.obj : error LNK2019: unresolved external symbol __imp__fibonacci_next referenced in function _main
1&gt;MthClient.obj : error LNK2019: unresolved external symbol __imp__fibonacci_current referenced in function _main
1&gt;MthClient.obj : error LNK2019: unresolved external symbol __imp__fibonacci_index referenced in function _main
1&gt;D:\workspace\MthClient\Debug\MthClient.exe : fatal error LNK1120: 4 unresolved externals
1&gt;Done building project "MthClient.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2017)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Sirmyself** [comment]
Try to look for the LIB and DLL file in your solution folder instead of the specific project folder. My solution was building everything in a "debug" folder at the root of the solution.

**Comment by mikeblome** [comment]
Clarified that relative paths are different for VS2017 and VS2019. Hopefully that will help folks avoid this problem in the future.
