### ISSUE TITLE
Calculating the stack offset for _UNWIND_CODE operations

### ISSUE THREAD

**Issue by sidhant-gupta-004** [MicrosoftDocs/cpp-docs#710]
Hello. How do we calculate the stack for `UWOP_SAVE_NONVOL` exactly? What does scaled-by-8 mean? Do we simply have to multiply the value in the next unwind code slot by 8? Or do we have to do different arithmetic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2017#unwind-data-for-exception-handling-debugger-support)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sidhant-gupta-004 Yes, scaled by 8 means multiply the info by 8 for the relative stack offset.
