### ISSUE TITLE
Exception Handler

### ISSUE THREAD

**Issue by sidhant-gupta-004** [MicrosoftDocs/cpp-docs#711]
Is the Exception Handler field deprecated? Because I cannot see a valid address (for `ExceptionHandler`) when an _UNWIND_CODE flag is 0x03. Thanks. :)
P.S.: I am analysing a Windows dump which is where I made this observation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cf8590-8a4f-91c3-8fa4-b225c247eb9d
* Version Independent ID: 062a75f5-f5c8-89db-4dec-1c3d0095f5c2
* Content: [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2017#unwind-data-for-exception-handling-debugger-support)
* Content Source: [docs/build/exception-handling-x64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/exception-handling-x64.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sidhant-gupta-004 The exception handler field is not deprecated.
