### ISSUE TITLE
Incomplete specification

### ISSUE THREAD

**Issue by V0d01ey** [MicrosoftDocs/cpp-docs#714]
Why would one write mentioned line of code?
> It is not sufficient to say
>```cpp
>const FlagType;      // Incomplete specification
>```
>because the FlagType is taken to be part of the type, not **an identifier that is being redeclared**.

Can this line somehow redeclare an identifier in some cases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f768e672-bb01-170e-3d3c-d9989cf09c8b
* Version Independent ID: 1d3c06ec-26b1-0d89-9cc7-327ac1133dd8
* Content: [Aliases and typedefs (C++)](https://docs.microsoft.com/en-us/cpp/cpp/aliases-and-typedefs-cpp?view=vs-2017)
* Content Source: [docs/cpp/aliases-and-typedefs-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/aliases-and-typedefs-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@V0d01ey You wouldn't write that, any more than you'd write

`const char;`

and expect the compiler to accept it. The following example, of 

`int;`

is the same kind of mistake. It's never an acceptable declaration. Only unions and (since C++11) structs can be declared anonymously.
