### ISSUE TITLE
Please fix some typo/errors

### ISSUE THREAD

**Issue by tangogu** [MicrosoftDocs/cpp-docs#718]
Example 3, the total size should be 12 bytes instead of 22.
Example 4, the total size should be 16 instead of 8.
Detail should be:
    short s;      // +8; size = 2 bytes
    long l;       // +12; size = 4 bytes
Instead of:
    short s;      // +0; size = 2 bytes
    long l;       // +0; size = 4 bytes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7052f5eb-e592-2920-e58a-30a6d4bbc3b8
* Version Independent ID: dfe35b76-1b05-7914-70a8-e35e17ef6624
* Content: [x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions?view=vs-2017)
* Content Source: [docs/build/x64-software-conventions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/x64-software-conventions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tangogu Thanks for bringing this up. It appears I fixed the typo in example 3 a couple of months ago, and forgot to update this issue. Example 4 is a union, not a struct, so the existing offsets are correct.
