### ISSUE TITLE
Poorly-formed markup in modeless dialog box section

### ISSUE THREAD

**Issue by DaManDOH** [MicrosoftDocs/cpp-docs#721]
The code snippets for the "To display a modeless dialog box" section (link https://docs.microsoft.com/en-us/cpp/mfc/example-displaying-a-dialog-box-via-a-menu-command?view=vs-2017#to-display-a-modeless-dialog-box) are poorly-formed, displaying the markup in the form fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58cc932-0f2a-c9b4-159d-6a932bb3b86f
* Version Independent ID: 60d3964b-e62f-366e-a8b6-3940ec2a2dcf
* Content: [Example: Displaying a Dialog Box via a Menu Command](https://docs.microsoft.com/en-us/cpp/mfc/example-displaying-a-dialog-box-via-a-menu-command?view=vs-2017#to-display-a-modeless-dialog-box)
* Content Source: [docs/mfc/example-displaying-a-dialog-box-via-a-menu-command.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/example-displaying-a-dialog-box-via-a-menu-command.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@DaManDOH thanks! this is fixed and should appear in a day or so.
