### ISSUE TITLE
The need of a default installation variable list

### ISSUE THREAD

**Issue by kevincrans** [MicrosoftDocs/cpp-docs#729]
It would be handy if there was a list of all C++ and C# default installation environment variables, so you don't have to use a custom command prompt if you enter some argument or add them to windows, like in javac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4649da-9af5-2b91-e05b-ac349a2b3542
* Version Independent ID: 8fa1e1dc-81bc-bc60-1c9e-d914a040575e
* Content: [LINK Environment Variables](https://docs.microsoft.com/en-us/cpp/build/reference/link-environment-variables?view=vs-2017)
* Content Source: [docs/build/reference/link-environment-variables.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/link-environment-variables.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kevincrans Given the level of trouble and misunderstanding seen in our feedback, our documentation always says to use the pre-generated developer command prompts in preference to setting the variables yourself. However, the developer command prompts just use command files to set these variables, and there's no reason you can't call the same ones in your own command prompts to set the variables up, as long as you call the command files with the right parameters for your preferred configuration.

The reason we don't just publish a list of the environment variables' default values is that there aren't any. These values depend on multiple parameters: where you installed the tools, which tool options you installed, what the host machine architecture is, what the build target architecture is, and probably another one or two I've forgotten. Importantly, they can change if you use the installer to add or remove various components, or update your Windows SDK. The batch files that set the variables up call other batch files that call still more batch files that may be added or removed by the installer to match what's on your machine. If you just used some SET commands to do the job, you might miss something.

It's a nice idea; it just doesn't work that way in practice.

**Comment by kevincrans** [comment]
Thank you for your response, I understand now, Sorry for the late reply.
