### ISSUE TITLE
Document does not describe expansion in any manner and is unhelpful if you can't find a user guide for it

### ISSUE THREAD

**Issue by chuggafan** [MicrosoftDocs/cpp-docs#733]
So I went down the "I'm looking for documentation on random things because I found it interesting" route and I noticed the page for Expanding Wildcard Arguments, despite sounding like it'd describe how it is expanded, it does not, saying:

>The wildcards are expanded in the same manner as operating system commands. (See your operating system user's guide if you are unfamiliar with wildcards.)

This presents a problem for me: I can't find any user's guide that has this information nor can I find anything about exactly how the wildcards are expanded, and this is strange, considering I went into the CRT, did some digging, and discovered that the underlying call's docs don't even have this documentation for _findfirst, FindFirstA, FindFirstExA, etc. so it's strange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1976bb69-69e2-1e6a-0158-d8cfaf007007
* Version Independent ID: 9ba07fde-151f-e461-06cb-1575c476f7e2
* Content: [Expanding Wildcard Arguments](https://docs.microsoft.com/en-us/cpp/c-language/expanding-wildcard-arguments?view=vs-2017)
* Content Source: [docs/c-language/expanding-wildcard-arguments.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/expanding-wildcard-arguments.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@chuggafan You got me curious, too, so I did some looking. The reason we don't (and won't) describe wildcard expansion behavior is that we defer to the behavior of the operating system, so it's not for us to describe how wildcard expansion actually works. The behavior might (and does) change (slightly) depending on the Windows version or file system in use, for example. You're right that the documentation for the calls used by the `setargv`/`wsetargv `versions that do wildcard expansion (basically, `FindFirstFileEx`, `FindNextFile`) also do some handwaving when it comes to how it works. I couldn't find anywhere official to point you for the rules, so much as I'd like to, I can't stick a link into this document, either. There's some interesting discussion in The Old New Thing blog in [How did wildcards work in MS-DOS?](https://blogs.msdn.microsoft.com/oldnewthing/20071217-00/?p=24143) that gives a hint to the complexity of the current search behavior.  That's about all the info I have.

**Comment by chuggafan** [comment]
In place of that then, can you bring up with the relevant members internally for that kind of thing to describe how the Operating System itself does it's wildcard expansion or give the defaults/changes for the windows version in some kind of documentation? It's a really interesting question that I'm sure would be great for me to dig into but I also don't have that kind of time to discover on such a large scale...
