### ISSUE TITLE
Incorrect property name

### ISSUE THREAD

**Issue by xiangfan-ms** [MicrosoftDocs/cpp-docs#734]
The name of the property in VS is 'Forced Include File', not 'Force Includes'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f2378f-4cf7-ee3d-6593-3abc347c990b
* Version Independent ID: 00e44ac5-a02d-8dae-1534-0e51643e609a
* Content: [/FI (Name Forced Include File)](https://docs.microsoft.com/en-us/cpp/build/reference/fi-name-forced-include-file?view=vs-2017)
* Content Source: [docs/build/reference/fi-name-forced-include-file.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fi-name-forced-include-file.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@xiangfan-ms thanks! fix should appear in a day or so.
