### ISSUE TITLE
Step 3 above is worded poorly.

### ISSUE THREAD

**Issue by BrentRector** [MicrosoftDocs/cpp-docs#742]
As the /utf-8 option itself specifies the preferred encoding, there is no additional information to specify. Therefore the current step 3 instructions which say "*and* specify your preferred encoding" are misleading. It would be better to say:

In Advanced Options, add the /utf-8 option to specify your preferred encoding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95cef197-b80b-d567-7650-b6b5f8741766
* Version Independent ID: dc4b1099-c2aa-5a85-14c7-9456ba39233b
* Content: [/utf-8 (Set Source and Executable character sets to UTF-8)](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2017)
* Content Source: [docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@BrentRector fixed. thanks! should appear in a day or so.
