### ISSUE TITLE
Item 3 is poorly worded (part 2)

### ISSUE THREAD

**Issue by BrentRector** [MicrosoftDocs/cpp-docs#743]
Additionally, there is no "Advanced Options" section in the Configuration Properties, C/C++, Command Line folder. The appropriate section is named "Additional Options".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95cef197-b80b-d567-7650-b6b5f8741766
* Version Independent ID: dc4b1099-c2aa-5a85-14c7-9456ba39233b
* Content: [/utf-8 (Set Source and Executable character sets to UTF-8)](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2017)
* Content Source: [docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@BrentRector got it thanks!
