### ISSUE TITLE
ArgumentNullException should be documented

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/cpp-docs#744]
In the current implementation, this method will throw an ArgumentNullException if the input parameter is null:

```
  inline std::string marshal_as(System::String^ const & _from_obj)
  {
	if (_from_obj == nullptr)
	{
		throw gcnew System::ArgumentNullException(_EXCEPTION_NULLPTR);
	}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60dc5f7d-b274-fa12-acd2-4a83b35bea42
* Version Independent ID: dcaa921b-47a0-75c4-9e8b-6e8cf494ed39
* Content: [marshal_as](https://docs.microsoft.com/en-us/cpp/dotnet/marshal-as?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(MARSHAL_CPPSTD%2Fmsclr%3A%3Ainterop%3A%3Amarshal_as);k(msclr%3A%3Ainterop%3A%3Amarshal_as);k(marshal_as);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-C%2B%2B);k(TargetOS-Windows);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/dotnet/marshal-as.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/marshal-as.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Thieum thanks! You are correct. Fix should appear by Monday July 15.
