### ISSUE TITLE
Sub blocks don't seem to work

### ISSUE THREAD

**Issue by timluther** [MicrosoftDocs/cpp-docs#747]
Hi,
  I'm using this function in this way:

_malloc_dbg(n, _CLIENT_BLOCK | (MY_SUB_BLOCK &lt;&lt; 16),__FILE__, __LINE__);

but when I do this, I get the following error:

---------------------------
Debug Assertion Failed!

Program: E:\prog\anthracite\bin\UnityDebug-x64\AnthracitePlayer.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 972

Expression: header-&gt;_block_use == block_use || header-&gt;_block_use == _CRT_BLOCK && block_use == _NORMAL_BLOCK

I don't get this if I omit the top 16 bytes, using my sub type specifier.
This suggests to me that perhaps you guys aren't masking the low 16bits of this dword when performing the '_block_use' checks? I don't like to assume the windows libraries are incorrect (because it's usually something I've done) but I can't see the problem with my code here: I think I'm using subblocks as the header file macros suggest I should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9275561f-980e-4d20-d986-2ffcab30beb5
* Version Independent ID: 6c87c5fc-e2f8-58ca-4038-cfd47f73846f
* Content: [_malloc_dbg](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc-dbg?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/malloc-dbg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/malloc-dbg.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@timluther  Since the assert is in the `free_dbg_nolock` function, I'd assume it was hit because you weren't passing the correct flags to `_free_dbg`. Since you found and presumably fixed that problem, are the debug heap functions working as described? Reopen if an issue remains to be documented.
