### ISSUE TITLE
How to specify command-line ("run") arguments for an executable?

### ISSUE THREAD

**Issue by patrikhuber** [MicrosoftDocs/cpp-docs#750]
How can I specify command-line ("run") arguments for an executable (i.e. cmake target)? I would have expected to find this here, but even after spending more than 10 minutes of googling and reading, I still haven't found any documentation of how to do it. This should be documented much better.

I am specifically looking for how to do it in VS 2019 Preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by sfreed141** [comment]
Hi Patrik,
You'll need to use a [launch.vs.json](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2017#configure-debugging-with-launchvsjson) file to specify command line arguments. In the configuration you can add the arguments using the "args" field.

The "project" field in launch.vs.json is the path to the executable you want to launch/debug. Unfortunately the ${workspaceHash} and ${name} macros in CMakeSettings.json will not evaluate in launch.vs.json, but you can still specify an absolute path (or a path relative to the workspace, using ${workspaceRoot}).

**Comment by sfreed141** [comment]
I found a better way to accomplish this as described [here](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017#configure-cmake-debugging-sessions). Try setting "project" to "CMakeLists.txt" and "projectTarget" to "mydemo.exe" (or whatever the name of your CMake target is). Another way to do this is to switch the Solution Explorer to Targets View (using the drop down next to the home icon) and then right-click and launch "Debug and Launch Settings" on the target you want to launch.

The fact that the CMake targets are not shown in the popup when you do "Debug and Launch Settings" from CMakeLists.txt is a bug. Thanks for helping find it!

**Comment by patrikhuber** [comment]
> Another way to do this is to switch the Solution Explorer to Targets View (using the drop down next to the home icon) and then right-click and launch "Debug and Launch Settings" on the target you want to launch.

Nice! This worked, and I think it's the simplest way to do it. This automatically adds an entry to `launch.vs.json` that actually works, and looks like this (after I've added the `"args": ...` part):

```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "default",
      "project": "CMakeLists.txt",
      "projectTarget": "mydemo.exe (examples\\mydemo.exe)",
      "name": "mydemo.exe (examples\\mydemo.exe)",
      "args": ["-a test"]
    }
  ]
}
```
Also if I change the `name` now, the updated/added item now successfully appears in the "Select Startup Item" dropdown.

> The fact that the CMake targets are not shown in the popup when you do "Debug and Launch Settings" from CMakeLists.txt is a bug. Thanks for helping find it!

Aah - cool, you're welcome :-)

Thank you very much for your help, that's brilliant. Feel free to close this issue. I'm leaving it open if you like to make a note to perhaps improve the documentation in various places (for VS 2019 at least). Or maybe some hint somewhere directly in the VS 2019 GUI. Perhaps a menu entry in the "Build" or "Debug" menus or in the "Select Startup Item" dropdown? This really wasn't obvious to me and I didn't manage to find the right docs pages when googling.

Thank you again!

**Comment by mikeblome** [comment]
I have updated the documentation to mention using "Targets View". @patrikhuber thanks for the feedback!
