### ISSUE TITLE
mistake in code example

### ISSUE THREAD

**Issue by tingl** [MicrosoftDocs/cpp-docs#751]
in the last c++ code example about logarithm, should it be:
logs[idx] = concurrency::fast_math::log10(**numbers**[idx]);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58e07cc-2b1b-668a-5d9d-73afd80ce1c6
* Version Independent ID: 2b3cbb85-9f6c-2ef2-285a-5af0dc64e31d
* Content: [C++ AMP Overview](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-overview?view=vs-2017)
* Content Source: [docs/parallel/amp/cpp-amp-overview.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/cpp-amp-overview.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@tingl thanks! This is fixed now. Should be visible in 1-2 days.
