### ISSUE TITLE
STA?

### ISSUE THREAD

**Issue by EricDavies** [MicrosoftDocs/cpp-docs#754]
You can't just have a page with some strange TLA  (like STA) on it without point people towards its definition. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2dd4014-f009-dd9c-3d39-5de0897871dd
* Version Independent ID: 10782062-6be2-8aff-1d87-9e8430f69234
* Content: [task Class (Concurrency Runtime)](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/task-class?view=vs-2017)
* Content Source: [docs/parallel/concrt/reference/task-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/task-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@EricDavies yeah sorry about that. I'll fix it. It means "single-threaded apartment" which you can search for precise documentation. If you think "main thread for the user interface" that's the general idea.

**Comment by mikeblome** [comment]
fix should appear by 03-20.
