### ISSUE TITLE
Ignore these libraries lists should be separated by semicolons

### ISSUE THREAD

**Issue by sschilz** [MicrosoftDocs/cpp-docs#755]
If you copy/paste the list of libraries to ignore into Visual Studio 2017, it does not work because the list in VS2017 is separated by semicolons ( ; ) - The lists here are separated by commas...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126acce3-7235-e676-89fa-77f16e2e6dc0
* Version Independent ID: 4a45039e-0d7c-9ec6-31b9-00b75209c332
* Content: [Linker Tools Warning LNK4098](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4098?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK4098)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4098.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4098.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sschilz Sorry it's taken a while to get back to you. I see where you're coming from. We probably didn't consider that someone would just copy and paste the list of libraries when the table was written, though in retrospect that's an obvious thing to do. I'll look into that.

**Comment by corob-msft** [comment]
The changes were part of a larger effort that updated the doc to remove references to the obsolete single-threaded libraries. They should show up online tomorrow.

**Comment by sschilz** [comment]
Awesome! Nice to see feedback follow through!  Thank you so much.
