### ISSUE TITLE
Migrate an existing Win32 DLL for UWP

### ISSUE THREAD

**Issue by mhandb** [MicrosoftDocs/cpp-docs#760]
The step 2 is saying to include `winapifamily.h` and set the macro `WINAPI_FAMILY=WINAPI_PARTITION_APP`.
Should it be `WINAPI_FAMILY=WINAPI_FAMILY_APP` instead ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f4e027-c6e8-395e-8cca-2392382aeeef
* Version Independent ID: dce12694-d381-b696-0109-5bf560b561a2
* Content: [DLLs (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/dlls-c-cx?view=vs-2017)
* Content Source: [docs/cppcx/dlls-c-cx.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/dlls-c-cx.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@mhandb apologies for delayed response. The WINAPI_FAMILY_APP macro is deprecated. The WINAPI_PARTITION_APP is a better choice here.

**Comment by mhandb** [comment]
Are you sure because defining 
`WINAPI_FAMILY=WINAPI_PARTITION_APP` as told in the documentation leads to this error
`c:\program files (x86)\windows kits\10\include\10.0.18362.0\shared\winapifamily.h(146): fatal error C1189: #error:  Unknown WINAPI_FAMILY value. Was it defined in terms of a WINAPI_PARTITION_* value?`

But 
`WINAPI_FAMILY=WINAPI_PARTITION_APP` has the expected effect.
