### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by goodandrewsoft** [MicrosoftDocs/cpp-docs#766]
example please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48873de2-1c54-2d8e-881c-065195a675c7
* Version Independent ID: 6c63bb99-60be-aa6f-7815-0779ad9a9183
* Content: [/link (Pass Options to Linker)](https://docs.microsoft.com/en-us/cpp/build/reference/link-pass-options-to-linker?view=vs-2017)
* Content Source: [docs/build/reference/link-pass-options-to-linker.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/link-pass-options-to-linker.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@goodandrewsoft Do you mean something like `cl /W4 /EHsc hello.cpp there.obj /link /VERSION:3.14`?

**Comment by corob-msft** [comment]
That example should be visible in the topic sometime tomorrow.
