### ISSUE TITLE
Inline friend

### ISSUE THREAD

**Issue by lunidev** [MicrosoftDocs/cpp-docs#771]
"Friend functions defined inside class declarations are not considered in the scope of the enclosing class; they are in file scope."

Is above correct ? 

//declaration in tip1.h
class tip1
{
....
public:
	static  float   basictax;
	 	
	.....................
	static float test1(float t) {
		return addtotaxpu(t);
	}
};

// Usage: in main.cpp

void main(){
tip1 testFriends;
testFriends.test();

}
Error	LNK2001	unresolved external symbol "public: static float tip1::basictax" (?basictax@tip1@@2MA)	 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52ffaf97-4abe-683a-cb75-78a33bdb7bcf
* Version Independent ID: f5ef91c6-d8f7-75a8-92ec-3fd46b4cfe99
* Content: [friend (C++)](https://docs.microsoft.com/en-us/cpp/cpp/friend-cpp?view=vs-2017)
* Content Source: [docs/cpp/friend-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/friend-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@lunidev you are correct. topic fix should appear by JUly 15.
