### ISSUE TITLE
...

### ISSUE THREAD

**Issue by tomaszek1989** [MicrosoftDocs/cpp-docs#772]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6c6f6a-188a-7110-962c-89ff8e00eee9
* Version Independent ID: ffa45840-7fbb-b9c2-0dd9-43eb95b760cc
* Content: [Install C++ support in Visual Studio 2017](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2017)
* Content Source: [docs/build/vscpp-step-0-installation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-0-installation.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Closed, no actionable info.
