### ISSUE TITLE
get mode?

### ISSUE THREAD

**Issue by goodandrewsoft** [MicrosoftDocs/cpp-docs#773]
If exist _setmode, how get mode ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6563ec7-aa91-8204-c1a1-7096037437f1
* Version Independent ID: a68fce2d-00a7-d6d2-c8b2-21f418262eea
* Content: [_setmode](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/setmode.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/setmode.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@goodandrewsoft Streams are opened in whatever mode you specify, or the default mode reported by `_fmode`. The `stdin`, `stdout`, and `stderr` streams are opened in text mode. Thereafter, the return result of `_setmode` tells you what the mode was before you set it. The file stream default translation mode can be read using `_get_mode`. See [Text and Binary Mode File I/O](https://docs.microsoft.com/en-us/cpp/c-runtime-library/text-and-binary-mode-file-i-o?) for more info.
