### ISSUE TITLE
static member - ERROR already defined in

### ISSUE THREAD

**Issue by lunidev** [MicrosoftDocs/cpp-docs#774]
Using your sample, I get 
Error	LNK2005	"public: static long BufferedOutput::bytecount" (?bytecount@BufferedOutput@@2JA) already defined in  .....
 Error	LNK1169	one or more multiply defined symbols found	  	...
FIXED by adding
__declspec(selectany)  so you should  modify your sample
__declspec(selectany)   long BufferedOutput::bytecount = 0;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4e180f-447c-308b-0e2d-dd1491d4758c
* Version Independent ID: 1929c1c6-d6eb-0a97-52ee-3d123cc5a129
* Content: [Static Members (C++)](https://docs.microsoft.com/en-us/cpp/cpp/static-members-cpp?view=vs-2017)
* Content Source: [docs/cpp/static-members-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/static-members-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@lunidev working through the backlog here. sorry for long delay. In VS2016 16.2 this works exactly as intended for me.  If you are still getting this error feel free to reopen.
