### ISSUE TITLE
Not for ARM64 

### ISSUE THREAD

**Issue by fobrs** [MicrosoftDocs/cpp-docs#775]
Doesn't work at all on ARM64 devices!! Better to use DirectCompute with HLSL compute shaders. Those work on ARM64 (!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219aaa58-4abd-48ac-69d7-1494bb60d6fe
* Version Independent ID: 14efc143-bf31-7643-4b4c-30d213e98e23
* Content: [C++ AMP (C++ Accelerated Massive Parallelism)](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-cpp-accelerated-massive-parallelism?view=vs-2017)
* Content Source: [docs/parallel/amp/cpp-amp-cpp-accelerated-massive-parallelism.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/cpp-amp-cpp-accelerated-massive-parallelism.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@fobrs thanks for the feedback. I have updated the system requirements on this page: [C++ AMP Overview](https://docs.microsoft.com/en-us/cpp/parallel/amp/cpp-amp-overview?view=vs-2017)

**Comment by fobrs** [comment]
It seems Visual Studio 2019 16.8 preview 2 supports C++ AMP on ARM64
https://developercommunity.visualstudio.com/comments/1162771/view.html
