### ISSUE TITLE
Missing how to set this linker option within CMake project

### ISSUE THREAD

**Issue by dcnoway** [MicrosoftDocs/cpp-docs#779]
To set this linker option within Visual Studio 2017 CMake project
1. Open your CMakeLists.txt in project root directory.
2. Add code below
    set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/PROFILE")
3. Rebuild your solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b65668-b767-0b57-445c-06988029d074
* Version Independent ID: eeaf28cc-45fe-c771-47ca-1c7ab52961a3
* Content: [/PROFILE (Performance Tools Profiler)](https://docs.microsoft.com/en-us/cpp/build/reference/profile-performance-tools-profiler?view=vs-2017)
* Content Source: [docs/build/reference/profile-performance-tools-profiler.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/profile-performance-tools-profiler.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@dcnoway Did you consider using [target_link_libraries]([url](https://cmake.org/cmake/help/latest/command/target_link_libraries.html)) or or[ target_link_options](https://cmake.org/cmake/help/git-stage/command/target_link_options.html) (if using a more recent version of CMake).

**Comment by dcnoway** [comment]
@Mike B
Thx for yr feedback!
I’m fine tuning a .exe file algorithm performance, not a .dll or .lib file.
Performance profiler requires /PROFILE linker options.
Therefore target_link_libraries is not suitable for me.

Maybe TARGET_LINK_OPTIONS is a good choice, but it is not supported by VS bundled CMake. (Visual Studio 15.9.6 CMAKE 3.12.18081601-MSVC_2)

I’ve just found a solution, and created a pull request on cpp-docs@GitHub.

BR

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mikeblome** [comment]
@dcnoway thanks!
