### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by egyik** [MicrosoftDocs/cpp-docs#785]
Regarding this bit,

    producing the following code:
    C++
```
    int main() {
       printf_s( "In quotes in the printf function call\n" "\n" );
       printf_s( "\"In quotes when printed to the screen\"\n" "\n" );
       printf_s( "\"This: \\\" prints an escaped double quote\"" "\n" );
    }
```

where did the duplicate "\n"s come from in the first two and why don't they lead to a blank line in the output? As far as I can see the stringer macro doesn't actually produce the first two lines of the code shown. As a check I compiled it using /P and it produced this, which also suggests the page isn't quite right.

```
   ...
   printf_s( "In quotes in the printf function call" "\n" );
   printf_s( "\"In quotes when printed to the screen\"" "\n" );
   ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 824eb991-74b4-975e-651c-ba57c2981d44
* Version Independent ID: 9349eb63-1e70-2986-c1c2-d945345a1723
* Content: [Stringizing Operator (#)](https://docs.microsoft.com/en-us/cpp/preprocessor/stringizing-operator-hash?view=vs-2017)
* Content Source: [docs/preprocessor/stringizing-operator-hash.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/stringizing-operator-hash.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@egyik When I compile with /P I get exactly what the example shows, and the code does produce the output shown when I run it.  I am not an expert on the preprocessor; if you still want to know why the duplicate \n's are produced, I suggest asking on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html)
