### ISSUE TITLE
Added tutorial information - exit

### ISSUE THREAD

**Issue by bbbender607** [MicrosoftDocs/cpp-docs#790]
It would be great to add an exit function to allow user to enter a char(\) and exit the console app outside of closing the window.  Very easy to follow the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2017)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Charmlie** [comment]
Also chars are bugging program

**Comment by corob-msft** [comment]
@bbbender607 Thanks for the suggestion. The logic to test whether the input is a formula or something else to terminate the program is a little too complex for what we're showing here, but it's a good idea.

@Charmlie  I can't tell what you're suggesting. If you've identified a problem, feel free to make a new issue to explain it.
