### ISSUE TITLE
To fix the "divide by zero" error

### ISSUE THREAD

**Issue by cwzhu0802** [MicrosoftDocs/cpp-docs#792]
the following code in this section please add ';'

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/zh-tw/cpp/get-started/tutorial-console-cpp?view=vs-2017)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cwzhu0802 Good catch, we'll fix that soon.

**Comment by pajenterprisesllc** [comment]
welcome team groups share we committee to our network

**Comment by pajenterprisesllc** [comment]
TEAM SHARE COMMITTEE

**Comment by corob-msft** [comment]
Okay, it took a little longer than soon. Sorry. This should be visible by sometime tomorrow.
