### ISSUE TITLE
Write memory access violation

### ISSUE THREAD

**Issue by win32nipuh** [MicrosoftDocs/cpp-docs#795]
I build the PostgreSQL odbc driver using VS2017. 
When test connection via odbc admin I receive: Write memory access violation exception.
It is here: 
extern PfnDliHook __pfnDliFailureHook2; 
extern PfnDliHook __pfnDliNotifyHook2;

void *CALL_PQconnectdb(const char *conninfo, BOOL *libpqLoaded)
{
	void *pqconn = NULL;
	*libpqLoaded = TRUE;
#if defined(_MSC_DELAY_LOAD_IMPORT)
		__pfnDliFailureHook2 = DliErrorHook;//&lt;----------
		__pfnDliNotifyHook2 = DliErrorHook;

It seems it is because MS has made these global variables as a constants starting from VS2015 Upd3 (delayimp.h)

How to fix it? When I declared these variables in the c file (not extern) - it works fine. Is it ok?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b15cb94-afea-7db4-5ff2-c367b337df22
* Version Independent ID: ca09e2c1-52b8-1ecf-e85f-a80e2e64f526
* Content: [Calling Conventions, Parameters, and Return Type](https://docs.microsoft.com/en-us/cpp/build/reference/calling-conventions-parameters-and-return-type?view=vs-2017)
* Content Source: [docs/build/reference/calling-conventions-parameters-and-return-type.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/calling-conventions-parameters-and-return-type.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@win32nipuh As the comment in delayimp.h says, you can define `DELAYIMP_INSECURE_WRITABLE_HOOKS` before you include delayimp.h for the old, less secure behavior, or you can define the const global values yourself by initializing them where you declare them:

```c
const PfnDliHook __pfnDliNotifyHook2 = delayHook;
const PfnDliHook __pfnDliFailureHook2 = failureHook;
```

The sample is missing the `const` in the comment. I expect you need to add an `extern "C"` if declaring them in C++ code.

**Comment by win32nipuh** [comment]
Thank you, it is c code, it is odbc driver.

**Comment by corob-msft** [comment]
Closing as fixed.
