### ISSUE TITLE
CWinApp::HtmlHelp details

### ISSUE THREAD

**Issue by franji1** [MicrosoftDocs/cpp-docs#798]
You do not bother to document ANY details about any of the parameters.  That would be useful.  Instead, you mention that the information on the parameters is documented in "About the HTMLHelp API Function in the Windows SDK", yet you provide NO LINK.

Either
1. Provide the details here (don't make me look for the details somewhere else - that's what this API documentation is for)
2. If you don't do that, provide the link to that information.  It's a web technology called a hyperlink.  That's actually why they call the web "the web".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868c82ff-f178-6604-9e18-03dac386f66c
* Version Independent ID: dba959a3-5d40-115f-7d14-dff4bbeb048d
* Content: [CWinApp Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cwinapp-class?view=vs-2017#htmlhelp)
* Content Source: [docs/mfc/reference/cwinapp-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cwinapp-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by KalleOlaviNiemitalo** [comment]
I imagine it would call [HtmlHelpW](https://docs.microsoft.com/en-us/windows/desktop/api/htmlhelp/nf-htmlhelp-htmlhelpw). The default value `UINT nCmd = 0x000F` would then mean [HH_HELP_CONTEXT](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/hh-help-context-command).

**Comment by franji1** [comment]
Agreed - those links need to appear in the CWinApp::HtmlHelp topic.  Hopefully someone can add those links.

**Comment by mikeblome** [comment]
@franji1 We will add them. Just be aware that these topics were originally written long before the age of internet.

**Comment by mikeblome** [comment]
@franji1 @KalleOlaviNiemitalo thanks for the feedback and links. Update should appear by July 15.
