### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by goodandrewsoft** [MicrosoftDocs/cpp-docs#804]
How debug from Developer Command Prompt if have only Build Tools for Visual Studio ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96f0a01-2e3a-6301-bba1-6a50252555b0
* Version Independent ID: 290ca773-a214-e81a-2ba3-c647f2b28a56
* Content: [Walkthrough: Compile a C program on the command line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=vs-2017)
* Content Source: [docs/build/walkthrough-compile-a-c-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-compile-a-c-program-on-the-command-line.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
good question. Investigating.

**Comment by mikeblome** [comment]
@goodandrewsoft The Build Tools for Visual Studio are just that--"build" tools. No debugger is included. You can install Visual Studio Community to debug from the IDE, or you can try using [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools), although it's not simple to learn.
