### ISSUE TITLE
PlatformName and PlatformShortName not documented

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/cpp-docs#806]
There is no `$(Platform)`, but there is no description of `$(PlatformName) and `$(PlatformShortName).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba7e6dc-88bf-47ff-7bcf-467140bc92f1
* Version Independent ID: 5dfa8c91-eb92-8905-741e-15cd10d54baa
* Content: [Common macros for build commands and properties](https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties?view=vs-2017)
* Content Source: [docs/ide/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@mloskot Thanks. I added an item for PlatformShortName. PlatformName gives similar values to Platform. The specific properties that are available depends on the project type as well as "Debug" vs "Release" configuration. Note that the list is not intended to be exhaustive and the topic describes how to view all the available properties and their values for your specific project configuration.

**Comment by mloskot** [comment]
@mikeblome Thanks. What is the commit? When the docs site gets updated?

**Comment by mikeblome** [comment]
@mloskot I commit to a private repo. The updates should appear later today (US Pacific time) when the public master syncs with our private master. Feel free to reopen if you still see a problem with the update.

**Comment by mloskot** [comment]
The page is now updated. Thanks
