### ISSUE TITLE
Incorrect menu sequence

### ISSUE THREAD

**Issue by timhargreaves** [MicrosoftDocs/cpp-docs#809]
The doc states you click File-&gt;New-&gt;File... but it should be File-&gt;Open-&gt;File...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3406b4da-3d4f-a3c8-a946-675cf3ff7bdc
* Version Independent ID: 3781d0ac-47eb-50bf-9b13-4b5d5c6bcea0
* Content: [Binary Editor (C++)](https://docs.microsoft.com/en-us/cpp/windows/binary-editor?view=vs-2017)
* Content Source: [docs/windows/binary-editor.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/binary-editor.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by msebolt** [comment]
Thank you for the feedback.  It appears you can get to the Binary Editor using both methods, so the Open method has also been added.

@mikeblome This issue can be closed.

**Comment by msebolt** [comment]
Close #809.
