### ISSUE TITLE
"Destructors for debug iterators" documentation contains a bug

### ISSUE THREAD

**Issue by mdaum-adsk** [MicrosoftDocs/cpp-docs#810]
In the documentation here: 
https://docs.microsoft.com/en-us/cpp/standard-library/debug-iterator-support?view=vs-2015#destructors-for-debug-iterators
Line 17:   "auto sink = new auto(std::begin(vect));"
should read "base* sink = new derived(std::begin(vect));"
in order to show what the example is trying to demonstrate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c200cd0a-85db-45ed-8e50-2a5f563d3156
* Version Independent ID: d43ff7d9-9c13-7eb3-88e6-c0221a5e8a80
* Content: [Debug Iterator Support](https://docs.microsoft.com/en-us/cpp/standard-library/debug-iterator-support?view=vs-2015#feedback)
* Content Source: [docs/standard-library/debug-iterator-support.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/debug-iterator-support.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mikeblome This looks like it arrived in the fix for #316. The slicing was intentional in the original example.

**Comment by mikeblome** [comment]
@mdaum-adsk. this was fixed awhile ago. thanks for the feedback!
