### ISSUE TITLE
Example to turn off warning incorrect

### ISSUE THREAD

**Issue by cdannemillernv** [MicrosoftDocs/cpp-docs#811]
Should be

#pragma warning(push)
#pragma warning ( disable : 4789 )
// unused code that generates compiler warning C4789`
#pragma warning(pop)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 771af8fa-b7dd-3db1-7d4e-91462941d410
* Version Independent ID: 57d31fa1-7482-8bba-60c7-19e971d2483d
* Content: [Compiler Warning (Level 1) C4789](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4789?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4789.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4789.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cdannemillernv You are correct. Thanks for pointing the error out. Would you like to take it one step further and submit a PR with a fix? (It's okay to say no, but simple things like this are a great way to get your feet wet.)

**Comment by corob-msft** [comment]
This is fixed and should be visible within a day.
