### ISSUE TITLE
Launch external programs

### ISSUE THREAD

**Issue by f-tischler** [MicrosoftDocs/cpp-docs#813]
Could you please give an example of how to launch external programs (e.g.: mpiexec) using launch.vs.json? In the case of mpiexec, how do I pass the full path to the executable? Is there a variable? 

I think this documentation is only helpful for getting started but is insufficient for actually working with the CMake integration. There is no documentation regarding variables provided by the IDE (in CMakeSettings.json and launch.vs.json) and no in-depth explanation of the configurable options (launch.vs.json, the descriptions provided by IntelliSense are not enough).

Please extend the documentation as the feature itself is super helpful and deserves more coverage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [CMake Projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017#single-file-compilation)
* Content Source: [docs/ide/cmake-tools-for-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@f-tischler Yes we are working on improving these topics.  You can use the tasks.vs.json file to define any arbitrary command line. Pass the full path to mpiexec in the "command" property and the arguments in the args array in the order that they are expected by mpiexec. This topic talks a little about it but doesn't have a great example for your scenario: https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017

**Comment by sfreed141** [comment]
Hi f-tischler,

There isn't a variable for the executable itself as far as I know, but you can access some of the variables defined in your CMakeSettings.json configuration. Maybe something like `/path/to/mpiexec ${cmake.buildRoot}/main.exe` will work? The blog post [CMake Support in Visual Studio: Customizing your Environment](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio-customizing-your-environment/) might also help.

Thanks for the feedback!
