### ISSUE TITLE
Linker Tools Error LNK1104

### ISSUE THREAD

**Issue by abobakrosman** [MicrosoftDocs/cpp-docs#814]
just make sure to close cmd window of last execution , then it will work incase the problem is "Can't read file /$path/to_exe_file" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd245507-f539-59bf-7ee6-2ba83928cd0c
* Version Independent ID: 97ea8b32-6ce0-d65f-d8f8-8726b53b3d75
* Content: [Linker Tools Error LNK1104](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1104)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1104.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1104.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
True enough. "If the filename is the executable your project builds, or an associated .pdb file, the most common cause is that your application is already running when you try to rebuild it, or it is loaded in a debugger." An instance loaded in a command window is a good example.
