### ISSUE TITLE
I still cannot run a cpp file

### ISSUE THREAD

**Issue by erelsgl** [MicrosoftDocs/cpp-docs#815]
I followed the instructions in this article:
* I cloned a github repository which contains a lot of c++ programs (each in its own subfolder).
* I opened the main repository folder using "Open Folder". It appeared in my Solution Explorer tab.
* I created a CppProperties.json file in the main repository folder, with a single configuration "x64-Debug" (automatically generated by Visual Studio).
* I opened one of the cpp files and clicked "Ctrl+F5", but nothing happened.

What else should I do in order to run cpp files in Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017)
* Content Source: [docs/ide/non-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/non-msbuild-projects.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@erelsgl You need to configure a launch.json file and tasks.json file. The document shows how to do that, at least for basic scenarios.

**Comment by erelsgl** [comment]
I tried to read it, but the number of options is overwhelming. All I need is to be able to run single CPP files (for demonstration in class). Is there a simpler guide for this need?

**Comment by mikeblome** [comment]
@erelsgl Sorry that it's confusing for you. We are working to make the workflow simpler in future versions of VS. In the meantime we now have this new tutorial: https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2017

If you still have questions, a great place to ask is the [C++ VS Developer Community forum](https://developercommunity.visualstudio.com/topics/C%2B%2B.html). There are several experts active on that site. Good luck!
