### ISSUE TITLE
Compiler Warning (level 2) C5046 - Version of 2017 this appeared in?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#817]
> This warning is new in Visual Studio 2017.

Would be nice to know which version of VS2017 this came out in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14e3b93-6d3d-b26c-99bd-bff4f22a95b5
* Version Independent ID: 9b32be60-20f2-a277-6c75-265c4b1bb991
* Content: [Compiler Warning C5046](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5046?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/c5046.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/c5046.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
[Compiler Warnings by compiler version](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version) reports this appeared in Visual Studio 2017 version 15.8. I'm not sure why that was left out of this page.

**Comment by corob-msft** [comment]
The detailed version info should appear in an update tomorrow or possibly Monday.
