### ISSUE TITLE
/Zm is ignored?

### ISSUE THREAD

**Issue by toughengineer** [MicrosoftDocs/cpp-docs#821]
[This](https://devblogs.microsoft.com/cppblog/precompiled-header-pch-issues-and-recommendations/) post says that `/Zm` flag is ignored and should not be used:

> The `/Zm` flag was retained for the `#pragma hdrstop` scenario that might work only with a PCH containing a single contiguous address range. The `/Zm` flag should not be used in any other scenario, and the value reported by fatal error C3859 should be ignored.

It would be nice to reflect those changes in this documentation since most probably everyone lands here while searching, instead of that blog post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f64acde-131d-c100-3ca2-907c5d9b50f3
* Version Independent ID: 2086f45d-c987-0dbd-1116-8e5ce54a7136
* Content: [/Zm (Specify Precompiled Header Memory Allocation Limit)](https://docs.microsoft.com/en-us/cpp/build/reference/zm-specify-precompiled-header-memory-allocation-limit?view=vs-2017)
* Content Source: [docs/build/reference/zm-specify-precompiled-header-memory-allocation-limit.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/zm-specify-precompiled-header-memory-allocation-limit.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
This was fixed a couple of weeks ago, but I forgot to update this issue. Closing.
