### ISSUE TITLE
intelliSenseMode values are incorrect

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#833]
The values listed for the intelliSenseMode property are incorrect.  In particular, it must be "windows-msvc-x64" and not "msvc-x64".  A help popup in VS shows me a bunch of other values that are not listed at all in this documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017#configuring-open-folder-projects)
* Content Source: [docs/ide/non-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/non-msbuild-projects.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@LegalizeAdulthood thanks for the feedback. You are correct and the topic now is fixed. The complete list of IntellisenseMode values is listed here: [CMakeSettings.json Schema Reference](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2017)
