### ISSUE TITLE
Table in Environment Variables section doesn't give values of predefined variables

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#834]
A bunch of variables are listed in two tables: 

Variable Name | Description
-- | --
vsdev | The default Visual Studio environment
msvc_x86 | Compile for x86 using x86 tools
msvc_arm | Compile for ARM using x86 tools
msvc_arm64 | Compile for ARM64 using x86 tools
msvc_x86_x64 | Compile for AMD64 using x86 tools
msvc_x64_x64 | Compile for AMD64 using 64-bit tools
msvc_arm_x64 | Compile for ARM using 64-bit tools
msvc_arm64_x64 | Compile for ARM64 using 64-bit tools

and this table

Variable Name | Description
-- | --
linux_x86 | Target x86 Linux remotely
linux_x64 | Target x64 Linux remotely
linux_arm | Target ARM Linux remotely

The Description column is essentially worthless.  In order to use these variables, we need to know what their values are expected to be.  Are they paths?  Are they true/false?  Are they 0/1?

An example of their use would clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017)
* Content Source: [docs/ide/non-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/non-msbuild-projects.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@LegalizeAdulthood We recently updated these docs. Does this page now provide the info you were expecting? [CppProperties Schema Reference](https://docs.microsoft.com/en-us/cpp/build/cppproperties-schema-reference?view=vs-2017)

**Comment by LegalizeAdulthood** [comment]
This is still confusing.  The table lists those names as "environment variables", but they aren't environment variables.  The example shows that they are used as values in the `inheritEnvironment` array that imply that the set of environment variables for the named compilation configuration will be inherited in the configuration.

In other words, these aren't the names of "environment variables", but they are instead identifiers that refer to specific compilation environments.

**Comment by mikeblome** [comment]
this is now fixed. thanks @LegalizeAdulthood !
