### ISSUE TITLE
Description about populating launch.vs.json is misleading for Open Folder

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#836]
> Configure debugging parameters with launch.vs.json
> To customize your program’s command line arguments, right-click on the executable in Solution Explorer and select Debug and Launch Settings. This will open an existing launch.vs.json file, or if none exists, it will create a new file prepopulated with the information about the program you have selected.

This doesn't work if you're doing Open Folder and it doesn't know anything about your existing targets.  It populates the JSON file with a bare minimum template and you have no guidance on what you need to fill in.  I tried figuring it out from the example given and the schema file associated with the JSON file, but didn't manage to make it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315efb2e-e70d-1117-4916-522a5e9f629f
* Version Independent ID: 796872b1-bba1-f7d8-5df9-d3f1c3ea905d
* Content: [Open Folder projects in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects?view=vs-2017)
* Content Source: [docs/ide/non-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/non-msbuild-projects.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by LegalizeAdulthood** [comment]
Maybe the description is referring to a folder structure where you have CMakeLists.txt present and VS can figure out the targets?

**Comment by sfreed141** [comment]
Hi,

Can you provide more information on your project and what you tried adding to launch.vs.json? There's a bit more information in [Customize build and debug tasks for "Open Folder" development](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2017#configure-debugging-with-launchvsjson) about configuring launch.vs.json, but I'm not sure I can help without more information.

Open Folder doesn't require any particular build system. However, CMake is natively supported by VS; if you open a folder with a CMakeLists.txt in it VS will be able to generate, build, and debug without any extra configuration through tasks.vs.json or launch.vs.json.

Let me know if that helps!

**Comment by range4life** [comment]
I agree. I can't find any proper documentation on what to put here when using an open folder project.

**Comment by LegalizeAdulthood** [comment]
Yeah, it's not a CMake based project.

I keep seeing this in VS issues; they equivocate Open Folder with CMake, but Open Folder isn't just for CMake, it's supposed to be the way to integrate foreign build systems into VS in such a manner that I get support for building, launching and debugging.

We need a complete example for integration of a foreign build system using these JSON files.

**Comment by range4life** [comment]
So for example, I have an open folder project (opened through Samba share on a remote linux host)
I right click on the folder and select "Debug and Launch settings".
I Select "C/C++ Attach for Linux (gdb)"

The following config is generated
```json
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "Y:\\home\\jake\\test",
      "project": "",
      "cwd": "${debugInfo.remoteWorkspaceRoot}",
      "program": "${debugInfo.fullTargetPath}",
      "processId": 0,
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "${debugInfo.remoteMachineName}",
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}",
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}",
          "/p",
          "${debugInfo.parentProcessId}",
          "/c",
          "${debuggerCommand}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
  ]
```

The example json has been populated with a bunch of macros for CMake projects. The tooltips/schema simply give a small description of the value and state that "When using CMake, ${debugInfo.whatever} can be used as the value for this field". 

However, I have no idea what to replace these macros with for my situation. I could assume remoteMachimeName is probably just an IP, but I don't really have a clue for the others. It fails pretty silently if the config is bad, so without a proper example for what to put here in the docs, it is very hard to get this working.

**Comment by LegalizeAdulthood** [comment]
When I right click on the folder and select Debug and Launch Settings and select Native, I only get
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "native",
      "name": "foo",
      "project": "apps\\foo"
    }
  ]
}
```

....this isn't helpful at all.

**Comment by mikeblome** [comment]
@range4life @LegalizeAdulthood We just updated the documentation for this feature. Can you take a look at let us know if there are still areas that are unclear to you? Thanks!

**Comment by range4life** [comment]
Seems pretty good now. I have yet to try it again, but looking at the new documentation, I feel like I'd have a much easier time figuring it out.
