### ISSUE TITLE
What happens if buffer size is too small?

### ISSUE THREAD

**Issue by frankbj57** [MicrosoftDocs/cpp-docs#841]
This is a documentation issue.

It is not clear what happens for the formats %s if the string is not terminated by a white space character before the maximum size is exceeded, and the buffer thus would be too small. 

My experience with the current version is that no data is returned at all, but the terminating '\0' is inserted in the first place of the buffer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4051396d-7d18-d9e1-d79c-d7cf6c23d369
* Version Independent ID: cbe04153-c724-3498-74e6-3da4fbf6c07f
* Content: [scanf_s, _scanf_s_l, wscanf_s, _wscanf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/scanf-s-scanf-s-l-wscanf-s-wscanf-s-l?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(EXERCISE%2B6_2%2Fscanf_s)%3Bk(scanf_s)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/reference/scanf-s-scanf-s-l-wscanf-s-wscanf-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/scanf-s-scanf-s-l-wscanf-s-wscanf-s-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@frankbj57 In the situation you describe, the return value will indicate that the string field wasn't converted successfully. All the output variables after the count that succeeded should be considered undefined. That means they might have their original values - or they might not. The behavior you see (of putting a null character at the beginning of a string buffer that failed conversion) is basically an undocumented implementation detail that you shouldn't rely upon; if you do, you get undefined behavior.

**Comment by Andrey-Tarasevich** [comment]
> ... That means they might have their original values - or they might not...

Very nice. Now, the documentation page clearly and explicitly says that in this case "nothing is written to the buffer". This contradicts what you said above.

The essence of this defect report is _specifically_ the error in the documentation page. Obviously it has not been fixed, yet this defect is "closed" for some reason. Why is it closed?
