### ISSUE TITLE
Specify Folder for Remote Debuggin

### ISSUE THREAD

**Issue by YoDaMa** [MicrosoftDocs/cpp-docs#843]
So I followed these steps to connect to my remote Linux VM which is running a C++ Project on a Linux Container. Now, I'm trying to debug the process. There is a way to specify the local folder that the compiled code in the linux container maps to, but I'm not finding any documentation on that. Is it not documented? If not, I'd appreciate documentation on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77337ba5-50f6-b474-89db-dd51bd8b560d
* Version Independent ID: cdc28c8a-a50e-f6d6-bf25-f5d80b056a5a
* Content: [Connect to your remote Linux computer in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=vs-2017)
* Content Source: [docs/linux/connect-to-your-remote-linux-computer.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/connect-to-your-remote-linux-computer.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by elizabethmorrow** [comment]
Hi @YoDaMa 

Can you give me more information about your project pipeline?

Is it correct that you have Visual Studio running on a Windows machine connected via SSH to a Linux VM, inside which you have a Linux container? Is this project using MSBuild (vcxproj) or CMake? 

Is this property debugging specific? What is the property name? Are you looking to customize the local:remote source mapping enabling the debugger to locate symbols? In your case would this map a Windows folder to the folder containing the binaries inside your container?

Thanks!
Elizabeth

**Comment by YoDaMa** [comment]
@elizabethmorrow @mikeblome  I'm sorry this was a while ago and the details are fuzzy. 

> Is it correct that you have Visual Studio running on a Windows machine connected via SSH to a Linux VM, inside which you have a Linux container? Is this project using MSBuild (vcxproj) or CMake?

I did have Visual Studio running in Windows connected via SSH to a Linux VM inside of which I have a Linux container. The project I was working on uses CMake.

> Is this property debugging specific? 

This scenario is debugging specific. For instance, imagine I want to step through the execution of my compiled C++ project running in that Linux container on my Linux VM. That way I can use Visual Studio to see what the variables are being set to, if maybe there's an issue with my pointers etc. et. etc. To do that I need to say to Visual Studio, "hey visual studio! See that folder in that container in that machine we are SSHing into? That's where my executable file is, compiled specfically for debugging. And please set a breakpoint in line 15 of my main.c file, so when it is running we can pause the execution right there."

> What is the property name? 

I don't know what this means.

> Are you looking to customize the local:remote source mapping enabling the debugger to locate symbols? 

I'm going to go with yes to this question, although I don't fully understand it.

> In your case would this map a Windows folder to the folder containing the binaries inside your container?

What you said sounds correct: a windows folder to the folder containing the binaries inside the container.

**Comment by elizabethmorrow** [comment]
Thanks @YoDaMa for the quick reply! I believe I've got a solution for you.

If you rick click one of the .cpp or CMakeLists.txt files in your project and select "Debug and Launch Settings" it will pop up a dialog where you can select a custom debugging template. Select "C/C++ Launch for Linux (gdb)" from that list. It will create a file called launch.vs.json which will allow you to customize your debugging launch options. Within this file, if you add a parameter "sourceFileMap" this allows you to indicate to the debugger where your binaries are located on the remote device and how this maps back to your local file system. You shouldn't have to change anything else in this file.

Let me know if this solution works for you!

Example using WSL:

"MIMode": "gdb",
      "externalConsole": true,
      "sourceFileMap": {
        "/mnt/c/Users/<USER>/source/repos/CMakeProject139": "C:\\Users\\<USER>\\source\\repos\\CMakeProject139"
      },
      "remoteMachineName": "${debugInfo.remoteMachineName}",

**Comment by mikeblome** [comment]
@YoDaMa are you unblocked now?

**Comment by mikeblome** [comment]
topic has been updated
