### ISSUE TITLE
generic_errno does not exist in VS2017

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/cpp-docs#848]
This page claims `<system_error>` defines `generic_errno`, but I can't find the `generic_errno` name anywhere in the C++ include directories of Visual Studio 2017 version 15.9.9, nor does the compiler recognize it after `#include <system_error>` and `using namespace std;`.

The `<system_error>` header of Visual Studio 2010 SP1 did define `generic_errno`, perhaps as a workaround for `enum class` not being supported.

As `generic_errno` doesn't seem to be part of standard C++ either, I think its documentation should be just removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64adc4fb-8639-cdad-8aeb-319878979dfb
* Version Independent ID: 9a73e2e0-32f9-a7e3-1378-259475f71ceb
* Content: [&lt;system_error&gt; typedefs](https://docs.microsoft.com/en-us/cpp/standard-library/system-error-typedefs?view=vs-2017#feedback)
* Content Source: [docs/standard-library/system-error-typedefs.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/system-error-typedefs.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@KalleOlaviNiemitalo  It appears that support for the `generic_errno` typedef was last seen in VS 2013, and dropped from VS 2015, which is as far back as our current documentation covers. I'll look into removing the references.

**Comment by corob-msft** [comment]
@KalleOlaviNiemitalo The fixes were slightly more involved than expected, but they look to be live now.
