### ISSUE TITLE
There is no main..

### ISSUE THREAD

**Issue by GrantMeStrength** [MicrosoftDocs/cpp-docs#852]
"The last line of the main function shows how you call the function object."

But there is no main function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a48c9128-4bd0-c584-2629-1184ae31c20d
* Version Independent ID: 820e99d3-9535-de76-5a13-8d06b94fb4cd
* Content: [Function Objects in the C++ Standard Library](https://docs.microsoft.com/en-us/cpp/standard-library/function-objects-in-the-stl?view=vs-2017)
* Content Source: [docs/standard-library/function-objects-in-the-stl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/function-objects-in-the-stl.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@GrantMeStrength True enough. It appears the relevant bit of code disappeared during the conversion to markdown in late 2016. I'll see about restoring it.

**Comment by corob-msft** [comment]
@GrantMeStrength It looks like the fix is live. Thanks for pointing out this issue.
