### ISSUE TITLE
Old-fashionned early-PC era wording

### ISSUE THREAD

**Issue by johan-boule** [MicrosoftDocs/cpp-docs#854]
I stopped reading at the word "x-copyable". This smells MS-DOS jargon so much that I cannot believe the cross-platform announce that's been made in the title. Rather than being covered with that disgusting dirt, I would be very much more interested to know why you are reinventing yet another source-based distribution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf8c665-4a38-7b59-e9e9-4887092c0aec
* Version Independent ID: c3fb32c6-e29e-9a2f-cdac-d68502a86dc4
* Content: [vcpkg-- A C++ package manager for Windows, Linux and MacOS](https://docs.microsoft.com/en-us/cpp/vcpkg?view=vs-2017#feedback)
* Content Source: [docs/vcpkg.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/vcpkg.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks for calling this to our attention. If I recall correctly, vcpkg was not yet cross-platform when this topic was first written.

**Comment by johan-boule** [comment]
This seems to be mostly fixed now (there's an apparent VC bias, but that's to be expected due to the tool name). What a relief for all the old folks who can't stand MSDOS-based "subculture"!
