### ISSUE TITLE
ATL Tutorial Error - did not find .idl file in project

### ISSUE THREAD

**Issue by LabObjects** [MicrosoftDocs/cpp-docs#855]
Hi,

When executing the Active Template Library (ATL) Tutorial I experienced a "did not find .idl file in project" error when attempting to add a ATL Simple Object or ATL Control. I have determined this error can be prevented by deselecting the "Security Development Lifecycle (SDL) checks option when creating the ATL (dll) project. 

Suggested update to Part 1 of tutorial, step 7, change: 
7. Leave the other options at their default values, and click OK.
to: 
7. From the list of options, deselect the <strong>Security Development Lifecycle (SDL) check</strong> option and leave the other options at their default values, and click OK. 

 Path: docs.microsoft.com/en-us/cpp/atl/creating-the-project-atl-tutorial-part-1?view=vs-2017

I am using Microsoft Visual Studio Professional 2017 Version 15.9.9.

This may not be the best fix - but it worked :-)

The Visual Studio 2019 page for the tutorial has the same text.
Thanks!

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@LabObjects. I cannot repro in VS2019. Is it possible you missed this step:

To enable support for rich error information and connection points
Click Options to open the Options page.
Select the Connection points check box. This option creates support for an outgoing interface in the IDL file.

**Comment by LabObjects** [comment]
Hi - okay thanks. I haven't tried it on VS2019, but will try it in the near future. Worst case - I have a work-around if I experience it again (maybe it is workstation specific). Thanks for you're time and efforts. Kind regards, April
