### ISSUE TITLE
<string_view> is not documented

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/cpp-docs#856]
The C++17 standard header &lt;string_view&gt; comes with Visual Studio 2017 but the header and the types it defines are not documented in the cpp-docs repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3f34a7-062a-f199-f31e-d35e0444d9be
* Version Independent ID: 5fba6de8-b958-f9e7-b0b6-059ec6ac8cf6
* Content: [C++ Standard Library Header Files](https://docs.microsoft.com/en-us/cpp/standard-library/cpp-standard-library-header-files?view=vs-2017#feedback)
* Content Source: [docs/standard-library/cpp-standard-library-header-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/cpp-standard-library-header-files.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@KalleOlaviNiemitalo we are working on adding <string_view> to the documentation. It is on our backlog.

**Comment by mikeblome** [comment]
@KalleOlaviNiemitalo this is now documented: https://docs.microsoft.com/en-us/cpp/standard-library/string-view?view=vs-2017

**Comment by KalleOlaviNiemitalo** [comment]
@mikeblome Can you please add it to the "Headers by category" list, too?

**Comment by mikeblome** [comment]
@KalleOlaviNiemitalo done. you should see it tomorrow. thanks again!
