### ISSUE TITLE
Document that copy constructor of ATL::CHandle moves the handle

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/cpp-docs#859]
`<atlbase.h>` defines the copy constructor of `ATL::CHandle` as follows:

```C++
inline CHandle::CHandle(_Inout_ CHandle& h) throw() :
	m_h( NULL )
{
	Attach( h.Detach() );
}
```

The `h.Detach()` call resets `h.m_h` to `NULL`, so the copy constructor really does a move. Please make this clear in the documentation.  One could expect the copy constructor to call `DuplicateHandle` instead, but it doesn't do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e781808-19b3-e8dd-7b18-acccdc7dbbb4
* Version Independent ID: bfbec978-c76c-5b45-1e8c-d201abe565be
* Content: [CHandle Class](https://docs.microsoft.com/en-us/cpp/atl/reference/chandle-class?view=vs-2017#chandle)
* Content Source: [docs/atl/reference/chandle-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/reference/chandle-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed
