### ISSUE TITLE
code comment incorrect

### ISSUE THREAD

**Issue by mintonla1958** [MicrosoftDocs/cpp-docs#861]
code comment:
    // Configure per-thread locale to cause all subsequently created
    // threads to have their own locale.
   _configthreadlocale(_ENABLE_PER_THREAD_LOCALE);
is incorrect. This is not inherited by created threads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5dbe29a-f595-339c-16a4-26614227002a
* Version Independent ID: 35e014bc-8b94-1596-ef43-6c58884c0ed0
* Content: [setlocale, _wsetlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/reference/setlocale-wsetlocale.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/setlocale-wsetlocale.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mintonla1958 Thanks for pointing this out. It's fixed in the current document.
