### ISSUE TITLE
locale::global does not support per-thread

### ISSUE THREAD

**Issue by mintonla1958** [MicrosoftDocs/cpp-docs#862]
setting locale::global is always program global, per-thread support is not present. So setting of _configthreadlocale does not matter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d59f7-3875-d49b-0344-c96fa364727d
* Version Independent ID: 43ea89e9-bd06-6454-fe44-4cc14c29ccf6
* Content: [locale Class](https://docs.microsoft.com/en-us/cpp/standard-library/locale-class?view=vs-2017#global)
* Content Source: [docs/standard-library/locale-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/locale-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@mintonla1958 Doesn't the example on this page show that _configthreadlocale does override the global locale for the thread that it is called on? [_configthreadlocale](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/configthreadlocale?view=vs-2017)

**Comment by corob-msft** [comment]
@mintonla1958 I would not say that `_configthreadlocale` does not matter. The C++ Standard Library doesn't support per-thread locale settings, or at least, it doesn't yet. The `_configthreadlocale` function is a Microsoft extension that supports enabling per-thread locales for the C runtime library (CRT), but you get weird differences between the behavior of the C++ Standard Library (STL) and the CRT if you enable it. The various combinations are explained in [Multithreading and Locales](https://docs.microsoft.com/en-us/cpp/parallel/multithreading-and-locales).

I can summarize some of the effects here: Internally, the CRT and the STL have separate static locale info stores, and the CRT can also use per-thread locale info stores. If you set the locale info using the CRT functions, the STL store doesn't know about those changes, but any CRT functions it delegates to will use them. The `locale::global` function, on the other hand, sets both the STL store and the CRT store with the same locale info values. Unfortunately, if it's called on a thread that's got per-thread locale info enabled, then the STL store change is global, but it only updates the thread-local CRT store. A different thread might have different CRT locale store settings. And even if `locale::global` is called on a thread that's using global locale settings, any threads that have per-thread locales set will be unaffected as far as the CRT functions called in those threads are concerned. Mixing STL and CRT calls for locale info can be fraught, and doubly so when per-thread locale info is used. The upshot is probably to stick to one or the other, but don't mix them.

I'm not sure that this needs additional documentation. I'll close it unless there's a more specific suggestion.

**Comment by mintonla1958** [comment]
sorry, wasn't clear. I'm talking strictly about the behavior of locale::global. 

Per http://www.cplusplus.com/reference/locale/locale/global/: Whether a single _global locale exists for the entire program, or one for each thread, depends on the library implementation.

So then the question was what is the MS implementation?  Other than by discovering by experimentation, the only place I saw that documented the behavior at all was buried in:

https://docs.microsoft.com/en-us/cpp/parallel/multithreading-and-locales?view=vs-2017:
Since the locale::global method changes the locale "globally", all C++ Standard Library objects in all threads start using the "french" locale.

So, it would be nice if the documentation of locale::global explicitly stated the implementation.

>> Mixing STL and CRT calls for locale info can be fraught, and doubly so when per-thread locale info is used
I hear that...  Been digging and experimenting on our app (Autodesk 3D Studio Max) on how to cleanly deal with locales. Frankenstein code, lots of c runtime, lots of c++ runtime, millions of lines, dlls coming in from other parts of Autodesk. One of them was pushing/popping c runtime locale in background thread causing decimal character in main thread to constantly change.  I more or less have a game plan at this point. Still confused on how when using french locale am seeing:

std::wostringstream ss; ss << 1.2f;  -- > output shows period decimal separator
std::locale loc; std::use_facet< std::numpunct<char> >(loc).decimal_point(); --> gives comma decimal separator

One of those forementioned dlls is doing a locale::global call, need to track those devs down to see what they are doing.   8pm evening fun...

**Comment by mintonla1958** [comment]
Just because random information is sometimes useful, the code setting the global locale was:
inline bool StdGeneralUtil::SetLocale()
{
	// Create and install global locale 
	std::locale::global(boost::locale::generator().generate("")); 
	// Make boost.filesystem use it 
	boost::filesystem::path::imbue(std::locale()); 
	return true; 
}
Folks responsible for that are fixing it..
