### ISSUE TITLE
Minor error in wording on Function Templates page

### ISSUE THREAD

**Issue by echuber2** [MicrosoftDocs/cpp-docs#863]
The last example on [the Function Templates page](https://docs.microsoft.com/en-us/cpp/cpp/function-templates?view=vs-2019) is this:

```c++
// function_templates2.cpp
template<class T> void f(T) {}
int main(int j) {
   f<char>(j);   // Generate the specialization f(char).
   // If not explicitly specified, f(int) would be deduced.
}
```

And then the paragraph below says,

> In the above example, the compiler will convert `char j` to type `int`.

I think it means to say, the compiler will convert `int j` to type `char`. (Unless I misunderstand the point the text is trying to make!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae0e123-9f52-bc7c-6a85-d0e5c0c79a74
* Version Independent ID: f314ba12-79ad-e35c-ecd9-f20691cb9be1
* Content: [Function Templates](https://docs.microsoft.com/en-us/cpp/cpp/function-templates?view=vs-2017)
* Content Source: [docs/cpp/function-templates.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/function-templates.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@echuber2 you understand better than the writer apparently. fixed as of July 15 and thanks!
