### ISSUE TITLE
Note H is missing

### ISSUE THREAD

**Issue by TheThief** [MicrosoftDocs/cpp-docs#865]
There's a "H" next to Guaranteed Copy Elision but no corresponding note below the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Visual C++ Language Conformance](https://docs.microsoft.com/en-us/cpp/visual-cpp-language-conformance?view=vs-2017#feedback)
* Content Source: [docs/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheThief Good point. I'll see if I can find where it went.

**Comment by corob-msft** [comment]
The footnote originally went to a comment that the feature was available in previews of 15.3, but was pulled from the release. The comment was removed as no longer relevant when the feature shipped in 15.6,  but I forgot to remove the superscript H. A fix should be visible tomorrow or Monday.
