### ISSUE TITLE
Broken Links under NMAKE Reference in PDF

### ISSUE THREAD

**Issue by DavidIsrawi** [MicrosoftDocs/cpp-docs#868]
NMake Reference -[ pg. 682 of complete PDF documentation](https://docs.microsoft.com/en-us/cpp/opbuildpdf/vcppdocs-2015/build/reference/TOC.pdf?view=vs-2017&branch=live)

**Issue**
Links on PDF added below are broken and still exposed to the document.

**Path**
cpp-docs/docs/build/reference/nmake-reference.md

**Broken Links**
- [Use the MSVC toolset from the command line](https://docs.microsoft.com/en-us/cpp/vcppdocs-2015/build/building-on-the-command-line)
- [Visual Studio Projects - C++](https://docs.microsoft.com/en-us/cpp/vcppdocs-2015/build/creating-and-managing-visual-cpp-projects)

**Comment by mikeblome** [comment]
@DavidIsrawi sadly I have to resolve this as "by design".  The "Create PDF" function does not pull in any files that are outside of the current Table of Contents node.  Someday we may have a better story for offline viewing, but not yet.
