### ISSUE TITLE
Second _mbstok_s likely should be _mbstok_s_l

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#874]
@versat commented on [Fri Mar 22 2019](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/17)

There are two declarations for _mbstok_s. The second one likely has the wrong function name and should be named _mbstok_s_l (as in the title).

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ba4b0c0f-c781-903c-9c46-f562546a3c2c
* Version Independent ID: 17285c50-16d2-cafb-c976-29983f66f822
* Content: [strtok_s, _strtok_s_l, wcstok_s, _wcstok_s_l, _mbstok_s, _mbstok_s_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Hi team, 
I moving this here since the contributor is reporting an error in the example
best

**Comment by corob-msft** [comment]
@CeciAc, @versat This issue is fixed in the en-us content. I expect the localized content will be updated soon.
