### ISSUE TITLE
Second _mbstok likely should be _mbstok_l

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/cpp-docs#876]
@versat commented on [Fri Mar 22 2019](https://github.com/MicrosoftDocs/cpp-docs.de-de/issues/18)

As the title suggests the second declaration of _mbstok likely should be the declaration for _mbstok_l.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1b3bc926-dabf-9acc-27ed-447707e971df
* Version Independent ID: 00ddc54e-c89f-843c-237a-20ae726d2021
* Content: [strtok, _strtok_l, wcstok, _wcstok_l, _mbstok, _mbstok_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor is reporting an error in the example
best

**Comment by corob-msft** [comment]
@CeciAc, @versat This issue is fixed in the en-us content. I assume the localized content will be updated at some point as well.
