### ISSUE TITLE
R u sure it's 10 elements in the vector?

### ISSUE THREAD

**Issue by Mon-ius** [MicrosoftDocs/cpp-docs#879]
Where: [](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cpp/lambda-expression-syntax.md)

```
#include <algorithm>
#include <iostream>

#include <vector>
using namespace std;
int main(){
    vector<int> v;
    for (int i = 1; i < 10; ++i)
    {
        v.push_back(i);
    }

    int count =0;
    for(auto x:v){
        ++count;
    }
    cout << "Hi cortana, how many elements in this vector???"<<endl << count << endl;
    return 0;
}
```

**Comment by Mon-ius** [comment]
In https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cpp/lambda-expression-syntax.md

**Comment by corob-msft** [comment]
@Mon-ius Yes, that's a mistake. I've poked the right value into the comments, and it should be updated by tomorrow sometime.
