### ISSUE TITLE
Although new warnings are mentioned as being introducted in 15.9, they are not documented!

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/cpp-docs#880]
At the head of the page, the following is included in the list of compiler versions with new warnings....
Visual C++ 2017 version 15.9 19.16.26926.0 

BUT:
The most recent version that has the new warnings documented (below it) is 15.8(!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672bc066-51a0-9778-4c50-98922ebb4b4c
* Version Independent ID: 6263d065-c81a-54f7-a99d-fef41134c872
* Content: [Compiler Warnings by compiler version](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=vs-2017#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warnings-by-compiler-version.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MikeDiack There were no diagnostics added for 15.9. The version number was added to the table for informational purposes. If you switch the documentation version control above the Table of Contents to Visual Studio 2019, you can also see the new diagnostics in VS 2019 previews (so far) - and that there (still) aren't any for 15.9.
