### ISSUE TITLE
Per-UserRedirection Issue

### ISSUE THREAD

**Issue by akeamwoods** [MicrosoftDocs/cpp-docs#882]
Changing  Per-UserRedirection to Yes caused an issue for me where I was unable to find my Poly Ctl in the Test Container. Changing  Per-UserRedirection back to No seemed to fix the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b6f074-8d33-8f93-6555-f7d559936fee
* Version Independent ID: 1edf1754-026c-dade-898b-76a42d6363c7
* Content: [Creating the Project (ATL Tutorial, Part 1)](https://docs.microsoft.com/en-us/cpp/atl/creating-the-project-atl-tutorial-part-1?view=vs-2017#feedback)
* Content Source: [docs/atl/creating-the-project-atl-tutorial-part-1.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl/creating-the-project-atl-tutorial-part-1.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@akeamwoods I'm not able to repro this in VS2019. Which version of VS were you using?
