### ISSUE TITLE
ComPtr::ComPtr (third version, taking a raw pointer) doesn't specify ownership semantics

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#886]
Is the given pointer assumed to be owned, and the ownership transferred, or does ComPtr::ComPtr call AddRef to acquire its own?

These things need to be specified every single time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c769cdb9-ab7c-77bd-16b7-8bb686169eff
* Version Independent ID: ff913b70-328c-9d9e-c7ec-ba942db726b1
* Content: [ComPtr Class](https://docs.microsoft.com/en-us/cpp/windows/wrl/comptr-class?view=vs-2019#feedback)
* Content Source: [docs/windows/wrl/comptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/wrl/comptr-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@TheJCAB fixed doc should appear by July 29. Thanks!
