### ISSUE TITLE
Rule of 5

### ISSUE THREAD

**Issue by JVApen** [MicrosoftDocs/cpp-docs#888]
Not talking about the rule of 5 leads to bugs as strings get moved and copied and as a result the destructor will do a double delete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9524c1-6a81-93c1-ff4d-bc53f6903ffa
* Version Independent ID: 24871971-a1e9-807a-192e-6a2473289283
* Content: [Destructors (C++)](https://docs.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=vs-2017#feedback)
* Content Source: [docs/cpp/destructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/destructors-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mt3d** [comment]
@corob-msft I think we can close this issue by writing a small Robust Programming section like the one in [this article](https://docs.microsoft.com/en-us/cpp/cpp/move-constructors-and-move-assignment-operators-cpp?view=vs-2019#robust-programming). I can write it if you agree with me.

**Comment by corob-msft** [comment]
@mt3d 
That's not a bad suggestion. We'd be happy to consider such a thing. 
@mikeblome for awareness.

**Comment by mikeblome** [comment]
yes great idea!
