### ISSUE TITLE
std::variant

### ISSUE THREAD

**Issue by JVApen** [MicrosoftDocs/cpp-docs#890]
Union is useful, however, by default one should first consider std::variant as it automates things like calling the right destructor. This ain't even mentioned here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a72b499a-3b65-4005-32dd-a6be9100a975
* Version Independent ID: aaa2c0c5-677c-4fb6-cca8-9d4a7aa9122f
* Content: [Unions](https://docs.microsoft.com/en-us/cpp/cpp/unions?view=vs-2017)
* Content Source: [docs/cpp/unions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Thanks @JVApen you are totally correct. I have added note to this effect. Should be visible July 16. We don't have a topic for std::variant yet but it's on our backlog. We're typing as fast as we can!
