### ISSUE TITLE
studio.h ain't c++

### ISSUE THREAD

**Issue by JVApen** [MicrosoftDocs/cpp-docs#891]
Using the header studio.h ain't c++, one should use cstdio instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9524c1-6a81-93c1-ff4d-bc53f6903ffa
* Version Independent ID: 24871971-a1e9-807a-192e-6a2473289283
* Content: [Destructors (C++)](https://docs.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=vs-2017#feedback)
* Content Source: [docs/cpp/destructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/destructors-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@JVApen thanks for the feedback! It looks like this has been fixed.

**Comment by JVApen** [comment]
@mikeblome: I still see the issue, same for string.h

**Comment by mikeblome** [comment]
@JVApen I see no instance of studio.h on this page: https://docs.microsoft.com/en-us/cpp/cpp/destructors-cpp?view=vs-2019

**Comment by mikeblome** [comment]
@JVApen nevermind I see now. Fixing and should appear tomorrow.
