### ISSUE TITLE
stdafx.h

### ISSUE THREAD

**Issue by JVApen** [MicrosoftDocs/cpp-docs#892]
Please don't use stdafx.h in examples, it is really unclear what this all includes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a72b499a-3b65-4005-32dd-a6be9100a975
* Version Independent ID: aaa2c0c5-677c-4fb6-cca8-9d4a7aa9122f
* Content: [Unions](https://docs.microsoft.com/en-us/cpp/cpp/unions?view=vs-2017)
* Content Source: [docs/cpp/unions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@JVApen agreed. We have a work item on our backlog to remove all unnecessary #includes for precompiled headers. The project template for console applications no longer uses them either.

**Comment by mikeblome** [comment]
@JVApen thanks! fixed. should be visible by 05-07.
