### ISSUE TITLE
Thanks a lot this article versy helpful for me

### ISSUE THREAD

**Issue by WinHtut** [MicrosoftDocs/cpp-docs#894]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d30debb1-87f9-1210-a381-8da0aa9ebbd4
* Version Independent ID: 1007144b-0e72-4f6b-a4f5-5a7ac41df817
* Content: [Enumerations (C++)](https://docs.microsoft.com/en-us/cpp/cpp/enumerations-cpp?view=vs-2017)
* Content Source: [docs/cpp/enumerations-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/enumerations-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
:)
