### ISSUE TITLE
What most people are really here to see:

### ISSUE THREAD

**Issue by BobStein** [MicrosoftDocs/cpp-docs#895]
scanf Type Field Characters - THE LETTERS - https://docs.microsoft.com/en-us/cpp/c-runtime-library/scanf-type-field-characters

Format Specification - THE SYMBOLS - https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-fields-scanf-and-wscanf-functions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d24fd8-1416-c6b9-dc3d-1d0e2478c081
* Version Independent ID: 647f7442-93d7-7791-e2d2-ef0470e074ba
* Content: [sscanf, _sscanf_l, swscanf, _swscanf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sscanf-sscanf-l-swscanf-swscanf-l?view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/reference/sscanf-sscanf-l-swscanf-swscanf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/sscanf-sscanf-l-swscanf-swscanf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@BobStein apologies for delayed response. I have added links to the suggested topics. Thanks! Should be visible in a day or so.
