### ISSUE TITLE
C4510 example does not trigger C4510

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#897]
If I copy the example from [C4510 description](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4510?view=vs-2017#feedback) into [godbolt](https://godbolt.org/z/XkLYYm) I do not get the warning. Instead I get C4623 with a different description than the one in the help. Any ideas why that is? Is 4510 deprecated and 4623 now has a broader scope? If 4510 is still a valid error is there an example on how to trigger it?

[Stackoverflow examples](https://stackoverflow.com/questions/934854/how-to-disable-warnings-4510-and-4610-from-stdlist-class) that I found are also [not triggering C4510](https://godbolt.org/z/a-Z7di).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9940a6e9-7b4c-301b-2f62-bea6649bc0c1
* Version Independent ID: e33ade42-f518-3fbb-dd87-b4f45635d157
* Content: [Compiler Warning (level 4) C4510](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4510?view=vs-2017#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4510.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4510.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tiagomacarios I've noticed this; it might be an issue for C4511, C4512, and C4513 as well. I've got a question in to the compiler team about it, but the initial reaction is puzzlement.

**Comment by tiagomacarios** [comment]
@corob-msft Any updates?

**Comment by corob-msft** [comment]
Sure. While it might be possible to generate this error, since it still has a code path, we couldn't figure out how to get it to fire instead of 4623. The code was last touched before the VS 2017 release. I'll pull the example at some point; for now, it's safe to ignore.

**Comment by corob-msft** [comment]
[Compiler Warning (level 4) C4510](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4510) updated.
