### ISSUE TITLE
difference between SDI and MDI Application with pictures

### ISSUE THREAD

**Issue by ShantanuKarIn** [MicrosoftDocs/cpp-docs#898]
Here is one link explaining the difference with pictures of SDI and MDI application http://www.equestionanswers.com/vcpp/sdi-and-mdi-application.php

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d293ba-e18f-074a-8baf-a11d02b2edf2
* Version Independent ID: 97b1e75a-1aee-addb-ff43-57f856a455d6
* Content: [SDI and MDI](https://docs.microsoft.com/en-us/cpp/mfc/sdi-and-mdi?view=vs-2017#feedback)
* Content Source: [docs/mfc/sdi-and-mdi.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/sdi-and-mdi.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Closing - not a doc issue.
