### ISSUE TITLE
How to run these makefiles?

### ISSUE THREAD

**Issue by goodandrewsoft** [MicrosoftDocs/cpp-docs#900]
How to run these makefiles?
How make `MyApp.exe.manifest`?

> If this script is run unchanged with Visual C++, it successfully creates MyApp.exe. It also creates the external manifest file MyApp.exe.manifest, for use by the operating system to load dependent assemblies at runtime.

What you mean `with Visual C`? This is command line scenario - doesnt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d235826-020d-09c6-1984-9491524debf6
* Version Independent ID: 6c3ca9ab-2589-07af-39c5-f14e01b5ac4a
* Content: [How to: Embed a Manifest Inside a C/C++ Application](https://docs.microsoft.com/en-us/cpp/build/how-to-embed-a-manifest-inside-a-c-cpp-application?view=vs-2017)
* Content Source: [docs/build/how-to-embed-a-manifest-inside-a-c-cpp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-embed-a-manifest-inside-a-c-cpp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@goodandrewsoft 
Sometimes we don't have a lot of time available to look at issues, so sorry about taking a long time to get to this.

This article only applies to apps that you build by using NMAKE. If you're not using NMAKE, this doesn't apply to you. If you use the Visual Studio IDE to build, the manifest is embedded automatically.

The reference to Visual C++ means the C++ compiler toolset that comes with Visual Studio. It includes a makefile tool called [NMAKE](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference). NMAKE can read the build instructions in makefiles. By convention, makefiles are named *makefile.mak* and are located in the same folder as the source files that they build. The first two example files are the makefile.mak files for building MyApp.exe and MyLibrary.dll. You would build them by calling NMAKE on the command line. In this case, it doesn't need any options. If you use the default name for the makefile, NMAKE builds the default target automatically.

In this example, the manifest files are generated as part of the build process. You don't have to create them separately.
