### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by BigGuy573** [MicrosoftDocs/cpp-docs#902]
Thanks, I am glad to be a part of the workspace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8649ec5-09cf-8157-8bbb-f71dc329b669
* Version Independent ID: d991cbe7-79f0-a43d-5331-f16e9632deab
* Content: [Preprocessor Directives](https://docs.microsoft.com/en-us/cpp/preprocessor/preprocessor-directives?view=vs-2017#feedback)
* Content Source: [docs/preprocessor/preprocessor-directives.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/preprocessor-directives.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
:)
