### ISSUE TITLE
solution presented is not working

### ISSUE THREAD

**Issue by siliconvoodoo** [MicrosoftDocs/cpp-docs#905]
suggested fix doesnt work. 1: there is no Advanced Save Options. (it's hidden under Save As -&gt; small arrow)
2: Even after save in UTF-8 it still complains. `blabla...current code page (932). Save the file in Unicode...`
Try to add /utf-8 then it's even worse "warning C4828: The file contains a character starting at offset 0x3eaf that is illegal in the current source character set (codepage 65001)."
Finally what indeed does work is save with signature (I imagine this means with BOM) + add /utf-8 option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f677989c-03ac-f741-48f5-c5924441a7f5
* Version Independent ID: 16584d74-1a02-22b4-14ed-355371fbc148
* Content: [Compiler Warning (level 1) C4819](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=vs-2017#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4819.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4819.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@siliconvoodoo 
Thanks for bringing this to our attention. There's more than one way to fix this issue, so the instructions have been expanded. Visual Studio 2019 even automates some of the process for you.
