### ISSUE TITLE
LOST SITE: https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support

### ISSUE THREAD

**Issue by sudeepku** [MicrosoftDocs/cpp-docs#907]
Issue reported by @pzyzhu  at https://github.com/MicrosoftDocs/feedback/issues/1333

Describe the bug
website "https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support" is lost

To Reproduce

goto https://docs.microsoft.com/en-us/cpp/build/unwind-data-for-exception-handling-debugger-support
See error
Expected behavior
404

Desktop (please complete the following information):

OS:windows 7 x64
Browser chrome

**Comment by mikeblome** [comment]
@sudeepku looks like that content moved here: https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=vs-2019

I have added a redirect for it which should go live later today.

**Comment by corob-msft** [comment]
Appears fixed.
