### ISSUE TITLE
Remarks section contains the same sentence twice.

### ISSUE THREAD

**Issue by rbosa** [MicrosoftDocs/cpp-docs#910]
2nd copy seems superfluous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a0bdc7-da2e-7d4d-2cd9-cc1de90ceda5
* Version Independent ID: 1f99051d-52b7-e637-da49-8b5cc3b76901
* Content: [Platform::Array Class](https://docs.microsoft.com/en-us/cpp/cppcx/platform-array-class?view=vs-2017)
* Content Source: [docs/cppcx/platform-array-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/platform-array-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@rbosa 
It certainly does seem superfluous. The fix should appear in about a week; we're waiting for a publication embargo to lift for Build.
