### ISSUE TITLE
CmdResponseType

### ISSUE THREAD

**Issue by Murzinio** [MicrosoftDocs/cpp-docs#913]
It should be specified that the enum CmdResponseType is defined inside of CFtpConnection, which is not obvious from the documentation and it can take a while to find it while trying to call CFtpConnection::Command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6914e5e-512d-c780-c3ab-6dd71d63dfd0
* Version Independent ID: 5a474f74-1c0a-16fd-8577-995f9af9df29
* Content: [CFtpConnection Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cftpconnection-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cftpconnection-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cftpconnection-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
thanks @Murzinio I have updated the document for Aug 30 publishing
