### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by otyshev** [MicrosoftDocs/cpp-docs#919]
used in a contant expression -&gt; used in a constant expression

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c017cf85-7a65-0bbb-b5e1-c6e5ca93ee3b
* Version Independent ID: 78f89035-bc4b-61bc-629d-50307b539b83
* Content: [constexpr lambda expressions in C++](https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-constexpr?view=vs-2017#feedback)
* Content Source: [docs/cpp/lambda-expressions-constexpr.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/lambda-expressions-constexpr.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@otyshev Fixed. Thanks for pointing it out.
