### ISSUE TITLE
/Gm is not the default anymore for debug builds

### ISSUE THREAD

**Issue by kkoehne** [MicrosoftDocs/cpp-docs#920]
&gt; By default, a project build enables the /Gm compiler option (incremental builds) for debug builds

I'm pretty sure this is not the default anymore since quite some time (Visual Studio 2013?). /Gm as an option is deprecated at least in Visual Studio 2019 ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba7546b8-099c-d8a0-8ef5-17d3b05ee97e
* Version Independent ID: 617dea74-b387-7a84-806e-9e898fbab459
* Content: [/MP (Build with Multiple Processes)](https://docs.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=vs-2019#feedback)
* Content Source: [docs/build/reference/mp-build-with-multiple-processes.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/mp-build-with-multiple-processes.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kkoehne This and other references to `/Gm` have been either deleted or updated to indicate it's deprecated, as appropriate. Thanks for bringing it to our attention.
