### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by JayMuller** [MicrosoftDocs/cpp-docs#923]
Hello
I've just downloaded Visual Studio 2019, and tried the "CalculatorTutorial".  The "Hello World" part worked just fine, but I get a ton of errors (too many to type out, and the list itself appears immune to "copy and paste") when I simply copy and past the code:

 // CalculatorTutorial.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>

using namespace std;

int main()
{
    cout << "Calculator Console Application" << endl << endl;
    cout << "Please enter the operation to perform. Format: a+b | a-b | a*b | a/b"
        << endl;
    return 0;
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu
// Tips for Getting Started:
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file

Something a novice programmer would take for granted must be escaping my perception, since I am beneath even that level of expertise.  Where should I start?  Thank you for any time and consideration.
Jay Muller

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JayMuller I'm sorry you're having a hard time here. Can you tell me what the first error reported is?

**Comment by JayMuller** [comment]
Thank you for the prompt reply!  I get the following:
CS1024 Preprocessor directive expected
CS1041
CS1514
CS1513
CS0116
CS0103 x 4
CS0201 x 2
I’m going to be tutored by an experienced coder over the summer and wanted to get a head start learning the basics to the extent possible.  Any assistance is greatly appreciated!
Thanks again,
Jay

**Comment by corob-msft** [comment]
Okay, that's unexpected. Those errors are from the C# compiler, not the C++ compiler. I wouldn't expect that to even be possible in the same project that compiles a C++ version of "Hello World", even if you changed the file extension to .cs in between. 

Two possibilities suggest themselves. The first is, you were in fact trying to build [the C# version of the tutorial](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019), but landed on the C++ docs by mistake half-way through. If that's the case, follow the link back to the right tutorial, and you should be okay.

The second possibility is, you meant to do the C++ tutorial, but chose the C# Console App project template by accident when you created your CalculatorTutorial project. Unfortunately, this might be an easy error to make. Basically, you need to make sure the template you choose in the [Create your app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019#create-your-app-project) section of the tutorial is the **Console App** that has the **C++**, **Windows**, and **Console** tags. If it says **C#** or **.NET** in it anywhere, it's not the right template. If the C++ version of the template isn't in the list, then you need to [install the "Desktop Development with C++" workload in the Visual Studio Installer](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2019).

Please let me know if either solution applies; the 2019 tutorial is a new document that gets seen by a lot of people, and I want to shake out the bugs early.

**Comment by JayMuller** [comment]
It was the second possibility.  Apparently, the default console is C# and I failed to notice the drop down menu above, allowing me to switch to C++, before proceeding.  It reminds me of the time I brought my newly built PC home and couldn’t power it up because I was unaware of a master power switch on the back of the tower (embarrassing).  Thank you for your assistance
Jay

**Comment by corob-msft** [comment]
By sometime tomorrow (around noon Pacific time) the article will be republished with a note about how to choose the right template.
