### ISSUE TITLE
_MSC_VER for VS2019 => 1920

### ISSUE THREAD

**Issue by bcldemjen** [MicrosoftDocs/cpp-docs#926]
Visual Studio 2019 version 16.0: _MSC_VER is 1920.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined Macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Update is live.
