### ISSUE TITLE
Clarify whether /Zc:referenceBinding is affected by /permissive- or not

### ISSUE THREAD

**Issue by k15tfu** [MicrosoftDocs/cpp-docs#927]
On /Zc:referenceBinding page, it's said that (https://docs.microsoft.com/en-us/cpp/build/reference/zc-referencebinding-enforce-reference-binding-rules)
> The /permissive- compiler option implicitly sets this option

but on /permissive- page it's said nothing about it (https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance).

**Comment by corob-msft** [comment]
@k15tfu The product regularly outpaces the documentation. It's safe to assume that `/permissive-` sets every relevant option to standard conforming, unless explicitly specified otherwise, or if it requires an additional switch, such as `/experimental`. Any conformance option you'd like to turn off should be specified explicitly after the `/permissive-` option on the command line, even if it's not mentioned in the `/permissive-` documentation as being set.

**Comment by k15tfu** [comment]
@corob-msft,

I'm following an opposite goal, I want to do everything in accordance with the standard. Therefore I specify /permissive- and add every /Zc option that should be turned on explicitly.

So right now /permissive- page doesn't mention /Zc:referenceBinding option so it stays unclear whether should I pass it manually or not.

**Comment by corob-msft** [comment]
@k15tfu While as far as I know, there's no harm in adding all the `/Zc` conformance switches to the command line in addition to `/permissive-`, I wouldn't expect behavior changes as a result. The `/Zc` switches enable a subset of the behaviors enabled by the `/permissive-` switch, and are not a complete substitute. They exist primarily to enable backward-compatibility for source code that relied on some common Microsoft-specific compiler behaviors. The `/permissive-` switch also enables other conformance behaviors that do not have `/Zc` switches. These other conformance behavior changes often express themselves as new warning or error messages, including warnings that are off-by-default when `/permissive-` is not set, in code that relies on the non-conforming behavior.

**Comment by corob-msft** [comment]
Updates are live.

**Comment by k15tfu** [comment]
@corob-msft Thanks!
