### ISSUE TITLE
scanf documentation omits the hh size prefix

### ISSUE THREAD

**Issue by mwinterb** [MicrosoftDocs/cpp-docs#931]
From https://en.cppreference.com/w/cpp/io/c/fscanf
The hh size modifier for reading an integer into a signed char or unsigned char isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99959836-38d3-f91f-864a-5445112c8cf1
* Version Independent ID: fdf9a35f-4b2c-c557-25be-32adfc75586b
* Content: [scanf Width Specification](https://docs.microsoft.com/en-us/cpp/c-runtime-library/scanf-width-specification?view=vs-2019)
* Content Source: [docs/c-runtime-library/scanf-width-specification.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/scanf-width-specification.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mwinterb 
I'm afraid this issue has been on the backlog for over three years, and never bubbled to the top. Expect action, but not necessarily soon.
