### ISSUE TITLE
Missing linker warning LNK4286

### ISSUE THREAD

**Issue by 1ftskank** [MicrosoftDocs/cpp-docs#933]
There is no information about the Linker Tools Warning LNK4286 (For example "warning LNK4286: symbol 'xmlFree' defined in 'libExample.lib(globals.obj)' is imported by 'libAnotherExample.lib(xml.obj)'")

**Comment by 1ftskank** [comment]
For the page titles "Linker Tools Errors and Warnings" - https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-errors-and-warnings?view=vs-2019

**Comment by corob-msft** [comment]
@1ftskank Thanks for pointing this out. I'll follow up with the linker team to find out more.

**Comment by corob-msft** [comment]
Error message is live now at [Linker Tools Warning LNK4286](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4286?view=vs-2019).

**Comment by 1ftskank** [comment]
Thank you for moving so quickly on this!
