### ISSUE TITLE
Not updated for Visual Studio 2019

### ISSUE THREAD

**Issue by bkuhns** [MicrosoftDocs/cpp-docs#936]
I'd like to see what C++ language conformance improvements were done for Visual Studio 2019, but it appears the page hasn't been updated for 2019. For example, there was mention in a VC++ blog post that the &lt;=&gt; "spaceship operator" has some initial support, but it's not even a language line item on this documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Visual C++ Language Conformance](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019#feedback)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@bkuhns it is on our backlog to fix update that page soon. For you can see what is new for RTM on this page: https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019
Be sure to set the version selector in the upper left to 2019.

**Comment by mikeblome** [comment]
topic has been updated
