### ISSUE TITLE
std::sample() is missing from the <algorithm> docs

### ISSUE THREAD

**Issue by jordanlkirk99** [MicrosoftDocs/cpp-docs#940]
Listed as available:
https://devblogs.microsoft.com/cppblog/announcing-msvc-conforms-to-the-c-standard/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da29b34b-b0c3-e92f-021d-c13ea4c28a65
* Version Independent ID: 6b5bd9c3-a759-65d1-d209-a3517a0dce75
* Content: [&lt;algorithm&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/algorithm?view=vs-2019#feedback)
* Content Source: [docs/standard-library/algorithm.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/algorithm.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@jordanlkirk99 thanks. This is on our backlog to do soon. I'll leave this open until its updated.

**Comment by mikeblome** [comment]
it's documented now. @jordanlkirk99 thanks!
