### ISSUE TITLE
Template recursion limit not specified

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#942]
The template depth limit isn't specified, nor is any switch to change it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b383e454-da7d-fb29-3fb0-1c66b327a8c6
* Version Independent ID: fa882068-fda0-5995-7bd9-9a587a924409
* Content: [Compiler Limits](https://docs.microsoft.com/en-us/cpp/cpp/compiler-limits?view=vs-2019)
* Content Source: [docs/cpp/compiler-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/compiler-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Ma-XX-oN 
As far as I know, CL.exe does not have a documented switch to limit template recursion depth. If you'd like to suggest one, I recommend you bring the issue up in the Microsoft C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html), where there are buttons to report a problem or suggest a feature.
Apparently, if there is a template recursion depth limit, [you are likely to run out of heap space before you hit it](https://developercommunity.visualstudio.com/content/problem/17316/vs2017-variable-template-infinity-recursion-make-c.html). I'll ask if there's an actual limit value.

**Comment by corob-msft** [comment]
Closing, as the limit is unspecified but large enough that it can't be reached in practice.
