### ISSUE TITLE
This was handled, as usual, in an infuriating way

### ISSUE THREAD

**Issue by ConceptJunkie** [MicrosoftDocs/cpp-docs#944]
Our application is built with Visual Studio 2015 and packaged with InstallShield.  The InstallShield project hasn't changed in 2 and a half years, yet now we get ridiculous error messages when installing on Windows 10 because the system thinks 2015 needs to be installed, but apparently it doesn't.

So now it seems our only option is to switch to installing the 2017 Redistributable instead, and we have no idea if that will cause compatibility problems, or what.  We literally need to alter our product, which is just about to ship, because Microsoft's own components act in an incoherent way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcccbfe4-34d9-67cb-efbb-6c15ff35b38e
* Version Independent ID: cc082cbf-a967-6709-f3ef-190e78cf84e9
* Content: [C++ Binary Compatibility between Visual Studio 2015 and Visual Studio 2017](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019#feedback)
* Content Source: [docs/porting/binary-compat-2015-2017.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/binary-compat-2015-2017.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@ConceptJunkie I'm sorry to hear you are experiencing these issues. I suggest you raise the issue on the [Visual Studio developer community](https://developercommunity.visualstudio.com/spaces/62/index.html) site and see if anyone can suggest a solution or workaround. The product team monitors that site and is typically very responsive to feedback from customers; this repo is solely for documentation and we have to describe the product as it is, not as it should be.

**Comment by corob-msft** [comment]
Closing since this doesn't seem like an issue documentation can fix.
