### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lexboss93** [MicrosoftDocs/cpp-docs#948]
[Here ](cpp-docs/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)it says:
"...from the correct Debug or **Retail** locations for your configuration."
I believe it should be **Release**.

**Comment by corob-msft** [comment]
@lexboss93 
You're right. Among Windows programmers, "Retail" is a synonym for "Release" in common usage, but not the right word to use here.

**Comment by corob-msft** [comment]
The fix should appear in a week or so, after the publishing embargo for the Build conference is lifted.
