### ISSUE TITLE
Default Click

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftDocs/cpp-docs#949]
It should be documented that setting Default Click property to false (which is also a variable in the class) causes the button to show the menu when you click anywhere on the button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aaeebc8-4feb-6add-c508-569f8ec7f149
* Version Independent ID: 1e215009-3826-71fe-737c-18988f2165da
* Content: [CMFCMenuButton Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfcmenubutton-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cmfcmenubutton-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmfcmenubutton-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@ajtruckle added missing member m_bDefaultClick along with your remark. Thanks! Should be visible July 15.
