### ISSUE TITLE
wait(250) function could't  found

### ISSUE THREAD

**Issue by flylinfan** [MicrosoftDocs/cpp-docs#951]
wait(250) function could't found
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08dad894-574b-ecc0-5fcb-4d5ad71b17d6
* Version Independent ID: 5620dba0-f69f-9646-955b-63e2b1e867f0
* Content: [Cancellation in the PPL](https://docs.microsoft.com/en-us/cpp/parallel/concrt/cancellation-in-the-ppl?view=vs-2019)
* Content Source: [docs/parallel/concrt/cancellation-in-the-ppl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/cancellation-in-the-ppl.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@flylinfan 
It looks like the example is missing a header:
`#include <concrt.h>`
Also, the lambda capture list around line 30 should have
`	auto t = create_task([&]`
to pick up the reference to `token`.
We will get around to updating the topic in a while.

**Comment by corob-msft** [comment]
The fixed file should appear in about a week, after the publishing embargo for Build is lifted.
