### ISSUE TITLE
Remark about when #pragma make_public is needed not accurate

### ISSUE THREAD

**Issue by Stannieman** [MicrosoftDocs/cpp-docs#952]
Could it be that this part "native type in the signature of a public function in a type with public assembly visibility" is not the only case where this applies?
I have the following scenario:
* Project P1 has a public class C1 with protected member variable M1 of a native type NT1.
* Project P2 references P1 and has an internal class C2 : C1.
* Whenever I try to access C1's protected NT1 from derived class C2 it results in the same error. NT1 does not even appear in any variable or method signature. Just accessing NT1 from inside a function body is enough.

Is this a bug or expected behavior which is not described here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b61146d5-c037-10b6-dcea-baf3493835fe
* Version Independent ID: d80acc01-0f8b-9b0d-5cd2-0d336be72be6
* Content: [make_public](https://docs.microsoft.com/en-us/cpp/preprocessor/make-public?view=vs-2019)
* Content Source: [docs/preprocessor/make-public.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/make-public.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Stannieman apologies for delayed response. If you ask this question on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) someone should be able to answer it for you.
