### ISSUE TITLE
The comment in the example is wrong for the result of %= 

### ISSUE THREAD

**Issue by rsn8887** [MicrosoftDocs/cpp-docs#955]
The example is wrong.

The result of 6 %= 3 is 3, and not 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb7e11f-cd0d-5e4d-fcf2-6b1060b7586c
* Version Independent ID: 90046753-8233-1a30-09d8-126f8350b3fc
* Content: [Assignment Operators](https://docs.microsoft.com/en-us/cpp/cpp/assignment-operators?view=vs-2019)
* Content Source: [docs/cpp/assignment-operators.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/assignment-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@rsn8887 
A careful reading of the example shows that `a` has been modified to hold 9 at that point in the execution, and `b %= 9` is 6, so 6 is the correct result.

**Comment by rsn8887** [comment]
Ah I was a bit too quick. Thanks for taking a look.
