### ISSUE TITLE
"Desktop Bridge" link gives 404

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/cpp-docs#960]
The following URL is no longer valid; I have not yet found its new location (if any).

https://docs.microsoft.com/en-us/windows-uwp/porting/desktop-to-uwp-root.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a36c4ec-b8f3-0202-907e-46fe88b70a9b
* Version Independent ID: 224f3c4d-1db1-3ba3-f47a-c8a042e3ea3a
* Content: [Desktop Applications (Visual C++)](https://docs.microsoft.com/en-us/cpp/windows/desktop-applications-visual-cpp?view=vs-2019)
* Content Source: [docs/windows/desktop-applications-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/desktop-applications-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@wjk thanks for calling this to our attention! The correct link is https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root. I have updated the topic and the fix should appear by 04-22.
