### ISSUE TITLE
Another example of the issue

### ISSUE THREAD

**Issue by yeroc-sebrof** [MicrosoftDocs/cpp-docs#961]
I came across this issue in an 'std::ostream& operator &lt;' I was writing where it was in a header file and it had no immediate use within said file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e3f4058-9a81-d1d1-dbde-7622d2569d64
* Version Independent ID: 09efa20f-df41-b5ba-4158-a39a2a9553a1
* Content: [Linker Tools Error LNK2005](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2005)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2005.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2005.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yeroc-sebrof 
Did you declare your operator function `inline`? If not, and the operator definition is in the header, this error is likely, as described in the second bullet point.

**Comment by yeroc-sebrof** [comment]
Declaring does seem to solve the issue that I was having so I suppose I didn't understand the example well enough to apply it to my circumstance. Thank!
