### ISSUE TITLE
Links to "ODBC Error Codes" and "SQLError" do not work

### ISSUE THREAD

**Issue by Nijegorodov** [MicrosoftDocs/cpp-docs#971]
Links to "ODBC Error Codes" and "SQLError" do not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b85c1c24-3dbb-5631-69f0-7439b9cd3a2e
* Version Independent ID: 86daf7d8-a1bb-c6de-872e-1b0a01712e10
* Content: [CDBException Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cdbexception-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cdbexception-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cdbexception-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@Nijegorodov Due to a publishing embargo for the Build conference, this fix will appear sometime around May 6 or 7.

**Comment by Nijegorodov** [comment]
Thank you Colin!
