### ISSUE TITLE
GetOutputTextExtent() incorrectly documented.

### ISSUE THREAD

**Issue by SwissFrank** [MicrosoftDocs/cpp-docs#972]
GetOutputTextExtent() documentation says that if size is -1 then length will be calculated.  In fact it calls GetTextExtentPoint32() which doesn't seem to have this feature.

GetOutputTextExtent() is overloaded, however, by a second version that simply doesn't take size, and DOES calculate it.

The other *****TextExtent() documentation may have the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f69fff3-a379-5622-f69e-6684e6ab1f77
* Version Independent ID: a7da136a-63c3-a7fc-7a02-ca33cc3d2737
* Content: [CDC Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cdc-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(AFXWIN%2FCDC%3A%3AGetOutputTextExtent)%3Bk(CDC%3A%3AGetOutputTextExtent)%3Bk(GetOutputTextExtent)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017#feedback)
* Content Source: [docs/mfc/reference/cdc-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cdc-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@SwissFrank 
This looks like may have been a copy and paste error when the topic was written. I noted issues in GetOutputTabbedTextExtent, GetOutputTextExtent, GetTabbedTextExtent, TabbedTextOut, and a similar but unrelated issue in GrayString.
