### ISSUE TITLE
MsHTML.h generates this error

### ISSUE THREAD

**Issue by JayRTurner99** [MicrosoftDocs/cpp-docs#975]
\Windows Kits\10\Include\10.0.17763.0\um\MsHTML.h(43244): warning BK4504: file contains too many references; ignoring further references from this source

This is a Microsoft file that cannot be edited by the user. Please correct the file or advise how to remove the warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368fe708-accd-c31f-89f0-10f11264a5dc
* Version Independent ID: 1971168a-3a07-730c-9c89-a2a8b1a8ac8b
* Content: [BSCMAKE Warning BK4504](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/bscmake-warning-bk4504?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(BK4504)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/tool-errors/bscmake-warning-bk4504.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/bscmake-warning-bk4504.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JayRTurner99 
The best way to turn off this warning is to not generate a .BSC browse information file at all. None of the Visual Studio tools make use of it; BSCMake is available for some third-party analysis tools to use, though I don't know which ones. If you're using Visual Studio and want to turn off browse information, go to the **Project Properties** page for your project, open **Configuration Properties** > **C/C++** > **Browse Information** and set **Enable Browse Information** to **No**. On the compiler command line, this is the equivalent of leaving out the [/FR](https://docs.microsoft.com/en-us/cpp/build/reference/fr-fr-create-dot-sbr-file) option.

Assuming you do need a browse information file for some reason, you can exclude the system headers by using the [/Es](https://docs.microsoft.com/en-us/cpp/build/reference/bscmake-options) option on the BSCMake command line. Alternatively, you can exclude MsHTML.h specifically by using the [/Ei](https://docs.microsoft.com/en-us/cpp/build/reference/bscmake-options) option. In Visual Studio, these can be set in the **Project Properties** page for your project. Go to **Configuration Properties**  > **Browse Information** > **Command Line** and add `/Es` in **Additional Options**.

Finally, if you do in fact want a browse information file for the symbols in MsHTML.h, don't get your hopes up. The BSCMake utility is in maintenance mode, and that means it only gets critical bug fixes, not new features added, such as expanded symbol capacity. That doesn't mean you can't ask, though. To do that, in Visual Studio, use the  **Help** > **Send Feedback** > **Report a Problem** menu item. Or, on the web, go to the Microsoft C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) page, where there are buttons to report a problem or suggest a feature. Good luck.
