### ISSUE TITLE
multimon.h generates this error

### ISSUE THREAD

**Issue by JayRTurner99** [MicrosoftDocs/cpp-docs#976]
Windows Kits\10\Include\10.0.17763.0\um\multimon.h(185): warning C4996: 'GetVersionExA': was declared deprecated

This is a Microsoft file and cannot be edited by the user. Please correct the file or advise on how to remove this warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc13c03-89ae-9db9-46f9-634d611e0960
* Version Independent ID: d827f52d-303d-89fe-4c38-c038c7e0b253
* Content: [Compiler Warning (level 3) C4996](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C4996);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-3-c4996.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-3-c4996.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JayRTurner99 
This looks like a bug in the multimon.h header. [I have a feeling it's not going to be fixed](https://devblogs.microsoft.com/oldnewthing/20091207-00/?p=15763). Odds are good - really, really good - that you don't need the header. However, if you've got some creaky, archaic code that requires it, and you can't touch that code for some reason, you can at least suppress the warning by wrapping the place where the header file is included by using some warning pragmas. The instructions are right here in this topic, in the [To turn the warning off without fixing the issue](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?&view=vs-2019#to-turn-the-warning-off-without-fixing-the-issue) section. It could look something like this:

```cpp
#pragma warning(push)
#pragma warning(disable:4996)
#include <multimon.h>
#pragma warning(pop)
```

Closing, as this isn't a documentation issue.
