### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/cpp-docs#986]
You say above:

"In the project properties for the UWP project, in the Linker section..."  I dont see Linker section anywhere in my UWP project?

then you say:
"Add an include statement to reference the header file to your pch.h in the UWP project..."  I dont see anywhere pch.h in my UWP project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd9724a-4824-5784-83a7-acaf9099610a
* Version Independent ID: a93349dd-05fe-f661-e084-b8313a8214f2
* Content: [How to: Use Existing C++ Code in a Universal Windows Platform App](https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019)
* Content Source: [docs/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@dinobu thanks for the feedback. I have clarified the topic. Fix should appear by July 15.
