### ISSUE TITLE
Why not provide links to the documentation of each of the pragmas?

### ISSUE THREAD

**Issue by CodieCodemonkey** [MicrosoftDocs/cpp-docs#987]
eom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb5e224-1e1c-bd82-90bb-74a9bb7882a1
* Version Independent ID: 4b68a1d1-aacf-95b4-640c-b5cb682ffc4d
* Content: [Pragmas](https://docs.microsoft.com/en-us/cpp/c-language/pragmas?view=vs-2019#feedback)
* Content Source: [docs/c-language/pragmas.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/pragmas.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@CodieCodemonkey 
That's a great idea. It's also easy to do, so I'm opening this up for people who want to get their feet wet with [contributing to Docs](https://docs.microsoft.com/en-us/contribute/) in GitHub. 

Use the pencil icon to go to the topic source on GitHub, then use the pencil icon there to start editing the markdown source for the file.

In this case, the entries are all found in a table that looks like this, to start with:
```
|||||
|-|-|-|-|
|**alloc_text**|**data_seg**|**include_alias**|`setlocale`|
```

To turn the table entries into links, you need to find the target first. That part is pretty easy; you can just search in Docs. For example, the topic about the [alloc_text](https://docs.microsoft.com/en-us/cpp/preprocessor/alloc-text?view=vs-2019) pragma is found at `https://docs.microsoft.com/en-us/cpp/preprocessor/alloc-text?view=vs-2019`. 

To turn that into a link, select the part of the URL that starts with `/cpp` up to just before the question mark: 
`/cpp/preprocessor/alloc-text`

Next, edit the entry in the table. Remove the asterisks or tick marks around the entry, and replace them with square brackets:
`[alloc_text]`.

Then, in parentheses, add the portion of the URL you copied earlier:
`[alloc_text](/cpp/preprocessor/alloc-text)`

Repeat this for the rest of the entries, then submit your PR. Bask in contributor glory when your PR is approved and merged.

**Comment by mikeblome** [comment]
fix should appear in 1-2 days
