### ISSUE TITLE
New Form command is not available in VS2019

### ISSUE THREAD

**Issue by alexoparin** [MicrosoftDocs/cpp-docs#994]
There is no support in Visual Studio 2019 in creating New Forms for MFC projects. There's no New Form button, not even CFormView base class is available among other MFC classes from MFC Class Wizard. So, Visual Studio 2019 says: "I don't like CForm and I hate CFormView, 'cause I have no idea what can it do, 'cause guys at Microsoft no longer know how to create a CForm based on CView, 'cause guys at Microsoft are too busy now, the work hard on filling new Windows with (thousand of useless small UWP) apps which must eat the whole power of 26 Intel cores 'cause Windows must not work too fast, otherwise people won't get tired of lags and thus won't ask for a new more expensive OS with even more small and uselasses apps to remind them to feed their cats, 'cause Microsoft bosses do really forget that their biggest revenue source is not food for those cats, but serious businesses with serious guys how still know how to build apps, just buy using CForms and some MFC hacks". That's what VS 20 19 says! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00fa5f5e-55fc-2751-3005-315a7cc117f4
* Version Independent ID: 14b24543-0bdd-e662-d199-6028209f6493
* Content: [Inserting a Form into a Project](https://docs.microsoft.com/en-us/cpp/mfc/inserting-a-form-into-a-project?view=vs-2019)
* Content Source: [docs/mfc/inserting-a-form-into-a-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/inserting-a-form-into-a-project.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@alexoparin Thanks for the feedback. This topic seems out of date. I don't see that Visual Studio 2017 can do this either. However, you can easily derive your view class from CFormView: https://docs.microsoft.com/en-us/cpp/mfc/reference/cformview-class?view=vs-2019. Does that work for you?
